### ISSUE TITLE
Release version 10.0

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#1000]
Let's track the preparation of 10.0 here.

(TBH I wanted to submit issue #1000.)

**Comment by graingert** [comment]
@aaugustin are you no longer using github milestones on this project? https://github.com/aaugustin/websockets/milestones?state=closed&direction=asc&sort=due_date

**Comment by aaugustin** [comment]
Indeed, I stopped using milestones. They didn't really help.

**Comment by aaugustin** [comment]
Pre-requisites:

* [ ] Merge Sans-I/O howto & reference docs #999
* [ ] Update changelog with git history
* [ ] Review private TODO

**Comment by aaugustin** [comment]
From private TODO:

* [x] Add security limits in Sans-I/O HTTP parser — security weakness in new feature = blocking bug
* [ ] Randomize delay before reconnecting (see RFC) — new feature isn't spec-compliant = blocking bug
* [ ] Change first argument of ClientConnection to a WebSocketURI (which requires making it a public API again...) — must stabilize the Sans-I/O API before making it public
* [ ] Make Headers importable from websockets (= add lazy imports for the datastructures module) + review the new API reference for other similar cases

**Comment by aaugustin** [comment]
Done in 13eff12.
