### ISSUE TITLE
Websocket implementation not interoperable with browser client websocket?

### ISSUE THREAD

**Issue by RonaldColyar** [aaugustin/websockets#1003]
I am trying to write a simple websocket server with a matching browser client. The connection is closed prematurely across all popular browsers(chrome,firefox and safari). It closes with a 1005 error , yet I haven't triggered a close event on either side(client/server).

Browser Client(typescript):

```TypeScript

export class Bare{

    connections : Map<string,WebSocket>
    constructor(){
        this.connections = new Map<string,WebSocket>();
    }

    setup_connection(name:string){
        let connection = new WebSocket('ws://localhost:50223');
        this.connections.set(name,connection);

    }
    send_stuff(name:string){
        let connection = this.connections.get(name);
        connection.send("stuff");
    }
}

```
Server(python):

```python

import asyncio
import websockets
import logging
logger = logging.getLogger('websockets')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())

class Main:

    def __init__(self):
        self.host = '127.0.0.1' 
        self.port = 50223

    async def check_declaration(self,websocket,path):
        while True:
            data = await websocket.recv()
            print(data)
            
    def start_server(self):
        loop = asyncio.get_event_loop()
        loop.run_until_complete(
            websockets.serve(self.check_declaration,self.host,self.port,ping_interval=None))
        loop.run_forever()

Main().start_server()

```

Additional information: This client is used via React web framework. I have verified that I can communicate with this server by using the .`onopen` callback assignment to hurry and send some mock data. Shortly after the connection closes if I am not sending consecutive chunks of data. First thing that came to mind was that I would need to ping the server , for the ping interval and then I set the ping interval of the server to None , which still yields the same result. Does the ping_interval only apply for clients that are written in this library?

Other things that I have tried: I tried actually using a mirroring python websocket client , which didn't have the same issue as the browser client.

**Comment by aaugustin** [comment]
websockets is interoperable with browsers.

All spec compliant clients support `ping_interval` without any special action from you, regardless of what client or what server you're using, and I'm not aware of any non-compliant clients where this could be an issue.

Could you bump the logging level to DEBUG? Then you should see which side sends a Close frame first. This will tell you who closes the connection, and then you can figure out why.

**Comment by RonaldColyar** [comment]
I appreciate your quick response and insight I am currently looking into it further: here is the output from the debug level. 

```
server - state = CONNECTING
server - event = connection_made(<_ProactorSocketTransport fd=528>)
server - event = data_received(<476 bytes>)
server < GET / HTTP/1.1
server < Headers([('Host', 'localhost:50223'), ('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0'), ('Accept', '*/*'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Sec-WebSocket-Version', '13'), ('Origin', 'http://localhost:3000'), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Sec-WebSocket-Key', 'PQ1eT0A/6GsmiSVwZVC00A=='), ('DNT', '1'), ('Connection', 'keep-alive, Upgrade'), ('Sec-GPC', '1'), ('Pragma', 'no-cache'), ('Cache-Control', 'no-cache'), ('Upgrade', 'websocket')])
server > HTTP/1.1 101 Switching Protocols
server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'JKfIF4xTNRyDXkqM4jiLRnXAF/Y='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Mon, 28 Jun 2021 08:09:46 GMT'), ('Server', 'Python/3.9 websockets/9.1')])
server - state = OPEN
```

**Comment by RonaldColyar** [comment]
Seems as though the server has no knowledge that the connection is being closed , I think this may be related to browser WebSockets? the above WebSocket client is almost like a mirror of your JS [script](https://github.com/aaugustin/websockets/blob/8446d7e02fb1fa3585d93a66d30811cc6bffbf8c/experiments/authentication/script.js) if you would like to reproduce this without needing typescript or react in your dev environment.

**Comment by lgrahl** [comment]
Would recommend tracing and staring at it in Wireshark. My guess is that this is an issue with your environment. :slightly_smiling_face:

**Comment by RonaldColyar** [comment]
@lgrahl  Exploring what you said about it being an issue with the environment, I got on a ubuntu machine and tried to run the same client and server and got the same result with the server logging on DEBUG level: 

```
server - state = CONNECTING
server - event = connection_made(<_SelectorSocketTransport fd=7 read=idle write=<idle, bufsize=0>>)
server - event = data_received(<454 bytes>)
server < GET / HTTP/1.1
server < Headers([('Host', 'localhost:50223'), ('User-Agent', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0'), ('Accept', '*/*'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate'), ('Sec-WebSocket-Version', '13'), ('Origin', 'http://localhost:3000'), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Sec-WebSocket-Key', 'YG+l23wvzxywtXCTA/K6OA=='), ('Connection', 'keep-alive, Upgrade'), ('Pragma', 'no-cache'), ('Cache-Control', 'no-cache'), ('Upgrade', 'websocket')])
server > HTTP/1.1 101 Switching Protocols
server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'y/kj5OUAcqUlQ2RH71skJOpeGmQ='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Mon, 28 Jun 2021 08:55:49 GMT'), ('Server', 'Python/3.8 websockets/8.1')])
server - state = OPEN



```

**Comment by lgrahl** [comment]
It does perhaps rule out the environment problem. We can't reproduce it because the JS client you posted above doesn't run anything. So, here's a minimal client I wrote and ran for 11m on Firefox 89:

```js
const connection = new WebSocket('ws://localhost:50223');
const sayHi = () => connection.send('hi');
connection.onopen = () => {
  setInterval(sayHi, 5*60*1000);
  sayHi();
};
connection.onmessage = ({data}) => console.log(data);
```

and this is the output of the server you've posted:

```
server - state = CONNECTING
server - event = connection_made(<_SelectorSocketTransport fd=7 read=idle write=<idle, bufsize=0>>)
server - event = data_received(<461 bytes>)
server < GET / HTTP/1.1
server < Headers(...)
server > HTTP/1.1 101 Switching Protocols
server > Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'PcU57EQh3b9JT3OvpLso5YGsERQ='), ('Sec-WebSocket-Extensions', 'permessage-deflate'), ('Date', 'Mon, 28 Jun 2021 10:50:25 GMT'), ('Server', 'Python/3.9 websockets/9.1')])
server - state = OPEN
server - event = data_received(<10 bytes>)
server < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'hi', rsv1=False, rsv2=False, rsv3=False)
hi
server - event = data_received(<10 bytes>)
server < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'hi', rsv1=False, rsv2=False, rsv3=False)
hi
server - event = data_received(<10 bytes>)
server < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'hi', rsv1=False, rsv2=False, rsv3=False)
hi
```

Which is exactly what I'd expect. Maybe there's something odd in your client code?

**Comment by aaugustin** [comment]
FWIW I also suspect it's a problem with the client environment.

I can't rule out entirely that websockets sends something that the browser doesn't like, causing it to terminate the connection. We had one bug like this before, related to the combination of compression and fragmentation. However, given the size of websockets' user base, at this point, we'd know if it flat-out didn't work with browsers.

**Comment by RonaldColyar** [comment]
@lgrahl  your code is constantly sending chunks of data to the server , which keeps the connection alive. My example tries to keep the connection alive without sending constant chunks of data back and forth. Keeping connections alive for 10+ seconds without exchanging?

**Comment by RonaldColyar** [comment]
@aaugustin  I understand that it may be a client env issue , but I have replicated the issue on 3 different machines with different specs. Just wondering if you can keep connections open without constantly sending chunks of data back and forth for at least 10 seconds? In @lgrahl's example , there is chunks being sent constantly. That example(@lgrahl 's) works fine for me too , can i not keep the connection alive without streaming data constantly with this lib?

**Comment by lgrahl** [comment]
My example uses a 5 minute interval which is hardly "constantly sending chunks". And it was just an example to point out that there's no timeout in between multiple minutes. Anyway, there are three kinds of keep-alive you can get with WebSocket:

- TCP-level keep-alive, if enabled. Determined by whatever your environment/OS gives you or how you setup your socket. You're on your own here if you want to use this.
- websockets keep-alive. See docs for settings.
- application-level keep-alive. Just implement your own interval that works for your use case.

In any of these cases we're usually talking about multiple minutes here before we run into timeouts. So I'm confused by what you mean with "10+ seconds" (but I also can't follow your description tbh, it's quite confusing).

**Comment by RonaldColyar** [comment]
@lgrahl  your example works fine , firefox must not allow you to store connections for later use?

**Comment by RonaldColyar** [comment]
Once again @aaugustin and @lgrahl  I love you guy's work on the wonderful library!! I hope I didn't cause too much worry , I hope to contribute to this amazing project! It deserves more stars!!!!!
