### ISSUE TITLE
Socket disconnection issue after recv()

### ISSUE THREAD

**Issue by hyavari** [aaugustin/websockets#1004]
I am trying to add a client WebSocket connection to my project. I need to have multiple connections to the server(s). 

```
connections = set()
connections.add("ws://10.4.0.5:8088")
connections.add("ws://10.4.0.6:8088")

async def socket_api(uri, ):
    websocket = None 
    while True:
        try:
            if not websocket:
                print ('Websocket NOT connected. Trying to reconnect...')
                websocket = await websockets.connect(uri)
                await websocket.send('hello')
            
            command = await websocket.recv()
            print('Srv Command: {}'.format(command))
            reccmd = json.loads(command)

            '''
            Process received msg
            '''

        except Exception as e:
            print('Error!', e)
            await asyncio.sleep(3)

async def handler():
    await asyncio.wait([socket_api(uri) for uri in connections])

asyncio.get_event_loop().run_until_complete(handler())
asyncio.get_event_loop().run_forever()
```
My issue is that the connection will be closed after one time receiving data over the socket and after that, just the exception runs.

What the wrong function I am using? How I should edit my code? Thanks.

**Comment by lgrahl** [comment]
Apologies but this issue tracker is not stackoverflow. Every now and then we might just get nerd-sniped and provide pointers but it's kinda getting a bit too much lately.

**Comment by curtailment** [comment]
Did you figure this out? My websocket connection is also closing itself after receiving one frame. I'm using async for to read messages and I get one frame, then according to the debug log, websockets just writes a close frame. My async for loop just seems to be stuck there and doesn't even exit the loop after the connection closes.

**Comment by curtailment** [comment]
Nevermind... it turns out there was a dictionary key exception inside my `async for` loop, which killed the loop, but that exception never bubbled up or showed in my log (I didn't catch it myself). I guess I need to learn more about exception handling in asyncio coroutines.
