### ISSUE TITLE
ConnectionResetError when enabling SSL

### ISSUE THREAD

**Issue by Randelung** [aaugustin/websockets#1006]
Hello,

So far I've been working without SSL to get my application up and running. I used version 8.1 up to now and so far everything was fine.
Now that I enabled SSL I'm getting errors:
```python
2021-07-02 17:58:02.492 ERROR    asyncio: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rando\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

Upgrading to 9.1 didn't help.

Gist: https://gist.github.com/Randelung/c1dfbeeb87ba1a1cc0c66424cb67b8f3
It comes with a cert and a private key that get written to disk, please be sure it's not overwriting anything important. Apparently you can't load certificates or keys from strings.
Run, go to http://localhost:8080/ and https://localhost:8443/. The http one will work fine, the ssl one throws one or two errors per load.

The errors seem harmless since the webpage still works, but the log is being spammed to death.

Thanks!

**Comment by lgrahl** [comment]
Sounds like an asyncio thing tbh since there's no reference to websockets code in the trace.

**Comment by Randelung** [comment]
... Firefox does not produce the issue, Chrome/Edge do. Reproduced on two systems using two different projects.

Sigh.

Any chance this error can be bubbled to user code as a callback or something in order to catch and ignore it? Or, depending on where it happens, just ignore it outright?

**Comment by aaugustin** [comment]
I would recommend creating a socket in the most basic way possible:

```python
import socket, ssl
sock = socket.create_server(("localhost", 1234))
context = ... # your SSL context
with context.wrap_socket(sock, server_side=True) as ssock:
        conn, addr = ssock.accept()
        conn.recv(1024)
```

If it works at this layer, it should work at all upper layers (hopefully...)

If it doesn't work at this layer, you'll get the best error message Python can give you here.

**Comment by aaugustin** [comment]
I'm closing the issue https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_server#asyncio.loop.create_server doesn't provide an option doing what you want and I doen't wish to stop using it.

**Comment by Randelung** [comment]
I wouldn't have expected you to switch API at all, I was hoping for insight on the issue since you're more experience on the subject.
However, I have a workaround, I think... The issue seems to be a combination of asyncio and Python strangeness.
Googling a bit lead me to https://bugs.python.org/issue30319, which states that socket.shutdown will not ignore errors because the object is still usable and some code might use the signal to trigger something. The only problem is that the event is triggered by asyncio and thus you can't try/catch the event.
However, asyncio lets you set a global exception handler on the event loop, using which I can suppress the exception.
You might have known about this, I'm still learning. 😅 I'm writing it down for posterity.

Your FAQ holds true once again - it's an asyncio issue (or rather misuse of it) and has nothing to do with websockets.

**Comment by aaugustin** [comment]
OK - I wasn't aware of the global exception handler. Nice work!
