### ISSUE TITLE
Module 'websockets' has no 'serve' member

### ISSUE THREAD

**Issue by Sonuq** [aaugustin/websockets#1007]
<!--
I am getting an error called "Module 'websockets' has no 'serve' member", I checked and I don't have any script called "websockets.py" in my directory.

import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f"> {greeting}")

start_server = websockets.serve(hello, "localhost", 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

**Comment by Sonuq** [comment]
I am getting an error called "Module 'websockets' has no 'serve' member", I checked and I don't have any script called "websockets.py" in my directory.


import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f"> {greeting}")

start_server = websockets.serve(hello, "localhost", 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

**Comment by aaugustin** [comment]
Could you provide the full stack trace please?

Also could you confirm which versions of Python and websockets you're using?

**Comment by Sonuq** [comment]
Websocket 9.1, Python 3.9.6

Also sorry if I don't know this, but what's a full stack trace?

**Comment by Sonuq** [comment]
Nevermind, VSCodium detects the problem but upon running, it receives the message from the client.

**Comment by kwint** [comment]
I think we have a recursion of this bug: https://github.com/aaugustin/websockets/issues/940

Mypy thinks there is no connect and typing attribute in the websocket module. This probably also whats going on above.

```
....py:440: error: Module has no attribute "connect"
....py:444: error: Module has no attribute "typing"
```

**Comment by aaugustin** [comment]
So:

- the code works as intended;
- it takes advantage of the dynamic nature of Python in a way that static analysis tools struggle with; a workaround for this is documented in #940.

**Comment by aaugustin** [comment]
439dafa6 should avoid similar issues in the future.
