### ISSUE TITLE
socket.io ?

### ISSUE THREAD

**Issue by parmentelat** [aaugustin/websockets#101]
Hello there
Sorry if this is not the proper channel...
I was just wondering if there's any known plan to leverage on this awesome work and provide  an asyncio-friendly socket.io functionality ? I am not so much after the fallbacks in socket.io (websockets-only is fine by me), but I do need the ability to send messages on a specific 'channel'/'event-name'.

If not, I would volunteer to give this a try, but to this end I could use a few pointers, as I haven't been able to spot any documentation that would specify how these event-names are encoded on a websockets - as I take it they are.

again my apologies if this is not the right medium, please redirect me in this case 

many thanks !

**Comment by aaugustin** [comment]
websockets is intended as a low level library that makes it easy to build systems with more features. If you're into the Python web community, it's roughly the same distinction as werkzeug vs. flask.

I don't know anyone working on this exact idea at this time. Try it!

Subscribing to channels just takes a few lines of code. The docs show how to do it for a single process. If you want multiple processes (i.e. a scalable solution) you'll likely use an external, dedicated pub/sub system.

Websockets don't have a concept of events names. You just define your own wire protocol. For example you can send JSON structures: `{"event": "spam_all_the_eggs", "data": {...}}`

You have two ways to implement it:

- wrap the public APIs — this is the easiest and the most robust, and it should be sufficient for your purposes
- inherit the protocol classes — this gives you full control, but it may be more difficult to maintain

Either way, I think it can and should live in a separate project. Small is beautiful :-)

**Comment by parmentelat** [comment]
many thanks :)

I had no intention to pollute your project with this stuff, this discussion is very helpful already.
So just to be sure that I'm getting it, is your example above compliant with what socket.io actually does behind the scenes ? I mean, a JSON encoding of a dict that has 'event' and 'data' ? 
I'd be curious to know where this is documented so I could read the full story :)

thanks again in any case, this is very helpful

**Comment by aaugustin** [comment]
I don't know what format socket.io actually uses. This was just an example of how you could achieve similar functionality.

**Comment by Ivoz** [comment]
You would need to implement [socket.io's own protocol](https://github.com/socketio/socket.io-protocol) ontop of websockets transport.

**Comment by aaugustin** [comment]
Thanks Ivoz for the links. I think we've covered the role that websockets could play in such a system, but feel free to get in touch if you have further questions!
