### ISSUE TITLE
Facing asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by bansalnaman15** [aaugustin/websockets#1013]
I created a server to handle thousands of requests at a time, why do I get this error after some time?

**Comment by lgrahl** [comment]
You will have to provide more info than that.

**Comment by bansalnaman15** [comment]
`import asyncio
import json

from websockets import serve
import datetime

dtf = "%Y-%m-%d %H:%M:%S"


async def echo(websocket, path):
    async for message in websocket:
        try:
            print("RCVD:", message)
            now = datetime.datetime.now().strftime(dtf)
            greeting = {
                "result": True,
            }
            await websocket.send(json.dumps(greeting))
        except:
            await websocket.send("")


async def main():
    async with serve(echo, "0.0.0.0", 7788):
        await asyncio.Future()


asyncio.run(main())
`
This is a basic server that I am using, it serves the requests for a while, but after a while it gives asyncio.exceptions.CancelledError

**Comment by aaugustin** [comment]
Please replace `except:` with `except Exception:`. (The former catches `CancelledError`, which is almost never what you want; the latter doesn't; I suspect this hides the real exception.)

Then please provide the full stack trace of the exceptions you're seeing.

**Comment by lgrahl** [comment]
Assuming the author has either resolved it or is not interested in it any more. Closing.
