### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000007EFEAB070>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### ISSUE THREAD

**Issue by knowledgecomputer2018** [aaugustin/websockets#1015]
hi how are you . what are you doing? your today is good .
i have a problem in connect to binance api with my system(windows 8.1) when i connect to binance with request websocket

ws=websocket.WebSocketApp(SOCKET,on_open=on_open,on_error=on_error,on_close=on_close,on_message=on_message)#callback function

i have a problem (title ) but when i connect to api binance with "colab google" i have not error with same code.

thank you very much reply me .

good luck
god willing

**Comment by aaugustin** [comment]
Apologies, I'm not going to help: https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users

**Comment by knowledgecomputer2018** [comment]
hi

my code is ping to website binance by API_KEY,SECRET_KEY.my code is correct because i run code over colab google is good but i run my system this is my problem . i turn off my firewall no different and i change port 9443 to open port but not change .

good luck
god willing
