### ISSUE TITLE
Question: Difference between max_size, read_limit, and write_limit

### ISSUE THREAD

**Issue by ThatXliner** [aaugustin/websockets#1016]
I'm trying to implement sending arbitrary-length messages by sending chunks. I need to know the default max limit for each chunk sent.

If I set `max_size` for the server to be too low, a giant message will fail on the server with the exception `websockets.exceptions.PayloadTooBig`. If I set `read_limit` too low, the *client* will fail with `websockets.exceptions.InvalidStatusCode`.

**Comment by aaugustin** [comment]
> I need to know the default max limit for each chunk sent.

There is no such limit. The effective limit is `max_size` because a chunk cannot be bigger than the message it belongs to.

> If I set `max_size` for the server to be too low, a giant message will fail on the server with the exception `websockets.exceptions.PayloadTooBig`.

Yes, that's the point of `max_size`, but you can set it to `None` to disable it entirely.

> If I set `read_limit` too low, the client will fail with `websockets.exceptions.InvalidStatusCode`.

I'm not seeing why this would happen. `read_limit` and `write_limit` are just controlling buffer sizes. Giving them different values is supposed to affect performance but not behavior.

**Comment by ThatXliner** [comment]
I see. Does websockets already handle message-chunking? (Unlimited length messages)

**Comment by aaugustin** [comment]
Yes it does.

**Comment by ThatXliner** [comment]
Oh ok. Maybe you should add that to the docs for `send()`

**Comment by aaugustin** [comment]
Maybe you should read the docs for `send()` :-)

> send() also accepts an iterable or an asynchronous iterable of strings, bytestrings, or bytes-like objects. In that case the message is fragmented. 

Unless I misunderstood, what you call "chunking" is actually called "fragmentation" in the WebSocket spec.

**Comment by ThatXliner** [comment]
Maybe this is an example of the [XY problem](https://xyproblem.info). Sorry about that, I'm just wondering if web sockets already supports unlimited length messages.

**Comment by aaugustin** [comment]
websockets doesn't do automatic fragmentation. You have to fragment by yourself if you want to fragment.
