### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by martincornejo** [aaugustin/websockets#1017]
I'm trying to set up a reverse proxy for a backend relying on websockets. Following this example of [nginx with websockets](https://www.nginx.com/blog/websocket-nginx/) with a node.js server works perfectly. However my python implementation returns always from the client side `websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502`. 

I've found in the documentation the following under `websockets.server.unix_serve`:
> It’s useful for deploying a server behind a reverse proxy such as nginx.

Is there something I'm missing? I've added a small reproducible example with python code for server and client, and the ngnix configuration.

**server.py**
```python
import asyncio
import logging
import websockets

logging.basicConfig(level=logging.INFO)

async def handler(websocket, path):
    while True:
        message = await websocket.recv()
        logging.info("message received: %s", message)
        await websocket.send(f"Received: {message}")


async def main():
    server = await websockets.serve(
        handler,
        "localhost",
        8010
    )
    logging.info("Server listening...")
    await server.wait_closed()

if __name__ == "__main__":
    asyncio.run(main())

```

**client.py**
```python
import asyncio
import logging
import websockets

logging.basicConfig(level=logging.INFO)

async def main():
    async with websockets.connect("ws://localhost:8020/ocpp/cp1") as ws:
        while True:
            message = input(">")
            await ws.send(message )
            response = await ws.recv()
            logging.info(f"From server: \"{response}\"")

if __name__ == "__main__":
    asyncio.run(main())

```

**nginx.conf**
```nginx
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream websocket {
        server 127.0.0.1:8010;
    }

    server {
        listen 8020;
        location /ocpp/ {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
        }
    }
}

events { }
```

**Comment by aaugustin** [comment]
The example in websockets' own documentation is simpler (no superfluous `map`) and works:
https://websockets.readthedocs.io/en/latest/howto/nginx.html#configure-and-run-nginx

Can you set the log level to `DEBUG` and provide complete logs both for the server and the client?

**Comment by martincornejo** [comment]
Thanks! Using the simpler `nginx.conf` file of the websockets documentation worked. Setting the log level to `DEBUG` also helped a lot. For some reason the server was rejecting the client connection with the previous setup...
