### ISSUE TITLE
[Question] how to avoid websockets.exceptions.ConnectionClosedError: code = 1002

### ISSUE THREAD

**Issue by vranky** [aaugustin/websockets#1020]
Hello I would like to establish websocket connection and subscribe some data. My question is how to define header params ?
Cause snippet below is returning exception ->
_websockets.exceptions.ConnectionClosedError: code = 1002 (protocol error), no reason_

```
async def client():
    async with websockets.connect(uri=f"wss://myUrl/api/graphql", extra_headers={
                                        "authorization": f"bearer {token}",
                                        "sessionId": asdfsadasd,
                                        "x-tenant": asfsdafsda,
                                    }) as websocket:

        async def receive() -> dict:
            return json.loads(await websocket.recv())

        # Handle events.
        while True:
            message = await receive()
            if message["type"] == "complete":
                break
            print(message)
asyncio.run(client())
```

**Comment by lgrahl** [comment]
Hi. Please provide a reproducible example. Otherwise, it could be literally anything.

**Comment by aaugustin** [comment]
In addition to what lgrahl said, 1002 means that the server sent something that websockets couldn't interpret according to the WebSocket Protocol.

Enabling logs at the DEBUG level may help understand what the server is sending: https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging
