### ISSUE TITLE
Invalid URI error when passing the URL of a running Jupyter notebook

### ISSUE THREAD

**Issue by Vishav3** [aaugustin/websockets#1023]
I am trying to send message using websocket client (Python-based) to the Jupyter notebook (the websocket server is running in the cell of notebook). The code i am using is below:

Websocket Client Code:

import websockets
import asyncio
async def listen():
    url = "ws://127.0.0.1:8888/?token=14bf261ecb24d32d4c3d63270fc27f75e32699b7a51f22aa"
    async with websockets.connect(url) as ws:
        await ws.send("Hello Server!")
        while True:
            msg = await ws.recv()
            print(msg)
asyncio.get_event_loop().run_until_complete(listen()) 

The websocket server Code (running in the cell of Jupyter notebook shown below): 
![image](https://user-images.githubusercontent.com/80038335/127199070-527cddfb-dc0d-4ab4-bf07-bd17b85beb85.png)

But when I run client i get following error:
![image](https://user-images.githubusercontent.com/80038335/127199184-1aca3b49-2715-4757-aef0-856e39781921.png)

However when I use the given URL separately in new browser window it actually works. Why I am getting this error?

The details of running Jupyter address is:
![image](https://user-images.githubusercontent.com/80038335/127204687-8b552048-07ea-449d-846e-da21677f3a0b.png)

Is there any specific syntax i need to follow for URL. I need this to run urgently for my project submission. Please help in this issue.

**Comment by aaugustin** [comment]
Actually this is a bug -- websockets doesn't support redirects when the `Location` header contains a relative URL.

Try `url = "ws://127.0.0.1:8888/tree?token=14bf261ecb24d32d4c3d63270fc27f75e32699b7a51f22aa"` so you bypass the redirect?

**Comment by Vishav3** [comment]
@aaugustin Thanks for the suggestion! But this is again giving error with following line of codes.
import websockets
import asyncio
async def listen():
url = "ws://127.0.0.1:8888/tree?token=14bf261ecb24d32d4c3d63270fc27f75e32699b7a51f22aa"
async with websockets.connect(url) as ws:
await ws.send("Hello Server!")
while True:
msg = await ws.recv()
print(msg)
asyncio.get_event_loop().run_until_complete(listen())

Error is:
![image](https://user-images.githubusercontent.com/80038335/127358488-f1524c9f-c376-4177-aa49-4c7a433de445.png)

And the weird part is I can able to communicate easily if I simply use below one and not passing URL:

import websockets
import asyncio
async def listen():
url = "ws://127.0.0.1:8080"
async with websockets.connect(url) as ws:
await ws.send("Hello Server!")
while True:
msg = await ws.recv()
print(msg)
asyncio.get_event_loop().run_until_complete(listen())

I can okay with that for communication on local host but my full project is running in Jupyter notebook (accessible via local browser) at remote server for that i need to pass URL for websocket connection. Or is there any other method by which i can establish the connection?

**Comment by Vishav3** [comment]
**Related to above issue:** The other help that i can expect is: I made a websocket server on glitch.com using jsnode with below code:
![image](https://user-images.githubusercontent.com/80038335/127374138-a6ed8054-7c80-42c5-9f1e-cf0484d80560.png)

When i try to establish the connection from my remote Jupyter notebook (which is websocket client by passing URL of server i.e. glitch.com) I can able to connect with following code:
![image](https://user-images.githubusercontent.com/80038335/127374024-4cdc368f-ca61-46a7-8b3a-65d4ce1ef2a1.png)

Is there any method by which  i can access the client URL at server end which is used by websockets (i mean reverse method). And after getting the client URL I can use that in my code.
