### ISSUE TITLE
Websocket client sends once only

### ISSUE THREAD

**Issue by kevinlinxc** [aaugustin/websockets#1024]
I believe this is different from the first question in the FAQ, since that refers to a websocket server.

I have a websocket Server in Java, and I'm using this package as a client in Python.

Here are two pieces of example code. Example 1 will send messages to the server indefinitely and the server will acknowledge them, but there is considerable latency, and I think it is because the code creates a new websocket connection in every loop, which slows it down as it waits for the connection to be made. To amend this, in example 2, I put the loop inside the context manager. Both examples of code constantly print that they are sending data to the websocket server, but **when I run example 2, the server only receives the first message** and then nothing else happens.

What am I doing wrong?

Example 1:
```python
import time
import asyncio
import websockets
import json
ws_name = "ws://localhost:8888"

async def toWebsocket(altitude):
    async with websockets.connect(ws_name) as websocket:
        d = {
            "type": "arduino_data",
            "flightData": {
                "latitude": 49.258381363187276,
                "longitude": -123.19507976825994,
                "altitude": int(altitude),
                "velocity": 14.272902869735958,
                "headwind": -0.9},
        }
        data = json.dumps(d)
        await websocket.send(data)


if __name__ == "__main__":
    while True:
        data = 5 # originally arduino serial code, removed for this example
        print(f"Sending {data} as altitude")
        if data:
            asyncio.run(toWebsocket(data))
        time.sleep(0.5)

```

Example 2:
```python
import time
import asyncio
import websockets
import json
ws_name = "ws://localhost:8888"

async def toWebsocket():
    async with websockets.connect(ws_name) as websocket:
        while True:
            data = 5 # originally arduino serial reading code, removed for this example
            if data:
                d = {
                    "type": "arduino_data",
                    "flightData": {
                        "latitude": 49.258381363187276,
                        "longitude": -123.19507976825994,
                        "altitude": int(data),
                        "velocity": 14.272902869735958,
                        "headwind": -0.9},
                }
                print(f"Sending {data} as altitude")
                data = json.dumps(d)
                await websocket.send(data)
                print(f"{d}")
            else:
                print("No data detected from serial yet")
            time.sleep(0.5)

if __name__ == "__main__":
    asyncio.run(toWebsocket())


```

**Comment by kevinlinxc** [comment]
I fixed it, but it's a shady fix.

I made my webseocket server echo the message back to all clients (it wasn't previously sending back to my Python, just a different client). I then added `greeting = await websocket.recv()` to my Python client and now it works properly, sending multiple messages with no delay.

**Comment by aaugustin** [comment]
It should work much better if you use asyncio.sleep instead of time.sleep.

**Comment by kevinlinxc** [comment]
Good suggestion, thanks
