### ISSUE TITLE
Sanic not raising ConnectionClosed on Python 3.7

### ISSUE THREAD

**Issue by priyesh-kashyap** [aaugustin/websockets#1033]
Hi,

I've been using Sanic and now I want to gather the information that whether the WebSocket is closing normally or abnormally. The problem that I'm facing currently is that whenever the client is closing a connection abnormally (Network Issue), no Exception is being raised. Although I'm getting logs `server - event = connection_lost(None) 
server - state = CLOSED 
server x code = 1006, reason = [no reason]
server! failing CLOSED WebSocket connection with code 1006` but no  Exception.

OS: ubuntu - 16
Sanic version: 20.6.3
websockets version: 8.1

**Comment by aaugustin** [comment]
There's a good chance this will go away with https://github.com/sanic-org/sanic/issues/2000.

**Comment by aaugustin** [comment]
This looks more like something that should be reported to Sanic. Note that Sanic is currently redoing their websockets integration in https://github.com/sanic-org/sanic/issues/2000. Probably that's their priority vs. fixing possible issues in the legacy implementation.

**Comment by priyesh-kashyap** [comment]
Yes, make sense. Actually, I was going through the `websockets.protocol.WebScoketCommonProtocol.fail_connection` and noticed that there is no exception raised in the case of abnormal termination of connection from the client-side. Let me report this to Sanic as well.

**Comment by ahopkins** [comment]
Yes, this is hopefully something that will be fixed in 21.9. A fix for 20.12 may also be coming, but it will not be back ported to 20.6.

**Comment by priyesh-kashyap** [comment]
Oooh, that's great. I'll wait for the release then.
