### ISSUE TITLE
TypeError: analyze() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by pourfard** [aaugustin/websockets#1038]
https://github.com/aaugustin/websockets/blob/1b0b2de59f13b79062a888a8d17ae5e9e5a60ef9/src/websockets/legacy/server.py#L305

Removing path as the second parameter resolves the issue.

**Comment by aaugustin** [comment]
I guess you have:

```python
async def analyze(websocket):
    ...
```

somewhere and it should really be:

```python
async def analyze(websocket, path):
    ...
```

(In a future version of the API, I'm thinking of switching to the former, but for now the API is the latter.)

**Comment by pourfard** [comment]
Thanks.

Yes, I changed it and the there is no problem.
