### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'

### ISSUE THREAD

**Issue by MoonMagiCreation** [aaugustin/websockets#1040]
I am trying to use websockets to send messages from python/django and I always get the same error.

`RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'`

I have tried many asynchronous sending methods, but have had no luck. My code is now this:

`asyncio.run(sendDataView())`
....

`async def sendDataView():`
`    async with websockets.connect('ws://127.0.0.1:8001/ws/viewData/') as ws:`
`        while True:`
`            await ws.send(json.dumps({`
`                'value': 85`
`            }))`
`            await asyncio.sleep(1)`
`

**Comment by aaugustin** [comment]
I think this is really a question about asyncio because you'd have exactly the same problems if your coroutine was just:

```python
async def sendDataView():
    await asyncio.sleep(1)
```

https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.new_event_loop should help.

Hard to tell if your architecture makes sense though — if you intend to call this from a Django view, I don't think it will scale well.

**Comment by MoonMagiCreation** [comment]
@aaugustin the idea was to launch a thread asynchronously in django that would update the data and send it via websocket to the client. But in the end I had to change my style to api requests from the client. Practice will tell if I accepted it.

If the problem is still yes:

`async def sendDataView():`
`    await asyncio.sleep(1)`

There is some kind of incompatibility between websockets and asyncio library threads.

**Comment by aaugustin** [comment]
If you start a thread in a Django view, call `new_event_loop()` in that thread, and then run `asyncio.run(<some websockets there>)` there, it should work. It won't scale well though.

To implement the logic shown in your initial post with a scalable design, you should separate the websockets stuff (running on asyncio) from the web stuff (running on threads) and use a message passing mechanism from web to websockets, so websockets knows when it should open a connection.

I don't have much information, so it's a bit difficult to give more help :-/
