### ISSUE TITLE
client side additional header token auth

### ISSUE THREAD

**Issue by dimension4c137** [aaugustin/websockets#1043]
I have a Problem to connect to a server (I am the client-side).
Server wants Token (Bearer) authentication. --> haven't found in docs or faqs 
as an example:

```
async def hello():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket: # shouldnt it be (uri, extra_header=)
        name = input("What's your name? ")

        await websocket.send(name)
        print(f"> {name}")

        greeting = await websocket.recv()
        print(f"< {greeting}")

asyncio.get_event_loop().run_until_complete(hello())
```

what I am doing wrong or how it should be

**Comment by aaugustin** [comment]
See https://websockets.readthedocs.io/en/latest/topics/authentication.html#machine-to-machine-authentication

(That's in the "development" version of the docs, which is why you didn't find it. It will become the stable version of the docs once I release version 10.0.)

**Comment by dimension4c137** [comment]
so auth is possible at the next release? or have you just meant the docs. because its not working in v.9.1?

**Comment by aaugustin** [comment]
This code has been working for at least 5 years; 10.0 only makes the docs more explicit.
