### ISSUE TITLE
websockets.send() routine is slowing the application

### ISSUE THREAD

**Issue by PyPatel** [aaugustin/websockets#1044]
I am using WebSockets to connect to exchange to receive and send data on high frequency (50 ms or less per tick). I am sending messages on each tick which is seriously slowing the application down. Without the send procedure, I am in sync with market data. But as soon as I start sending messages to socket connection, it gets very slow (maybe buffer limit reaches or some other issue) 

Code structure for Websocket connection and send procedure is called on each tick is as follows:

``` python3
async def _connect(self):
    retries = 0
    delay = 1
    while retries <= self.retries or self.retries == -1:
        try:
            async with websockets.connect(uri = self.endpoint, ping_interval = None) as websocket:
                # asyncio.ensure_future(self._watch(websocket))
                # connection was successful, reset retry count and delay
                retries = 0
                delay = 1
                await self.market_subscribe(websocket)
                await self.trade_subscribe(websocket)
                await self._handler(websocket)
            
        except (ConnectionClosed, ConnectionAbortedError, ConnectionResetError) as e:
            print("encountered connection issue %s - reconnecting...", str(e))
            await asyncio.sleep(delay)
            retries += 1
            delay *= 2

    raise ExhaustedRetries()

async def _handler(self, websocket):
    self.websocket = websocket
    # loop = asyncio.get_running_loop()
    async for message in websocket:
        message = json.loads(message)
        msg_type = message['op']
        if msg_type == 'mcm':
            await self.book_event_handler(message) ## Updates book in memory
            await self.send_exposure_map(websocket) ## Sends order 
            # 2. Run in a custom thread pool: # DID NOT WORK
            # with futures.ThreadPoolExecutor() as pool:
            #     result = await loop.run_in_executor(pool, self.send_exposure_map)
            # print('custom thread pool run')

def run(self, start_loop:bool = True):
    try:
        loop = asyncio.get_event_loop()
        loop.create_task(self._connect())
        if start_loop:
            loop.run_forever()
    except KeyboardInterrupt:
        print("Keyboard Interrupt received - shutting down")
    except Exception as E:
        print(f"Unhandled exception:: {E}") 

async def send_exposure_map(self, websocket):
  self.websocket = websocket
  instructions = []        
  send_message = json.dumps(
              {
                  "action":"orderExposureMap",
                  "instructions":instructions,
                  "id": self.sender_id
              }
          )
  self.sender_id += 1 ##* Keep incrementing for each send message
  self.last_order = time()
  await websocket.send(send_message)
```

Is there anything wrong here, or anyway I can improve on this so that I stay in sync with the market? Currently, it hardly sends a single message per second.

**Comment by ahopkins** [comment]
I had some conversation with @PyPatel regarding this. IMO it sounds like there are potentially two things going on:

1. There is a loop that is causing a lot of connection overhead and the script needs to be optimized to reuse connections and not block itself; or
2. The issue is server side. Either the response being slow, or there is some sort of throttling.

**Comment by lgrahl** [comment]
There's no obvious flaw in the code to me and we can't/won't debug other peoples servers. If sending asynchronously blocks, then yes, it sounds like the buffer is saturated. I'd suggest investigating that and reopening if that's not the case.

**Comment by aaugustin** [comment]
I see references to a thread executor and I would recommend against this if you care about performance.

**Comment by PyPatel** [comment]
I suspect the issue could be

- Buffer getting full because of the send messages (but at the same time, I tried running with `max_queue=None` to remove the buffer limit from WebSocket. It did not work.) This should also cause receive messages to get slow down, which is not happening. Slowness only happens when I start sending messages on the same WebSocket 
- I do not see a spike in thread usage or RAM which says that threading will not help
- Issue with the server which is receiving the data

I am running out of ideas.

**Comment by PyPatel** [comment]
Closing this on the suspicion of the server-side issue.

**Comment by aaugustin** [comment]
`max_queue=None` affects the recv buffer; it shouldn't interact the send buffer. I removes backpressure on incoming messages, which is the opposite of what you seem to expect. ("This should also cause receive messages to get slow down, which is not happening.")
