### ISSUE TITLE
Library hangs with default compression

### ISSUE THREAD

**Issue by greuff** [aaugustin/websockets#1050]
This hangs forever:

```
#!/usr/bin/env python

import asyncio
import websockets
import logging

logging.basicConfig(level=logging.DEBUG)
logging.getLogger("websockets").setLevel(logging.DEBUG)

async def hello():
    uri = "wss://streams.exchange.bitpanda.com"
    async with websockets.connect(uri) as websocket:
        await websocket.send('{"type":"SUBSCRIBE","channels":[{"name":"ORDER_BOOK","depth":10,"instrument_codes":["BTC_EUR"]}]}' + "\n")
        response = await websocket.recv()
        print(f"<<< {response}")

asyncio.run(hello())
```

but when you change the connect line to 

```
    async with websockets.connect(uri, compression=None) as websocket:
```

it runs through as expected. Library version 10, but also observed with version 9.0.1

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/project/contributing.html#cryptocurrency-users

**Comment by greuff** [comment]
That is stupid. I also have children, I drive a BEV, I have a photovoltaic system on my (wooden) house, I care about the environment. A Bitcoin exchange doesn't create blockchain transactions every time, but it acts as a cache. Yes, Bitcoin is bad and should die, but come on, you're in the software industry (just like I am), you're using computers that need energy, the internet as a whole needs an obscene amount of energy. But whatever floats your boat, I have my workaround, if you don't want to improve your software only because of hypocritical ideological reasons have it your way.

**Comment by aaugustin** [comment]
If it was a bug it websockets, I'd fix it, but it's a bug in bitpanda.

bitpanda's clearly gets the message: if you send another message e.g. `await websocket.send('{}\n')` you get an error from their application layer, which suggests that their protocol layer is working.

If you add `extensions=[ClientPerMessageDeflateFactory()]` to the `connect()` call — which doesn't specify an optimized window size, while the default configuration does — then the bug in bitpanda doesn't trigger. It's very similar to #1046.

If the team at bitpanda want to look at the problem from their end and determine that websockets is doing something that it shouldn't be doing, I'll review their info.

**Comment by aaugustin** [comment]
Hypothesis: their compressor crashes when the extension negotiation includes the `server_max_window_bits` parameter and the error is swallowed silently.

- `[ClientPerMessageDeflateFactory()]` works
- `[ClientPerMessageDeflateFactory(server_max_window_bits=14)]` fails
- `[ClientPerMessageDeflateFactory(server_max_window_bits=15)]` fails differently, because bitpanda has another bug that causes them to send a non-spec-compliant response (they don't include `server_max_window_bits` in their response, while the spec says they should), and this other bug hides the bug you're looking for.

**Comment by greuff** [comment]
Thank you for looking into it!

**Comment by Avon619** [comment]
> This hangs forever:
> 
> 
> 
> ```DNA 
> 
> #!/usr/bin/env python
> 
> 
> 
> import asyncio
> 
> import websockets
> 
> import logging
> 
> 
> 
> logging.basicConfig(level=logging.DEBUG)
> 
> logging.getLogger("websockets").setLevel(logging.DEBUG)
> 
> 
> 
> async def hello():
> 
>     uri = "wss://streams.exchange.bitpanda.com"
> 
>     async with websockets.connect(uri) as websocket:
> 
>         await websocket.send('{"type":"SUBSCRIBE","channels":[{"name":"ORDER_BOOK","depth":10,"instrument_codes":["BTC_EUR"]}]}' + "\n")
> 
>         response = await websocket.recv()
> 
>         print(f"<<< {response}")
> 
> 
> 
> asyncio.run(hello())
> 
> ```
> 
> 
> 
> but when you change the connect line to 
> 
> 
> 
> ```
> 
>     async with websockets.connect(uri, compression=None) as websocket:
> 
> ```
> 
> 
> 
> it runs through as expected. Library version 10, but also observed with version 9.0.1
