### ISSUE TITLE
Python 3.9.7 breaks tests

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#1051]
Tests fail due to https://bugs.python.org/issue45097. It will be fixed in 3.9.8. We could pin GitHub actions to 3.9.6 (and inevitably forget to unpin...) or just live with broken builds for two months, until GitHub actions gives us 3.9.8.

**Comment by aaugustin** [comment]
Revert around mid november 2021, when 3.9.8 is available on GitHub actions.

**Comment by vfazio** [comment]
3.9.8 has been released https://www.python.org/downloads/release/python-398/

**Comment by aaugustin** [comment]
Thank you.
