### ISSUE TITLE
Client always disconnects after short time

### ISSUE THREAD

**Issue by danspage** [aaugustin/websockets#1055]
Hi,
Thanks for writing an awesome python library, it's super useful. I'm having an issue where my client will connect, start sending messages to the server, and then stop sending them, disconnecting after anywhere between 3 and 30 seconds. Consulting google, many people are saying to add `ping_interval=None` and `ping_timeout=None` to the websockets.serve function, however doing so does not stop the issue. Are there any other common fixes to this problem? Here's my [code](https://pastebin.com/aiMbZi9A).

Thanks!

**Comment by aaugustin** [comment]
You're referring to a client but you provided code for a server?

**Comment by aaugustin** [comment]
I'm not seeing anything wrong with that code.

I'm aware of the cargo-cult advice of adding `ping_interval=None` and `ping_timeout=None`. This is neither useful nor correct in general. It may help only for interacting with buggy implementations, and those are uncommon.

I don't have any other ideas that may help nor actions I could take, so I'm going to close this issue.
