### ISSUE TITLE
no loop arg in asyncio.wait call

### ISSUE THREAD

**Issue by rodriguez-facundo** [aaugustin/websockets#1058]
Hi, this is more of a question than a bug. Why the loop arg is dropped for Python 3.8 and 3.9? https://github.com/aaugustin/websockets/blob/c70c7d6703ab8bef35cc89965becc67e8a1afe7c/src/websockets/legacy/compatibility.py#L13

I see some "Future belongs to a different loop" after running a server in prod for a while and would like to be explicit about the loop.

**Comment by aaugustin** [comment]
This prevents deprecation warnings in Python 3.8.

websockets' test suite contains tests for deprecation warnings. When Python introduces new deprecations, usually I act on them immediately to avoid new warnings, which would require making the tests conditional on the Python version, etc. (There's a bit of that in the test suite anyway but not too much.)

**Comment by aaugustin** [comment]
You can monkey-patch your local version to put `(3, 10)` there just for debugging..

**Comment by rodriguez-facundo** [comment]
This fixed the issue for me. but it is not pretty

```python
sys.version_info = sv(3, 7, 12, 'final', 0)
```

The problem is that I'm running nest_asyncio and the loop has to be specify

**Comment by rodriguez-facundo** [comment]
monkey patch was the solution :)
