### ISSUE TITLE
Reference cycle in websockets 10?

### ISSUE THREAD

**Issue by chrysn** [aaugustin/websockets#1059]
In the CI tests of aiocoap, I noticed breakage going from websockets 9.1 to 10 without finding a plausible link to the change and commit log.

The change is subtle and usually not covered by Python's API guarantees: I check that after an asynchronous shutdown (which in the websockets case performs a `.close()` and `await s.wait_closed()` on the server), the large library objects are actually freed when their last reference is removed. This is useful in spotting memory leakage -- though granted, it may be overzealous.

Does the websockets package generally aim for the same property of running the destructors by refcount? If not, would you accept changes that make it so?

I do not have a minimal test case yet, hoping for a "yeah we changed X, you'll have to shut down more tightly by doing Y"; otherwise, I can try to assemble a test. More for my own reference and the very very curious: Public logs of the diverging behavior for [10](https://gitlab.com/aiocoap/aiocoap/-/jobs/1623608185) and [9.1](https://gitlab.com/aiocoap/aiocoap/-/jobs/1623695631), a minimal check in aiocoap's tests is conducted using `AIOCOAP_SERVER_TRANSPORT=ws python3 -m unittest tests.test_server.TestServerWS --failfast`.

**Comment by aaugustin** [comment]
Interesting.

If you're talking of an individual connection, that is, a `WebSocketServerProtocol` instance, I would suspect the fact that connections have a logger which have a reference to the connection:

https://github.com/aaugustin/websockets/blob/10.0/src/websockets/legacy/protocol.py#L221

I'd be open to tweaking this with a `weakref` to facilitate garbage collection.

But I think you're talking of  the `.close()` and `.wait_closed()` methods of the `WebSocketServer` object. That doesn't ring a bell.

I'm not seeing any objects provided by websockets in the reference cycles visible in the CI logs. Do some of the classes involved inherit classes provided by websockets?

**Comment by chrysn** [comment]
It's indeed something around the logging -- neutering the self.logger (by brutally assigning `self.logger = logging`) made my tests pass. Still looking for the precise cause for fix that's done with precision and not a butcher's knife.

Thanks for the pointer, I'll have a look whether a weakref or maybe something else around logging fixes things. (I've spent more time than I'd like to admit finding that lazy logs cause more trouble than they're worth, maybe it's something like that).

**Comment by chrysn** [comment]
Digging through this, I found the `self.logger.extra['websocket'] == self` extra that's set through the LoggerAdapter in the legacy implementation. (I'm using the legacy implementation? Gotta up my deprecation detection...).

Revisiting the deletion checks I noticed that I already *do* run the GC for these objects, but that it was the extra that lingered in the logs evaluated by the test suite that kept the socket alive for longer than needed.

As the records already need some stripping down (the `del record.websocket` line is in the good company of `del record.args` and `del record.exc_info`), I conclude that this is well fixed at my end, and not a change in websockets behavior that can in any way be blamed on the module.

Thanks for your help in finding this!

**Comment by aaugustin** [comment]
> Digging through this, I found the self.logger.extra['websocket'] == self extra that's set through the LoggerAdapter in the legacy implementation.

I think that's the code I linked to in my previous comment? ;-)

> (I'm using the legacy implementation? Gotta up my deprecation detection...).

Don't worry — this is the only existing implementation at this point; it isn't deprecated. I moved it to make room for a new one, but the new one doesn't exist yet :-)
