### ISSUE TITLE
Problems with update to websockets 10.0

### ISSUE THREAD

**Issue by oliver-zehentleitner** [aaugustin/websockets#1060]
Hello Augustin!

My library unicorn-binance-websocket-api connects to some endpoints of Binance.com and up to websockets 9.1 everything worked fine.

When we use websockets 10.0 all endpoints work except one.(To give the endpoint a name: binance.com-futures) The connection is established and confirmed, but no data comes over the socket connection.  However, PING/PONG are received.

The python-binance library "suffers" from the same phenomenon: https://github.com/sammchardy/python-binance/issues/1023

Here I have uploaded the logfiles for comparison, but the data does not help. I don't see any hint: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/199#issuecomment-932750828

Can you help me and explain what has changed in version 10.0 and could lead to such behavior? And what tests can we do to get better clues?

Thanks a lot, 
Oliver

**Comment by aaugustin** [comment]
This looks a lot like https://github.com/aaugustin/websockets/issues/1050#issuecomment-922330659 or https://github.com/aaugustin/websockets/issues/1046#issuecomment-918552350.

Basically, cryptocurrency exchanges support for compression settings appears to be buggy. They dislike an optimization I made in 10.0 to reduce memory usage. In the best case, they infringe the RFC in the opening handshake and websockets crashes loudly. In the worst case, they silently fail to send messages, which is utterly impossible to debug from the outside.

**Comment by oliver-zehentleitner** [comment]
Thank you very much! With that infos i can fix it!

**Comment by aaugustin** [comment]
I know the easy path is to workaround by disabling compression; that said it would be really useful if you were able to report this to Binance so they have a chance to fix it.

It's super easy to reproduce with websockets -- literally 5 lines of code, including setting logging to DEBUG. Maybe that'll help them fix their WebSocket implementation, or at least report the bug to the maintainers of the server they're using.

**Comment by oliver-zehentleitner** [comment]
you're right, i've been trying to contact them through different ways since yesterday! thank you very much!

**Comment by aaugustin** [comment]
Complete explanation here: https://github.com/aaugustin/websockets/issues/1065#issuecomment-938123309
