### ISSUE TITLE
Issue with v10, v9.1 works (Default Compression?)

### ISSUE THREAD

**Issue by simbaja** [aaugustin/websockets#1064]
I might perhaps be doing something incorrectly here, but I have some code that works on 9.1 but doesn't work on 10.  It connects, but then after 10 seconds (the connect timeout), it appears to just close the connection and cancels the async message iterator.  Looking at the FAQ, I thought it might be related to the asyncio.sleep(0) discussion (#867); however, even after 
adding that to the send function, it still didn't seem to work properly.

I then went looking through the issues and found #1050, #1057, and #1060.  Although my library isn't attempting to connect to crypto (it's for kitchen appliances :)), perhaps this is also a server side issue?  Disabling compression appears to resolve it, but I'm not sure if that's the root cause.  Is there anything additional I can try or any additional debugging that might illuminate the issue further to confirm it's a server side problem?

Code excerpt: 

```
        try:
            await self._set_state(GeClientState.CONNECTING)
            async with websockets.connect(self.endpoint) as socket:
                self._socket = socket
                self._setup_futures()
                await self._subscribe_all() #has a send
                await self._set_connected()
                await self._get_appliance_list() #has a send
                try:
                    async for message in CancellableAsyncIterator(socket, self._disconnect_requested):  #dies here without receiving
                        try:
                            await self._process_message(message)
                        except GeRequestError as err:
                            _LOGGER.exception("Could not process request")
                except websockets.WebSocketException:
                    _LOGGER.error("Unknown error reading socket")
                except RuntimeError as err:
                    #do nothing if it's a StopAsyncIteration, we just stopped the iteration
                    #as part of the disconnect
                    if not isinstance(err.__cause__, StopAsyncIteration):
                        raise
        finally:
            self._teardown_futures()
            await self._disconnect()
```

Full code is here: https://github.com/simbaja/gehome/blob/master/gehomesdk/clients/websocket_client.py.

Please let me know if there's anything else I can provide to aid in analysis/resolution.  Thanks in advance for any assistance you can provide.

**Comment by aaugustin** [comment]
api.brillon.geappliances.com appears to be hosted by AWS so this is very likely the same as https://github.com/aaugustin/websockets/issues/1065#issuecomment-938123309. Let's follow up over there.
