### ISSUE TITLE
Cors support

### ISSUE THREAD

**Issue by gianlnicc** [aaugustin/websockets#107]
There's no working example of a working cors websocket server.
I have tried with origins="'*'" but withou success.

**Comment by aaugustin** [comment]
The only way to use this library is cross-origin: it cannot serve HTTP requests, only websockets. So I'm a bit confused by your question. Furthermore, my crystal ball failed to show me your code — it's flaky tonight.

If you think there's a bug in websockets, could you provide a description of the problem you're seeing as well as reproduction instructions, sample code, and anything else that could help me figure out what you're talking about? Thanks.

**Comment by gianlnicc** [comment]
I think I have an issue with javascript library socket.io client, it start first a longpolling connection and give me a cors error.

**Comment by aaugustin** [comment]
I'm sorry if my first message wasn't clear enough. There's no way I can help you with so little information. Either provide a proper bug report or stop wasting my time. Thanks.
