### ISSUE TITLE
Error in importing Module

### ISSUE THREAD

**Issue by aeroaks** [aaugustin/websockets#108]
I am running Python 3.5.1 on Windows in virtual environment. I installed `websockets` using `pip`.

When I try to import the websockets library I get the following error:
```
>>> import websockets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "*\websocket_app\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "*\websocket_app\websockets\client.py", line 10, in <module>
    from exceptions import InvalidHandshake
ImportError: No module named 'exceptions'
```

**Comment by aaugustin** [comment]
The exception you're getting doesn't match the current source code:

    from .exceptions import InvalidHandshake

You must have accidentally modified your local installation.

**Comment by aeroaks** [comment]
Thanks for the comment! My mistake!
