### ISSUE TITLE
How can I send message to a specific client

### ISSUE THREAD

**Issue by Pidbid** [aaugustin/websockets#1083]
Problem description:
    You know, There may be many connections at the same time. But I just want to sand specific message to specific client. What shoule I do? Thanks

What I'm doing:
    It is a chat room, One user can send messages to another user …… It's just like send_to([id...])

**Comment by aaugustin** [comment]
It depends.

If you never intend to run more than one process, you can just store a mapping of "client identifier" => "websocket connection" in a dict:

```python
    connected = {}

    async def handler(websocket):
        # Register.
        connected[<identifier>] = websocket
        try:
            # Do stuff...
        finally:
            # Unregister.
            del connected[<identifier>]
```

If you may run more than one process, then you need some sort of interprocess communication, maybe based on a publish / subscribe system.

**Comment by aaugustin** [comment]
Marking as a documentation issue because this should be addressed in the FAQ, in common patterns, or maybe with a full example.

**Comment by fillwithjoy1** [comment]
Updating from aagustin's example, you need to use the await <client>.send(message). If you need to send to all clients in a list/dict use <client_list/dict>.broadcast(message)
