### ISSUE TITLE
Subscribing and using send/recv concurrently

### ISSUE THREAD

**Issue by valentino-sm** [aaugustin/websockets#1088]
I would like to subscribe for continuous messages from the server and use regular send/recv approach for interaction at the same time.
Here is problem. I can't use synchronous way because I can't be sure the message I got is related to this particular request.
```python
ws.send(message)
result = await ws.recv()
```
What is the preferred way for implementing with?
Use two different websockets separately? Or split general stream of messages from one websocket and handling them differently? In that way I should find suitable answer for particular request in the stream.

**Comment by aaugustin** [comment]
What about using HTTP for the stream with request/response semantics and WebSocket for the subscription stream?

**Comment by valentino-sm** [comment]
> What about using HTTP for the stream with request/response semantics and WebSocket for the subscription stream?

Thank you! Seems it is most logical one. But performance? I'm not sure but requests should be much faster using opened websocket connection comparing to raw http. Speed is very sensitive in my case

**Comment by aaugustin** [comment]
I'm not expecting a large difference between a HTTP connection (with keepalive enabled, which browsers do by default) and a WebSocket connection, especially a HTTP/2 connection. The main difference is that HTTP headers are larger than headers of individual WebSocket frames.

Else, it's up to you to build a mechanism to match requests to response. HTTP/2 provides such a mechanism, hence my suggestion to go with HTTP.
