### ISSUE TITLE
A request, multiple responses, how the client receives it

### ISSUE THREAD

**Issue by mlip-m** [aaugustin/websockets#1091]
When the client sends a request, the server returns multiple answer data and how the client receives it

**Comment by aaugustin** [comment]
There are no concepts of "request" or "response" in websockets, just messages sent in one direction of the others.

If you want to have one asyncio task sending the "requests" and another task reading "responses", look at https://websockets.readthedocs.io/en/stable/howto/patterns.html#consumer-and-producer (you need to read what comes earlier in the page to understand this section).

If you just want to send a "request" and read a number of "responses":

```python

await websocket.send(request)
async for response in websocket:
    ... # do stuff with response
    if this_is_the_last(response).for_this(request):
        break
```
