### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

### ISSUE THREAD

**Issue by shexiaoheng** [aaugustin/websockets#1092]
```python
import asyncio
import json
import time

import websockets


def create_req_body(r_id, method, params):
    data = {
        "jsonrpc": "2.0",
        "id": r_id,
        "method": method,
        "params": params
    }
    return json.dumps(data)


async def do_wss(url):
    req_json = create_req_body(1, "eth_subscribe", ["newHeads"])
    async with websockets.connect(url) as wss:
        await wss.send(req_json)
        subscription_response = await wss.recv()
        print(subscription_response)
        subscribe_result = json.loads(subscription_response)['result']
        req_json = create_req_body(2, "eth_unsubscribe", [subscribe_result])
        start_time = int(time.time())
        end_time = start_time + 5
        while end_time > int(time.time()):
            recv_data = await wss.recv()
            print(recv_data)
            print('\n')
        await wss.send(req_json)
        unsubscription_response = await wss.recv()
        print(unsubscription_response)


class TestWSS:

    def test_wss(self):
        url = 'xxxxx'
        asyncio.get_event_loop().run_until_complete(do_wss(url))
```

I use the above code, everything is normal under python3.8.10, but this error is reported when running under python3.9.7: ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c : 1129)

![image](https://user-images.githubusercontent.com/3015681/142617528-aaa1f9f2-f476-43a3-be71-6440a67a1b59.png)

I checked the FAQ, setting ssl=None or ssl=False will encounter the error "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400". Setting ssl=True will report the same error as above without ssl.

**Comment by aaugustin** [comment]
Can you open a connection with https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection without involving websockets?

If you have the same results with asyncio and with websockets (and I suspect you will), then the problem isn't at the layer of websockets.

**Comment by shexiaoheng** [comment]
The problem has been solved, refer to: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
