### ISSUE TITLE
consumer_handler not being called.

### ISSUE THREAD

**Issue by gitgitwhat** [aaugustin/websockets#1093]
I have a client app that is based on the code that used to be here: https://websockets.readthedocs.io/en/stable/intro/index.html#both-sides.  During the connect_handler, I spin up a thread to do some initialization and send off the first message to the server.  The server then responds appropriately.  However, my consumer_handler routine is never called and the debug output does not show the message was received but I can clearly see the server response in Wireshark.

```
	async def consumer_handler(self, websocket, path):
		try:
			async for message in websocket:
				print(message)
				await self.process_message(message)
		except Exception as e:
			print(e)

	async def producer_handler(self, websocket, path):
		try:
			while True:
				message = await self.producer()
				await websocket.send(message)
		except Exception as e:
			print(e)

	async def connect_handler(self, websocket, path):
		'''This simply schedules the sequential execution of the producer_task
		and consumer_task. It does NOT run them in parallel!'''
		consumer_task = asyncio.ensure_future(self.consumer_handler(websocket, path))
		producer_task = asyncio.ensure_future(self.producer_handler(websocket, path))

		if self.cb_connected is not None:
			t1 = threading.Thread(target=self.cb_connected)
			t1.start()

		done, pending = await asyncio.wait(
			[consumer_task, producer_task],
			return_when=asyncio.FIRST_COMPLETED,
		)

		for task in pending:
			task.cancel()
```

Here is the debug output.  After my first message is sent, it just hangs because the server message was never processed.

```
= connection is CONNECTING
> GET / HTTP/1.1
> Host: ...
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Key: ...
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Extensions: permessage-deflate; server_max_window_bits=12; client_max_window_bits=12
> User-Agent: Python/3.8 websockets/10.0
< HTTP/1.1 101 Switching Protocols
< Connection: Upgrade
< Upgrade: websocket
< Sec-WebSocket-Accept: ...
= connection is OPEN
DBG: connected callback
> TEXT '<INIT_MESSAGE_TO_SERVER>' [136 bytes]
```

It's probably a design issue on my end and not a websockets problem but I'm not sure what's wrong.  Do you think you can extend your examples to add a more robust client example?  Something that doesn't just connect, send, recv and exit but instead continues to run and is able to send or recv arbitrary messages?  Thanks.

**Comment by aaugustin** [comment]
Does https://websockets.readthedocs.io/en/stable/howto/faq.html#i-m-having-problems-with-threads help?

**Comment by gitgitwhat** [comment]
Changing the thread to `call_soon_threadsafe` results in the callback never even being called.


```
self.loop = asyncio.get_event_loop()
asyncio.set_event_loop(self.loop)
self.loop.call_soon_threadsafe(self.cb_connected)
```

Again, Python is not my strongest language so I'm sure I'm messing something else up.

**Comment by aaugustin** [comment]
This discussion is more "learning how asyncio works" that "websockets doesn't work". I'm sorry, I can't make time to help with that.
