### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

### ISSUE THREAD

**Issue by NevilleLongedBottom** [aaugustin/websockets#1096]
Hi mate,

Apologies if your repeating yourself but im honestly getting desperate for help lol. When connecting the attached code to WSS, i get the following error: 'TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary' for the below code. More specifically in this para: 
```
 def main():
    event_filter = contract.events.PairCreated.createFilter(fromBlock='latest')
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            asyncio.gather(
                log_loop(event_filter,2 )))
         
    finally:
        loop.close()
```

I would truly appreciate a review of the code whenever you get a second as im exchausting all options lol.

Let me know if you need more code etc, Cheers

**Comment by aaugustin** [comment]
Well I'm not seeing anything related to websockets in that code and the error you're reporting is raised by asyncio.

Can you confirm you have the latest version of websockets installed?

**Comment by NevilleLongedBottom** [comment]
> Well I'm not seeing anything related to websockets in that code and the error you're reporting is raised by asyncio.
> 
> Can you confirm you have the latest version of websockets installed?

Hi Augustin cheers for the reply, current version is 1.2.1. Im connecting to a node via WS earlier in the code so nothing visible in the attached code.

**Comment by aaugustin** [comment]
Probably you're looking at the version of another library because websockets never had a version 1.2.1: https://websockets.readthedocs.io/en/stable/project/changelog.html

**Comment by paniccia-taurob** [comment]
I had the same, it went away updating to version 10.1.
