### ISSUE TITLE
Implement a synchronous send/recv loop without having to re-connect

### ISSUE THREAD

**Issue by breakds** [aaugustin/websockets#1097]
Hi the websockets community!

Apologize for opening a ticket to ask a question - I am not sure about a better way and I have searched online/inside this github repo and cannot find the answer.

Here is a toy example where each time `game.step()` is called, it will (await) send a message and (await) receive a message. 

```python
import asyncio
import time
import websockets


class Game(object):
    def __init__(self):
        self._count = 0

    async def step(self):
        self._count += 1
        async with websockets.connect('ws://localhost:8001/') as ws:
            await ws.send(str(self._count))            
            message = await ws.recv()
            print(f'Received "{message}".')

def main():
    game = Game()
    while True:
        asyncio.run(game.step())
        time.sleep(1)

if __name__ == "__main__":
    main()
```
The problem with this is that every time when `game.step()` is called, apparently the weboscket connection will be dropped and re-created. Forgive my ignorance in `asyncio`, I made several attempts but still cannot get this work. Can anyone give some suggestions? Thanks!

**Comment by lgrahl** [comment]
Here's how it can be done (untested but should do). There are of course other ways.

```python
import asyncio
import websockets


class Game:
    def __init__(self, ws):
        self._ws = ws
        self._count = 0

    async def step(self):
        self._count += 1
        await self._ws.send(str(self._count))            
        message = await self._ws.recv()
        print(f'Received "{message}".')

async def loop():
    async with websockets.connect('ws://localhost:8001/') as ws:
        game = Game(ws)
        while True:
            await game.step()
            await asyncio.sleep(1)

if __name__ == "__main__":
    asyncio.run(loop())
```

Even though this issue doesn't have much to do with asyncio, you were using `time.sleep`, so I strongly suggest reading into asyncio. :slightly_smiling_face:

**Comment by breakds** [comment]
> Here's how it can be done (untested but should do). There are of course other ways.
> 
> ```python
> import asyncio
> import websockets
> 
> 
> class Game:
>     def __init__(self, ws):
>         self._ws = ws
>         self._count = 0
> 
>     async def step(self):
>         self._count += 1
>         await self._ws.send(str(self._count))            
>         message = await self._ws.recv()
>         print(f'Received "{message}".')
> 
> async def loop():
>     async with websockets.connect('ws://localhost:8001/') as ws:
>         game = Game(ws)
>         while True:
>             await game.step()
>             await asyncio.sleep(1)
> 
> if __name__ == "__main__":
>     asyncio.run(loop())
> ```
> 
> Even though this issue doesn't have much to do with asyncio, you were using `time.sleep`, so I strongly suggest reading into asyncio. slightly_smiling_face

Thanks! The problem with this pattern is that I cannot offer the class `Game` to the user as the other game. Ideally, I want the websocket to be encapsulated in `Game` so that the user does not have to know about it. Is this still possible?

Thank you!

**Comment by lgrahl** [comment]
Okay, I'll provide another hint since it's not trivial to figure out how to wrap the async context manager (`async with`).

```python
import asyncio
import websockets


class Game:
    def __init__(self):
        self._count = 0

    async def __aenter__(self):
        self._ws = await websockets.connect('ws://localhost:8001/')
        return self

    async def __aexit__(self, *_):
        await self._ws.close()

    async def step(self):
        self._count += 1
        await self._ws.send(str(self._count))            
        message = await self._ws.recv()
        print(f'Received "{message}".')

async def loop():
    async with Game() as game:
        while True:
            await game.step()
            await asyncio.sleep(1)

if __name__ == "__main__":
    asyncio.run(loop())
```

Maybe you want to add this to the patterns, @aaugustin?

**Comment by breakds** [comment]
> Okay, I'll provide another hint since it's not trivial to figure out how to wrap the async context manager (`async with`).
> 
> ```python
> import asyncio
> import websockets
> 
> 
> class Game:
>     def __init__(self):
>         self._count = 0
> 
>     async def __aenter__(self):
>         self._ws = await websockets.connect('ws://localhost:8001/')
>         return self
> 
>     async def __aexit__(self, *_):
>         await self._ws.close()
> 
>     async def step(self):
>         self._count += 1
>         await self._ws.send(str(self._count))            
>         message = await self._ws.recv()
>         print(f'Received "{message}".')
> 
> async def loop():
>     async with Game() as game:
>         while True:
>             await game.step()
>             await asyncio.sleep(1)
> 
> if __name__ == "__main__":
>     asyncio.run(loop())
> ```
> 
> Maybe you want to add this to the patterns, @aaugustin? Could use some improvement so it's also usable without the context manager.

Nice! Good idea to have a context manager like this. Thanks a lot for the help :) This should work with minimal change on my use case.

> Maybe you want to add this to the patterns

I think this pattern can be generally useful too.

**Comment by breakds** [comment]
> Okay, I'll provide another hint since it's not trivial to figure out how to wrap the async context manager (`async with`).
> 
> ```python
> import asyncio
> import websockets
> 
> 
> class Game:
>     def __init__(self):
>         self._count = 0
> 
>     async def __aenter__(self):
>         self._ws = await websockets.connect('ws://localhost:8001/')
>         return self
> 
>     async def __aexit__(self, *_):
>         await self._ws.close()
> 
>     async def step(self):
>         self._count += 1
>         await self._ws.send(str(self._count))            
>         message = await self._ws.recv()
>         print(f'Received "{message}".')
> 
> async def loop():
>     async with Game() as game:
>         while True:
>             await game.step()
>             await asyncio.sleep(1)
> 
> if __name__ == "__main__":
>     asyncio.run(loop())
> ```
> 
> Maybe you want to add this to the patterns, @aaugustin? Could use some improvement so it's also usable without the context manager.

Not sure whether this is worth mentioned as a pattern, I found a solution after studying the asyncio and async generators:

```python
import asyncio
import time
import websockets


async def make_ws_generator():
    async with websockets.connect('ws://localhost:8001/') as ws:
        message = yield None
        while True:
            await ws.send(message)
            response = await ws.recv()
            message = yield response

class Game(object):
    def __init__(self):
        self._count = 0
        self._ws = None

    async def step(self):
        if self._ws is None:
            self._ws = make_ws_generator()
            _ = await self._ws.__anext__()
            
        self._count += 1
        message = await self._ws.asend(str(self._count))
        print(f'Received "{message}".')

def main():
    game = Game()
    while True:
        asyncio.get_event_loop().run_until_complete(game.step())
        time.sleep(1)

if __name__ == "__main__":
    main()
```

Here `main()` is purely synchronous.

**Comment by lgrahl** [comment]
I would not consider that a viable approach. First of all, you're continuously interrupting the event loop, so things may or may not complete. Secondly, you're back to creating new connections with every step.

If your code has to work synchronously, then consider dispatching from another thread to an event loop that is continuously running. See the asyncio docs on how to do this safely.

**Comment by breakds** [comment]
> I would not consider that a viable approach. You're continuously interrupting the event loop, so things may or may not complete.
> 
> If your code has to work synchronously, then consider dispatching from another thread to an event loop that is continuously running. See the asyncio docs on how to do this safely.

Thanks for the notes - I understand that this can potentially interact badly if there are other async code running in the event loop. Do you suggest having a specific thread dedicate to the event loop that runs the game related code?
