### ISSUE TITLE
Having client waiting for asynchronous incoming messages from server while sending to server

### ISSUE THREAD

**Issue by gilles380** [aaugustin/websockets#1098]
Hi,
and first, congrats  for the great job with this WS API  !

I wonder about the FAQ section : 
**How do I stop a client that is continuously processing messages**

```python
async def client():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket:
        # Close the connection when receiving SIGTERM.
        loop = asyncio.get_running_loop()
        loop.add_signal_handler(
            signal.SIGTERM, loop.create_task, websocket.close())

        # Process messages received on the connection.
        async for message in websocket:
            ...
asyncio.run(client())
```

which  is working fine, making the client to indefinitely wait for asynchonous incoming message from server

Then, I wonder if it is possible to implement the sending part, using the SAME connection   (the one created when calling ** async with websockets.connect(uri) as websocket:  ** code)
> meaning, doing two things in parallel, as stated in the FAQ, but not enough skills using asyncio, I can't figure out how

Thanks for your feedback

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/howto/patterns.html#consumer-and-producer should give you an idea of how to do two things in parallel.

**Comment by breakds** [comment]
Thanks a lot for the prompt guidance!

**Comment by gilles380** [comment]
Ok, 
then, I can understand the server part calling  the handler in your example :
async with websockets.serve(handler, "", 8001):
....

But, regarding Client side , after connection is done : 
async def client():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket:

**Awaiting :func:`connect` yields a :class:`WebSocketClientProtocol` which can then be used to send and receive messages.**

Can't figure out how bind the consumer/producer handler you pointed out in the FAQ :
async def handler(websocket):
    await asyncio.gather(
        consumer_handler(websocket),
        producer_handler(websocket),
    )

 to the connected websocket

**Comment by aaugustin** [comment]
```python
async def do_thing_one(websocket):
    async for message in websocket:
        ...

async def do_thing_two(websocket):
    while True:
        await websocket.send("blabla")
        await asyncio.sleep(3)

async def client():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket:
        await asyncio.gather(
            do_thing_one(websocket),
            do_thing_two(websocket),
        )

asyncio.run(client())
```

**Comment by gilles380** [comment]
Thanks a lot for the tips !
