### ISSUE TITLE
Logging customziation

### ISSUE THREAD

**Issue by zbz95** [aaugustin/websockets#1099]
Hello! Thank you very much for this wonderful library! 

Recently I have started using this library as a client that listens to messages from server. I set logging level to debug to track the time between ping/pongs, reconnection times etc. But the problem is that debug level also logs all the messages sent from server and server sends a lot of messages ~ thousands per second so it becomes uncomfortable tracking information I need.

Is it possible to filter logging messages and have only ping pong, connection status messages?

Before creating this issue I read the source code and came to conclusion that in order to achieve what I want I need to change this line in frames.py :  
```
if self.debug:
    self.logger.debug("< %s", frame)
```

to:

```
if self.debug:
    if frame.opcode != OP_TEXT:
          self.logger.debug("< %s", frame)
```
Am I right? Maybe filtering log messages would be useful to others also and can be added as a feature?

**Comment by aaugustin** [comment]
This is a valid request.

The opposite request — "I want to see messages but not the noise of protocol-level concerns like handshakes and ping/pongs" — is equally valid. As a consequence, I cannot make everyone happy just by playing with log levels.

Your options here are:

- configure a [filter](https://docs.python.org/3/library/logging.html#filter-objects) to remove the logs you don't want and add it to the `websockets` logger
- implement your own logs for things you care about e.g. see the example of measuring latency at the bottom of [this page](https://websockets.readthedocs.io/en/stable/topics/timeouts.html)
