### ISSUE TITLE
connection timed out after few minutes

### ISSUE THREAD

**Issue by gencer** [aaugustin/websockets#110]
I have a definition like this:

```
 while True:
        if not websocket.open:
            await req.close()
            return
            message = await websocket.recv()
```

And few minutes later if i stay idle i get this on server and disconnect user:

```
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
```

How can avoid this and stay connected as long as possible?

**Comment by aaugustin** [comment]
You should wrap `await websocket.recv()` in a task with a timeout. asyncio provides APIs for that.

If the timeout is reached, `await websocket.ping()` and let `while True` loop resume.

I suggest using 25 seconds for the timeout as many systems close idle connections after 30 seconds.

(I'm interested in hearing whether that solution actually works. Perhaps I should document it better.)

**Comment by gencer** [comment]
@aaugustin are you talking about `asyncio.timeout(timeout, *, loop=None)` ? Perhaps an example for your suggestion :)

**Comment by aaugustin** [comment]
Yes, that's the easier way to achieve the desired timeout here.

I thought it was added in Python 3.5 but apparently it also exists in 3.4 (and I don't think 3.3 matters much these days).

**Comment by gencer** [comment]
My python version is 3.5 so, It won't be a problem for me. I will test this ASAP.

Thanks!

**Comment by gencer** [comment]
I solved by issue as you suggested.

Thanks.

Case closed now.

**Comment by aaugustin** [comment]
Actually I'd like to keep this issue around to check if I can improve documentation.

**Comment by gencer** [comment]
@aaugustin: Actually i'll (and others) appreciate if you can document this subject as you stated. In fact, I fixed already but still need some document to check if i did the correct way.

**Comment by aaugustin** [comment]
This will be built-in if #449 gets merged.
