### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

### ISSUE THREAD

**Issue by baplec** [aaugustin/websockets#1100]
Hi, i will need help one this :)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4892/1595696696.py in <module>
----> 1 ts = bsm.trade_socket('BNBBTC')

~\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\streams.py in trade_socket(self, symbol)
    624         """
    625 
--> 626         return self._get_socket(symbol.lower() + '@trade')
    627 
    628     def aggtrade_socket(self, symbol: str):

~\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\streams.py in _get_socket(self, path, stream_url, prefix, is_binary, socket_type)
    344         conn_id = f'{socket_type}_{path}'
    345         if conn_id not in self._conns:
--> 346             self._conns[conn_id] = ReconnectingWebsocket(
    347                 loop=self._loop,
    348                 path=path,

~\AppData\Local\Programs\Python\Python310\lib\site-packages\binance\streams.py in __init__(self, loop, url, path, prefix, is_binary, exit_coro)
     60         self.ws: Optional[ws.WebSocketClientProtocol] = None
     61         self.ws_state = WSListenerState.INITIALISING
---> 62         self._queue = asyncio.Queue(loop=self._loop)
     63         self._handle_read_loop = None
     64 

~\AppData\Local\Programs\Python\Python310\lib\asyncio\queues.py in __init__(self, maxsize, loop)
     31 
     32     def __init__(self, maxsize=0, *, loop=mixins._marker):
---> 33         super().__init__(loop=loop)
     34         self._maxsize = maxsize
     35 

~\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py in __init__(self, loop)
     15     def __init__(self):
     16         if loop is not _marker:
---> 17             raise TypeError(
     18                 f'As of 3.10, the *loop* parameter was removed from '
     19                 f'{type(self).__name__}() since it is no longer necessary'

TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

**Comment by aaugustin** [comment]
This question was asked and answered before in this bug tracker. See also: https://websockets.readthedocs.io/en/stable/project/contributing.html#cryptocurrency-users

**Comment by baplec** [comment]
Ok I can understand your opinion on crypto, thank you anyway
