### ISSUE TITLE
Performance degradation, disconnections and odd behavior

### ISSUE THREAD

**Issue by budleigh** [aaugustin/websockets#1101]
Hi there, fairly new to this library. I wrote a pretty substantial bit of server code with websockets over the weekend and, upon testing, found that connection behavior was sporadic and exceedingly slow. In particular, connecting several clients to a server seems to result in some sort of deathmatch, where certain connections dominate the runtime while others appear only very intermittently but ultimately peter out and die. After a few minutes, all connections are simply closed. This is all running on a localhost loopback.

I whittled things down until I was running no more than the basic tutorial instance for the library, i.e. bypassing all of the code I'd written on top of it:

```python
import asyncio
import websockets
import logging

async def test(socket):
    async for message in socket:
        print(message)


async def main():
    async with websockets.serve(test, 'localhost', 8079):
        await asyncio.Future()

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    asyncio.run(main())
```

The clients I'm running are simple browser-native websocket instances running in a few browser tabs. Specifically, they connect to the server and then send some data back at some short interval (I tested several, from 16 milliseconds to 4 seconds).

```javascript
const socket = new WebSocket(wsUrl);

socket.onmessage = (event) => {
  console.info(event.data);
};

const id = uuidv4();  // any random string
let lastPush = 0;
const tick = (timestamp) => {
  const sinceLastPush = timestamp - lastPush;
  if (sinceLastPush >= PUSH_INTERVAL) {
    socket.send(`ping: ${id}`);
    lastPush = timestamp;
  }

  window.requestAnimationFrame(tick);
}

window.requestAnimationFrame(tick);
```

[Here's an example conversation between the server and two clients](https://pastebin.com/Pk9jYs2N), `fbb5f8cb-e6ec-4132-8d6a-54f0c9153c03` and `995bb0df-66eb-468e-8bb5-c634c40bb707`, with `PUSH_INTERVAL` set to 2000 milliseconds (and log level set to DEBUG for fun). You can see that even at a frequency of one message every two seconds, things get messy pretty much instantly: fbb5 disappears for long periods of time and the reappears just as suddenly. This ran for about 3 minutes. I know that asynchronous runtimes handling IO operations are fundamentally unpredictable, but I think this is unusual.

[Here's another conversation between the server and three clients pinging at an interval of 128 milliseconds](https://pastebin.com/seaS7RHa). This one is much more stark - `fe4b97b2-22ad-44b0-a787-271ff21bc175` takes over aggressively. Not visible, though, is the behavior I occasionally observe where at 3+ clients the messages literally almost chug to a halt. This doesn't always happen. Also unpredictable were disconnects: sometimes this melee seemed to result in several disconnections of what seemed to be a totally healthy variety (no error messages, like the server just quietly sent a close frame for some reason), but sometimes it didn't.

I'm not sure where I could've gone wrong having minimized the test case to what amounts to the tutorial listing running on localhost. I tried different Python runtimes (3.10, 3.9, 3.7) with the same results. I've ensured that my browser clients are behaving in the expected way. This is a lot of writing for what I'm sure will amount to something fundamental I've overlooked or some other environmental issue. Can anyone else reproduce this, or notice what I got wrong?

Thanks.

*editing for more details:
- Windows 10 (10.0.19044 Build 19044) ~~<-- possibly the problem?~~ I've reproduced this exactly on macOS 12.0.1.
- websockets @ 10.1
- Python @ 3.10, 3.9, 3.7

**Comment by budleigh** [comment]
Closing as I was able to reproduce this in an entirely different framework in an entirely different language (go + gorilla WebSocket). I must be getting throttled by the browser or something.

**Comment by aaugustin** [comment]
Phew. Thanks for figuring it out by yourself. I wasn't quite sure how to help 😅

**Comment by budleigh** [comment]
FWIW, it **is** the case that the browser throttles sockets on tabs that aren't active! That may be in the specification somewhere but I didn't see it on MDN. The solution, I guess, is to run them in workers. Anyways, thanks for a great library.
