### ISSUE TITLE
Add option to disable ipv6 socket

### ISSUE THREAD

**Issue by budleigh** [aaugustin/websockets#1102]
Hi there again,

I ran into some issues running a `websockets` server in a Docker container (specifically via the image `python:3.8.12-alpine3.15`). I get this error: ```OSError: [Errno 99] error while attempting to bind on address ('::1', 8080, 0, 0): address not available```.

There are certainly circumstances beyond a Docker container where IPv6 would not be available - because `create_unix_server` is being called inside `websockets.serve()` without an explicit socket family, it assumes `socket.AF_UNSPEC`, which resolves to both `AF_INET` and `AF_INET6`. My workaround was to call `server.serve()` with a keyword argument `family=socket.AF_INET`, which does work, but I felt it was a bit non-obvious. I didn't see any reference to the fact that general socket arguments are essentially passed through to asyncio's server factories.

Not a huge issue but wanted to raise as maybe needing at least some documentation.

**Comment by aaugustin** [comment]
It's indirectly documented here: https://websockets.readthedocs.io/en/stable/howto/faq.html#how-do-i-set-which-ip-addresses-my-server-listens-to

> How do I set which IP addresses my server listens to?
> 
> Look at the host argument of create_server().
> 
> serve() accepts the same arguments as create_server().

and there: https://websockets.readthedocs.io/en/stable/reference/server.html#websockets.server.serve:

> Any other keyword arguments are passed the event loop’s create_server() method.
> 
> For example:
> 
> You can set ssl to a SSLContext to enable TLS.
> 
> You can set sock to a socket that you created outside of websockets.

I'll look into improving these docs to cover this use case. Thanks for reporting this.

**Comment by aaugustin** [comment]
Thanks for reporting this. It could be quite common!
