### ISSUE TITLE
OSError from Raspberry Pi

### ISSUE THREAD

**Issue by ThatXliner** [aaugustin/websockets#1107]
## Situation

I have program A (the WebSocket client) that spawns program B within it (the WebSocket server).

(This is because I'm using WebSockets for [IPC](https://en.wikipedia.org/wiki/Inter-process_communication)).

Sure I could refactor program B into a daemon but I really don't want to (but if that's the only solution, it's totally doable)

## Problem

But attempting to connect 1 second after I spawn the child process results in `OSError`. This even happens with `await asyncio.sleep(10)` or even using custom re-connection code (because I don't want to [loop forever](https://github.com/aaugustin/websockets/blob/668f320e0547d80afe6529528e1ecc6088955cdc/src/websockets/legacy/client.py#L596)):
```py
async def main():
    BACKOFF_MIN = 1.0
    BACKOFF_MAX = 20.0
    BACKOFF_FACTOR = 1.5
    BACKOFF_DELAY = BACKOFF_MIN
    while True:
        try:
            async with connect(...) as connection:
                ...
        except OSError:
            BACKOFF_DELAY = BACKOFF_DELAY * BACKOFF_FACTOR
            await asyncio.sleep(BACKOFF_DELAY)
        else:
            break
```

But it just hangs and never actually connects.

Now here's the worst part: this only happens with my Raspberry Pi. Any help?

**Comment by ThatXliner** [comment]
More info: it works when starting the server and client in a separate process...

**Comment by aaugustin** [comment]
I would recommend you try opening just TCP connections with `asyncio.open_connection` and `asyncio.create_server` instead of WebSocket connections.

If you hit the same issue, and I expect you will hit the same issue, then you can rule out websockets as a cause.

**Comment by RemiCardona** [comment]
I would also suggest actually printing out the `OSError` exception, that should give you more clues as to what is actually happening.

**Comment by aaugustin** [comment]
A bit of background on my comment — I'm pretty sure this happens because you fork after creating the event loop, which results in an unusable event loop in the child. This explains what you're reporting. But it's a wild guess based on insufficient context.

**Comment by ThatXliner** [comment]
It's saying something like `connect call failed ::1`

**Comment by ThatXliner** [comment]
> I would recommend you try opening just TCP connections with `asyncio.open_connection` and `asyncio.create_server` instead of WebSocket connections.
> 
> If you hit the same issue, and I expect you will hit the same issue, then you can rule out websockets as a cause.

With

```py
# a.py
import asyncio
import signal
import sys


async def main():
    proc = await asyncio.create_subprocess_exec(sys.executable, "b.py")
    # print(proc)
    # await asyncio.sleep(2)
    BACKOFF_MIN = 1.5
    BACKOFF_MAX = 20.0
    BACKOFF_FACTOR = 1.5
    BACKOFF_DELAY = BACKOFF_MIN
    while True:
        print("Connecting...")
        try:
            reader, writer = await asyncio.open_connection("127.0.0.1", 1234)
            print("Connected!")
            print("writing")
            writer.write(b"Hello world")
            await writer.drain()
            print("recieving...")
            response = await reader.read()
            print(response)
            assert response == b"Hello world"
        except OSError:
            BACKOFF_DELAY = BACKOFF_DELAY * BACKOFF_FACTOR
            print(f"Re-connecting in {BACKOFF_DELAY} seconds")
            await asyncio.sleep(BACKOFF_DELAY)
        else:
            break
    proc.send_signal(signal.SIGTERM)
    await proc.wait()


if __name__ == "__main__":
    asyncio.run(main())
```

and

```py
# b.py

import asyncio
import signal


async def handle_echo(reader, writer):
    writer.write(await reader.read(1024))
    await writer.drain()
    writer.close()


async def main():
    server = await asyncio.start_server(handle_echo, "127.0.0.1", 1234)
    task = asyncio.create_task(server.serve_forever())
    asyncio.get_event_loop().add_signal_handler(signal.SIGTERM, task.cancel)
    try:
        await task
    except asyncio.exceptions.CancelledError:
        pass


if __name__ == "__main__":
    asyncio.run(main())
```

It works on both raspberry pi and my computer.

**Comment by aaugustin** [comment]
Thank you. Would you mind providing the equivalent code using websockets, which doesn't work on Raspberry Pi, so can try to reproduce?

**Comment by ThatXliner** [comment]
Weird... I'm going to investigate further

**Comment by ThatXliner** [comment]
Ok it appears that my set up in the raspberry pi wasn't exactly the same as the one in the host. I solved it now.
