### ISSUE TITLE
"Malformed HTTP message" when using WSS

### ISSUE THREAD

**Issue by dbrgn** [aaugustin/websockets#111]
I'm using this test script:

``` python
#!/usr/bin/env python

import ssl
import asyncio
import websockets
import logging

logging.basicConfig(level=logging.DEBUG)

async def hello(websocket, path):
    name = await websocket.recv()
    print("< {}".format(name))

    greeting = "Hello {}!".format(name)
    await websocket.send(greeting)
    print("> {}".format(greeting))

context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(certfile='cert.pem')
context.set_ciphers('RSA')

start_server = websockets.serve(hello, 'localhost', 8764, ssl=context)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

The keypair I'm using is self-signed.

When connecting from a web browser through wss, I get the following error:

``` javascript
> var ws = new WebSocket("wss://localhost:8764");
2016-05-17 11:20:59.148 WebSocket connection to 'wss://localhost:8764/' failed: WebSocket opening handshake was canceled
```

And on the server side:

```
$ python server.py 
DEBUG:asyncio:Using selector: EpollSelector
INFO:websockets.server:Exception in opening handshake: Malformed HTTP message
```

I assume the browser closes the connection because the server certificate is untrusted. But there is no error message saying so.

Is there a way to emit a better / more helpful error message in this case?

**Comment by aaugustin** [comment]
In the scenario you're describing, the browser decides it doesn't like the certificate offered by the server, closes the connection, and doesn't quite tell you why.

The server doesn't know why the connection dropped. A network failure would have the same effect. Presuming that it's always a certificate error could be misleading in cases where it isn't.

The browser knows why it dropped the connection and should tell it. That's an issue with the browser, not with `websockets`.

Please let me know if you disagree with my analysis or see a way to improve the situation by making changes in `websockets`!

**Comment by dbrgn** [comment]
I see, thanks for the explanation! Would it be possible to indicate the difference between a "connection close" and a "malformed http message"?

**Comment by aaugustin** [comment]
Not sure, but that's worth investigating.

**Comment by aaugustin** [comment]
I tried reproducing this issue and I'm no longer getting a message at all in the server logs, perhaps due to changes in `asyncio` or in `websockets`. I think I'll leave it there.

**Comment by aaugustin** [comment]
For future reference my test script:

```python
#!/usr/bin/env python

import asyncio
import logging
import ssl

import websockets


logging.basicConfig(level=logging.DEBUG)

async def hello(websocket, path):
    name = await websocket.recv()
    print("< {}".format(name))

    greeting = "Hello {}!".format(name)
    await websocket.send(greeting)
    print("> {}".format(greeting))

context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(certfile='websockets/testcert.pem')
context.set_ciphers('RSA')

start_server = websockets.serve(hello, '127.0.0.1', 8764, ssl=context)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
