### ISSUE TITLE
Documentation: Deployment to Azure

### ISSUE THREAD

**Issue by harisbal** [aaugustin/websockets#1112]
I understand that this may not be a priority but I would really appreciate an example (similar to the one for [Heroku](https://websockets.readthedocs.io/en/latest/howto/heroku.html)) of deploying websockets on Azure .
Cheers

**Comment by aaugustin** [comment]
A quick Google search suggests that there is no solution for running websockets in Azure. Indeed, Azure only knows how to run WSGI apps and you cannot run websockets over WSGI. See https://docs.microsoft.com/en-us/azure/app-service/configure-language-python#container-characteristics.

**Comment by harisbal** [comment]
Thank you very much for the clarification @aaugustin .
I was misguided based on [this](https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#web-sockets)

**Comment by aaugustin** [comment]
Hrm. Needs double checking.

**Comment by harisbal** [comment]
Thanks very much for investigating.
Not sure if it helps but I'm aware that Flask-SocketIO can run on Azure (e.g. [here](https://github.com/prashanthmadi/azure-appservice-py-websocket))

**Comment by aaugustin** [comment]
It looks like you can run arbitrary containers with Azure: https://docs.microsoft.com/en-us/azure/app-service/quickstart-custom-container?tabs=python&pivots=container-linux. The documentation for deploying on Kubernetes shows how to put websockets in a container. Then you can deploy this container to Azure like any other custom container.

The procedure is more complex that those I documented until now. Some of the information is hard to find. I don't feel like duplicating this much of Microsoft's documentation and maintaining it up to date (especially screenshots of configuration done via a ~point'n'grunt interface~GUI.) For these reasons, I don't plan to add it to websockets' docs, sorry!

**Comment by aaugustin** [comment]
The Flask-SocketIO example you gave relies on gevent, which is a way to run a WebSocket app over WSGI that I didn't want to talk about. It works as long as you're lucky enough not to hit any gevent bug.

Similar hacks are possible with asyncio — like I demonstrated at DjangoCon US 2013 — but I'm not aware of anything production-ready based on this principle.

**Comment by harisbal** [comment]
Thank you very much for spending time on this @aaugustin :)
