### ISSUE TITLE
Concurrernt write causes data corruption

### ISSUE THREAD

**Issue by zzxjl1** [aaugustin/websockets#1115]
The client's websockets lib gives out an exception(seems to received corrupted data) when there are many threads sending data to it at the same time.

**Comment by zzxjl1** [comment]
received 1007 (invalid data); then sent 1007 (invalid data)

**Comment by zzxjl1** [comment]
```
lock = asyncio.Lock()
async with lock:
        await conn.send(msg)

```
I already tried to set up a lock, but it didn't make any difference.

**Comment by aaugustin** [comment]
I don't have enough information to understand the problem. I don't even know if you're using websockets on the server side, the client side, or both. However, I'm pretty sure that websockets doesn't have that kind of bug.

If you provide a minimal example allowing me to reproduce the issue, I'll take a look.
