### ISSUE TITLE
Update copyright to 2022

### ISSUE THREAD

**Issue by fillwithjoy1** [aaugustin/websockets#1116]
Update copyright from 
![image](https://user-images.githubusercontent.com/29514446/148706724-e0367158-b159-453c-8ae1-fa31a8316794.png)
to 
![image](https://user-images.githubusercontent.com/29514446/148706734-7156ccf2-8033-4ba5-986d-fdb8450d35b5.png)

**Comment by aaugustin** [comment]
This will happen automatically at the next docs rebuild.

**Comment by fillwithjoy1** [comment]
Ah ok, sounds good Sent from Mail for Windows From: Aymeric AugustinSent: Monday, 10 January 2022 7:08 PMTo: aaugustin/websocketsCc: Joy; AuthorSubject: Re: [aaugustin/websockets] Update copyright to 2022 (Issue #1116) This will happen automatically at the next docs rebuild.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
