### ISSUE TITLE
In WebSocketApp, python syntax errors are suppressed when the procedure associated with 'on_message' is run.

### ISSUE THREAD

**Issue by cfranz1598** [aaugustin/websockets#1121]
Apparently all or most runtime errors are suppressed when WebSocketApp calls the procedure associated with the 'on_message' parameter.  Example code and run log as follows:

```
import websocket
import json

cc = 'btcusd'
interval = '1m'

socket = f'wss://stream.binance.com:9443/ws/{cc}t@kline_{interval}'

def on_message(ws, message):
    jmessage = json.loads(message)
    candle = jmessage['k']
    print("I got here")
    time = candel['x']  # note the misspelling of the variable
    print('but not here')

def on_close(ws, close_status_code, close_msg):
    print(f"### closed ### - {close_status_code} - {close_msg}")

ws = websocket.WebSocketApp(socket, on_message=on_message, on_close=on_close)
ws.run_forever()
```
Run log:
```
I got here
I got here
I got here
I got here
I got here
```
Best guess is that there is a 'try: except" block around the call to whatever procedure is associated with the 'on_message' parameter suppressing runtime errors.  Syntax errors like that above and key errors are also ignored.  Didn't check for everything.

Good luck and thanks.

**Comment by RemiCardona** [comment]
This is the "websocketS" project (with an S), the `websocket` module is not handled here. Cheers.
