### ISSUE TITLE
send_binary not available

### ISSUE THREAD

**Issue by KohnoseLami** [aaugustin/websockets#1123]
I use Websocket-Client to exchange information in send _ binary, but I need to port the Websocket into Discord.py and make it asynchronous.
So please tell me how to send binaries directly in this module.

**Comment by aaugustin** [comment]
The answer to this question is easily found in the documentation of the `send()` method.

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/reference/common.html#websockets.legacy.protocol.WebSocketCommonProtocol.send

**Comment by KohnoseLami** [comment]
I'm sorry, but this is because I misunderstood the "TypeError: 'Lock' object is not iterable" error caused by not updating the websockets module, and misunderstood that the binary could not be sent.

**Comment by KohnoseLami** [comment]
Thank you for a careful answer.
