### ISSUE TITLE
Improving PyCharm IDE experience

### ISSUE THREAD

**Issue by pyharbor** [aaugustin/websockets#1124]
Hey I want to start off by saying I like your repository here a lot and use it for many of my own projects. That said I've noticed that compared to other libraries the PyCharm IDE experience is pretty lacking. 

I believe the use of  **lazy_import**, which I understand provides some amount of performance gains, also seems to obscure and hide the library from the IDE's `autocomplete, intellisense, command + click, etc...` features.

Below is an example of the code using the lazy_import, which is exactly how a developer would experience the library after pip installing it in PyCharm

<img width="1028" alt="Screen Shot 2022-01-31 at 9 50 34 PM" src="https://user-images.githubusercontent.com/92963988/151907668-8b95ccc5-34d3-4d26-b025-dd24f9683bef.png">

I decided to modify the `__init__.py` directly to add the imports and I commented out the lazy_import function since it was upset about the namespace collisions occurring. I minimally tested the library afterwards and it seemed to work while also supporting much more IDE features. I do believe that most developers would not do something like this however and thus their local development experience would be considerably worse.

<img width="965" alt="Screen Shot 2022-01-31 at 9 51 09 PM" src="https://user-images.githubusercontent.com/92963988/151907853-0caa36f6-5e18-419f-ac6e-18d99bc14d60.png">

This is what the IDE "experience" was like after modifying the `__init__.py` file

<img width="988" alt="Screen Shot 2022-01-31 at 9 51 03 PM" src="https://user-images.githubusercontent.com/92963988/151907894-516ef9ff-4c3d-48ac-a2f6-d41d486c10aa.png">

I'm not sure what the best way to improve the IDE experience would be, while also keeping lazy_imports, but I do believe it is a worthwhile thing to do. A different python repository had a discussion on this very issue which maybe useful to you.

https://github.com/pulumi/pulumi/issues/7367

**Comment by aaugustin** [comment]
Please use the full import paths: `from websockets.clients import connect` if the convenience imports don't work for you.

This should be documented.
