### ISSUE TITLE
Support for Micropython

### ISSUE THREAD

**Issue by AmirHmZz** [aaugustin/websockets#1125]
What's your opinion about **WebSockets** implementation for **MicroPython** to be used in IOT projects?
How much difficult it seems to be ?

**Comment by aaugustin** [comment]
I'm not familiar with MicroPython. If you want to assess this, a good start would be to make a list of:

- Python language features not supported by MicroPython and that websockets uses
- Python standard libraries not available in MicroPython and that websockets uses

This should give you an idea of the effort required and whether it makes sense considering.

**Comment by aaugustin** [comment]
So, for starters, you'd have to swap ``asyncio`` with ``uasyncio``. This isn't going to happen in the main repo.

If you want to do this, probably you should start a new project from scratch and copy-paste the bits you need!
