### ISSUE TITLE
How to set custom ping string message?

### ISSUE THREAD

**Issue by pastet89** [aaugustin/websockets#1127]
Not an issue, but can't believe I spent hours looking for what which should be quite common request. The `data` param in the `ping` method cannot be passed if we want to use the functionality by default. By default I mean, to set up an instance from `websockets.connect` with `ping_interval` and just let it go.

There is no class attribute for the ping frame which can be replaced. Now I am looking for the source of `connect`, in order to rewrite it to create an instance from a new subclass, which I must inherit from `WebSocketClientProtocol`, then to rewrite the `ping` function to use my custom ping message.

This is insane. Can't believe this is so complicated. Please prove me wrong, tell me there is an other obvious easy way to do it.

**Comment by lgrahl** [comment]
You definitely don't have to do that. There are legitimate reasons to roll your own keepalive task and I believe your use case is one of them. A custom keepalive ping task is really simple to make ([just copy and modify this code](https://github.com/aaugustin/websockets/blob/668f320e0547d80afe6529528e1ecc6088955cdc/src/websockets/legacy/protocol.py#L1230:L1269)) and you'll have a lot more control over it. All you have to do is disable the builtin keepalive functionality and then fire up your custom one once the connection has been established.

Alternatively, a viable way to achieve that would be to add a `ping_data_cb` function to the constructor and call that every time a ping is to be created. But, honestly, I believe that's a rabbit hole. If we add this, where do we draw the line? What if the next person would then request to be able to control the ping timeout dynamically?

**Comment by pastet89** [comment]
Ok thanks. I still think it would be useful to add one `ping_frame` param to the object initiator. No more custom coding logic, just the ability to alter the ping frame. Kindly consider it.
