### ISSUE TITLE
TypeError using websockets.connect in python3.6

### ISSUE THREAD

**Issue by lars-petter-hauge** [aaugustin/websockets#1131]
Thanks for a great module. I am encountering an issue when trying to follow the `connect` using it as an infinite asynchronous iterator https://websockets.readthedocs.io/en/stable/reference/client.html#websockets.client.connect. This only occurs on python3.6. From my understanding the module is supposed to be compatible with python 3.6.

I recreated the problem using a small example, mainly based on the content in readthedocs, setting up a server as shown https://websockets.readthedocs.io/en/stable/intro/tutorial1.html#bootstrap-the-server (with a small modifications, as `asyncio.run` is introduced in 3.7. Used  `run_until_complete` instead..

and connecting with:

```
async for websocket in websockets.connect("ws://localhost:8001"):
    try:
        websocket.send("some")
    except websockets.ConnectionClosed:
        continue
```

The error I get is: 
```
Traceback (most recent call last):
  File "test_client.py", line 6, in main
    async for websocket in websockets.connect("ws://localhost:8001"):
TypeError: 'async for' requires an object with __aiter__ method, got Connect
```

Python 3.6
websockets: 9.1

The following issue looks to have relatable content; https://github.com/aaugustin/websockets/issues/340 but strictly mentions that the syntax in the docs is for python 3.6+.

**Comment by mrajancsr** [comment]
yuo need to define that in a function.  
async def fun():
    async for whatever....

**Comment by aaugustin** [comment]
The functionality that you're trying to use is only available in a version of websockets that requires Python 3.7 or later.

**Comment by pedropregueiro** [comment]
I'm also getting this error using python 3.9.13 and websockets 9.1. Help?

**Comment by aaugustin** [comment]
Use a more recent version of websockets where this feature is available. Check the changelog (I didn't memorize it).

**Comment by pedropregueiro** [comment]
my bad @aaugustin, I installed websockets yesterday and assumed pip got the latest version available. apparently not 🤦 

thanks for the quick reply anyway!
