### ISSUE TITLE
websocket-client and multiprocessing.

### ISSUE THREAD

**Issue by teamblubee** [aaugustin/websockets#1132]
I wanted to ask here just to get some clarification.

I ran into some issues when using the python asyncio based websockets.

I have a program with 2 processes. Each one connects to a websocket. Each websocket needs to be pinged every x seconds to keep the connection open.

The problem is asyncio requires me to `await websocket.send("ping")` This is where the bottleneck lies, awaiting causes delays in my message processing.

It would be beneficial if I could send these pings in a way that's non blocking such as in a different process, a different thread or some period when nothing else is going on .

Could I use this websocket-client in such a manner?

**Comment by aaugustin** [comment]
> The problem is asyncio requires me to await websocket.send("ping") This is where the bottleneck lies, awaiting causes delays in my message processing.

Did you benchmark that?

`await websocket.send("ping")` is very fast; it doesn't even yield to the event loop in regular circumstances (i.e. when send buffers aren't full, a fairly unlikely situation).

> a different process, a different thread

"a different task"

**Comment by teamblubee** [comment]
> > The problem is asyncio requires me to await websocket.send("ping") This is where the bottleneck lies, awaiting causes delays in my message processing.
> 
> Did you benchmark that?
> 
> `await websocket.send("ping")` is very fast; it doesn't even yield to the event loop in regular circumstances (i.e. when send buffers aren't full, a fairly unlikely situation).
> 
> > a different process, a different thread
> 
> "a different task"

I actually noticed the problem because I need to send a message at least ever 5 seconds. When doing the await call, i noticed that the whole program slows down because when I await send the heartbeat message to the server, the whole asyncio loop is blocked. 
I can't run the socket heartbeat in 1 asyncio loop or thread and the receive in another.

Is there a function to check if close() was called on a WebSocketApp instance?

**Comment by aaugustin** [comment]
Ah, we're talking about different libraries. You're using websocket-client. Here it's websockets.

**Comment by teamblubee** [comment]
> a function to check if close() was called on a WebSocketApp instance?

websocket-client does not use await...

Receiving messages is fairly quickly but I need to send a message to the server every _x_ seconds. When i call
```python
await send("keepalive")
```
it will actually cause the connection to drop, because await the future takes longer than _x_ seconds. I cannot use different asyncio loops to send and receive. So is there any options to use a low priority thread or some other way to avoid having the main loop blocks while sending these keepalive messages?
