### ISSUE TITLE
remote_address cleared too early in secure server

### ISSUE THREAD

**Issue by noxord** [aaugustin/websockets#1136]
Hi and thanks for this module. I've noticed a small error/inconsistency when using secure server.
In the code below (using code from examples),  websocket.remote_address is empty when client connection is closed and the code reaches finally statement, so a client address will not be printed. I consider this an error, because in case of non-secure connection, in the very same code, websocket.remote_address is still populated at that point. So there is inconsistency between secure and non-secure behavior.

```
async def hello(websocket):
    try:
        async for message in websocket:
            #Do something
            pass 

    finally:
        print(f"Websocket client {websocket.remote_address[0]} disconnected")

ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
localhost_pem = pathlib.Path(__file__).with_name("localhost.pem")
ssl_context.load_cert_chain(localhost_pem)

async def main():
    async with websockets.serve(hello, "localhost", 8765, ssl=ssl_context):
        await asyncio.Future()  # run forever
asyncio.run(main())
```

**Comment by aaugustin** [comment]
These attributes are just a proxy to the underlying socket so, indeed, they may well get cleared when the socket is closed.

TLS and non-TLS sockets have slightly different closure scenarios, leading to observable differences in user code.

Immediately I don't have an opinion about how to resolve this. I could document the behavior; then you'd have to store `remote_address` when the socket is connected if you want to use it later. Or I could cache it in websockets.

**Comment by noxord** [comment]
Caching would be good, just for consistent behavior. It's not very important or something, I just wanted to let you know and track this.

**Comment by aaugustin** [comment]
I am going to consider this as a bug in asyncio because it is reproducible without websockets.

```python
>>> import asyncio
>>> loop = asyncio.get_event_loop()
<stdin>:1: DeprecationWarning: There is no current event loop
```

**Test with TLS**

```python
>>> transport, protocol = loop.run_until_complete(loop.create_connection(asyncio.Protocol, "google.com", 443, ssl=True))
>>> transport.get_extra_info("peername")
('142.250.74.238', 443)
>>> transport.close()
>>> loop.run_until_complete(asyncio.sleep(0.1))
>>> transport.get_extra_info("peername")
>>>
```

Note that the second `transport.get_extra_info("peername")` doesn't return anything.

*** Test without TLS**

```python
>>> transport, protocol = loop.run_until_complete(loop.create_connection(asyncio.Protocol, "google.com", 80))
>>> transport.get_extra_info("peername")
('142.250.74.238', 80)
>>> transport.close()
>>> loop.run_until_complete(asyncio.sleep(0.1))
>>> transport.get_extra_info("peername")
('142.250.74.238', 80)
>>>
```
Note that the second `transport.get_extra_info("peername")` still returns the address.

**Comment by aaugustin** [comment]
Issue filed upstream: https://github.com/python/cpython/issues/91635
