### ISSUE TITLE
Add an option for setting keepalive_ping() message - add ping_message as kwarg to websockets.connect

### ISSUE THREAD

**Issue by pj-ml** [aaugustin/websockets#1137]
Hi, first crack at ever suggesting an enhancement so please feel free to ignore if this is completely off base. I noticed that a lot of the websocket servers that I connect to require some custom keep alive messages, e.g. '{"type": "PING"}'. I thought that it might be useful if you could specify the message that you would like to use as your keep alive message through an argument in the wesockets.connect object.

I used a simple workaround in my case, but I think this would make the keepalive messages way more usable. Happy to have a crack at making the adjustment myself if necessary, but it would also be my first contribution to any project.

**Comment by aaugustin** [comment]
I believe services that have this requirement expect this to be sent as a Text frame, not as a Ping frame, which is what websockets sends.

So the request is actually for an easy, built-in solution to send heartbeats or keepalives at regular intervals. It isn't just about customizing the content of the keepalive pings.

Could you point to documentation of services with this requirement? That would help me map the use case.

**Comment by pj-ml** [comment]
![ping_pong](https://user-images.githubusercontent.com/61276811/156244064-3f7ad693-55f2-47d6-bd8b-e4ae7b4f9a57.PNG)
https://docs.valr.com/

Correct, they expect the message to be sent as a text frame (screenshot attached). This exchange also requires a text frame with an empty string as a keepalive message:
![image](https://user-images.githubusercontent.com/61276811/156244649-f7ec58d3-1c71-49d5-a5a7-81bd57f1e593.png)
https://www.luno.com/en/developers/api#tag/Streaming-API

**Comment by pj-ml** [comment]
No worries, thanks for having a look at it anyway
