### ISSUE TITLE
InvalidStatusCode for 1013 [WS_1013_TRY_AGAIN_LATER]

### ISSUE THREAD

**Issue by madkote** [aaugustin/websockets#1141]
hi,

the ws service closes connection with code 1013 (try again later) or any other code and I would like to catch it.
Currently the websockets raises exception `<class 'websockets.exceptions.InvalidStatusCode'> server rejected WebSocket connection: HTTP 403` .

How I can catch and distinguish that I receive the code 1013 or any other (see below).

Thanks!
---
Example of codes:
```
"""
WebSocket codes
https://www.iana.org/assignments/websocket/websocket.xml#close-code-number
https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
"""
WS_1000_NORMAL_CLOSURE = 1000
WS_1001_GOING_AWAY = 1001
WS_1002_PROTOCOL_ERROR = 1002
WS_1003_UNSUPPORTED_DATA = 1003
WS_1004_NO_STATUS_RCVD = 1004
WS_1005_ABNORMAL_CLOSURE = 1005
WS_1007_INVALID_FRAME_PAYLOAD_DATA = 1007
WS_1008_POLICY_VIOLATION = 1008
WS_1009_MESSAGE_TOO_BIG = 1009
WS_1010_MANDATORY_EXT = 1010
WS_1011_INTERNAL_ERROR = 1011
WS_1012_SERVICE_RESTART = 1012
WS_1013_TRY_AGAIN_LATER = 1013
WS_1014_BAD_GATEWAY = 1014
WS_1015_TLS_HANDSHAKE = 1015
```

**Comment by aaugustin** [comment]
You are mixing two kinds of error codes that happen at different stages:
- `InvalidStatusCode` happens during the handshake; the WebSocket connection isn't established yet.
- WebSocket close code happen when closing an established connection, after the WebSocket handshake.

You can get the close code from https://websockets.readthedocs.io/en/stable/reference/client.html#websockets.client.ClientConnection.close_code or https://websockets.readthedocs.io/en/stable/reference/exceptions.html#websockets.exceptions.ConnectionClosed.rcvd — but only in cases where the connection is successfully established, then closed, which isn't the case here.
