### ISSUE TITLE
Endless loop when I try to send big message

### ISSUE THREAD

**Issue by MrHalfman** [aaugustin/websockets#1142]
Hi, on OSX with Python 3.8 and websockets 10.2 I get an infinite loop with this message when I try to send a big message over ws (> 250KB which is not that big) : 

`Task <Task pending name='Task-13' coro=<Api._send_job_async() running at api.py:877> cb=[_run_until_complete_cb() at asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop`

Here are my functions :

```python
    async def _send_job_async(self, job_name, kwargs):
        await self._ws_send('job', {
            'job_name': job_name,
            'kwargs': kwargs,
        })

    async def _ws_send(self, action, data):
        while True:
            try:
                await self.websocket.send(orjson.dumps({
                    'action': action,
                    'recipients': ['interface'],
                    'data': data,
                }))
                return
            except Exception as e:
                self.logger.debug(e)
                time.sleep(1)
                await self._ws_connect()
```

And my connection is initialized like that : `self.websocket = await websockets.client.connect(self.websocket_ip)`

Thank you for your help

**Comment by aaugustin** [comment]
Start here - https://websockets.readthedocs.io/en/stable/howto/faq.html#why-does-my-simple-program-misbehave-mysteriously

**Comment by MrHalfman** [comment]
Thanks for the fast answer, I was still facing this issue after changing to asyncio.sleep so I decided to switch to another client using Threads

**Comment by aaugustin** [comment]
OK. I just noticed you have more than one event loop running (based on the error message you pasted) which suggests incorrect use of asyncio. Switching to threads fixes this obviously. websockets will get this feature with #885.
