### ISSUE TITLE
async for websocket timeouts

### ISSUE THREAD

**Issue by icon-wm** [aaugustin/websockets#1143]
I'm not sure if it is by design, but
`async for websocket in websockets.connect(websocket_resource_url):`
does not seem to throw timeouts.

This however throws timeouts correctly
`async with websockets.connect(websocket_resource_url) as websocket:`

**Comment by aaugustin** [comment]
This seems like the intended behavior. The point of `async for ... in connect(...): ...` is to retry connecting forever if a timeout occurs. Perhaps you could enable debug logs (see the docs about logs) and see if that clarifies what websockets is doing?
