### ISSUE TITLE
constant disconnects with 1006 errors streaming from various crypto currency exchanges

### ISSUE THREAD

**Issue by mrajancsr** [aaugustin/websockets#1144]
Hello, i am having trouble with the websockets library.  I am working as a crypto currency software engineer and i need to build data feeds from various crypto exchanges.  When i use your library, i am able to stream with no issues.  The issues start occuring when i leave my computer for a while and come back and notice the screen is just frozen and i constantly get 1006 errors.  I am running this process in a tmux terminal.  what could be the reason to constantly get 1006 errors when streaming from exchanges? Initially i thought perhaps it was my async push to redis which was causing t his.  but i have a stand alone stream option without pushing anything anywhere and the error still occurs.  

Heres a how i defined my functions: 

```
url = "wss://fstream.binance.com/ws/"
BINANCE_SUBSCRIPTION_PAYLOAD: Dict[str, str] = {
    "method": "SUBSCRIBE",
    "params": [""],
    "id": 1,
}
BINANCE_TRADE_BLOTTER: str = "@aggTrade"
BINANCE_BLOTTER_MAPPING: Dict[str, str] = {
    "trxn_time": "T",
    "symbol": "s",
    "trxn_price": "p",
    "trxn_size": "q",
}
symbol = 'btcusdt'
async def receive(self) -> Optional[List[Dict]]:
        message = loads(await self.websocket.recv())
        if "result" in message:
            return None
        return [
            {
                new_key: message[old_key]
                for (new_key, old_key) in BINANCE_BLOTTER_MAPPING.items()
            }
        ]
async def send(self) -> None:
        BINANCE_SUBSCRIPTION_PAYLOAD["params"] = [
            f"{symbol}{BINANCE_TRADE_BLOTTER}"
        ]
        await self.websocket.send(dumps(BINANCE_SUBSCRIPTION_PAYLOAD))
        print("Socket open!")

Then i continuously stream using this logic below: 
while True:
        try:
            records = await obj.receive()
        except Exception as e:
            obj.logger.info(f"exception occured at {stream_name}")
            msg = f"""Socket Closed: at {datetime.now()};
            close reason: {obj.websocket.close_reason},
                close code: {obj.websocket.close_code}"""
            print(msg)
            obj.logger.info(msg)
            obj.logger.info("\n")
            obj.logger.info(e)
            print("reconnecting...")
            obj.websocket = await websockets.connect(obj.url, ping_interval=None)
            await obj.send()
            continue
        if not records:
            continue

        record_count += len(records)
        for record in records:
            await handle_record(record, stream_name, pipe, handle_lob, save, symbol)
        if not save:
            continue
        if record_count >= MAX_RECORD_COUNT:
            await pipe.execute()
            # -some exchanges require a pong when they send a ping frame
            if obj.exchange == "Ftx":
                await obj.websocket.ping()
            else:
                await obj.websocket.pong()

            print("pushed to redis")
            record_count = 0
```
 
I am really not able to understand why the program freezes after few hours of me stepping away from my computer.  While i am watching it there is no issue with it freezing. 
Upon reading the documents for exchanges, binance sends ping frame every few minutes and they allow unsolicited pong frames.  FTX sends pong and expects a ping() in return https://docs.ftx.com/#websocket-api
Can. you please suggest what i am doing wrong as im unable to debug this error

**Comment by cloutsocks** [comment]
this issue can and should be closed https://websockets.readthedocs.io/en/stable/project/contributing.html?highlight=crypto

> Cryptocurrency users
> websockets appears to be quite popular for interfacing with Bitcoin or other cryptocurrency trackers. I’m strongly opposed to Bitcoin’s carbon footprint.
> 
> I’m aware of efforts to build proof-of-stake models. I’ll care once the total energy consumption of all cryptocurrencies drops to a non-bullshit level.
> 
> You already negated all of humanity’s efforts to develop renewable energy. Please stop heating the planet where my children will have to live.
> 
> Since websockets is released under an open-source license, you can use it for any purpose you like. However, I won’t spend any of my time to help you.
> 
> I will summarily close issues related to Bitcoin or cryptocurrency in any way.

**Comment by blueForestIcarus** [comment]
retards
