### ISSUE TITLE
Closing Serve in Thread 

### ISSUE THREAD

**Issue by sschuhmann** [aaugustin/websockets#1148]
In a project I have started a Websocket server with 

websockets.serve() 

in an own Thread. This works reasonably well, except for closing the server.

I have tried the documented way using close(). However, this method is not available in the Serve object. 

How should I close the server in order to close the Thread?

**Comment by aliqandil** [comment]
Doesn't the "server" object gets returned when you "await" the "serve()" function? That object should have the "close" method.

**Comment by sschuhmann** [comment]
I call the serve function from a synch method, so awaiting does not work. However, I have tried to use async.run to execute the function, this causes an exeption. 

Is there a other way to call it from a synch function?

**Comment by aaugustin** [comment]
Hard to say what the problem is when you haven't provided a minimal reproduction of the problem and/or a stack trace of the error you are getting.

https://websockets.readthedocs.io/en/stable/howto/faq.html#why-am-i-having-problems-with-threads may help (specifically the pointer to `call_soon_threadsafe`, if you're triggering `close` from another thread than the thread that is running the asyncio event loop).

**Comment by sschuhmann** [comment]
I´m really sorry to dig this up again, but I havent been able to solve the problem so far. My code looks like

´´´ 
server = websockets.serve(handler, host, port, loop=event_loop)
Thread(target=run, args(loop, server))
...

def run(loop, server):
    loop.run_until_complete(server)
    loop.run_forever()
....

def stop():
    server.close()
    loop.stop()
´´´

The Serve object, which I get from instanciating the server does not have any methods to gracefully stop the server. If I try to call any stop function from within the event loop I get the same problem. 

Is there any other way, a WebsocketServer should be initialized in it´s own Thread? 

The use case is to have an open connection to all clients (with message handlers) without blocking my main application
