### ISSUE TITLE
When a server request triggers a client request instead of a response

### ISSUE THREAD

**Issue by alexmac98** [aaugustin/websockets#1149]
Hello. Please interpret this Issue as a doubt about the websockets library. 
I'm currently facing a problem and I don't know how to fix it and I need to know if this is a websockets problem or not.

Putting it simply, I've two entities that communicate with each other through websockets, Entity A and Entity B.
The problem I'm facing is:
1. **Entity A** sends a request to **Entity B** and awaits for its response;
2. **Entity B**, when it receives the request, instead of responding to it, sends a request of its own to **Entity A**, and awaits for its response.
3. **Entity A** receives that request, generates the response and sends the response - I'm sure of this (used Wireshark to check if the response is in fact sent).
4. PROBLEM: **Entity B** doesn't receive the response, and blocks, because it keeps awaiting for it.

Do you have any idea why this might happen? Does the first await of Entity A "blocks" the "websocket channel" Entity A -> Entity B?

The following image depicts the context. In this case, Entity A is the Central System and Entity B is the Charge Point. The Charge Point keeps waiting for the AuthorizeResponse, which is previously sent by the Central System. The RemoteStartTransactionRequest sent by the Central System triggers the AuthorizeRequest sent by the Charge Point.

![Screenshot from 2022-03-18 11-05-59](https://user-images.githubusercontent.com/72937839/158993683-dd20dafd-84bf-4ea2-a285-479f686442fb.png)

**Comment by lgrahl** [comment]
Hi. Websockets is just a bidirectional data channel and nothing more. What you're describing sounds like a bug on application level. But, yes, you can write arbitrary request/response protocols on top of websockets. I hope that answers the question regarding websockets. :slightly_smiling_face:

**Comment by lgrahl** [comment]
A hint on request/response protocol design: If you want to bidirectionally have multiple requests running independent of each other, the receiving end should never await one specific response because that would cause before mentioned deadlock.

**Comment by alexmac98** [comment]
Thank you for the fast response. I need to await the Authorize Response, since the response of the RemoteStartTransaction is directly dependent of it...
I've no idea how to fix this issue. I think the asyncio is swapping in-between awaits with no response, which is the case, indefinitely.

**Comment by lgrahl** [comment]
The flow of each direction is independent, yes.
