### ISSUE TITLE
client/server example - AttributeError

### ISSUE THREAD

**Issue by yotam-medini** [aaugustin/websockets#115]
Hello, 
The Web-based example works fine for me, but with the 'simpler'
server.py&client.py I experience the failure below.
What am I missing ?

$ ls -l; cksum *.py
total 8
-rw-r--r-- 1 yotam yotam 397 2016-05-19 23:15:15 client.py
-rw-r--r-- 1 yotam yotam 424 2016-05-19 23:14:42 server.py
709809666 397 client.py
2251947991 424 server.py
$ python3.5 --version
Python 3.5.1
$ python3.5 server.py &
[1] 17044
$ python3.5 client.py
Traceback (most recent call last):
  File "client.py", line 16, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "client.py", line 7, in hello
    async with websockets.connect('ws://localhost:8765') as websocket:
AttributeError: __aexit__
$ echo $?
1
$

**Comment by aaugustin** [comment]
I cannot reproduce this issue.

```
% cd example
% PYTHONPATH=.. python server.py &
[1] 96046
% PYTHONPATH=.. python client.py
What's your name? me
> me
< me
> Hello me!
< Hello me!
```

**Comment by yotam-medini** [comment]
After clean re-installing of websockets for python3.5 -
the  server.py + client.py  example  - works well for me.

Previously using 'pip3' to install websockets
and brutally sym-linking
  /usr/local/lib/python3.5/dist-packages/websockets ->
  /usr/local/lib/python3.4/dist-packages/websockets ->
was a bad idea.

I ended up deleting this wrong symbolic-link and issuing:
   # python3.5 -m pip install -U --force-reinstall -I websockets
and as already stated above, the example works well.


Since currently - python3.5 is not installed by default
on recent GNU/Linux distributions, and usage of pip module
depends on the python version, let me suggest that in

  https://pypi.python.org/pypi/websockets

in addition to
  "Installation is as simple as pip install websockets. ..."
the page will also say something like:

   Installing websockets for python3.5 can be done by:
   # python3.5 -m pip install websockets

**Comment by yotam-medini** [comment]
Hello Aymeric,

Thank you for testing this.
I re-installed your websockets via
   python3.5 -m pip install  ...
and now the example works fine.

I added a comment in the case.

thanks you again for all your work -- yotam

**Comment by aaugustin** [comment]
No problem. I'm not very eager to get into an explanation of

**Comment by Ivoz** [comment]
@yotam-medini it's usually much more useful to use a virtualenv to isolate exactly which python you want to use for a project.

    $ virtualenv --python=/usr/local/bin/python3.5 wsproject
    $ source wsproject/bin/activate
    (wsproject) $ pip install websockets -y
    (wsproject) $ python client.py

The last two calls are made inside the virtual environment, which you know has to be referring to a python3.5. It also means you can install whichever packages you like inside it without messing your 'system' / 'global' state of python packages.
