### ISSUE TITLE
Documentation to use Websockets in own thread

### ISSUE THREAD

**Issue by sschuhmann** [aaugustin/websockets#1156]
Hi,

I had opened Issue #1148 which is closed now.  Even after testing different setups< I haven´t been able to find a proper solution. This might also be interesting mfor others with the same usse case.

**Use Case**: I need to run a websocket server in an own thread, which is closed together with the main thread. 

**Implementation** 
``ˋ
server = websockets.serve(handler, host, port, loop=event_loop)
Thread(target=run, args(loop, server))

def run(loop, server):
    loop.run_until_complete(server)
    loop.run_forever()

def stop():
    server.close()
    loop.stop()
ˋˋˋ

**Problem**
With this implementation I´m unable to close the websocket server. Await the serve seems to block the thread.

**Comment by lgrahl** [comment]
Apologies if this sounds a bit rude but it seems you've ignored the two pointers you got in https://github.com/aaugustin/websockets/issues/1148#issuecomment-1072445935.

1. Please, provide a full minimal example that we can actually execute.
3. You should use `call_soon_threadsafe` to dispatch from another thread. [Maybe take a look at the Python docs talking about multithreading and asyncio.](https://docs.python.org/3/library/asyncio-dev.html#asyncio-multithreading)

**Comment by sschuhmann** [comment]
Thank you for pointing that out! Please find a minimal example attached. This also includes a run_threadsafe to close the server, which hasn't worked

`
import websockets
from threading import Thread
import asyncio
import signal


class SocketServer:

    _server = None
    _loop = None

    def __init__(self) -> None:
        self._loop = asyncio.new_event_loop()

    async def _handle_request(self, websocket, path):

        async for msg in websocket:
            print(msg)

    def _run(self, loop, server):
        loop.run_until_complete(server)
        loop.run_forever()

    def run_server(self):
        self._server = websockets.serve(
            self._handle_request, "localhost", 4711, loop=self._loop
        )

        self.t = Thread(target=self._run, args=(self._loop, self._server))
        self.t.start()

    def stop(self):
        self._loop.call_soon_threadsafe(self._server.stop())
        self._loop.stop()


server = None


def _signal_handler(signum, frame):
    server.stop()


def main():
    global server
    signal.signal(signal.SIGINT, _signal_handler)
    server = SocketServer()
    server.run_server()

    while True:
        pass


if __name__ == "__main__":
    main()

`

**Comment by sschuhmann** [comment]
[minimal.zip](https://github.com/aaugustin/websockets/files/8408809/minimal.zip)

**Comment by lgrahl** [comment]
There are several bugs in that code:

1. `self._server` is the coroutine creating the server but it's not the actual server instance. I'd advise reading into [developing with asyncio, especially the _debug mode_ section](https://docs.python.org/3/library/asyncio-dev.html#debug-mode) in order to notice such bugs.
2. It's calling `stop` on the server but there's only a `close` method.
3. In this case, `run_coroutine_function` would be the correct way to close. See the [Concurrency and Multithreading](https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading) chapter.
4. The thread cannot run `loop.run_forever()` since it would prevent the program from stopping.

```python
import websockets
from threading import Thread
import asyncio
import signal
import sys


class SocketServer:
    _server = None
    _loop = None

    def __init__(self) -> None:
        self._loop = asyncio.new_event_loop()

    async def _handle_request(self, websocket, path):
        async for msg in websocket:
            print(msg)

    def _run(self, loop, server):
        loop.run_until_complete(self._server.wait_closed())

    def run_server(self):
        self._server = self._loop.run_until_complete(websockets.serve(
            self._handle_request, "localhost", 4711, loop=self._loop
        ))
        Thread(target=self._run, args=(self._loop, self._server)).start()

    def stop(self):
        async def close():
            self._server.close()
            await self._server.wait_closed()

        closed = asyncio.run_coroutine_threadsafe(close(), self._loop)
        closed.result(timeout=1.0)
        self._loop.stop()


server = None


def _signal_handler(signum, frame):
    server.stop()
    sys.exit(0)


def main():
    global server
    signal.signal(signal.SIGINT, _signal_handler)
    server = SocketServer()
    server.run_server()

    while True:
        pass


if __name__ == "__main__":
    main()
```

I'll leave this issue open in order to let @aaugustin decide whether something like this should be documented.

**Comment by aaugustin** [comment]
I am very reluctant to put this inside websockets' documentation; I'd rather leave it to blog posts / online forums / this issue.

Indeed: as this discussion demonstrates:

1. You'd have exactly the same patterns in any other context where you want to start a long running asyncio coroutine (typically a server) in a thread and then stop it later by calling a coroutine. To me this belongs more to "asyncio" than "websockets".

2. As this discussion demonstrates, mixing threads and event loops is confusing. (Mixing signals and threads in Python is already confusing as only the main thread will receive signals.) That documentation would trigger issue reports from confused users.

3. This could lead users to believe that this is a good design, while in most cases it isn't. Often, it's best:

- either to keep the event loop in the main thread and to move the rest of the processing to other threads via `run_in_executor` — if you're going to mix threads and event loops, that's the least messy solution.
- or to move it to a separate process with some kind of inter-process communication — there are many options depending on the use case.

So, documenting this pattern will not help users of websockets write better code, will generate issues adding no value to websockets, and is more asyncio's responsibility than websockets'.

**Comment by aaugustin** [comment]
Thanks for bringing it up though :-) While my previous message may come across as a thorough rebuttal, it's mostly a rendering of my thought process to help you understand where we disagree.

**Comment by lgrahl** [comment]
Ack. In general but especially when it comes to Python, and even more so in combination with asyncio, the number one question should be: "Do I really need **classic** threads here?" Speaking from personal experience (which of course is biased by the use cases I've encountered), the answer is almost always "no".

**Comment by aaugustin** [comment]
I think the FAQ already addresses that but I'll double check.

**Comment by aaugustin** [comment]
As it stands, the [FAQ](https://websockets.readthedocs.io/en/stable/howto/faq.html?highlight=faq#why-am-i-having-problems-with-threads) may not suffice to convince someone who thinks they need threads. Reopening as a doc issue to clarify why not use threads and what the alternatives are.
