### ISSUE TITLE
websockets.send func is not thread safe?

### ISSUE THREAD

**Issue by yingchengpa** [aaugustin/websockets#1162]
Hi and thanks for this module. I found a error in my project:
      my  python3.6.exe create a thread to send ws message to web client ,  the simple code likes this :
~~~
async def notify(msg):
    await _wstocken.send(msg)

--------------------------------
def threadFunc():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    while(True):
        loop.run_until_complete(notify('hello world'))
    
    loop.close()
~~~
I create one thread ,the js client work good, however when I create more  threads to send ws message to js client, the client Chrome throw a 'Could not decode a text frame as UTF-8' error. So, I modify my code like this, it works good . 
~~~
_lock = threading.RLock()
async def notify(msg):
    _lock.acquire()
    await _wstocken.send(msg)
    _lock.release()
~~~

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/howto/faq.html#why-am-i-having-problems-with-threads

**Comment by aaugustin** [comment]
(If you're going to use asyncio for concurrency, then use asyncio, not threads.)
