### ISSUE TITLE
Replicating on_message functionality using websockets

### ISSUE THREAD

**Issue by dmr07** [aaugustin/websockets#1163]
I'm looking to implement something similar to the on_message functionality WebSocketApp but using the websockets library, i.e. always read the latest message. However it looks like they only offer `recv()` in order to read the next message in the queue.

My temporary work around is to run `ws.recv()` in a while loop, but I'm not sure whether this is the right approach:
```py
async with websockets.connect(self.socket) as ws:
    while True:
        msg = await asyncio.wait_for(ws.recv(), timeout=3)
        self.on_msg(msg)
```
With this approach I have two concerns:

1) I'm subscribed to a channel that gets a lot of messages, so I'm concerned recv will fall behind in reading the messages in the queue if I keep the socket running. (I previously had a 0.1s delay in the while loop and noticed that the message I was getting was not the latest. Even after terminating my internet connection, it kept reading from the message queue before raising a connection closed error)

2) I'm currently using a timeout to detect if a message hangs for unforeseen reasons, but there are cases where there are simply no messages and it raises a timeout error. I'm not able to differentiate the two using the current method.

What's the best way to always get the latest message, even if there's a queue of unread messages? Also, how would you do error handling to avoid the issue in 2)?

**Comment by aaugustin** [comment]
I don't think WebSocketApp behaves the way you believe it behaves. Low-level, callback-based libraries usually call `on_msg` for every message, even if more messages were already received. They don't call it just for the last one. It seems harder to achieve what you're trying to achieve with such a library than with wesbockets.

With the higher-level, coroutine-based design of websockets, you can create that kind of structure.

Run this in a task:

```python
queue = asyncio.Queue()

async with websockets.connect(self.socket) as ws:
    async for msg in ws:
        queue.put_nowait(msg)  # always succeeds because queue is unlimited
```

And this in another task:

```python
while True:
    msg = await queue.get()
    # if more messages were received, get the last one
    while True:
        try:
            msg = await queue.get_nowait()
        except asyncio.QueueFull:
            pass
    # now msg is the last message in the queue, do what you want with it
    await process(msg)
```

(untested, but should put you on a viable track)

**Comment by aaugustin** [comment]
This proposal solves your second problem because you can detect the disconnection immediately in the first task, even if the second task is still busy processing the last message.

**Comment by lgrahl** [comment]
I'd distinguish between two scenarios though:

1. Buffering due to high load blocking the event loop. Using a (priority) queue won't help you there.
2. Buffering due to async tasks not being done yet but not blocking the event loop. In that case a (priority) queue will help you.

Personally, I would put the work items into a queue and handle the keepalive directly in the receive handler.
