### ISSUE TITLE
recv() if available

### ISSUE THREAD

**Issue by devinrsmith** [aaugustin/websockets#1168]
I'd like to `recv()` if "immediately" available, otherwise return `None`.

My first attempt was:

```python
async def recv_if_available(ws):
    try:
        return await asyncio.wait_for(ws.recv(), 0)
    except asyncio.TimeoutError:
        return None
```

I'm always getting `None`. If I change the timeout to a very small positive number (`0.0000001`), it "works" - but I'd like to see if I can avoid that.

My next attempt was:

```python
async def recv_if_available(ws):
    await asyncio.sleep(0)
    try:
        return await asyncio.wait_for(ws.recv(), 0)
    except asyncio.TimeoutError:
        return None
```

Am I using the asyncio primitives or websockets incorrectly? I *could* introduce a queue and separate out my consumer/producer, but I was hoping to be able to lean on the websockets queue instead of introducing another one. Any help would be much appreciated!

**Comment by aaugustin** [comment]
You expect that `asyncio.wait_for(foo() 0)` will return the value if and only if `foo()` doesn't yield control to the event loop. This is not true:

```pycon
>>> async def do_not_yield():
...     return "bar"
...
>>> import asyncio
>>> asyncio.run(asyncio.wait_for(do_not_yield(), 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in do_not_yield
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/tasks.py", line 418, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/myk/.pyenv/versions/3.10.0/lib/python3.10/asyncio/tasks.py", line 420, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
>>> asyncio.run(asyncio.wait_for(do_not_yield(), 0.000000001))
'bar'
```

----

There is no public API for what you are trying to do.

```python
async def recv_if_available(ws):
    try:
        return await asyncio.wait_for(ws.recv(), 0.000000001)
    except asyncio.TimeoutError:
        return None
```

sounds like a reasonable solution.

If a message isn't already available, yielding control to the event loop will take more than 1ns, so it does what you want.

----

The alternative is to rely on implementation details / private APIs, with the risks that it entails.

I don't think that's a good tradeoff here given that there's a fully functional solution based on a public API.

----

Finally, I would like to challenge the concept of "immediately" available — and the fact that you added quotes suggests that you know that it's questionable. What if the data is on your NIC but hasn't reached websockets yet? Is that "immediately" available or not "immediately" available? What if it is in the OS buffers? In these cases, websockets will have it in less than 1ms. So maybe `await asyncio.wait_for(ws.recv(), 0.001)` is really what you want?

**Comment by devinrsmith** [comment]
Thanks for a simple example demonstrating the generic flaw in my approach. I'm going to do some more research into asyncio to better understand the semantics of what I want to try and do.
