### ISSUE TITLE
PyPy-websockets-10.3-pp38-pypy38_pp73-win_amd64.whl wheel

### ISSUE THREAD

**Issue by stonebig** [aaugustin/websockets#1169]
having a PyPy-websockets-10.3-pp38-pypy38_pp73-win_amd64.whl  in test matrix would be nice

(apparently I could compile it, and it works, it's for safety tests)

**Comment by aaugustin** [comment]
If not sure if you're asking (1) for a wheel on PyPI for the next release or (2) for running the unit tests on other version of PyPy.

(1) is just a matter of bumping the version of cibuildwheel. I can do that.
(2) is one more step down the road of "it's my job to ensure that websockets runs on PyPy", but I don't want to take this job; I want to leave it to PyPy maintainers. Furthermore, running the tests on PyPy is significantly slower than on CPython, which is annoying. I would like to see if I can run them only on the main branch, not on pull requests.

**Comment by stonebig** [comment]
(1) would be nice enough
