### ISSUE TITLE
Stopping producer and cleaning on closed server connection

### ISSUE THREAD

**Issue by giladwa** [aaugustin/websockets#1173]
When a connection is getting disconnected with 1006, there's no immediate way to clean and stop the producer work.

For example:
What is the best way to avoid waiting for 1200 seconds in the below code? (and clean resources as fast as possible)

```
async def producer_test(client_ws):
    while True:
        yield {"test":"test"}
        await asyncio.sleep(1200) # or waiting for any other resource
    # clean resources


async def handler(client_ws):
    async for dict_msg in producer_test(client_ws):
        if dict_msg:
            await client_ws.send(dict_msg)
```

**Comment by giladwa** [comment]
Needless to say that instead of sleep, it could have been an event base "await", which can wait for hours/days, and the resources will still be in use.

**Comment by aaugustin** [comment]
This question is unrelated to websockets. It's about asyncio.

You need to wait on two things in parallel and return when one of them completes:

1. producer_test(client_ws)
2. client_ws.wait_closed()

This is typically achieved with:

```python
task1 = asyncio.create_task(producer_test(client_ws))
task2 = asyncio.create_task(client_ws.wait_closed())
await asyncio.wait([task1, task2], return_when=asyncio.FIRST_COMPLETED)
# check if task1.done(), if task2.done(), and take appropriate action

**Comment by giladwa** [comment]
Thank you, client_ws.wait_closed() is what I was looking for.
