### ISSUE TITLE
async for message in self._websocket_client is blocking the event loop 

### ISSUE THREAD

**Issue by phantomdrake077** [aaugustin/websockets#1178]
Have a question of the simple snippet code. New to the asyncio so maybe missing something basic here. The read message is for getting the real time prices flowing and is an infinite loop as the server will not disconnect it. Also need to continuously receive the messages that the server is sending. 

```
uvloop.install()

loop = asyncio.get_event_loop()
loop.run_until_complete(alice_blue_obj.init_websocket_connection())
loop.run_until_complete(alice_blue_obj.read_messages())
loop.run_forever()

asyncio.run(alice_blue_obj.subscribe(instrument1, "full_snapquote"))
asyncio.run(alice_blue_obj.subscribe(instrument2, "full_snapquote"))

**async def read_messages(self):**
        print('in read_messages')
        async for message in self._websocket_client:
            print(message)
```

**Comment by aaugustin** [comment]
`asyncio.run` creates another event loop. You cannot use the same connection from different event loops. Probably that's the issue. Restructure your program to have exactly one `asyncio.run` call and no `loop.run_*` calls.

**Comment by phantomdrake077** [comment]
Hi thanks for the quick reply @aaugustin. One followup question here would be if a thread outside wants to send subscription message on the same socket for a different instrument, that code won't be part of asyncio.run. So how is that normally done?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/howto/faq.html#why-am-i-having-problems-with-threads

**Comment by phantomdrake077** [comment]
oh awesome. That really helps.
