### ISSUE TITLE
Proper way to handle disconnects mid-execution and/or use context manager?

### ISSUE THREAD

**Issue by cloutsocks** [aaugustin/websockets#1181]
hi! wonderful library

im unfortunately wrapping my head around the non-callback structure and other things

the context manager is really nice, and particularly for handling reconnects, but i'm not sure how to reconcile it with how i intend to use it

consider the extremely simple snippet where a client receives a number to count to from a server, and starts counting back

```
async with websockets.connect(uri) as websocket:
    count_to = int(await websocket.recv())
    await websocket.send(f'i will count to {count_to}!")

    for i in range(count_to):
        await asyncio.sleep(1)
        await websocket.send(str(i))

```

if a connection drops during this, as expected in a context manager, we would break out

we can follow the faq to make it reconnect

```
async for websocket in websockets.connect(uri):
    try:
        ...
    except websockets.ConnectionClosed:
        continue
```

 but my issue is now - what if i wanted to continue counting without breaking out (and deferring the send or so)? or what if i wanted to resume counting when the connection re-establishes?

for the latter, i could store state somewhere, but this becomes trickier where you end up in a malformed state because you broke out mid execution

i can think of ways to work _around_ this but i felt it better to ask directly since i felt i was approaching things the wrong way

my other thought is maybe i want to wrap all send and recv's with a try rather than the context manager itself but that also felt questionable

**Comment by aaugustin** [comment]
You are going to need two asyncio tasks, coordinated with a queue:

- First task keeps the connection open with `async for websocket in websockets.connect(uri): ...` and runs a loop that reads messages from the queue and sends them
- Second task counts down and puts messages in the queue

Pseudo code:

```
# task 1

async for websockets.connect(uri) as websocket:
    if this is the first time we enter the loop:
        receive count_to
        initialize queue
        start task that counts down
    
    while True:
        i = await queue.get()
        await websocket.send(str(i))

# task 2

    for i in range(count_to):
        await asyncio.sleep(1)
        await queue.put(i)

```

**Comment by cloutsocks** [comment]
thank you!! i had a feeling a message queue might be the answer
