### ISSUE TITLE
Lazy import

### ISSUE THREAD

**Issue by CaedenPH** [aaugustin/websockets#1183]
In the `__init__.py` the function `lazy_import` is used to import local modules. The problem with this is that typehints are not showing up which makes coding the project a lot more difficult and less professional. I'm not entirely sure how `lazy_import` is importing these modules but whatever it is doing is not registering through my typechecker. I am using Pylance and Python visual studio code as my typechecker. 
![image](https://user-images.githubusercontent.com/23421705/173414001-3a1a7eca-5660-44cd-8e15-6a0b490c64d2.png)

**Comment by aaugustin** [comment]
From https://websockets.readthedocs.io/en/stable/reference/index.html:

**Comment by CaedenPH** [comment]
> `websockets.client.WebSocketClientProtocol`
This still shows up as `Any`

**Comment by aaugustin** [comment]
It works for me. I suspect it's an issue with your mypy setup.

```
myk@mYk:websockets/src ‹main›$ cat issue1183.py
import websockets.client

reveal_type(websockets.client.WebSocketClientProtocol)
myk@mYk:websockets/src ‹main›$ mypy issue1183.py
issue1183.py:3: note: Revealed type is "def (*, logger: Union[logging.Logger, logging.LoggerAdapter[Any], None] =, origin: Union[websockets.typing.Origin, None] =, extensions: Union[typing.Sequence[websockets.extensions.base.ClientExtensionFactory], None] =, subprotocols: Union[typing.Sequence[websockets.typing.Subprotocol], None] =, extra_headers: Union[websockets.datastructures.Headers, typing.Mapping[builtins.str, builtins.str], typing.Iterable[Tuple[builtins.str, builtins.str]], websockets.datastructures.SupportsKeysAndGetItem, None] =, **kwargs: Any) -> websockets.legacy.client.WebSocketClientProtocol"
Success: no issues found in 1 source file
```

**Comment by aaugustin** [comment]
Maybe https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports?

**Comment by aaugustin** [comment]
Wait, you're using pylance, not mypy. I don't know much about pylance. I still suspect that it's failing to import websocktes.

**Comment by CaedenPH** [comment]
> Wait, you're using pylance, not mypy. I don't know much about pylance. I still suspect that it's failing to import websocktes.

Pylance is very popular when it comes to python development, so I doubt that I am the only person with this problem. Perhaps you could do some testing or just import the modules normally in the `__init__`?

**Comment by aaugustin** [comment]
I will do some testing before reverting the conditional import mechanism. (FYI it's designed to provide an implementation on top of trio without making trio a hard dependency of websockets. But that's a few years in the future, probably...)

Could you provide reproduction instructions please?

I expect something along these lines:

* Create a virtualenv and install websockets
    * What are you using? poetry? python -m venv?
* Open a project in Visual Studio Code
    * Any specific setup? Extensions to install/enable?
* Tell Visual Studio Code to load the virtualenv
    * Not sure if anything specific is needed here?

**Comment by CaedenPH** [comment]
> I will do some testing before reverting the conditional import mechanism. (FYI it's designed to provide an implementation on top of trio without making trio a hard dependency of websockets. But that's a few years in the future, probably...)
> 
> 
> 
> Could you provide reproduction instructions please?
> 
> 
> 
> I expect something along these lines:
> 
> 
> 
> * Create a virtualenv and install websockets
> 
>     * What are you using? poetry? python -m venv?
> 
> * Open a project in Visual Studio Code
> 
>     * Any specific setup? Extensions to install/enable?
> 
> * Tell Visual Studio Code to load the virtualenv
> 
>     * Not sure if anything specific is needed here?

Sorry for the late response. Visual studio code is more of a text based editor than an ide so no complicated steps are required. 
Just install visual studio code and the python extension which will also install pylance. Then just install websockets with pip (no venv required) and view the type hints.
Pylance is a great type checker and I have had no problems with any modules  except for this one.

**Comment by ooliver1** [comment]
Pylance is a slight edit of pyright, the note in docs about:

> For convenience, many public APIs can be imported from the websockets package. However, this feature is incompatible with static code analysis. It breaks autocompletion in an IDE or type checking with [mypy](https://github.com/python/mypy). If you’re using such tools, use the real import paths.

which matches this behaviour, I don't see the difference.

This package can just import directly from the other modules though with
```py
# __init__.py

from .file import Member
```

**Comment by aaugustin** [comment]
Thanks to PEP 690, I will be able drop the lazy imports mechanism when I drop support for Python < 3.12. Given that Python 3.7 is still supported and that Python gets a minor version every other year (I believe?) that's about 10 years from now :-/

**Comment by aaugustin** [comment]
@CaedenPH This works for me:

<img width="1136" alt="Screenshot 2022-07-29 at 08 58 25" src="https://user-images.githubusercontent.com/788910/181701605-0013ef25-729c-4c78-a8a6-33163f84c8a4.png">

I suspect your original problem was the same as this one (which I'm demonstrating with the standard library to rule out websockets):

<img width="1136" alt="Screenshot 2022-07-29 at 08 59 42" src="https://user-images.githubusercontent.com/788910/181701797-2710322d-e70a-4b42-8f87-f70786c8d39c.png">

----

Yes, for backwards-compatibility reasons, there are "magic" imports in websockets. If I could send a message to myself-from-eight-years-ago, I wouldn't expose all API in the root package.  Now it's too late :-(

**Comment by aaugustin** [comment]
Reopening to check if I can clarify the documentation further or make it easier to discover.

**Comment by ooliver1** [comment]
> Thanks to PEP 690, I will be able drop the lazy imports mechanism when I drop support for Python < 3.12. Given that Python 3.7 is still supported and that Python gets a minor version every other year (I believe?) that's about 10 years from now :-/

I don't see how that mindset even works, I said there is no need for "lazy imports", you can just use normal imports, no? It has the same maintainability as "lazy imports", just does not need to be so special and actually works with typing.

**Comment by ooliver1** [comment]
Then what is https://github.com/aaugustin/websockets/blob/main/src/websockets/__init__.py#L56 still there for? Just use relative imports to add them to the main package

**Comment by aaugustin** [comment]
It's that way because:

1. Long ago the library was simple and small and it was OK to cram everything in the toplevel namespace.
2. Now it's growing to support several implementations — Sans-I/O, asyncio - 2 versions, sockets & threads, trio, perhaps curio. Some of this work is public, other parts aren't. But I don't want trio to be a hard dependency of websockets.
3. I want to keep backwards compatibility for importing from the root package.

**Comment by aaugustin** [comment]
Ah, one more reason — as the library was undergoing significant restructuring, managing renames and deprecation warnings in a central place was much easier.

**Comment by aaugustin** [comment]
439dafa6 should fix it going forwards.
