### ISSUE TITLE
Connection is getting closed based on pong

### ISSUE THREAD

**Issue by gorkem2020** [aaugustin/websockets#1187]
Hello,

First of all, thank you for this awesome library. It is very easy to use and fast to deploy. However, I've been having an issue lately and noticed a behavior that I cannot understand the logic behind it.

Here is the scenario, I'm connecting a remote server with context manager and default parameters. So, the library handles the whole ping pong thing. It sends a ping message and receives a pong. So far so good... But sometimes the remote server, for some reason, does not send pong back. However, I'm getting all the messages I expect. around 100 messages a minute, so at least 1 message every second. So we know the connection is good, the remote server is alive, etc. 

My question is why does it close the connection? Even though it has not received a pong back in time, it still receives all the messages on time without any problem. It should ignore the ping pong as long as there are messages coming in, no? 

Thank you!

**Comment by aaugustin** [comment]
Pongs are mandatory in the spec. I don't want to add complexity to work around that bug in the server you're connecting to :-/ I would suggest adding `ping_timeout=None` to the `connect()` call as a workaround.

**Comment by gorkem2020** [comment]
> Pongs are mandatory in the spec. I don't want to add complexity to work around that bug in the server you're connecting to :-/ I would suggest adding `ping_timeout=None` to the `connect()` call as a workaround.

thanks!
