### ISSUE TITLE
Is there an example to explain the usage of websockets with ssl?

### ISSUE THREAD

**Issue by ghostplant** [aaugustin/websockets#119]
I don't know how to establish a wss server using this library, most of my try are replied with "Malformed HTTP message"

**Comment by ghostplant** [comment]
Well. I successful establish wss connection.

**Comment by skewty** [comment]
Do you mind sharing your example?

I'm getting ConnectionResetError on my client and can't figure out why.

**Comment by aaugustin** [comment]
Perhaps the tests will help:

- https://github.com/aaugustin/websockets/blob/858b261d7d5365128e4f302690892d16fa93e34c/websockets/test_client_server.py#L391-L393
- https://github.com/aaugustin/websockets/blob/858b261d7d5365128e4f302690892d16fa93e34c/websockets/test_client_server.py#L378-L381

**Comment by aaugustin** [comment]
Of course, depending on what you use on the client and the server side, you've got the happy mess of TLS certificate validation to deal with. Even if you have an "official" cert you still have to make sure Python loads CA certificates from somewhere... I'm not an expert of this.
