### ISSUE TITLE
IIS reverse proxy

### ISSUE THREAD

**Issue by ramezanifar** [aaugustin/websockets#1192]
My goal is to run a websocket server in local host and the clients access it via Windows Web Server IIS acting as a reverse proxy server.
Server runs at `localhost:5005` as shown below:
```
#!/usr/bin/env python

import asyncio
import websockets

async def echo(websocket):
    async for message in websocket:
        print(message)
        await websocket.send(message)

async def main():
    async with websockets.serve(echo, "localhost", 5005):
        await asyncio.Future()  # run forever

asyncio.run(main())
```
Then in IIS:
- In Application Request Routing Cache --> Server Proxy Setting --> Enable proxy, I checked.
- Under Sites --> Default Web Site, I added an application named `app` 
- Using URL Rewrite, I added the following rule:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxy" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:5005" logRewrittenUrl="true" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```
Now a client should be able to connect from `ws://localhost/app`. However connection fails and I get this exception in server:
```
connection handler failed
Traceback (most recent call last):
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 1149, in read_frame
    extensions=self.extensions,
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\framing.py", line 70, in read
    data = await reader(2)
  File "C:\Program Files\Python37\lib\asyncio\streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\server.py", line 232, in handler
    await self.ws_handler(self)
  File "D:/Robotic Framework/RoboticApps/UI_Framework/server.py", line 7, in echo
    async for message in websocket:
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 482, in __aiter__
    yield await self.recv()
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 553, in recv
    await self.ensure_open()
  File "C:\Users\amin.ramezanifar\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```
To make sure if IIS settings are correct, I used another websocket library named "simple-websocket-server" and it worked fine. Here is the server implementation:
```
from simple_websocket_server import WebSocketServer, WebSocket


class SimpleEcho(WebSocket):
    def handle(self):
        # echo message back to client
        self.send_message(self.data)

    def connected(self):
        print(self.address, 'connected')

    def handle_close(self):
        print(self.address, 'closed')


server = WebSocketServer('localhost', 5005, SimpleEcho)
server.serve_forever()
```
Can anyone tell me what the issue is?
I tried both an html client and a python client (unsuccessful with websockets module, successful with simple-websocket-server module).
Thank you

**Comment by aaugustin** [comment]
I'm not seeing anything wrong with what you describe.

The exception shown by websockets suggests that IIS closed the TCP connection. However, we don't know why.

Perhaps [turning on debug logs](https://websockets.readthedocs.io/en/stable/howto/cheatsheet.html#debugging) would give you a clue?

At worst, you can figure out which side closed the TCP connection with Wireshark, but that's pretty low level.

**Comment by ramezanifar** [comment]
The question is why IIS closes the connection?
IIS does not behave that way for few other websocket servers that I have tested and used.
An example is the code sample I put above using "simple-websocket-server".
In the documentation, I see a guide to use NGINX as reverse proxy. Can someone please provide a guide for IIS?
Thanks

**Comment by aaugustin** [comment]
... the minor issue being that "one of the developers" is probably "me" and I don't have a Windows install around nor knowledge of IIS :-(

Typically, cases of "$SETUP works with $LIBRARY but not websockets" happen because websockets provides more features than $LIBRARY, breaking $SETUP.

Let's try the most frequent offender -- could you add `compression=None` here:

```python
    ...
    async with websockets.serve(echo, "localhost", 5005, compression=none):
        ...
```

and see if that helps?

[This old stackoverflow question](https://stackoverflow.com/questions/34316825/websockets-reverse-proxy-in-iis-8) suggests that IIS disliskes compression on WebSocket connections.

**Comment by ramezanifar** [comment]
Thanks @aaugustin  for the solution. With that flag set to off, it works just fine.
I had come across this [instruction](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/httpcompression/) saying what should be done to enable compression. Evidently it does not help. With your hint about IIS not liking to compress, I found [this ](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/5a3498ee-b410-447c-930c-b1a08f60b6fa/arr30-doesnt-support-websocket-compression?forum=iisapplicationrequestrouting) that says **ARR3.0 doesn't support WebSocket compression**.
At this time, ARR3 (Application Request Routing) which is installed for IIS10 is the last version so we should probably wait for the future releases.
For other users that come here seeking a guide how to set IIS as reverse proxy, there is pictorial guide [here](https://www.microfocus.com/documentation/extend-acucobol/1011/GUID-81B323FA-6AE6-438A-A1F5-016D7F45A097.html). 
Thank you
