### ISSUE TITLE
bit coin bit coin bitcon bitcoin 

### ISSUE THREAD

**Issue by blueForestIcarus** [aaugustin/websockets#1198]
bitcoin
bitcoin
bitcoin
bitcoin
bitcoin
bitcoin

:) :) :) :)

**Comment by blueForestIcarus** [comment]
![image](https://user-images.githubusercontent.com/6549542/180587094-dd52713f-9d78-4ed9-909f-1759e83566a6.png)

**Comment by blueForestIcarus** [comment]
![image](https://user-images.githubusercontent.com/6549542/180587101-09c909e2-8590-4e95-ba81-62d38d49089d.png)

**Comment by blueForestIcarus** [comment]
![image](https://user-images.githubusercontent.com/6549542/180587123-328171d3-6a64-425a-8aad-f986aa74322b.png)
^ typical bitcoin mining rig

**Comment by garryspins** [comment]
cool

**Comment by lgrahl** [comment]
Nice whataboutism. Now, grow up and respect the author's choice.

**Comment by blueForestIcarus** [comment]
He's a faggot.

**Comment by blueForestIcarus** [comment]
And his stance on crypto is very convenient for the CTO of a payment processing company.

**Comment by aaugustin** [comment]
FTR my stance on crypto predates my current position at Qonto. I was working in the media industry back then.

The discussion here isn't leading to improving websockets, therefore I'm going to lock the thread.

**Comment by blueForestIcarus** [comment]
People that manage infrastructure, such as a websocket library for a major programming language, have an obligation for a certain amount of diligence. Closing issues, on grounds admittedly unrelated to the success of the project, just so you can pretend to be a good person while shilling your industry, is not an acceptable way to manage a project. It is degenerate.
