### ISSUE TITLE
websocket.send() doesn't fail on a closed websocket

### ISSUE THREAD

**Issue by yoniker** [aaugustin/websockets#1201]
Hi!

So I am using Sanic (based on @aaugustin 's  suggestion), which uses this package for its ws implementation.
Running a simple server:

```
from sanic import Sanic
from sanic.response import json as json_response
import json

app = Sanic("SanicChatApp")
app.config.WEBSOCKET_PING_INTERVAL = 300
app.config.WEBSOCKET_PING_TIMEOUT = 600

connected_websockets = {}

@app.route('/websockets/message_user/<user_id:str>', methods=["POST"])
async def send_user_message_by_url(request, user_id: str):
    data = request.json
    sent = await send_websocket_message(user_id=user_id, message=data)
    if sent:
        return json_response({'result': 'message_sent'})
    return json_response({'result': 'message_not_sent'})

@app.route('/websockets/healthcheck', methods=["GET"])
async def say_healthy(request):
    return json_response({'status': 'websockets service is healthy!'})


@app.websocket("/websockets/register")
async def register(request, websocket):
    user_id = request.headers.get('user_id')
    if user_id is None:
        print('no user id header was sent')
        return
    
    print(f'connected with user {user_id}')
    
    connected_websockets[user_id] = websocket
    print(f'Registered user {user_id}')
    try:
        print(f'websocket ping interval is {websocket.ping_interval}')
        await websocket.keepalive_ping()
        print(f'connection with user {user_id} was closed')
        if user_id in connected_websockets:
             del connected_websockets[user_id]
    finally:
        if user_id in connected_websockets:
             del connected_websockets[user_id]
        await websocket.close()


async def send_websocket_message(user_id, message):
    if user_id not in connected_websockets:
        print(f'user {user_id} not found in connected_websockets!')
        print(f'current users are {connected_websockets.keys()}')
        return False
    try:
        websocket = connected_websockets[user_id]
        await websocket.send(json.dumps(message))
        print(f'sent {message} successfully!')
        return True
    except Exception as e:
        print(f'failing ws because of exception {e}')
        return False

#ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
#ssl_context.load_cert_chain(certfile='keys/dordating.crt', keyfile='keys/dordating.key')
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000,) #ssl=ssl_context)


'''

docker build . -t websockets:1

docker run -d --rm -p5000:5000/tcp websockets:1

'''
```

When the client closes the app, there are a few minutes where the endpoint /send_websocket_message 
can be called, and yet websocket.send doesn't raise any exception (to my understanding it should raise an exception if the ws was closed and the server doesn't know about it), and the user_id is still in the dictionary connected_websockets.

So the call wrongfully succeeds. What's going on?

**Comment by aaugustin** [comment]
I suspect this is an issue in Sanic's integration rather than in websockets itself.

Specifically, `await websocket.keepalive_ping()` doesn't correspond to anything in websockets. So I cannot tell you why this returns later than you expect.

I would recommend:

- enabling debug logs to understand if your client sends a close frame before exiting: that should be enough for websockets to reject further writes
- checking whether Sanic detects the end of the TCP stream and calls `write_eof()` on the `websockets.server.ServerConnection` instance

**Comment by yoniker** [comment]
"If you want to do both in the same server, look at HTTP frameworks that build on top of websockets to support WebSocket connections, like Sanic."
This is part of a document you have written, so I'm surprised you sent me away to debug...

Since I want to implement a pure websockets microservice, i would have used websockets by itself without sanic, but the microservice needs to support an endpoint such as /send_message/<userid> which has to be http, and according to the documentation this isn't supported (http has just a minimal,healthcheck support according to the documentation).

This kind of an HTTP endpoint is necessary and common. Without the ability to write that simple microservice in websockets or Sanic (without having to debug things myself as was suggested), I'm not sure how usable the library really is (aside from small toy examples)...

**Comment by aaugustin** [comment]
websockets is sufficiently usable that [over 62k GitHub projects](https://github.com/aaugustin/websockets/network/dependents) depend on it as of today. I'm sorry it didn't work for you.
