### ISSUE TITLE
Missing closing code 1006

### ISSUE THREAD

**Issue by aprilahijriyan** [aaugustin/websockets#1202]
Hi, I just realized, that closing code `1006` is not available at https://github.com/aaugustin/websockets/blob/57a1325795cc7b9166a5b4599c34c4869d8b2ab6/src/websockets/frames.py#L78-L91

I'm using starlette, where when I close a websocket connection with code `1006` it throws a `ProtocolError` exception from https://github.com/aaugustin/websockets/blob/57a1325795cc7b9166a5b4599c34c4869d8b2ab6/src/websockets/frames.py#L434-L443

**Comment by aaugustin** [comment]
You aren't allowed to close a connection with code 1006.

From RFC 6455:

```
   1006

      1006 is a reserved value and MUST NOT be set as a status code in a
      Close control frame by an endpoint.  It is designated for use in
      applications expecting a status code to indicate that the
      connection was closed abnormally, e.g., without sending or
      receiving a Close control frame.
```
