### ISSUE TITLE
Document Tutorial Code 

### ISSUE THREAD

**Issue by PloyPanmaneeCNC** [aaugustin/websockets#1204]
In https://websockets.readthedocs.io/en/latest/intro/quickstart.html#connect-from-a-browser `show_time.py` code on line 8 `async def show_time(websocket):` when run html and got error 
```
Python 3.7.9 (bundled)
>>> %Run show_time.py
Error in connection handler
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\websockets\legacy\server.py", line 293, in handler
    await self.ws_handler(self, path)
TypeError: show_time() takes 1 positional argument but 2 were given

```

but in https://websockets.readthedocs.io/en/9.0.1/intro.html#browser-based-example code work normally it's `async def time(websocket, path):`

**Comment by aaugustin** [comment]
Could you check you're looking at the version of documentation that matches the versions of websockets that you installed?

**Comment by PloyPanmaneeCNC** [comment]
It's said 10.3 but when I check with my interpreter it's 9.0, Sorry it's my mischeck so when I update and run again it word normally
