### ISSUE TITLE
Python websockets.recv() returns the message that has just been sent

### ISSUE THREAD

**Issue by damc** [aaugustin/websockets#1221]
I'm using `websockets` Python package. I have a websocket server that listens for a connection.

I am including my code below. The expected result is that after opening the connections, the server should await for a message from the client. After that it should send a message "hi" and wait for another message. After that it should send another message ("hi2") etc.

However, the program doesn't behave in the expected way. Everything is all right to the second call of `await websocket.recv()`. That call returns "hi" immediately, without waiting for the message sent from the client. So it returns the message that it has just sent before, instead of waiting for the client to send the message.

```Python
from asyncio import get_event_loop
from websockets import serve

async def run(websocket, path):
    print("path", path)
    print("connection open! hooooraaaaayyyyy")
    message = await websocket.recv()
    print(message)
    await websocket.send('hi')
    print("I've just said hi")
    message = await websocket.recv() # returns 'hi' immediately (its own message)
    print(message)
    await websocket.send('hi2')
    message = await websocket.recv() # returns 'hi2'
    print(message)
    await websocket.send('hi3')
    print("end of run")


start_server = serve(run, "localhost", 8765)

get_event_loop().run_until_complete(start_server)
get_event_loop().run_forever()
```

I decided to ugly fix it with an additional `await websocket.recv()` line after each `await websocket.send()` line. That way, the recv() after the send() will return the message that has just been sent and the second `await websocket.recv()` will await for the message from the client. So the code now looks like that:

```Python
async def run(websocket, path):
    print("path", path)
    print("connection open! hooooraaaaayyyyy")
    message = await websocket.recv()
    print(message)
    await websocket.send('hi')
    await websocket.recv() # will return 'hi'
    print("I've just said hi")
    message = await websocket.recv() # will wait for the client
    print(message)
    await websocket.send('hi2')
    await websocket.recv()
    message = await websocket.recv()
    print(message)
    await websocket.send('hi3')
    await websocket.recv()
    print("end of run")
```

That solved the problem. But at some point when I run the program, the program randomly started to behave differently - it started to await for the client to return the message. So now it was awaiting two times. So I brought it back to what it was before and it worked as expected.

But the program seems to randomly sometimes act in the expected way (`await websocket.recv()` returning the message from the client) and sometimes in the unexpected way (`await websocket.recv()` return the message that has just been sent by the server). So how can I make it work so that it works always?

**Comment by aaugustin** [comment]
Maybe your client echoes messages sent by the server?

You should try turning on debug logs. This will show what is going on at the network level.

https://websockets.readthedocs.io/en/stable/topics/logging.html?highlight=debug%20logs#configure-logging

**Comment by damc** [comment]
No, my client is not echoing messages send by server. I will try turning the deubg logs on and I'll see.

**Comment by damc** [comment]
I've just checked the DEBUG logs. In the below example, I sent a message like this:

```
'{"type": "say", "data": {"message": "What change"}}'
```

As you can see, in the below logs that message has been returned, but there is nothing that client does that sends back this message. Potentially, this might an issue with the client, but I checked the code on the client side and I didn't find anything that would be responsible for echoing the message.

```
DEBUG:websockets.server:> TEXT '{"type": "say", "data": {"message": "What change"}}' [51 bytes]
DEBUG:websockets.server:< TEXT '{"type": "say", "data": {"message": "What change"}}' [51 bytes]
DEBUG:websockets.server:% sending keepalive ping
DEBUG:websockets.server:> PING ce 8e 61 a9 [binary, 4 bytes]
DEBUG:websockets.server:< PONG ce 8e 61 a9 [binary, 4 bytes]
DEBUG:websockets.server:% received keepalive pong
DEBUG:websockets.server:% sending keepalive ping
DEBUG:websockets.server:> PING 49 53 e3 b1 [binary, 4 bytes]
DEBUG:websockets.server:< PONG 49 53 e3 b1 [binary, 4 bytes]
DEBUG:websockets.server:% received keepalive pong
DEBUG:websockets.server:% sending keepalive ping
DEBUG:websockets.server:> PING a1 f6 4a 07 [binary, 4 bytes]
DEBUG:websockets.server:< PONG a1 f6 4a 07 [binary, 4 bytes]
DEBUG:websockets.server:% received keepalive pong
DEBUG:websockets.server:< TEXT 'anything' [8 bytes]
```

The 'anything' message at the end has been sent by the client, so that's ok.

Are you able to reproduce that error yourself? For me, it happens randomly - sometimes it work as it should, sometimes I receive the message back.

**Comment by damc** [comment]
All right, I tested it with this: https://www.xhcode.com/websocket/ and I don't get the issue if I use the client from that website. That suggests that the issue is with my client, not with the library. So I will investigate the client-side deeper.

**Comment by aaugustin** [comment]
I am positive that the message is coming back on the WebSocket connection. Check with Wireshark if you don't trust websockets' logs.
