### ISSUE TITLE
Should servers expect a PONG or a PING to keep connection alive?!

### ISSUE THREAD

**Issue by Serpens66** [aaugustin/websockets#1222]
I use websockets as client.
Previously I used the "ws4py" module and my code is adjusted to work with both.

I noticed a difference in the "ping_intervall" from websockets and the "heartbeat_freq" from ws4py:
**websockets**: Sends a **Ping** frame every x seconds: https://github.com/aaugustin/websockets/blob/main/src/websockets/legacy/protocol.py
**ws4py**: Sends a **Pong** frame every x seconds: https://github.com/Lawouach/WebSocket-for-Python/blob/961c07ce16ce4eedc34ca1fdacd29442870feccc/ws4py/websocket.py

And the strange thing is, that there are servers that tell me they expect a "ping" every 30 seconds in documentation , or they will disconnect, while in fact they need a pong. I already overwrote the Heartbeat class from ws4py and confirmed that the connection closes when sending a real Ping, and it stays open when sending a Pong instead every x seconds.

So... why does ws4py sends a pong keepalive and why do some (all?) servers expect a pong?
And should websockets also switch to sending a pong as keepalive? Or at least add an init parameter for this to enable it?

**Comment by aaugustin** [comment]
Both methods are legit: you can:

- send a ping and expect a pong; this is what websockets does;
    - if you get the pong, you know that everything is working at least at the network and protocol level;
- send an unsolicited ping; this is what ws4py does;
    - this is just a heartbeat: it can help keep the TCP connection open but doesn't tell you if everything works.

**Comment by aaugustin** [comment]
Some servers may require clients to send ping at regular intervals. Some servers also expect clients to send a text message containing the string "ping", moving the heartbeat to the application layer. Different people adopt different strategies here.

**Comment by aaugustin** [comment]
You can customize what websockets does with `ping_interval` and `ping_timeout`.

There is no built-in way to send pongs at regular intervals. However, you can do it as follows:


```python
async def send_heartbeat_pongs(websocket, interval=30):
    while True:
        await asyncio.sleep(interval)
        try:
            await websocket.pong()
        except websockets.exceptions.ConnectionClosed:
            break

async def main():
    async with websockets.connect(...) as websocket
        asyncio.create_task(send_heartbeat_pongs(websocket))
        # do stuff with the connection

asyncio.run(main())
```

(untested, I just typed the code in the comment box, but it shouldn't be too far from a version that actually works)

**Comment by Serpens66** [comment]
Thank you very much.

I now ended up copy pasting your keepalive_ping function and adding an optional pong to it. And then I found that this is also the way to implement latency measurement ( https://github.com/aaugustin/websockets/issues/1195 ) on my own, which would work if there wasn't this problem: https://github.com/aaugustin/websockets/issues/1177

**Comment by weaming** [comment]
How can I send back a PONT to server after receiving a PING from server?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/latest/faq/common.html#how-do-i-respond-to-pings
