### ISSUE TITLE
JWT Token Authorization While SSL disabled

### ISSUE THREAD

**Issue by Xyonia** [aaugustin/websockets#1223]
Hello friends.

I am trying to connect my Lora gateway and while doing that using WebSockets as the library especially to disable SSL verification. The code automatically log in and get a JWT token. Unfortunately, i cannot send this token to authorize the WebSocket side of the system i cannot pass the JWT with any method.

Postman can connect easily with same wss address and extra header as:
KEY: Sec-WebSocket-Protocol
VALUE: Bearer, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcyIsImV4cCI6MTY2MjAzNjIxMSwiaWQiOjEsImlzcyI6ImFzIiwibmJmIjoxNjYxOTQ5ODExLCJzdWIiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbkBtY2lvdC5jb20ifQ.HYo_ZWSF18cmUqKWs6QU8psAGgutcBBhlrkDTCY-BNw

```
import requests
from requests.auth import HTTPDigestAuth
import warnings
import os
import sys
import grpc
import websockets
import asyncio
import pathlib
import ssl
from chirpstack_api.as_pb.external import api
warnings.simplefilter("ignore")



url = "https://192.168.20.100:8080/api/internal/login"
data ={
          "email": email",
          "password": "password"
       }



response = requests.post(url, json=data, verify=False)
print("Status Code:", response.status_code)
jwt = str(response.json())
jwt = jwt.split("'")[3]
token=jwt
headers = {"Authorization": "Bearer" + " " + jwt}
print(token)

print('Initializing WebSocket Connection...')

#HIGHLY INSECURE
ssl_context = ssl.SSLContext()
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE
#HIGHLY INSECURE
#todo kluge
uri = "wss://@192.168.20.100:8080/api/devices/0000000000000003/events"
header=("Sec-WebSocket-Protocol: Bearer,")
created = ("\n"+token)
list1 = ["Sec-WebSocket-Protocol", created]

data2 ={"Sec-WebSocket-Protocol:Bearer, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcyIsImV4cCI6MTY2MjAzNjIxMSwiaWQiOjEsImlzcyI6ImFzIiwibmJmIjoxNjYxOTQ5ODExLCJzdWIiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbkBtY2lvdC5jb20ifQ.HYo_ZWSF18cmUqKWs6QU8psAGgutcBBhlrkDTCY-BNw"
       }



async def hello():
##    async with websockets.connect(uri, ssl=ssl_context) as websocket:
    websockets.handshake.build_request(data3)
    async with websockets.connect(
        "wss://192.168.20.100:8080/api/devices/0000000000000003/events",
        ssl=ssl_context
        ) as websocket:
        greeting = await websocket.recv()
        print(f"< {greeting}")
asyncio.get_event_loop().run_until_complete(hello())

```

Is there any point that i am missing ?
Thanks

**Comment by aaugustin** [comment]
It's quite weird to pass authentication information in the `Sec-WebSocket-Protocol` header.

You can do that with the `subprotocols` argument:

```python
    async with websockets.connect(
        "wss://192.168.20.100:8080/api/devices/0000000000000003/events",
        subprotocols=["Bearer, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcyIsImV4cCI6MTY2MjAzNjIxMSwiaWQiOjEsImlzcyI6ImFzIiwibmJmIjoxNjYxOTQ5ODExLCJzdWIiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbkBtY2lvdC5jb20ifQ.HYo_ZWSF18cmUqKWs6QU8psAGgutcBBhlrkDTCY-BNw"],
        ...,
    ) as websocket:
        ...
```

PS - you accidentally posted credentials above, you should rotate them and remove them from your message.

**Comment by aaugustin** [comment]
You may also want to turn on debug logs to see what websockets is sending exactly.

**Comment by Xyonia** [comment]
Thank you so much for your help sir.

Unfortunatelyi when i tried exactly same method you mentioned (with ssl/without ssl) both gives me this error.


``File "C:\Users\ozan_\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 497, in __init__
    validate_subprotocols(subprotocols)
  File "C:\Users\ozan_\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\headers.py", line 481, in validate_subprotocols
    raise ValueError(f"invalid subprotocol: {subprotocol}")
ValueError: invalid subprotocol: Bearer, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcyIsImV4cCI6MTY2MjAzNjIxMSwiaWQiOjEsImlzcyI6ImFzIiwibmJmIjoxNjYxOTQ5ODExLCJzdWIiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbkBtY2lvdC5jb20ifQ.HYo_ZWSF18cmUqKWs6QU8psAGgutcBBhlrkDTCY-BNw``

PS- Credentials was temporary but i removed them, thank you.

**Comment by aaugustin** [comment]
Ah, right, this isn't a legal value for the `Sec-WebSocket-Protocol` header, so you cannot do that.

The next thing to try would be:

```python
    async with websockets.connect(
        "wss://192.168.20.100:8080/api/devices/0000000000000003/events",
        extra_headers={"Sec-WebSocket-Protocol": "Bearer, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhcyIsImV4cCI6MTY2MjAzNjIxMSwiaWQiOjEsImlzcyI6ImFzIiwibmJmIjoxNjYxOTQ5ODExLCJzdWIiOiJ1c2VyIiwidXNlcm5hbWUiOiJhZG1pbkBtY2lvdC5jb20ifQ.HYo_ZWSF18cmUqKWs6QU8psAGgutcBBhlrkDTCY-BNw"},
        ...,
    ) as websocket:
        ...
```

I don't know if websockets will accept that. You're trying to do something that the RFC prohibits and websockets generally tries to prevent that. But I don't remember adding a check for this.

**Comment by Xyonia** [comment]
The `Sec-WebSocket-Protocol` is a must when connecting via Postman too. When i tried to add as `extra_headers` it throws an error in case of it is not defined as a subprotocol.

```

File "C:\Users\ozan_\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\Users\ozan_\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 658, in __await_impl__
    await protocol.handshake(
  File "C:\Users\ozan_\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 336, in handshake
    self.subprotocol = self.process_subprotocol(
  File "C:\Users\ozan_\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 247, in process_subprotocol
    raise InvalidHandshake("no subprotocols supported")
websockets.exceptions.InvalidHandshake: no subprotocols supported
```

**Comment by Xyonia** [comment]
Ok, thank you for your help.
