### ISSUE TITLE
Multiple headers with same name

### ISSUE THREAD

**Issue by iudeen** [aaugustin/websockets#1226]
Is setting multiple headers with same name not allowed when using the legacy server?

Currently, when we set multiple headers with same name, an exception is raised.

Is there a way to overcome this?

**Comment by aaugustin** [comment]
Can you provide the full stack trace please?

**Comment by iudeen** [comment]
```
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\uvicorn\lib\site-packages\websockets\legacy\server.py", line 165, in handler
    await self.handshake(
  File "D:\ProgramData\Anaconda3\envs\uvicorn\lib\site-packages\websockets\legacy\server.py", line 643, in handshake
    response_headers.setdefault("Server", self.server_header)
  File "D:\ProgramData\Anaconda3\envs\uvicorn\lib\_collections_abc.py", line 1007, in setdefault
    return self[key]
  File "D:\ProgramData\Anaconda3\envs\uvicorn\lib\site-packages\websockets\datastructures.py", line 119, in __getitem__
    raise MultipleValuesError(key)
```

**Comment by aaugustin** [comment]
It looks like `Headers.setdefault` doesn't work when a key already has multiples values. That would be a bug.

(Out of curiosity, what is the use case for setting multiple `Server` headers? I've never seen that.)

**Comment by iudeen** [comment]
Thanks for the reply.

> It looks like `Headers.setdefault` doesn't work when a key already has multiples values. That would be a bug.

Oh, if that's the case, can we fix this with a PR? I can try to help.

> (Out of curiosity, what is the use case for setting multiple `Server` headers? I've never seen that.)

Well, this emerged while working on a PR in Uvicorn. Uvicorn allows users to specify their own headers. This is to cover a scenario where they might add `Server` header.

I personally don't think of, or have seen, any real any benefit in setting multiple `Server` header.

**Comment by aaugustin** [comment]
As mentioned in the merge request, the current behavior of `Headers.setdefault` is correct. We cannot change it because it returns the current value when present and we don't want to do this when there are multiple values.

Given that there's no use case for multiple `Server` or `User-Agent` headers, I don't see any reason for spending more time on this.
