### ISSUE TITLE
how to make the websockets.connect() go through with http proxy?

### ISSUE THREAD

**Issue by Lamchi-Joo** [aaugustin/websockets#1230]

**Comment by Lamchi-Joo** [comment]
how to make the websockets.connect() go through with http proxy?

**Comment by Lamchi-Joo** [comment]
i didn't  find any support proxy function in this issues  ----->  https://github.com/aaugustin/websockets/issues/364

**Comment by aaugustin** [comment]
Indeed, that's why #364 is still open.

**Comment by ifreedom** [comment]
@Lamchi-Joo you can use `websocket-client` library instead. To use `websocket-client` with `asyncio`, you can look at [wsapi.py](https://github.com/ifreedom/python-ftx/blob/master/ftx/wsapi.py) as a reference.

**Comment by isaackogan** [comment]
> @Lamchi-Joo you can use `websocket-client` library instead. To use `websocket-client` with `asyncio`, you can look at [wsapi.py](https://github.com/ifreedom/python-ftx/blob/master/ftx/wsapi.py) as a reference.

Is running in executor a valid solution for high volume?
