### ISSUE TITLE
How to get the status code for websockets.client.connect?

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#1231]
Hi! I apologize if i missed in documentation, but how can i get the status code of
a connection attempt?
Sometime my users do not have the right certificates and have something like this in logs:
```
ERROR:2022-09-21 19:30:23,345 Could NOT establish connection (WebSocket) to A.B.C.D:8097
InvalidStatusCode(401, Headers([('Cache-Control', 'private'), ('vary', 'accept-encoding'), ('Content-Type', 'text/html;charset=utf-8'), ('Content-Language', 'en'), ('Content-Length', '740'), ('Date', 'Wed, 21 Sep 2022 11:30:22 GMT')]))
```
Is there a way to get the status code to react and print user-friendly mesaages?
Thanks a lot!

**Comment by adriansev** [comment]
oh, i see now that i can catch `InvalidStatusCode` and than i have `e.status_code` .. did i get it right? thanks a lot!!

**Comment by aaugustin** [comment]
Yes this is the public API for this!
