### ISSUE TITLE
Error when I disconnect my client during a connection

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [aaugustin/websockets#1237]
@aaugustin I am receiving this error when I disconnect my client in the middle of a connection request.
I am using Python 3.10 and websockets 10.3
```
ERROR:    opening handshake failed
Traceback (most recent call last):
  File "C:\Users\s******5\PycharmProjects\websocket\venv\lib\site-packages\websockets\legacy\server.py", line 163, in handler
    await self.handshake(
  File "C:\Users\s******5\PycharmProjects\websocket\venv\lib\site-packages\websockets\legacy\server.py", line 597, in handshake
    raise self.connection_closed_exc()  # pragma: no cover
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by ChaitanyaYeole02** [comment]
@aaugustin 
As all my clients disconnect and connect frequently, I often get this error in my sentry.

```
        # The connection may drop while process_request is running.
        if self.state is State.CLOSED:
            raise self.connection_closed_exc()  # pragma: no cover
```
I can see you have raise this error, but is there any way to avoid this?

**Comment by aaugustin** [comment]
Not sure there's a good way to catch this. Needs investigation.

**Comment by ChaitanyaYeole02** [comment]
Cannot we just do this?

```
        # The connection may drop while process_request is running.
        if self.state is State.CLOSED:
            warnings.warn("opening handshake failed", ConnectionAbortedError)
```

**Comment by aaugustin** [comment]
"Can we just make a backwards-incompatible change?"

:-)

**Comment by ChaitanyaYeole02** [comment]
Nice one, LMAO,  my bad. I will look into it, if this can be done

**Comment by aaugustin** [comment]
Jokes aside, this requires looking at the history of when this code was introduced. Maybe it was in reaction to another issue. Then we should ensure fixing you use case doesn't break someone else's use case.

I don't have an immediate idea of what the solution could look like.

**Comment by aaugustin** [comment]
In fact I determined websockets could end up in an inconsistent state and "fixed" it in #984. This was never reported by a user — presumably because it's uncommon to have a slow `process_request`.

I am tempted to handle this case in this block:

https://github.com/aaugustin/websockets/blob/569ba1e04aa78313fd4bceb1cdae59c822682add/src/websockets/legacy/server.py#L177

so you don't end up in the catch-all exception handler:

https://github.com/aaugustin/websockets/blob/569ba1e04aa78313fd4bceb1cdae59c822682add/src/websockets/legacy/server.py#L210

**Comment by aaugustin** [comment]
This would be a good time to add a test (and it's super annoying to write tests for that kind of behavior — maybe you should let me do that part...)

**Comment by ChaitanyaYeole02** [comment]
Ohh, I get it now. If you need any help in the test cases let me know :)

**Comment by ChaitanyaYeole02** [comment]
I will check it from my side once and let you know the solution or any idea I got while testing and also does it affect any other use case.

**Comment by ChaitanyaYeole02** [comment]
> In fact I determined websockets could end up in an inconsistent state and "fixed" it in #984. This was never reported by a user — presumably because it's uncommon to have a slow `process_request`.
> 
> I am tempted to handle this case in this block:
> 
> https://github.com/aaugustin/websockets/blob/569ba1e04aa78313fd4bceb1cdae59c822682add/src/websockets/legacy/server.py#L177
> 
> so you don't end up in the catch-all exception handler:
> 
> https://github.com/aaugustin/websockets/blob/569ba1e04aa78313fd4bceb1cdae59c822682add/src/websockets/legacy/server.py#L210

Yeah, then I guess it will not hurt any other use case.

**Comment by ChaitanyaYeole02** [comment]
@aaugustin Did you have the time to test the solution?

**Comment by aaugustin** [comment]
In fact there's already a test exercising this code path (probably `test_connection_error_during_opening_handshake`). #1242 should fix it.

**Comment by aaugustin** [comment]
I tested manually by running this server:

```python
#!/usr/bin/env python

import asyncio
import websockets

async def process_request(path, request_headers):
    for counter in range(5, 0, -1):
        print(counter)
        await asyncio.sleep(1)

async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)

async def main():
    server = await websockets.serve(echo, "localhost", 8765, process_request=process_request)
    await server.serve_forever()

if __name__ == "__main__":
    asyncio.run(main())
```

and connecting with `python -m websockets ws://localhost:8765/` and interrupting the client before the countdown completes.

On the main branch, I get the same traceback you reported once the countdown completes.

```
opening handshake failed
Traceback (most recent call last):
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 165, in handler
    await self.handshake(
  File "/Users/myk/dev/websockets/src/websockets/legacy/server.py", line 601, in handshake
    raise self.connection_closed_exc()  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

With the changes in the #1242, I don't.
