### ISSUE TITLE
Unable to pass long authorization token

### ISSUE THREAD

**Issue by stepienj** [aaugustin/websockets#1239]
It is not possible to pass a JWT token longer than 4KB when using 'Authorization' header or Url param

I see hardcoded limitation in the legacy/http.py:
```
    # Security: this guarantees header values are small (hard-coded = 4 KiB)
    if len(line) > MAX_LINE:
        raise SecurityError("line too long")
```

**Comment by aaugustin** [comment]
Oh well... monkey-patch the limit? I don't know your constraints here but a 4kB JWT doesn't sound right to me...

**Comment by stepienj** [comment]
Yes, 4.5KB is my extreme header length, I know this is not good, but never hit the limit, I searched the web and found these values for the default header length
- Apache - 8K
- Nginx - 4K-8K
- IIS - 8K-16K
- Tomcat - 8K – 48K
- Node (<13) - 8K; (>13) - 16K

Maybe worth to consider increasing and/or making the length configurable?

**Comment by aaugustin** [comment]
There was a somewhat related discussion in #743. Maybe I should just change it to 8k and call it a day.

**Comment by aaugustin** [comment]
This will be configurable in version 13.0: https://github.com/python-websockets/websockets/commit/bbb316155a5aeb719f262873a5b29a98c19b25d9.

Please be aware that, if you are currently monkey-patching MAX_LINE, that will break in version 13.0. You will have to set the WEBSOCKETS_MAX_LINE_LENGTH environment variable instead.
