### ISSUE TITLE
legacy http MAX_LINE

### ISSUE THREAD

**Issue by IlyaDjurin** [aaugustin/websockets#1243]
Hello!
I recently ran into the problem of limiting the header row (MAX_LINE) https://github.com/aaugustin/websockets/blob/569ba1e04aa78313fd4bceb1cdae59c822682add/src/websockets/legacy/http.py#L196.
In my case i have cookie "line" more then 4110 bytes, and I would like to make this parameter configurable (by env), i don't want to trim cookie from the nginx side.
Can i change this line (https://github.com/aaugustin/websockets/blob/569ba1e04aa78313fd4bceb1cdae59c822682add/src/websockets/legacy/http.py#L14)  to something like this:
`MAX_LINE = os.environ.get("WEBSOCKET_MAX_LINE", default=4110)`

**Comment by aaugustin** [comment]
Does 8ce4739b7efed3ac78b287da7fb5e537f78e72aa help?

I understand that it isn't what you suggest but currently there is no "configuration by env variables" in websockets and I'm resisting the addition of a new configuration mechanism without a strong justification.

**Comment by IlyaDjurin** [comment]
Thanks, 8192 will be enough, a larger value will cut off nginx.
Can you tell me when these changes will be in the next version 10.4?

**Comment by aaugustin** [comment]
I don't really schedule releases.

In the meantime, if needed, you can monkey-patch it.

**Comment by gordianberger** [comment]
FYI https://github.com/aaugustin/websockets/commit/8ce4739b7efed3ac78b287da7fb5e537f78e72aa does not actually change the legacy class or am I wrong?

**Comment by aaugustin** [comment]
Ha. Good point. I forgot that the constants were duplicated.

**Comment by aaugustin** [comment]
This will be configurable in version 13.0: https://github.com/python-websockets/websockets/commit/bbb316155a5aeb719f262873a5b29a98c19b25d9.

Please be aware that, if you are currently monkey-patching MAX_LINE, that will break in version 13.0. You will have to set the WEBSOCKETS_MAX_LINE_LENGTH environment variable instead.
