### ISSUE TITLE
Buffer Settings and error 1009 (message too big)

### ISSUE THREAD

**Issue by bmoscon** [aaugustin/websockets#1247]
From my understanding of the documentation, `max_size` should allow a client to increase the size of the buffer for expected messages. I have mine set to 8MB, and yet I get an error:

```
websockets.exceptions.ConnectionClosedError: received 1009 (message too big) Max frame length of 65536 has been exceeded.
```

Two questions here, and perhaps I have misunderstood the documentation. The docs indicate that the default is 1MB, so I'm wondering where the 65k limit its saying has been breached is coming from and second, I increased it to far over 65k, so why isn't that being honored? I'm not sure if the `max_size` parameter actually influences the max frame length or not. Am I using the wrong parameter?

**Comment by aaugustin** [comment]
"Max frame length of 65536 has been exceeded" isn't generated by websockets. Furthermore, 65536 is smaller than the default limit of websockets.

I believe you have successfully changed the maximum size in your client but you are still hitting a limit set by the server, which generates this error.

Try configuring your server in addition to the websockets client.

**Comment by bmoscon** [comment]
Thank you for taking the time to explain that!
