### ISSUE TITLE
 Quote this project for game server development.

### ISSUE THREAD

**Issue by JackLuguibin** [aaugustin/websockets#1248]
Hello, I would like to quote this project for game server development, do you have any good suggestions?

**Comment by aaugustin** [comment]
Hello, I'm not sure what you mean by "quote this project". Can you clarify your question please?

**Comment by JackLuguibin** [comment]
> Hello, I'm not sure what you mean by "quote this project". Can you clarify your question please?

I mean I want to import this package to design a game server, have you considered a solution in this respect?
