### ISSUE TITLE
Copy button on docs page copies line numbers along with code

### ISSUE THREAD

**Issue by dhirajgagrai** [aaugustin/websockets#1251]
In the [Quick start](https://websockets.readthedocs.io/en/stable/intro/quickstart.html) page, there are blocks of code which have a copy button. If copying through that button, it also adds line numbers to the clipboard.

I think it's a problem with the sphinx-copybutton extension. I found a reference to this issue [here](https://github.com/executablebooks/sphinx-copybutton/pull/178). It seems that they have fixed it.

**Comment by aaugustin** [comment]
OK, this will get fixed after:

1. sphinx-copybutton makes a release
2. websockets makes a release (and docs are built with this new version)


Thank you for letting me know; I wasn't aware of the issue.

**Comment by aaugustin** [comment]
1. happened on Nov 15.

**Comment by aaugustin** [comment]
I can confirm that this doesn't happen anymore with `sphinx-copybutton==0.5.1`.

Given that no other action is necessary — other than making a release — I will close this issue now.

Thank you for reporting it and diagnosing it.
