### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'ws_handler' and 'ws_server'

### ISSUE THREAD

**Issue by Jmmx1237** [aaugustin/websockets#1252]
Hi, I' m trying to migrate my code from another websocket module to websockets.

Now my script doesn't work with websockets and I can't find the error. Unfortunately the examples in the documentation are not quite enough for me. Maybe someone could take a quick look at where the error is?

I think the error is that the call "async with websockets.serve" is not implemented correctly? How do i get the server up and running?

Edit: Code deleted in this post, added short example in a new comment.

**Comment by aaugustin** [comment]
The code you pasted contains far too much experimental or commented-out code to be sure what you're trying to achieve. It runs both one client and one server.

If you want to run a server and have the `Websocket.handler` method to handle new connections (ignoring the client connection to `wss://echo.websocket.org`) this should do:

```python
ws = Websocket()
async with websockets.serve(ws.handler, '192.168.0.24', PORTNUM):
    await asyncio.Future()
```

If that doesn't help, please provide a minimal example of what doesn't work for you (max 10 lines).

**Comment by Jmmx1237** [comment]
Thanks for the reply. Yes, it should be both a websocket server and a modbus client. I will build a minimal example.

Using partial, I want to pass other parameters that are important for modbus. Client contains the modbus connection, there must be also an error. I think I did also something wrong when I migrated my code. Ok, thank you, I will answer you.

**Comment by Jmmx1237** [comment]
import asyncio
import json
import os
import secrets
import signal
import websockets
from websockets import connect

import sys
import shutil
import logging
import time
import sqlite3
from sqlite3 import Error
import functools
from functools import partial
from pymodbus.client.sync import ModbusTcpClient as ModbusClient

logger = logging.getLogger(__name__)

# Modbus Config
UNIT = 0x1
# Adresses to Hardware
HOST = '192.168.0.24'
#HOST = '192.168.0.50'
# Portnumber
PORT = 5020
#PORT = 502
# Coil Output Base Address
COILBASE = 512

# Websocket Portnummer listen
PORTNUM = 8001


class Websocket():

    def __init__(self, client, handler): #, server, sock, address
        try:
            super(Websocket, self).__init__()

            self.modbus = client
            self.functions = {
                "relais1": partial(self.simple_switch, COILBASE + 16),
                "relais2": partial(self.simple_switch, COILBASE + 1),
                "relais3": partial(self.simple_switch, COILBASE + 2),
                "set_temp1": partial(self.set_temperature1, 524),
            }
        except Exception as exception:
            logger.exception("constructor")
            raise

    def __await__(self, client):
        # see: http://stackoverflow.com/a/33420721/1113207
        return self._async_init().__await__()

    async def _async_init(self, client):
        self._conn = connect("wss://echo.websocket.org")
        self.websocket = await self._conn.__aenter__()
        return self


    def simple_switch(self, address, value):
        """ value can be one of "on", "off" or "get" """
        [...]
        return "on" if rp.bits[0] else "off"


    async def set_temperature1(self, address, value):
        # Loop for temperature controll
        if (self.database_reading()[0][1]) == 524 and (self.database_reading()[1][1]) == 'on':
            while True:
                 if (self.database_reading()[0][1]) == 524 and (self.database_reading()[1][1]) == 'off':
                    break
                await asyncio.sleep(1)

    def database_reading(self):
        [...]

    # should this handle message???
    async def receive(self):
        try:
            message = await self.websocket.recv()

            commands = json.loads(message)
            new_state = {}

            print("Echoing '%s'" % commands)

            for key, value in commands.items():
                function = self.functions[key]
                print("function '%s'" % function)
                new_state[key] = function(value)
                print("new_state '%s'" % new_state)
                print("key '%s'" % key)
                print("value '%s'" % value)
            print(json.dumps(new_state))
            #self.sendMessage(json.dumps(new_state))
            await self.websocket.send(json.dumps(new_state))

            print("Echoing '%s'" % commands)

        except Exception as exception:
            logger.exception("handle message")
            raise

    # ???
    async def sendMessage(self, message):
        await self.websocket.send(message)

    async def close(self):
        await self._conn.__aexit__(*sys.exc_info())
    # ???
    async def handler(self, websocket):
        while True:
            message = await websocket.recv()
            print(message)


async def main():
    logging.basicConfig()

    with ModbusClient(host=HOST, port=PORT) as client:
        client.connect()
        time.sleep(0.025)

        print("Websocket server on port %s" % PORTNUM)

        # How do I pass arguments to the connection handler? {https://websockets.readthedocs.io/en/stable/faq/server.html}
#       create_protocol = functools.partial(Websocket(), client)
        # How can this be done correctly?
        async with websockets.serve('', '192.168.0.24', PORTNUM, partial(Websocket(), client)):
            await asyncio.Future()  # run forever


if __name__ == '__main__':
#    main()
    asyncio.run(main())

**Comment by aaugustin** [comment]
`async with websockets.serve("192.168.0.24", PORTNUM, functools.partial(Websocket(), client)):` <-- here you are putting the connection handler as the third argument, while it's the first argument (before host and port).

In addition, your `Websocket` class doesn't implement `__call__`, so an instance of this class like `Websocket()` cannot be the first argument of `functools .partial`.

**Comment by aaugustin** [comment]
I would recommend you start from a very basic websocket server that does nothing besides accepting connections, then gradually add the other bits you need while making sure it keeps working at every step.

Indeed, in addition to the two obvious things I mentioned, I can see several other points that may be wrong. It's going to

**Comment by aaugustin** [comment]
If I were you, since there's one global instance of the modbus client, I'd just put it in a global variable and access that variable from my connection handler. Done.

Also I strongly recommend you remove all the astroturfed crap you copy-pasted from StackOverflow like `return self._async_init().__await__()` and `await self._conn.__aexit__(*sys.exc_info())` — given the question you're asking, I'm positive that you DO NOT need that shit and it IS NOT helping.

**Comment by aaugustin** [comment]
```python

async def handler(connection):
    global CLIENT
    websocket = Websocket(CLIENT, connection)  # shouldn't be too far from the intent of your class
    # do stuff here

async def main():
    logging.basicConfig()

    global CLIENT
    with ModbusClient(host=HOST, port=PORT) as CLIENT:
        client.connect()
        time.sleep(0.025)

        print("Websocket server on port %s" % PORTNUM)

        async with websockets.serve(handler, '192.168.0.24', PORTNUM):
            await asyncio.Future()  # run forever
```

**Comment by Jmmx1237** [comment]
> I would recommend you start from a very basic websocket server that does nothing besides accepting connections, then gradually add the other bits you need while making sure it keeps working at every step.

Agreed, I will try that.

**Comment by aaugustin** [comment]
You can call `connection.send(...)` and `connection.recv()` as needed in the `handler` coroutine.
