### ISSUE TITLE
官方文档，看不懂，能不能写的细一点，建议优化

### ISSUE THREAD

**Issue by jintianyehengjiandan** [aaugustin/websockets#1253]
**I am a new programmer who has just worked for 6 months. This document you have written has very little useful information. I suggest you optimize it, which I mean is not friendly to new programmers like me**

**I refer to the following document**
https://websockets.readthedocs.io/en/stable/reference/client.html

现在重连，关闭，超时，我想一起兼容，找不到方法

#!/usr/bin/envpython
# -*-coding:UTF-8-*-
"""
@Project：
@File：
@Author：
@Date：2022/7/13 10:02
"""
import asyncio
import collections
import json
import inspect
import ctypes
import os
import sys
import func_timeout
import threading
import numpy as np
import websockets
class WebSocketClient(threading.Thread):
    def __init__(self, serverHost="localhost", serverPort=8000):
        """
        :param serverHost: 待连接的远程主机的域名
        :param serverPort: 待连接的远程主机的端口
        """
        super(WebSocketClient, self).__init__()
        self.__serverHost = serverHost
        self.__serverPort = serverPort

        self._isFinish = False

        self._listener = lambda *d: None  # 接受消息回调
        self._reconnectionListener = lambda *d: None  # 重连的回调（重连做什么事）

        self._successConnectionListener = lambda *d: None  # 连接成功回调
        self._timeoutListener = lambda *d: None  # 超时回调
        self._breakConnectionListener = lambda *d: None  # 连接断开回调,这个必须连接成功再断开才能调用
        self._connectListener = lambda *d: None  # 组合形式的连接成功，连接失败回调

        self._queue = collections.deque(maxlen=10000)  # 开启队列

        self._firstData = None
        self.ws = None

        self.isConnect = False

        self.reconnection = False

    def firstSend(self, data):
        self._firstData = data

    async def _clientRecv(self, websocket):
        while not self._isFinish:
            try:
                data = await websocket.recv()
                self._listener(json.loads(data))
            except websockets.ConnectionClosed:
                self._breakConnectionListener()
                self._connectListener(False)
                self.isConnect = False
                print("ConnectionClosed...")  # 链接断开
                break
            except websockets.InvalidState:
                print("InvalidState...")  # 无效状态
                break
            except Exception as e:
                print(e)
                break

    async def _clientSend(self, websocket):
        while not self._isFinish:
            try:
                if len(self._queue) > 0:
                    data = self._queue.popleft()
                    await websocket.send(data)
                else:
                    await asyncio.sleep(0.1)
            except websockets.ConnectionClosed:
                self._breakConnectionListener()
                self._connectListener(False)
                self.isConnect = False
                print("ConnectionClosed...")  # 链接断开
                break
            except websockets.InvalidState:
                print("InvalidState...")  # 无效状态
                break
            except Exception as e:
                print(e)
                break

    async def _clientRun(self):
        ipaddress = "ws://" + self.__serverHost + ":" + str(self.__serverPort)
        async for websocket in websockets.connect(ipaddress,
                                                  open_timeout=20, ping_interval=20, ping_timeout=20, close_timeout=10,
                                                  max_size=2 ** 50,
                                                  read_limit=2 ** 50,
                                                  write_limit=2 ** 50,
                                                  ):
            self.isReconnection = True
            print(ipaddress, "链接成功")
            self._successConnectionListener()
            self._connectListener(True)
            self.isConnect = True
            try:
                if self._firstData:
                    await websocket.send(json.dumps(self._firstData))
                if self.reconnection:
                    await self._reconnectionListener(websocket)
                task1 = asyncio.create_task(self._clientRecv(websocket))
                asyncio.create_task(self._clientSend(websocket))

                await task1
                self.reconnection = True
            except websockets.ConnectionClosed:
                continue

    def run(self):
        try:
            asyncio.run(self._clientRun())
        # TODO 捕获下面俩中错误很奇怪，只能捕获其中一种，注释掉另一种查看现象
        except asyncio.exceptions.TimeoutError:  # 这个报错和参数open_timeout=10连用的
            # print(666666)
            self._timeoutListener()  # 第一次连接超时
            # self.run()
        # except ConnectionRefusedError:
        #     print(77777777777)
        #     self.run()
        # self._isFinish = True

    def setListener(self, listener):
        self._listener = listener

    def setReconnectionListener(self, listener):
        self._reconnectionListener = listener

    def setSuccessConnectionListener(self, listener):
        self._successConnectionListener = listener

    def setTimeoutListener(self, listener):
        self._timeoutListener = listener

    def setBreakConnectionListener(self, listener):
        self._breakConnectionListener = listener

    def setConnectionListener(self, listener):
        self._connectListener = listener

    def returnConnectResult(self):  # 这种返回连接状态，会有延迟
        return self.isConnect

    def sendData(self, data):
        if not self._isFinish:
            self._queue.append(self.jsonDumps(data))
        else:
            raise Exception("链接以断开")

    def close(self):
        self._listener = lambda *d: None
        self._isFinish = True
        self.isConnect = False

    @staticmethod
    def jsonDumps(json_str):
        def encode_complex(obj):
            if isinstance(obj, np.int32):
                return int(obj)
            if isinstance(obj, np.float32):
                return float(obj)
            raise TypeError(f'Object of type {obj.__class__.__name__} 'f'is not JSON serializable')

        return json.dumps(json_str, default=encode_complex)

**Comment by aaugustin** [comment]
I recommend you read with the tutorial, which is the document intended for people like you, rather than the API reference.

**Comment by jintianyehengjiandan** [comment]
> I solved my problem, and sure enough, I'm too good. Thank you

**Comment by jintianyehengjiandan** [comment]
#!/usr/bin/envpython
# -*-coding:UTF-8-*-
"""
@Project：ffmpeg-python-demo
@File：WebSocketClient.py
@Author：姜恩柱
@Date：2022/7/13 10:02
"""
import asyncio
import collections
import json
import inspect
import ctypes
import os
import sys
import func_timeout
import threading
import numpy as np
import websockets


class WebSocketClient(threading.Thread):
    def __init__(self, serverHost="localhost", serverPort=8000):
        """
        :param serverHost: 待连接的远程主机的域名
        :param serverPort: 待连接的远程主机的端口
        """
        super(WebSocketClient, self).__init__()
        self.__serverHost = serverHost
        self.__serverPort = serverPort

        self._isFinish = False

        self._listener = lambda *d: None  # 接受消息回调
        self._reconnectionListener = lambda *d: None  # 重连的回调（重连做什么事）

        self._successConnectionListener = lambda *d: None  # 连接成功回调
        self._timeoutListener = lambda *d: None  # 超时回调
        self._breakConnectionListener = lambda *d: None  # 连接断开回调,这个必须连接成功再断开才能调用
        self._connectListener = lambda *d: None  # 组合形式的连接成功，连接失败回调

        self._queue = collections.deque(maxlen=10000)  # 开启队列

        self._firstData = None
        self.ws = None

        self.isConnect = False

        self.reconnection = False

        self.count = 0

    def firstSend(self, data):
        self._firstData = data

    async def _clientRecv(self, websocket):
        while not self._isFinish:
            try:
                data = await websocket.recv()
                self._listener(json.loads(data))
            except websockets.ConnectionClosed:
                self._breakConnectionListener()
                self._connectListener(False)
                self.isConnect = False
                print("ConnectionClosed...")  # 链接断开
                break
            except websockets.InvalidState:
                print("InvalidState...")  # 无效状态
                break
            except Exception as e:
                print(e)
                break

    async def _clientSend(self, websocket):
        while not self._isFinish:
            try:
                if len(self._queue) > 0:
                    data = self._queue.popleft()
                    await websocket.send(data)
                else:
                    await asyncio.sleep(0.1)
            except websockets.ConnectionClosed:
                self._breakConnectionListener()
                self._connectListener(False)
                self.isConnect = False
                print("ConnectionClosed...")  # 链接断开
                break
            except websockets.InvalidState:
                print("InvalidState...")  # 无效状态
                break
            except Exception as e:
                print(e)
                break

    async def _clientRun(self):
        ipaddress = "ws://" + self.__serverHost + ":" + str(self.__serverPort)
        while not self._isFinish:
            try:
                async with websockets.connect(ipaddress,
                                              open_timeout=10,
                                              max_size=2 ** 50,
                                              read_limit=2 ** 50,
                                              write_limit=2 ** 50,
                                              ) as websocket:
                    self.isReconnection = True
                    print(ipaddress, "链接成功")
                    self.count = 0
                    self._successConnectionListener()
                    self._connectListener(True)
                    self.isConnect = True
                    try:
                        if self._firstData:
                            await websocket.send(json.dumps(self._firstData))
                        if self.reconnection:
                            await self._reconnectionListener(websocket)
                        task1 = asyncio.create_task(self._clientRecv(websocket))
                        asyncio.create_task(self._clientSend(websocket))

                        await task1
                        if self._isFinish:
                            break
                        self.reconnection = True
                    except websockets.ConnectionClosed:
                        continue
            except ConnectionRefusedError as e:
                print(e)
                # print(self.count)
                if self.count == 3:
                    self._timeoutListener()
                    return
                self.count += 1
                await asyncio.sleep(2)

    def run(self):
        asyncio.run(self._clientRun())
        # try:
        #     asyncio.run(self._clientRun())
        # # TODO 捕获下面俩中错误很奇怪，只能捕获其中一种，注释掉另一种查看现象
        # except asyncio.exceptions.TimeoutError:  # 这个报错和参数open_timeout=10连用的
        #     # print(666666)
        #     self._timeoutListener()  # 第一次连接超时
        #     # self.run()
        # except ConnectionRefusedError:
        #     print(77777777777)
        #     self.run()
        # self._isFinish = True

    def setListener(self, listener):
        self._listener = listener

    def setReconnectionListener(self, listener):
        self._reconnectionListener = listener

    def setSuccessConnectionListener(self, listener):
        self._successConnectionListener = listener

    def setTimeoutListener(self, listener):
        self._timeoutListener = listener

    def setBreakConnectionListener(self, listener):
        self._breakConnectionListener = listener

    def setConnectionListener(self, listener):
        self._connectListener = listener

    def returnConnectResult(self):  # 这种返回连接状态，会有延迟
        return self.isConnect

    def sendData(self, data):
        if not self._isFinish:
            self._queue.append(self.jsonDumps(data))
        else:
            raise Exception("链接以断开")

    def close(self):
        self._listener = lambda *d: None
        self._isFinish = True
        self.isConnect = False

    @staticmethod
    def jsonDumps(json_str):
        def encode_complex(obj):
            if isinstance(obj, np.int32):
                return int(obj)
            if isinstance(obj, np.float32):
                return float(obj)
            raise TypeError(f'Object of type {obj.__class__.__name__} 'f'is not JSON serializable')

        return json.dumps(json_str, default=encode_complex)
