### ISSUE TITLE
Asynchronous processing of incoming requests

### ISSUE THREAD

**Issue by maka1500** [aaugustin/websockets#1257]
It seems that requests are not processed asynchronously.

Is it possible to process this asynchronously please?

I have this function:

```
async def main():
    async with websockets.serve(handler, "", 8001):
        await asyncio.Future()  # run forever
```

In this case function handler is not called asynchronously.
This means if I have 10 concurrent requests, they are all added to the queue, and they cannot be processed asynchronously.

If I add this as handler:

`
async def handler(websocket):
    time.sleep(4)
`

And If I have 10 concurrent requests, it will take them 40 seconds to finish, instead of 4 seconds.

Is this possible to change please?

Thank you very much.

**Comment by maka1500** [comment]
What is someone is making some online game? And if 100 players are connected? Then each player request is processed one by one, instead asynchronously - which is non-sense. Am I wrong please? Could something be changed?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/faq/asyncio.html#why-does-my-simple-program-misbehave-mysteriously

**Comment by maka1500** [comment]
Thanks, it works now!
