### ISSUE TITLE
on_close() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by EliotAmn** [aaugustin/websockets#1258]
Hi ! Thanks for this very helpful library!

I use websockets inside python classes. And when I want to use the "on_close" method, I have this error :
`on_close() takes 2 positional arguments but 4 were given`

This is my code :

```py
def on_close(self, ws):
    print("Closed")
```
```py
self.node_ws = websocket.WebSocketApp(self.node_ws_url,
    on_message=self.on_message,
    on_close=self.on_close,
    on_error=self.on_error,
    on_open=self.on_open)
self.node_ws.run_forever()
```

Maybe the problem went from the `self` argument?
Thanks for your reply!

Eliot

**Comment by aaugustin** [comment]
You are referring to another library. You filed this issue against the wrong repository.
