### ISSUE TITLE
 It takes a few seconds for the stop signal to be sent to the run stop

### ISSUE THREAD

**Issue by AndrewGPU** [aaugustin/websockets#1259]
The stop time seems to be consistent with the connect timeout，However I don't know why it took so long to stop。
                loop = config.asyncio.get_running_loop()
                loop.add_signal_handler(
                    signal.SIGTERM, loop.create_task, websocket.close())

I just want a quick reboot

**Comment by aaugustin** [comment]
Unfortunately there isn't enough context in your question to help you. If I just copy paste what you wrote, I get an instant reboot.

**Comment by AndrewGPU** [comment]
import asyncio
import traceback


async def test():
    import websockets
    from json import dumps
    import signal
    uri = "wss://fstream.binance.com/stream"
    while True:
        try:
            print(f"ws重启完成")
            async with websockets.connect(uri, timeout=3, ping_interval=20, ping_timeout=5 * 60) as websocket:
                asyncio.create_task(websocket.send(
                    dumps({
                        "method": "SUBSCRIBE",
                        "params": ["!bookTicker"],
                        "id": 12}
                    )))

                loop = asyncio.get_running_loop()
                loop.add_signal_handler(
                    signal.SIGTERM, loop.create_task, websocket.close())

                async for message in websocket:
                    print(message)
        except:
            msg = f"{traceback.format_exc()}"
            print(msg)

**Comment by AndrewGPU** [comment]
import asyncio
import traceback


async def test():
    import websockets
    from json import dumps
    import signal
    uri = "wss://fstream.binance.com/stream"
    while True:
        try:
            print(f"ws重启完成")
            async with websockets.connect(uri, timeout=3, ping_interval=20, ping_timeout=5 * 60) as websocket:
                asyncio.create_task(websocket.send(
                    dumps({
                        "method": "SUBSCRIBE",
                        "params": ["!bookTicker"],
                        "id": 12}
                    )))

                loop = asyncio.get_running_loop()
                loop.add_signal_handler(
                    signal.SIGTERM, loop.create_task, websocket.close())

                async for message in websocket:
                    print(message)
        except:
            msg = f"{traceback.format_exc()}"
            print(msg)

**Comment by AndrewGPU** [comment]
```python
import asyncio
import traceback


async def test():
    import websockets
    from json import dumps
    import signal
    uri = "wss://fstream.binance.com/stream"
    while True:
        try:
            print(f"ws重启完成")
            async with websockets.connect(uri, timeout=3, ping_interval=20, ping_timeout=5 * 60) as websocket:
                asyncio.create_task(websocket.send(
                    dumps({
                        "method": "SUBSCRIBE",
                        "params": ["!bookTicker"],
                        "id": 12}
                    )))

                loop = asyncio.get_running_loop()
                loop.add_signal_handler(
                    signal.SIGTERM, loop.create_task, websocket.close())

                async for message in websocket:
                    print(message)
        except:
            msg = f"{traceback.format_exc()}"
            print(msg)
```

**Comment by AndrewGPU** [comment]
The above code cannot be restarted immediately, it needs to wait for 3 seconds

**Comment by AndrewGPU** [comment]
@aaugustin

**Comment by aaugustin** [comment]
https://github.com/aaugustin/websockets/commit/9e960b508988c4049eb9f3377c505f506a3af060 might help.

If you need more, unfortunately, https://websockets.readthedocs.io/en/stable/project/contributing.html#cryptocurrency-users
