### ISSUE TITLE
harsh warnings on reset connections during handshake

### ISSUE THREAD

**Issue by RemiCardona** [aaugustin/websockets#126]
At work, our websocket daemon is behind an HAproxy. Said reverse proxy is configured to probe our daemon to see if it's alive. Since 181acf3e29499ecff61b5e6892d73bae5332292e, this health check generates a _lot_ of logs which look like the following:

``` python-traceback
WARNING 2016-09-02 09:42:19,976 websockets.server Error in opening handshake
Traceback (most recent call last):
  File "/home/rcardona/Projects/websockets/websockets/server.py", line 64, in handler
    extra_headers=self.extra_headers)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 98, in throw
    return self.gen.throw(exc)
  File "/home/rcardona/Projects/websockets/websockets/server.py", line 143, in handshake
    path, headers = yield from read_request(self.reader)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 98, in throw
    return self.gen.throw(exc)
  File "/home/rcardona/Projects/websockets/websockets/http.py", line 43, in read_request
    request_line, headers = yield from read_message(stream)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 98, in throw
    return self.gen.throw(exc)
  File "/home/rcardona/Projects/websockets/websockets/http.py", line 83, in read_message
    start_line = yield from read_line(stream)
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 98, in throw
    return self.gen.throw(exc)
  File "/home/rcardona/Projects/websockets/websockets/http.py", line 103, in read_line
    line = yield from stream.readline()
  File "/usr/lib/python3.4/asyncio/coroutines.py", line 98, in throw
    return self.gen.throw(exc)
  File "/usr/lib/python3.4/asyncio/streams.py", line 418, in readline
    yield from self._waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 582, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```

This is due to how HAproxy implements its healthcheck (and I'm told it's quite a standard practice): it opens a connection and resets it immediately (instead of properly closing it, as one would expect). This is to prevent leaving sockets in the `FIN_WAIT2` or (most likely) `TIME_WAIT` states on proxy side.

To reproduce the issue, `nmap -p <port> <hostname>` from a _different_ host does the trick (if done locally, the connection is closed and no exception is raised).

As far as I'm concerned, just ignoring this kind of exception at this point in time (the handshake) does the trick for me. In any case, a connection reset is not an actual failure that `websockets` could have prevented in any meaningful way. It's just one of the many things that may happen when dealing with sockets.

My proposed solution is to simply log `ConnectionError` exceptions (which include `ConnectionResetError`) as `INFO` without a traceback.

**Comment by aaugustin** [comment]
Yes, websockets shouldn't be too noisy on ConnectionErrors, as these happen all the time.

However, it must log something to help beginners figure out what happens.

Is this particular change: https://github.com/aaugustin/websockets/commit/181acf3e29499ecff61b5e6892d73bae5332292e#diff-cb2dd6531e50e6a2341236c06817f021R80 the source of the problem?

**Comment by RemiCardona** [comment]
This one hasn't come up yet. But that one is the main culprit: https://github.com/aaugustin/websockets/commit/181acf3e29499ecff61b5e6892d73bae5332292e#diff-a548b853d665035e6e62944845d0a575R74

**Comment by aaugustin** [comment]
Yes, the change I pointed to means the code no longer goes through this branch: https://github.com/aaugustin/websockets/commit/181acf3e29499ecff61b5e6892d73bae5332292e?diff=unified#diff-a548b853d665035e6e62944845d0a575R71 and hits the more verbose error reporting path.

**Comment by RemiCardona** [comment]
So, thanks to Sentry, I've been sifting through all the tracebacks collected on production machines and it appears connection resets can and **do** happen anytime. Anyone well versed in TCP will likely label me as Captain Obvious.

So far, the most common connection resets happen in:
* the opening handshake (due to our load balancers)
* the closing handshake (there are a number of reasons there, one of which is because AIUI the `websockets` module doesn't fully implement the shutdown order from paragraph 7.1.1. from the spec. I could be wrong about that though.)
* any time/anywhere inside `ws_handler` because we're mostly working with crappy 3G/4G connections and that mobile networking is hell.

Now, I could (and locally did) patch the opening and closing handshake to be silent about reset connections and I've thoroughly wrapped all the code that calls `websockets` methods with `try/except (ClosedConnection, ConnectionResetError)`. Because all methods can raise both types of exceptions.

But, and I'll admit it's a gut feeling, it feels awkward to do that. I really wish `websockets` would handle the `ConnectionResetError` exceptions for me and only raise its own exception classes.

Would you be open to patches about that? It probably would require some API breakage.

Cheers

**Comment by RemiCardona** [comment]
Slightly updated patch to also reduce the severity of connection errors on the closing handshake. As far as I'm concerned, this should hide most, if not all, the connection problems from our logs.

So while this should be a nice improvement, it does not address the elephant in the room that *all* calls to `websockets` coroutines *must* be guarded with `try/except (ClosedConnection, ConnectionResetError)`. I have done so in my server code but I really feel `websockets` should be doing this for me.

But that's stuff for another time.

**Comment by aaugustin** [comment]
@RemiCardona I'm unlikely to find time to give this library some love in the next months. Would you like commit access?

**Comment by RemiCardona** [comment]
I definitely don't mind lending a hand. Hopefully I can work on this Soon™.

**Comment by aaugustin** [comment]
OK - you have commit access. I can give you permission to make releases later if you need it.

If you don't want to start with harder issues for which there's no obvious backwards-compatible solution, working on some of the easier issues (including doc issues) would be a good way to become more familiar with the stakes of maintaining this lib.
