### ISSUE TITLE
Error in sample code for "How do I stop a client that is processing messages in a loop?"

### ISSUE THREAD

**Issue by beirne-arcsight** [aaugustin/websockets#1261]
I need to have a signal handler in my loop so I used the code from the FAQ entry [How do I stop a client that is processing messages in a loop?](https://websockets.readthedocs.io/en/stable/faq/client.html#how-do-i-stop-a-client-that-is-processing-messages-in-a-loop). I kept getting an error, though, saying "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/unix_events.py:140: RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited".

I did some debugging and realized that the problem is in this line:

> loop.add_signal_handler(
>             signal.SIGTERM, loop.create_task, websocket.close())

It is giving the signal handler the return value of websocket.close() rather than a reference to the websocket.close method itself. After I changed it to:

loop.add_signal_handler(
            signal.SIGTERM, loop.create_task, websocket.close)

the error went away.

**Comment by aaugustin** [comment]
Good catch. Thank you.

**Comment by aaugustin** [comment]
Actually, the original example was correct. I tested it again today and it works. I'm not sure what's happening to you.

I reverted this change to fix #1266.
