### ISSUE TITLE
Cannot catch InvalidStatusCode

### ISSUE THREAD

**Issue by via986** [aaugustin/websockets#1262]
Hello. I'm a novice in this library. I have this simple code:
```
uri = 'wss://ftx.com/ws/'
    try:
        async for websocket in websockets.connect(uri):
            async for message in websocket:
                message = await websocket.recv()
    except websockets.exceptions.InvalidStatusCode as err:
        print(f'{err=}')
```
that raises error:
`websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 503`
`try - except` doesn't catch this error. And I don't know why ( How to catch it?

Even `except Exception as err:` doesn't catch it...

websockets==10.3
Python 3.10.7

Thanks!

**Comment by aaugustin** [comment]
Hello, unfortunately I won't be able to help: https://websockets.readthedocs.io/en/stable/project/contributing.html#cryptocurrency-users
