### ISSUE TITLE
Multiple clients connecting to a single ws server are responses getting entangled 

### ISSUE THREAD

**Issue by alamathe1** [aaugustin/websockets#1264]
**Client Side:**

```
import websockets

async def connect(self) -> None:
    uri: str = _get_uri(async_client=True) # uri = "ws://127.0.0.1:5500"
    self._websocket = await websockets.connect(
        uri, max_size=max_size, ping_timeout=300, compression=None
    )

async def send_message(self, data: bytes) -> None:
    await self._websocket.send(data)

async def _connect_send_receive_until_complete(
        self, data: bytes
    ) -> None:
        await self.connect()
        await self.send_message(data)
        try:
            while True:
                await self.receive_message(callback)
        except websockets.exceptions.ConnectionClosed:
            _logger.info(f"Async ws handler closed")
            break
```

**Server side:**

```
async def init_server(self) -> websockets.WebSocketServer:
    return await websockets.serve(
        self._serve, // Serve handler
        self._host,
        self._port_server1,
        max_size=None,  # type: ignore[arg-type]
        ping_timeout=None,  # type: ignore[arg-type]
        compression=None,
    )

async def _serve(self, socket: websockets.WebSocketServerProtocol, path: str) -> None:
    while True:
        self._websocket = socket
        msg= await self._websocket.recv()
        message = getMessage() // Function that sends messages continuously in a interval
        await websocket.send(message)
```

This is more of a question that a bug. We have two clients from the same machine connecting to the websocket server. The scenario:
1. Client A makes a connection and send a message and continuously keeps connection open to receive a response.
2. Client A gets the response.
3. Client B makes a connection and sends a message and continuously keeps connection open to receive a response.
4. Client B gets the response.
5. Client A stops getting any response.

My understanding is that since the same URI is used by both the client - ws://127.0.0.1:5500, websockets gets entangled when multiple clients connect. My question is how can we ensure that we sending responses to multiple clients in an isolated environment? (PS: For a single client connecting to a server, it works fine.)

Couldn't find much examples on this specific use-case. Any pointers will be helpful.

**Comment by aaugustin** [comment]
> My understanding is that since the same URI is used by both the client - ws://127.0.0.1:5500, websockets gets entangled when multiple clients connect.

That's incorrect. Connections are independent from one another.

What you're trying to achieve is covered at this point in the tutorial: https://websockets.readthedocs.io/en/stable/intro/tutorial2.html#broadcast
