### ISSUE TITLE
Exceptions from asyncio's create_connection() are not wrapped into ConnectionClosedError

### ISSUE THREAD

**Issue by avdgrinten** [aaugustin/websockets#1265]
If `create_connection()` fails in `legacy/client.py`, a raw `ConnectionResetError` (= a built-in Python exception) is raised:
```
  async with websockets.connect(ws_url) as ws:
File "/opt/foobar/lib/python3.9/site-packages/websockets/legacy/client.py", line 604, in __aenter__
  return await self
File "/opt/foobar/lib/python3.9/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
  transport, protocol = await self._create_connection()
File "/usr/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
  transport, protocol = await self._create_connection_transport(
File "/usr/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
  await waiter
File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
  data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Is this behavior expected? I would have expected `websockets` to wrap that exception into its own `websockets.ConnectionClosedError` (which I am already catching). The need to catch both exceptions (`ConnectionResetError` and `websockets.ConnectionClosedError`) seems rather pointless, as they will basically both result in the same response in downstream code.

**Comment by avdgrinten** [comment]
If it's not desirable to change the behavior, it would be nice to document the exceptions that the user actually has to handle when establishing a connection. Right now, the documentation mentions `InvalidURI`, `InvalidHandshake` and `TimeoutError`, but none of the built-in Python exceptions.

**Comment by avdgrinten** [comment]
Well, the difference is that the connectivity-related exceptions *must* be handled by any robust production-grade application (e.g., by reconnecting or by telling the user to check their internet connectivity), while there is not a lot that you can do about `KeyboardInterrupt` or `MemoryError`.

**Comment by aaugustin** [comment]
Yes, we have clear cut cases of exceptions we care about and exception we don't care about.

But what about everything in the middle? I don't even know how to make a full list of all exceptions that could occur, across all support platforms.

**Comment by aaugustin** [comment]
asyncio [doesn't document](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection) the exceptions that `create_connection` may raise; actually it doesn't say anything about exceptions:

This makes it impossible to provide guarantees about the kind of exceptions that `connect`, a wrapper around `create_connection`, may raise.

If you care about connectivity errors, catch `OSError` (which supersedes `IOError` these days). It will solve your original issue:

```
>>> ConnectionResetError.mro()
[<class 'ConnectionResetError'>, <class 'ConnectionError'>, <class 'OSError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>]
```
