### ISSUE TITLE
Caught signal produces coroutine was expected error

### ISSUE THREAD

**Issue by beirne-arcsight** [aaugustin/websockets#1266]
I have my first websockets program working except for one thing, signal handling. I can't get the signal catcher to work.
Here's my code. Terminating_signals has signal.SIGTERM and signal.SIGINT.
```
async with websockets.connect(url, extra_headers=extra_headers) as websocket:
    loop = asyncio.get_running_loop()
    for signal_type in terminating_signals:
        loop.add_signal_handler(signal_type, functools.partial(loop.create_task, websocket.close))
    async for message in websocket:
        self.parse_events(message)
```

This works for setting the handler, but when I send the script a signal I get:

```
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got <bound method WebSocketCommonProtocol.close of <websockets.legacy.client.WebSocketClientProtocol object at 0x7f2ef7be00d0>>
```

I did also try not using functools.partial like in the faq and got the same result.

How do I get the close method to work as a coroutine?

**Comment by aaugustin** [comment]
Yeah. Actually, I was thinking about that yesterday night and forgot to file an issue. Thank you for reminding me.

We need a `loop.call_soon` there.

**Comment by beirne-arcsight** [comment]
Any tips on where to place the loop.call_soon?

**Comment by aaugustin** [comment]
This issue came shortly after #1261, where I got confused, but that's cleared now. Please ignore my previous comment.

You can change your example to `loop.add_signal_handler(signal_type, functools.partial(loop.create_task, websocket.close()))`.

You don't need `partial` You can use `loop.add_signal_handler(signal_type, loop.create_task, websocket.close())` to achieve the same effect.

**Comment by beirne-arcsight** [comment]
FYI, I got it to work like you said with one signal. If I set up two handlers I get a RuntimeError with a stack trace, but the script exits OK.

**Comment by aaugustin** [comment]
Good to hear that you're sorted. I'm not quite sure how Python behaves in the presence of multiple signal handlers; judging by your experience, "poorly". At this point, we're no longer in "websockets" territory, more in "Python" territory, so StackOverflow may be a better option if you need further help.
