### ISSUE TITLE
Websockets server CAN NOT handle muti client connection

### ISSUE THREAD

**Issue by Haskely** [aaugustin/websockets#1268]
I've read this [FAQ](https://websockets.readthedocs.io/en/stable/faq/server.html#why-can-only-one-client-connect-at-a-time), but I don't think the phenomenon I am about to describe is reasonable.

The requirement is very simple: 

1. set up a server, and when the client connects, it will send messages continuously; 
2. support multiple clients to connect at the same time.

I wrote following code:

## ws_server.py

```python
import websockets
from websockets.exceptions import ConnectionClosed
import asyncio


def run_websocket_server(host="0.0.0.0", port=8000):
    async def handle_session(socket):
        while True:
            await socket.send(f"Hello")

    print(f"Server Running！\n\t Please connect http://{host}:{port}")

    loop = asyncio.get_event_loop()
    loop.run_until_complete(
        websockets.serve(
            ws_handler=handle_session,
            host=host,
            port=port,
        )
    )
    loop.run_forever()


if __name__ == "__main__":
    run_websocket_server()

```

## ws_client.py

```python
import asyncio
import websockets
import time


def run_local_ws_client(host="0.0.0.0", port=8000):
    async def ws_client(uri):
        async with websockets.connect(uri) as websocket:
            recv_cnt = 0
            start_time = time.time()
            while True:
                recv_text = await websocket.recv()
                recv_cnt += 1
                total_time = time.time() - start_time
                if total_time > 1.0:
                    print(f"Average recv fps: { recv_cnt / total_time} fps", end="\r")
                    start_time = time.time()
                    recv_cnt = 0

    asyncio.get_event_loop().run_until_complete(ws_client(f"ws://{host}:{port}"))


if __name__ == "__main__":
    run_local_ws_client()

```

And while running one ws_server.py with mutiple ws_client.py, only first one can successfully receive messages.

![图片](https://user-images.githubusercontent.com/13416700/204141439-2a373f79-77a3-4da4-aa28-f27dfe35f874.png)

May be related to: #578 

**BUT， simpily add `await asyncio.sleep(0.0)` after the `await socket.send(f"Hello")`, it worked properly!** 

Why should I must add `await asyncio.sleep(0.0)` make it behave as expected? `await socket.send(f"Hello")` should be enough to allow asyncio switch different tasks, isn't it? cc @aaugustin

**Comment by aaugustin** [comment]
Yes, you landed on the correct FAQ, but it doesn't cover your situation very well. I'm improving it.

In asyncio, awaiting a coroutine can yield control but isn't guaranteed to yield control.

You will find an extended discussion in the context of websockets in #867.

**Comment by aaugustin** [comment]
PS. I have yet to find a use case other than benchmarking for sending a firehose of messages in a loop like that. I don't plan to make changes specifically to optimize for benchmarking.

**Comment by Haskely** [comment]
Thanks, I'll study the right way to do it
