### ISSUE TITLE
Regarding websocket library selection

### ISSUE THREAD

**Issue by tushargoyal22** [aaugustin/websockets#1270]
Can we please publish a document or update in ReadMe about

How to make a choice between [websockets](https://github.com/aaugustin/websockets) and [websocket-client](https://github.com/websocket-client/websocket-client)

If we can get elaborated comments on the downsides and upsides of using one over the other, it will be very helpful.

**Comment by aaugustin** [comment]
If you need such a document to make your choice, most likely either library will work great for you :-)

**Comment by aaugustin** [comment]
Generally speaking, it's difficult to do that kind of comparison because the maintainers of one library know elaborate details of what they've done... but not what others have done... leading to benchmarks where everyone says that they're the best...

**Comment by tushargoyal22** [comment]
![image](https://user-images.githubusercontent.com/43175862/204726482-05f425ec-2fbb-4ae2-84bd-61d7eea65c6c.png)

Can we get an elaborate idea of this? As currently based on our use case we planned to have result_callbacks added by the users according to their requirements, something like [this](https://github.com/websocket-client/websocket-client#:~:text=def%20on_message(ws%2C%20message)%3A)

So our use case is for users to subscribe to a Kafka topic, for getting data snapshots and diffs. In case you are aware of some implementations on top of [websockets](https://github.com/aaugustin/websockets) for this use case, then do let me know

**Comment by aaugustin** [comment]
Your last comment was too terse for me to visualize the data architecture you have in mind. I understand that you want to write a WebSocket client; there must be a WebSocket server between this client and Kafka or the client must connect to Kafka separately?

Regarding corountines and callbacks:

- In a coroutine-based system (which websockets + asyncio gives you), it is trivial to call callbacks — just call them!
- In a callback-based system, you're stuck with callbacks (and possibly callback hell) forever.
