### ISSUE TITLE
Verify that "Setting a cookie on the domain of the WebSocket URI" documentation works

### ISSUE THREAD

**Issue by chrysn** [aaugustin/websockets#1271]
I've attempted to follow the "Setting a cookie on the domain of the WebSocket URI" section in the documentation, but it appears that browsers do not behave as indicated there.

My tests consists of:

* https://host1 serves a cookie JS based setter website (`document.cookie = "role=" + value + ";samesite=lax";`) and a WebSocket server.
* https://host2 tries to establish a connection to wss://host1/socket

To test, I browse the setter website explicitly, and then go to host2. As variations, I have also tried embedding host1 into host2 through an iframe.

In no setup (other than a single host serving both the site that opens the web socket and the cookie setter) I have observed the cookie being sent along with the WebSocket connection.

If the described setup actually works, it'd be great to see maybe a link to a reference project using it and thus demonstrating that browsers do work that way. Otherwise, please consider updating it to state that cookies are only sent when the web socket and the site opening it are on the same host (possibly on different subdomains if configured correctly).

**Comment by aaugustin** [comment]
The key message of the docs is "don't do this unless you really know what you are doing" :-)

There is an example in the repo which, I believe, works: https://github.com/aaugustin/websockets/tree/main/experiments/authentication

Run `python app.py` in this directory and see how it goes.

For the purposes of the Same Origin Policy, which is what you're struggling with, `localhost:8000` and `localhost:8003` are just as different as `host1` and `host2`.

**Comment by aaugustin** [comment]
I just tried running that code. It's working. I see the cookie in the network inspector.
