### ISSUE TITLE
The answer of "How can I pass arguments to a custom protocol subclass?" in docs can't work on Python 3.10

### ISSUE THREAD

**Issue by chinese-wzq** [aaugustin/websockets#1275]
https://websockets.readthedocs.io/en/stable/faq/common.html#how-can-i-pass-arguments-to-a-custom-protocol-subclass
The code did't work on Python 3.10 now.

Here is a example about the reson behind:
```
import functools
class a:
    def __init__(self,extra_argument,*args,**kwargs):
        print(extra_argument)
        print(args)
        print(kwargs)
A=functools.partial(a,extra_argument=1)
hello=A(2)
```
The output is:
```
Traceback (most recent call last):
  File "/home/***/test.py", line 8, in <module>
    hello=A(2)
TypeError: a.__init__() got multiple values for argument 'extra_argument'
```
Maybe this way is outdated?

**Comment by chinese-wzq** [comment]
It work this way:
```
import functools
class a:
    def __init__(self,*args,**kwargs):
        print(kwargs["extra_argument"])
        print(args)
        print(kwargs)
A=functools.partial(a,extra_argument=1)
hello=A(2)
```
Maybe new Python's grammar is different?

**Comment by aaugustin** [comment]
Thank your for the bug report. Indeed the documentation isn't correct.

I will use this pattern: [part 1](https://github.com/aaugustin/websockets/blob/38b08fb72fb3c7e8358b3bba7cbe467c2a355aa9/experiments/broadcast/server.py#L131) and [part 2](https://github.com/aaugustin/websockets/blob/38b08fb72fb3c7e8358b3bba7cbe467c2a355aa9/experiments/broadcast/server.py#L48).
