### ISSUE TITLE
Unable to add parameters in url when using websocket client (websockets.connect)

### ISSUE THREAD

**Issue by Lucasmm016** [aaugustin/websockets#1277]
Can't add parameters in a URL, even if I add them the server doesn't receive them:

Example:

```
async def listen():
    url = 'ws://example.com/?param1=12&param2=13&param3=14'
    headers = {'Cookie': 'token=12345678'}

    async with websockets.connect(url, extra_headers=headers) as ws:
        ...
```

How to get through it? I've already tried every way, and I assure you that the server really doesn't receive these parameters!
The server receives only the URL but without the parameters!

**Comment by aaugustin** [comment]
Please enable debug logs: https://websockets.readthedocs.io/en/stable/topics/logging.html

You will see that parameters are sent and that it's a problem with the server, not with websockets.

**Comment by Lucasmm016** [comment]
I just checked the logs, and I also created a socket server myself to keep track of incoming parameters, and it really is a websockets problem, the parameters are not arriving on the server as expected, I tried another library and the parameters arrive normally!

**Comment by aaugustin** [comment]
With this client:

```python
#!/usr/bin/env python

import asyncio
import websockets

async def hello():
    async with websockets.connect("ws://localhost:8765/?foo=bar") as websocket:
        pass

asyncio.run(hello())
```

and this server:

```python
#!/usr/bin/env python

import asyncio
import websockets

async def echo(websocket):
    print(websocket.path)

async def main():
    async with websockets.serve(echo, "localhost", 8765):
        await asyncio.Future()  # run forever

asyncio.run(main())
```

the server prints:

```
/?foo=bar
```

With the information you have provided, I cannot reproduce the issue.

If you can modify the example above in a way that reproduces your problem, I will investigate.
