### ISSUE TITLE
Opensource means no discrimination against fields or endeavors. The project is then not opensource. Please stop referring this project as opensource.

### ISSUE THREAD

**Issue by h8ku** [aaugustin/websockets#1278]

**Comment by aaugustin** [comment]
I guess you're referring to my statement regarding crypto. It applies to where I spend my lifetime. I never claimed my life was opensource.

It says explicitly that you can do anything you want with the code and license. The code and license don't discriminate against any use.

Congratulations, you demonstrated that you are too stupid to read 4 lines of text. Typical of issues filed by crypto fanboys. Now shut up.
