### ISSUE TITLE
Pylance unable to access/index members of websockets

### ISSUE THREAD

**Issue by 0xLem0nade** [aaugustin/websockets#1281]
VS Code is throwing a lint error with websockets.connect() function as shown below:

![Screenshot from 2023-01-01 16-23-41](https://user-images.githubusercontent.com/18480836/210171196-ff0a51a6-648d-4572-b77e-d277c8d278c9.png)

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/faq/misc.html#why-does-my-ide-fail-to-show-documentation-for-websockets-apis

**Comment by 0xLem0nade** [comment]
So that's why! Okay can we move the methods to their designated modules so that it throws a runtime error rather than a linting one? This way developers are forced to use the correct static imports.

**Comment by aaugustin** [comment]
See the discussion here: https://github.com/aaugustin/websockets/issues/1183#issuecomment-1272550703

**Comment by aaugustin** [comment]
439dafa6 should solve that..
