### ISSUE TITLE
WebRTC signaling server?!?

### ISSUE THREAD

**Issue by endertable** [aaugustin/websockets#1282]

**Comment by endertable** [comment]
Not issues but more of inquiries.  My situation is this:  I want to connect a video camera and browser via Webrtc.  I need a socket server that runs on port 443 (hardcoded in camera) and of course, I need a httpd server that runs on port 443.  No big deal, I can use 2 RPis, one for the websocket server and one for the httpd services.  My only real situation with this, is that I can't find the setting to prevent the browser, (MS Edge) from complaining about CORS.  The exact error it gives me is: 

`Access to XMLHttpRequest at 'https://mywebsocket.com/socket.io/?EIO=4&transport=polling&t=OMOYW2y' from origin 'https://myhttpdserver.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have tried the following on my websockets server.py and still get that error:

```
headers = {"Access-Control-Allow-Origin": "*"}
header=("Access-Control-Allow-Origin: *")

async def main():
    async with websockets.serve(hello, "0.0.0.0", 443, ssl=ssl_context, origins=None, extra_headers={"Access-Control-Allow-Origin": "https://myhttpdserver.com"}):
        await asyncio.Future()  # run forever
```

I know some other apps use a  "sio = socketio.AsyncServer(cors_allowed_origins='*')" setting to allow it but I can't find anything similar in websockets.

The second question I have more refers to websockets being able to send webrtc SDP "offers" and "answers" between my camera and a browser.  Would they be sent as json TEXT or is there some other way they should be sent.  Are there different "Channels" on websocket such as a text and data or does it all come down the same way.  The following is some truncated data having logging running on the server:

```
= connection is OPEN
< TEXT '{"type":"offer","sdp":"v=0\\r\\no=- 65775026674...age-size:262144\\r\\n"
}' [867 bytes]
> TEXT '{"type":"offer","sdp":"v=0\\r\\no=- 65775026674...age-size:262144\\r\\n"
}' [867 bytes]
= connection is CLOSING
> CLOSE 1000 (OK) [2 bytes]
< CLOSE 1000 (OK) [2 bytes]
x closing TCP connection
= connection is CLOSED
connection closed
```

Of course, it also scares me that the cam and the browser are both going to get their messages echoed back to themselves so I will have to come up with some kind client mapping to prevent that.

Has anyone successfully used this as their webrtc signaling server or seen any samples online with this package.

Thanks

**Comment by aaugustin** [comment]
Regarding your first question: can you enable debug logs (https://websockets.readthedocs.io/en/stable/topics/logging.html#configure-logging) and post the logs?

Specifically, I would like to check if the browser preflights the request, which would appear in the logs as an `OPTIONS` request. If so, websockets should reject that with an HTTP 405 error, which would explain the behavior you're seeing.

(Then we'd have to understand what triggers the pre-flight. You aren't the first person trying a cross-origin connection; you're the first person reporting this issue. I have established cross-origin connections to a websockets server without running into this problem.)

If there's another cause, we may see it in the logs too.

----

You have only one channel in WebSocket connection, unless you're using a subprotocol that specifies multiple channels.

At this point, wouldn't you be better off using https://github.com/aiortc/aiortc?

**Comment by endertable** [comment]
In reference to the cross origin issue I was having, I kind of rewrote some of the coding on the HTML/JS and using a different JS API so I have not been getting that issue anymore. But when I finalize the browser page, it may or may not come back and I will post on here those logs if it does.

Thank you for the reference repository for AIORTC. That is very interesting reading, but I think it is overkill for what I am actually needing. I have been reading a lot about this websocket package including some tutorials online with a connect 4 game which has really helped me learn a lot more about this API.  And alot about Python, as I am just starting to learn this language as well.

I know this package will do what I need, because I need something very simple and I think I am almost there.

I only need like 2 or 3 transmits between browser and cam solely to marry them up:

Camera  connects to the websocket server and just listens, does nothing else but waits and listen for an "SDP offer".

The browser makes that offer to the camera, through the web socket, and then the camera responds with an "SDP answer". 

The browser then takes the information from the SDP answer and forms a secure connection, handshakes with the camera and starts a UDP stream player with that information (this is actually irrelevant to the websocket, anymore).

Hehe, that is all.  That is all I need of the websocket.  It's job is done.  After the cam and browser handshake, the rest is now direct between the browser and the cam.  WebRTC even has it's own data channel for their communication from that point on.

The camera connects perfect to this websocket module and sits steadily waiting for the "offer" for hours like it is supposed to, just PING-PONG so I am very happy about that.  That was half the battle.  That includes with active SSL.  :)

 I will now be working on the html page/JS using coding from the connect4 game as I am new to web sockets JS, and that game worked perfect for parsing data on the websocket channel.  I will just have to revise the app.py a lot because the cam should NOT receive any extraneous messages except for "offers".

I am posting my server.py (app.py) and kind of afraid because as a programmer you would probably want to smack me on the back of the head for this awful programming, but please remember I am new to python as well and still learning how their functions and global variable passing works in this language.  Right now, this is in non-ssl beta testing, but a few ssl_context lines, and we can be secure.  So far it looks like it is going to work if/when I get the browser to interact with it, so thanks much to the person who wrote this websockets.



```
import asyncio
import json
import websockets
import socket


uri='0.0.0.0'
port='5000'

connected_clients = {
    # "id":websocket
}

async def response(websocket):
    global remote_ip
    remote_ip = websocket.remote_address[0]
    print("Connected IP: ", remote_ip)
    ## store client connection / websocket on a dictionary using IP
    connected_clients[str(remote_ip)] = websocket
    async for data in websocket:

        ## decode 'data' to proper json or type(dict)
        responsedata = json.loads(data)
        json_packet: dict = json.loads(data)

        ## handle message, must do following check because camera answer will not have an 'action' keyword
        if 'action' in responsedata:
           action = json_packet['action']
           print(action)
        else:
           action = 'null'

        ##  Execute action
        if action ==  "initt":
                ##  Only the browser sets it's IP as master_ip, does as soon as it connects
                global master_ip
                master_ip = remote_ip
                print("Setting as master IP: ", master_ip)
        elif action == "get_cams":
                ##  Only the browser will inquire about current connections to see which cam(s) connected
                print("Running get_cams")
                print(connected_clients)
		##  Have to find a way to send this to browser and not just console
                print("Master IP: ", master_ip)
        elif action == "make_offer":
                ##  Only the browser will make an offer, should also include IP of camera and SDP offer data
                user_id = json_packet['ip']
                message = json_packet['SDP_OFFER']
                print("Sending SDP Message to: ", user_id)
                if user_id in connected_clients:
                    # send message
                    print(f"IP still alive")
                    await connected_clients[user_id].send(message)
                    await connected_clients[remote_ip].send("Sent offer to cam")
                    print(f"<{message}> sent")
                else:
                    ##  We should actually never get here
                    await connected_clients[remote_ip].send("Connection does not exist!")
                    print("Connection does not exist!")
        elif action == "deinit":
                ##  Disconnect and force close websockets (read up on how to do this)
                deinitt()
            # This last case is for the cam, which will never have an 'action' keyword
        else:
                ##  Ok, the camera does not send an 'action', so it is returning SDP answer to browser
                print(f"sending <{data}> to browser")
                print("Master IP: ", master_ip)
                await connected_clients[master_ip].send(data)
                print(f"<{data}> sent to browser")


# application server
async def server():
    async with websockets.serve(response, uri, port):
        await asyncio.Future()  # run forever



# start application server
if __name__ == '__main__':
    try:
        print(f'Listening on -> ws://{uri}:{port}/')
        asyncio.run(server())
    except KeyboardInterrupt:
        print('\nServer hard stop')
```

**Comment by aaugustin** [comment]
Thanks for sharing and for the kind words!

As far as I understand, you have everything you need to move forwards, so I will close this issue now
