### ISSUE TITLE
Remove the 'Server' token from header to prevent easy fingerprinting

### ISSUE THREAD

**Issue by gitgitwhat** [aaugustin/websockets#1283]
Nmap can easily fingerprint Websockets by the returned Server header (Python/3.7 websockets/10.3 in my particular example).  While the merits of security through obscurity can be argued, reducing data leakage isn't a bad thing.  Apache provides a way to remove this particular header so it'd be nice if Websockets did to.

Am I missing something in the docs or do I need to mod the source code to get this functionality?  It'd be nice if it was an option.

**Comment by aaugustin** [comment]
See https://websockets.readthedocs.io/en/stable/reference/server.html#websockets.server.serve. Use the `server_header=None`.
