### ISSUE TITLE
recv() does not receive all packets

### ISSUE THREAD

**Issue by mkuehn94** [aaugustin/websockets#1285]
I'm building a websocket client with this library but the problem i encounter is that not all packets are recevied when calling websocket.recv()

I'm using 3 different independent coroutines: one for receiving packets, one for sending and one for parsing & interpreting received packets.
The whole application works very well when there is not a high frequency of new packets coming in, but if that's the case the following code seems to "swallow" some packets arbitrarily, like there is some limit of how many packets per second can be received. sample code for my recv coroutine:

```
async def recv_coroutine(websocket):
    try:
        while(True):
            response = await websocket.recv()
            await recv_queue.put(response)

    except Exception as e:
        #exception handling
```

this should ensure that recv is called pretty much all the time and waiting for incoming messages.
any help would be appreciated

**Comment by aaugustin** [comment]
> like there is some limit of how many packets per second can be received

There is no such limit in websockets (other than the practical limit of how fast Python can run on the fastest CPU money can buy). If messages are coming in faster than you can read them, they will pile up and eventually the connection will time out.

You aren't providing enough information to reproduce the issue. If messages are dropped somewhere, odds are very much in favor of the drop occurring in your code (tested by one person over a few days) than in websockets (battletested by tens of thousand of people over a decade).

Also, some high-throughput servers drop messages when clients don't acknowledge them fast enough. Maybe that's the reason. Which server are you connecting to?

**Comment by mkuehn94** [comment]
Thank you for your help and time.
I'm connecting to my own javascript server which sends a lot of binary data. so i can log which packets were send & received. The issue only happens when there is a lot of packets arriving very fast.  my observation however shows that these packets do not pile up but rather get dropped? by the client (never arrive). I admit it's very likely due to my own mistake but i can't find the cause for weeks.

I tried switching 
`response = await websocket.recv()`
with
`async for message in websocket:`

with the same results. The only thing I need to acknowledge is a ping packet which is properly done.

As this is my own problem this issue can be closed and I apologize for any time wasted.

**Comment by aaugustin** [comment]
If you give me a minimum reproducible example, I can take a look. Without seeing the code, I'm not going to be able to say much more.

You should enable debug logs. Then you will see every packet that websockets receives and gives to you app. That could help you pinpoint the problem (or rule out a cause in websockets).
