### ISSUE TITLE
Why are Python websockets way slower than low-level equivalent?

### ISSUE THREAD

**Issue by t0mm4rx** [aaugustin/websockets#1286]
Hello,

I'm trying to understand why Python websockets have so much latency.
The following benchmark shows that Python is about 6x slower than C++ to process websocket messages. It's quite astonishing to me as it seems to be more of an I/O problem rather than a computing one.

Server:
```python
import time
import json
import asyncio
import random
import websockets

async def on_connection(websocket, path):
    """When a client connects."""
    print("New connection")
    while True:
        try:
            await websocket.send(json.dumps({
                "ts": time.time(),
            }))
            time.sleep(random.random() / 2)
        except websockets.ConnectionClosedOK:
            break
        except websockets.exceptions.ConnectionClosedError:
            break

async def main():
    """Entrypoint. Run the server."""
    async with websockets.serve(on_connection, "localhost", 4242):
        await asyncio.Future()

if __name__ == "__main__":
    asyncio.run(main())

```

Here is a basic CPP client implementation:
```cpp
#include "easywsclient.hpp"
#include "simdjson.h"
#include <chrono>
#include <assert.h>
#include <stdio.h>
#include <string>
#include <iostream>
#include <sys/time.h>

using easywsclient::WebSocket;
static WebSocket::pointer ws = NULL;
simdjson::ondemand::parser parser;

inline long long micros() 
{
    return std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::system_clock::now().time_since_epoch()).count();
}

void handle_message(const std::string & message)
{
    simdjson::padded_string messaged_padded(message);
    simdjson::ondemand::document parsed = parser.iterate(messaged_padded);
    double server_ts = parsed.find_field("ts");
    long long delta = micros() - server_ts * 1000 * 1000;
    std::cout << delta << "μs" << std::endl;
}

int main()
{
    ws = WebSocket::from_url("ws://localhost:4242/");
    assert(ws);
    while (ws->getReadyState() != WebSocket::CLOSED) {
      ws->poll();
      ws->dispatch(handle_message);
    }
    delete ws;
    return 0;
}
```

And here is a Python client implementation:
```python
import time
import asyncio
import json
import websockets

async def hello():
    uri = "ws://localhost:4242"
    async with websockets.connect(uri) as websocket:
        while True:
            data = await websocket.recv()
            data = json.loads(data)
            diff = (time.time() - data["ts"]) * 1000 * 1000
            diff = int(diff)
            print(f"{diff}μs")

if __name__ == "__main__":
    asyncio.run(hello())

```

The result is the following:
- The average latency in C++ is 150μs, ranging from 50μs to 300μs.
- The average latency with Python `websockets` is 800μs, ranging from 400μs to 3000μs (3ms).
- I've benchmarked other Python websocket libraries, with very similar results.

My questions are the following:
1. Can you see any bias or error in this benchmark?
2. Why is Python so much slower, and why its latency is so random?
3. Is there any way to reduce the latency while staying in Python?

Thanks

**Comment by aaugustin** [comment]
The Python code sample you provided makes the mistake explained in this FAQ: https://websockets.readthedocs.io/en/stable/faq/asyncio.html#why-does-my-simple-program-misbehave-mysteriously

**Comment by aaugustin** [comment]
The other of magnitude isn't shocking for C++ vs. Python. Unfortunately there's a few copies happening and those aren't cheap.

Other potential issues with your benchmark:

- Is `time.time()` sufficiently accurate? Usually best to use `time.perf_counter()`; since it's only valid for relative measurement, you can send a message from the client, have the server echo it, and see how long it takes for the echo to come back.
- Can you benchmark `json.loads()` separately? I would like to be sure you're benchmarking `websockets` and not `json`.

**Comment by t0mm4rx** [comment]
- time.time is known to be precise at around 1 microsecond. So it's quite insignificant compared to the 800 microseconds that Python takes to process the message.
- `json.loads` takes a few microseconds, the result is no different when placing the `time.time()` before the `json.loads(data)`.

I made the observation that the latency difference is way less on x86_64 hardware than on my M1 chipset. It might be related to hardware optimization.
I get performances much closer to C++ on a testing Linux machine.

**Comment by aaugustin** [comment]
Can you check if `from websockets.speedups import apply_mask` works? If this raises `ImportError`, then it would explain the issue.

**Comment by t0mm4rx** [comment]
Yes, importing `apply_mask` from `websockets.speedups` works.

**Comment by aaugustin** [comment]
It would require more investigation, then. If I want to look into it, I should be able to reproduce your benchmark easily.

**Comment by Evan6998** [comment]
I use `uvloop` running on a x86 machine and the gap between c++ and python narrowed.

```
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

**Comment by aaugustin** [comment]
I was wondering whether the issue could be explained by https://github.com/aaugustin/websockets/blob/f2176ebc682742ec6a00646663c108bc400451bb/src/websockets/speedups.c#L133 not being defined on M1, but a quick Google search suggests that it is. It would cause a large performance gap.

**Comment by aaugustin** [comment]
I agree with the recommendation to use uvloop - documented here: https://websockets.readthedocs.io/en/stable/topics/performance.html

You should also review this FAQ: https://websockets.readthedocs.io/en/stable/faq/misc.html#why-is-websockets-slower-than-another-python-library-in-my-benchmark

For example, if easywebsocket doesn't use compression while websocket uses it, that would easily explain the difference.

For context, I performed extensive benchmarking of websockets (and pushed the state of the art of the ecosystem in Python; other libraries followed). I don't believe there are easy gains left.

The answer is probably going to be in the area of:

- bias in the benchmark i.e. enabling different features;
- Python being generally slower than C++, a known fact.
