### ISSUE TITLE
Delivery guarantee

### ISSUE THREAD

**Issue by kotolex** [aaugustin/websockets#1287]
Hey!
It is not a bug, just a question. If my send() coroutine was succesfull and after it i had succesfull ping-pong - it is guarantee for me, that user got my message?

**Comment by aaugustin** [comment]
Yes.

**Comment by aaugustin** [comment]
(At least at the network level; then you don't know what their software did with the message.)

**Comment by kotolex** [comment]
thats enough for me, thank you
