### ISSUE TITLE
Get all the IPs connected

### ISSUE THREAD

**Issue by endertable** [aaugustin/websockets#1289]
Hi, this is not an issue, more of an inquiry.

This program is working very great as a WebRTC middleman for my cams.  I just have what I hope is a simple question.

How can I retrieve just the IP addresses that are connected?  When I execute:

`print(connected_clients) `

I get the following:

`{'172.16.141.139': <websockets.legacy.server.WebSocketServerProtocol object at 0x75ff02b0>, '172.16.141.138': <websockets.legacy.server.WebSocketServerProtocol object at 0x75ff0730>, '172.16.141.132': <websockets.legacy.server.WebSocketServerProtocol object at 0x75f92390>, '172.16.141.124': <websockets.legacy.server.WebSocketServerProtocol object at 0x75f92310>, '172.16.141.105': <websockets.legacy.server.WebSocketServerProtocol object at 0x75f92fd0>}`

I have tried the following to get just the IP addresses:

```
                allcamsIP = ""
                connectedCams = connected_clients
                for k, v in connectedCams.items():
                    thisIP=vars()[k]
                    allcamsIP=allcamsIP + dmesg
```

And I get the following error:

```
  File "secure_server.py", line 77, in response
    dmesg=vars()[k]
KeyError: '172.16.148.139'

```

Is there a way that I am missing?

Thanks...

**Comment by RemiCardona** [comment]
`k` is the IP address, no need to use `vars()`

**Comment by aaugustin** [comment]
`ip_addresses = list(connected_clients.keys())` should do it. `connected_clients` is a regular Python dict. You should check methods available on `dict` -- they're very useful!

**Comment by aaugustin** [comment]
(The shortest version is `ip_addresses = list(connected_clients)`. It has exactly the same effect. I just wanted to start with the more explicit version.)

**Comment by endertable** [comment]
Thanks, guys!!!!
