### ISSUE TITLE
Blacklisting flooding IPs based on last connect and numbers

### ISSUE THREAD

**Issue by gencer** [aaugustin/websockets#129]
If we want to blacklist some IPs (when they are flooding/ddos) should we do this in our own python code or is it wise to implement it in websockets?

I am currently using MongoDB as backend (or redis can be choosen) and log the activity with minimum data. (IP=LAST_CONNECT). If same IP exceeds the limit, then i just close() without recv().

**Comment by aaugustin** [comment]
I think that's out of scope for websockets. DoS mitigation is a complex topic with no one-size-fits-all answer.

You have at least ways to do this with websockets:

- call a method that perform the check in the handler, you'll need [remote_address]( https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol.remote_address) -- note that it may not be accurate if you deploy websockets behind a reverse proxy.

- subclass WebSocketServerProtocol to do this at the level of the HTTP handshake.

However mitigating DoS in the application layer is pointless. You need to do it at the network level to have any chance to survive. Check out SaaS solutions such as CloudFlare.
