### ISSUE TITLE
OSError: [WinError 121] The semaphore timeout period has expired

### ISSUE THREAD

**Issue by chriscai91** [aaugustin/websockets#1291]
Hi,

I get the above error when the websocket connection is persisted for more than a day. The error is preceded by 'data transfer failed' in the python terminal. Although I have reconnection implemented and it successfully reconnects, my program will stop working because of the data transfer error.

Any help would be much appreciated.

Thanks

**Comment by aaugustin** [comment]
This is the same as #924 and #810. I guess a network device between you and the server cuts the connection after a day. You should catch the exception so that your program continues working after reconnection.

**Comment by chriscai91** [comment]
Thanks for the reply! If I deploy the websocket app to some cloud service would this still happen? The current program is running locally on my PC.

**Comment by aaugustin** [comment]
In the cloud, you would probably run the app on Linux, so this Windows-specific error won't happen. However, if you want your program to be resilient, it would be worth figuring out how to recover from disconnections. Generally speaking, if you assume that [the network is reliable](https://queue.acm.org/detail.cfm?id=2655736), you will be disappointed at some point.
