### ISSUE TITLE
How to implement websocket reverse proxy？

### ISSUE THREAD

**Issue by manyhelp** [aaugustin/websockets#1293]
1. I need to connect to the third-party websocket and accept the data。
2. push the received data to the web page

target server wss url： wss://hq.sinajs.cn/wskt?list=sz002460,sz002466
                     wss header:  {"Origin": "https://finance.sina.com.cn", "Host": "hq.sinajs.cn",}

received target server data, websocket push web page.

do not use nginx or iss ...

**Comment by aaugustin** [comment]
You need to write a server with a connection handler along the lines of:

```python
async def handler(server_ws):
    async with connect("wss://hq.sinajs.cn/wskt?list=sz002460,sz002466", origin="https://finance.sina.com.cn/") as client_ws:
        async for message in client_ws:
            await server_ws.send(message)
```

**Comment by aaugustin** [comment]
Untested — I don't intend to do your homework — but hopefully this gets you started.
