### ISSUE TITLE
Explanation of sub-packages marked as `legacy`  in the documentation

### ISSUE THREAD

**Issue by WillCodeCo** [aaugustin/websockets#1297]
I was just curious if the intention is to move away from `asyncio` since most of the guts of the async stuff is happening in a package called `websockets.legacy` ?

I did try searching through the docs, apologies if I missed something.

Thanks !

**Comment by aaugustin** [comment]
There is no intent to move away from asyncio.

There is an intent to support other concurrency & I/O models, included but not limited to Sans-I/O (already available) and sockets & threads (#1245, started 3 or 4 years ago, but life happens...)

There is a possibility of building a new asyncio layer on top of the Sans-I/O layer, similar to the work-in-progress sockets & thread layer. It is far from obvious that it will happen in my lifetime.

**Comment by aaugustin** [comment]
If the latter happens, then I'll organize an orderly transition from the current implementation, marked as legacy, to the new implementation. Don't hold your breath though.

**Comment by aaugustin** [comment]
Worth adding to the FAQ.
