### ISSUE TITLE
watchdog==2.3.0 breaks reload on code changes in docs

### ISSUE THREAD

**Issue by leogallot** [aaugustin/websockets#1303]
Hello,

Since `watchdog==2.3.0`, the content of the _**Reload on code changes**_ section of the docs seems not to work properly anymore, the websockets server doesn't start.

`watchmedo auto-restart --pattern "*.py" --recursive --signal SIGTERM python app.py`

```python
# app.py

import asyncio
import websockets

async def hello(websocket):
    name = await websocket.recv()
    print(f"<<< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f">>> {greeting}")

async def main():
    async with websockets.serve(hello, "localhost", 8765):
        await asyncio.Future()  # run forever

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by leogallot** [comment]
`watchdog==2.3.1` fixed it. 👍

**Comment by aaugustin** [comment]
Thank you for taking the time to let me know and good to hear that it was fixed promptly!
