### ISSUE TITLE
Websockets Sending Messages Fails Despite Successful Code Execution

### ISSUE THREAD

**Issue by killerwhite** [aaugustin/websockets#1305]
Hi there,
 
I am writing to report a problem I encountered while using your websockets library.
 
I am sending messages to a client using the library and the code appears to be sending them successfully (no exceptions are thrown). But in practice the client is not receiving any WebSocket messages and Wireshark is not capturing any sent WebSocket messages. Moreover, the WebSocketServerProtocol object's state remains at 1 regardless of whether the client receives the WebSocket message or not.
 
I have included some debugging information below.
 
I added logging when sending messages to the client on the server side: 
{Image 1}
 
![image](https://user-images.githubusercontent.com/22679011/222881019-1c813d36-b1f3-4b87-a7ad-511cdd059a6a.png)

When sending succeeds, the connection state is 1:
{Image 2}
 
![2](https://user-images.githubusercontent.com/22679011/222881076-806a70aa-ed0e-4d66-8c25-653409c91a38.jpg)

When sending fails, the connection state remains at 1: 
{Image 3}
 
![3](https://user-images.githubusercontent.com/22679011/222881094-ef9e2b7f-44ba-44da-8ec0-a3f0b3b47a6a.jpg)

At this point, the settings for my server were as follows: 
{Image 4}
 
![image](https://user-images.githubusercontent.com/22679011/222881097-7c372b6b-407d-4f0d-8d3c-0fd1f79fe1d0.png)

I removed the "ping_interval=None" setting as shown in Image 5.
{Image 5}
 
![image](https://user-images.githubusercontent.com/22679011/222881103-ae806b82-436c-4273-8182-a45d6f9df5fa.png)

After removing the ping_interval configuration, the actual sending failure problem no longer occurs.

I would really appreciate it if you could fix this issue as soon as possible

**Comment by aaugustin** [comment]
> When sending fails, the connection state remains at 1:

You are logging the value *before* calling send().

> After removing the ping_interval configuration, the actual sending failure problem no longer occurs.

This suggests that the client you are connecting to doesn't respond to pings, which is a protocol violation. Disabling keepalive is a reasonable solution to deal with such clients.

> I would really appreciate it if you could fix this issue as soon as possible

I would really appreciate it if you double checked your code before wasting my time.
