### ISSUE TITLE
Access timeout condition in infinite asynchronous iterator for client.connect

### ISSUE THREAD

**Issue by MarkusPiotrowski** [aaugustin/websockets#1308]
I hope it is OK to ask a question, I didn't find another place to do so.

I'm using `client.connect()` with an infinite asynchronous iterator as described in the docs:
```
async for websocket in websockets.connect(...):
    try:
        await websocket_handler(websocket)
    except websockets.ConnectionClosed:
        continue
```
In my program, I want to stop the iterator if a certain `asyncio.Event` is set. This can happen any time, either when the websocket handler is running, but also if the connection was already closed and cannot be opened again (e.g. because the websocket server has stopped working). 
I had thought that an `open_timeout` would cause the iterator to enter the `for loop`, where I could then check the `asyncio.Event` status, but this does not seem to be the case.  
So, in this 'infinite asynchronous iterator' pattern, is there any chance for me to get knowledge about a failed connection attempt?

Or would you suggest using a different pattern, e.g.:
```
while not stop_condition.is_set():  # my asyncio.Event
    async with websockets.connect(...) as websocket:
        await websocket_handler(websocket)
```
I wonder about the performance of both approaches, in my experience the 'infinite asynchronous iterator' pattern worked quite well.

**Comment by aaugustin** [comment]
Hello, the automatic reconnection pattern (`async for websocket in websockets.connect()`) is, well, automatic and doesn't give you control on reconnections. If the open timeout is reached, it retries and it enters the loop only once it manages to establish a connection.

----

The code is here: https://github.com/aaugustin/websockets/blob/ba1ed7a65cc876ff4e0fcd4dd4711402836475e2/src/websockets/legacy/client.py#L592-L646

If you ignore exponentional backoff on retries and backwards compatibility for Python < 3.8, it boils down to:

```python
        while True:
            async with connect(...) as websocket:
                yield websocket
```

That's exactly the pattern you're proposing — after replacing `while True` with `while not stop_condition.is_set()`. So you can just do that.

----

An alternative would be to put the whole code into a coroutine:

```python
async def run_client():
    async for websocket in websockets.connect(...):
        ...
```

Then start a task that runs this coroutine and cancel the task when you want to exit.

**Comment by MarkusPiotrowski** [comment]
Dear @aaugustin,

Thank you.
