### ISSUE TITLE
async for messages in ws doesn't wait for all messages if stream is idle

### ISSUE THREAD

**Issue by nitanmarcel** [aaugustin/websockets#1311]
If the stream is idle for a few seconds, I can't receive any new messages and for loop exists.

The websocket is taken from an website, where I can see the messages being received, but they are most of the time slow, and there are many of them coming at once. but in the code below, it doesn't wait for it to finish

```
async with websockets.connect(URL, ssl=True) as ws:
    await ws.send('{"protocol":"json","version":1}')
    async for messages in ws:
        print(messsages)
        # sometimes, if the stream is idle for a few seconds, I can't receive any new messages and loop exists

**Comment by aaugustin** [comment]
Your report is extremely vague, making it impossible for me suggest potential causes.

What does "slow" mean? 50ms between messages? 50 seconds? 50 hours?

What does "doesn't wait to finish" mean? Do you get an exception? Does the program hang?

Could you provide a complete reproducible example? Assuming the server is public.

Failing that, could you enable debug logs (https://websockets.readthedocs.io/en/stable/topics/logging.html#configure-logging) and provide full logs as well as the full stack trace if you get an exceptionL

**Comment by nitanmarcel** [comment]
> Your report is extremely vague, making it impossible for me suggest potential causes.
> 
> What does "slow" mean? 50ms between messages? 50 seconds? 50 hours?
> 
> What does "doesn't wait to finish" mean? Do you get an exception? Does the program hang?
> 
> Could you provide a complete reproducible example — if the server is public?
> 
> Failing that, could you enable debug logs (https://websockets.readthedocs.io/en/stable/topics/logging.html#configure-logging) and provide full logs as well as the full stack trace if you get an exception?

Meaning the stream is spanmed with messages, but at a certain point it stops receiving them and moves forward finishing the for loop.

Will try my best to write a reproductible code later

https://github.com/nitanmarcel/sydney-telegram/blob/main/bot_chat.py#L128


The delay is something around half a second or a second. This can be seen with a bing account and a bot chat whitelist, at this site with debug tools and websocket network listen.

https://bing.com/sydchat

**Comment by aaugustin** [comment]
Possibly, you have more than 20 seconds of lag reading messages and websockets' keepalive times out.

You can test this hypothesis by adding `ping_timeout=None` to your `connect()` call.

websockets can read/write >10k messages / second so it isn't the bottleneck. The bottleneck is probably what your code does between reading messages.

**Comment by nitanmarcel** [comment]
> Possibly, you have more than 20 seconds of lag reading messages and websockets' keepalive times out.
> 
> You can test this hypothesis by adding `ping_timeout=None` to your `connect()` call.
> 
> websockets can read/write >10k messages / second so it isn't the bottleneck. The bottleneck is probably what your code does between reading messages.

Thanks for the response, but that didn't help. Whatever it got me in the right track and it seems that I got it working.

Not related to the library, but it seems that the server, at least what I could decipher from the source code needs a json message as a ping. Disabling the ping_timeout and ping_interval and sending the ping json seems to have fixed my issue

**Comment by aaugustin** [comment]
Oh, yes, this happens. While the WebSocket spec says that arbitrary ping payloads are possible, some servers put restrictions on what you should send.
