### ISSUE TITLE
how i can do an request header auth before conneciton in server?

### ISSUE THREAD

**Issue by notedit** [aaugustin/websockets#133]

**Comment by aaugustin** [comment]
You'll have to inherit `WebSocketServerProtocol` and override the `handshake` method.

https://github.com/aaugustin/websockets/blob/858b261d7d5365128e4f302690892d16fa93e34c/websockets/server.py#L124

Check authentication in the HTTP headers, if it's correct return the normal response to upgrade to websockets, if not request it.

**Comment by aaugustin** [comment]
This will be built-in in version 8.0.
