### ISSUE TITLE
How to make wss instead of ws?

### ISSUE THREAD

**Issue by vanjavk** [aaugustin/websockets#135]
I can't find any example on how to do this anywhere. I already have letsencrypt cert on my server (so I thought I'd use that?). I have files: cert.pem chain.pem fullchain.pem privkey.pem
Now what exactly I need to do to convert my ws server to wss ? I couldn't find any tutorials that deal with my situation :(
Also I was thinking of using only TLSv1.2 protocol if there's not some good reason against it?

**Comment by vanjavk** [comment]
Basicly my ws server works normally but when I add this:
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain(certfile="/etc/letsencrypt/live/vanjavk.xyz/cert.pem", keyfile="/etc/letsencrypt/live/vanjavk.xyz/privkey.pem")
start_server = websockets.serve(handler, host=ip,port=port,ssl=context)

and then change client address from ws://139.59.214.241:13337 to wss://139.59.214.241:13337

I get no errors on server but when I try to connect with client I get: ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)

**Comment by vanjavk** [comment]
Actually I just realised that adding ssl=context doesn't make it automatically wss because I can still connect to it through ws :( I'm totally confused

**Comment by vanjavk** [comment]
Woops apparently something else stopped me from using wss. It works now so I'll just close this :D

**Comment by DoHyeong** [comment]
hello i have a similar problem like that.
my chrome returns 'failed: WebSocket opening handshake was canceled' error
can you show me pull source code?
thank you

**Comment by vanjavk** [comment]
Well my problem was that I didn't know how to exactly enable SSL, but at the end this is source code of enabling it:
```
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain(certfile="/etc/letsencrypt/live/vanjavk.xyz/cert.pem", keyfile="/etc/letsencrypt/live/vanjavk.xyz/privkey.pem")
start_server = websockets.serve(handler, host=ip,port=port,ssl=context)
```
everything else in source code is related to my project and not important

**Comment by DoHyeong** [comment]
my code is same that.

Is your letsencrypt file is same that your calling client's(web site) certification?

Thank you.

**Comment by vanjavk** [comment]
I'm not calling any certs on client (my client isn't actually in python), I just use wss instead of ws in address.
This is source code (javascript) of extension I used in my app:

```
/**
Client-Side WebSocket Bindings for GameMaker Studio
Author: Dickson Law
(C) GameGeisha Interactive, 2010-2014
*/

var __ws_sockets__ = new Array();

function __ws_connect__(url) {
	return __ws_connect_ext__(url, "");
}

function __ws_connect_ext__(url, protocols) {
	var ws, id;
	
	//Try to create the WebSocket
	try {
		if (protocols == "") {
			ws = new WebSocket(url);
		}
		else {
			ws = new WebSocket(url, protocols.split('|'));
		}
	}
	catch (e) {
		return -1;
	}
	
	//Add the WebSocket
	id = __ws_sockets__.push({
		socket: ws,
		inbox: new Array()
	})-1;
	
	//Tack on events
	ws.onmessage = function(event) {
		__ws_sockets__[id].inbox.push(event.data);
	};
	
	//Return numeric handle
	return id;
}

function __ws_status__(id) {
	try {
		return __ws_sockets__[id].socket.readyState;
	}
	catch (e) {
		return -1;
	}
}

function __ws_disconnect__(id) {
	return __ws_disconnect_ext__(id, 1000, "");
}

function __ws_disconnect_ext__(id, code, reason) {
	try {
		__ws_sockets__[id].socket.close(code, reason);
	}
	catch (e) {
		return false;
	}
}

function __ws_send_message__(id, msg) {
	try {
		__ws_sockets__[id].socket.send(msg);
		return true;
	}
	catch (e) {
		return false;
	}
}

function __ws_has_message__(id) {
	try {
		return __ws_sockets__[id].inbox.length > 0;
	}
	catch (e) {
		return false;
	}
}

function __ws_get_message__(id) {
	try {
		return (__ws_sockets__[id].inbox.splice(0, 1))[0] || "";
	}
	catch (e) {
		return "";
	}
}
```
