### ISSUE TITLE
is websockets support cocurrent?

### ISSUE THREAD

**Issue by JoyCood** [aaugustin/websockets#136]
when two client connect in to server, the client that last connect the server must wait the first client processing finish? like a queue? is there have an example like SocketServer lib? one thread to one client after connected made.

**Comment by mschnitzer** [comment]
@JoyCood here is an example how you can have each client in a single thread: https://github.com/mschnitzer/dapsenv/blob/master/source/dapsenv/apiserver.py

The code is not pretty well - still not a python expert. But at least you've a starting point.

**Comment by JoyCood** [comment]
@mschnitzer thanks for your reply, but the link is unavailable.

**Comment by mschnitzer** [comment]
@JoyCood Oh yes, this is a private repository. But I can leak this stuff since it doesn't need to be private: https://gist.github.com/mschnitzer/0c3a86d249c89f0ffa88a26b788d8c75

**Comment by JoyCood** [comment]
@mschnitzer 
from your code, the port can bind once, but when your start more than one thread will raise bellow exception:
OSError: [Errno 48] error while attempting to bind on address ('::', 2222, 0, 0): address already in use

**Comment by mschnitzer** [comment]
When initializing this class, it starts a thread in which is running the websocket server. Then each client will be in a new thread as you can see here: https://gist.github.com/mschnitzer/0c3a86d249c89f0ffa88a26b788d8c75#file-ws_thread-py-L29

This line means: Start a server with the IP `self._ip` and port `self._port` and use `self._api_server_runtime` as the client thread.

For example:
Client 1 connects -> It will be processed in a new thread which runs the `self._api_server_runtime` function.
Client 2 connect -> Runs in a separate `self._api_server_runtime` thread

**Comment by JoyCood** [comment]
@mschnitzer i try to simulate your code like bellow, but it is not concurrent runing. 
we start the server and listening on 2222, then start two clients: client_1, client_2 and type something in client_1 and client_2,  the server will aways print the result same order as input order. so the websockets is not concurrent?

**websockets_server.py**
`
    import asyncio
    import threading
    import time
    import websockets

    async def handler(websocket, path):
        while True:
            try:
                data = await websocket.recv()
                print("< {}".format(data))
                time.sleep(5)
            except websockets.exceptions.ConnectionClosed:
                print("socket closed")
                break

    def serve():
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        start_server = websockets.serve(handler, '', 2222)
        asyncio.get_event_loop().run_until_complete(start_server)
        asyncio.get_event_loop().run_forever()

    threading.Thread(target=serve).start()

`

**websockets_client.py:**
`
    import sys
    import asyncio
    import websockets

    async def client():
        async with websockets.connect('ws://localhost:2222') as socket:
            while True:
                thing = sys.stdin.readline()
                if thing == '\n':
                    return
                await socket.send(thing)

    asyncio.get_event_loop().run_until_complete(client())

`

**Comment by mehaase** [comment]
Yes, this library can handle concurrent connections. Why do you expect the server to print out messages in a different order than it receives them?

Also, you should use `await asyncio.sleep(5)`, not `time.sleep(5)`. Using `time.sleep` will block the entire event loop for 5 seconds, while using `asyncio.sleep` will schedule the coroutine to resume in 5 seconds and will allow the event loop to keep running in the meantime.

**Comment by JoyCood** [comment]
@mehaase thanks you.   i got it now.
