### ISSUE TITLE
consider building on wsproto

### ISSUE THREAD

**Issue by graingert** [aaugustin/websockets#139]
wsproto is part of the https://sans-io.readthedocs.io/ movement and can allow various different IO systems to share code.

**Comment by graingert** [comment]
eg a twisted or a blocking or an asyncio approach can all benefit from a common core of code.

**Comment by aaugustin** [comment]
websockets predates the sans-io movement. It works and I'm not planning to rewrite it for no actual benefits.

If you want on asyncio + wsproto library, the easiest is to start a new project. Perhaps you can learn from my mistakes and get the API right faster than I did :-)

**Comment by graingert** [comment]
> Perhaps you can learn from my mistakes and get the API right faster than I did

What do you mean by this?

**Comment by aaugustin** [comment]
You can take a look at the changelog around major version bumps.

Also skimming closed issues could show you what trips up users.
