### ISSUE TITLE
how can i use wss requests?

### ISSUE THREAD

**Issue by DoHyeong** [aaugustin/websockets#140]
I want to use wss requsts.
how can i use it?
browser returns 
failed: WebSocket opening handshake was canceled

**Comment by aaugustin** [comment]
You need a valid SSL certificate or else the browser will summarily terminate the connection.

**Comment by aaugustin** [comment]
In case that helps here's the code that starts a WSS server in the test suite:
https://github.com/aaugustin/websockets/blob/master/websockets/test_client_server.py#L390-L393
