### ISSUE TITLE
Getting peer certificate (wss://..)

### ISSUE THREAD

**Issue by nobuggy** [aaugustin/websockets#145]
I'm using websockets with wss://.. and I need to get the peer certificates after the connection has been established. In order to do that I need access to the `SSLSocket.getpeercert()` via `BaseTrasport.get_extra_info()`. I did not find an API to get hold of a transport underlying a websocket (apologies if there is and I didn't see it).

Here's a piece of code based on the sample from the doc that shows how I did it (uses TLS client authentication). Requires access to private fields **`websocket.reader._transport`**. Maybe an API could be added to avoid accessing internal fields.

```python
import ssl
import asyncio
import websockets
from pprint import pformat

async def serve_connection(websocket, path):
    transport = websocket.reader._transport
    sslsock = transport.get_extra_info('ssl_object')
    print("server: client cert: %s" % (pformat(sslsock.getpeercert()),))
    
    name = await websocket.recv()
    print("server < {}".format(name))
    greeting = "Hello {}!".format(name)
    await websocket.send(greeting)
    print("server > {}".format(greeting))


async def test():
    server_tls_ctxt = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    server_tls_ctxt.load_cert_chain('server.crt', 'server.key')
    server_tls_ctxt.load_verify_locations('client.crt')
    server_tls_ctxt.verify_mode = ssl.CERT_REQUIRED
    
    client_tls_ctxt = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    client_tls_ctxt.load_verify_locations('server.crt')
    client_tls_ctxt.load_cert_chain('client.crt','client.key')
    client_tls_ctxt.verify_mode = ssl.CERT_REQUIRED
    client_tls_ctxt.check_hostname = True
    
    start_server = await websockets.serve(serve_connection, 'localhost', 8765, ssl=server_tls_ctxt)

    async with websockets.connect('wss://localhost:8765', ssl=client_tls_ctxt) as websocket:
        transport = websocket.reader._transport
        sslsock = transport.get_extra_info('ssl_object')
        print("client: server cert: %s" % (pformat(sslsock.getpeercert()),))

        name = 'Tom Bombadil'
        await websocket.send(name)
        print("client > {}".format(name))
        greeting = await websocket.recv()
        print("client < {}".format(greeting))

    start_server.close()
    await start_server.wait_closed()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(test())
    finally:
        loop.close()
```
For the sake of completeness here the two lines to create the referenced keys/certs with openssl:
```
openssl req -new -x509 -days 365 -sha1 -newkey rsa:1024 -nodes -keyout server.key -out server.crt -subj '/O=Company/OU=Department/CN=localhost'
openssl req -new -x509 -days 365 -sha1 -newkey rsa:1024 -nodes -keyout client.key -out client.crt -subj '/O=Company/OU=Department/CN=Tom Bombadil'
```

**Comment by aaugustin** [comment]
The `websocket` object is an instance of `websockets.WebSocketServerProtocol` which inherits `asyncio.StreamReaderProtocol`.

The connection is entirely handled by `asyncio.StreamReaderProtocol` at the lower levels.

Based on the documentation, I think you could create a subclass that inherits `WebSocketServerProtocol` and override the `connection_made(transport)` method.

https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseProtocol.connection_made

There you get the transport from a public API. Also you get it when the TLS connection is established, which is the best point to handle certificate based authentication. If auth fails there's no point to proceed with the HTTP and websocket handshake.

**Comment by nobuggy** [comment]
Works! Didn't see that. Maybe the doc could have an example in case this comes up again (or maybe not if it's too exotic). Thanks for the quick answer.

**Comment by aaugustin** [comment]
I think the docs refer to the possibility to inherit `WebSocketServerProtocol` somewhere.

If you want to add an example — "for instance you can override connection_made..." — a pull request will be appreciated. Thanks!
