### ISSUE TITLE
Websocket server restarts constantly 

### ISSUE THREAD

**Issue by rldotai** [aaugustin/websockets#148]
The websocket server restarts constantly if used with `run_forever()` if you use it as suggested by the example.

The server script I am using is slightly modified so it just sends "Hello" to the client (which can be a minimal web page).
I provide both below.

The `server.py` script.

```python3
#!/usr/bin/env python

import asyncio
import websockets

async def hello(websocket, path):
    greeting = "Hello"
    await websocket.send(greeting)
    print("{}".format(greeting))

start_server = websockets.serve(hello, 'localhost', 9999)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

A minimal web page using the browser's builtin WebSocket implementation.

```html
<!doctype html>
<html>
<head></head>
<body></body>
<script>
var ws = new WebSocket('ws://localhost:9999');
ws.onopen = () => console.log('Connection opened');
ws.onclose = () => console.log('Connection closed');
ws.onmessage = (msg) => console.log(msg);
</script>
</html>
```

The output from the server script is:

```
Hello
Hello
Hello
```

And in the JavaScript debug console, we get

```
Connection opened
MessageEvent {isTrusted: true, data: "Hello", origin: "ws://localhost:9999", lastEventId: "", source: null…}
Connection closed
```

Even while the `server.py` script continues to print `Hello`.

The documentation suggests that this example script should instead send the message and close the connection; instead it sends the message repeatedly even if there is no client capable of receiving it.
If `run_forever()` is not used, no message is sent.

I do not know if this is a bug in the library itself, or something on my end (standard Python 3.5 via Anaconda on Ubuntu 14), but it is really confusing.

As suggested elsewhere, it's possible to avoid this behavior by e.g. terminating the event loop itself, (with `loop.stop()`, but I was wondering if a) this problem is specific to my setup or b) if there's a cleaner way to avoid what seems to be undesirable behavior.

**Comment by aaugustin** [comment]
Can you clarify this?

> Even while the server.py script continues to print Hello.

I expect the server to print "Hello" once every time you refresh the page in the browser.

The examples provided in the documentation have a `while True` statement (because lots of people were confused when the example exited after sending a single message). Are you sure you aren't running a version where this statement is still present?

**Comment by rldotai** [comment]
It turns out it was a bug on my end.
Originally I was using the `reconnecting-websockets` package from npm, but suspected that the connection was being reestablished after it closed, prompting another "Hello" to be sent.

This was essentially the case.

I switched to using the builtin `WebSocket` instead, but found the same behavior.
It turns out that I had not saved the commented version and the `ReconnectingWebsocket` was not garbage collected, so it continued to receive messages while the builtin `WebSocket` recorded that the a single message was sent and the connection was subsequently closed.

```javascript
// the following line should have been commented or removed
var ws = new ReconnectingWebsocket('ws://localhost:9999');
var ws = new WebSocket('ws://localhost:9999');
``` 

So, it was not a bug, and I apologize for not making sure that I tested with the exact same code I posted in the issue report.

However, I am still wondering how I might implement a websocket server that performs a task (e.g., sends a message) and then ceases running and releases the connection.

If I use `run_forever()`, it seems to do just that, which can be worked around but is probably not ideal.
If I use `run_until_complete()`, I cannot get the message to be consistently sent; it seems that at one end or the other the connection may end up being closed, or the handshake fails.

Here is the code that I am using.

```python3
#server.py
import asyncio
import websockets

async def hello(websocket, path):
    greeting = "Hello"
    await websocket.send(greeting)
    print("{}".format(greeting))

start_server = websockets.serve(hello, 'localhost', 9999)
asyncio.get_event_loop().run_until_complete(start_server)
```

Running this once after refreshing the page will sometimes send a message, but will sometimes not send anything and the program will just exit (without printing anything).

Other times, after refreshing the page and running `server.py` from the IPython console, we might get

```python
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.
``` 

Later the browser console might log an error like 

```
WebSocket connection to 'ws://localhost:9999/' failed: WebSocket opening handshake timed out
```

and in the IPython console, a `BrokenPipeError` is raised

```python
BrokenPipeError: [Errno 32] Broken pipe
Task exception was never retrieved
```

Is the `websockets` library just not intended for this purpose?

Or is there some pattern I can employ to be able to connect, send a message, close and release the socket?
Ideally with some sort of guarantee that it will be received if there's a client waiting for a connection on the other end?



Thanks for the help.

**Comment by aaugustin** [comment]
> is there some pattern I can employ to be able to connect, send a message, close and release the socket?

The code you posted above does exactly that for every WebSocket connection.

Additionally, if you want to stop the server exactly after it has served one connection, you can probably do something like this (untested):

```python
import asyncio
import websockets

handled_one_request = asyncio.Future()

async def hello(websocket, path):
    greeting = "Hello"
    await websocket.send(greeting)
    print("{}".format(greeting))
    handled_one_request.set_result(None)

start_server = websockets.serve(hello, 'localhost', 9999)
server = asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_until_complete(handled_one_request)
server.close()
asyncio.get_event_loop().run_until_complete(server.wait_closed())
```

This is a weird use case, though.

**Comment by rldotai** [comment]
That actually helps clarify how `asyncio` and `websockets` work together.
I was having trouble following the `asyncio` documentation because it's a) massive and b) somewhat non-linear.

I ended up deciding to bite the bullet and use a backend that can handle publishing to arbitrary numbers of clients.
It was actually pretty easy all things considered.
So, I suppose that's the true sign of well-designed code, in that it makes doing things correctly (well, robustly) easier than just hacking out a prototype. 
Thanks again!
