### ISSUE TITLE
Support ssl=None in connect w/ ws:// URL

### ISSUE THREAD

**Issue by Badg** [aaugustin/websockets#149]
Currently, if you pass ssl=None like this:

```python
        if tls:
            use_tls_ctx = SSL_VERIFICATION_CONTEXT
        
        else:
            use_tls_ctx = None
        
        websocket = await websockets.client.connect(
            str(loc),
            ssl = SSL_VERIFICATION_CONTEXT,
            max_size = 10 * (2 ** 20)    # Max incoming msg size 10 MiB
        )
```

you get something like this:

```
Traceback (most recent call last):
  File "c:\users\badgerdoc\dropbox\documents\projects--muterra\py_hypergolix\hypergolix\comms.py", line 719, in loop_run
    **self._conn_kwargs
  File "C:\Python35\lib\asyncio\coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "c:\users\badgerdoc\dropbox\documents\projects--muterra\py_hypergolix\hypergolix\comms.py", line 418, in new
    max_size = 10 * (2 ** 20)    # Max incoming msg size 10 MiB
  File "C:\Python35\lib\site-packages\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "C:\Python35\lib\site-packages\websockets\client.py", line 151, in connect
    raise ValueError("connect() received a SSL context for a ws:// URI. "
ValueError: connect() received a SSL context for a ws:// URI. Use a wss:// URI to enable TLS.
```

The docs on ```AbstractEventLoop.create_connection``` makes it look like ssl=None is acceptable. It would be nice (I mean, it's definitely splitting hairs! It took me all of three additional lines of code to have a workaraound, but...) if ssl=None would still work with a ws:// URL, as a secondary (yes, perhaps redundant) way of specifying "not using TLS here".

**Comment by aaugustin** [comment]
[This line](https://github.com/aaugustin/websockets/blob/c25954538aab85c259dc37e8235c1362d9543146/websockets/server.py#L347) means that not specifying `ssl` and specifying `ssl=None` are equivalent on the server side.

[This line](https://github.com/aaugustin/websockets/blob/c25954538aab85c259dc37e8235c1362d9543146/websockets/client.py#L150) should be changed to achieve the same effect on the client side.

I will accept a PR that changes `elif 'ssl' in kwds` to `elif kwds.get('ssl') is not None`. Just make sure tests still pass with `tox` with that change.

**Comment by Badg** [comment]
👍 I'll see what I can do!
