### ISSUE TITLE
Consumer and Producer both in code sample

### ISSUE THREAD

**Issue by RojavaCrypto** [aaugustin/websockets#152]
From here:

https://websockets.readthedocs.io/en/stable/intro.html

The listed code sample for both receive and send is convulated and not straightforward.

Here is a better solution:

```
async def consumer_handler(websocket, path):
    while True:
        message = await websocket.recv()
        await consumer(message)

async def producer_handler(websocket, path):
    while True:
        message = await producer()
        await websocket.send(message)

async def handler(websocket, path):
    loop = asyncio.get_event_loop()
    producer_task = loop.create_task(self.producer_handler(websocket, path))
    consumer_task = loop.create_task(self.consumer_handler(websocket, path))
    # Use task.cancel() to stop the tasks.

```

**Comment by aaugustin** [comment]
Unless I'm missing something, `handler()` will return immediately and the websocket connection will be closed before the tasks have any chance to do something.

Did you try this code and does it work for you?

**Comment by chmedly** [comment]
I decided to use RojavaCrypto's code since it looked like it was designed to do what I'm trying to do and I figured someone should see if it works.  My rework:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time
import asyncio
import websockets
import functools
import json
from multiprocessing import Process, Pipe


async def consumer_handler(websocket, path, parent_conn):
    while True:
        message = await websocket.recv()
        parent_conn.send(message)


async def producer_handler(websocket, path, child_conn2):
    while True:
        if child_conn2.poll():
            message = child_conn2.recv()
            message = json.dumps(message)
            await websocket.send(message)

async def handler(websocket, path, parent_conn, child_conn2):
    loop = asyncio.get_event_loop()
    producer_task = loop.create_task(producer_handler(websocket, path, child_conn2))
    consumer_task = loop.create_task(consumer_handler(websocket, path, parent_conn))
    # Use task.cancel() to stop the tasks.


def f(child_conn):
    while True:
        if child_conn.poll():
            stuff = child_conn.recv()
            print("Stuff in fconn is: {}".format(stuff))

def f2(parent_conn2):
    while True:
        asyncio.sleep(4)
        currenttime = round(time.time())
        parent_conn2.send(currenttime)
            
if __name__ == '__main__':
    parent_conn, child_conn = Pipe()
    parent_conn2, child_conn2 = Pipe()
    p = Process(target=f, args=(child_conn,))
    p.start()
    p2 = Process(target=f2, args=(parent_conn2,))
    p2.start()
    start_server = websockets.serve(
            functools.partial(handler, parent_conn=parent_conn,
            child_conn2=child_conn2),
            '127.0.0.1', 8765)
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()

    p.join()
    p2.join()

```
It seems to run ok.  It prints out complaints when the client closes the connection suddenly but keeps running.  Of course I'm still struggling to write a client that works with it to really test it.  I need the client to have separate consumer and producer coroutines.  Once the client connects to the server, the server should begin sending routine messages for the client to consume.  And the client can send bits of data back in response to the users actions in a GUI.  (And I want to derive the GUI update loop from the incoming messages from the server.)  I just can't find much in the way of example code to understand how this can work with websockets.

**Comment by aaugustin** [comment]
In the meantime, https://websockets.readthedocs.io/en/stable/intro.html#both was changed to something closer to their suggestion, without the bug I pointed out.

**Comment by chmedly** [comment]
So the server WAS closing the connection!  Aha.  Thank you for adding this. I didn't realize it was in response to RojavaCrypto's code.   

Here's some updated server code with added sprinkles to aid troubleshooting. 
One of the problems I'm having is that my server's consumer_handler coroutine doesn't appear to be taking anything from the websocket even though my client appears to be sending.  For instance, the Intro example client should send something that the server should print.  What am I missing??  

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time
import asyncio
import websockets
import functools
import json
from multiprocessing import Process, Pipe, Queue

async def consumer_handler(websocket, parent_conn):
    while True:
        try:
            message = await websocket.recv()
            parent_conn.put(message)
            print("I sent this to the queue: {}".format(message)) 
        except Exception as e1:
            print("consumer exception was: {}".format(e1))
            break

async def producer_handler(websocket, child_conn2):
    while True:
        message = child_conn2.recv()
        message = json.dumps(message)
        try:
            await websocket.send(message)
        except Exception as e1:
            print("producer exception was: {}".format(e1))
            break

async def handler(websocket, path, parent_conn, child_conn2):
    consumer_task = asyncio.ensure_future(consumer_handler(websocket, parent_conn))
    producer_task = asyncio.ensure_future(producer_handler(websocket, child_conn2))
    done, pending = await asyncio.wait(
        [consumer_task, producer_task],
        return_when=asyncio.FIRST_COMPLETED,
    )

    for task in pending:
        task.cancel()

def f(parent_conn):
    print("child_conn f started.") #Is this thing even on? 
    while True:
        stuff = parent_conn.get()
        print("Stuff in fconn is: {}".format(stuff))

def f2(parent_conn, parent_conn2):
    county = 0
    while True:
        time.sleep(2)
        currenttime = round(time.time())
        parent_conn2.send(currenttime)
        if county > 5: #send something to the consumer once in awhile so we know it's alive
            parent_conn.put(currenttime)
            county = 0
        county += 1
            
if __name__ == '__main__':
    parent_conn = Queue()
    parent_conn2, child_conn2 = Pipe()
    p = Process(target=f, args=(parent_conn,))
    p.start()
    p2 = Process(target=f2, args=(parent_conn, parent_conn2,))
    p2.start()
    start_server = websockets.serve(
            functools.partial(handler, parent_conn=parent_conn,
            child_conn2=child_conn2),
            '127.0.0.1', 8765)
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()

    p.join()
    p2.join()
```

**Comment by aaugustin** [comment]
I'm sorry, I don't really understand what you're doing with pipes, etc. I can't help you there.

**Comment by chmedly** [comment]
The pipes are how I eventually intend to pass data to and from the websockets section of my code.  I stripped it down and then face palmed when I realized that the multiprocessing pipes I was using were blocking and cannot be awaited. [see -- message = child_conn2.recv() --] So I rewrote a simplified version this way using an asyncio queue and it works:  

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import asyncio
import websockets

async def consumer_handler(websocket):
    global glob_message
    while True:
        message = await websocket.recv()
        await glob_message.put(message)
        print("this went in glob_message: {}".format(message))

async def producer_handler(websocket):
    global glob_message
    while True:
        message = await glob_message.get()
        await websocket.send(message)

async def handler(websocket, path):
    producer_task = asyncio.ensure_future(producer_handler(websocket))
    consumer_task = asyncio.ensure_future(consumer_handler(websocket))
    done, pending = await asyncio.wait(
        [consumer_task, producer_task],
        return_when=asyncio.FIRST_COMPLETED,
    )

    for task in pending:
        task.cancel()

if __name__ == '__main__':
    glob_message = asyncio.Queue()
    start_server = websockets.serve(
            handler,
            '127.0.0.1', 8765)
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()  
```
Lastly, I found that I can still use multiprocessing and the necessary pipes and queues by using the aioprocessing module.  It provides awaitable multiprocessing queues and pipes.  
Thank you for all your help.

**Comment by shalakhin** [comment]
Would be great if there will be some example of the consumer method.

```python
async def consumer_handler(websocket, path):
    async for message in websocket:
        await consumer(message)
```

here `consumer` is not clear. What should be there?

**Comment by shalakhin** [comment]
here it is not clear as well:

```python
async def producer_handler(websocket, path):
    while True:
        message = await producer()
        await websocket.send(message)
```

any example of `producer()` implementation? Without that example is not clear

**Comment by aaugustin** [comment]
`consumer()` and `producer()` implement your system's logic.

`consumer()` does something with messages received on the connection.

`producer()` generates messages to send on the connection.

**Comment by overthrowrobotics** [comment]
I'm struggling with this consumer and producer example too. In this example a method is needed called 
async def consumer() but how does it send messages back to consumer_handler? Does it just do a return with a string? 

`async def consumer():
     return "some string"`

**Comment by aaugustin** [comment]
Yes.

**Comment by juntiedt2** [comment]
I got my webserver with producer and consumer working

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import asyncio
import websockets
import datetime

async def consumer(message): 
    print("consumer: ", message)

async def producer():
    now = datetime.datetime.utcnow().isoformat() + 'Z'
    return (now)


async def consumer_handler(websocket):
    while True:
        async for message in websocket:
            #print("this went in glob_message: {}".format(message))            
            await consumer(message)    #global glob_message

async def producer_handler(websocket):
    #global glob_message
    while True:
        message = await producer()
        print("producer: ", message)
        await websocket.send(message)
        await asyncio.sleep(5.0)         

async def handler(websocket, path):
    producer_task = asyncio.ensure_future(producer_handler(websocket))
    consumer_task = asyncio.ensure_future(consumer_handler(websocket))
    done, pending = await asyncio.wait(
        [consumer_task, producer_task],
        return_when=asyncio.ALL_COMPLETED,
    )

    for task in pending:
        task.cancel()

if __name__ == '__main__':
    glob_message = asyncio.Queue()
    start_server = websockets.serve(handler, '127.0.0.1', 5678)
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever() 
```
my index.html echoing back to the server

```
<!DOCTYPE html>
<html>
    <head>
        <title>WebSocket demo</title>
    </head>
    <body>
        <script>
            var ws = new WebSocket("ws://127.0.0.1:5678/"),
                messages = document.createElement('ul');
            ws.onmessage = function (event) {
                var messages = document.getElementsByTagName('ul')[0],
                    message = document.createElement('li'),
                    content = document.createTextNode(event.data);
                message.appendChild(content);
                messages.appendChild(message);
                console.log(event.data);
                ws.send(event.data);
            };
            document.body.appendChild(messages);
        </script>
    </body>
</html>
```
now I want to read from asyncio_redis from which I got the following example

```
#!/usr/bin/env python
"""
Simple example that sets a key, and retrieves it again.
"""
import asyncio
from asyncio_redis import RedisProtocol

if __name__ == '__main__':
    loop = asyncio.get_event_loop()

    def run():
        # Create connection
        transport, protocol = yield from loop.create_connection(RedisProtocol, 'localhost', 6379)

        # Set a key
        yield from protocol.set('key', 'value')

        # Retrieve a key
        result = yield from protocol.get('key')

        # Print result
        print ('Succeeded', result == 'value')

        transport.close()

    loop.run_until_complete(run())
```
how can I integrate redis protokol.get(key) into my producer function?
I am struggling with putting it into the event-loop or adding it as a task.
Any help very much appreciated.

**Comment by elmahdy-intake37** [comment]
I need some help in WebSockets, please?

**Comment by carlos54** [comment]
Server side :
`
import asyncio
import websockets
import datetime
import random
import secrets
import collections
from threading import Thread
    
ws_message_queue = collections.deque(maxlen=100) 

async def consumer_handler(websocket):
    while True:
        async for message in websocket:       
            print("api websocket consume message : ", message)

async def producer_handler(websocket):
    while True:
        if len(ws_message_queue) > 0 :
            message = ws_message_queue.pop()
            await websocket.send(message)
            print(f"api websocket produce notification : {message}")     
        await asyncio.sleep(2)         

async def handler(websocket, path):
    producer_task = asyncio.ensure_future(producer_handler(websocket))
    consumer_task = asyncio.ensure_future(consumer_handler(websocket))
    done, pending = await asyncio.wait([consumer_task, producer_task],
        return_when=asyncio.ALL_COMPLETED,
    )
    for task in pending:
        task.cancel()

def run_ws_in_loop(loop, server):
    print("ws start websockert server in new thread")
    loop.run_until_complete(server)
    loop.run_forever()
          

#-----------------------------------------------------
async def simulation_api_mergetask():
    complexity = random.randint(3,10)
    # print(f'job work time estimation...{complexity}!')
    await asyncio.sleep(complexity)
    return secrets.token_hex(8)

async def simulation_api_main():
    print("start service")
    while True: #random.randint(1,100) <= 99:
        try:
            idjob = await asyncio.wait_for(simulation_api_mergetask(), timeout=7)
            ws_message_queue.appendleft(f"job done {idjob}")
        except asyncio.TimeoutError:
            print('ouups timeout...')
    print("stop service")

if __name__ == '__main__':
    ws_loop = asyncio.new_event_loop()
    ws_server = websockets.serve(handler, '127.0.0.1', 5678, loop=ws_loop)
    t = Thread(target=run_ws_in_loop, args=(ws_loop, ws_server))
    t.start()
    
    main_loop = asyncio.get_event_loop()
    main_loop.run_until_complete(simulation_api_main())
`

Client side :
`
import asyncio
import websockets

async def lisen_ws_api():
    uri = "ws://127.0.0.1:5678"
    async with websockets.connect(uri) as websocket:
        while True:
            new_message = await websocket.recv()
            print(f"server api say : {new_message}")

asyncio.get_event_loop().run_until_complete(lisen_ws_api())`
