### ISSUE TITLE
http.py uncaught exceptions

### ISSUE THREAD

**Issue by garrett4** [aaugustin/websockets#157]
The def read_line(stream): function keeps failing for uncaught exceptions. I made a fix on my install to get rid of it. The should be something like below. There was also a byte code error with .endswith.

```
def read_line(stream):
    """
    Read a single line from ``stream``.

    """
    try:
        line = yield from stream.readline()
    except:
        line = str("")
    if len(line) > MAX_LINE:
        raise ValueError("Line too long")
    if not line.endswith('\r\n'):
        raise ValueError("Line without CRLF")
    return line
```

**Comment by RemiCardona** [comment]
Do you have a test case so that we can try and reproduce it locally ?

Thanks

**Comment by garrett4** [comment]
I'll see what I can do. I found the problem in a base install of the Home Assistant Raspberry Pi all in one image:
https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/

**Comment by aaugustin** [comment]
Per PEP 20, "errors shouldn't pass silently".

Furthermore a bare except is a bad practice.

Generally speaking a function shouldn't swallow exceptions it cannot handle usefully.
