### ISSUE TITLE
Would I need to defensively call send() for multiple clients?

### ISSUE THREAD

**Issue by jamesstidard** [aaugustin/websockets#165]
I have created a simple chat room based on the examples on the repo. Heres the [gist](https://gist.github.com/jamesstidard/2a38ffeff8861c708562f94b84b2137f).

Am I being too defensive by suppressing `websockets.exceptions.ConnectionClosed` in the [broadcast function](https://gist.github.com/jamesstidard/2a38ffeff8861c708562f94b84b2137f#file-websocket_chat_server-py-L19)?

I remove clients from the set in the main `while True` loop but I don't think you can reason that the client will always be removed before another client tries to send them a message. Is that right?

Thanks

**Comment by RemiCardona** [comment]
> Am I being too defensive by suppressing websockets.exceptions.ConnectionClosed in the broadcast function?

Not at all. You can get `ConnectionClosed` or any other `OSError` exceptions anytime you get near a socket (the fact that it's managed with `asyncio` is irrelevant). So you _have_ to be defensive if you want your chat program to stay up.

As for the order of operations (clients coming and going), it's quite simple really: hope for the best, plan for the worst. Your gist seems to do mostly that, except that I would recommend dropping gone client from `connected` in `broadcast()` too. No reason to keep them around, but it's a minor improvement as they will most likely get dropped at the next loop round when `recv()` is called.

HTH

**Comment by jamesstidard** [comment]
@RemiCardona Ah ok, great. Not going mad then. Thanks for the quick response and your work on the project.
