### ISSUE TITLE
Timeout on `recv` = dropped messages

### ISSUE THREAD

**Issue by rr-** [aaugustin/websockets#166]
Scenario:

1. I use the example from the documentation with both async consumer and async producer.
2. I also run an async UI, and to let it execute in "parallel", I add `timeout=` to `asyncio.wait`.
3. If I set `timeout` to reasonable 0.1 s, a small percent of packets from the server doesn't find its way to the `consumer` task. The lower timeout I set, the higher odds that the message will be dropped.

The issue gets more apparent if I quickly spam multiple packets.
What can I do?

It kind of sounds like https://github.com/python/asyncio/issues/343 (I'm using Python 3.6 though)

**Comment by rr-** [comment]
In the below examples, while I cannot reproduce the issue with a timeout such as 0.1, 0.001 is enough to trigger this behavior.

**server.py**

```python
#!/usr/bin/env python
import asyncio
import websockets

connected = set()

async def hello(websocket, path):
    global connected
    connected.add(websocket)
    try:
        while True:
            counter = await websocket.recv()
            print(counter)
            for client in connected:
                await client.send(counter)
    finally:
        connected.remove(websocket)
        for ws in connected:
            await ws.close()

start_server = websockets.serve(hello, 'localhost', 8765)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**client.py**

```python
#!/usr/bin/env python
import asyncio
import websockets
import sys

POLL_TIME = 0.001
messages_received = 0
messages_sent = 0

spam = '--spam' in sys.argv

async def producer() -> int:
    if not spam:
        # don't send anything (timeout > POLL_TIME)
        await asyncio.sleep(99999)
        assert False
    # always be on time (timeout < POLL_TIME)
    await asyncio.sleep(POLL_TIME / 2)
    global messages_sent
    messages_sent += 1
    return 'packet #%d' % messages_sent

async def consumer(message):
    global messages_received
    messages_received += 1
    print(message)

async def hello():
    async with websockets.connect('ws://localhost:8765') as websocket:
        while messages_received < 1000:
            listener_task = asyncio.ensure_future(websocket.recv())
            producer_task = asyncio.ensure_future(producer())
            done, pending = await asyncio.wait(
                [listener_task, producer_task],
                timeout=POLL_TIME,
                return_when=asyncio.FIRST_COMPLETED)

            if listener_task in done:
                r = listener_task.result()
                await consumer(r)
            else:
                listener_task.cancel()

            if producer_task in done:
                await websocket.send(producer_task.result())
            else:
                producer_task.cancel()

try:
    asyncio.get_event_loop().run_until_complete(hello())
finally:
    print('msgs sent: ', messages_sent)
    print('msgs received: ', messages_received)
```

I run the scripts like this:

1. `./server`
2. `./client` (it'll pick up the messages)
3. `./client --spam` (it'll send the messages)

`./client --spam` shows:

```
msgs sent:  1000
msgs received:  1000
```

whereas `./client` receives fewer messages:

```
msgs sent:  0
msgs received:  970
```

**Comment by aaugustin** [comment]
I believe this is a race condition, when a message is received between `asyncio.wait` and `listener_task.cancel`. This means it's a bug in the example, not in the library.

The example was simplified significantly, which has the side effect of eliminating this race condition, and means we can consider the bug in the example fixed.

Please reopen if you encounter the race condition within websockets itself.
