### ISSUE TITLE
Python 3.6 not installed on Travis CI environment

### ISSUE THREAD

**Issue by JCharante** [aaugustin/websockets#169]
From the [last test](https://travis-ci.org/aaugustin/websockets/builds/216015933), it seems python3.6/py36 isn't installed, while having been [added](https://github.com/aaugustin/websockets/commit/fd54f619769a5a07ad85d18152d3c1bf39dd5936) to tox.ini causing tests to fail.

**Comment by aaugustin** [comment]
Thanks for the heads up.

I never had a good experience with Travis CI, I think I'll remove it, and perhaps try Circle CI.

**Comment by aaugustin** [comment]
"Fixed" in 388bd4a.
