### ISSUE TITLE
websockets.http.read_response(stream), need more documentation for `stream`

### ISSUE THREAD

**Issue by TheMLGuy** [aaugustin/websockets#174]
Would be really helpful to document what is `stream` and what are possible inputs for it

**Comment by aaugustin** [comment]
In practice it's an `asyncio.StreamReader`.

In practice anything with a `readline` async method will work.

**Comment by aaugustin** [comment]
Documenting that it must be an `asyncio.StreamReader` seems all right, as it's the lowest level class I can find that provides a `readline` async method, and this allows us to make changes to the implementation without breaking the public API.
