### ISSUE TITLE
Remaining newline on the stream make connection close

### ISSUE THREAD

**Issue by maxux** [aaugustin/websockets#177]
Hello,

I don't know if it's a weird implementation on the server side (I don't have access to server code, it's some proprietary stuff), but when I try to make some websocket request to it, the library directly close the connection.

The reason is, the first frame received is incorrect because it contains `"\r\n"` and not a real websocket payload. During the `read_message` on the `http.py`, by reading again one time after the new line, communication works.

```
        if header_line == b'\r\n':
            yield from read_line(stream)
            break
```

I think it was normal to end the HTTP header with 2 \r\n, but it looks like it's not implemented like this on the code, any reason why ?

**Comment by aaugustin** [comment]
Apparently the server you're connecting to includes three \r\n:

- one that ends the last header
- one blank line that matches `if header_line == b'\r\n'`
- an extra line that you swallow with `yield from read_line(stream)`

I think that's wrong.

Did you manage to connect with another websockets client?

Can you point to a spec saying this is legal?

If you can answer these two questions positively, then I guess websockets will have to support that special case.

**Comment by maxux** [comment]
I don't know if it's legal, but using a web browser (Chromium or Safari), web socket works fine

**Comment by aaugustin** [comment]
This is so weird. Perhaps you could try capturing the traffic with Wireshark to see what happens exactly?

**Comment by maxux** [comment]
I did it. This is how I managed to find issue.
In my first try, the library just closed the connection and didn't get any reply. Using wireshark, the reply was correctly sent and perfectly decoded.

**Comment by maxux** [comment]
Here is the raw packet seen from wireshark. Honestly I don't have any clue how this should be managed from client-side.
https://clea.maxux.net/screenshots/27-04-17-223537.png

**Comment by maxux** [comment]
I tested 2 nodejs library, just to give it a try, and both of them fails too. Well I guess it's a server side issue and not a client fix to apply. I don't know how it works in a browser, but it definitively should not. You can close this one as won't fix :) Sorry.

**Comment by aaugustin** [comment]
OK. This is really weird. If you figure out what happens I'd love to know the details.
