### ISSUE TITLE
examples/client.py fails on second interaction

### ISSUE THREAD

**Issue by ebenolson** [aaugustin/websockets#183]
Error when entering a second name:

    websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.

Guessing the `while` and the context manager need to be switched?

**Comment by aaugustin** [comment]
It's an unintended change that was committed accidentally in a41c8310807af4de9b2275c685988b3cbcf01ae2.

Thanks for the heads up.
