### ISSUE TITLE
Consider using a proper HTTP implementation

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#19]
The HTTP parsing and generation code is very simple at this time.

It could be worth relying on an external library for these parts.

**Comment by aaugustin** [comment]
Consider https://github.com/Lukasa/pycohttpparser.

**Comment by aaugustin** [comment]
I'm scaling down my ambitions for this library.

**Comment by aaugustin** [comment]
Re-opening as I discovered h11, a small pure-Python HTTP parser "sans I/O".

**Comment by aaugustin** [comment]
Still unsure what problem this issue actually solves..

**Comment by cjerdonek** [comment]
Security maybe?

**Comment by aaugustin** [comment]
I'm working on replacing the stdlib's MIME parser with a bare-bones custom HTTP implementation. This seemed like the path of least effort.

**Comment by aaugustin** [comment]
Another reason for not relying on a full HTTP implementation: https://tools.ietf.org/html/rfc6455#section-1.7:

> The WebSocket Protocol is an independent TCP-based protocol.  Its
> only relationship to HTTP is that its handshake is interpreted by
> HTTP servers as an Upgrade request.
