### ISSUE TITLE
expose an asynchronous iterator API for consuming messages

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#192]
Given that one of the focuses of `websockets` is simplicity, it seems like it would make sense for `websockets` to expose an API that lets one consume messages using [asynchronous iterators and `async for`](https://www.python.org/dev/peps/pep-0492/#asynchronous-iterators-and-async-for), which were introduced in Python 3.5 via PEP 492.

This would let one replace the following boilerplate consumer pattern everywhere:

    async def handler(websocket, path):
        while True:
            message = await websocket.recv()
            # Do stuff.

with the following simpler and more elegant pattern:

    async def handler(websocket, path):
        async for message in receiving(websocket):
            # Do stuff.

The idea would be that the `websockets` library could expose the asynchronous iterator `receiving()` in the code above (or something very similar).

Python 3.6 lets one define such an iterator very simply, using asynchronous generators which were introduced by [PEP 525](https://www.python.org/dev/peps/pep-0525/).

It would look something like this:

    async def receiving(websocket):
        while True:
            yield await websocket.recv()

(It can also be defined more manually in earlier versions of Python.)

Maybe example code taking advantage of this pattern can be added to the docs even before such an API is added to websockets itself (or even if such an API is never added).

**Comment by aaugustin** [comment]
Yes this looks really cool.

The current API predates the introduction of iterators.

Could we take it as far as:

```
async for message in websocket:
    # do stuff with message
```

That would be damn cool.

**Comment by cjerdonek** [comment]
Thanks for being receptive. Seems likely that could work!

**Comment by aaugustin** [comment]
If you feel like submitting a pull request, perhaps you'll get commit access to merge it yourself :-) (after I review it)

**Comment by cjerdonek** [comment]
What version(s) of Python would the API initially need to support? Would >= Python 3.6 be okay, or is Python 3.5 also necessary?

**Comment by aaugustin** [comment]
Whatever floats your boat :-)

All you need is to document it properly, and make sure the library still imports properly on Python 3.3. Check out the hack for shipping code that uses Python 3.5+ syntax (await / async).

**Comment by cjerdonek** [comment]
I started work on this here using your same pattern / hack: PR #195

**Comment by aaugustin** [comment]
Looks good!
