### ISSUE TITLE
setup.py raises an error

### ISSUE THREAD

**Issue by mschnitzer** [aaugustin/websockets#196]
Hey,

I'm the maintainer of the `python3-websockets` package for the openSUSE distribution. I'm trying to update the package in our update channels to the newest version but I'm getting an error...

When I try to execute `python3 setup.py build` it raises the following error:
```
[   11s] + python3 setup.py build
[   11s] Traceback (most recent call last):
[   11s]   File "setup.py", line 11, in <module>
[   11s]     long_description = f.read()
[   11s]   File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
[   11s]     return codecs.ascii_decode(input, self.errors)[0]
[   11s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 467: ordinal not in range(128)
[   11s] error: Bad exit status from /var/tmp/rpm-tmp.e5TX0W (%build)
```

Do you know how I can fix this? It appears since version 3.3.

**Comment by cjerdonek** [comment]
It looks like this is the same as issue #171, which was fixed later after the release. I'm not 100% sure this will work, but you could try the following:

    $ PYTHONIOENCODING=utf8 python3 setup.py build

**Comment by aaugustin** [comment]
Indeed — one can't fix a release after the fact... Closing as a duplicate.
