### ISSUE TITLE
provide programmatic access to status code if client connection fails

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#198]
Currently, if [`client.connect()`](https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/client.py#L136) fails, there doesn't seem to be a programmatic way to get the HTTP status code when applicable.  For example, in the case of a 404, the following traceback occurs. The status code occurs in the error text but not otherwise:

    Traceback (most recent call last):
      ...
      File "/.../lib/python3.6/site-packages/websockets/py35/client.py", line 12, in __aenter__
        self.websocket = await self
      File "/.../lib/python3.6/site-packages/websockets/py35/client.py", line 19, in __await__
        return (yield from self.client)
      File "/.../lib/python3.6/site-packages/websockets/client.py", line 165, in connect
        extra_headers=extra_headers)
      File "/.../lib/python3.6/site-packages/websockets/client.py", line 83, in handshake
        raise InvalidHandshake("Bad status code: {}".format(status_code))
    websockets.exceptions.InvalidHandshake: Bad status code: 404

The relevant line of code is [here](https://github.com/aaugustin/websockets/blob/5d361a361a31ce19896dd0fb2c9dc684514e2a09/websockets/client.py#L124).

One possible solution would be to define an `HttpError` exception class that has a `status_code` attribute. This would be similar to [`urllib.error`'s `HTTPError` class](https://docs.python.org/3.6/library/urllib.error.html#urllib.error.HTTPError).

**Comment by aaugustin** [comment]
Yes, that part of the API isn't convenient. Your proposal works for me.

**Comment by cjerdonek** [comment]
I posted PR #209 for this.
