### ISSUE TITLE
Make WebSocketServer not inherit from asyncio.AbstractServer

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#203]
Currently, the code is a little misleading / confusing because [`WebSocketServer`](https://github.com/aaugustin/websockets/blob/b1d09a1b1c36215a59f6a630215ed15d4582b3a8/websockets/server.py#L312) inherits from `asyncio.AbstractServer`, but a `WebSocketServer` object `server` isn't actually an object returned by [`AbstractEventLoop.create_server()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_server).  That object is stored at `server.server`.

(That an `AbstractServer` is an object returned by `create_server()` is documented in CPython [here](https://github.com/python/cpython/blob/aa8d0a24694bea05061f1920ec3f944a9e6799d5/Lib/asyncio/events.py#L193).)

There are also a few places in the docs that could use a similar clarification.

For example, it would help if in the two places in the docs that describe the [`WebSocketServer.close()`](https://github.com/aaugustin/websockets/blob/b1d09a1b1c36215a59f6a630215ed15d4582b3a8/websockets/server.py#L346) method, it could also mention that the underlying `asyncio.AbstractServer` object is closed.

Another spot is in the [docstring for `serve()`](https://github.com/aaugustin/websockets/blob/b1d09a1b1c36215a59f6a630215ed15d4582b3a8/websockets/server.py#L398), where it says it returns an `asyncio.Server` object rather than a `WebSocketServer` object.

It also doesn't look like the code is using this fact. I did try changing `class WebSocketServer(asyncio.AbstractServer):` to `class WebSocketServer:`, and the tests still pass.

Maybe the right way to say it is that `WebSocketServer` shares an interface with `asyncio.AbstractServer`, if you want to emphasize the parallel (and the note can be added about `create_server()`'s not accepting a custom class).

I'm happy to file a PR.

**Comment by aaugustin** [comment]
Yes, that's probably good to clarify.

I've chosen to encapsulate rather than inherit because that felt cleaner. I don't remember any other reason.

**Comment by cjerdonek** [comment]
Cool, thanks!
