### ISSUE TITLE
Server is correctly responding to closing request from client

### ISSUE THREAD

**Issue by Somefive** [aaugustin/websockets#206]
I was trying to build server push application. While using websocket client based on Python and websocket client based on JavaScript, it seems that if they are trying to request to close the connection from the server built by websocket based on Python, this library cannot respond to the closing request correctly and can only wait until timeout.
Then I try to use nodejs to build the server and use the same clients and everything goes right.
So I guess this library's server side is not handling closing request from client side.

**Comment by cjerdonek** [comment]
Can you provide the code you're using on the client and server side (preferably just the relevant bits), and the error message you're seeing?

**Comment by Somefive** [comment]
```python
import asyncio
import websockets
import json
import time

async def hello(websocket, path):
	print("welcome")
	while True:
		time.sleep(1.5)
		await websocket.send(json.dumps({"type":"verbose","message":"verbose","timestamp":int(time.time()*1000)}))
		print("sent")
		websocket.recv()
	print("end")

start_server = websockets.serve(hello, 'localhost', 9050)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
This is the server code of Python which is causing problems.
```Javascript
var ws = require("nodejs-websocket")

var server = ws.createServer(function (conn) {
    console.log("New connection")
    var timer = setInterval(()=>{
    	conn.sendText(JSON.stringify({type:"verbose", message:"verbose", timestamp:new Date().getTime()}));
    	console.log("sent");
    }, 1500);
    conn.on("close", (code, reason) => {
	    console.log("Connection closed")
	    clearInterval(timer);
    })
}).listen(9050)
```
This is the server code which do not cause problems.
One of the test client code is written in Python using websocket as well.
```python
import asyncio
import websockets

async def hello():
	async with websockets.connect("ws://localhost:9050") as websocket:
		# name = input("What's your name?")
		# await websocket.send(name)
		# print("> %s" % name)
		# greeting = await websocket.recv()
		print(await websocket.recv())
		print(await websocket.recv())
		print(await websocket.recv())
		websocket.close()
		# print("< %s" % greeting)
		
asyncio.get_event_loop().run_until_complete(hello())

```
So when the program runs well (Using JS version as server), the server presents like
```
New connection
sent
sent
sent
Connection closed
```
And the client side it only wait several seconds to quit correctly.
However, when using server code with python version, the server continuously sending message even if the client asks to close the request and after tens of seconds, the client has already refused to receive message for a long time, the server find the connection broken and return errors with error_code 1006 which is not 1000 as the usual way.
```
welcome
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
sent
Error in connection handler
Traceback (most recent call last):
  File "/home/somefive/miniconda3/lib/python3.6/site-packages/websockets/protocol.py", line 571, in write_frame
    yield from self.writer.drain()
  File "/home/somefive/miniconda3/lib/python3.6/asyncio/streams.py", line 333, in drain
    yield from self._protocol._drain_helper()
  File "/home/somefive/miniconda3/lib/python3.6/asyncio/streams.py", line 204, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/somefive/miniconda3/lib/python3.6/site-packages/websockets/server.py", line 84, in handler
    yield from self.ws_handler(self, path)
  File "server.py", line 11, in hello
    await websocket.send(json.dumps({"type":"verbose","message":"haha","timestamp":int(time.time()*1000)}))
  File "/home/somefive/miniconda3/lib/python3.6/site-packages/websockets/protocol.py", line 320
```

**Comment by JCharante** [comment]
@Somefive I believe that you are supposed to wrap the while statement in a try catch block.

```
async def hello(websocket, path):
	print("welcome")
	try:
		while True:
			time.sleep(1.5)  # should really be using asyncio's sleep to not block the thread
			await websocket.send(json.dumps({"type":"verbose","message":"verbose","timestamp":int(time.time()*1000)}))
			print("sent")
			print(await websocket.recv())  # Will not send another message until the server receives a message
	finally:
		print("end")
```

**Comment by Somefive** [comment]
@JCharante 
Yes, try - catch could solve the problem. 
However, I still think the proper way to handle a closing request from client side is not by raising an exception. Because, the client side is sending a closing request which means the state of client side is being CLOSING and waiting handshake from server side to close the connection and turn the state into CLOSED. Beside, the try - catch method still need to wait for tens of seconds to catch the connection lost exception however since the client side has already sent a formal request to close the connection, the connection should be closed as soon as the server received that instead of waiting for extra seconds and timeout.

**Comment by Somefive** [comment]
The client code I was actually trying to use is in JavaScript in web front end. I would like to see when user click on close connection button and the state is transformed to successfully CLOSED state so that I can pop up the reconnect window. But currently, it is keeping CLOSING state and hang up there for a long time and it is not an elegant way to destroy the websocket instance to shut down the connection.

**Comment by cjerdonek** [comment]
FWIW, from what I can tell it looks like the only test of the client closing the connection is [here](https://github.com/aaugustin/websockets/blob/b1d09a1b1c36215a59f6a630215ed15d4582b3a8/websockets/test_client_server.py#L367) (`test_client_closes_connection_before_handshake()`), for the connection being closed _before_ the handshake is done.

**Comment by aaugustin** [comment]
You wrote `websocket.recv()` in your example. You probably meant `await websocket.recv()`. That explains while the loop loops constantly.

You also use `time.sleep(1.5)` which is blocking, you want the non-blocking `await asyncio.sleep(1.5)` instead.

Making these changes should make the issue go away.

websockets catches exceptions in connections handlers and performs the closing handshake correctly.

NB - raising an exception when the handler is waiting on `websocket.recv()` is correct: no message will ever be received. Previously, `websocket.recv()` returned `None` in that case, but that required testing for that case after every call to `recv()`, which was needlessly verbose. An exception is a better way to handle this.

**Comment by Somefive** [comment]
I see, thank you very much!
