### ISSUE TITLE
Configure tox / coverage to report line numbers

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#212]
Currently, when coverage fails to meet 100% when running tox, the offending line numbers aren't reported. Patch forthcoming.

**Comment by cjerdonek** [comment]
I posted PR #213 for this.

**Comment by aaugustin** [comment]
Usually I open the HTML report for this.

**Comment by cjerdonek** [comment]
Addressed by PR #213 / 93f258fb455d68ec931a53dde3d138e27ed5ef72.
