### ISSUE TITLE
ConnectionError handling in WebSocketServerProtocol.handler() not tested

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#215]
When I comment out [this code](https://github.com/aaugustin/websockets/blob/93f258fb455d68ec931a53dde3d138e27ed5ef72/websockets/server.py#L73) in `WebSocketServerProtocol.handler()`, the tests still pass:

    try:
        path = yield from self.handshake(
            origins=self.origins, subprotocols=self.subprotocols,
            extra_headers=self.extra_headers)
    # except ConnectionError as exc:
    #     logger.debug(
    #         "Connection error in opening handshake", exc_info=True)
    #     raise
    except Exception as exc:
        if self._is_server_shutting_down(exc):
            response = ('HTTP/1.1 503 Service Unavailable\r\n\r\n'
                        'Server is shutting down.')
        elif isinstance(exc, InvalidOrigin):
            response = 'HTTP/1.1 403 Forbidden\r\n\r\n' + str(exc)
        elif isinstance(exc, InvalidHandshake):
            response = 'HTTP/1.1 400 Bad Request\r\n\r\n' + str(exc)
        else:
            logger.warning("Error in opening handshake", exc_info=True)
            response = ('HTTP/1.1 500 Internal Server Error\r\n\r\n'
                        'See server log for more information.')
        self.writer.write(response.encode())
        raise

Is handling `ConnectionError` actually needed here? If so, the desired behavior should be tested.

I noticed this when I was working on PR #202.

**Comment by cjerdonek** [comment]
I added PR #217 for this.

**Comment by aaugustin** [comment]
Hu, right, I was sloppy on tests... I could get away with this until you started double-checking my work :-)

**Comment by cjerdonek** [comment]
:)

**Comment by aaugustin** [comment]
I took the time to review the PR this morning and it occurred to me that the test logic could be simplified.

The `WriteCollectingProtocol` in #217 does three things:

1. inject an arbitrary exception in `handshake()` (which was previously achieved with a `@unittest.mock.patch`)
2. track writes made by the protocol
3. track the exception raised by the client when it starts

Another `@unittest.mock.patch` allows handling 2. more consistently with the remainer of the file, as shown in #280.

#217 also added a test for a situation that is already tested `test_server_error_in_handshake`. It's best not to test two different situations in a single test method.
