### ISSUE TITLE
Rename serve()'s klass to reflect that it can be a function

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#216]
I encountered a situation where it would be somewhat awkward to pass a class to `websockets.serve()` as the `klass` argument and would be more natural to pass a function.  The use case is when subclassing `WebSocketServerProtocol` and wanting to set custom instance attributes to values that are determined at runtime.

This would be similar to (but not quite the same as) the following note in Python's [`AbstractEventLoop.create_connection()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_connection) docs:

> Note: _protocol\_factory_ can be any kind of callable, not necessarily a class. For example, if you want to use a pre-created protocol instance, you can pass `lambda: my_protocol`.

**Comment by aaugustin** [comment]
Sure, go ahead!

**Comment by cjerdonek** [comment]
Will do, thanks! Would you be open to me renaming the argument in the same patch to reflect that klass need not be a class? The main issue I see would be backwards compatibility. Or that can be done later (also see a related minor issue I will be filing shortly ).

**Comment by aaugustin** [comment]
You can rename the argument to `protocol_factory` (good riddance `klass`, you were ugly) and add a backwards-compatibility shim.

That shim would be:
- mentioned in the changelog
- not mentioned in the API docs
- not scheduled for deprecation

**Comment by aaugustin** [comment]
See `legacy_recv` for a very similar case.

**Comment by cjerdonek** [comment]
Thinking more about your comment, do you think `protocol_factory` could cause confusion since it's not the same as the `protocol_factory` passed to [`AbstractEventLoop.create_server()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_server) (and has a different signature)?

In the asyncio docs, `protocol_factory` is called without arguments. But in this case, this "factory" is passed a number of keyword arguments and is used by `serve()` to create a `protocol_factory`.

**Comment by cjerdonek** [comment]
To avoid confusion, `create_protocol` maybe?

**Comment by aaugustin** [comment]
No very strong feelings here. Go for `create_protocol` if you prefer!

**Comment by cjerdonek** [comment]
I posted PR #236 for this.

**Comment by cjerdonek** [comment]
Closed by PR #236.
