### ISSUE TITLE
Allow custom arguments to EventLoop.create_connection to support proxies / custom transport

### ISSUE THREAD

**Issue by FraMecca** [aaugustin/websockets#221]
As specified [here](https://docs.python.org/3/library/asyncio-eventloop.html#creating-connections) loop.create_connection (of client.py:191) supports a custom socket for transport.

This would allow, for example, websockets over TOR provided that I open a socket to a TOR domain indipendently from your library.

Even if you provide **kwds in the function call, it is not valid because as the docs specifies if a socket is given explicitely,  none of host, port, family, proto, flags and local_addr should be specified.

If you want I can provide a possible workaround but I don't know about the other legitimate use cases of **kwds in loop.create_connection.

**Comment by aaugustin** [comment]
Thanks for the bug report.

Would you like to try submitting a pull request?

I believe it should look like this:

```
host = wsuri.host if kwds.get('sock') is None else None
port = wsuri.port if kwds.get('sock') is None else None
transport, protocol = yield from loop.create_connection(
    factory, host, port, **kwds)
```

I'm not really in a position to test this change, but if it works for you, I'm happy to merge it.
