### ISSUE TITLE
Measure coverage of C code

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#222]
@mayeut has been working on this: see https://github.com/aaugustin/websockets/pull/211#issuecomment-317249971 for details and recover the corresponding bits from that PR.

**Comment by mayeut** [comment]
There are multiple options for this:

1. Same as #211 for `tox.ini`. It lacks validation with a `--fail-under` like option. I simplified the one from #211 for Unix only in mayeut/websockets@9163a4786fa7e693a1bd2511a3e4356e70081d1c
2. Use CI to collect coverage information & validate PRs. I implemented this using [travis-ci](https://travis-ci.org/mayeut/websockets/builds/260170245) & [codecov](https://codecov.io/gh/mayeut/websockets/tree/coverage/websockets) in mayeut/websockets@55f5a67653479eabea88d36ce1aad554cfb7e29e and mayeut/websockets@ea7491dc2e48eaec07d556c7a530adb7d6f4211d (this second commit is to get 100% coverage on C extension)
3. A combination of both
4. Other ?

**Comment by aaugustin** [comment]
Right now I'm using Circle CI for running tox on PRs. I recently discovered that it only works for PRs from branches committed to this repo, not from branches in forks. I'm pretty sure that's a matter of configuration; I haven't looked into it.

I switched from Travis CI to Circle CI because I have generally had a very poor experience with Travis CI, mainly with random failures. Circle CI is easier to setup and more reliable in my experience. This isn't a deal breaker, but even if we build wheels on Travis CI (because that's what cibuildwheel supports) I'd rather keep Circle CI as our primary CI service.

I need to think a bit about CodeCov. It seems a bit annoying to depend on CI + a third-party service to validate coverage. Of course, if the alternative is "not validating coverage at all", it's still an improvement...

**Comment by aaugustin** [comment]
Let's add CodeCov.

It's fine if only Python code is covered. I understand what the `bytesnullhook` in https://github.com/mayeut/websockets/commit/ea7491dc2e48eaec07d556c7a530adb7d6f4211d does and I don't want to maintain that in this repository.

**Comment by aaugustin** [comment]
(CodeCov is a bit orthogonal to the original issue here.)

**Comment by mayeut** [comment]
Yes, the `bytesnullhook` is a bit overkill. I kept it in a separate commit for this reason exactly. It was more some experimenting than something I want to add. I thought of doing helpers as a package in PyPI for this (even created a project for it) but the simple fact that a cpython recompilation is needed kind of kill it anyway.
The fact is that 100% coverage is nice to be able to easily add a `--fail-under 100` on tools supporting it (which is not the case of gcovr for now). Anything other than 100% will move at some point. Anyway, 100% line coverage (as opposed to branch coverage) is easy to do once needed for the C code here.

**Comment by aaugustin** [comment]
Given that:

- we have only 130 lines of C code at this time;
- it never changed and I don't expect it to change often in the future;
- I understand the implementation but I don't feel very capable of or interested in maintaining it;
- I'm not looking forwards to debugging C code coverage issues in CI — debugging wheel generation issues is annoying enough;

I'm going to give up on rewieving and merging the PR :-( Thanks for your work and sorry.

I'm keeping it in mind and will revive it in case we add more C code e.g. to optimize HTTP header parsing (God help us!)
