### ISSUE TITLE
Server shutdown on windows?

### ISSUE THREAD

**Issue by Ball-Man** [aaugustin/websockets#228]
The given shutdown example works fine for linux systems, but raises a not implemented exception(signal handler). Now, i'd like to close the server in a safe way; any suggestions?

**Comment by aaugustin** [comment]
Yes, that's why the documentation says:

> On Unix systems, shutdown is usually triggered by sending a signal.

I'm not going to be able to help much because I don't know anything about Windows.

There was some discussion here: https://github.com/aaugustin/websockets/issues/124#issuecomment-253951579
