### ISSUE TITLE
InvalidHandshake: Malformed HTTP message

### ISSUE THREAD

**Issue by yudevit** [aaugustin/websockets#234]
Hello,

I keep running into an error trying to make a websocket connection.

I don't have a lot of experience with socket programming in python so I may as well be doing something wrong here.

I use Python 3.6 and the websockets version is 3.3.

Below is the error I receive:

> Traceback (most recent call last):
>   File "C:\Program Files\Python36\lib\site-packages\websockets\client.py", line 79, in handshake
>     status_code, headers = yield from read_response(self.reader)
>   File "C:\Program Files\Python36\lib\site-packages\websockets\http.py", line 65, in read_response
>     status_line, headers = yield from read_message(stream)
>   File "C:\Program Files\Python36\lib\site-packages\websockets\http.py", line 83, in read_message
>     start_line = yield from read_line(stream)
>   File "C:\Program Files\Python36\lib\site-packages\websockets\http.py", line 107, in read_line
>     raise ValueError("Line without CRLF")
> ValueError: Line without CRLF
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\[User]\PycharmProjects\[MyProject]\WebsocketConnection.py", line 13, in <module>
>     asyncio.get_event_loop().run_until_complete(hello())
>   File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
>     return future.result()
>   File "C:\Users\[User]\PycharmProjects\[MyProject]\WebsocketConnection.py", line 5, in hello
>     async with websockets.connect('wss://streamer.cryptocompare.com') as websocket:
>   File "C:\Program Files\Python36\lib\site-packages\websockets\py35\client.py", line 12, in __aenter__
>     self.websocket = await self
>   File "C:\Program Files\Python36\lib\site-packages\websockets\py35\client.py", line 19, in __await__
>     return (yield from self.client)
>   File "C:\Program Files\Python36\lib\site-packages\websockets\client.py", line 165, in connect
>     extra_headers=extra_headers)
>   File "C:\Program Files\Python36\lib\site-packages\websockets\client.py", line 81, in handshake
>     raise InvalidHandshake("Malformed HTTP message") from exc
> websockets.exceptions.InvalidHandshake: Malformed HTTP message

The code I use is the one from the official doc with changes to the _host_ and the _message_ content that I try to send:

```
async def hello():
async with websockets.connect('wss://streamer.cryptocompare.com') as websocket:
        name = input("[0~Poloniex~BTC~USD]")
        await websocket.send(name)
        print("> {}".format(name))

        greeting = await websocket.recv()
        print("< {}".format(greeting))

asyncio.get_event_loop().run_until_complete(hello())
```
Taken the nature of the error I tried converting the message to json and removing the square brackets but the error remained unchanged.

**Comment by aaugustin** [comment]
I don't think there's a WebSocket server at this URL.

Here's what I'm getting in a browser:

```
>> var ws = new WebSocket('wss://streamer.cryptocompare.com')
<- undefined
 x  Firefox can’t establish a connection to the server at wss://streamer.cryptocompare.com/.
```

**Comment by aaugustin** [comment]
Related: #494.
