### ISSUE TITLE
Document the possibility to call send() and recv() concurrently

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#238]
It's possible this question is a non-issue or the question has an obvious answer, but I'm wondering what requirements the API has, if any, around the extent to which calls to `send()` and `recv()` need to be "synchronized."

By this I mean things like: are calls to `send()` and `recv()` allowed to be concurrent? Similarly, is it permissible for multiple `send()` or multiple `recv()` calls to be concurrent?  If there are any limitations, it might be worth noting / discussing them in the documentation.

**Comment by aaugustin** [comment]
You can `send()` concurrently — we fixed a bug that prevented it, which was actually a bug in asyncio: `drain()` couldn't be called concurrently.

Technically you may be able `recv()` concurrently. In practice that's a bad idea, because there's no guarantee on which one of the two callers will get the message.

I'm open to adding some documentation (after making some quick tests to confirm the behavior).

**Comment by cjerdonek** [comment]
Good point that there shouldn't really be a need for concurrent `recv()`'s. The third combination is concurrent `send()`'s and `recv()`'s. How about that one?

I agree some tests would be worth adding. Note that they may not provide a full guarantee though. Without looking at the code, I'm guessing there are probably multiple possible branch points and orderings. One value in documenting it is that it says what the code is supposed to do, so people would know what they should be able to rely on and whether to file bugs, etc, as opposed to it being undefined behavior.

**Comment by aaugustin** [comment]
`send()` and `recv()` are largely independent from one another.

We didn't discuss `ping()` and `pong()`. They're also independent from everything else. `await ws.ping()` (which waits for the corresponding pong) goes through a different path than `await ws.recv()`.

**Comment by cjerdonek** [comment]
Oh, yes, I remember seeing those too but didn't want to overwhelm with possibilities! :)

**Comment by aaugustin** [comment]
They aren't commonly used; let's leave them aside in this discussion.

**Comment by ssolari** [comment]
I figured this was a related question as it pertains to documentation and the independent handling of send() and recv().   A common use case for websockets is to push data to the client asynchronously, which may involve making calls to the websocket outside the original handler.   We are having problems understanding how to correctly clean up send() exceptions that originate outside the original call handler.  

The case is that we want to  push data from the server to the client at periodic intervals.   How might we appropriately clean up the websocket_handler when the client disconnects and a send() raises an exception outside the original handler?  Example below:

```

import asyncio
import uvloop
import websockets


class CustomWsClass(object):

    def __init__(self, loop):

        self._websockets = {}
        self.loop = loop
        self.loop.call_soon(lambda: asyncio.ensure_future(self._test_websockets()))

    async def websocket_handler(self, websocket, path):

        userid = None
        try:
            # request token from open websocket
            await websocket.send('request user')
            try:
                userid = await asyncio.wait_for(websocket.recv(), timeout=4)
            except asyncio.TimeoutError:
                return

            if userid not in self._websockets:
                self._websockets[userid] = set()
            self._websockets[userid].add(websocket)

            while True:
                await websocket.recv()
        finally:
            # disconnect websocket
            if userid in self._websockets:
                if websocket in self._websockets[userid]:
                    self._websockets[userid].remove(websocket)
                if len(self._websockets[userid]) == 0:
                    del self._websockets[userid]

    async def _test_websockets(self):

        for userid in self._websockets:

            bytes_to_send = b'hello world'  # await self.get_some_data(userid)
            remove_sockets = []
            for i, ws in enumerate(self._websockets[userid]):
                try:
                    await ws.send(bytes_to_send)
                except:
                    remove_sockets.append(ws)

            for ws in remove_sockets:
                # ? how to create exception in original websocket_handler ?
                self._websockets[userid].remove(ws)

        self.loop.call_later(20, lambda: asyncio.ensure_future(self._test_websockets()))


loop = uvloop.new_event_loop()
s = CustomWsClass(loop)
start_server = websockets.serve(s.websocket_handler, '127.0.0.1', 8080, loop=loop)
asyncio.get_event_loop().run_until_complete(start_server)
s.run_forever()
```

**Comment by ssolari** [comment]
Maybe the question was premature.  After some testing, it seems that the ```await websocket.recv()``` raises a ClosedConnection exception when the connection is closed.   Maybe the only question would be if that is eventually guaranteed then?

**Comment by aaugustin** [comment]
Yes, `recv()` will either return a message or raise `ConnectionClosed`.
