### ISSUE TITLE
Listen for websocket close on server side

### ISSUE THREAD

**Issue by eferdman** [aaugustin/websockets#243]
Is this possible using this websockets library and how would you suggest doing this?

I would like to be able to detect an onclose event from a specific client (ie the user closes the browser or navigates to another page) in order to clean up resources (in my case a redis connection) when a specific websocket connection closes. 

Here's what I have so far... I'm using websockets.exceptions.ConnectionClosed but is it possible to make an onclose handler instead?

```
import websockets
import asyncio
import asyncio_redis


# The producer coroutine
async def subscribe_to_redis():
    # Create connection
    connection = await asyncio_redis.Connection.create(host='localhost', port=6379)
    return connection


# web socket server pushing data to the browser
async def browser_server(websocket, path):
    conn = await subscribe_to_redis()

    # Create subscriber.
    subscriber = await conn.start_subscribe()

    # Subscribe to channel.
    await subscriber.subscribe(['our-channel'])

    try:
        while True:
            # Await published message.
            reply = await subscriber.next_published()

            print('Received: ', repr(reply.value), 'on channel', reply.channel)

            # send the published message to the websocket client
            await websocket.send(repr(reply.value))
    except websockets.exceptions.ConnectionClosed:
        print('Connection Closed!')


if __name__ == '__main__':
    # Boiler-plate for the websocket server, running on localhost, port 8765
    loop = asyncio.get_event_loop()
    loop.set_debug(True)
    ws_server = websockets.serve(browser_server, 'localhost', 5678)
    loop.run_until_complete(ws_server)
    loop.run_forever()
```

Thanks!

**Comment by aaugustin** [comment]
This library aims at providing a corountine-based API rather than a callback based API.

You may subclass WebSocketServerProtocol (see the docs for how to use a custom protocol subclass) and override [connection_lost](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseProtocol.connection_lost). Check the value of `self.close_code`. Note that this method will always be called, regardless of how the connection was closed.

**Comment by aaugustin** [comment]
As of version 7.0, you will be able to use `wait_closed` for this purpose.

```python
async def browser_server(websocket, path):
    closed = asyncio.ensure_future(websocket.wait_closed())
    closed.add_done_callback(lambda task: your_on_close_action())
```
