### ISSUE TITLE
Investigate support for `x-webkit-deflate-frame`

### ISSUE THREAD

**Issue by RouquinBlanc** [aaugustin/websockets#244]
Safari implements it's own alias of `permessage-deflate` called `x-webkit-deflate-frame`... It does pretty much the same (apparently).

Need to find a proper specification to review first and assess about implementing.

**Comment by RouquinBlanc** [comment]
seems to be their experimental implementation from 2012, and after that not much interest in switching to the standardized one:
https://bugs.webkit.org/show_bug.cgi?id=115504
...

**Comment by aaugustin** [comment]
I'm not really looking to work around Apple's laziness here... They have the money to `s/x-webkit-deflate-frame/permessage-deflate/` if they care about Safari's performance...
