### ISSUE TITLE
check log level before calling logger.debug()

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#246]
Since the contents of a frame can be large, it might be worth considering checking the log level in an if statement prior to calling `logger.debug()` in places like [this](https://github.com/aaugustin/websockets/blob/27e06981ff12421da3c2c0e05b6b4abbadcf9937/websockets/protocol.py#L548).

I believe calling [`logger.getEffectiveLevel()`](https://docs.python.org/3/library/logging.html#logging.Logger.getEffectiveLevel) will work for this (followed by the appropriate comparison).

**Comment by cjerdonek** [comment]
I'm closing this because I suspect the logging module doesn't interpolate the format string until after it knows it needs to be logged.

**Comment by aaugustin** [comment]
Yes, there's no performance issue.

However it would be useful to log only the first N bytes of the frame for readability, defaulting to something like 1024.

That constant could be a module-level variable so it can be overridden by monkey-patching (`websockets.DEBUG_FRAME_SIZE_LIMIT = 8192`).

**Comment by aaugustin** [comment]
Actually this would have a performance cost as it will cause a copy of every frame... Let's forget it.
