### ISSUE TITLE
include user-friendly meaning of status code in messages

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#249]
I think it would be helpful if, in cases where the websocket client or server states a numeric status code in messages to the user (e.g. log messages and exception messages), it could also include the English meaning of the code alongside.

For example, instead of the client raising an exception like this:

> websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1011, no reason.

it could raise something like this:

> websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1011 (Internal Server Error), no reason.

Something like this could be achieved somewhat automatically by using a data structure like an enum to represent status codes. Here is an example from Python's http module to illustrate what I mean (look at the `repr()` in particular):

    >>> from http import HTTPStatus
    >>> status = HTTPStatus.OK
    >>> print(status.name, status.value, repr(status))
    OK 200 <HTTPStatus.OK: 200>

There is already a [`CLOSE_CODES`](https://github.com/aaugustin/websockets/blob/27e06981ff12421da3c2c0e05b6b4abbadcf9937/websockets/framing.py#L35) dict in `framing.py`, but the mapping doesn't seem to be used anywhere (aside from the keys).

This issue is different from but related to issue #198 in that I'm not suggesting that the header include this text, but rather that the client code map the integer to its corresponding meaning after receiving the number.

This would be useful because it means that users of the websockets library won't need to look for all occurrences and apply a mapping like this themselves if they want to provide a friendlier developer experience (and it might not be possible in some cases if just a string message is provided).

**Comment by cjerdonek** [comment]
Note that `enum` [was added](https://docs.python.org/3/library/enum.html) in Python 3.4, so we would be able to use enums once issue #237 is addressed (dropping support for Python 3.3).

**Comment by aaugustin** [comment]
Yes, this is a good idea.
