### ISSUE TITLE
HTTP server returns 404 from Websocket request on valid websocket endpoint

### ISSUE THREAD

**Issue by Redrield** [aaugustin/websockets#250]
**The problem:**
    My HTTP server, written using the Ktor framework in Kotlin has a Websocket endpoint at /ws. When I try 
    to connect to it using this library, it returns a 404. I'm running on Manjaro Linux

**The solution:**
I found that a solution to the issue was as simple as changing Upgrade: WebSocket to Upgrade: websocket in the headers of the request. After that small change, it connects as usual and just works.

**Comment by cjerdonek** [comment]
Could this be a bug in that framework (perhaps [here](https://github.com/Kotlin/ktor/blob/29638b650a531248cb2b74e15799e35f70b8cdb3/ktor-features/ktor-websockets/src/org/jetbrains/ktor/websocket/Routing.kt#L13))?

[RFC 6455](https://tools.ietf.org/html/rfc6455) says in section 4.2.1. "Reading the Client's Opening Handshake":

> An |Upgrade| header field containing the value "websocket", treated as an ASCII case-insensitive value.

**Comment by cjerdonek** [comment]
It couldn't hurt to change it here, though. The same RFC also says in section 4.1. "Client Requirements":

> The request MUST contain an |Upgrade| header field whose value MUST include the "websocket" keyword.

This language doesn't include the case-insensitive qualifier though, so maybe changing to lowercase will be more likely to work with other servers.

**Comment by aaugustin** [comment]
Yes, let's change it to lowercase. Cool edge case :-)

**Comment by Redrield** [comment]
In the end it was actually a problem with the server framework, turns out. They've patched it, so this isn't a necessity for me anymore.

**Comment by aaugustin** [comment]
FTR the Ktor issue is https://github.com/Kotlin/ktor/issues/186 and the corresponding commit is https://github.com/Kotlin/ktor/commit/6330d036de9d1a58e4569cfc0d3451971c9773fe.

**Comment by cjerdonek** [comment]
This may be worth a code comment since the reason for lower-casing is
somewhat obscure and there is no test.

**Comment by aaugustin** [comment]
Damn, caught by the patrol again :-)

To be honest I didn't care enough to write a test... mostly because I don't think anyone will ever find a reason to change it back.

**Comment by cjerdonek** [comment]
:) Yeah, I wasn't demanding a test! I was just suggesting a code comment as an easy alternative (and in the absence of a test).
