### ISSUE TITLE
Allow setting user-agent

### ISSUE THREAD

**Issue by m1keil** [aaugustin/websockets#262]
At the moment it seems like user-agent is being set in handshake(). It would be really useful if a user of the library could set its own user-agent string.

Two ideas I have:
* Either creating new parameter to the connect function, or 
* Allowing **extra_headers** to override the default user-agent header

I think I can provide PR for either of these. Will you be open to any of these ideas?

Thanks!

**Comment by aaugustin** [comment]
Yes, you can make [this line](https://github.com/aaugustin/websockets/blob/96bcc64e9098ce6c1c3597deca05c8aaf7f03f2b/websockets/client.py#L234) execute only if `User-Agent` isn't set after processing `extra_headers` (which happens just above).

**Comment by m1keil** [comment]
Awesome! I'll provide a PR

**Comment by aaugustin** [comment]
Could you confirm the use case? Hiding information about the server software to increase security?

I'm just curious if there's another reason I missed when I hardcoded the user agent.

**Comment by m1keil** [comment]
I use websockets to develop an alternative client for an internal API at work. Having the ability to set the user-agent lets my client identify itself property.
Note I'm concerned about the user-agent of the client, not the server (I don't think the server uses connect(), right?)

**Comment by aaugustin** [comment]
Ah, right, we're talking about the client side here.

If you could make the same change for the server side while you're there — search for `set_header('Server', USER_AGENT)` in `websockets/server.py` — that would be perfect.

**Comment by aaugustin** [comment]
This will be configurable with an environment variable in version 13.0: https://github.com/python-websockets/websockets/commit/bbb316155a5aeb719f262873a5b29a98c19b25d9.

Please be aware that, if you are currently monkey-patching USER_AGENT, that will break in version 13.0. You will have to set the WEBSOCKETS_SERVER or WEBSOCKETS_USER_AGENT environment variable instead.
