### ISSUE TITLE
Unclear on how to use ping/pong mechanism

### ISSUE THREAD

**Issue by jacksonofalltrades** [aaugustin/websockets#268]
Documentation shows the API for these, but not sure how to use them.

I have a websocket server using the producer/consumer model. My server is talking to clients that are either in web browsers, iPhone apps, or test clients.

It looks like I can create a producer handler that calls websocket.ping(), but I'm unclear how to get a pong back to the python server from my JavaScript websocket connection that the websocket server will correctly interpret as a response to the ping.

Any help is greatly appreciated!

**Comment by aaugustin** [comment]
I would expect the browser to take care of replying to pings to pongs.

Your JavaScript code shouldn't handle this protocol-level mechanism.

Enable logging at the DEBUG level to see every frame and look for opcodes 9 and 10, which are ping and pong respectively.
