### ISSUE TITLE
Improve exception hierarchy, perhaps insert a root WebSocketException class

### ISSUE THREAD

**Issue by ncalexan** [aaugustin/websockets#270]
I see from https://github.com/aaugustin/websockets/blob/d37433902cc959b050925581d6e9bd361262e9be/websockets/exceptions.py#L11 that the `websockets` exception hierarchy is rooted at Python's `Exception` class.  It would be nice to be able to handle all `websockets` exceptions uniformly, like:

```python
try:
    ws.send(...)
except websockets.WebSocketException:
    ...
```

rather than have to enumerate the exception hierarchy.

**Comment by aaugustin** [comment]
Exceptions expected during the opening handshake (i.e. when calling `connect`) are covered by `InvalidHandshake`.

During the data transfer phase, the most relevant exception is `ConnectionClosed`. I'm not sure it makes sense to catch other exceptions such `PayloadTooBig` without either catching them specifically for their semantics, or catching all exceptions. This isn't Java (and it isn't `catch`, it's `except`); arbitrary exceptions are always possible.

I don't see the use case for giving a common base class to exceptions expected during the opening handshake and during the data transfer phase.

However, I'm sympathetic to improving the exception tree, which didn't age well. Unfortunately it's part of the public API so we need to be careful about changes.

**Comment by ncalexan** [comment]
> Exceptions expected during the opening handshake (i.e. when calling connect) are covered by InvalidHandshake.

OK.  I didn't see this hierarchy when I looked, partially 'cuz I _was_ trying to "catch them all" as part of a test program (while not swallowing arbitrary exceptions).  I think you're right, the hierarchy does allow for generic error catching -- once you know what applies where.  More below.
 
> During the data transfer phase, the most relevant exception is ConnectionClosed. I'm not sure it makes sense to catch other exceptions such PayloadTooBig without either catching them specifically for their semantics, or catching all exceptions. This isn't Java (and it isn't catch, it's except); arbitrary exceptions are always possible.

Heh -- I fixed my comment.  I write a lot of Python and a lot of Java, and a little JavaScript, and I've always disliked Python's non-standard `except` :)

> I don't see the use case for giving a common base class to exceptions expected during the opening handshake and during the data transfer phase.
> 
> However, I'm sympathetic to improving the exception tree, which didn't age well. Unfortunately it's part of the public API so we need to be careful about changes.

So, action items: it's not clear what exactly you mean by improving the exception tree.  Should this ticket be duped to an existing ticket to track that work?  Should we morph it into tracking that work?  For my part, I'd morph this into a documentation ticket: I'd add a module comment about the hierarchy, and move your notes about specific functions into the class comments.

Thanks for the prompt triage!

**Comment by aaugustin** [comment]
It isn't clear to me either :-)

I'd like to write down the tree of exceptions, figure out in which circumstances they are raised exactly, and make it more consistent, perhaps accepting some backwards incompatibilities in the process.

**Comment by aaugustin** [comment]
See also #285.

**Comment by aaugustin** [comment]
The current exception tree is:

```
Exception
+-- InvalidHandshake
|   +-- AbortHandshake
|   +-- InvalidMessage
|   +-- InvalidHeader
|   +-- InvalidOrigin
|   +-- InvalidStatusCode
|   +-- NegotiationError
|       +-- InvalidParameterName
|       +-- InvalidParameterValue
|       +-- DuplicateParameter
+-- InvalidState
|   +-- ConnectionClosed
+-- InvalidURI
+-- PayloadTooBig
+-- WebSocketProtocolError
```
