### ISSUE TITLE
How to pass additional args to server function in Basic example file?

### ISSUE THREAD

**Issue by chmedly** [aaugustin/websockets#271]
I must be missing something simple here.  I'm looking at the Basic server and client examples in the docs but it's not clear to me how to pass additional arguments to the 'hello' function.  Here's a piece of code where I want to pass a multiprocessing pipe endpoint to the function.  It doesn't work but I think illustrates what I'm trying to do.  

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time
import asyncio
import websockets
from multiprocessing import Process, Pipe

async def hello(websocket, path, parent_conn):
    name = await websocket.recv()
    parent_conn.send(name)
   
def f(conn):
    while True:
        if conn.poll():
            stuff = conn.recv()
            print("Stuff in fconn is: {}".format(stuff))
            
if __name__ == '__main__':
    parent_conn, child_conn = Pipe()
    p = Process(target=f, args=(child_conn,))
    p.start()
    start_server = websockets.serve(hello,
                            '127.0.0.1', 8765, parent_conn)
    
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()

```

**Comment by cjerdonek** [comment]
I'm going off memory, but I'm pretty sure you can accomplish the same end goal by subclassing `WebSocketServerProtocol` and adding custom instance attributes. You might also want to look at the following issue, where I suggest that another approach should be possible (namely subclassing `WebSocketServer`, which would be more natural in certain circumstances): https://github.com/aaugustin/websockets/issues/230

**Comment by aaugustin** [comment]
Does this work?

```
import functools
start_server = websockets.serve(
    functools.partial(hello, parent_conn=parent_conn),
    '127.0.0.1', 8765)
```

**Comment by chmedly** [comment]
to aaugustin:
Why yes it does!  
Hmm, I need to read the partial docs again.  It's like magic...
btw I put the parent_conn at the end of the args like so:

`async def hello(websocket, path, parent_conn):`

Can you add this to the getting started section?  It was one of the first questions I had and I went through all of the closed "issues" looking for clues about this.

**Comment by chmedly** [comment]
Nope.  It does matter where I put the argument.  Putting it ahead of websocket or even in between give me this error. 

`TypeError: hello() got multiple values for argument 'parent_conn'`

**Comment by aaugustin** [comment]
`websockets` always passes 2 positional arguments to `hello`: `websocket` and `path`.

`partial` can add:
- positional arguments at the beginning of the list of positional arguments: you can use this by defining `hello(parent_conn, websocket, parent)` and then passing `functools.partial(parent_conn)` to `serve`
- keyword arguments: this is what you did above, in that case the arguments need to be after `websocket` and `parent` in the definition of `hello`, else these arguments don't end up in the right locations.

I don't think this is hello-world material, however it's worth adding to the docs.

**Comment by JDeuce** [comment]
Looks like these docs added in 050a6ae eventually got removed in latest somehow.

Also there's an issue with them. The path argument was deprecated and some magic was added here: https://github.com/aaugustin/websockets/blob/668f320/src/websockets/legacy/server.py#L1123

When attempting to use a functools.partial with a simple 2 argument handler such as

    async def handler(websocket, my_extra_argument)
    
    ...

    websockets.serve(functools.partial(handler, my_extra_argument=...)
    
It will pass through that block and generate errors such as `handler() got multiple values for argument 'hack'`

The workaround for now is to avoid getting caught by that deprecation block which checks if your functions expects 2 arguments, by simply adding a third dummy argument

    async def handler(websocket, my_extra_argument, my_dummy_argument=None)
    

Maybe @aaugustin should reconsider the deprecation here for cases like this?

**Comment by aaugustin** [comment]
I think this is the same as #1095.
