### ISSUE TITLE
bad format exception websockets client crashes 

### ISSUE THREAD

**Issue by ta32** [aaugustin/websockets#279]
I used the example code to try and connect to this Connection URL: wss://ws.blockchain.info/inv
API described here https://blockchain.info/api/api_websocket

The client returns a 400 status code ( bad format exception ). 
```
websockets.exceptions.InvalidStatusCode: Status code not 101: 400
wsuri.resource_name = '/inv' ( when tracing the code) 
```

I cant see what i am doing wrong, because the equivalent code when I am using  this library https://github.com/websocket-client/websocket-client works....

I also tested the module against wss here http://websocket.org/echo.html and it work. The only difference is that there was no resource name.

**Comment by aaugustin** [comment]
This endpoint works for me:

```python
>>> import asyncio
>>> import websockets
>>> ws = asyncio.get_event_loop().run_until_complete(websockets.connect('wss://ws.blockchain.info/inv'))
>>> ws.state_name
'OPEN'
>>> asyncio.get_event_loop().run_until_complete(ws.send('{"op":"ping"}'))
>>> asyncio.get_event_loop().run_until_complete(ws.recv())
'{"op":"pong"}'
>>> asyncio.get_event_loop().run_until_complete(ws.close())
>>> ws.state_name
'CLOSED'
```

I can't see what you are doing wrong either because you didn't include the failing code in your bug report and my crystal ball is momentarily out of order.

**Comment by ta32** [comment]
Hi @aaugustin, i ran the code you pasted and it still did not work :(

```
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import websockets
>>> ws = asyncio.get_event_loop().run_until_complete(websockets.connect('wss://ws.blockchain.info/inv'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\client.py", line 215, in connect
    extra_headers=extra_headers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\websockets\client.py", line 125, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 400
```
Windows 10 64bit
python 3.6.2. I am using anaconda python
asyncio (3.4.3)
websockets (3.4)

What more information can i give you?

**Comment by aaugustin** [comment]
For some reason that server returns a "400 Bad Request" error code instead of accepting the connection.

You should review the documentation of the service to see in which circumstances they return that error.
