### ISSUE TITLE
Performence issue

### ISSUE THREAD

**Issue by chookapp** [aaugustin/websockets#283]
I've tried to do a simple stress test.
I opened a websocket from client to server and sent frames of 4096 bytes.
On my computer I got to ~50Mbps.
Increasing the frame size to 40960 didn't seem to change much.
Using a profiler I was able to find a possible issue.
The `utils.apply_mask` seems to use all of my CPU.

**Comment by chookapp** [comment]
I have raised a question on how to improve the performance in [stackoverflow](https://stackoverflow.com/questions/46540337/python-xoring-each-byte-in-bytes-in-the-most-efficient-way):

I applied the fix and now it is, at least, 3 times faster...

**Comment by cjerdonek** [comment]
Would it be worth adding the stress test to the repo for future reference? Are benchmarks already being stored somewhere?

**Comment by messense** [comment]
So you are using the pure Python version of `apply_mask`, did you try the [C version](https://github.com/aaugustin/websockets/pull/214)? BTW, there are binary wheels for them.

**Comment by chookapp** [comment]
Just for clarity: I'm running this on a Linux machine, I'm using python 3.5 and websockets version 3.4

@messense Not intentionally, but yes, my program seems to be using the pure python version of `apply_mask`. I did not do anything other that installing websockets using pip.
I was not aware of that pull request (that could have saved me some time :-)

**Comment by messense** [comment]
@chookapp Try upgrade your pip to latest version (`pip install -U pip`) then reinstall `websockets` (might need to clean pip cache first, usually located at `~/.cache/pip`), it should use the binary wheel automatically.

**Comment by chookapp** [comment]
Thanks.
Apparently my pip was indeed old. 
After re-installing the websockets I was able to push ~850mbps which is also my network capacity.
