### ISSUE TITLE
Make websocket state human-understandable

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#284]
Currently, when troubleshooting the state of a connection, if you log the "state" attribute, you just see a number like 1. It would be nice if this was something more human-understandable. The states are [here](https://github.com/aaugustin/websockets/blob/5ce75688f59b017c2f0d4efebff8e9022f0e3d67/websockets/protocol.py#L32):

    CONNECTING, OPEN, CLOSING, CLOSED = range(4)

This could be done with an enum.

**Comment by cjerdonek** [comment]
I see now that there is a `state_name` attribute, but it seems like an enum would be more elegant.

**Comment by aaugustin** [comment]
Yes, that would be a bit better.

Regarding backwards compatibility, I think the best solution would be to remove `state_name` —
 which is a public API — in the next major release.

We could also keep it but remove it from the documentation, it isn't bloating the code base :-)

**Comment by cjerdonek** [comment]
Yes, it could just delegate to self.state.name if self.state is changed to
an enum.

**Comment by cjerdonek** [comment]
By the way, are you collecting a list of possible breaking changes for the next major release somewhere so they aren't lost track of?

**Comment by aaugustin** [comment]
Not at this time... We could create an issue for that purpose.
