### ISSUE TITLE
ConnectionClosed subclass for normal closure

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#285]
I was thinking it would be a nice touch to add (and use) a `ConnectionClosed` subclass that corresponds to a normal closure (i.e. status code 1000).

This would make it easier for users to handle expected (normal) closures differently and more elegantly, namely without having to inspect the code attribute. For example, here is one place in the websockets code base that such a pattern could be used:

    try:
        while True:
            yield await self.recv()
    except ConnectionClosed as exc:
        if exc.code == 1000:
            return
        else:
            raise

Here is the code link:
https://github.com/aaugustin/websockets/blob/27549c4b390443b7504e937d4d974bd0855b4c7f/websockets/py36/protocol.py#L4

**Comment by aaugustin** [comment]
Yes, this is a good idea.

**Comment by aaugustin** [comment]
I think that 1001 should also be treated as a normal closure. That's the code browsers send when leaving a page.

I don't expect users to write an onbeforeunload event handler that closes explicitly the websocket connection.

**Comment by aaugustin** [comment]
Name proposal: `ConnectionClosedOK`?

**Comment by aaugustin** [comment]
Open questions

- [ ] Explain in the docs where `ConnectionClosed` is discussed?
- [ ] Add a complementary `ConnectionClosedError` exception?
