### ISSUE TITLE
Add Protocol.closed() property

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#286]
I think it would be useful to add a `closed()` property to `WebSocketCommonProtocol`, similar to the [`open()`](https://github.com/aaugustin/websockets/blob/27549c4b390443b7504e937d4d974bd0855b4c7f/websockets/protocol.py#L240) property. This would be useful, for example, for users who want to assert that a connection is closed, without having to separately look up and import the `CLOSED` constant and do an equality comparison.

**Comment by aaugustin** [comment]
Yeah, why not.

At this rate we'll add `closing()` soon...

**Comment by aaugustin** [comment]
Users could be puzzled if they encounter a situation where `not ws.open and not ws.closed` (because `ws.state == CLOSING`).
