### ISSUE TITLE
[Question] Compression Extensions Support

### ISSUE THREAD

**Issue by hktonylee** [aaugustin/websockets#289]
Sorry that I can't find any better place to ask question so I have to put it here.

The question is that is there any target date for the release of the compression extensions support? I only find the related code in the master branch but not in v3.4. If v3.4 already supports it, it will be awesome.

**Comment by aaugustin** [comment]
I haven't released a version that support compression yet.

I was planning to do it this week-end but #291 came up and I think it's a release blocker.
