### ISSUE TITLE
Render coroutines as such in generated docs

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#295]
This issue is a placeholder for the generated docs to auto-indicate which functions are coroutines. [This comment](https://github.com/aaugustin/websockets/issues/291#issuecomment-337836400) is where this first came up.

I believe there are at least two or three solutions commonly being used for this in async packages, as it's not natively built in to Sphinx yet.

**Comment by aaugustin** [comment]
Yes, that would be nice.

At this time, for lack of a better solution, I'm trying to spell out whether each API is a method or a coroutine.

**Comment by aaugustin** [comment]
Sphinx is likely going to gain this feauture: see https://github.com/sphinx-doc/sphinx/issues/4777, https://github.com/sphinx-doc/sphinx/pull/4847.

Let's wait for Sphinx to release that feature and RTD to update Sphinx to that version.

**Comment by njsmith** [comment]
FWIW, [sphinxcontrib-trio](https://sphinxcontrib-trio.readthedocs.io/en/latest/) is (I say not very modestly) easy to use, complete, tested, etc. It should just work, and despite the name it doesn't really care whether you're using trio.

**Comment by aaugustin** [comment]
Thanks for the tip!

(Also thanks for your blog posts — I'm an avid reader.)

**Comment by aaugustin** [comment]
It works.
