### ISSUE TITLE
allow and/or document how to run a single test

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#297]
I could be doing something wrong, but I wasn't able to run a single test using tox.

After searching online, when I changed a line in tox.ini to be the following, I was able to do it:

    python -m unittest {posargs}

Was I missing something to be able to do this without altering tox.ini?

**Comment by aaugustin** [comment]
I don't think you missed anything.

Feel free to commit that change!

**Comment by aaugustin** [comment]
(I usually run isolated tests with `python -m unittest ...`. I never tried 1

**Comment by cjerdonek** [comment]
That's a good point. I might have done that in the past but since forgot.

Do you have thoughts on where to put tips on how to run tests for now? A code comment in the tox.ini file? I don't think there's a contributing file yet.

**Comment by aaugustin** [comment]
There's `docs/contributing.rst`, which could use some details...
