### ISSUE TITLE
Release version 4.0

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#298]
We added support for compression and a bunch of other improvements since 3.4. I think this is a good time to release v4.0 (all the more since I've had less time for websockets since a few weeks and I'm not sure that'll improve going forwards).

@cjerdonek @homerunisgood @mayeut Is there anything you'd like to get into that release? If so, please make sure there's an issue or PR tagged with the 4.0 milestone. A major release is a good time to make backwards-incompatible changes (even though we're trying to avoid these in general).

**Comment by aaugustin** [comment]
I'm planning to merge #301, #302 and #303 before making the release. Anything else?

**Comment by cjerdonek** [comment]
Not that I can think of. Thanks for all your work!! 👍

**Comment by RouquinBlanc** [comment]
Same for me, I'm pretty much done. I will deploy this version and see how it runs over time!

Thanks a lot for making that happen!

**Comment by aaugustin** [comment]
Done!

**Comment by messense** [comment]
Something wrong with Travis CI settings? Only Windows wheels are uploaded to pypi.

![image](https://user-images.githubusercontent.com/1556054/32313607-bd986d6e-bfde-11e7-996d-6c044e5982fd.png)

**Comment by aaugustin** [comment]
Yes I'm investigating this right now.

**Comment by aaugustin** [comment]
I've pushed the tags again, Travis CI is building.

**Comment by aaugustin** [comment]
We have Linux and Windows wheels but no OS X wheels, see #304.

This is a modest concern as OS X is a dev platform only (I hope).

**Comment by messense** [comment]
Hmm, but source package isn't uploaded either, so OS X users will not be able to upgrade to 4.0 for now.

**Comment by aaugustin** [comment]
I'm making a 4.0.1 version and trying to upload it correctly.

PyPI isn't my friend today...

**Comment by aaugustin** [comment]
I uploaded a sdist for 4.0.1, Linux and Windows wheels are there, I haven't repaired macOS wheel generation yet but I'm optimistic.

**Comment by aaugustin** [comment]
macOS wheels are there.

**Comment by RouquinBlanc** [comment]
Indeed now it installs with wheel on OSX!

Strange thing though, on ubuntu 16.04 and python 3.5.2 it is still stuck to version 3.4???
```
(wsproxy) user@test.vm:~$ pip install -U websockets
Collecting websockets
  Using cached websockets-3.4-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: websockets
Successfully installed websockets-3.4
```

**Comment by aaugustin** [comment]
Try with `--no-cache-dir`?
