### ISSUE TITLE
Odd exception

### ISSUE THREAD

**Issue by jacksonofalltrades** [aaugustin/websockets#299]
I'm not seeing any of the stack connect to my own code, so not sure what's causing this:

Error in opening handshake
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 69, in handler
    extra_headers=self.extra_headers)
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 304, in handshake
    raise AbortHandshake(*early_response)
TypeError: type object argument after * must be an iterable, not HTTPStatus

Any idea what might cause this or how to clean it up?

**Comment by aaugustin** [comment]
Did you override `process_request`?

**Comment by jacksonofalltrades** [comment]
I did...so I am failing to follow the spec for that, perhaps? Here's what I wrote:
`class HealthCheckServerProtocol(websockets.WebSocketServerProtocol):

    @asyncio.coroutine
    def process_request(self, path, request_headers):
        if path == '/client/ws/api/v1/status':
            body = b'status = green\n'
            return OK, [('Content-Length', str(len(body)))], body
        else:
            authenticator = DefaultAuthenticator()
            auth_payload = authenticator.authenticate(request_headers)
            if auth_payload is None:
                logging.exception("Attempt to access websocket server by unauthorized client with headers: %s" % request_headers)
                return UNAUTHORIZED`

**Comment by aaugustin** [comment]
That last line should be `return UNAUTHORIZED, [], b''`.

**Comment by jacksonofalltrades** [comment]
Oh! Thank you!

**Comment by aaugustin** [comment]
Well, in your defense, this isn't the nicest API... :-/

**Comment by jacksonofalltrades** [comment]
Haha. Perhaps, but I really appreciate you writing this. It's perfect for the project I'm working on!
