### ISSUE TITLE
`connect` and `serve` don't report themselves as coroutines

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#300]
```python
>>> from websockets.client import connect
>>> import asyncio
>>> asyncio.iscoroutine(connect)
False
```

I believe this is caused by the wrapper class that makes them async context managers.

**Comment by cjerdonek** [comment]
(I think you want to be calling `asyncio.iscoroutine()` on the return value rather, and `asyncio.iscoroutinefunction()` on the callable.)

Technically, what they are though is ["awaitable."](https://www.python.org/dev/peps/pep-0492/#await-expression)

Yes, this stems from the weirdness of having an async context manager class _also_ being awaitable itself. I think this is the only place I've seen something trying to be both at the same time.

**Comment by aaugustin** [comment]
I wasn't sure whether connect or its return value was supposed to be a coroutine, thanks for filling the gap...

That said I tested both before filing this issue and both returned `False` so the issue is still valid — albeit very minor :-)

**Comment by cjerdonek** [comment]
A couple questions:

* Is it actually important that `iscoroutinefunction()` return `True`?
* I also wonder if it's even possible for something to simultaneously be both a true coroutine and an async context manager -- as opposed to "faking" it so that the function returns True even though it's not really a coroutine. Did you have an idea on how to solve this?

**Comment by aaugustin** [comment]
I'm not sure! Investigation needed.

**Comment by cjerdonek** [comment]
Today I asked about this issue on the async-sig list (originally in general terms), to find out if there was any advantage for a function (and/or its return value) having `asyncio.iscoroutinefunction()` (resp. `asyncio.iscoroutine()` return `True`:
https://mail.python.org/pipermail/async-sig/2017-November/000397.html

The answer seems to be that there isn't really an advantage, in which case I think this issue can be closed after updating the documentation.

The docstrings for `serve()` and `connect()` can be changed from saying each is a "coroutine" to saying each is a "function returning an _awaitable_ that in returns a `WebSocketServer` (resp. `WebSocketClientProtocol`) object."

**Comment by aaugustin** [comment]
Great, thanks for getting that information.

I'm hesitating about changing the documentation. On one hand "callable returning an awaitable" describes the implementation more accurately. On the other hand the behavior is indistinguishable from a "coroutine" for practical purposes so perhaps it's best to keep the description simple?

**Comment by cjerdonek** [comment]
I think it's better to be accurate than to gloss over differences like these. For one, it can lead to confusion if users find that the documentation doesn't match what the functions are giving (e.g. `asyncio.iscoroutine()` returning `False`). It also serves to educate people on `asyncio` and its concepts when correct terminology is used.

There are many options for keeping the documentation simple while still aiming to be correct (something I didn't attempt in my comment above). Here's one option for the first line:

> Return an awaitable that starts a :class:`WebSocketServer`.

Clarifying details like mention of the word "awaitable" can even be moved further down if you don't want to clutter the main parts. For example:

```python
"""
Creates, starts, and return a :class:`WebSocketServer`.
...
The return value is an awaitable, so it must be awaited to start
and obtain the :class:`WebSocketServer`.  On Python ≥ 3.5, the
return value can also be used as an asynchronous context manager. ...
"""
```

**Comment by aaugustin** [comment]
@cjerdonek Does the wording in that PR work four you?

**Comment by cjerdonek** [comment]
@aaugustin I looked at it quickly, and it looks okay to me. Thank you!

PS - coincidentally, if you're curious, there's a thread on the async-sig list today, which was getting at a subtle difference between different types of awaitables:
https://mail.python.org/pipermail/async-sig/2018-May/000484.html
It doesn't affect this issue, but I thought it might be of interest to this audience.

**Comment by aaugustin** [comment]
Good to know we aren't the only ones thinking about these questions, even if Python core doesn't seem to care much.
