### ISSUE TITLE
Building OS X wheels on Travis CI fails

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#304]
See https://travis-ci.org/aaugustin/websockets/jobs/296128393

**Comment by messense** [comment]
Maybe `sudo pip install twine` could fix it?

**Comment by aaugustin** [comment]
Ah, right, that's the problem. We're installing twine with the system Python 2.7. Installing it with the homebrew Python 3 should work without requiring sudo.

**Comment by aaugustin** [comment]
This would be easier to fix if Travis CI didn't have over one hour of backlog of macOS builds.

**Comment by aaugustin** [comment]
Fixed in cb9b268c60a96f5bdcc8988587e0460ca4edbcdc and 05907cd7e390617d6c80f2b2a0bf222e622dd641.
