### ISSUE TITLE
loop behavior change with 4.0

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#305]
I just want to point out an issue I noticed when trying 4.0. This may very well be an acceptable behavior change, but I at least wanted to point it out here for posterity and so it can be discussed.

Basically, when I tried using `serve()` in previously working code, I got an error like the following:

> RuntimeError: Task <Task pending ...> got Future <_GatheringFuture pending> attached to a different loop

The stack trace implicates this line:

https://github.com/aaugustin/websockets/blob/93c7bc1446f1f9e99b0919dceacf84fd92832811/websockets/server.py#L725

I believe the issue is that whereas before the line [here](https://github.com/aaugustin/websockets/blob/93c7bc1446f1f9e99b0919dceacf84fd92832811/websockets/server.py#L679) in `serve()` getting the `loop` for the server:

    if loop is None:
        loop = asyncio.get_event_loop()

was happening within code that had to be awaited, in 4.0 it now happens in `__init__()` (due to the changes I made yesterday).
 https://github.com/aaugustin/websockets/blob/93c7bc1446f1f9e99b0919dceacf84fd92832811/websockets/server.py#L679

If your code calls `asyncio.new_event_loop()` between when `serve()` is called and when the coroutine object return value is awaited, you will get the error.

I believe the fix for people like me is simply to arrange not to call `serve()` until it is ready to be awaited.

Alternatively, `websockets` can be changed to move the code in `__init__()` to `__await__()` (removing the "split"), but this would require saving all of the args as attributes on the `Serve` class, which would make that code a little annoying.

I do think the code for `>= 3.5` is now easier to reason about because you can see it there in front of you all in one place. However, I'm not yet sure if there is a more elegant way of handling all of it that will satisfy the various constraints (e.g. including issue #300).

PS - by inspection, I believe the same issue is present for the client-side `connect()` as well.

**Comment by aaugustin** [comment]
Thanks for reporting this issue.

> If your code calls asyncio.new_event_loop() between when serve() is called and when the coroutine object return value is awaited, you will get the error.

That's fine. `serve()` implicitly depends on the current event loop when you don't pass an explicit `loop` argument.

If you change the current event loop after calling `serve()`, you can't use the coroutine it returned. This is a reasonable.

Previously, that implicit dependency only manifested when you awaited the coroutine. This was an implementation detail.

This bug report should allow other people who hit this problem to solve it quickly.

**Comment by cjerdonek** [comment]
Okay, I posted PR #306 for this in case we did want to fix it. I wrote the code for that before your last comment since I saw an easy way to fix it. We don't have to use the PR of course, but I just wanted to show it.
