### ISSUE TITLE
Comparison compared to https://github.com/aio-libs/aiohttp websocket

### ISSUE THREAD

**Issue by samholt** [aaugustin/websockets#307]
Hi All,

Taking the lead on the Websocket development of the large open source project: https://github.com/ccxt/ccxt.

Would anyone be so kind as to recommend whether we choose either:
- https://github.com/aaugustin/websockets/
- https://github.com/aio-libs/aiohttp/

Which one would be best suited to the task of interfacing with cryptocurrency exchange web sockets ?

(Comments here can go into the eventual projects documentation, detailing the reason for the choice).

Thank you all

**Comment by aaugustin** [comment]
Strengths and weaknesses of `websockets` are discussed here: https://github.com/aaugustin/websockets#why-should-i-use-websockets

I'm not aware of characteristics of cryptocurrency exchange that would affect the suitability `websockets` for the task.

My personal discomfort with the environmental impact of cryptocurrency mining is irrelevant here.
