### ISSUE TITLE
pings dict can grow uncontrollably?

### ISSUE THREAD

**Issue by bluetech** [aaugustin/websockets#312]
The following is a theoretical concern from reading the code (if I understood it correctly), I did not run into it in real use.

Consider for illustration a server with long-running connections, sending keep-alive pings every 30s. Consider a client which does not respond to pings for some reason. Then every 30s an item is added to the `pings` OrderedDict, which will not be removed until the connection is closed: there will not be a pong to remove it, and if the ping's future is cancelled e.g. with a timeout, it is not removed from the dict either.

In order to avoid uncontrollable growth, possible solutions I can think of are to clear a future from the dict upon cancellation, or to cancel and discard old futures from the dict after it reaches a size limit.

**Comment by aaugustin** [comment]
Yes, this is indeed the current behavior.

However, if you send many pings without receiving a pong, you're likely having bigger isses :-) The TCP connection will timeout before memory consumption becomes an issue.

I'm not sure how much memory a `Future` uses, let's say 200 bytes (. One ping every two seconds means 100 B / second. That means 350 kB after an hour. The TCP timeout is usually less than an hour.

For this reason I'm not sure it worth doing something.
