### ISSUE TITLE
error in example echo server

### ISSUE THREAD

**Issue by geniuz** [aaugustin/websockets#313]
Hi, how I can fix error in example "echo":
TypeError: 'async for' requires an object with __aiter__ method, got WebSocketServerProtocol
Thanks

**Comment by qdamian** [comment]
Try `pip install --upgrade websockets` to update to the latest version.

**Comment by aaugustin** [comment]
Indeed it looks like you're using an older version of `websockets`.

Please provide the version: `from websockets.version import version; version` of the library if this doesn't solve your problem.
