### ISSUE TITLE
SyntaxError in compability.py on Python 3.7

### ISSUE THREAD

**Issue by martmists** [aaugustin/websockets#314]
Though I know 3.7 isn't officially released yet, it would be nice to support it beforehand.

One option is to replace `asyncio.async` with `getattr(asyncio, "async")`, or even use `getattr(asyncio, "ensure_future", getattr(asyncio, "async"))`

**Comment by aaugustin** [comment]
As far as I can tell, the current implementation already does what you suggest:
https://github.com/aaugustin/websockets/blob/13eb4a09815b7edf3ac6270cbdf131b89b4ccc9d/websockets/compatibility.py#L12-L15

It uses `try / except AttributeError` instead of `getattr` but the logic is exactly the same.

**Comment by aaugustin** [comment]
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files
