### ISSUE TITLE
Problem with health check custom handler

### ISSUE THREAD

**Issue by jacksonofalltrades** [aaugustin/websockets#316]
I'm not entirely sure this is an issue with this websockets library, but I've put in code to have a specific url path trigger a health check response so that I can run my websocket server on an instance in a load balancer in an autoscaling group in AWS.

Somehow, though, I still end up having health checks fail multiple times per day, and I'm not sure what's causing it. Is there any reason you are aware of that this code could fail to respond or at least fail to respond in a timely manner?

```
class HealthCheckServerProtocol(websockets.WebSocketServerProtocol):

    @asyncio.coroutine
    def process_request(self, path, request_headers):
        if path == '/client/ws/api/v1/status':
            body = b'status = green\n'
            return OK, [('Content-Length', str(len(body)))], body
        else:
            authenticator = DefaultAuthenticator()
            auth_payload = authenticator.authenticate(request_headers)
            if auth_payload is None:
                logger.exception("Attempt to access websocket server by unauthorized client with headers: %s" % request_headers)
                return UNAUTHORIZED, [], b''
```

**Comment by aaugustin** [comment]
I suppose the health check might time out if you're doing expensive things that tie the asyncio event loop for several seconds. (Wild guess.)

**Comment by jacksonofalltrades** [comment]
Hm. I've noticed that the whole server seems very sensitive to even small changes in asyncio.sleep times within any of my handlers. Any idea why that would be? For example, if I adjust sleep times too low (0.5 seconds), then it seems my connections never stay open for very long from a client. Is there anything built in to asyncio to let me track how long each coroutine is taking before the next one gets executed? Or do I just need to add lots of logging?

**Comment by jacksonofalltrades** [comment]
I think I was doing some things wrong with not breaking out of handlers properly when exceptions were thrown in some cases.

**Comment by jacksonofalltrades** [comment]
Hm, so I am still having this problem. Is there some way to ensure that the health check handler doesn't get delayed by other tasks?
