### ISSUE TITLE
A Future or coroutine is required

### ISSUE THREAD

**Issue by TheDeadOne** [aaugustin/websockets#318]
I tried to run a [basic example](https://websockets.readthedocs.io/en/stable/intro.html#basic-example) from the documentation and got an error:

```
Traceback (most recent call last):
  File "hello.py", line 14, in <module>
    asyncio.get_event_loop().run_until_complete(start_server)
  File "c:\python3\Lib\asyncio\base_events.py", line 322, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "c:\python3\Lib\asyncio\tasks.py", line 531, in ensure_future
    raise TypeError('A Future or coroutine is required')
TypeError: A Future or coroutine is required
```

Python 3.5.0
websockets 4.0.1

**Comment by cjerdonek** [comment]
Thanks for reporting the Python version. Can you try with Python 3.5.1 or higher? `asyncio.ensure_future(coro_or_future)` was changed to accept any awaitable only in Python 3.5.1:

https://docs.python.org/3/library/asyncio-task.html#asyncio.ensure_future

(Technically, perhaps this means websockets doesn't support Python 3.5.0.)

**Comment by cjerdonek** [comment]
Maybe the docs section linked in the OP should be changed from "This section assumes Python ≥ 3.5" to "This section assumes Python ≥ 3.5.1."

**Comment by aaugustin** [comment]
Actually we should say that we only support the latest micro release.

This is how Django documents this policy: https://docs.djangoproject.com/en/2.0/faq/install/#what-python-version-can-i-use-with-django

What's good enough for Django is good enough for websockets ;-)

**Comment by pilotandy** [comment]
I can confirm that it work with 3.5.1, but not 3.5.0.  However, in my case, I'm not the one who can upgrade the version of python in our production environment.  Is there something I can do to get it to work for 3.5.0?

**Comment by aaugustin** [comment]
Try using an earlier version of websockets. 3.4 may work; this looks related to changes we made in 4.0.
