### ISSUE TITLE
Add python_requires to setup.py

### ISSUE THREAD

**Issue by dscole** [aaugustin/websockets#321]
Please add a [python_requires](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=python_requires#new-and-changed-setup-keywords) setting. That way if someone or something tries to pip install it on python2, they get a meaningful error.

**Comment by aaugustin** [comment]
If you submit a pull request for this I'll merge it.

Will this supersede https://github.com/aaugustin/websockets/blob/136d9bc9a917f7f5fdde4001e801b591ee1b4a0b/setup.py#L20-L21?

This isn't obvious when installing from a wheel.

(I stopped caring about the existence of Python 2 a few years ago so I'm unlikely to spend more than a couple minutes on this.)

**Comment by dscole** [comment]
I believe it will. The setup.py isn't run when installing from a wheel. That's why you need to make it part of the package's requirements. Note, that this issue isn't python2 specific, people will probably see similar issues if they try to install from python 3.3. Someone will try to install, maybe even succeed, but fail unexpectedly when it hits code that uses new features that don't exist in python versions you dropped support for.

**Comment by hugovk** [comment]
+1 for `python_requires`, although it's only for pip>=9.0.0, so the `if py_version < (3, 4):` check is still useful for a while longer.
