### ISSUE TITLE
Error 1006

### ISSUE THREAD

**Issue by GitHub2022** [aaugustin/websockets#322]
Hi all,

i am connected to a websocked and always get error 1006 back. It seems like that it happens after exact 86 seconds. It looks like:

    async with websockets.connect ('wss://wsxxx.de/socket.io/1/websocket/' + str (hskey)) as websocket:
        try:
            while True:
                greeting = await websocket.recv()
                print (greeting)
        except websockets.exceptions.InvalidState:
            print (websocket.state)

If i set a "time.sleep(2)" i can increase the amount of time before i receive the same error by at least 50%. 

So here is the thing - how can i determine what exactly is causing the error 1006? Is there anything wrong with my code?

**Comment by cjerdonek** [comment]
What web server are you using? nginx or something else, and what timeout is configured for the web server. Maybe the web server is terminating the connection. I believe I've observed that as a cause.

**Comment by GitHub2022** [comment]
the remote site is using socket.io 0.9x as implementation. which exact server it is i dont know, i am just working on the client side and of course they are not responding to any questions.

**Comment by cjerdonek** [comment]
I would experiment to see if sending messages periodically lets you extend the amount of time you can keep the connection open..

**Comment by GitHub2022** [comment]
yes i did that as well. Answer is no, same time. I did a .send("test"). As soon as i start a ping the server terminates the connection rigth away.

**Comment by GitHub2022** [comment]
Weird is that if i set the time.sleep() i can increase the time until the connection breaks. That means that its not a total timeout by the server. Maybe its something the recv()  function can not correctly understand?

**Comment by GitHub2022** [comment]
#!/usr/bin/env python

import asyncio
import websockets
import requests
import time
import logging
import aiohttp

logger = logging.getLogger('websockets')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

async def hello():
    r = requests.request ("GET", 'https://ws.bitcoin.de/socket.io/1/?t=' + str (time.time ()).split ('.')[0],
                          timeout=20)
    hskey = r.text.split (':')[0]

    last_time = time.time ()

    async with websockets.connect ('wss://ws.bitcoin.de/socket.io/1/websocket/' + str (hskey)) as websocket:
        try:
            while True:
                time_diff = round (time.time () - last_time)
                print (time_diff)

                #pong_waiter = await websocket.ping ()
                #pong_waiter = await websocket.send ("test")
                #await pong_waiter
                # time.sleep(3)
                greeting = await websocket.recv()
              
                print (greeting)
                
        except websockets.exceptions.InvalidState:
            time_diff = round (time.time () - last_time)
            print (time_diff)

            print (websocket.state)
            print ('Exit')
        except websockets.exceptions.InvalidMessage:
            print ('message invalid')
            print ('Exit')

asyncio.get_event_loop().run_until_complete(hello())

**Comment by GitHub2022** [comment]
Any ideas?

**Comment by aaugustin** [comment]
You set the log level to DEBUG. That's a good idea. What do the logs say?

**Comment by GitHub2022** [comment]
the log said error 1006. yes it is not that much of data coming in. so nothing i really can work with.

**Comment by aaugustin** [comment]
Probably it means the other end dropped the connection without a closing handshake.

**Comment by GitHub2022** [comment]
maybe, the point is that if i increase a timer (time.sleep) i can increase the amount of time the connection is working. So why should the remote server differentiate?

**Comment by GitHub2022** [comment]
problem solved. server expected to send back empty messages ...
