### ISSUE TITLE
module 'websockets' has no attribute 'serve'

### ISSUE THREAD

**Issue by erelsgl** [aaugustin/websockets#335]
I installed the latest version of websockets (4.0.1),  copied the example from here:
     http://websockets.readthedocs.io/en/stable/intro.html

and ran it in Python 3.5.2.

I got an error: "module 'websockets' has no attribute 'serve'".

**Comment by aaugustin** [comment]
There must be something wrong with your installation. Perhaps the `websockets` module you're importing isn't the one you think you're importing (e.g. if you have a `websockets.py` file in your current directory). Try `print(websockets.__file__)` to check what module you're actually using.

**Comment by erelsgl** [comment]
This is correct! I named the example file "websockets.py".

**Comment by aaugustin** [comment]
Ha! You can't be the first one. Perhaps I should warn about this common Python pitfall in the docs.

**Comment by jyoung360** [comment]
I ran into this trap as well.  A warning in the docs would be great.

**Comment by aaugustin** [comment]
Let's add it to the FAQ.

**Comment by aaugustin** [comment]
Better late than never!

**Comment by johannesschaffer** [comment]
I still have that issue wiht version 1.9.0. I'm on Windows, in case that matters. I don't have a websocket.py file. Importing from websockets.server or websockets.sync.server works. But not from websockets directly.
