### ISSUE TITLE
document that `ws_handler` should be prepared to handle CancelledError

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#337]
Since when a websockets server is closed (i.e. when `WebSocketServer.close()` is called), [`protocol.handler_task.cancel()` is called](https://github.com/aaugustin/websockets/blob/d4a6a24fcf9786b1917668bfaee946e85bc22478/websockets/server.py#L558-L559) on every `WebSocketServerProtocol` instance, I think it would be good to document that authors should write `ws_handler` to be prepared to handle `CancelledError` being thrown in.  (`ws_handler` is the connection handler coroutine passed to `websockets.serve()`.)

**Comment by aaugustin** [comment]
Yes.

**Comment by aaugustin** [comment]
I verified experimentally that catching `asyncio.CancelledError` results in a 1000 close code rather than 1001.

**Comment by aaugustin** [comment]
@cjerdonek Does that PR look good to you?
