### ISSUE TITLE
handling closed connections in ws_handler

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#338]
I recently noticed that if a connection closes abnormally (and additionally is one that `websockets` is aware of), then `ws_handler` on the server side just continues running normally. This can create a problem by leaving protocol objects on the server-side running for longer than they need to be.

I sort of expected in this case that the server would send `CancelledError` in to `ws_handler` to notify the handler that there is no longer a connection to be handled.

I'm wondering then if it would make sense for `websockets` to send `CancelledError` in this case. If not, what is the right way for a `ws_handler` to "subscribe" to or be notified of the connection closing? It would be much better for `ws_handler` e.g. to be able to register a callback on a future rather than having to, say, check that `protocol.open` is true at regular intervals.

Here is example code to illustrate the issue:

```python
def log(msg):
    print(f'****: {msg}')

async def fail_connection(protocol):
    await asyncio.sleep(5)
    log('failing connection')
    await protocol.fail_connection()

async def handle_connection(protocol, path):
    asyncio.ensure_future(fail_connection(protocol))
    try:
        while True:
            await asyncio.sleep(1)
            log('still handling connection')
    finally:
        log('exiting handle_connection()')

async def run_client():
    async with websockets.connect('ws://localhost:8765'):
        print('client connected')
        await asyncio.sleep(10)

    print('client exiting')

async def run():
    async with websockets.serve(handle_connection, 'localhost', 8765):
        await run_client()
```

And here are the logs:

    client connected
    INFO:asyncio:poll 998.616 ms took 1003.063 ms: timeout
    ****: still handling connection
    INFO:asyncio:poll 999.874 ms took 1004.412 ms: timeout
    ****: still handling connection
    INFO:asyncio:poll 999.875 ms took 1003.993 ms: timeout
    ****: still handling connection
    INFO:asyncio:poll 999.880 ms took 1004.832 ms: timeout
    ****: still handling connection
    ****: failing connection
    DEBUG:websockets.protocol:server ! failing WebSocket connection: 1011 
    DEBUG:websockets.protocol:server > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
    DEBUG:asyncio:poll 15.719 ms took 0.015 ms: 1 events
    DEBUG:websockets.protocol:client < Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
    DEBUG:websockets.protocol:client > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
    DEBUG:websockets.protocol:server < Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
    DEBUG:websockets.protocol:server x half-closing TCP connection
    DEBUG:asyncio:poll 14.151 ms took 0.010 ms: 1 events
    DEBUG:asyncio:<_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>> received EOF
    DEBUG:websockets.protocol:client - eof_received()
    DEBUG:websockets.protocol:client - connection_lost(None)
    DEBUG:asyncio:<_SelectorSocketTransport fd=13 read=polling write=<idle, bufsize=0>> received EOF
    DEBUG:websockets.protocol:server - eof_received()
    DEBUG:websockets.protocol:client x closing TCP connection
    DEBUG:websockets.protocol:server - connection_lost(None)
    DEBUG:websockets.protocol:server x closing TCP connection
    ****: still handling connection
    INFO:asyncio:poll 999.879 ms took 1002.503 ms: timeout
    ****: still handling connection
    INFO:asyncio:poll 999.879 ms took 1004.720 ms: timeout
    ****: still handling connection
    INFO:asyncio:poll 999.879 ms took 1000.126 ms: timeout
    ****: still handling connection
    INFO:asyncio:poll 999.880 ms took 1003.233 ms: timeout
    ****: still handling connection
    client exiting
    ****: exiting handle_connection()
    DEBUG:websockets.protocol:server ! failing WebSocket connection: 1001

**Comment by cjerdonek** [comment]
With how `websockets` is currently written, it looks like `protocol.connection_lost_waiter` could be used for this. However, the ergonomics of this isn't so great, and it's not clear if `connection_lost_waiter` is part of the public API.

Below is an example of adjusting the code above to handle abnormal closures using `connection_lost_waiter`. This wraps the original websocket handler with a handler that (1) starts the handler task, and (2) registers a callback on `connection_lost_waiter` that cancels the original handler task.

```python
async def _handle_connection(protocol, path):
    asyncio.ensure_future(fail_connection(protocol))
    try:
        while True:
            await asyncio.sleep(1)
            log(f'still handling connection: {protocol.state!r}')
    finally:
        log('exiting handle_connection()')

async def handle_connection(protocol, path):
    task = asyncio.ensure_future(_handle_connection(protocol, path))
    protocol.connection_lost_waiter.add_done_callback(lambda future: task.cancel())

    await task
```

**Comment by aaugustin** [comment]
You are correct. The current design assumes that `ws_handler` will notice that the connection is closed next time it attempts to interact with the connection with `recv`, `send`, `ping` or `pong`.

Cancelling the `ws_handler` when the connection terminates makes sense.

I'd do that in `WebSocketServerProtocol.handler` by changing:

```python
yield from self.ws_handler(self, path)

**Comment by cjerdonek** [comment]
Could you somehow phase in the friendlier behavior, e.g. making it opt-in
initially and deprecating the old behavior in a major release?

**Comment by aaugustin** [comment]
`shield` starts by wrapping its argument in `ensure_future`.

After `yield from asyncio.shield(finalize(...))`, `finalize(...)` lives it its own task. If that `yield from` in cancelled, the link is broken and there's no way to wait for `finalize()`to complete.

**Comment by aaugustin** [comment]
> what is the right way for a ws_handler to "subscribe" to or be notified of the connection closing?

I added `WebSocketCommonProtocol.wait_closed` for this purpose today.

> With how websockets is currently written, it looks like protocol.connection_lost_waiter could be used for this. However, the ergonomics of this isn't so great, and it's not clear if connection_lost_waiter is part of the public API.

`wait_closed` is the public API you were missing. Indeed it's built on top of `connection_lost_waiter`.

So plan B is implemented.

----

Going back to plan A.

@lgrahl and I had a discussion on a similar topic in #464.

Eventually we decided to remove cancellation to make sure end users consistently see `ConnectionClosed` exceptions. If we added cancellation in the situation described here, users could randomly see `ConnectionClosed` or `CancelledError` depending on which one wins the race. That would be inconsistent with the choice made in #464.

We also reached the conclusion that cancellation was appropriate when something no longer cares about the result of a process it started. One could argue that we're in this situation: the server /almost/ no longer cares about the result of `ws_handler`.

The fine print in /almost/ is that `ws_handler` is user-provided code. This is an [inversion of control](https://en.wikipedia.org/wiki/Inversion_of_control) scenario. We don't know if there's anything worth executing left in `ws_handler`.

My arguments around finalization code above show that in some cases, there's something worth executing and that throwing `CancelledError` will just make things more complicated.

----

I'm bothered by the inconsistency at this point: we're cancelling `ws_handler` when the server shuts down but not when the connection drops. I'm not finding a valid reason why websockets should handle these two situations differently. It's an accidental result of implementing them separately.

When the server shuts down, we want to terminate connections with 1001 Going Away. To achieve this, we need cancel `ws_handler`, detect that the server is shutting down (cf. `_is_server_shutting_down`) and decide that a 1001 is appropriate.

Closing the connection with 1001 and letting `ws_handler` terminate would be more consistent. If we change what we documented in #392, it will be a backwards-incompatible change (but an acceptable one).

**Comment by lgrahl** [comment]
This is an interesting one. I never encountered it since my implementation closes all connections and waits for all handlers to return before it shuts down the server. This allows me to control the close code for each connection individually and clean up any remaining resources.

Because of that, I would be fine if the server *cancels* remaining handlers implicitly by letting them know that the connection is gone as proposed in https://github.com/aaugustin/websockets/issues/338#issuecomment-423834444. The only thing that could happen is that the handler waits for something completely different... which I don't think is important since the application already made an intent to shut down the server. If it wants to shut down cleanly, it needs to signal that intent to its own handlers.

**Comment by aaugustin** [comment]
If I make this change, then there are only two situations where websockets cancels tasks:

1. Tasks created with `asyncio.ensure_future`, passed to `asyncio.wait`, and returned as still pending (4 instances);
2. Internal tasks running `ping_keepalive` and `transfer_data` that must terminate when the connection shuts down.

None of these tasks run user code, only framework code, so the "inversion of control" argument doesn't apply to them.

**Comment by lgrahl** [comment]
In hindsight, it would have perhaps made sense to use an `asyncio.Queue` to hand out `(connection, path)` tuples and let the application queue its own task.

**Comment by aaugustin** [comment]
Also known as "letting the user deal with the problem" ;-)

Jokes aside, websockets aims at being very simple to get started with. It shouldn't require too much assembly to be usable. Of course that make it less flexible; it's a tradeoff.

**Comment by aaugustin** [comment]
While working on this, I dug myself into this beautiful rabbit hole: https://bugs.python.org/issue34852

**Comment by aaugustin** [comment]
I have a WIP PR for this in #483. I still need to:

- [ ] Figure out what happens to connections where the opening handshake hasn't completed yet when the server shuts down and try to return a HTTP 503 if possible
- [ ] Review tests -- currently everything passes and there's 100% coverage but I'm not sure everything makes sense
- [ ] Document the `ws.wait_closed().add_done_callback(asyncio.current_task().cancel)` trick

**Comment by aaugustin** [comment]
Interestingly, this PR also seems to provide a reasonable solution to #394.

**Comment by aaugustin** [comment]
Server and client examples for testing server shutdown (trigger it with Ctrl-C) during the handshake or the data exchange phase.

**Server**

```python
#!/usr/bin/env python

import asyncio
import logging
import signal
import websockets

logging.basicConfig(level=logging.DEBUG)


class ServerProtocol(websockets.WebSocketServerProtocol):
    async def process_request(self, path, request_headers):
        # Wait to make it easier to interrupt the handshake
        for counter in range(10, 0, -1):
            print(counter)
            await asyncio.sleep(1)


async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)


async def echo_server(stop):
    async with websockets.serve(
        echo, "localhost", 8765, create_protocol=ServerProtocol
    ):
        await stop


loop = asyncio.get_event_loop()

stop = asyncio.Future()
loop.add_signal_handler(signal.SIGINT, stop.set_result, None)
loop.add_signal_handler(signal.SIGTERM, stop.set_result, None)

loop.run_until_complete(echo_server(stop))
```

**Client**


```python
#!/usr/bin/env python

import asyncio
import logging
import websockets

logging.basicConfig(level=logging.DEBUG)


async def echo():
    async with websockets.connect("ws://localhost:8765") as websocket:
        for letter in "abcdefghij":
            await websocket.send(letter)
            await websocket.recv()
            await asyncio.sleep(1)


loop = asyncio.get_event_loop()

loop.run_until_complete(echo())
```
