### ISSUE TITLE
TypeError: 'async for' requires an object with __aiter__ method,

### ISSUE THREAD

**Issue by SaturnTeam** [aaugustin/websockets#340]
I tried your client and server implementation from readme, and got this error
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/websockets/server.py", line 135, in handler
    yield from self.ws_handler(self, path)
  File "s.py", line 6, in echo
    async for message in websocket:
TypeError: 'async for' requires an object with __aiter__ method, got WebSocketServerProtocol
`
websockets 4.0.1
Python 3.5.2 
ubuntu 16.04

**Comment by aaugustin** [comment]
Symptoms look identical to #332. I can't tell if the root cause is the same.

**Comment by SaturnTeam** [comment]
I used version 4.0.1 installed from scratch and downgrade to 3.4 helped me

**Comment by aaugustin** [comment]
The code in the README uses Python 3.6+ syntax. That should be mentioned somewhere.

**Comment by wasif-digitalnet** [comment]
@aaugustin 
I have latest version 6.0 installed still having the same issue,

**Comment by lgrahl** [comment]
Use version 7.0 if you really must have Python 3.5 support.
