### ISSUE TITLE
`easy_install websockets` on Windows with Python 3.5 fails to build.

### ISSUE THREAD

**Issue by ashleysommer** [aaugustin/websockets#341]
I don't know if this is a duplicate, it seems like it would be a common issue, but I couldn't find it while searching.

Using `easy_install` to download and install websockets on Windows 10, in a Python 3.5 VirtualEnv.

This is the output:
```
zip_safe flag not set; analyzing archive contents...
websockets.__pycache__.test_client_server.cpython-35: module references __file__
 File "c:\src\myproject\venv\lib\site-packages\websockets-4.0.1-py3.5-win-amd64.egg\websockets\py36\protoco
l.py", line 15
   yield await self.recv()
   ^
SyntaxError: 'yield' inside async function

zip_safe flag not set; analyzing archive contents...
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd6
4\\cl.exe' failed with exit status 2
```

It seems the websockets-4.0.1-py3.5-win-amd64.egg bundle contains /py36/ directory that does not compile in python3.5.

It does not fail when using PIP, because I guess it downloads the compiled wheels.

**Comment by aaugustin** [comment]
Thanks for the report.

I never used `easy_install`; as far as I understand, it was superseded by `pip`, wasn't it? I never used Windows either so I don't really know where to start with this issue.

If you can provide a pull request that doesn't add complexity (like setting the zip_safe to avoid the inspection proces that crashes here), I'll consider it. Otherwise, use `pip`?

**Comment by Ivoz** [comment]
Yes, `easy_install` is essentially a deprecated tool. `pip` should come automatically with any new python 3. Is there a salient reason you're sticking to using it?

**Comment by ashleysommer** [comment]
I usually use `pip`, and as a Linux developer, I myself have not used Windows in a very long time.

However there _is_ a reason I am trying to install using `easy_install` on Windows 10 install `websockets`.

I am deploying a Sanic project on a Windows 10 venv for a colleague.
To install sanic on Windows, you need to pass in some environment variables.
Namely: `set SANIC_NO_UVLOOP=true` and `set SANIC_NO_UJSON=true`, before installing sanic, so that it does not pull in those dependencies when `setup.py` is run.

Unfortunately this doesn't work with pip, because pip pulls in pre-built packages and does not build with `setup.py`. But `easy_install sanic` _does_ work, because easy install unzips the package and runs `setup.py` to install it, which honors the set environment variables.

The problem I'm seeing is that `websockets` is a dependency of sanic. So using `easy_install` to install sanic causes `easy_install` to install all of sanic's dependencies too, including websockets. That is what is giving the problem, and the reason I created this Issue.

The way I got around it was to run `pip install websockets` _before_ `easy_install sanic`, so easy_install sees that `websockets` is already installed and doesn't try to install it itself.

**Comment by cjerdonek** [comment]
That sounds like the right approach and is what I would do.

**Comment by ashleysommer** [comment]
Having just read up about the `zip_safe` flag, I believe it would still be beneficial for `websockets` to include it in its `setup.py` file.

One of the uses of of `zip_safe` is you are telling setuptools that you know the code might emit warnings during analysis, but you know the code is still correct, so install the bundle anyway.
Which is exactly what we want to do in this circumstance.

I will do up a quick PR.

**Comment by Ivoz** [comment]
@ashleysommer had you tried `--no-binary sanic` with your `pip install` invocation?

**Comment by ashleysommer** [comment]
@Ivoz 
No, I didn't know about the `--no-binary` switch for pip. I will try that, though I'm not sure if that will fix the problem that pip ignores the set environment variables. But it might work, given that it probably needs to run sanic's `setup.py` to install the package if `--no-binary` is set.

> I hestitate to think that modifying an underlying dependency package because something that depends on it is having trouble with its own build process is ever a good idea.

I absolutely agree. This is sanic's fault for not having a better Windows install process, or even uvloop's fault for not being compatible with Windows, causing downstream projects to have to do conditional installs.

I made PR #342 because I think it is not a very big change, and it will eliminate the problem for any other people (such as my colleague) who might run into this same error message in the future.

**Comment by aaugustin** [comment]
If making that change helps, why not. I'm not promising to keep it if it causes unexpected problems.
