### ISSUE TITLE
How to connect many websocket? #question

### ISSUE THREAD

**Issue by thomaszdxsn** [aaugustin/websockets#343]
Hi, 

I have a new job, the legacy code used this package to support connect many websocket(around 20, 24 * 7), but i think it's usage is sick...

Because it use Thread to get various websocket, and every Thread subclass individually get eventloop, run this package to connect, is it correctly?

**Comment by aaugustin** [comment]
Most likely, it isn't correct. For commercial support, please contact me here: https://fractalideas.com/
