### ISSUE TITLE
Is it possible to run multithread server?

### ISSUE THREAD

**Issue by SaturnTeam** [aaugustin/websockets#346]
I wonder, how can I use this lib to run server with multithreading? I want separate thread for each incoming connection

**Comment by aaugustin** [comment]
You might be able to achieve that with liberal use of `call_soon_threadsafe`. However, before asking how you could, please consider whether you should, and the answer is definitely "no" :-)

Your question suggests that:
- either you haven't figured out why asyncio and websockets exist: in that case, read about asyncio until you understand that each incoming connection is handled in its own coroutine and crucially not in its own thread;
- or you're asking about a potential (and totally wrong) solution to another problem: in that case, CPU intensive work is likely part of the question and `run_in_executor` likely part of the solution, but really this is a guess.

**Comment by SaturnTeam** [comment]
How can I run Serve object in run_in_executer or call_soon_threadsafe? 
`TypeError: 'Serve' object is not callable`
```

start_server = websockets.serve(main_request_handler, WEBSOCKET_HOST, WEBSOCKET_PORT)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Comment by aaugustin** [comment]
Really this is a question about asyncio, not about websockets. Look at the asyncio documentation about interactions with threads.

**Comment by SaturnTeam** [comment]
So you don't know too. Documentaion doesn't cover this case
