### ISSUE TITLE
Is there a way to get the low level socket file descriptor?

### ISSUE THREAD

**Issue by lvella** [aaugustin/websockets#347]
I want to set some socket properties directly on the socket (specifically, I want to enable low level TCP keepalive instead of pinging at application level). Is there a way to get the low level socket from the object returned by `websockets.connect()`?

**Comment by aaugustin** [comment]
**The proper way**

The design of asyncio encourages customization by subclassing, so the proper way is:

- Write a subclass of `WebSocketClientProtocol`
- Override `connection_made(transport)` in that class
- Do whatever you want with `socket = transport.get_extra_info('socket')` in that method
- Don't forget to call the parent implementation
- Connect using your custom protocol with `ws = await websockets.connect(..., create_protocol=MyClientProtocol)`

**The quick'n'dirty way**
Assuming:
```python
ws = await websockets.connect(...)
```
One of these should do the job:
```python
socket = ws.writer.get_extra_info('socket')
```
or perhaps
```python
socket = ws.writer.transport.get_extra_info('socket')
```

**Comment by roguh** [comment]
For future reference, you can now use the `sock` argument when calling `serve`.

> [Any other keyword arguments are passed the event loop’s [create_server()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server) method.](Any other keyword arguments are passed the event loop’s [create_server()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server) method.)
