### ISSUE TITLE
healtch check example

### ISSUE THREAD

**Issue by oplatek** [aaugustin/websockets#354]
Hello,

can you please explain to me
how to serve websocket connections on some URL and HTTP requests on other URL?

My URLs looks like this

```
/ws     ... websocket
/health ... HTTP
```

I found some relevant information at
https://github.com/aaugustin/websockets/issues/311.
and
https://github.com/aaugustin/websockets/blob/master/websockets/test_client_server.py#L146

However, I am still not sure how to use the modified `WebSocketServerProtocol`  e.g. the `HealthCheckServerProtocol` correctly. See the snippet below.
The problem is that I do not know where to **register** the `HealthCheckServerProtocol` in my code:

```
class HealthCheckServerProtocol(WebSocketServerProtocol):
    async def process_request(self, path, request_headers):
        if path == '/__health__/':
            body = b'status = green\n'
            return OK, [('Content-Length', str(len(body)))], body

async def handler(wsp, path):
    print("I do not know how to get the wsp argument as an instance of HealtchCheckServerProtocol")

server = loop.run_until_complete(websockets.serve(handler, '0.0.0.0', '8080'))
```

Thank you!

PS: Will you be interested in adding such example to the example dir?
It seems to me that implementing health-check is fairly often

**Comment by aaugustin** [comment]
Pass `create_protocol=HealthCheckServerProtocol` to [serve](http://websockets.readthedocs.io/en/stable/api.html#websockets.server.serve).

**Comment by ddehghan** [comment]
Hi - By any chance you can share your solution. 

How does the server know which protocol should be served by which class? do you have to run each protocol on a different port?

**Comment by ddehghan** [comment]
ok great. would you like me to send you a pull request for an example of health check ? or someone else is working on that.

**Comment by aaugustin** [comment]
What do you think of the PR I just submitted?
