### ISSUE TITLE
Make module runnable, provide `cat`-style tool

### ISSUE THREAD

**Issue by athre0z** [aaugustin/websockets#361]
I think it'd greatly aid development and debugging of new WebSocket tools if the module would come with a very simple `cat` style tool, echoing received messages to the terminal and sending messages from `stdin`. There are quite a few such tools around, however they all seem to require installing an unreasonable amount of other stuff (NodeJS, Go compiler, ...).

Using this lib, such a tool shouldn't be more than maybe 50 lines of code and could be cleanly tucked away in `__main__.py`, allowing invocation of the tool via `python -mwebsockets`, for example. We could also add support for `nc`-style `-l` listen mode.

What do you think? If you like the idea, I'd be happy to write & contribute it.

**Comment by aaugustin** [comment]
That sounds interesting. Happy to review a PR. Please keep it as simple as possible.

`asyncio` won't work directly with stdin. You'll need something line `asyncio.run_in_executor(input())` to read inputs.

**Comment by athre0z** [comment]
Hmm, that seems to complicate things more than I hoped. I can't seem to figure out how to allow cancelation of the tool with a single `CTRL+C`. As soon as I run `loop.run_in_executor(None, sys.stdin.readline)`, it requires either a second `CTRL+C` to kill the script or pressing enter (having `readline` return). On Unix, it's also possible to directly close the tool with a single `CTRL+D` when running as client.

My current progress is available here:
https://github.com/athre0z/websockets/blob/runnable-module/websockets/__main__.py

I found this [`ainput` function in the lib aioconsole](https://github.com/vxgmichel/aioconsole/blob/master/aioconsole/stream.py#L149) that doesn't have the issue with blocking the exit, however I'm pretty sure we neither want a dependency for such a "simple" thing nor want to copy those multiple hundred source lines (especially since this other lib is GPL).

Any ideas?

**Comment by aaugustin** [comment]
This is indeed getting more complicated than I hoped :-/

**Comment by aaugustin** [comment]
So here's my attempt. @athre0z Does it work for you?

In order to get a clean interaction with signals, blocking system calls (`input()`) are performed in the main thread. This solves the "double ^C" problem. It requires running the event loop in a background thread.

It's more than 50 lines of code: 94 lines, or 64 lines excluding blank lines and comments. It doesn't support listen mode (yet). It's only portable to VT100 terminals, as I'm using a VT100 escape code to clear the input line when I need to show an output line. It needs tests (if possible) and docs.

**Comment by athre0z** [comment]
Yup, that works great on macOS, nice work! On Windows however, the `readline` module is not available, thus crashing with:
```
Traceback (most recent call last):
  File "C:\Users\ath\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\ath\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Y:\Development\websockets\websockets\__main__.py", line 3, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

Contrary to what one might assume, Windows actually supports VT100 escape sequences:
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
The support for those was silently added in some update in 2016.

**Comment by athre0z** [comment]
Also, on macOS, when erroring due to connection issues (e.g. 404), it requires 3x ^C to quit.

**Comment by aaugustin** [comment]
Thanks for testing!

I need to investigate the first point -- perhaps I can get creative with VT100 codes (e.g. does "insert line above" exist?) instead of depending on readline.

The second should be easy to fix: it's a matter of catching and handling exceptions.

**Comment by aaugustin** [comment]
I fixed these two problems, as well as a few others.

With manual testing on macOS, I get a proper behavior (correct display of lines, no stray characters, timely exit):

- when the exiting with Ctrl-C or Ctrl-D
- when the remote endpoint closes the connection
- when failing to establish the connection

I wrote code that's supposed to work on Windows but I have no way to test it.

**Comment by aaugustin** [comment]
To test, I modify the echo example like this:

```diff
diff --git a/example/echo.py b/example/echo.py
index 8fa307d..eece7b4 100755
--- a/example/echo.py
+++ b/example/echo.py
@@ -4,8 +4,20 @@ import asyncio
 import websockets

 async def echo(websocket, path):
+    async def count():
+        i = 0
+        while True:
+            i += 1
+            await websocket.send(str(i))
+            await asyncio.sleep(i / 10)
+    task = asyncio.ensure_future(count())
+
     async for message in websocket:
         await websocket.send(message)
+        # await asyncio.sleep(1)
+        break
+
+    task.cancel()

 asyncio.get_event_loop().run_until_complete(
     websockets.serve(echo, 'localhost', 8765))
```

and I run:

```
PYTHONPATH=. python example/echo.py
```

```
python -m websockets localhost:8675
```

**Comment by aaugustin** [comment]
I'm not sure it's worth writing tests for this script.

**Comment by athre0z** [comment]
It works great on macOS and, well, partially on Windows.

<img width="965" alt="screen shot 2018-08-02 at 23 31 10" src="https://user-images.githubusercontent.com/6553158/43612669-591b4054-96ad-11e8-8d61-70e0a302b52b.png">

**Comment by aaugustin** [comment]
Thanks a lot for the "enable VT100 on Windows" trick.

https://bugs.python.org/issue29059 suggests that's the way to go (I sort of disagree with the decision there).

**Comment by athre0z** [comment]
Excellent, now I can uninstall NodeJS from my host system again! Thanks for taking the time to implement this!
