### ISSUE TITLE
ws over https ?

### ISSUE THREAD

**Issue by parmentelat** [aaugustin/websockets#363]
Hello, there

I am a total newbie with this library which I stumbled upon just today; 

I was using socket.IO but am considering to move to a simpler approach based on raw ws(s);  
largely due to the lack of an asyncio-based library for a socket.io client in python btw

That's why I am quite interested; I have a question about using https though, as none of the examples touches on that, and the project's page on readthedocs do not either seem to address that topic

So is this something doable, and if so how to go about doing it ?
IMHO this is something that would deserve a quick example as well :)

In any case, this looks like a very nice and very useful piece if work, thanks for putting this together

**Comment by aaugustin** [comment]
I have to admit it took me a bit of time to locate this information, it's hidden in the documentation of [websockets.server.serve](http://websockets.readthedocs.io/en/stable/api.html#websockets.server.serve):

> you can set the ssl keyword argument to a [SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext) to enable TLS.

I'm keeping this open as a documentation issue.

Thanks for the kind words!

**Comment by parmentelat** [comment]
thanks for the feedback; make sure to mention 'https' somewhere, as this is probably what people will be looking for in readthedocs - that's what I did at least :)

**Comment by aaugustin** [comment]
Good point. We can say something like "WSS is the equivalent of HTTPS for websockets". Let's include "TLS", "SSL" and "certificate" as well for good measure.

**Comment by aaugustin** [comment]
PS - chic à la jaune ;-)

**Comment by parmentelat** [comment]
Yo camarade ;)

**Comment by aaugustin** [comment]
@parmentelat I'm interested in hearing your feedback on the PR I just submitted.
