### ISSUE TITLE
Syntax error in Python 3.7.0b2

### ISSUE THREAD

**Issue by Mattwmaster58** [aaugustin/websockets#365]
I saw [this commit](https://github.com/aaugustin/websockets/commit/9f566c5d12eae1258aa6f1991fe8cf0a7d390f97) but it hasn't fixed the problem. In fact, the line that is throwing the error hasn't even been change in the commit. Here is the error:

    File "C:\Program Files\Python37\lib\site-packages\websockets\compatibility.py", line 15
       asyncio_ensure_future = asyncio.async           # Python < 3.5
                                                                ^
    SyntaxError: invalid syntax

**Comment by Mattwmaster58** [comment]
See PR #366

**Comment by aaugustin** [comment]
Your traceback contains:

```python
   asyncio_ensure_future = asyncio.async           # Python < 3.5
```

The current implementation is:

```python
    asyncio_ensure_future = getattr(asyncio, 'async') # Python < 3.5
```

You can confirm this here:

https://github.com/aaugustin/websockets/blob/13eb4a09815b7edf3ac6270cbdf131b89b4ccc9d/websockets/compatibility.py#L15

So this is fixed in the master branch.

**Comment by Mattwmaster58** [comment]
Reinstalling the exact same version I had before fixes the issue. Weird. Thanks for your help
