### ISSUE TITLE
Confusing error when `max_size` is too small

### ISSUE THREAD

**Issue by yig** [aaugustin/websockets#368]
The error produced when sending a message over the `max_size` limit is confusing:

```
Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/websockets/server.py", line 135, in handler
    yield from self.ws_handler(self, path)
  File "./server_test.py", line 7, in layer_server
    async for msg in websocket:
  File "/usr/local/lib/python3.6/site-packages/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/usr/local/lib/python3.6/site-packages/websockets/exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

To reproduce, run the following Python:

```
#!/usr/bin/env python3

import asyncio
import websockets

async def layer_server( websocket, path ):
    async for msg in websocket:
        print( msg )

port_websocket = 9988
print("WebSocket server on port", port_websocket )
start_server = websockets.serve( layer_server, 'localhost', port_websocket )
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

Then in a browser:

```
var socket = new WebSocket( "ws://localhost:9988" );
socket.binaryType = 'arraybuffer';
var data = new Uint8Array(1000*1000);
// Works fine with the default.
socket.send(data);
// Produces the error unless `max_size` is raised.
data = new Uint8Array(1000*1000*10);
socket.send(data);
```

To fix, replace `start_server` with `start_server = websockets.serve( layer_server, 'localhost', port_websocket, max_size = None )`.

**Comment by yig** [comment]
I think this is not a duplicate, because the cause is different (max size too small vs network connection is dropped).

Is the security vulnerability you are referring to a denial of service attack by sending a very large file? That's not a concern. This is an entirely local application broken up into an HTML/JavaScript GUI with a python computation back-end. The websocket only listens on localhost. If the user wants to denial of service themselves, that is their prerogative 😄.

**Comment by aaugustin** [comment]
Yes, it's a different scenario, however there may be a common cause. Or may not :-)

Yes, that's the vulnerability I was referring to. Your first message didn't provide any context and developers tend to copy-paste whatever they see on the Internet without thinking about the consequences....

**Comment by aaugustin** [comment]
The error has improved somewhat on master.

Reproduction instructions:

Run this Python script:

```python
#!/usr/bin/env python3

import asyncio
import logging
import websockets

logging.basicConfig(level=logging.DEBUG)

async def layer_server( websocket, path ):
    async for msg in websocket:
        print( msg )

port_websocket = 9988
print("WebSocket server on port", port_websocket )
start_server = websockets.serve( layer_server, 'localhost', port_websocket , max_size=10, compression=None)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

Execute these two lines in a browser console (one by one - the connection needs a few milliseconds to open)

```js
var socket = new WebSocket( "ws://localhost:9988" );
socket.send(new Uint8Array(100));
```

This results in:

```
WebSocket server on port 9988
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:websockets.protocol:server - state = CONNECTING
DEBUG:websockets.protocol:server - event = connection_made(<_SelectorSocketTransport fd=10 read=idle write=<idle, bufsize=0>>)
DEBUG:websockets.protocol:server - state = OPEN
DEBUG:websockets.protocol:server ! failing WebSocket connection: 1009
DEBUG:websockets.protocol:server - state = CLOSING
DEBUG:websockets.protocol:server > Frame(fin=True, opcode=8, data=b'\x03\xf1', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:server x half-closing TCP connection
DEBUG:websockets.protocol:server - event = eof_received()
DEBUG:websockets.protocol:server - event = connection_lost(None)
DEBUG:websockets.protocol:server - state = CLOSED
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/Users/myk/Documents/dev/websockets/websockets/server.py", line 135, in handler
    yield from self.ws_handler(self, path)
  File "issue-368.py", line 9, in layer_server
    async for msg in websocket:
  File "/Users/myk/Documents/dev/websockets/websockets/py36/protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "/Users/myk/Documents/dev/websockets/websockets/protocol.py", line 337, in recv
    yield from self.ensure_open()
  File "/Users/myk/Documents/dev/websockets/websockets/protocol.py", line 494, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
DEBUG:websockets.protocol:server ! failing WebSocket connection: 1011
```

There are three error codes mentioned here: 1009 (correct), 1006 and 1011.

The error message doesn't show the root cause; it should.

Additional improvements may be possible.

**Comment by aaugustin** [comment]
This reveals an interesting design issue.

`transfer_data` reads frames and puts them into a queue where `recv` can get them. If `transfer_data` hits an exception, it fails the connection and, only for unknown exceptions, logs an error.

Could it inject an exception into the queue so the next `recv` raises it? Should it?

**Comment by aaugustin** [comment]
Here's a pure Python reproduction.

Server:

```python
#!/usr/bin/env python3

import asyncio
import logging

import websockets

logging.basicConfig(level=logging.DEBUG)

async def handler(websocket, path):
    async for msg in websocket:
        print(msg)

asyncio.get_event_loop().run_until_complete(
    websockets.serve(
        handler, 'localhost', 8765,
        max_size=10, compression=None,
    )
)
asyncio.get_event_loop().run_forever()
```

Client:

```python
#!/usr/bin/env python3

import asyncio
import logging

import websockets

logging.basicConfig(level=logging.DEBUG)

async def send_msg():
    async with websockets.connect('ws://localhost:8765/') as websocket:
        await websocket.send('a' * 20)


asyncio.get_event_loop().run_until_complete(send_msg())

```

The client exits cleanly when the server closes the connection with code 1009.

The server exits messily as above. The only hint about the cause of the error is "! failing WebSocket connection: 1009"

**Comment by aaugustin** [comment]
`recv()` now raises a `ConnectionClosed` exception which is the documented behavior in that case.

However the `ConnectionClosed` exception reports an incorrect close code:

`websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason`

**Comment by aaugustin** [comment]
So here's what happens:

- the server receive a frame that's bigger than what it's willing to accept
- it stops reading incoming data and thus never receives a close frame from the client
- per the spec, if no close frame is received, the close code is 1006

https://tools.ietf.org/html/rfc6455#section-7.1.5:

> If _The WebSocket Connection is Closed_ and no Close control frame was received by the endpoint (such as could occur if the underlying transport connection is lost), _The WebSocket Connection Close Code_ is considered to be 1006.

To sum up, there are two problems:

1. Logging a `ConnectionClosed` exception with a close code at https://github.com/aaugustin/websockets/blob/9b0929582874cab3b3d18e283a841c43fd198eaf/websockets/server.py#L140 isn't sufficient to indicate the cause of the failure. When `transfer_data` catches an error, either that error should be logged, or the next `recv()` should raise a more specific exception. The latter seems more discoverable.

2. Failing the connection with code 1011 at https://github.com/aaugustin/websockets/blob/9b0929582874cab3b3d18e283a841c43fd198eaf/websockets/server.py#L141 when the connection was already failed doesn't seem necessary. Probably it doesn't hurt, but it pollutes the logs. This requires additional investigation.

**Comment by yig** [comment]
This is great! It's nice to see such an active project.
