### ISSUE TITLE
Example of exception handling

### ISSUE THREAD

**Issue by ddehghan** [aaugustin/websockets#369]
I can't find anywhere any example of how to handle "Invalid handshake" errors. If you go directly to the websocket server with a browser it wont be able to upgrade the connection to a socket and throws and exception. I am not sure where/how to catch that exception. It would be very helpful to add an example for this. 

> Invalid handshake
> Traceback (most recent call last):
>   File "/Users/david/.pyenv/versions/venv-3.6.4-dm-socket/lib/python3.6/site-packages/websockets/handshake.py", line 85, in check_request
>     assert get_header('Upgrade').lower() == 'websocket'
> AssertionError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/david/.pyenv/versions/venv-3.6.4-dm-socket/lib/python3.6/site-packages/websockets/server.py", line 88, in handler
>     extra_headers=self.extra_headers,
>   File "/Users/david/.pyenv/versions/venv-3.6.4-dm-socket/lib/python3.6/site-packages/websockets/server.py", line 437, in handshake
>     key = check_request(get_header)
>   File "/Users/david/.pyenv/versions/venv-3.6.4-dm-socket/lib/python3.6/site-packages/websockets/handshake.py", line 93, in check_request
>     raise InvalidHandshake("Invalid request") from exc
> websockets.exceptions.InvalidHandshake: Invalid request

```

import asyncio
import websockets

async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)

asyncio.get_event_loop().run_until_complete(
    websockets.serve(echo, 'localhost', 8765))
asyncio.get_event_loop().run_forever()
```

Above is the simple echo code. If you browse to it with http://localhost:8756 you get that exception

**Comment by ddehghan** [comment]
this is also necessary when a crawler decides to visit your dns name and causes a lot of 404s which would cause exceptions and cause pain for whomever is handling the server alerts. 

a catch all handler to handle all the http traffic and server 404 would be very helpful.

**Comment by aaugustin** [comment]
It would be nice to handle such requests a bit more gracefully.

In the current version of websockets, you can write a WebSocketServerProtocol subclass and override [process_request](https://websockets.readthedocs.io/en/stable/api.html#websockets.server.WebSocketServerProtocol.process_request) to respond 404 to any request that doesn't contain a suitable `Upgrade` header.

**Comment by aaugustin** [comment]
#393 should address this comprehensively. Let me know if you have feedback on that PR. Thanks!

**Comment by ddehghan** [comment]
great. returning 426 is a good idea.
