### ISSUE TITLE
Example of non-blocking WebSocket client

### ISSUE THREAD

**Issue by mcguipat** [aaugustin/websockets#370]
I would be interested to see an example implementation using the `websockets` library of the async client that is described in the below thread using the `websocket-client` library.  
https://stackoverflow.com/questions/29145442/threaded-non-blocking-websocket-client?rq=1&utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by aaugustin** [comment]
```python
#!/usr/bin/env python

import asyncio
import websockets

async def hello():
    async with websockets.connect('ws://echo.websocket.org/') as websocket:
        for i in range(100):
            await asyncio.sleep(1)
            websocket.send("Hello %d" % i)

asyncio.get_event_loop().run_until_complete(hello())
```

(untested, but should work)

Find more examples in the docs: http://websockets.readthedocs.io/en/stable/intro.html#common-patterns
