### ISSUE TITLE
Support basic auth in client

### ISSUE THREAD

**Issue by koliyo** [aaugustin/websockets#373]
It does not seem possible to connect to a server using basic auth?

For example:
```
websockets.connect('wss://myuser:mypass@myserver.com')
```

**Comment by aaugustin** [comment]
Indeed this isn't supported right now.

This paragraph of the RFC says this feature may be implemented:

>    12.  The request MAY include any other header fields, for example,
>         cookies [RFC6265] and/or authentication-related header fields
>         such as the |Authorization| header field [RFC2616], which are
>         processed according to documents that define them.

----

In the meantime, you can add the basic auth header yourself with the `extra_headers` argument to [connect](http://websockets.readthedocs.io/en/stable/api.html#websockets.client.connect).

Roughly it should look like this:

```python

from base64 import b64encode

def basic_auth_header(username, password):
    assert ':' not in username
    user_pass = f'{username}:{password}'
    basic_credentials = b64encode(user_pass.encode()).decode()
    return ('Authorization', f'Basic {basic_credentials}')

websockets.connect(
    'wss://myserver.com',
    extra_headers=[basic_auth_header('myuser', 'mypass')],
)
```

**Comment by aaugustin** [comment]
If you can confirm that my proposal above works, that's helpful.

**Comment by koliyo** [comment]
Yes, that works! Thanks for the help! Would be great if the `connect` call did this header setup automatically.

**Comment by aaugustin** [comment]
@koliyo PR #374 implements this feature.

If you're able to remove the solution I suggested above, to try that patch and to confirm that it does the job, that's much appreciated.

Assuming you're using a virtualenv (or something built on top such as virtualenvwrapper or pipenv), you can test the patch that way:

```
cd $VIRTUAL_ENV/lib/python3.6/site-packages  # adjust the Python version number if needed
curl https://patch-diff.githubusercontent.com/raw/aaugustin/websockets/pull/374.diff | patch -p1
```

Then `pip uninstall websockets; pip install websockets` to restore the original version.

**Comment by messense** [comment]
I think you can simply use `pip install -U https://github.com/aaugustin/websockets/archive/client-basic-auth.zip` to try #374

**Comment by nesttle** [comment]
> Indeed this isn't supported right now.
> 
> This paragraph of the RFC says this feature may be implemented:
> 
> > 1. The request MAY include any other header fields, for example,
> >    cookies [RFC6265] and/or authentication-related header fields
> >    such as the |Authorization| header field [RFC2616], which are
> >    processed according to documents that define them.
> 
> In the meantime, you can add the basic auth header yourself with the `extra_headers` argument to [connect](http://websockets.readthedocs.io/en/stable/api.html#websockets.client.connect).
> 
> Roughly it should look like this:
> 
> ```python
> from base64 import b64encode
> 
> def basic_auth_header(username, password):
>     assert ':' not in username
>     user_pass = f'{username}:{password}'
>     basic_credentials = b64encode(user_pass.encode()).decode()
>     return ('Authorization', f'Basic {basic_credentials}')
> 
> websockets.connect(
>     'wss://myserver.com',
>     extra_headers=[basic_auth_header('myuser', 'mypass')],
> )
> ```

Looks working OK on client side. My question is how to retrieve and check in server side? 
Would be nice to see an example like client_headers.py and server_headers.py to check the correct method to implement headers on both sides.

Thanks and great job! @aaugustin

**Comment by aaugustin** [comment]
It's slightly more complicated than it should be...

**Server**

```python
from websockets.headers import build_basic_auth  # private API!

import asyncio
import http
import websockets

USERNAME = 'foo'
PASSWORD = 'bar'
AUTHORIZATION = build_basic_auth(USERNAME, PASSWORD)


class BasicAuthServerProtocol(websockets.WebSocketServerProtocol):

    async def process_request(self, path, request_headers):
        print("HTTP connection")
        try:
            authorization = request_headers['Authorization']
        except KeyError:
            return http.HTTPStatus.UNAUTHORIZED, [], b'Missing credentials\n'
        if authorization != AUTHORIZATION:
            return http.HTTPStatus.FORBIDDEN, [], b'Incorrect credentials\n'


async def run(ws, path):
    print("WS connection")


async def start():
    await websockets.serve(
        run, '0.0.0.0', 3737, create_protocol=BasicAuthServerProtocol)


asyncio.get_event_loop().run_until_complete(start())
asyncio.get_event_loop().run_forever()
```

**Client**

```python
import asyncio
import websockets

async def run():
    async with websockets.connect('ws://foo:bar@localhost:3737') as websocket:
        pass

asyncio.get_event_loop().run_until_complete(run())
```

**Comment by aaugustin** [comment]
Let's follow up in #492.

**Comment by Sikkafalibagivar** [comment]
system/priv-app/GoogleExtServices/GoogleExtServices.apk
