### ISSUE TITLE
How to open multiple clients?

### ISSUE THREAD

**Issue by exostieStevelo** [aaugustin/websockets#382]
Do you have something example to open multiple clients?

I try something like this:

    async def hello(location):
        async with websockets.connect(location) as websocket:
            name = input("What's your name? ")
            await websocket.send(name)
            print("> {}".format(name))

            greeting = await websocket.recv()
            print("< {}".format(greeting))

    asyncio.get_event_loop().run_until_complete(hello(locationA))
    asyncio.get_event_loop().run_until_complete(hello(locationB))

I will get errors:

    error connect Malformed HTTP message
    error connect Malformed HTTP message
    error connect Malformed HTTP message
    error connect Malformed HTTP message
    error connect Malformed HTTP message
    error connect Malformed HTTP message
    error connect Malformed HTTP message
    error connect Malformed HTTP message

**Comment by exostieStevelo** [comment]
@aaugustin  thanks you reply. I went clients connected in parallel at the same time.
in this example only one it will be fine. 

    asyncio.get_event_loop().run_until_complete(hello(locationA))

**Comment by aaugustin** [comment]
That's really a question about asyncio, not about websockets. Take a look at `asyncio.ensure_future` or `asyncio.wait` and related APIs.

(I'm still unsure of how that question is related to the error messages you showed in your original message.)

**Comment by exostieStevelo** [comment]
@aaugustin  thanks. I will try to dig more about asyncio.
