### ISSUE TITLE
Ping at scheduled intervals

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#383]
We could add a `ping_interval` argument to the protocol.

When set, the protocol would start a task to send a ping at regular intervals.

This can help to keep connections open, especially across proxies with short timeouts.

This task would be a simple as:

```python
while self.open:
    yield from asyncio.sleep(self.ping_interval)
    yield from self.ping()
```

As a bonus, we could kill the connection if no pong is received in one `ping_interval`.

**Comment by bmoscon** [comment]
I'd love to see this - I did something very similar for a project that uses this library, so its definitely useful

**Comment by RemiCardona** [comment]
On our project, we already have something really similar, but with automatic reconnection. I fail to see how I could reuse what is proposed here without reimplementing the whole method/function to fit out own needs.

Don't get me wrong, I'm not opposed to websockets having support for something like this, I just wanted to say that, in my case, I most likely wouldn't be able to use it as proposed. However, I definitely see use for this.

Cheers

**Comment by cjerdonek** [comment]
As an alternative, since it's so simple, it might be useful to start out by documenting the pattern. Also, for people calling a websockets server from a browser, the same pattern using Javascript would be similarly useful.

**Comment by RemiCardona** [comment]
While the ping mechanism is officially part of the protocol spec, there's no official API to access it from the JS/browser side. It's up to browsers to figure if/when to initiate pings or pongs to check the connection status.

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by cjerdonek** [comment]
Yes, I was just suggesting that, if sample code is provided to show how to ping at regular intervals using Python to keep a connection alive, then it could also be useful to provide such sample code for Javascript -- even if there is no "canonical" solution due to the lack of an API.

**Comment by aaugustin** [comment]
@RemiCardona To signal to the application that the connection is lost, we can provide a Future and complete it when a ping times out. Then it's up to the application to close and reopen the connection (only on the client side).

I think we don't enforce enough structure to handle this automatically.

I don't believe we can inject an exception either — see #338 for a discussion of cancelling the connection handler (on the server side) when the connection is close, a more basic situation than the one we're discussing here.

**Comment by vgoklani** [comment]
Hey - has this been implemented? Please add :) Thanks!

**Comment by aaugustin** [comment]
This issue is open, which means this feature hasn't been implemented yet.

**Comment by aaugustin** [comment]
I proposed an implementation of this feature in #449.

It only deals with sending pings regularly, not with automatic reconnection — that's #414. However, if automatic reconnection is implemented, this feature will make it more reliable because it will detect connection failures more eagerly.

**Comment by aaugustin** [comment]
I would very much appreciate feedback on my PR, especially if you can test it in realistic circumstances and report whether it behaves cleanly.

**Comment by vgoklani** [comment]
testing now :) how do I change the ping message?

**Comment by aaugustin** [comment]
(You can send a ping with a specific payload if you want to with the `ping` API, but that's another story.)

**Comment by aaugustin** [comment]
I added tests and improved the pull request. I think it's ready to merge.

I'm still looking for a code review and/or reports of whether it works well.
