### ISSUE TITLE
Ending pending tasks properly

### ISSUE THREAD

**Issue by ianks** [aaugustin/websockets#39]
I am writing a small script and would like to know how to properly deal with the scenario that the server exits while client is still connected. The idea is to catch SIGINT, close server, loop, and wait for pending tasks to complete before exiting. Right now, I run into this error:

```
Task was destroyed but it is pending!
task: <Task pending coro=<run() done, defined at /home/vagrant/.pyenv/versions/3.4.2/lib/python3.4/site-packages/websokets/protocol.py:222> wait_for=<Future pending cb=[Task._wakeup()]>>
```

Here is my current script. Thank you very much for your work, this library has been nice!

```python
@asyncio.coroutine
def handler(websocket, path):
    while True:
        if not websocket.open:
            break

        yield from websocket.send("Hello!")
        yield from asyncio.sleep(1.0)

def boot_server(host, port):
    print('Atlas server is listening on http://', host, ':', port, sep='')

    return websockets.serve(handler, host, port)

def main():
    server = boot_server('0.0.0.0', 8765)
    event_loop = asyncio.get_event_loop()

    try:
        event_loop.run_until_complete(server)
        event_loop.run_forever()
    except KeyboardInterrupt:
        print('\nCtrl-C (SIGINT) caught. Exiting...')
    finally:
        server.close()
        event_loop.close()

if __name__ == "__main__":
    main()
```

**Comment by sgould420** [comment]
Hi I am having a similar problem. I want to properly shutdown my websocket server,

I have something like this :

loop = asyncio.get_event_loop()
start_server = websockets.serve(websocketHandler, '127.0.0.1', 5678)
loop.run_until_complete(start_server)
try:
     loop.run_forever()
finally:
     start_server.close()
     loop.run_until_complete(start_server.wait_closed())

I am running the above code in it's own thread, and made loop global. 
If I call  "loop.call_soon_threadsafe(loop.stop)" from somewhere else  in my program,  then the code under "finally:" executes, but I get this error:
    loop.run_until_complete(start_server.wait_closed())
AttributeError: 'generator' object has no attribute 'wait_closed'

Why can't I use wait_closed()?

**Comment by aaugustin** [comment]
In your example, it's the return value of `loop.run_until_complete(start_server)` which has a `wait_closed` method, not `start_server`.

**Comment by sgould420** [comment]
Ahhhh.. Ok, I was confused because the examples do not  use a return value from ```asyncio.get_event_loop().run_until_complete(start_server)``` for anything, and the API docs say that ```serve()``` yields a Server which provides ```close()``` method and  a ```wait_closed()``` coroutine. 
So in my example I am not sure exactly what ```start_server``` really is, and why the server itself is really retuned by ```loop.run_until_complete(start_server)```.   I am obviously new to asyncio, event loops, and websockets..

But anyhow,  I changed my code to:
```python
loop = asyncio.get_event_loop()
start_server = websockets.serve(websocketHandler, '127.0.0.1', 5678)
websocketServer = loop.run_until_complete(start_server)
try:
     loop.run_forever()
finally:
     websocketServer.close()
     loop.run_until_complete(websocketServer.wait_closed())
```
And now it works! Thank you!

**Comment by aaugustin** [comment]
Yes there's a problem of vocabulary... "yields a Server" means you must "yield from" (or "run_until_complete") to get the Server instance.
