### ISSUE TITLE
How to keep connection alive?

### ISSUE THREAD

**Issue by milteven12** [aaugustin/websockets#398]
Hello, i'm trying to build a simple server-client script that continuosly send messages to a client connected but In the example the client connection is always closed after sending the first message.
Does anyone know how to do it?

Thank you.

**Comment by aaugustin** [comment]
Duplicate of #83. Keeping open as a documentation issue.

**Comment by aaugustin** [comment]
In fact documentation seems already adequate:

> You will usually want to process several messages during the lifetime of a
> connection. Therefore you must write a loop.
