### ISSUE TITLE
Refactor tests as "test coroutines"

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#403]
With a decorator to execute them in run_until_complete.

Suggested by @cjerdonek in #310 — which was originally about another issue, so I'm filing this new issue for clarity. See that PR for details.

**Comment by aaugustin** [comment]
I took a stab at this. It makes tests _more_ difficult to write because the event loop is constantly running. It isn't possible to run it a bit, make checks or changes, run it a bit more, etc.

Even though #516 looks like it shouldn't change the behavior, in practice some code paths that used to be covered aren't covered anymore.

**Comment by cjerdonek** [comment]
I would recommend doing this incrementally. For example, it might be the case that 80-90% of the tests convert fine in straightforward fashion. For the rest, it might take more work, or perhaps just a different approach or way of thinking to cover the same edge cases. Focusing first on the easier cases will give you time to think about handling the remainder. I would be surprised if any code paths can't be handled elegantly with this approach (setting aside things like testing starting the loop itself, which I would view as out of scope). It's more a matter of finding the right way to look at it.

**Comment by RemiCardona** [comment]
just catching up to this issue: did you take a look at asynctest? Or even pytest-asyncio?

At work we've used asynctest extensively and it's quite nice to use. Since we're going the pytest route, we've also been looking at pytest-asyncio which is clearly lacking a lot of asynctest features, but it does have a lot of potential.

Would you be interested in PRs going in either direction?

**Comment by aaugustin** [comment]
#630 feels like an improvement.

Also, I couldn't resist the temptation of magic :-)

**Comment by aaugustin** [comment]
@RemiCardona Well, I built independently the subset of asynctest that I needed. It's about 50 lines so there isn't much to gain by replacing it by a dependency.

**Comment by aaugustin** [comment]
`test_protocol` and `test_client_server` might look better with asynctest. However, I'm not sure I want to spend time rewriting them...

**Comment by aaugustin** [comment]
Hmm, I'm not a fan of how asynctest copy-pasted most of `TestCase.run`... I think I'll keep my cool little hack :-)

**Comment by cjerdonek** [comment]
@aaugustin FWIW, I think what you did is good. Keep it light-weight..

**Comment by aaugustin** [comment]
Thanks! I'm going to merge it, then.

**Comment by aaugustin** [comment]
`test_client_server` and `test_protocol` are the two big targets here.

**Comment by aaugustin** [comment]
I'm never going to do a huge test refactor in the legacy module, so closing this.

I'll use the better approach in new asyncio code only.
