### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#405]
Add it to the testing matrix when it's supported on CircleCI... For now I'm removing that change from #404.

**Comment by aaugustin** [comment]
I had to revert #404 because of #411.

The following code seems to work on Python 3.4 - 3.7:

```diff
diff --git a/websockets/client.py b/websockets/client.py
index 92f29e9..87f9e28 100644
--- a/websockets/client.py
+++ b/websockets/client.py
@@ -393,23 +393,26 @@ class Connect:
     def __aexit__(self, exc_type, exc_value, traceback):
         yield from self.ws_client.close()

-    def __await__(self):
-        transport, protocol = yield from self._creating_connection
+    async def __await__impl__(self):
+        transport, protocol = await self._creating_connection

         try:
-            yield from protocol.handshake(
+            await protocol.handshake(
                 self._wsuri, origin=self._origin,
                 available_extensions=protocol.available_extensions,
                 available_subprotocols=protocol.available_subprotocols,
                 extra_headers=protocol.extra_headers,
             )
         except Exception:
-            yield from protocol.fail_connection()
+            await protocol.fail_connection()
             raise

         self.ws_client = protocol
         return protocol

+    def __await__(self):
+        return self.__await__impl__().__await__()
+
     __iter__ = __await__

```

It's... less than elegant.

As far as I understand, the problem is:

- We're still sticking with `@asyncio.coroutine` and `yield from` in order to support Python 3.4;
- In Python 3.7, `__await__` no longer supports `yield from`, from reasons not entirely clear to me, perhaps related to the removal of backwards compatibility features added in Python 3.5 when implementing PEP 492.

**Comment by aaugustin** [comment]
Mabye the best way to fix this would be:

- To define `__iter__` as the current implementation of `__await__` (instead of `__iter__ = __await__`)
- To move the definitons of `__aenter__`, `__aexit__` and `__await__` to a module that is only imported on Python 3.5+ and to monkey-patch them on the `Connect` and `Serve` classes

**Comment by cjerdonek** [comment]
I did some investigation of the failing test case. What seems to have changed is that `self._creating_server` here:

https://github.com/aaugustin/websockets/blob/a6211d48c57a0886ee1eefa87651c99bd08d4fd2/websockets/server.py#L725

is a generator object in 3.6 and a coroutine object in 3.7. The `_creating_server` value is the return value of `loop.create_server()`. The 3.7 CPython change is here:

https://github.com/python/cpython/commit/5f841b553814969220b096a2b4f959b7f6fcbaf6

I'm guessing this will help locate a simpler fix. I'm posting this before thinking about alternative fixes.

**Comment by cjerdonek** [comment]
PS - I think you might have a bug here in 3.6 and 3.7:

https://github.com/aaugustin/websockets/blob/458169b1c8ce692633d9bf90e8474c249936d49d/websockets/test_client_server.py#L1065-L1068

I think the import is silently failing due to a circular import in the module being imported, but it may not be affecting things because the tests are getting imported successfully elsewhere. I'm not quite sure, but something seems fishy.

**Comment by cjerdonek** [comment]
Also, to add to my second last comment, there's a similar issue on the client side with `self._creating_connection` I believe.

**Comment by cjerdonek** [comment]
Is there a way to move away from requiring the use of `__await__()` for the API?

**Comment by aaugustin** [comment]
Tests run as expected on Python 3.5 and 3.5.1:

```
(websockets-5Rx74wXk) myk@mYk:dev/websockets ‹py37›$ pyenv shell 3.5.0
(websockets-5Rx74wXk) myk@mYk:dev/websockets ‹py37*›$ python3.5 -m unittest websockets/test_client_server.py
ss......................................................................sss...................................................................
----------------------------------------------------------------------
Ran 142 tests in 0.851s

OK (skipped=5)
(websockets-5Rx74wXk) myk@mYk:dev/websockets ‹py37*›$ pyenv shell 3.5.1
(websockets-5Rx74wXk) myk@mYk:dev/websockets ‹py37*›$ python3.5 -m unittest websockets/test_client_server.py
..............................................................................................................................................
----------------------------------------------------------------------
Ran 142 tests in 0.880s

OK
(websockets-5Rx74wXk) myk@mYk:dev/websockets ‹py37*›$
```

**Comment by aaugustin** [comment]
I don't think we can move away from `__await__` because we want the same API to be awaitable and usable as an async context manager, thus we need to implement everything as methods on a class.

**Comment by aaugustin** [comment]
Version 6.0 adds support for Python 3.7 and is now available on PyPI: https://pypi.org/project/websockets/6.0/#files
