### ISSUE TITLE
Listen to multiple connections?

### ISSUE THREAD

**Issue by WurtzJd** [aaugustin/websockets#412]
First, thanks for sharing your work, it is extremely useful.

I am having problem to understand how to open and listen to multiple connections at the same time, without missing any messages. The way I understand Asyncio, we can simulate parallel programming but fundamentally events still occur one after the other. So if messages arrive on two connections at the same time, one of them will be missed.

What am I missing here?
Many thanks

**Comment by aaugustin** [comment]
asyncio.create_server takes care of this. It keeps track of all connections and lets your app deal with incoming data on each connection, one after the other.

You may be missing the fact that the OS buffers incoming data and the application can read it at any time later.

**Comment by WurtzJd** [comment]
Yes it is the OS buffer that I am missing. How can it receive multiple message at the same time? Can it still do it on a single-core processor?

**Comment by aaugustin** [comment]
Each TCP connection has its own buffer.

On a single core processor you can't run threads on parallel.

On a multi core processor it's often easier to use multiple processes than multiple threads, as having two in-process concurrency mechanisms (coroutines and threads) can become complicated quickly.

**Comment by WurtzJd** [comment]
Ok I don t get everything but I know where to dive now, thanks a lot.

**Comment by WurtzJd** [comment]
I have a code listening from two Binance streams. Each stream send data every second. All is good and I receive "simultaneously" the messages. 

Now the following thing confuses me: if I add a sleeping time of 5 seconds after a message is received, I lose the messages that arrive during this sleeping time. It is concerning because it means that if I am to slow to process incoming messages, I will lose messages. Is there any way to prevent this by using a buffer?

`import asyncio
import websockets
import json

async def listen(ws_address):
    async with websockets.connect(ws_address) as websocket:
        while True:
            event = json.loads(await websocket.recv())
            
async def main():
    
    ws_address1 = 'wss://stream.binance.com:9443/ws/ethbtc@depth5'
    ws_address2 = 'wss://stream.binance.com:9443/ws/xrpbtc@depth5'
    
    tasks = [asyncio.ensure_future(listen(ws_address1)), asyncio.ensure_future(listen(ws_address2))]
    await asyncio.gather(*tasks)
    
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()`

**Comment by aaugustin** [comment]
I have to walk away from the discussion. I'm not contributing to heating the planet with cryptomining.

**Comment by aaugustin** [comment]
;-)

**Comment by echo-ray** [comment]
@WurtzJd 
Hi~ 
Did you find any solutions? 
Binance's websocket is really much different from other exchanges.

**Comment by aaugustin** [comment]
You could also do everything in coroutines and use `run_in_executor` for interacting with the database.

**Comment by WurtzJd** [comment]
This is indeed what I am doing, sorry I forgot to mention that my database thread is done via run_in_executor
