### ISSUE TITLE
[Suggestion] Echo server demo not compatibility with python 3.5

### ISSUE THREAD

**Issue by extraymond** [aaugustin/websockets#416]
It would be nice to have a working example for people under 3.6.

This is how I get it working with 3.5.
First make an iterable object, bind the socket to it, and for every next iter, I will await on the socket.recv().

```python
class IterSocket:
    def __init__(self, socket):
        self.socket = socket

    def __aiter__(self):
        return self

    async def __anext__(self):
        return await self.socket.recv()
```

And finally, just wrap the websocket instance in this IterSocket object, and the rest is all the same in the docs.

```python
async def echo(websocket, path):
    async for message in IterSocket(websocket):
        await websocket.send(message)
```

Hope someone find this useful.

**Comment by aaugustin** [comment]
We might be able to implement support for `async for` in Python 3.5.

It could become complicated to keep everything straight on all Python versions, though.

**Comment by aaugustin** [comment]
The difficulty comes from writing something that works on all supported Python versions.

I think it will be easier after dropping support for Python 3.4, when we can use async / await.

**Comment by calid** [comment]
I'm going to second this.  A lot of popular distros still ship with 3.5 and it would be nice to have have examples that work out of box for people without requiring building and installing a custom python.

**Comment by extraymond** [comment]
Another reason to have 3.5 checked is for pypy, they are still on 3.5.

**Comment by aaugustin** [comment]
Python 3.5 isn't supported any longer in the master branch.
