### ISSUE TITLE
Allow to pass event loop into websockets.serve()

### ISSUE THREAD

**Issue by rielsi** [aaugustin/websockets#42]
```websockets``` does not currently allows us to explicitly pass an event loop instance into ```websockets.serve()```. Subsequent call to ```create_server()``` relies on existence of the default event loop, which is, however, not guaranteed, even in the main thread, since the calling code may deliberately suppress invoking of default event loop. According to PEP 3156:
> It is okay to set the current event loop to None , in which case subsequent calls to get_event_loop() will raise an exception. This is useful for testing code that should not depend on the existence of a default event loop.

Also see  https://www.python.org/dev/peps/pep-3156/#passing-an-event-loop-around-explicitly  

Most of ```asyncio``` calls allow us to explicitly pass an event loop instance via the keyword-only ```loop``` argument. Please consider implementing such argument on ```websockets.serve()``` to benefit the code that not relies on the existence of the default event loop.

**Comment by aaugustin** [comment]
Passing a `loop` argument to `serve` should be working with the current code.

The [documentation](http://aaugustin.github.io/websockets/#websockets.server.serve) says:

> extra keyword arguments are passed to create_server.

Can you clarify what problem you're encountering when passing a `loop` argument?

**Comment by rielsi** [comment]
The problem is, ```create_server()``` does not expects the ```loop``` kwarg at all, instead ```create_server()``` _is_ the method of loop - and the loop instance being used is always the default one. Please take a look at the ```websocket```'s ```server.py``` lines 161-162:
```python
    return (yield from asyncio.get_event_loop().create_server(
            factory, host, port, **kwds))
```
As you can see, it's the default event loop that get used to ```create_server()```
These lines should read like these:
```python
    if not loop:
        loop = asyncio.get_event_loop()
    return (yield from loop.create_server(factory, host, port, **kwds))
```
and the ```websockets.serve()``` signature should be along these lines (please notice the ```loop``` kwarg):
```python
@asyncio.coroutine
def serve(ws_handler, host=None, port=None, *,
          klass=WebSocketServerProtocol, origins=None, loop=None, **kwds):
...
```

**Comment by aaugustin** [comment]
Ah, now I understand. Thanks for clarifying.

**Comment by aaugustin** [comment]
Can you check if this pull request helps?
