### ISSUE TITLE
Passing cookie through python websocket client

### ISSUE THREAD

**Issue by yjqiang** [aaugustin/websockets#420]
Can I pass cookie through websockets?

**Comment by aaugustin** [comment]
Yes, with `extra_headers=[('Cookie', '...')]`.

**Comment by yjqiang** [comment]
Thanks. And I want some more complete information, like cookies, origin and others. Where can I find these things?

**Comment by aaugustin** [comment]
Did you read the documentation before asking that question?

If not, you can find the answer by yourself. If yes, perhaps the documentation could be clarified.

**Comment by aaugustin** [comment]
https://tools.ietf.org/html/rfc6265#section-4.2

**Comment by yjqiang** [comment]
Thanks a lot

**Comment by Aran-Fey** [comment]
I still can't figure out how to do this. Searching the docs for "extra_headers" yields no useful results. The closest thing I could find is the "How do I get access HTTP headers, for example cookies?" section in the FAQ, but I want to *set* cookies, not *access* them.

The documentation related to headers is really very sparse.

**Comment by aaugustin** [comment]
Documentation is there: https://websockets.readthedocs.io/en/stable/api.html#websockets.client.connect

Use `websockets.connect(..., extra_headers={"Cookie": ...})`.

Would you mind filing a new ticket requesting better documentation around this? Probably worth adding to the FAQ, as it seems to come up once in a while.

**Comment by Aran-Fey** [comment]
I see, thanks. Weird that it doesn't show up in the search results.

Opened a new issue at #798.
