### ISSUE TITLE
How to exit loop running?

### ISSUE THREAD

**Issue by kuifu** [aaugustin/websockets#425]
I'm running websocket client in my MacOS. Everything is OK after running.
Then I shutdown the wifi connection for 10 seconds, and re-connect to wifi .
I found that my application is dead....

So, How to exit the loop event - run_forever()  in my own function? thanks.

```py

class WSS():
    WSS.wss_uri= 'wss://...'

    async def wss_main():
        async with websockets.connect(WSS.wss_uri)  as ws:
            async for message in ws:
                print(message)
                # If the network has some issue , I want to quit this loop. How to ?

def wss_run():
    running = False
    while True:
        if not running:
            try:
                running = True
                wss = WSS()
                asyncio.get_event_loop().run_until_complete(wss.wss_main())
                asyncio.get_event_loop().run_forever()
            except Exception as e:
                print(e)
                running = False
        time.sleep(1)

wss_run()
```

**Comment by kuifu** [comment]
Do you have any internal timeout parameter?
If the websocket is dead, how can I detect it and kill it?

```py
async for message in ws:
    print(message)
```

if websocket is frozen, this code will stop for ever. you can try shutdown you network for 10 seconds and re-enable it.

**Comment by aaugustin** [comment]
http://websockets.readthedocs.io/en/stable/cheatsheet.html#keeping-connections-open

**Comment by kuifu** [comment]
Thank you for your professional answer.
I helps too much!

**Comment by aaugustin** [comment]
Perhaps this is a duplicate of #414.

**Comment by kuifu** [comment]
I'm sorry to cost your working time. You answer really helped me. It's my fault that I didn't read the docs carefully.

In my mind, you can add more full samples to help others to use websockets. 

I just finished my program, can you help to put it on the site? Of course, you can help to review the code.

**Comment by aaugustin** [comment]
Thanks for clarifying :-) Sometimes it's hard to tell across the language barrier.
