### ISSUE TITLE
Timeout doesn't work on websockets.connect()

### ISSUE THREAD

**Issue by kuifu** [aaugustin/websockets#428]
Hi, I met a problem. my client was trying to connect to a websocket server. I had used the parameter timeout=60, but it doesn't work.

![websockets-timeout](https://user-images.githubusercontent.com/26201247/41498794-4c7804ec-71a8-11e8-9cd9-d4ee7987d119.png)

I hadn't seen any exceptions when the connect action got timeout.

**Comment by kuifu** [comment]
I'm sure the server is not working well, but how can I detect such timeout? the whole program is waiting ...

**Comment by kuifu** [comment]
[INFO][2018-06-16 20:33:48]:padchat_ws!
[WARN][2018-06-16 20:35:04]:run():[Errno 60] Connect call failed ('123.*.*.*', 7777)

Got an error number 60

**Comment by aaugustin** [comment]
Timeout only applies to the closing handshake:

> The timeout parameter defines the maximum wait time in seconds for completing the closing handshake and, only on the client side, for terminating the TCP connection. close() will complete in at most 4 * timeout on the server side and 5 * timeout on the client side.

**Comment by aaugustin** [comment]
You can wrap calls with `asyncio.wait_for` if you want to enforce a timeout. The timeout parameter in websockets is for operations that the library handles under the hood.

At first sight, only the closing handshake occurs without user control. The opening handshake (discussed here) and read / write operations are under user control and can be wrapped in asyncio.wait_for as needed.

So I'd say this is a documentation issue.

**Comment by kuifu** [comment]
So there is no way to detect a connect timeout? I have to wait the Error number 60 ?

**Comment by aaugustin** [comment]
`with asyncio.wait_for(connect(...))`

**Comment by kuifu** [comment]
OK. I got it. you are using asyncio.wait_for to solve a original websocket connect timeout. good idea. Thanks .

**Comment by aaugustin** [comment]
I'm going to reopen this issue because I think it's a common question and it deserves a paragraph in the documentation.

**Comment by Harishankar14** [comment]
Hey, thanks for this, i know it is indeed a bit old, if you don't mind, can u share me the paragraph mentioned and the docs too !!
