### ISSUE TITLE
Deployment tips to deal with a lot of connections

### ISSUE THREAD

**Issue by bsergean** [aaugustin/websockets#445]
Hi there,

I am thinking about the best way to handle a bunch of connections using the least amount of machines (2 to 4 beefy servers probably), and I wonder if folks here have insights. With http I've been using gunicorn which makes it very easy to use many cores, but I'm a bit lost with asyncio on how to use all my cores. My application will likely just push data into redis and do little CPU work, but if there are a bunch of connected clients cpu might become an issue.

I thought about running multiple servers on multiple ports, and use nginx who's serving on port 80 as a load-balancer + proxy_pass (is that even possible) to go to multiple daemon running the websockets app (something like [that](https://stackoverflow.com/questions/13240840/nginx-reverse-proxy-multiple-backends)?).

And then I'd have multiple services (each one, on a given machine, running under systemd) / each proxy_pass talk to one.

```
start_server = websockets.serve(hello, 'localhost', 8000) # for 'proxy_pass A'
start_server = websockets.serve(hello, 'localhost', 8001) # for 'proxy_pass B'
start_server = websockets.serve(hello, 'localhost', 8002) # for 'proxy_pass C, etc...'
```

I know it's a very vague question and not really an issue, but in absence of a better place to discuss this ... here we go !

Thanks,
- Benjamin

**Comment by bsergean** [comment]
I have to admit I got lazy and went with aiohttp... however I am still using websockets right now on the client side to try to generate a lot of connections. Not sure whether I can make that work with many process though, or if it's worth it.

I've also found a code example .. that I cannot find anymore where a specific socket option was used so that the same socket could be used by multiple forked process. I'll keep looking and I'll share it here.

**Comment by aaugustin** [comment]
So you deployed aiohttp with gunicorn?

**Comment by bsergean** [comment]
Yes they have a bunch of tutorials on how to do so, it's in their [doc](http://aiohttp.readthedocs.io/en/v0.18.2/gunicorn.html). And I haven't deployed anything at this point, it's still running locally but it 'works' (I can hit it with a test client).

Here is what it takes apparently to make a 'worker' that is compatible with gunicorn.
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/worker.py

I don't know what interface the 'app' needs to follow/implement so that gunicorn can 'run your code'.

**Comment by aaugustin** [comment]
In fact, if you're running a relatively recent Linux (>= 3.9), there's a very simple solution: use `serve(..., reuse_port=True)` and run as many websocket processes as you need.

If you run five copies of this script:

**slow_echo.py**

```python
#!/usr/bin/env python

# Script for testing parallel deployment (without burning CPU cycles).

import asyncio
import time
import websockets

DELAY = 0.1     # 100ms


async def slow_echo(websocket, path):
    async for message in websocket:
        time.sleep(DELAY)   # block the event loop to simulate CPU load
        await websocket.send(message)

asyncio.get_event_loop().run_until_complete(
    websockets.serve(slow_echo, 'localhost', 8765, reuse_port=True))
asyncio.get_event_loop().run_forever()
```

Then this script should complete in 2 seconds rather than 10 seconds:

**benchmark.py**

```python
#!/usr/bin/env python

# WS client example

import asyncio
import websockets

CLIENTS = 10
MESSAGES = 10


async def run_client(client):
    async with websockets.connect('ws://localhost:8765') as websocket:
        for message in range(MESSAGES):
            await websocket.send('{client}:{message}')
            await websocket.recv()


clients = [run_client(client) for client in range(CLIENTS)]
asyncio.get_event_loop().run_until_complete(asyncio.wait(clients))
```

Apparently this doesn't work on macOS: https://stackoverflow.com/questions/41247790/so-reuseport-on-macos-with-libuv#41479612

**Comment by aaugustin** [comment]
I tested the `reuse_port` technique on Linux. It's simple and it works.

It isn't ideal from a latency perspective under load, for reasons explained here: https://blog.cloudflare.com/the-sad-state-of-linux-socket-balancing/

**Comment by aaugustin** [comment]
In fact the Cloudflare blog post describes three deployment techniques and there's a reasonable way to implement them with websockets:

a. Single listen socket, single worker process => run a Python process. (This is also what you would do inside a container.)
b. Single listen socket, multiple worker processes => deploy nginx or haproxy in front of N Python processes listening on different ports. (This is the model with the most moving parts, but it's also a well known model for running web apps.)
(c) Multiple worker processes, each with separate listen socket => run N Python processes listening on the same port with the `reuse_port` option.

I think I'm going to document that.

**Comment by bsergean** [comment]
For simplicity, I was considering option 2 myself, with no nginx, but instead gunicorn forking multiple python process. We have a load-balancer that can redirected incoming connection (SSL) to any port, so I would make incoming connections go to port 8765 (one that can be 'created' without being superuser).

Actually gunicorn seems to also have an option to reuse ports.

```
reuse_port
~~~~~~~~~~

* ``--reuse-port``
* ``False``

Set the ``SO_REUSEPORT`` flag on the listening socket.

.. versionadded:: 19.8
```

On that Cloudflare blog post, they use an http benchmark and notice odd performance with option C, but I wonder if with persistent connections / websockets that would perform better.

**Comment by bsergean** [comment]
https://stackoverflow.com/questions/32661091/behavior-of-so-reuseaddr-and-so-reuseport-changed

Also on macOS there are 2 sockets options, maybe they have to be combined to provide that Linux behavior. But I'm not a socket expert at all so that stack-overflow comment is probably right...

**Comment by aaugustin** [comment]
The "odd performance" is increased variance in the latency for accepting connections. This is likely to be less a problem for websockets than for HTTP, if only because web pages rarely have multiple websocket requests on the critical path for rendering something in the browser.

**Comment by aaugustin** [comment]
And I'm pretty sure that `SO_REUSEADDR` doesn't matter here, we want `SO_REUSEPORT` and it doesn't do what we need on BSD.

**Comment by bsergean** [comment]
Hello, just to close the loop here I wanted to mention that I am now using docker + kubernete etc... and just simply spinning up more replicas/container instances, as you had mentioned earlier (the new fangled way !). It is a very simple and elegant way to scale I feel. Now I need to read up on the websockets doc a little more to tune how I can make sure my app doesn't run out of memory, when tons of new connections comes in, and instead reject them. I hope there's a way, and if there isn't we will just try to bump our replicas count until things settle for our load.

By browsing the web I've also came across something called [ASGI](https://asgi.readthedocs.io/en/latest/), which is an interface similar to WSGI / some people have already made it possible to run your websockets library through something called [uvicorn](https://www.uvicorn.org/), whose name sounds a lot like gunicorn... and another thing called [starlette](https://www.starlette.io/), so a bunch of options are available. At some point I built a little class interface myself, mostly ripped of aio-http so that I could use gunicorn.

Thanks a lot for all your hard work on this websockets library, it's great stuff !

**Comment by lgrahl** [comment]
We run several processes (one for each CPU core) of our server using websockets with different ports on each machine. Not with Gunicorn, just managing it with systemd. Since we want to terminate TLS anyway as Python isn't really great in that regard, we use nginx in front.

To distribute load, we prefix the hostname with a single byte (`ff.example.org`). This allows to distribute to up to 256 different hosts. Currently, we have split them into eight groups where four are running on one machine and the other four on another. On each machine, the four remaining groups are distributed to four processes. Clients will choose a random prefix.

uvloop and pypy would increase the serving pace with pretty much no effort required but we haven't had a need to deploy it so far.

**Comment by aaugustin** [comment]
@lgrahl Would you be willing to provide an appropriately anonymized version of your systemd config? I wanted to document that but I never implemented it.

**Comment by RemiCardona** [comment]
I should have chimed here: at work on one deployment we have close to a 500 "permanent" connections running off of 2 websockets servers, each in its own AWS VM, with Amazon's ELB doing TCP load balancing, and nginx handling TLS termination. (The connections are 3G/4G modems, so they go away and come back on all the time, which is a lot more work on the TLS side)

The server is running python 3.6, with python's default asyncio implementation, no uvloop, no forking, no threads. Each connection has a relatively low traffic, but times 500 those 2 servers do get a constant stream of work to do. I was worried about compression support in 5.0 but that turned out to be negligible overhead.

Those 2 servers definitely have headroom for sudden spikes of traffic, and usually the bottlenecks end up being in other parts of our system, with the websockets servers chugging along nicely.

**Comment by bsergean** [comment]
Chiming in (again ?) too.

We now have something exposed externally, for a subset of our users (3%) and started receiving live traffic 2 days ago.

We use kubernete, standard setup and I'm afraid I don't know all the details. What I know is that TLS is terminated at the load balancer (HAProxy ?), we use the RedHat version of kubernete (OpenShift). Right now we have around 1200 permanent connections, on 8 containers that have 1 full cpu and 1G of ram. (unrelated) There's a leak in my app btw and memory slowly goes up ... I need to figure this out.

Anyway, who said that Python cannot scale :) ?? !!

**Comment by lgrahl** [comment]
> @lgrahl Would you be willing to provide an appropriately anonymized version of your systemd config? I wanted to document that but I never implemented it.

Sorry for the delay. Yup, I'll add it to my to do list.

**Comment by sambeirne** [comment]
@aaugustin I came across this issue while looking for a simple deploy method. Based on the comments here and documentation for similar tools, I ended up using `systemd` and `nginx`. The anonymized version follows.

This is running on Debian 10. Default paths and users may be different on other distros. `www-data` is the nginx user if nginx is installed with apt.

The app is installed (`pip install -e .`) in a virtual environment in `/srv/app` with an [entry point](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html) in setup.py, so it can be started from the `venv/bin` folder. It takes a command line argument for the unix socket.

```bash
usage: app [-h] [-u UNIX_SOCKET]

Websocket Server

optional arguments:
  -h, --help            show this help message and exit
  -u UNIX_SOCKET, --unix-socket UNIX_SOCKET
                        UNIX domain socket
```

The app starts the server with `unix_serve`.

First, create a systemd service unit template for the app.

/etc/systemd/system/websocket@.service
```ini
[Unit]
Description=websocket daemon %i
After=network.target

[Service]
User=www-data
RuntimeDirectory=websocket
ExecStart=/srv/app/venv/bin/app -u /run/websocket/websocket%i.sock
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

Enable and start the service with `systemctl`. For the sake of this example, I'm starting two processes.

```bash
systemctl enable websocket@{1..2}.service
systemctl start websocket@{1..2}.service
```

Then configure nginx ([websocket proxying](http://nginx.org/en/docs/http/websocket.html), [using nginx as a load balancer](http://nginx.org/en/docs/http/load_balancing.html)).

/etc/nginx/sites-available/example.com.conf
```nginx
upstream websocket {
    least_conn;
    server unix:/run/websocket/websocket1.sock;
    server unix:/run/websocket/websocket2.sock;
}

server {
    listen         80;
    listen         [::]:80;
    server_name    example.com;

    location /socket/ {
        proxy_pass          http://websocket;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
    }
}
```
Enable the site and restart nginx.

```bash
ln -s /etc/nginx/sites-available/example.com.conf /etc/nginx/sites-enabled/
nginx -s reload
```

The proxy should be listening on `ws://example.com/socket/`.

One thing I might change is to have systemd also manage the socket, which would allow for better control over permissions; I'm running the app as the nginx user to avoid issues. However, [unix_serve](https://websockets.readthedocs.io/en/stable/api.html#websockets.server.unix_serve) assumes that `path` is not `None` and creates the socket when it starts. [loop.create_unix_socket](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_unix_server) appears to allow the path to be empty as long as the optional `sock` argument is provided.

**Comment by aaugustin** [comment]
Great! Thanks for sharing!

Whatever works for `loop.create_unix_server` should work for `unix_serve` as well. Please file an issue if it doesn't.

**Comment by sambeirne** [comment]
Awesome! That's my mistake. The `sock` argument does work.

In case it's helpful to anyone else, I put together a complete  copy/paste-able [example](https://gist.github.com/sambeirne/7a1ee751b3b3da80106c67f7c69582a8) with `systemd` socket activation.

**Comment by aaugustin** [comment]
Looks good!

**Comment by AmirHmZz** [comment]
@lgrahl @aaugustin According to my experience, using PyPy won't increase performance of websocket server. I've done a comparison between CPython and PyPy with a simple server application and here is the result :

- **CPython :** 20K clients >> CPU utilization ≈ **95%** & **600MB** ram
- **PyPY :** 18K clients >> CPU utilization = **100%** & **630MB** ram

It wasn't a big surprise anyway, because [PyPy's official documentation](https://www.pypy.org/performance.html) also mentioned that :

> Be aware of the difference between code that is compute-bound (slow because it's doing a huge number of instructions) and code that is I/O bound (slow because of disk or network delays).
> Expect to get most of your gains from optimizing compute-bound code. It's usually (though not always) a sign that you're near the end of worthwhile tuning when profiling shows that the bulk of the application's time is spent on network and disk I/O.

**Comment by bsergean** [comment]
Have you tried uvloop ?
It is something to accelerate asyncio which is quite easy to use, but it makes your build a bit slower. If you are just doing a bench I think it’s worth trying.

**Comment by AmirHmZz** [comment]
@bsergean Yes, I've tried it. Using **uvloop** handled additional 5K clients on the same server with same configuration.

**Comment by bsergean** [comment]
Cool, so about 25% improvements, in a realistic situation it seems. Thanks for sharing.

**Comment by aaugustin** [comment]
@bsergean I believe this PR touches many things we wanted to know 3 years ago when we started this discussion.

I recently added a few guides. Maybe I should do "nginx + unix sockets" too. It seems to be a popular combination.

**Comment by bsergean** [comment]
At work for a different project with have a setup where multiple process all bind to the same port, which you had mentioned was an option a long time ago.

This issue can be closed btw if you feel like it, it seems convenient as a discussion board / share how people deal with deployment, but since there are existing deployment guides it isn't required.
