### ISSUE TITLE
Using aioredis with websockets

### ISSUE THREAD

**Issue by bsergean** [aaugustin/websockets#447]
While developing a server, I'd like to read/write to redis: I found a package that works with asyncio called [aioredis](https://github.com/aio-libs/aioredis).

```
    # Now push to redis
    redis = await aioredis.create_redis_pool(
        'redis://localhost',
        minsize=5, maxsize=10,
        loop=asyncio.get_event_loop())

    await redis.publish_json('my_channel_name', msg)

    redis.close()
    await redis.wait_closed()
```

However I am new to asyncio dev and I don't understand how I can only have 'one redis' connection (not sure whether I need a pool) that can be used in my 'connection processor', from the main documentation. Can I add 'member' variable that I can use from the websocket object

```
async def handler(websocket, path):
    async for message in websocket:
        # HOW CAN I ACCESS MY redis pool from here ?
        # Should I make it a global, and force or wait for the pool to be created (something like that ?).
        # Or can I add it to 'websocket'
        await process_message(websocket, message)
```

I've seen that [custom example](https://github.com/aaugustin/websockets/blob/master/example/health_check_server.py), but I don't know how to fit my 'global' in there. Flask has a way to access 'globals'. Not sure whether what I'm trying to do make sense.

Thanks for any help !

**Comment by bsergean** [comment]
I realized that those questions are more about asyncio ... regardless I've just found aiohttp and it has something called an 'app', that can store things and be accessed from a handler (typical example is with a [db connection](https://aiohttp-demos.readthedocs.io/en/latest/tutorial.html#creating-connection-engine)). That would probably be a nice extension to websockets.

**Comment by aaugustin** [comment]
I'd use a global variable. It can be lazily instantiated if that's appropriate (i.e. write a `get_redis_connection()` that returns the existing connection if there is one, else creates it).

**Comment by bsergean** [comment]
I actually tried such an approach but I was still getting some odd errors that are probably linked with my bad knowledge of asyncio. I should make a small minimal repro case that shows the problem.

**Comment by bsergean** [comment]
I might try another approach using functools.partial. This lets someone attach variable to a function, which is the one passed in. Here's an example with client code, I should try to adapt it for server code.

```
async def client(url, creds, clientCallback):
    async with websockets.connect(url) as websocket:
        # do stuff
        await clientCallback(websocket)


# where the magic happens, retrieve 'path' from args
async def clientCallback(websocket, **args):
    path = args['path']

    print('hello world', path)

    with open(path) as f:
        for line in f:
            print(f"> {line}")
            await websocket.send(line)



async def hello(url, credentials, path):
    publishClientCallback = functools.partial(clientCallback, path=path)

    # (found that 'parallel' snippet somewhere)
    tasks = []
    N = 5 
    for _ in range(N):
        task = asyncio.ensure_future(client(url, credentials, publishClientCallback))
        tasks.append(task)

    done, pending = await asyncio.wait(
        tasks,
        return_when=asyncio.FIRST_COMPLETED,
    )
    for task in pending:
        task.cancel()
```

**Comment by aaugustin** [comment]
Yes, `functools.partial` came up in similar discussions before, see https://websockets.readthedocs.io/en/stable/cheatsheet.html?highlight=partial#passing-additional-arguments-to-the-connection-handler as well.
