### ISSUE TITLE
Receive messages and periodically push data to client.

### ISSUE THREAD

**Issue by thiagomorato** [aaugustin/websockets#45]
Hey, does anyone have a clue about how to push data to client, lets say every 0.5s, and still be able to receive messages?

By now I can only do one, or another and as I'm new to Python making it has proven quite a quest for me. Any ideas?

**Comment by aaugustin** [comment]
This is a general question about asyncio. There's nothing specific to websockets in my answer.

You should define two coroutines:

    @asyncio.coroutine
    def push_data(websocket):
        while websocket.open:
            yield from websocket.send(...)
            yield from asyncio.sleep(0.5)

    @asyncio.coroutine
    def get_data(websocket):
        while websocket.open:
            msg = yield from websocket.recv()
            ...

Then you have two options.

1) Run them together with asyncio.wait:

    yield from asyncio.wait([push_data(websocket), get_data(websocket)])

2) Turn them into tasks:

    push_task = asyncio.async(push_data(websocket))
    get_task = asyncio.async(get_data(websocket))

(Unlike coroutines, tasks execute even if you aren't explicitly yielding from them.)

If that's any comfort, asyncio has a learning curve, like any async I/O framework :-)

I hope this helps.

**Comment by thiagomorato** [comment]
Thanks mate it just helped me A LOT!
