### ISSUE TITLE
WebSocket connection is closed - how to interpret the error code?

### ISSUE THREAD

**Issue by vgoklani** [aaugustin/websockets#452]
Hello - I am trying to interpret these error messages:

WebSocket connection is closed: code = 1005 (no status code [internal), no reason
WebSocket connection is closed: code = 1006 (connection closed abnormally [internal), no reason

which (apparently) occur on my end, based on this: https://tools.ietf.org/html/rfc6455#section-7.4.1

   1005

   1005 is a reserved value and MUST NOT be set as a status code in a
   Close control frame by an endpoint.  It is designated for use in
   applications expecting a status code to indicate that no status
   code was actually present.

   1006

   1006 is a reserved value and MUST NOT be set as a status code in a
   Close control frame by an endpoint.  It is designated for use in
   applications expecting a status code to indicate that the
   connection was closed abnormally, e.g., without sending or
   receiving a Close control frame.

My code is as follows:

	async def connect(self):
		while True:
			log.info("connecting")
			async with websockets.connect(self.url, max_queue=4 * 2**10,) as websocket:
				log.info("connected")
				await websocket.send(json.dumps(self.subscribe))
				log.info("subscribed: {}".format(websocket.remote_address))
				while(True):
					try:
						message_str = await asyncio.wait_for(websocket.recv(), timeout=self._timeout)
						self.queue.put_nowait(message_str)
					except asyncio.TimeoutError:
						log.warn("timeout error - no data in {} seconds, pinging connection".format(self._timeout))
						pong_waiter = await asyncio.wait_for(websocket.ping("keepalive"), timeout=self._timeout)
						await asyncio.wait_for(pong_waiter, timeout=2 * self._timeout)
						log.warn('ping/pong received, keeping connection alive...')
					except Exception as e:
						error_message = "resetting connection: {}".format(e.args)
						log.error(error_message)
						raise Exception(error_message)

How would i figure out what these error codes mean? Typically in a synchronous websocket library, there would be an on_error() handler. Presumably this is being routed through the exception mechanism. Is that the case here? How do I interpret these errors? Thanks!

**Comment by aaugustin** [comment]
Perhaps the remote endpoint closed the connection improperly.

Enable logging to see all messages exchanged on the connection: https://websockets.readthedocs.io/en/stable/cheatsheet.html?highlight=logging#debugging

and you should get a better idea of what's happening.
