### ISSUE TITLE
connect to a socket source that also includes other parameters

### ISSUE THREAD

**Issue by brianehlert** [aaugustin/websockets#46]
A bit of a novice here, so excuse me if this is obvious.
(I am trying to translate some node.js into python as well)

I am trying to create a connection to a web service that requires two keys to be passed in the connection string.

The node.js uses an npm module and looks like this:
          var meshblu = require('meshblu');
          var request = require('request');

          var conn = meshblu.createConnection({
          "uuid": "0d3a53a0-2a0b-11e3-b09c-ff4de847b2cc",
          "token": "qirqglm6yb1vpldixflopnux4phtcsor"
        });

        conn.on('ready', function(data){
        console.log('Ready');

They also have a REST interface that requires this in the header like this using PowerShell:
$authHeader = @{
    meshblu_auth_uuid = $obj.uuid   
    meshblu_auth_token = $obj.token
}
$skynetUsers = Invoke-RestMethod -URI http://skynet.im/devices?type=user -Headers $authHeader -Method Get
$skynetUsers.devices

Any idea how to handle this with the websockets?

**Comment by aaugustin** [comment]
As far as I can tell from meshblu's readme, these parameters must be passed as HTTP headers, like this:

    meshblu_auth_uuid: 0d3a53a0-2a0b-11e3-b09c-ff4de847b2cc
    meshblu_auth_token: qirqglm6yb1vpldixflopnux4phtcsor

Unfortunately, websockets doesn't support passing custom HTTP headers at this time.

If you don't mind I'll close this ticket which is extremely specific and open a new one for supporting custom HTTP headers (#47).
