### ISSUE TITLE
How to add message to queue?

### ISSUE THREAD

**Issue by wardbradt** [aaugustin/websockets#463]
Is this the correct way to add a message to the queue that will later be returned by `recv()`? If it matters, this is for a `WebSocketClientProtocol`.

```
import websockets
import asyncio

async def bar():
    uri = 'wss://api.foo.com'
    message = 'message to be received'
    conn = await websockets.connect(uri)
    await conn.messages.put(message)

    async with conn as c:  # this is probably bad syntax for yielding from the protocol
        async for msg in c:
            print(msg)  # will this eventually print 'message to be received'?

asyncio.get_event_loop().run_until_complete(bar())
```

Is there any potential problem with doing this?

**Comment by wardbradt** [comment]
Also, I think it would be great if there were (more) examples of using this library with asyncio as many of the issues in this repo are about asyncio rather than `websockets`. I would like to contribute to this effort if you (@aaugustin) think it is a good idea. Should such examples be in the docs or the examples directory?

**Comment by aaugustin** [comment]
I'm lacking some context here. It appears that you want to pretend that a message was received on the websocket connection, when it comes from another source.

I would encourage you to implement a separate queue where you would push messages from the websocket connection and from you other source, instead of piggybacking on websockets' internals.

Until now I'm trying to stay out of the business of teaching asyncio because it looks like a bigger time sink than I can afford :-/ I wish there was a good third-party resource for that.

**Comment by wardbradt** [comment]
I am writing a class which inherits from `WebSocketClientProtocol`. I would, as you guessed, like to make it appear "that a message was received on the websocket connection." Is it risky to do it in this way? I could implement your approach if it would be better.

**Comment by wardbradt** [comment]
I am writing a class which inherits from `WebSocketClientProtocol`. I would, as you guessed, like to make it appear "that a message was received on the websocket connection." Is it risky to do it in this way? I could implement your approach if it would be better.

**Comment by aaugustin** [comment]
Regarding the idea of providing more examples of how to use asyncio with websockets, I changed my mind over the week. It would be a good contribution if you're motivated. It can live in the websockets documentation. I'm willing to mentor you.

In practice here's how we could move forward:

- you gather a list of examples / patterns / topics (either things you know how to do, or things you wish you knew how to do), maybe by reviewing issues in this repository
- we review that list together in a new GitHub issue (or private email if that's more comfortable) and decide on how to organize this section of the docs
- you write the bulk of this new documentation; I provide guidance and feedback

Bonuses:

- there are too many examples in the "getting started" document, it'd be better if some were moved to this new section
- if everything goes well, you'll have commit access to websockets soon :-)

**Comment by wardbradt** [comment]
I currently do not have the time to contribute to this effort to the extent you describe. I could certainly contribute some examples when I have time to do so; I would not like to commit to the planning and organization you describe above as I will not be able to do so in a timely manner.

**Comment by aaugustin** [comment]
As far as I can tell, that code would work. Both producers would push messages into the shared queue.
