### ISSUE TITLE
Add support for custom HTTP headers in handshake request

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#47]
See #46 for a use case.

**Comment by knutae** [comment]
Created a pull request which allows custom HTTP headers in the client.connect() call.

My first fork and pull request ever on github, let me know if I did something wrong. :)

**Comment by ye** [comment]
@aaugustin thanks for creating this library! @knutae thanks for the PR to add this functionality. Another use case for the custom HTTP header support is the ability to retrieve custom HTTP headers that WebSocket client sending in at the time of handshake. I was looking at the code, but I couldn't find a way to get that at version 2.5. Is it possible without modify the source? Can you shed some lights on my request?
