### ISSUE TITLE
If any workaround for proxy support?

### ISSUE THREAD

**Issue by birbird** [aaugustin/websockets#472]
This library has the limitation "The client doesn’t support connecting through a proxy".
My situation is that I have to use a proxy. May I ask if any workaround for proxy?
Any help will be highly appreciated.

**Comment by aaugustin** [comment]
It's going to take some manual work.

You could establish the connection to the proxy yourself (looking at #422) may help than pass the already connected socket with the `sock` argument to `connect`.

**Comment by ChyiYaqing** [comment]
Listen to you suggestion to establish the connection to the proxy , then pass the already connected socket with the sock argument.

```
try:
	proxy_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	proxy_sock.connect(("127.0.0.1", 1080))
except Exception as err:
	print(err)

async def getStream():
       async with websockets.connect("wss//stream.xxx.com:xxx", sock=proxy_sock) as websocket:
                message = await websocket.recv()
```
But get the "asyncio Value Error - ValueError: You must set server_hostname when using ssl without a host".

Please give me some other suggestions. Thank You.

**Comment by aaugustin** [comment]
You need to do the HTTP request to connect to the proxy before passing the `sock` argument to `connect`.

To be honest "it's going to take some manual work" was an euphemism for "you're going to hate this".

Then, if you're doing a WSS connection inside the proxy connection, you must pass a `server_hostname` to `connect` like the error message tells you.
