### ISSUE TITLE
How can i add s5 proxy to ws , and deal with ping?

### ISSUE THREAD

**Issue by CL545740896** [aaugustin/websockets#473]
Could u tell me how can i do it ,Because i can't find them in the example! Thanks

**Comment by CL545740896** [comment]
then,when i disconnect the ws, how can i reconnect the ws

**Comment by aaugustin** [comment]
There's no support for SOCKS5 proxies right now.

I'm not sure what you mean by "deal with ping" but I suspect that websockets already does what you need automatically. You don't need to care about pings.

Your last question seems to be the same as #414.

**Comment by aaugustin** [comment]
For clarity, I created a dedicated issue for SOCKS proxy support. See #475.
