### ISSUE TITLE
websockets rooms

### ISSUE THREAD

**Issue by zhangatao** [aaugustin/websockets#481]
Excuse me, how to use websockets to create rooms?

**Comment by lgrahl** [comment]
There is no abstraction for that. Join them via the path. I've written something like that a while ago: [silly-signalling](https://github.com/lgrahl/silly-signaling/blob/3cdabe72859bdd7557c96a9b4c1b060b675cf9c6/server.py)

**Comment by aaugustin** [comment]
Also you might want to look at higher level abstractions such as WAMP.
