### ISSUE TITLE
Sending cookies

### ISSUE THREAD

**Issue by HydraulicSheep** [aaugustin/websockets#489]
I have a header list in the form `[('Cookie','foo=3; bar=6;')]` and a websocket connection in the form:
`async with websockets.connect("wss:example.com, extra_headers = [headers]) as websocket:`.
The headers are not passing correctly and I have no idea why.
Is this a bug?

Thanks,

HydraulicSheep

**Comment by aaugustin** [comment]
As far as I can tell, you're creating a list of one element containing a list of headers with `extra_headers=[headers]`. Try `extra_headers=headers` instead.
