### ISSUE TITLE
Document how you serve both websockets and a aiohttp server on the same port.

### ISSUE THREAD

**Issue by Natim** [aaugustin/websockets#49]
I'd like to have some HTTP pages alongside my websocket handler.

How should I integrate?

Would this works?

```
#!/usr/bin/env python

import asyncio
from aiohttp import web
import websockets

@asyncio.coroutine
def hello(websocket, path):
    name = yield from websocket.recv()
    print("< {}".format(name))
    greeting = "Hello {}!".format(name)
    yield from websocket.send(greeting)
    print("> {}".format(greeting))

@asyncio.coroutine
def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(body=text.encode('utf-8'))

@asyncio.coroutine
def init_http_server(loop):
    app = web.Application(loop=loop)
    app.router.add_route('GET', '/{name}', handle)

    srv = yield from loop.create_server(app.make_handler(),
                                        '127.0.0.1', 8080)
    print("Server started at http://127.0.0.1:8080")
    return srv



loop = asyncio.get_event_loop()

websocket_server = websockets.serve(hello, 'localhost', 8765)
http_server = init_http_server(loop)

loop.run_until_complete(websocket_server)
loop.run_until_complete(http_server)

loop.run_forever()
```

**Comment by Natim** [comment]
This apparently works but if I want to share the same port and plug the websocket on a specific endpoint I didn't find out how I should do.

**Comment by Natim** [comment]
I assume an answer you can make is: http://aiohttp.readthedocs.org/en/v0.15.0/web.html#websockets

But it doesn't actually use this repository API. Is it possible to benefit from this project API using aiohttp?

**Comment by aaugustin** [comment]
Well, the easiest would be to run on separate ports.

Last I checked, `aiohttp` performed the websockets handshake automatically. I don't know if that's still true — the API changes quickly. You could try passing control to a `WebSocketServerProtocol` (or perhaps a subclass) but I don't have working code for this.

**Comment by Natim** [comment]
Do you think it could be a good idea be able to add some http handler to the websockets projects or would it be to close to what propose aiohttp?

**Comment by aaugustin** [comment]
This project doesn't aim at providing an HTTP server.

**Comment by aaugustin** [comment]
I'm going to close this issue as "out of the scope I'm willing to maintain".
