### ISSUE TITLE
Multiple concurrent client connections [documentation request]

### ISSUE THREAD

**Issue by ahonnecke** [aaugustin/websockets#490]
I'm attempting to write a single client that subscribes to multiple websocket connections, sends one or more subscribe messages to each connection and then asynchronously listens to all of the connections handling the messages as is appropriate.  I'm having trouble finding an example or an example that's close enough to modify in the documentation.

**Comment by aaugustin** [comment]
Look at the asyncio docs about [running tasks concurrently](https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently).
