### ISSUE TITLE
Flow control not working?

### ISSUE THREAD

**Issue by lgrahl** [aaugustin/websockets#502]
I cannot get the flow control to kick in in my example forwarding server:

- The receiving client will wait 20 seconds before trying to receive any data.
- The sending client will send a total amount of 256 MiB in 64 KiB messages as fast as possible.
- The forwarding server just forwards the data as fast as possible but does use `await` which should propagate the flow control.

This is my understanding of the existing flow control for each server/client instance:

- The default settings allow to buffer up to 32 MiB of binary data. But we use 64 KiB messages, so the maximum amount of buffered message should be 2 MiB in this case.
- `asyncio` will buffer a tiny amount of data. This is the part I'm not 100% sure about but IIRC it should not be above 64 KiB with the default settings of `websockets`.
- The TCP buffer will also swallow some amount of data. Usually that will be ~3 MiB on Linux.

That makes ~5 MiB of buffering. Way less than the 256 MiB the client is sending. So, the flow control should kick in at about ~5 MiB and that should be visible in the output.

On my machine, the sending client will just send the data and exit. :confused: I'm puzzled. Apparently, the call to `.drain` never *blocks*. Could this be some OS optimisation due to all instances being run on the same machine? Even so, that would be an issue since I suppose some implementations will terminate TLS on nginx and forward connections to localhost.

If you want to give it a try, run the below example...

- create the forwarding server with `python blah.py s`,
- connect the receiving client with `python blah.py cr`, and
- connect the sending client with `python blah.py cs`.

---

Edit: I have used commit 21d3bed6bcdd4a0374e28dfee0887584ec64e12c for running the below code since 7.0 has not been released, yet.

```python
import asyncio
import functools
import sys

import websockets


async def handle_client(ws: websockets.WebSocketCommonProtocol, path: str, context: dict):
    role, expected_total = path.lstrip('/').split('/')

    # Forwarded to
    if role == 'cr':
        context['other'] = ws
        await ws.connection_lost_waiter
        print(path, 'closed')

    # Forwarded from
    elif role == 'cs':
        other_ws = context.get('other')  # type: websockets.WebSocketCommonProtocol
        assert other_ws is not None
        expected_total = int(expected_total)
        actual_total = 0
        while True:
            # Receive
            try:
                data = await ws.recv()
            except websockets.ConnectionClosed:
                print(path, 'closed')
                other_ws.close(code=1337)
                break
            actual_total += len(data)
            print('recv', actual_total, '/', expected_total)

            # Send
            await other_ws.send(data)
            print('send', actual_total, '/', expected_total)

    # No!
    else:
        raise RuntimeError('Go away')


def server(loop: asyncio.BaseEventLoop):
    context = {}
    server = loop.run_until_complete(websockets.serve(
        functools.partial(handle_client, context=context), port=55555,
        ping_interval=None, max_size=2 ** 16, max_queue=1,
    ))
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        server.close()


async def client_send(data: bytes, n_sends: int):
    expected_total = n_sends * len(data)
    ws = await websockets.connect(
        f'ws://[::1]:55555/cs/{expected_total}',
        #ping_interval=None, max_size=2 ** 16, max_queue=1,
    )  # type: websockets.WebSocketCommonProtocol
    for i in range(n_sends):
        await ws.send(data)
        print((i + 1) * len(data), '/', expected_total)


async def client_recv(data: bytes, n_recvs: int):
    actual_total = 0
    expected_total = n_recvs * len(data)
    ws = await websockets.connect(
        f'ws://[::1]:55555/cr/{expected_total}',
        #ping_interval=None, max_size=2 ** 16, max_queue=1,
    )  # type: websockets.WebSocketCommonProtocol
    await asyncio.sleep(20.0)
    for _ in range(n_recvs):
        data = await ws.recv()
        actual_total += len(data)
        print(actual_total, '/', expected_total)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    data = b'\xef' * 2**16
    n = 4096
    # -> 256 MiB

    if sys.argv[1] == 's':
        server(loop)
    elif sys.argv[1] == 'cs':
        loop.run_until_complete(client_send(data, n))
    elif sys.argv[1] == 'cr':
        loop.run_until_complete(client_recv(data, n))
    else:
        raise RuntimeError('Go away')
```

**Comment by aaugustin** [comment]
Your test data is highly compressible.

Try disabling compression by passing the `compression=None` argument to `connect`.

**Comment by lgrahl** [comment]
Woops. Good point.

**Comment by lgrahl** [comment]
I'll give it a try tomorrow but highly assume it will be resolved by turning off compression.

**Comment by aaugustin** [comment]
Guess how I know this ;-)

**Comment by lgrahl** [comment]
With compression off, I think it is working quite well:

On my machine, the maximum TCP buffer is `6291456` for receiving and `4194304` for sending. I have set `max_size=2 ** 16` and `max_queue=1`. With these settings, I can see that the sender pauses once it reaches `14614528` bytes.

Sender:
`4194304` (TCP)
??? (asyncio)
`65536 * 1` (websockets)
-> `4259840`

Server (receive):
`6291456` (TCP)
??? (asyncio)
`65536 * 1` (websockets)
-> `6356992`

Server (forward):
`4194304` (tcp)
??? (asyncio)
`65536 * 1` (websockets)
-> `4259840`

Total: `12779520`. This still a little less than `14614528` but it does generally make sense. If someone knows where those extra ~1.75 MiB come from, let me know. A part of it will be asyncio I guess.

**Comment by lgrahl** [comment]
I guess I also have to factor in the receiving client...

Receiver:
`6291456` (TCP)
??? (asyncio)
`65536 * 1` (websockets)
-> `6356992`

Total: `17039360`. In theory, we should have had ~2.3 MiB extra. My calculations may be slightly wrong, so I'm thankful for any further comments. :slightly_smiling_face:

**Comment by aaugustin** [comment]
As far as I know, asyncio has 64kB read and write buffers.

I documented my understanding of buffers there: https://websockets.readthedocs.io/en/stable/design.html#buffers

I don't know very well how the OS handles TCP buffers, which account for most of the data in this scenario.

**Comment by lgrahl** [comment]
> As far as I know, asyncio has 64kB read and write buffers.

A nit: at least the `_SelectorTransport` [reads in 256 KiB chunks](https://github.com/python/cpython/blob/b83d917fafd87e4130f9c7d5209ad2debc7219cd/Lib/asyncio/selector_events.py#L580), so IIRC you may or may not have a little bit of extra data in the buffers depending on how well the messages fit into the receive buffer as used by `socket.recv`.

**Comment by lgrahl** [comment]
My (perhaps premature) conclusion from that is that the `websockets` buffer can be quite severely limited without impacting the throughput since the TCP buffers will be large enough (and much more flexible) to compensate for high-delay scenarios.

**Comment by aaugustin** [comment]
My own conclusion is that we have too many layers of buffers and that it's hard to draw conclusions :-)

**Comment by lgrahl** [comment]
For the sake of completeness, here is my updated code if someone wants to play with it:

```python
import asyncio
import functools
import sys

import websockets


async def handle_client(ws: websockets.WebSocketCommonProtocol, path: str, context: dict):
    role, expected_total = path.lstrip('/').split('/')

    # Forwarded to
    if role == 'cr':
        context['other'] = ws
        await ws.connection_lost_waiter
        print(path, 'closed')

    # Forwarded from
    elif role == 'cs':
        other_ws = context.get('other')  # type: websockets.WebSocketCommonProtocol
        assert other_ws is not None
        expected_total = int(expected_total)
        actual_total = 0
        while True:
            # Receive
            try:
                data = await ws.recv()
            except websockets.ConnectionClosed:
                print(path, 'closed')
                other_ws.close(code=1337)
                break
            actual_total += len(data)
            print('recv', actual_total, '/', expected_total)

            # Send
            await other_ws.send(data)
            print('send', actual_total, '/', expected_total)

    # No!
    else:
        raise RuntimeError('Go away')


def server(loop: asyncio.BaseEventLoop):
    context = {}
    server = loop.run_until_complete(websockets.serve(
        functools.partial(handle_client, context=context), port=55555,
        compression=None,
        ping_interval=None, max_size=2 ** 16, max_queue=1,
    ))
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        server.close()


async def client_send(data: bytes, n_sends: int):
    expected_total = n_sends * len(data)
    ws = await websockets.connect(
        f'ws://[::1]:55555/cs/{expected_total}',
        compression=None,
        ping_interval=None, max_size=2 ** 16, max_queue=1,
    )  # type: websockets.WebSocketCommonProtocol
    for i in range(n_sends):
        await ws.send(data)
        print((i + 1) * len(data), '/', expected_total)


async def client_recv(data: bytes, n_recvs: int):
    actual_total = 0
    expected_total = n_recvs * len(data)
    ws = await websockets.connect(
        f'ws://[::1]:55555/cr/{expected_total}',
        compression=None,
        ping_interval=None, max_size=2 ** 16, max_queue=1,
    )  # type: websockets.WebSocketCommonProtocol
    await asyncio.sleep(20.0)
    for _ in range(n_recvs):
        data = await ws.recv()
        actual_total += len(data)
        print(actual_total, '/', expected_total)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    data = b'\xef' * 2**16
    n = 4096
    # -> 256 MiB

    if sys.argv[1] == 's':
        server(loop)
    elif sys.argv[1] == 'cs':
        loop.run_until_complete(client_send(data, n))
    elif sys.argv[1] == 'cr':
        loop.run_until_complete(client_recv(data, n))
    else:
        raise RuntimeError('Go away')
```
