### ISSUE TITLE
Document DEBUG logging

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#503]
I'm not sure it's sufficently discoverable.

**Comment by RankoHata** [comment]
I found an error in the project tutorial.

	logging.error(
                    "unsupported event: {}", data)

I think it should be

	logging.error("unsupported event: {}".format(data))

-> [url](https://websockets.readthedocs.io/en/stable/intro.html#browser-based-example)

**Comment by aaugustin** [comment]
The current version is correct. Loggers format messages lazily. This has several benefits, mainly performance and ability to group messages.

**Comment by aaugustin** [comment]
Actually it's already in the cheatsheet.
