### ISSUE TITLE
Return the close code in WebSocketCommonProtocol.wait_closed

### ISSUE THREAD

**Issue by lgrahl** [aaugustin/websockets#513]
I would find it useful to get the close code as the `WebSocketCommonProtocol.wait_closed` future's result.

Currently, I'm wrapping `.wait_closed` in my use case to be able to return the close code. This could also include the reason. Instead of returning a tuple for these, we could just return the `ConnectionClosed` instance.

**Comment by aaugustin** [comment]
So we're talking of replacing:

```python
yield from ws.wait_closed()
do_stuff(ws.close_code)
```
with:

```python
close_code = yield from ws.wait_closed()
do_stuff(close_code)
```

I like the simplicity of the current `wait_closed()` API — no arguments, no return value, no exceptions. I'm trying to keep websockets API very straightforward and unsurprising.

Perhaps you can share an actual code example where the advantages of this change are more obvious than in my made-up example?

**Comment by lgrahl** [comment]
I wouldn't want to remove the `close_code` attribute. Just additionally return the close code in `wait_closed()`. It would be merely slightly more convenient, so I wouldn't mind if it's not being added.

**Comment by aaugustin** [comment]
I'm still in the "there should be one way to do it" camp. I haven't seen enough upside to add a second way. Sorry!
