### ISSUE TITLE
Silence "yield from lock" deprecation warning

### ISSUE THREAD

**Issue by koliyo** [aaugustin/websockets#514]
When running in python 3.7 I'm getting deprecation warnings

```
/usr/local/lib/python3.7/site-packages/websockets/protocol.py:911: DeprecationWarning: 'with (yield from lock)' is deprecated use 'async with lock' instead
```

**Comment by aaugustin** [comment]
Yes, unfortunately it's staying until I drop support for Python 3.4 in March 2019 (#476).

**Comment by aaugustin** [comment]
Actually the right solution would be to silence the warning. I remember trying it and failing to come up with the right warnings.filterwarnings incantation. If someone knows how to do that, I'd love a PR.

**Comment by aaugustin** [comment]
This doesn't happen anymore after #536.
