### ISSUE TITLE
Ping/auto ping not working?

### ISSUE THREAD

**Issue by sillibird** [aaugustin/websockets#515]
I'm using basic code to connect to a websocket and send/receive

```
async with websockets.connect(websocket_url) as websocket:
        async for message in websocket:
            print (message)
            await websocket.ping()
```
However, the connection dies because it is not being pinged. Even if I try with a ping_interval set, same results.

**Comment by aaugustin** [comment]
If the connection never receives a message, the body of the `async for` loop never executes.
