### ISSUE TITLE
Bind to Ip as client

### ISSUE THREAD

**Issue by kariya2** [aaugustin/websockets#518]
Hey, I have very little experience with the networking stack so I apologise in advance for this probably elementary questions. I need to bind to a local ip(my box has many) and connect to a websocket URL. I couldn't figure how to do it using this library, if it's possible any help would be sincerely appreciated. Thanks!

**Comment by aaugustin** [comment]
The `connect` coroutine of `websockets` is a wrapper around the `create_connection` coroutine of `asyncio`. If `asyncio` can do it, so can `websockets` :-)

**Comment by aaugustin** [comment]
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection documents a `local_addr` argument which looks a lot like what you're asking for.
