### ISSUE TITLE
How to setup a fake server for unit test

### ISSUE THREAD

**Issue by r4mbo7** [aaugustin/websockets#521]
Hi ! I'm am using websockets to consume data from wss://my.exemple.com
How I can re-route wss://my.exemple.com - to a FakeServer in order to test what FakeServer can publish ?

I'm thinking of something like this...
```python
import asynctest

class TestKlass(asynctest.TestCase):

	async def test_my_websocket_handler(self):
		""" Verify websocket handler behavior """

		class FakeServer():

			# @route('wss://my.exemple.com') <- I may define connection endpoint addresses like that
			async def subscription_handlers(self, *args, **kwargs):
				""" My fake server

				I wan't to publish stuff from here to my consumers
				"""
				pass

		async with FakeServer() as server:
				# How to take advantage of fake server here ?!
				async with websockets.connect('wss://my.exemple.com') as websocket:
					async for message in websocket:
						# Here I Can consume messages  from my fake server !
						pass
```

I will really appreciate replies with pieces of codes ! :)

Thanks ! :+1:

**Comment by aaugustin** [comment]
Somewhat related to #282.

**Comment by r4mbo7** [comment]
Hi @aaugustin ! It seems patch isn't the best approach because we don't want the behaviors of our tested methods to be altered.
Work in progress..

**Comment by aaugustin** [comment]
Yes, there's no direct relation between the current suggestions in #282 and what you'd like.

I made the link mostly to feed #282 with testing approaches.

**Comment by r4mbo7** [comment]
Answer here #539 :smiley:
