### ISSUE TITLE
Disable cert verification (non-crypto!)

### ISSUE THREAD

**Issue by mkoistinen** [aaugustin/websockets#522]
Hi. Another user was asking the same question here in #480, but, unfortunately, that conversation stopped short of helping others. I'm attempting to connect to a Ubiquiti EdgeRouter. I do not have their self-signed cert.

I'm doing this (Python 3.6):
```
    ssl_context = ssl.SSLContext()
    ssl_context.verify_mode = ssl.CERT_NONE
    ssl_context.check_hostname = False

    async def hello():
        async with websockets.connect('wss://192.168.1.1/ws/stats', ssl=ssl_context) as websocket:
            msg = await websocket.recv()
            print(f"< {msg}")

    asyncio.get_event_loop().run_until_complete(hello())
```

But it fails with:
```
Traceback (most recent call last):
  File "ws.py", line 89, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "ws.py", line 84, in hello
    ssl=ssl_context,
  File "/.../python3.6/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/.../python3.6/site-packages/websockets/py35/client.py", line 20, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/.../python3.6/site-packages/websockets/client.py", line 286, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 400
```
Am I doing this correctly? It seems to still not like my ssl_context =(

**Comment by lgrahl** [comment]
I might be wrong but status code `400` certainly doesn't look like a TLS issue to me. I think you're already past the TLS handshake. Can you verify that via Wireshark?

It is also generally discouraged to create an `ssl.SSLContext` directly. You may want to use `ssl.create_default_context` instead.

**Comment by mkoistinen** [comment]
I'm not sure about Wireshark analysing encrypted SSL packets (is that possible?), but I did turn on DEBUG level logging. It looks like the SSL is OK. For some reason, the server is not liking my request. Will keep at it. Thank you for your response and your suggestions!
