### ISSUE TITLE
[QUESTION] Fragmenting large messages

### ISSUE THREAD

**Issue by TheDiscoMole** [aaugustin/websockets#524]
I am trying to fragment my message into < 1 MB sizes as the whole is > 1 GB and am simply splitting my `type:byte` string into chunks.

When I send these chunks it only seems to work with the server option `max_size=None`, which seems counter intuitive since I have made the effort of ensuring that each frame does not reach the 1MB size limit.

Does this work as intended? I can't find the post i read anymore, but it sounded like `max_size=None` could cause some issues with many clients, is there a drawback to this server setting?

**Comment by lgrahl** [comment]
I think what you're asking for is #479?

Fragmentation on a message-oriented transport that supports messages of arbitrary size is counter-intuitive, indeed. :slightly_smiling_face:
