### ISSUE TITLE
How to send a JSON heartbeat message to the server every minute?

### ISSUE THREAD

**Issue by ShervinDD** [aaugustin/websockets#526]
Hi, I know the websocket can be pinged as a heartbeat, but what if I have to send a specific JSON heartbeat message?

I'm trying to send the following JSON message every minute as a heartbeat to keep the websocket connection alive: `{ "topic": "phoenix", "event": "heartbeat", "payload": {}, "ref": 0 }`

EDIT: But I want to receive messages every 1 second. (msg = await WS.recv() )

My code looks like this:

``` Python
import asyncio
import json
import websockets

async def socket_connect_WS():
    async with websockets.connect('wss://host.com') as WS:
        await WS.send(json.dumps({"topic": "channel", "event": "phx_join", "payload": {}, "ref": 0}))
        while True:
            msg = await WS.recv()
            print(json.loads(msg))
            await WS.send(json.dumps({"topic": "phoenix", "event": "heartbeat", "payload": {}, "ref": 0 }))
            await asyncio.sleep(1)

loop = asyncio.get_event_loop()
asyncio.ensure_future(socket_connect_WS())
loop.run_forever()
```

This keeps the websocket open but I would prefer to send the JSON heartbeat message every minute rather than every second.

**Comment by lgrahl** [comment]
Erm... replace `asyncio.sleep(1)` with `asyncio.sleep(60.0)`? :wink:

**Comment by ShervinDD** [comment]
> Erm... replace `asyncio.sleep(1)` with `asyncio.sleep(60.0)`?

Sorry @lgrahl , what I want to do is send the heartbeat message every 60 secs but receive msg = WS.recv() every 1 second.

**Comment by lgrahl** [comment]
I would suggest to spawn two separate tasks for that purpose and separate the send and receive logic.

**Comment by aaugustin** [comment]
Agreed, you need two tasks.
