### ISSUE TITLE
How would i close a websockets connection while its stuck awaiting in websocket.recv()

### ISSUE THREAD

**Issue by araa47** [aaugustin/websockets#527]
I have the following code that connects to a websocket as a client and waits for messages. I am trying to find the right way to close this websocket connection. 
If i set stop_threads = True, the code does'nt automatically shut since its stuck in the await websocket.recv(). What would be the right way to close this connection from another thread,
while the code is waiting for a message to be recieved. 

```
async with websockets.connect(url, ssl=True, timeout=self._timeout) as websocket:                  
    while True: 
        if stop_threads == False:
            try: 
                message = await websocket.recv()
                print(message)
            except Exception as e:
                print(e)
                await websocket.close() 
                return 
```

**Comment by aaugustin** [comment]
`asyncio.call_soon_threadsafe(ws.close)`

It would be best to close it from another coroutine / task rather than another thread. Mixing threads and coroutines isn't recommended.
