### ISSUE TITLE
How to start server using asyncio.run()

### ISSUE THREAD

**Issue by OrangeTux** [aaugustin/websockets#531]
All of the examples in the documentation start the websocket server using [ayncio's low-level API](https://docs.python.org/3/library/asyncio-llapi-index.html). According the docs this part of the API is intended for ["library and framework developers"](https://docs.python.org/3/library/asyncio.html). So I tried to start a server using [Python's 3.7 high-level API](https://docs.python.org/3/library/asyncio-api-index.html) `asyncio.run()`:

``` python
#!/usr/bin/env python

# WS server example

import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f"> {greeting}")

async def main():
    start_server = await websockets.serve(hello, 'localhost', 8765)

asyncio.run(main())
```

But this script finishes instantly, without any errors. I'd expect that the line `start_server = await websockets.serve(hello, 'localhost', 8765)` would block instead and the script will run forever. Any idea what I do wrong?

**Comment by lgrahl** [comment]
Untested but you could probably do

```python
async def main():
    server = await websockets.serve(hello, 'localhost', 8765)
    await server.wait_closed()
```

**Comment by aaugustin** [comment]
It may be nice to provide an API that is natively compatible with `run()` in order to avoid these three lines of boilerplate.

Currently we're mirroring asyncio APIs that also require an explicit `main()` coroutine: https://docs.python.org/3/library/asyncio-stream.html#tcp-echo-server-using-streams

**Comment by OrangeTux** [comment]
@lgrahl Thanks for the answer. I can confirm that it works.
