### ISSUE TITLE
Auto ping/pong ,timeout,ping_timeout,event_loop 

### ISSUE THREAD

**Issue by araa47** [aaugustin/websockets#532]
I have several questions, I am connecting to several WebSockets and using this library as a python client to receive information from these ws. 

1) Does websockets library automatically respond to a ping message from a server and send a pong back? Or will i need to implement this myself? 

2) Does websockets library automatically send ping to the servers once in a while to make sure the connection is still active? Or do I need to implement this myself? 

3) What do the timeout and ping_timeout arguments actually do? I've tried setting them to see if the WebSocket automatically disconnects if i turn my wifi off. However it seems like the code is  stuck in the message = await websocket.recv() line

4) Can i run multiple websockets in the same event loop by passing the loop arguement in the websockets.connect() line? Would this have any performance implications compared to starting multiple threads and new event loops for each websocket? 

I have found several similar issues in this thread but not very sure on if its implemented since setting the ping_timeout and disconnecting wifi does not seem to cause a disconnection after the timeout period. The disconnection only seems to happen when i turn wifi back on. 

https://github.com/aaugustin/websockets/pull/449

```
            try:
                async with websockets.connect(url, ssl=True, timeout=self._timeout, ping_timeout=2) as websocket:
                    while self._uds_status: 
                        try: 
                            message = await websocket.recv()
                            events = json.loads(message)
                            print(events)
                        except Exception as e:
                            print("uds_ws_connect, Err:(%s) Restarting socket manager!"%(e))
                            await websocket.close()
                            self._uds_status = False
            except Exception as e:
               print("Exception occured at uds_ws_conenct(), %s"%e)
```

**Comment by lgrahl** [comment]
1/2/3: See [the WebSocketCommonProtocol API description](https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol) for an explanation of `ping_timeout`. It's active by default, so you don't need to manually send ping messages or manually respond to them.

4: It's possible. Performance implications depend on your use case but threading is unlikely to be of help due to the GIL. Consider running blocking code in a [thread pool or process pool](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) instead.

**Comment by araa47** [comment]
@lgrahl , thanks for the great response. Answered most of my questions. 

For number 4. I have been trying to run two WebSockets in the same event loop but this doesn't seem to work. I can't seem to connect to both the WebSockets.  However running multiple WebSockets on different threads, and each thread creating a new event loop, seems to work properly.

**Comment by araa47** [comment]
@lgrahl , you were right. Got it to work. 

Been testing out the performance difference in opening up **51 WebSockets** and subscribing to them using two different designs. 

1) Run a single event loop, and run all the WebSockets in the same loop 
2) Create 51 threads each creating a new event loop that handles each WebSocket 

I have only tested both scripts out for a few minutes on my mac and the results below are from activity monitor on mac. 

1) Runs 103 threads, and uses about 4 % CPU 
2) Runs 21 threads and uses about 3.8% CPU 

I was expecting the GIL to have a much harsher performance degradement. Could this be because in Design 1, all that the threads are doing are creating event loops and waiting for them to run_until_complete, thus the context management is still asynchronous? 

Very curious to try to understand why this might be. 

Attached is a code snippet of the difference between design 1 and design 2 . Both the pieces of code simply calls a function md_ws_connect(pair), which connects to a websocket and gets market data for the currency pair every second. 

**Design 1**
```
def md_threads_init():
    global crypto
    all_threads = {}

    for coin in crypto:
        pairusdt = coin + 'usdt'
        pairbtc = coin + 'btc'
        paireth = coin + 'eth'
        all_threads[pairusdt] = threading.Thread(target = md_async_loop_init, args=(pairusdt,))
        all_threads[pairbtc] = threading.Thread(target = md_async_loop_init, args=(pairbtc,))
        all_threads[paireth] = threading.Thread(target = md_async_loop_init, args=(paireth,))
        
    for pair in all_threads:
        all_threads[pair].start()

    
def md_async_loop_init( pair):
    loop = None
    try:
        # start loop and run until complete
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        # code will be stuck here during execution and move to socket manager
        loop.run_until_complete(md_ws_connect(pair))
        # the code will only reach this block if md_ws_connect returns
        loop.close()
    except Exception as e:
        print("md_async_loop_init() Err:(%s)"%e)
        if loop:
            loop.close()
            
    print("finished ASYNCH MarketData thread process for pair: %s" % ( pair), True)
    
```
**Design 2** 
```
def single_loop_no_threads():
    global crypto
    [asyncio.ensure_future(md_ws_connect(coin+'usdt')) for coin in crypto]
    [asyncio.ensure_future(md_ws_connect(coin+'btc')) for coin in crypto]
    [asyncio.ensure_future(md_ws_connect(coin+'eth')) for coin in crypto]
    pending = asyncio.Task.all_tasks()
    main_asyncio_loop = asyncio.get_event_loop()
    # run the tasks until complete
    main_asyncio_loop.run_until_complete(asyncio.gather(*pending))
    main_asyncio_loop.close()
```

**Comment by lgrahl** [comment]
Hrm, I think using an event loop for each connection kind of defeats the purpose of asyncio.

Also, be aware of [this](https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users) and since I agree with @aaugustin I will stick to it. Nothing personal.
