### ISSUE TITLE
Provide an API for disabling compression on specific messages

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#538]
If some frames contain already compressed data, it would be nice to be able to tell websockets not to recompress them.

**Comment by aaugustin** [comment]
I'm not sure this use case really exists in practice. If you could benefit from this feature, please explain why in a comment :-)

**Comment by adriansev** [comment]
Hi! I am not sure if this should be frame oriented or message oriented, but it could be really useful if the message contain already compress data like media files or my (would be) use case of something called root files [(ROOT)](https://root.cern/) that are already compressed with anything from zlib, lzma and lz4

**Comment by aaugustin** [comment]
Yes, when fragmentation is used, this would likely make more sense at the message level rather than at the frame level.

**Comment by aaugustin** [comment]
This issue generalizes to "how to pass arbitrary per-message information to extensions?" which doesn't have an obvious solution.

**Comment by aaugustin** [comment]
In fact this only makes sense at the message level. Since I filed this issue, I discovered that the RSV1 bit is only set on the first frame when a message is fragmented; if it's set, all fragments are compressed.

**Comment by aaugustin** [comment]
In terms of API, this could be achieved by adding a `hints` argument to `send`, which would be passed to extensions:

```python
await ws.send(big_compressed_blob, hints={"permessage-deflate": {"compress": False}})
```

This isn't a particularly beautiful API though...

**Comment by aaugustin** [comment]
The more I think about this issue, the less I believe it's worth solving.

To care about this, you need:

1. to be exchanging a mix of compressible messages and non-compressible messages on the same connection
2. to have enough compressible messages that you cannot afford sending them as is (too much network traffic)
3. to have enough non-compressible messages that you cannot afford to compress them (too much CPU usage)

I'd be curious to hear about real-life examples of such a mixx of messages

In practice, if you exchange pre-compressed payloads, probably they're pre-compressed because they dwarf the rest of the traffic, so you can just disable compression and accept that the rest of the traffic won't be compressed.

Or maybe you can live with double compression; gzip is Quite Fast on modern hardware. Probably it works too.

So -- not going to put my time into this until there's more demand.
