### ISSUE TITLE
Client Side Unix Domain Sockets

### ISSUE THREAD

**Issue by nelsonhp** [aaugustin/websockets#539]
## What:
I was unable to find an easy way to create a Unix Domain Socket client with websockets(v7.0) on Python 3.6

## Why:
The client requires the manual creation of the socket and the process is not well documented.

## Intent:
I am posting this as a possible solution to anyone looking for this answer, or as a possible addition to the package, if the maintainers feel it is appropriate. 

## Extra Information:
Once a solution was found, it made utilization of the async  context managers and async generators less clean. 

## Suggestions:
Improve documentation to include example of Unix domain socket instantiation for clients.
Optionally, include a solution in package. I have provided one, but due to the use of __slots__ and the lack of kwargs pass through, this solution needs generalization.

## Code:
```python

""" This code is released under the terms, conditions, and limitations of 
BSD 3-Clause "New" or "Revised" License

Author: Hunter Prendergast
Date: December 31, 2018
"""
import socket
import websockets

class WSClient(object):
    """Async context manager for unix domain socket based websocket client.

    Usage:
    >>> import asyncio as aio
    >>> async def example():
    ...        async with WSClient(path='/tmp/sock.sock') as ws:
    ...            async for msg in ws:
    ...                print(msg)
    ...
    >>> loop = aio.get_event_loop()
    >>> loop.run_until_complete(example())
    """

    __slots__ = ["_host", "_path", "_port", "_ws"]

    def __init__(self, path=None, host=None, port=None):
        """Initialize context manager."""
        assert path or all([host, port]), "Must supply host and port or path."
        self._path = path
        self._host = host
        self._port = port
        self._ws = None

    async def __aenter__(self):
        """Entrance block."""
        if self._path:
            sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            sock.connect(self._path)
            uri = "ws://localhost"
        else:
            sock = None
            uri = "ws://{}:{}".format(self._host, self._port)
        self._ws = await websockets.connect(uri, sock=sock)
        return self._ws

    async def __aexit__(self, exc_type, exc, tb):
        """Exit block."""
        await self._ws.close()
```
Please feel free to utilize as needed and thanks for the amazing library!

**Comment by aaugustin** [comment]
What's your use case for this? I would like to explain the purpose of this API in the docs.

**Comment by nelsonhp** [comment]
I use it to create secure communication channels for micro-services internal to a physical or virtual machine. I think the more general use case is to facilitate debugging of Unix Domain sockets for the case where a Unix Domain server has been instantiated.

**Comment by aaugustin** [comment]
There's a design decision to make.

`websockets.connect(uri)` passes a lot of information in the `uri` parameter, including and not limited to:

- the host and port to connect to
- whether this is a secure connection
- the path to send in the HTTP request

When connecting to a Unix socket, we don't need the host and port, but we need the rest of the information. As a consequence, `websockets.unix_connect(path)` doesn't suffice.

`websockets.unix_connect(path, uri="ws://localhost/")` is the best I have. (I also thought about encoding the path in the WebSocket `uri` but I didn't find a sensible way to do that.)

`websockets.unix_connect("/path/to/socket")` would work for some simple use cases. Usually you don't need TLS if you're connecting to a local socket. Many WebSocket servers only serve one endpoint and don't care about `path`.

`websockets.unix_connect("/path/to/socket", "wss://user:password@localhost/path")` would support all other cases. `websockets` would require the host to be `localhost` and the port not to be specified, which is the most sensible default for connecting to a local socket.
