### ISSUE TITLE
Websocket won't close with 3.4.2

### ISSUE THREAD

**Issue by ghost** [aaugustin/websockets#54]
I'm following the loop example here: http://aaugustin.github.io/websockets/#example

I had code that would read from a queue (producer) and then publish to the websocket.
With Python 3.4.1, this code worked fine.
When I upgraded to Python 3.4.2, this code no longer detected when the other end of the socket was closed.

In fact, all I get in my console is "socket.send() raised exception", which sounds a lot like https://github.com/aaugustin/websockets/issues/23

I noticed the change logs for 3.4.3 and 3.4.4 mention some fixes and patches to the asyncio module. I'm using pyenv and it looks like it doesn't have those available at the moment so I can't quickly verify.

**Comment by aaugustin** [comment]
Thanks for taking the time to report this issue. Indeed, as asyncio matured, it became more strict and that revealed some defects in websockets.

Could you provide some minimal code to reproduce your issue? That would really help.

**Comment by aaugustin** [comment]
Over the last few days, I made a series of improvements to the handling of connection close. This may have fixed your problem.

If you still encounter the issue on the latest 3.4.x Python version, please provide enough information to reproduce it. Thanks!
