### ISSUE TITLE
missing messages PUSH

### ISSUE THREAD

**Issue by niamiot** [aaugustin/websockets#548]
Hi,
First of all I'm quite new to websockets & asyncio so the issue could be from my misunderstanding of the situation.
I'm currently trying to create a websockets server on which my client push its messages (I know this is not the usual way to use websocket but this is not my choice).

**My issue is I miss numerous message pushed from my client.** Some messages send from the client are not displayed  by the minimal piece of code thereafter.

I'm running  python 3.7  & websockets 7.0.

At this point I'm quite confused :
- Do I need to use thread in addition to asyncio to avoid missing messages ? 
- Is this a bug ?

Thanks for your help !

Here is the minimal code I'm using 
```python
import asyncio
import websockets
import signal
import sys



async def get_tag_data(websocket, path):
    # print('received')
    data = await websocket.recv()
    print(data)


def signal_handler(sig, frame):
    """ Manage ctrl + c and so  close connections
    """
    print('You pressed Ctrl+C!')
    anchors_server.ws_server.close()
    sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)


loop = asyncio.get_event_loop()
anchors_server = websockets.serve(get_tag_data, '', 9001)
loop.run_until_complete(asyncio.gather(anchors_server))
loop.run_forever()
```

**Comment by aaugustin** [comment]
Your code only gets one message and exits. You need a loop:

```python
async def get_tag_data(websocket, path):
    # print('received')
    while True:
        data = await websocket.recv()
        print(data)
```

or better

```python
async def get_tag_data(websocket, path):
    async for data in websocket:
        print(data)
```

**Comment by niamiot** [comment]
*look at the answer*
*facepalm*

thank you. Sorry for wasting your time with some stupid question.

**Comment by aaugustin** [comment]
Never mind. It's a surprisingly common pitfall. I've had this exact question several times.
