### ISSUE TITLE
[IncompleteReadError] The server is sending 0 byte message sometimes

### ISSUE THREAD

**Issue by LanDeQuHuXi** [aaugustin/websockets#549]
I'm subscribed to a stream that sometimes sends 0-byte message, and it will raise IncompleteReadError which closes the current websocket connection.

I'm wondering how could I handle this without causing the connection to be closed?

The error happened in _read_frame_, which uses self.reader.readexactly to read frames.
Do I need to override this coroutine to make it work?

**Comment by aaugustin** [comment]
This shouldn't happen unless the server also closes the TCP connection.

`self.reader.readexactly` is supposed to block until enough data is available.

**Comment by aaugustin** [comment]
I'd need more information to understand what happens here.

At least a full trackeback, perhaps also logs at the DEBUG level.

**Comment by LanDeQuHuXi** [comment]
Hi, I'm really sorry that I have't responded earlier. (I was on GitHub account recently)
I could not reproduce it reliably now.

You can close this issue,
 If I can reproduce it reliably, I will reopen it and attach the trackback and logs.

Thank you a lot!

**Comment by aaugustin** [comment]
OK. Feel free to file a ticket if you encounter further problems that could be bugs in websockets!
