### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by lgrahl** [aaugustin/websockets#553]
It would be neat to add type hints for [static type checking with mypy](https://mypy.readthedocs.io/en/latest/introduction.html).

**Comment by aaugustin** [comment]
Yes, that would be nice :-)

It won't add much to `websockets` itself because it has full test coverage. It could be useful for projects built with `websockets`.

**Comment by aaugustin** [comment]
See also [PEP 561](https://www.python.org/dev/peps/pep-0561/) for distributing types hints.

**Comment by aaugustin** [comment]
Complexities:

- `WebSocketCommonProtocol` is an async iterable only on Python ≥ 3.6
- `Headers.__init__` is annoyingly messy to type, it needs [something like that](https://github.com/python/typeshed/blob/9e5816a5390302933b2444fcff345798e06fa784/stdlib/3/typing.pyi#L386-L401)

**Comment by aaugustin** [comment]
I tried adding type annotations inline: it works fine for simple cases but it has two drawbacks:

1. Some function definitions get really harder to read than they should be e.g.

    ```python
    def decode(self, frame: Frame, *, max_size: Optional[int] = None) -> Frame:
        ...
    ```

     vs.

    ```python
    def decode(self, frame, *, max_size=None):
        ...
    ```

    (perhaps a matter of habit...)

2. I ended up needing patterns like this to avoid import loops:

    ```python
    if TYPE_CHECKING:
        from websockets.framing import Frame
    else:
        Frame = None
    ```
    
So I'm weakly in favor of separate stubs in `.pyi` files.

**Comment by aaugustin** [comment]
I already reached the stage where I'm finding bugs in mypy / typeshed... https://github.com/python/typeshed/pull/2752/files

**Comment by aaugustin** [comment]
Here are the remaining errors in the current state of the PR and my assumptions about their cause:

```
src/websockets/framing.py:308: error: "memoryview" has no attribute "c_contiguous"
```
=> It's a bug in mypy / typeshed.

```
src/websockets/protocol.py:473: error: Argument 1 to "prepare_data" has incompatible type "Union[int, str, bytes, memoryview]"; expected "Union[str, bytes, bytearray, memoryview]"
src/websockets/protocol.py:478: error: Argument 1 to "prepare_data" has incompatible type "Union[int, str, bytes, memoryview]"; expected "Union[str, bytes, bytearray, memoryview]"
src/websockets/protocol.py:501: error: Argument 1 to "prepare_data" has incompatible type "Union[int, str, bytes, memoryview]"; expected "Union[str, bytes, bytearray, memoryview]"
```
=> mypy gets confused because bytes are Sequence[int] (even though bytes are handled in the previous branch).

```
src/websockets/protocol.py:896: error: Argument 3 to "Frame" has incompatible type "Union[bytes, bytearray, memoryview]"; expected "bytes"
```
=> I haven't figured out the best way to handle bytes-like objects. mypy is supposed to duck-type bytearry and memoryview with bytes. It didn't work very well for me.

```
src/websockets/protocol.py:1056: error: "BaseTransport" has no attribute "abort"
```
=> It's a bug in mypy / typeshed.

```
src/websockets/protocol.py:1184: error: "BaseTransport" has no attribute "set_write_buffer_limits"
```
=> I haven't figured out how to tell mypy we have a Transport there and not just a BaseTransport.

```
src/websockets/server.py:503: error: Incompatible types in "await" (actual type "Optional[Tuple[HTTPStatus, Union[Headers, Mapping[str, str], Iterable[Tuple[str, str]]], bytes]]", expected type "Awaitable[Any]")
src/websockets/server.py:890: error: Incompatible return value type (got "Coroutine[Any, Any, WebSocketServer]", expected "AwaitableGenerator[Any, None, WebSocketServer, Generator[Any, None, WebSocketServer]]")
src/websockets/client.py:485: error: Incompatible return value type (got "AwaitableGenerator[Any, None, Tuple[BaseTransport, BaseProtocol], Generator[Any, None, Tuple[BaseTransport, BaseProtocol]]]", expected "Tuple[Transport, WebSocketClientProtocol]")
src/websockets/client.py:489: error: Incompatible return value type (got "Coroutine[Any, Any, WebSocketClientProtocol]", expected "AwaitableGenerator[Any, None, WebSocketClientProtocol, Generator[Any, None, WebSocketClientProtocol]]")
src/websockets/client.py:504: error: Incompatible types in "await" (actual type "Tuple[Transport, WebSocketClientProtocol]", expected type "Awaitable[Any]")
```
=> I don't understand __iter__ and __await__ in the Serve and Connect classes. It seems that mypy doesn't either. Most likely they work by accident.

```
src/websockets/client.py:485: error: Argument 2 to "create_connection" of "AbstractEventLoop" has incompatible type "Optional[str]"; expected "str"
src/websockets/client.py:485: error: Argument 3 to "create_connection" of "AbstractEventLoop" has incompatible type "Optional[int]"; expected "int"
```
=> It's a bug in mypy / typeshed.

```
src/websockets/client.py:529: warning: Returning Any from function declared to return "WebSocketClientProtocol"
```
=> mypy loses track of the fact that our protocol factory returns a WebSocketClientProtocol in `factory = lambda: create_protocol(...)`.

```
src/websockets/__main__.py:116: error: Argument 1 to "wait" has incompatible type "List[object]"; expected "Iterable[Union[Generator[Any, None, <nothing>], Awaitable[<nothing>]]]"
```
=> There's certainly a way to fix that but I haven't found it yet.

**Comment by aaugustin** [comment]
Eight type errors remaining...

**Comment by aaugustin** [comment]
It wasn't too hard to support Python 3.5 but it's ugly.

**Comment by aaugustin** [comment]
I think it's good to go.

I would appreciate if someone else took a look at the patch before it's merged, as I had no prior experience with mypy. Certainly not the most exciting kind of patch to review, I know...
