### ISSUE TITLE
Issues while receiving large BLOBs

### ISSUE THREAD

**Issue by symisc** [aaugustin/websockets#557]
Hi,

My JavaScript code basically send large chunk of 1MB BLOBs extracted from the browser canvas during the first interaction, after connection is successfully opened. While the Websocket server correctly accept & parse the incoming connection, extracting that chunk on the handler via `websocket.recv()`, takes at least 10 seconds to process on a powerful OVH dedicated machine. 
Is there any issue slowing down this operation? or is there any parameter to tune to make thing goes faster on the server side?

Thank you @aaugustin  for this amazing piece of work.

**Comment by aaugustin** [comment]
I'm not sure what would cause this.

Perhaps a quick check: can you try `import websockets.speedups` in the same Python installation you're using to run this service? It should succeed; if it doesn't then that's the first thing to fix.

**Comment by symisc** [comment]
`import websockets.speedups` should be imported on the same script handling the connection?

**Comment by aaugustin** [comment]
Yes.

**Comment by symisc** [comment]
Great. Thanks! One last question. Does running two instances or more of the same Websocket server say one on port 1000, the other on port 2000 and so forth improve concurrency? The basic idea here is to take advantages of multi-core CPUs since the event loop run on a singe core (process)?

**Comment by aaugustin** [comment]
Yes, it does. Documenting this is part of #445.

**Comment by aaugustin** [comment]
Did you figure out the slowness? It shouldn't take 10 seconds to load 1MB of data, even without the speedups.

**Comment by aaugustin** [comment]
Cool, thanks for the confirmation that websockets isn't at fault :-)
