### ISSUE TITLE
Expected?  client: "Malformed HTTP message" -> destruction of pending asyncio tasks

### ISSUE THREAD

**Issue by enewhuis** [aaugustin/websockets#56]
I am using websockets to make hundreds of client connections.

As a test client, as load increases, and the number of connections approaches several hundred websockets connections per asyncio loop, I am seeing new connections fail with increasing frequency raising "Malformed HTTP message" exceptions.

I don't know if the Malformed HTTP is caused by my test server or not.  But as shown below I see many asyncio tasks being destroyed while in a pending state.  I am curious if this is expected behavior given the above.

```Task was destroyed but it is pending!
task: <Task pending coro=<run() running at /usr/local/lib/python3.4/site-packages/websockets/protocol.py:232> wait_for=<Future pending cb=[Task._wakeup()]>>```

**Comment by aaugustin** [comment]
Each websocket connection runs an asyncio task that handles automatically control frames (ping, pong, close). If something goes wrong, the task can be garbage collected while it's waiting for a callback, which triggers this warning.

It would be better if websockets didn't emit spurious warnings.

**Comment by aaugustin** [comment]
In 9469965a I modified the client example to close the connection. If you make the same change to your test script, you shouldn't see these warnings anymore. If you do, let me know and I'll investigate further.
