### ISSUE TITLE
while true recv() : message queue is not emptied

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#565]
Hi! I have a problem with running recv() in a `while True:` loop :  
the messages are getting pile up in the queue so each message that i receive will be added
to the websocket queue so the `result = await websocket.recv()` will contain all previous messages  
Is this a bug or should i do something after i get the result?
Thank you!

**Comment by adriansev** [comment]
well, i might be wrong again in making assumptions how the remote server work :(   
i have the following log,  and i am not sure if "client < " if directly from remote or it is the status of local websocket queue :  

> ./j pwd
> {"command": "pwd", "options": []}
> Enter PEM pass phrase:
> Connecting to :  wss://<remote_host>:8097/websocket/json
> client - state = CONNECTING
> client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x7f863a041780>)
> client - state = OPEN
> client > Frame(fin=True, opcode=1, data=b'{"command": "commandlist", "options": []}', rsv1=False, rsv2=False, rsv3=False)
> client < Frame(fin=True, opcode=1, data=b'{"metadata":{"site":"CERN","currentdir":"\\/alice\\/cern.ch\\/user\\/a\\/asevcenc\\/","user":"asevcenc"},"results":[{"message":"ls ls_csd get cat cat_csd whereis whereis_csd cp cp_csd cd cd_csd time mkdir mkdir_csd find find_csd listFilesFromCollection scrlog submit motd access commit packages pwd ps rmdir rm rm_csd mv mv_csd masterjob user touch touch_csd type kill lfn2guid guid2lfn guid2lfn_csd w uptime addFileToCollection addMirror addTag addTagValue chgroup chown chown_csd createCollection deleteMirror df du fquota jobinfo jquota killTransfer listSEDistance listTransfer md5sum mirror queue queueinfo register registerOutput removeTag removeTagValue resubmit resubmitTransfer showTags showTagValue spy top groups token uuid stat listSEs xrdstat whois addTrigger addHost queue register addSE addUser calculateFileQuota calculateJobQuota groupmembers shutdown edit emacs less mcedit more nano sensible-editor vim"}]}', rsv1=False, rsv2=False, rsv3=False)
> {"command": "pwd", "options": []}
> client > Frame(fin=True, opcode=1, data=b'{"command": "pwd", "options": []}', rsv1=False, rsv2=False, rsv3=False)
> client < Frame(fin=True, opcode=1, data=b'{"metadata":{"site":"CERN","currentdir":"\\/alice\\/cern.ch\\/user\\/a\\/asevcenc\\/","user":"asevcenc"},"results":[{"message":"ls ls_csd get cat cat_csd whereis whereis_csd cp cp_csd cd cd_csd time mkdir mkdir_csd find find_csd listFilesFromCollection scrlog submit motd access commit packages pwd ps rmdir rm rm_csd mv mv_csd masterjob user touch touch_csd type kill lfn2guid guid2lfn guid2lfn_csd w uptime addFileToCollection addMirror addTag addTagValue chgroup chown chown_csd createCollection deleteMirror df du fquota jobinfo jquota killTransfer listSEDistance listTransfer md5sum mirror queue queueinfo register registerOutput removeTag removeTagValue resubmit resubmitTransfer showTags showTagValue spy top groups token uuid stat listSEs xrdstat whois addTrigger addHost queue register addSE addUser calculateFileQuota calculateJobQuota groupmembers shutdown edit emacs less mcedit more nano sensible-editor vim"}]}{"metadata":{"site":"CERN","currentdir":"\\/alice\\/cern.ch\\/user\\/a\\/asevcenc\\/","user":"asevcenc"},"results":[{"pwd":"\\/alice\\/cern.ch\\/user\\/a\\/asevcenc\\/","message":"\\/alice\\/cern.ch\\/user\\/a\\/asevcenc\\/"}]}', rsv1=False, rsv2=False, rsv3=False)
> {"metadata":{"site":"CERN","currentdir":"\/alice\/cern.ch\/user\/a\/asevcenc\/","user":"asevcenc"},"results":[{"message":"ls ls_csd get cat cat_csd whereis whereis_csd cp cp_csd cd cd_csd time mkdir mkdir_csd find find_csd listFilesFromCollection scrlog submit motd access commit packages pwd ps rmdir rm rm_csd mv mv_csd masterjob user touch touch_csd type kill lfn2guid guid2lfn guid2lfn_csd w uptime addFileToCollection addMirror addTag addTagValue chgroup chown chown_csd createCollection deleteMirror df du fquota jobinfo jquota killTransfer listSEDistance listTransfer md5sum mirror queue queueinfo register registerOutput removeTag removeTagValue resubmit resubmitTransfer showTags showTagValue spy top groups token uuid stat listSEs xrdstat whois addTrigger addHost queue register addSE addUser calculateFileQuota calculateJobQuota groupmembers shutdown edit emacs less mcedit more nano sensible-editor vim"}]}{"metadata":{"site":"CERN","currentdir":"\/alice\/cern.ch\/user\/a\/asevcenc\/","user":"asevcenc"},"results":[{"pwd":"\/alice\/cern.ch\/user\/a\/asevcenc\/","message":"\/alice\/cern.ch\/user\/a\/asevcenc\/"}]}
> client - state = CLOSING
> client > Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
> client < Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
> client - event = connection_lost(None)
> client - state = CLOSED
> client x code = 1000, reason = [no reason]
> client x closing TCP connection

**Comment by aaugustin** [comment]
`client < ...` is a message from the remote server.

**Comment by adriansev** [comment]
ok, thank you for clarification!!
