### ISSUE TITLE
How do I upgrade websocket server?

### ISSUE THREAD

**Issue by umtek12** [aaugustin/websockets#566]
I was looking at the websockets server code and I dont know how to upgrade and integrate it to the existing code example.

I was using your basic example:
```
import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f"> {greeting}")

start_server = websockets.serve(hello, 'localhost', 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

I keep getting this error from chrome:
![2](https://user-images.githubusercontent.com/33585978/52132724-a3b05100-25f4-11e9-8377-914f200721d7.png)

**Comment by aaugustin** [comment]
You can't access a WebSocket endpoint by typing its address in the URL bar.

Please read the "Getting Started" doc: https://websockets.readthedocs.io/en/stable/intro.html#browser-based-example
