### ISSUE TITLE
patch releases don't appear in changelog

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#572]
I noticed that the patch releases don't appear in the changelog: https://websockets.readthedocs.io/en/stable/changelog.html

It would be useful to be able to know how those differ from the minor version on which they're based.

**Comment by aaugustin** [comment]
4.0.1 was functionally identical to 4.0. I did it because wheels for 4.0 failed to build on Travis CI.

5.0.1 fixed a major regression in 5.0 (#411).

**Comment by cjerdonek** [comment]
Thanks!
