### ISSUE TITLE
websockets.exceptions.InvalidStatusCode: Status code not 101: 401

### ISSUE THREAD

**Issue by BenTearzz** [aaugustin/websockets#575]
Python version: 3.6.5, 3.6.7, 3.7.0
Websockets version: 7.0.0

I have the following code:
`async def notifications(self):
	async with websockets.connect(f"wss://stream.pushbullet.com/websocket/{token}") as websocket:
		while True:
			data = await websocket.recv()
			print(f"Received data: {data}")`

I kept getting a `websockets.exceptions.InvalidStatusCode: Status code not 101: 401` error when running this. Switching Python version did not help. But when I removed websockets version 7.0.0, and installed websockets 6.0.0 it worked again.

**Comment by aaugustin** [comment]
Perhaps websockets 6.0 and 7.0 produce a slightly different handshake and pushbullet dislikes it.

Are you able to:

- locate the sources code of websockets (e.g. `import websockets; print(websockets.__file__)`
- insert a debug statement in `WebSocketClientProtocol.write_http_request`: add `print(request)` just before `self.writer.write(request.encode())`
- run your test code and capture the HTTP request
- do this for websockets 6.0 and 7.0, compare the HTTP requests, and look for any difference?

If there is a difference that could explain why pushbullet responds with a 401 error, then I'll do my best to fix it.

**Comment by BenStigsen** [comment]
6.0.0:
```
GET /websocket/some_oauth_token HTTP/1.1
Host: stream.pushbullet.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: YAP/MC35NM4oXSzwU7qWlQ==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
User-Agent: Python/3.6 websockets/6.0
```

7.0.0:
```
GET /websocket/some_oauth_token HTTP/1.1
Host: stream.pushbullet.com
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: 038+CER/Hy0Ga/0Jbsb/6w==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
User-Agent: Python/3.6 websockets/7.0
```

**Comment by aaugustin** [comment]
Hrm... Aside from the generated random key, I'm not seeing any difference here :-/ If websockets sends the same request but gets a different response, I'm not sure how to proceed.

Obviously you anonymized the OAuth token for this bug report. I assume you double-checked it's correct in both cases? That would be the most obvious cause for a 401 Unauthorized error.

If you want to do the same kind of debugging for the raw HTTP response, which could give us a hint, you can insert `print(line)` just before `return line[:-2]` in `websockets.http.read_line`.

**Comment by aaugustin** [comment]
After 4 months, I assume you figured it out or you moved on, so I'm going to close this issue

**Comment by BenTearzz** [comment]
Well, I found a solution. I'm using version 6.0.0 instead of 7.0.0.

**Comment by aaugustin** [comment]
That makes sense. I'm sorry we couldn't figure it out. I can try to help you debug this further if you need to upgrade at some point.
