### ISSUE TITLE
Is setting of max_queue to 0 blocking receiving of messages completely?

### ISSUE THREAD

**Issue by petr-fedorov** [aaugustin/websockets#576]
Documentation for [class websockets.protocol.WebSocketCommonProtocol](https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol) state that:
> The max_queue parameter sets the maximum length of the queue that holds incoming messages. The default value is 32. 0 disables the limit. Messages are added to an in-memory queue when they’re received; then recv() pops from that queue. 

But when I set max_queue to 0, messages are not added to queue at all as if the queue size became ... zero and it is always full!  recv() never returns (I see in the log that messages ( a single welcome message in my case)  arrive  from a server but are  not returned by recv() aftewards).

 Is that an expected behaviour?  If yes I would suggest to re-write this sentence:

> 0 disables the limit.

**Comment by aaugustin** [comment]
I suspect the behavior may have changed accidentally when I replaced the `asyncio.Queue` with a `collections.deque`.

**Comment by aaugustin** [comment]
You can work around the bug with `max_queue=2**20` — hopefully a million messages is enough?

**Comment by petr-fedorov** [comment]
@aaugustin Hmm, I used exactly this number - how did you know? :-)

**Comment by aaugustin** [comment]
I read minds.

**Comment by aaugustin** [comment]
;-)
