### ISSUE TITLE
HEADERS

### ISSUE THREAD

**Issue by FUCKYOUCUNTAAAAAAAH** [aaugustin/websockets#577]
PLEASE MAKE THE USE OF HEADERS MORE CLEAR.
WHAT TYPE OF DATA TAKES THE PARAM origin from websockets.client.connect(origin=WHATTHEHELL)
WHAT THE ACTUAL FUCK IS GOING ON HERE.
THANKS.

**Comment by lgrahl** [comment]
Go away...
