### ISSUE TITLE
performance decay with yield from ws.send multi connection

### ISSUE THREAD

**Issue by hippo-dalaoshe** [aaugustin/websockets#580]
Version
```
python 3.4
websockets 4.0.1
```
I use one main thread and one event loop to handle websocket connection, and echo every msg to the client connection.
I find that, when increase the connection with 1 msg/s per connection, the request arrive time (time interval between the request is sent from client and the request is recv from yield from connection.recv()) will increase quickly. 
In my test environment, all client and the server are deploy in the same local network, and only one connection, the arrival time delay is about 20ms, but when it increase to 500 connection, the delay is up to 500ms - 1s.
 
I think the problem happen in the yield from connection.send() call, may the send buffer or recv buffer is low performance?

**Comment by aaugustin** [comment]
This is a fairly broad question. If you can propose changes that will improve performance, I'm definitely interested.

**Comment by lgrahl** [comment]
I would suggest doing the performance evaluation with (and without) uvloop, the latest Python version and the current version of the library before doing further investigation.

**Comment by aaugustin** [comment]
Agreed.

My guess is that performance characteristics shouldn't differ widely beetween websockets 4 and 7; Python 3.4 vs 3.7 could make a difference. Definitely worth trying uvloop.

**Comment by hippo-dalaoshe** [comment]
Thanks, it is my first time to use `uvloop`, I try  `uvloop` in `python 3.6.6`, it seems the problem has not been improve efficiently. Now, I decide to use `c++` and `boost`  to test the performance, if I can find the performance improve method fortunately, I will post it.

**Comment by LanDeQuHuXi** [comment]
I tried with a simple echo server as well that I could NOT see any performance improvement with uvloop either, which is kind of contrary to what they have been advertising.

**Comment by hippo-dalaoshe** [comment]
> I tried with a simple echo server as well that I could NOT see any performance improvement with uvloop either, which is kind of contrary to what they have been advertising.
> 
> But I also tested context switching, which shows uvloop is faster 2x to 3x. I guess if we can figure out where is the bottle neck, websockets can be 2x to 3x faster by just switching to uvloop.
> 
> ```
> # test simple context switching
> NUM = 100000
> 
> async def run_event_loop(times):
>     for _ in range(times):
>         await asyncio.sleep(0)
> 
> loop = asyncio.get_event_loop()
> t0 = time.time()
> loop.run_until_complete(run_event_loop(NUM))
> t1 = time.time()
> logging.info(f'took {t1-t0:.6f} to run {NUM} context switching')
> ```
thanks for help, I retry my example and remove all the useless code,  I find it I ignore a  time-consuming operation before which cause this problem. So it is not the problem of `websockets`, I will close this issue, but I did not find the faster of uvloop, maybe there is something wrong with my test? I will try it latter.
