### ISSUE TITLE
How to put the websockets on a schedule?

### ISSUE THREAD

**Issue by vgoklani** [aaugustin/websockets#582]
Hey there - quick question, how would I put the websockets on a schedule, so that the feed connects at 8am, and disconnects at 6pm, M-F? Any ideas?

Thanks!

**Comment by ssshah86** [comment]
Checkout: https://github.com/dbader/schedule

**Comment by RemiCardona** [comment]
This is out of the scope of the websockets module. I suggest looking at time/date libraries on pypi. Cheers.

**Comment by vgoklani** [comment]
I don't agree; it's not trivial to stop an async connection at a set time.

**Comment by lgrahl** [comment]
What's wrong with @ssshah86's suggestion? You can run that as a task on the event loop.

**Comment by aaugustin** [comment]
I agree:

- with vgoklani that termination can be more difficult that one might expect in asyncio
- with RemiCardona that this is out of scope for websockets

Generally speaking I'm trying to draw a line between `asyncio` and `websockets`. I feel this falls on the `asyncio` side.

`websockets` provides an API for closing connections. If you have issues with that API, then it's a `websockets` issue.
