### ISSUE TITLE
TimeoutError when trying to connect to own server

### ISSUE THREAD

**Issue by matcool** [aaugustin/websockets#583]
I'm trying to run a websocket server, which works fine on my computer (where I'm running it and connecting via localhost), but whenever I try to connect via somewhere else (different network, or even a different device on the same wifi) I get a timeout error. 
edit: My port forwarding works properly, as it works fine when running something like `python -m http.server`

**Comment by matcool** [comment]
After some struggling I found why, I have to run the server with my lan ip instead of localhost.

**Comment by aaugustin** [comment]
Might be worth adding to a FAQ!
