### ISSUE TITLE
How to build a multi-processing websocket server?

### ISSUE THREAD

**Issue by erelsgl** [aaugustin/websockets#584]
I built a simple websocket server with websockets and it works great. However, when two or more clients connect at the same time, the server waits for one to finish before starting to process the other.
I tried to use "multiprocessing.Process" or "ProcessPoolExecutor" but got errors such as "coroutine is never awaited" or "can't pickle asyncio.Future objects".

Is it possible to build a websocket server that can handle multiple connections with multiprocessing?

**Comment by aaugustin** [comment]
Probably your connection handler blocks? Running with asyncio debug enabled could help: https://docs.python.org/3/library/asyncio-dev.html#debug-mode

**Comment by aaugustin** [comment]
(and it's certainly wrong to use multiprocessing here)

**Comment by winner484** [comment]
@aaugustin 
#But how to do this?
    import asyncio
    import websockets

    @asyncio.coroutine
    def hello(websocket, path):
        name = yield from websocket.recv()
        print("< {}".format(name))

        greeting = "Hello {}!".format(name)

        yield from websocket.send(greeting)
        print("> {}".format(greeting))

    start_server = websockets.serve(hello, 'localhost', 8765)

    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()

**Comment by aaugustin** [comment]
I'm sorry, I don't understand your question. Please explain what result you're getting and what result you're expecting.
