### ISSUE TITLE
how to add different coroutine dynamiclly in the same websocket port?

### ISSUE THREAD

**Issue by chendongxtu** [aaugustin/websockets#586]
Hi, aaugustin!

**Comment by chendongxtu** [comment]
thanks for your work , i'm confused about a question like followed:
   all the demo in the webscoket-server is like: 
      start_server = websockets.serve(hello, 'localhost', 8765)
    and the first param hello is a ws_handler, and it binds the port 8765,  so i has some problems with this and i don't know how to solve it.
    1、if i wanna to register another ws_hanler, i need use like this:
              another_server = websockets.serve(another_hello, 'localhost', 8765)
          the problem is 8765 is used by hello, so it will encounter error, can i use the same port in different ws_hander?
     2、when use websockets.serve ， it needs init an exist ws_handler at first, but i wanna to add ws_handler dynamiclly, how can i do this?
        best wishes!

**Comment by aaugustin** [comment]
Currently you can have only one handler. You need to dispatch different URLs by yourself. See also #311.

**Comment by chendongxtu** [comment]
thanks, the link #311 has told me how to process different handler via url.
the left problem is the handler must be inited where we call websockets.serve() function.
that is to say when websockets channel connected, the handler are called and consumed.
follwing is my demands:
i want to create a websocket channel at first, and then tell the client the pay result in realtime
this is the my flow:
	1、in frontend, there is a page for user to deposit.
	2、in backend, when frontend sends a deposit request, the backends will create an order, 
	and then send the deposit request to thirdparty, and then return the order_id to the frontend.
	3、the frontend use the order_id to query backend through short polling until the thirdparty return the pay result.
	so, in step3, i want to used websocket replace short polling, if thirdparty callback the backend, then the backend
	send the result to frontend through websockt, this can avoid frenquency request from frontend.

so my idea is:
1、create a webscoket channel between client and server at first.
2、when the thirdparty callback the server, the server notify the callback content to cilent through the websocket channel.

following is the simplest sample code:

############ server.py #############
import websockets
import asyncio
import json
import flask
from flask import Flask, request, jsonify
from flask_wtf.csrf import CsrfProtect
import functools
csrf = CsrfProtect()
app = Flask(__name__)


async def notify_result(websocket, path, result):
	await websocket.send(result)


@app.route('/scan_qrcode_deposit_result_notify', methods=['GET']) # for test, change the method post to get
def scan_qrcode_deposit_notify():
    # suppose there are three guys A, B, C, so the thirdparty will callback three times
    # and the server need notify the client three times
    # we can done this through we browser, type http://127.0.0.1:5000/scan_qrcode_deposit_result_notify?order_id=3
    result = {'order_id': request.args.get('order_id'),  'status': 'success'}

    try:
        handler = functools.partial(notify_result, result=json.dumps(result))
        print('-----------handler success----------')
        asyncio.get_event_loop().run_until_complete(websockets.serve(handler, 'localhost', 8765))
    except Exception as e:
        print('encounter error')
        print(e)

    return jsonify(code=0, message='ok')

if __name__ == '__main__':
    csrf.init_app(app)
    app.run(debug=True)


##########client.py##########
import asyncio
import websockets

async def hello():
	import ipdb
	ipdb.set_trace()
	async with websockets.connect(
		'ws://localhost:8765/') as websocket:
		
		#name = input("what's your name?")
	
		#await websocket.send(name)
		#print("> {}".format(name))

		greeting = await websocket.recv()
		print('< {}'.format(greeting))

asyncio.get_event_loop().run_until_complete(hello())
asyncio.get_event_loop().run_forever()


then i run python server.py and type http://127.0.0.1:5000/scan_qrcode_deposit_result_notify?order_id=3 in chorme,
every thing is okay, but when i try to type python client.py in the console, it encounter following error:
#########error info start#######################
Traceback (most recent call last):
  File "websocket_study/client.py", line 22, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "websocket_study/client.py", line 11, in hello
    async with websockets.connect(
  File "/home/chendong/Desktop/project/venv/lib/python3.5/site-packages/websockets/py35/client.py", line 2, in __aenter__
    return await self
  File "/home/chendong/Desktop/project/venv/lib/python3.5/site-packages/websockets/py35/client.py", line 12, in __await_impl__
    transport, protocol = await self._creating_connection
  File "/usr/lib/python3.5/asyncio/base_events.py", line 695, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.5/asyncio/base_events.py", line 682, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 402, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 432, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8765)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
#########error info end#######################


i can not fix why the problem is,
if my idea error or my code flow is error? 
how can i realize it?

**Comment by chendongxtu** [comment]
and when i write like this:

**Comment by chendongxtu** [comment]
and when i write like this:
if __name__ == '__main__':
    handler = functools.partial(notify_result, result=json.dumps({'hello': 'American'}))
    loop = asyncio.get_event_loop()
    server = loop.run_until_complete(websockets.serve(handler, 'localhost', 8765))
    csrf.init_app(app)
    app.run(debug=True)

this error is:
python flask_test.py 
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 958, in create_server
    sock.bind(sa)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask_test.py", line 36, in <module>
    server = loop.run_until_complete(websockets.serve(handler, 'localhost', 8765))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 564, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/chendong/Desktop/project/venv/lib/python3.5/site-packages/websockets/py35/server.py", line 13, in __await_impl__
    server = await self._creating_server
  File "/usr/lib/python3.5/asyncio/base_events.py", line 962, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8765): address already in use

can not i use it in the flask main thread?

**Comment by aaugustin** [comment]
There's a lot going on here, but as far as I can tell, you're starting a new `websockets` servers with every HTTP request to this Flask view. The first one will work; the second won't because the port is already used by the first one.

This isn't a workable design. Try running separate websockets and flask servers and communicating between them with a messaging system — the easiest could be Redis pub/sub.

**Comment by aaugustin** [comment]
There's a lot going on here, but as far as I can tell, you're starting a new `websockets` servers with every HTTP request to this Flask view. The first one will work; the second won't because the port is already used by the first one.

This isn't a workable design. Try running separate websockets and flask servers and communicating between them with a messaging system — the easiest could be Redis pub/sub.
