### ISSUE TITLE
howto :: add websocket client query to a derived class

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#588]
Hi! I am trying to add a websocket query to a (custom) class (derived from another, not under my control). For that member function i added "async" in front of declaration but i receive a message from the base class that `RuntimeWarning: coroutine 'MyCopyProgressHandler.end' was never awaited` and seems that is not executed. - [my code](https://github.com/adriansev/jalien_py/blob/master/alien.py#L56)
Any idea what can be done?
Thank you!!

**Comment by aaugustin** [comment]
This isn't really a websockets issue. Try StackOverflow maybe?

You're more likely to get an answer if you post a minimal example rather than a 550 lines long script.
