### ISSUE TITLE
RuntimeWarning: coroutine 'process_request' was never awaited

### ISSUE THREAD

**Issue by Jacobh2** [aaugustin/websockets#597]
Hey!

First of all, thanks for an awesome lib!

I'm having some issues with the `websocket.serve` function when I'm passing a partial async method as the `process_request` arg.

I see in [the docs](https://websockets.readthedocs.io/en/stable/api.html?highlight=process_request#websockets.server.WebSocketServerProtocol.process_request) that this method is allowed to be a coroutine, which is what I need. I do, however also require more arguments to be passed into the method. Therefore I'm using the `functools.partial`.

I'm now wondering if this makes the lib confused as if the passed function is a regular method or coroutine, as [this](https://stackoverflow.com/questions/52422860/partial-asynchronous-functions-are-not-detected-as-asynchronous) suggest.

I'm getting these logs:
```
2019-04-16 07:12:57,006#WARNING:MainThread:websockets.server:handler                            : 147 :Error in opening handshake
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 117, in handler
    extra_headers=self.extra_headers,
  File "/usr/local/lib/python3.7/site-packages/websockets/server.py", line 483, in handshake
    raise AbortHandshake(*early_response)
TypeError: type object argument after * must be an iterable, not coroutine
/usr/local/lib/python3.7/site-packages/websockets/server.py:166: RuntimeWarning: coroutine 'process_request' was never awaited
  return
```
when using the `process_request` as:
```py3
async def process_request(handler, path, request_headers):
    pass


def create_server(host, port):
    process_request_fn = partial(process_request, client_handler)
    handle_fn = partial(handle, client_handler)
    return websockets.serve(handle_fn, host, port, process_request=process_request_fn)
```

I have successfully used the `handle` function in a partial and which is async, but now needed also the `process_request` function to be async. Am I missing something? Thanks for all the help.

**Comment by Jacobh2** [comment]
Tested to install directly from master branch, which makes it work!

Problem with last release (7.0) is the code
```py3
# Hook for customizing request handling, for example checking
# authentication or treating some paths as plain HTTP endpoints.
if asyncio.iscoroutinefunction(self.process_request):
    early_response = yield from self.process_request(path, request_headers)
else:
    early_response = self.process_request(path, request_headers)
```
[here](https://github.com/aaugustin/websockets/blob/7.0/src/websockets/server.py#L471) which is exactly the problem as the linked Stackoverflow talks about.

In [master branch](https://github.com/aaugustin/websockets/blob/master/src/websockets/server.py#L507), a smarter use of `isinstance(early_response, Awaitable)` is used, which makes this work perfectly when using partials! 👍 

@aaugustin, how does the release schedule look like? Do you think it would be possible to make a release with this fix to PyPi?

**Comment by aaugustin** [comment]
Hell and sorry for not answering earlier!

The release schedule looks like "every few months, I go through the backlog of issues, decide which one I want to fix in the next release, fix them, and make a release". I'm at the stage of going through the backlog of issues, which puts the next release in July, hopefully.
