### ISSUE TITLE
Connection getting closed when masking is not being used

### ISSUE THREAD

**Issue by deep110** [aaugustin/websockets#598]
I am using a websocket client in another lang (C), unable to send data without masking. Able to send the same data when masking is enabled.
According to RFC 6455, masking can be optional. 

This is how I am forming my packet.
```
unsigned int frame_size = 4 + payload_len;
char* data = (char*)malloc(frame_size);
memset(data, 0, frame_size);

*((char*)data) = 0x81; // setting first byte
*((char*)data+1) = 126 | 0x0; //payload length with mask bit off

payload_len &= 0xffff;
unsigned int len_size = 2;
for(i = 0; i < len_size; i++) {
	*((char*)data+2+i) = *((char*) &payload_len + (len_size-i-1));
}
memcpy(data+4, buf, buf_len);
```

Thanks for any help.

**Comment by lgrahl** [comment]
From [RFC 6455, sec 5.1](https://tools.ietf.org/html/rfc6455#section-5.1):

> To avoid confusing network intermediaries (such as
   intercepting proxies) and for security reasons that are further
   discussed in Section 10.3, a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).
