### ISSUE TITLE
Update docs to remove Python 3.4/3.5 support

### ISSUE THREAD

**Issue by Morocat** [aaugustin/websockets#599]
I got pretty far into a project on python 3.6 only to find on my target running 3.5 websockets are no longer supported. It would have been nice to know this in advance.

**Comment by lgrahl** [comment]
It's in the docs and in the readme. I'm not sure what more you want. :slightly_smiling_face: 

7.0 (current release) still supports 3.4.

**Comment by Morocat** [comment]
My bad, I meant pypi.

**Comment by lgrahl** [comment]
PyPI obviously does not reflect `master`. :woman_shrugging:
