### ISSUE TITLE
.wait() timeout behavior -- is this a bug?

### ISSUE THREAD

**Issue by carlcrott** [aaugustin/websockets#601]
In looking through the docs this might not be a bug as:

> Note that this function does not raise asyncio.TimeoutError. 
> Futures or Tasks that aren’t done when the timeout occurs are simply returned in the second set.

except "done" and "pending" below give no outputs

```
import asyncio
import time

def eternity():
    # Sleep for one hour
    time.sleep(3600)
    return 'yay!'

async def intermediary():
    # Demonstrate non-timeout of .wait()
    done, pending = await asyncio.wait(eternity(), timeout=1)
    print(done)
    print(pending)

async def main():
    # Wait for at most 1 second
    try:
        await asyncio.wait_for(intermediary(), timeout=3.0)
    except asyncio.TimeoutError:
        print('timeout!')

asyncio.run(main())

```

What is the function of the timeout argument for the .wait() method ?

UPDATE:
If the .wait() method cant timeout, then how does a timeout event populate up to cause a handleable exception?

**Comment by lgrahl** [comment]
I don't see how this is related to this library. You probably want to ask it in the Python IRC (freenode #python) or open a bug report in the Python bug tracker. :slightly_smiling_face:

**Comment by carlcrott** [comment]
@igrahl the problem is that the code returns non-standard behavior, specifically quiet failures, for standard python try / except blocks.


Restated: why does the above code not fail with an exception?

The problem becomes obvious when the server>>client communication ultimately uses a websocket.send() method which is within a wait(), which throws no error.

IE: It seems theres no way to catch failed server > client pushes.

**Comment by carlcrott** [comment]
```
import asyncio
import time

async def eternity():
    await asyncio.sleep(3600)
    return 'yay!'


async def intermediary():
    await asyncio.wait_for(eternity(), timeout=1)


async def main():
    try:
        await asyncio.wait_for(intermediary(), timeout=2)
    except asyncio.TimeoutError:
        print('timeout!')

asyncio.run(main())


```

^ This does give the expected behavior... however this is declaring everything as asynchronous.

Okcool. But if I wanted access to the  'yay!' returned by eternity()  in intermediary()  

... how would I do that?

**Comment by aaugustin** [comment]
> But if I wanted access to the 'yay!' returned by eternity() in intermediary()

```python
async def intermediary():
    result = await asyncio.wait_for(eternity(), timeout=1)
    return result
```

(again, nothing to do with websockets)

**Comment by carlcrott** [comment]
@aaugustin The timeout problem still exists.  

which is highlighted by @lgrahl 's claim:

> Edit: time.sleep is synchronous. You need to use asyncio.sleep.
This: 
```
def eternity():
    # Sleep for one hour
    time.sleep(3600)
    return 'yay!'
```

Should behave all the same as this:

```
async def eternity():
    # Sleep for one hour
    await time.sleep(3600)
    return 'yay!'
```

It was my hope that something like this would work, and return a timeout:

```
async def eternity(): 
    time.sleep(3600)
    return 'yay!'
```

... but it doesn't.

I'm assuming its very very complex to get asyncio timeouts to behave with the 'synchronous' methods @lgrahl described?

I'm using this to interface with real-time serial hardware and while I've fixed my problem... not having timeouts for everyday non-asynchio-functions could cause problems in the future.

**Comment by lgrahl** [comment]
Please accept the fact that your question has nothing to do with this library. The only common denominator of this library and your question is the usage of `asyncio`. We could answer it but this is not the place where it should be discussed.

Easiest would be to ask your question in Python's IRC: https://www.python.org/community/irc/

**Comment by carlcrott** [comment]
Im sorry. Pretend im retarded then.

What question should I be asking regarding how to time out a asyncio function?
