### ISSUE TITLE
How could I listen to any ipv4 connections?

### ISSUE THREAD

**Issue by stereomatchingkiss** [aaugustin/websockets#602]
The example only show us how could we listen to localhost, but how could we listen to a range of ip or any ipv4, ipv6 connection?

I tried with this solution, but it do not work

`start_server = websockets.serve(hello, '0.0.0.0', 1234, ssl=ssl_context)`

**Comment by aaugustin** [comment]
websockets.serve works like asyncio.create_server, so you can refer to the documentation of [create_server](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server):

> If host is an empty string or None, all interfaces are assumed and a list of multiple sockets will be returned (most likely one for IPv4 and another one for IPv6).
