### ISSUE TITLE
Document how to create channels or rooms

### ISSUE THREAD

**Issue by britisharmy** [aaugustin/websockets#603]
How can i send a message to a specific room or channel

In the docs, you only have this

``    await websocket.send(greeting)``

I want to send to specific channel and subscribe to that channel on the client side.

**Comment by lgrahl** [comment]
See #481.

**Comment by aaugustin** [comment]
I'm going to reopen this as a documentation issue. This is a reasonable question; we should address it in the docs.

**Comment by aaugustin** [comment]
Closing in favor of  #621.
