### ISSUE TITLE
How to set response header on server

### ISSUE THREAD

**Issue by vcJiang** [aaugustin/websockets#607]
I try to use vue-socket-io to connet websocket server , but an error about 'No 'Access-Control-Allow-Origin' header is present on the requested resource.'  here is my server code:

```python
async def test(websocket, path):
    print('testing async')
    while True:
        # print('testing async')
        await websocket.send(b'hahahah')
        await asyncio.sleep(1)

header = {'Access-Control-Allow-Origin' : '*'}
chat_server = websockets.serve(test, 'localhost', 9999, extra_headers=header)

asyncio.get_event_loop().run_until_complete(chat_server)
asyncio.get_event_loop().run_forever()`
```

Maybe this question is about response header, please help

**Comment by aaugustin** [comment]
Can you try to enable logging at the DEBUG level? Like https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging but with DEBUG instead of INFO.

I don't remember if it logs the HTTP request / response. If it does, that could help.

**Comment by vcJiang** [comment]
> server - state = CONNECTING
server - event = connection_made(<_SelectorSocketTransport fd=2272 read=idle write=<idle, bufsize=0>>)
Invalid upgrade
Traceback (most recent call last):
  File "C:\Users\jzm16\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\server.py", line 117, in handler
    extra_headers=self.extra_headers,
  File "C:\Users\jzm16\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\server.py", line 485, in handshake
    key = check_request(request_headers)
  File "C:\Users\jzm16\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\handshake.py", line 86, in check_request
    raise InvalidUpgrade('Connection', connection)
websockets.exceptions.InvalidUpgrade: Invalid Connection header: ['keep-alive']
server ! failing WebSocket connection in the CONNECTING state: 1006 [no reason]
server x half-closing TCP connection
server - event = eof_received()
server - event = connection_lost(None)
server - state = CLOSED
server x code = 1006, reason = [no reason]

here is after logging but I don't know what it caused. other people give some solutions that I could try to use nginx or maybe we have some methods to alter CORS？

there is the error in html page:
`Failed to load resource: the server responded with a status of 426 (Upgrade Required)
Access to XMLHttpRequest at 'http://localhost:9999/socket.io/?EIO=3&transport=polling&t=Mfd1G70' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by aaugustin** [comment]
> ` websockets.exceptions.InvalidUpgrade: Invalid Connection header: ['keep-alive']`

vue-socket-io doesn't attempt a WebSocket connection: you're receiving `Connection: keep-alive` instead of `Connection: upgrade`.
