### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [aaugustin/websockets#609]
Hey again @aaugustin :)

You said that I could design a logo for this repo. Here's the logo I designed. If you like it, I am waiting for your advice about the color.

![ws](https://user-images.githubusercontent.com/36298335/57143426-8774a980-6dc7-11e9-8a2a-fe222a63df4d.jpg)

**Comment by reallinfo** [comment]
Also, web-site view;

![wsread](https://user-images.githubusercontent.com/36298335/57143592-e0444200-6dc7-11e9-9dba-2e60d5f6cb59.png)

**Comment by aaugustin** [comment]
Looks perfect! Thanks!

**Comment by reallinfo** [comment]
other variations;

![ws](https://user-images.githubusercontent.com/36298335/57197779-2211eb80-6f74-11e9-8f63-bc09c1b6e77d.jpg)

**Comment by reallinfo** [comment]
If there is no your other request, I will send a pr.

**Comment by aaugustin** [comment]
In the vertical / horizontal logos, could you change the spelling to websockets (lower-case and with an s)?

The protocol is called WebSocket and my library is called websockets. I realize that I sometimes wrote WebSockets; this is a mistake; let's standardize to websockets.

**Comment by reallinfo** [comment]
oh sorry, how does look it now?

![ws](https://user-images.githubusercontent.com/36298335/57223797-f47a8000-700f-11e9-895c-dde9f96bde17.jpg)

**Comment by reallinfo** [comment]
So i can send a pr ? :)

**Comment by aaugustin** [comment]
Last question — what font did you use for the text?

**Comment by reallinfo** [comment]
sure, please look [here](https://www.dafont.com/typo-round.font) 

Also, feel free to write me your other projects.
