### ISSUE TITLE
How to generate new EC key and assign to websockets?

### ISSUE THREAD

**Issue by Truth0906** [aaugustin/websockets#610]
As title,

How to generate new EC key and assign to websockets?

Thanks

**Comment by aaugustin** [comment]
I don't know what an EC key is.

**Comment by aaugustin** [comment]
If you're referring to an elliptic-curve based certificate for securing a WSS connection, then examples for "assign to websockets" is here: https://websockets.readthedocs.io/en/stable/intro.html?highlight=tls#secure-example and there: .https://docs.python.org/3/library/ssl.html#server-side-operation

**Comment by Truth0906** [comment]
Thank you, I will study those articles.
