### ISSUE TITLE
How to change the HTML response message when viewed from a browser

### ISSUE THREAD

**Issue by Verequies** [aaugustin/websockets#611]
How does one change the message in the HTML response when viewed in a browser?

At the moment it responds: "Invalid Upgrade header: []".
I would like to change that to for example: "Websocket for Program, Connect using Websockets".

I understand this is in the '426 Upgrade Required' response, however I'm not sure how to set that up.

I've setup notification websockets for Phabricator via reverse proxy through NGINX, and that responds with "HTTP/501 Use Websockets" when you browse to 'phabricator.example.com/ws'.

If its not directly possible, at least at the moment, is there a workaround?

**Comment by aaugustin** [comment]
This must be very common; websockets should provide a better error message.

You can work around the issue with a custom `process_request` that detects when there's no upgrade header and returns a suitable HTTP response.

There's an example here: https://websockets.readthedocs.io/en/stable/deployment.html?highlight=process_request#port-sharing

Adapt it: `if 'Upgrade' not in request_headers: ...`

**Comment by Verequies** [comment]
Awesome! Just tested that and it works fine. Does the 'process_request' function affect any other operations of websockets? As in do I have to reimpliment anything by using it?

Also this got me thinking, is it possibly to supply a HTML page instead of plain text?

**Comment by aaugustin** [comment]
No, you don't have to reimplement anything. The default implementation of `process_request` does nothing: https://github.com/aaugustin/websockets/blob/52872a5485651d606900cddd720b4a4aa658d690/src/websockets/server.py#L303

You can provide a HTML page by setting the Content-Type header to text/html and putting some HTML in the body.

**Comment by Verequies** [comment]
Ah I see, thanks for clarifying that.

Having a bit of trouble setting the Content-Type header. I've looked at the API and some examples, but its not working. In my websockets serve function, I have set extra_headers=[{"Content-Type": "text/html"}].

**Comment by aaugustin** [comment]
Right, `extra_headers` only applies when the websocket connection is established successfully.

**Comment by Verequies** [comment]
Ah yep, thanks, good to know.

**Comment by aaugustin** [comment]
I'm going to change the error message to:

```
Failed to open a WebSocket connection: invalid Connection header: keep-alive.

You cannot access a WebSocket server directly with a browser. You need a WebSocket client.
```

I'm keeping the detail of which headers is wrong because it may help people debugging their websocket clients.
