### ISSUE TITLE
ssl.SSLError flooding logs

### ISSUE THREAD

**Issue by Verequies** [aaugustin/websockets#614]
I just added SSL/TLS support to my websocket implementation, and upon testing it I get ssl.SSLError's such as the following:
`ssl.SSLError: [SSL: WRONG_VERSION_NUMBER]`
`ssl.SSLError: [SSL: UNKNOWN_PROTOCOL]`
`ssl.SSLError: [SSL: NO_SHARED_CIPHER]`

Trying to add an 'except ssl.SSLError' does not seem to work. Is there a way to turn the errors off?

I understand this is with the underlying SSL library, however I have a strict configuration for SSL/TLS and I don't want to see these messages for clients of which I don't support of which I am testing with testssl.sh.

EDIT: Probably should post an example traceback :D
```
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x61dae08788d0>
transport: <_SelectorSocketTransport closing fd=10 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)
```

**Comment by aaugustin** [comment]
This StackOverflow question (in the context of `aiohttp`, not `websockets`, but it's the same issue) has a pretty good answer:

https://stackoverflow.com/questions/52012488/ssl-asyncio-traceback-even-when-error-is-handled

Unfortunately, the ticket in the Python bug tracker hasn't gotten much attention:

https://bugs.python.org/issue34506

----

One thing I'm not sure about is whether the logging is triggered from `websockets` or from `asyncio`. Would you be able to configure logging in your application to display the name of the logger?

If it's a `websockets.<something>` logger, then I can do something about it.

**Comment by lgrahl** [comment]
The error is raised via the `asyncio` logging channel.

@Verequies depending on what kind of logging module you use, you can filter the log message. This is what we have done to work around #606 (happens a lot in production but never locally).

**Comment by aaugustin** [comment]
Closing in favor of https://bugs.python.org/issue34506.

**Comment by carlvon1800** [comment]
Hi Guys,

I got around this by creating a custom exception_handler.  Just posting in case others can use this.

def exception_handler(loop, context):
    exception = context['exception']

    if isinstance(exception, SSLError):
        pass
    else:
        raise exception

loop.set_exception_handler(exception_handler)
