### ISSUE TITLE
A way to avoid writing to .cache/Python-Eggs/ ?

### ISSUE THREAD

**Issue by Talkless** [aaugustin/websockets#615]
Some Python application started to use Websockets, and `AppArmor` started to deny writing to the `~/.cache/`, `~/.cache/Python-Eggs/`... . When tweaking AppArmor rules, it came to the need to *allow writing and mmap'ing .so files, written in the user directory*:
```
type=AVC msg=audit(1558123907.535:5936): apparmor="DENIED" operation="file_mmap" profile="electrumx_server" name="/home/electrumx/.cache/Python-Eggs/websockets-7.0-py3.6-linux-armv7l.egg-tmp/websockets/speedups.cpython-36m-arm-linux-gnueabihf.so" pid=16500 comm="electrumx_serve" requested_mask="m" denied_mask="m" fsuid=998 ouid=998
```
When MAC idea is to limit what application can read/write/execute, this "feature" really decreases security a lot...

Is there a way to setup `websockets` package so that these writes by the user application (not root who installs it) would not be needed..? Some how to generate this cache while installing, etc..?

Thanks!

**Comment by Talkless** [comment]
This is what happens if these writes are denied:

```
May 17 23:26:13 odroid-hc1 electrumx[18858]: pkg_resources.ExtractionError: Can't extract file(s) to egg cache                                        [2/1838]
May 17 23:26:13 odroid-hc1 electrumx[18858]: The following error occurred while trying to extract file(s)
May 17 23:26:13 odroid-hc1 electrumx[18858]: to the Python egg cache:
May 17 23:26:13 odroid-hc1 electrumx[18858]:   [Errno 13] Permission denied: '/home/electrumx/.cache/Python-Eggs/websockets-7.0-py3.6-linux-armv7l.egg-tmp/web
sockets/speedups.cpython-36m-arm-linux-gnueabihf.so'
May 17 23:26:13 odroid-hc1 electrumx[18858]: The Python egg cache directory is currently set to:
May 17 23:26:13 odroid-hc1 electrumx[18858]:   /home/electrumx/.cache/Python-Eggs
May 17 23:26:13 odroid-hc1 electrumx[18858]: Perhaps your account does not have write access to this directory?
May 17 23:26:13 odroid-hc1 electrumx[18858]: You can change the cache directory by setting the PYTHON_EGG_CACHE
May 17 23:26:13 odroid-hc1 electrumx[18858]: environment variable to point to an accessible directory.
```

**Comment by Talkless** [comment]
Looks like `python3 ./setup.py easy_install -Z .` helps to avoid need to uncompress at runtime. Out of scope..?

**Comment by SomberNight** [comment]
Running `setup.py` directly is deprecated though, isn't it? see e.g. https://github.com/pypa/setuptools/issues/960#issuecomment-277343010

Also see https://setuptools.readthedocs.io/en/latest/easy_install.html
> Warning Easy Install is deprecated. Do not use it. Instead use pip. If you think you need Easy Install, please reach out to the PyPA team (a ticket to pip or setuptools is fine), describing your use-case.

`pip install` should always be preferred now I think

Also, what if, as in your example, `websockets` is just a dependency of another package?
Does your workaround work then?

**Comment by Talkless** [comment]
> pip install should always be preferred now I think

Yes, it's the dependency. I've checkouted the source of the software (electrumx, https://github.com/kyuupichan/electrumx/blob/master/setup.py) and wanted install it directly from the source.

**Comment by aaugustin** [comment]
To the best of my knowledge, websockets isn't doing anything weird that would cause this.

Furthermore, [I don't provide support for issues related to Bitcoin or cryptocurrency](https://websockets.readthedocs.io/en/stable/contributing.html#bitcoin-users) and it looks like electrum falls in this bucket.
