### ISSUE TITLE
Client side documentation

### ISSUE THREAD

**Issue by parthsharma1996** [aaugustin/websockets#616]
In the client side example and documentation, I was unable to find the familiar `on_opne`, `on_message` and `on_close` functions that you get in a standard WebSocket object in JavaScript (and also https://github.com/websocket-client/websocket-client) 

Is this because this is a lower level implementation? What am I missing? 

P.S. I also didn't understand the examples very well in general due to the use of `asyncio` functions which I am unfamiliar

**Comment by lgrahl** [comment]
It's not lower level but just a different API. There are two standards: The [WHATWG WebSocket API for browsers](https://html.spec.whatwg.org/multipage/web-sockets.html#network) and the [IETF WebSocket Protocol](https://tools.ietf.org/html/rfc6455). The latter does not require the former.

You probably want to familiarise yourself with `asyncio` before diving into this library. Once you do grasp the concepts a little, I have no doubts that this API will start to make more sense to you. (Warning: Potential adverse effects include suddenly perceiving event-based callback APIs as ugly.)

**Comment by aaugustin** [comment]
Actually it's a higher level API.

From low-level to high-level you have:

1. Callbacks
2. Futures
3. Coroutines

You're talking of level 1. websockets provides a level 3 API.

There are other libraries if you enjoy callback-based code ;-)
