### ISSUE TITLE
exception error still processing messages?

### ISSUE THREAD

**Issue by Postea-CS** [aaugustin/websockets#622]
i have a simple server as such 
```
async def onConnect(websocket, path):
    try:
    async for message in websocket:
            await processMessage(message)
    except  Exception as e:
        logging.warning(f"hard disconnect")
    logging.info(f"Device disconnected")
    websocket.close();

start_server = websockets.serve(onConnect, '127.0.0.1', SERVERPORT,ping_interval=None)
asyncio.get_event_loop().run_until_complete(start_server)
```

once in a while i get this on the server logs. 
_server ! failing WebSocket connection in the OPEN state: 1006 [no reason]
server - event = connection_lost(None)
server - state = CLOSED
server x code = 1006, reason = [no reason]
server x half-closing TCP connection_

Curious why that happens but it seems that while i caught the exception and logs are printing out the 'Device disconnected', subsequent client send() still get processed. aka processMessage() is still getting called. 
I am not sure if this is a asynio issue or something else. I thought i am doing a simple standard server as recommended. 

Thanks for any help .

**Comment by aaugustin** [comment]
> once in a while i get this on the server logs.

This happens when the TCP connection dropped.

**Comment by aaugustin** [comment]
> i caught the exception and logs are printing out the 'Device disconnected', subsequent client send() still get processed. aka processMessage() is still getting called.

I don't understand this. After exiting the `try/except` block, there's no reason why `processMessage` would be called. This is a matter of how Python works; nothing to do with websockets.

However, if `processMessage` starts an asyncio task, it could still be running.

Furthermore, `websockets.close()` doesn't do what you expect because you forgot to await it. However, you don't need to call it, it's called automatically when `onConnect` returns.

**Comment by Postea-CS** [comment]
Thanks for the reply. 

> This happens when the TCP connection dropped.

I am more curious what could have happened. Client side still thinks its up and and happily sending messages. 

> I don't understand this. After exiting the try/except block, there's no reason why processMessage would be called. This is a matter of how Python works; nothing to do with websockets.

Same question i have. it seems the connection is still up and running. the client is still periodically sending messages and its getting thru even though the tcp connection is supposed to be dropped. And even though the function should have return, i still see printouts from processMessage()
I think its might be async for thing? Is websockets supposed to raise a StopAsyncIteration? 

>  However, if processMessage starts an asyncio task, it could still be running.

No processMessage is just process the message string and printout. 

> Furthermore, websockets.close() doesn't do what you expect because you forgot to await it. However, you don't need to call it, it's called automatically when onConnect returns.

My bad, i added that to see if that would help with the issue.

**Comment by aaugustin** [comment]
It's going to be hard for me to investigate further with the information you provided.

Perhaps there's a simple explanation - you had two clients running, one closed the connection, the other kept running?

If you can provide a complete example that exhibits the issue and that I can run, then I'll take a look.

**Comment by aaugustin** [comment]
I'm closing this issue because there isn't much I can do with the information you provided.

There might be a fault in websockets but I don't have enough evidence to make this a priority.
