### ISSUE TITLE
InvalidStateError in self._put_message_waiter.set_result(None)

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#634]
Full stack trace:

- https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/issues/18
- https://github.com/Rapptz/discord.py/issues/1996

This is likely to be a bug in websockets.

**Comment by bithon** [comment]
I have to investigate it, but i think to remember that the use of `from __future__ import print_function` and a coroutine leads to get blind on some errors happening in the code within the print_function. I moved away from that system but its already in my lib and the user with the issue is using it. It could might be a bug in the user code within the callback function but it doesnt get recognized and finally the async routine results in an invalid state. We are testing and i will report you as soon as we know something.

**Comment by aaugustin** [comment]
Thanks!

`_put_message_waiter` exists only for the situation where the queue of incoming messages is full. Then websockets stops receiving messages until `recv()` pops one from the queue.

When this happens, in `transfer_data_task`, websockets does:

```python
                        self._put_message_waiter = self.loop.create_future()
                        try:
                            await self._put_message_waiter
                        finally:
                            self._put_message_waiter = None
```

and when `recv()` is called, it does:

```python
        if self._put_message_waiter is not None:
            self._put_message_waiter.set_result(None)
            self._put_message_waiter = None
```

----

I suspect the scenario we're seeing is:

- `transfer_data_task` is cancelled, perhaps because the connection is closing
- since it's waiting on `_put_message_waiter`, `_put_message_waiter` gets cancelled as well
- `recv()` is called
- it attempts to set the result of `_put_message_waiter`, which produces `InvalidStateError`

Actually there are three possibilities if `_put_message_waiter` isn't pending; it may be:

- cancelled: that's my theory above
- done with a result: I don't think this is possible, considering how `set_result` is wrapped in `if self._put_message_waiter is not None: ...; self._put_message_waiter = None` structure
- done with an exception: I don't think this is possible, because there's no call to `set_exception`.

Cancellation is the bane of my life as a maintainer of this library...

----

It turns out that `_pop_message_waiter`, which follows exactly the same pattern, defends against this issue (see the comment):

```python
            self._pop_message_waiter = pop_message_waiter
            try:
                # If asyncio.wait() is canceled, it doesn't cancel
                # pop_message_waiter and self.transfer_data_task.
                await asyncio.wait(
                    [pop_message_waiter, self.transfer_data_task],
                    loop=self.loop,
                    return_when=asyncio.FIRST_COMPLETED,
                )
            finally:
                self._pop_message_waiter = None
```

----

The fix should be as simple as:

```diff
﻿﻿diff --git a/src/websockets/protocol.py b/src/websockets/protocol.py
index 43dcbd4..5161017 100644
--- a/src/websockets/protocol.py
+++ b/src/websockets/protocol.py
@@ -725,7 +725,7 @@ class WebSocketCommonProtocol(asyncio.StreamReaderProtocol):
                     while len(self.messages) >= self.max_queue:
                         self._put_message_waiter = self.loop.create_future()
                         try:
-                            await self._put_message_waiter
+                            await asyncio.shield(self._put_message_waiter)
                         finally:
                             self._put_message_waiter = None
 
```

The hard part is writing a test.

**Comment by lgrahl** [comment]
> Cancellation is the bane of my life as a maintainer of this library...

Tell me about it. Kind of reminds me of the woes of thread cancellation.

**Comment by bithon** [comment]
Its possible that we found the reason for this issue. Till now it happened latest after 20h of running, now it runs since ~50 hours.

We will report in latest in two weeks, if it happened again or not.

**Comment by bithon** [comment]
In our case it seems it was like i said, a bug within the user code of the print_function caused the problem
