### ISSUE TITLE
WebSocketProtocolError is no longer exposed

### ISSUE THREAD

**Issue by Harmon758** [aaugustin/websockets#649]
The changelog for 8.0 says:

>    **Version 8.0 renames the** ``WebSocketProtocolError`` **exception** to :exc:`ProtocolError` **.**
>
>    A ``WebSocketProtocolError`` alias provides backwards compatibility.

However, `WebSocketProtocolError` is no longer exposed:
```py
>>> import websockets
>>> websockets.WebSocketProtocolError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'websockets' has no attribute 'WebSocketProtocolError'
```
and this change breaks backwards compatibility.

**Comment by aaugustin** [comment]
Thanks, I'll make a bugfix release with this fix.
