### ISSUE TITLE
Websocket Server still running after close and wait_close coroutine calls

### ISSUE THREAD

**Issue by cotardp** [aaugustin/websockets#65]
Hello,

Here is the situation:
- I have a server running a websocket instance (works)
- I serve clients with a SSL websocket  (works)
- I want to perform, for any reason, a restart of the websocket server. In this case, Everything seem to work. The connection are closed etc.  but when I try to run again the server, asyncio complains the event loop is sill running.

My environment!:
Both Ubuntu 14.04 LTS and Debian 8.0 jessie
Python 3.4
websocket from pypi (last version in date)

The corresponding  reduced code:
```
class MyClass:
    def serve(self, interface, port):
        self.loop = asyncio.get_event_loop()
        if self.loop.is_running():
            self.loop.stop()

        self.wsserver = websockets.serve(WebSocketHandler,
                                         interface,
                                         port,
                                         loop=self.loop)
        self.server = self.loop.run_until_complete(self.wsserver)
        self.loop.run_forever()

    def close(self):
        self.server.close()
        self.loop.run_until_complete(self.server.wait_closed())
        self.loop.stop()


if __name__ == '__main__':
	instance  = MyClass()
	instance.serve('0.0.0.0', 4444)

	//In my program, the following calls are made from a signal handler
	instance.close()
	instance.serve('0.0.0.0', 5555)
```
The last call gives the error
"Event loop is running"

I tried to stop() and close(), the loop, wait for loop to stop running. But nothing seems to work.
Any idea why I cannot restart the server?
Thank you

**Comment by aaugustin** [comment]
This issue appears to be related to `asyncio`, not to `websockets`. Are you using the [event loop methods to register sigal handlers](https://docs.python.org/3/library/asyncio-eventloop.html#unix-signals)?

**Comment by cotardp** [comment]
Yes I tried but with no success. I am not really comfortable with asyncio as it is the first time I use it.
Could you explain me how to stop your websocket server while loop.run_forever() is running ? It seems the close() and wait_closed() has no effect on the server.

**Comment by aaugustin** [comment]
Whatever works for stopping a server created with [asyncio.create_server()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.create_server) should work. (If not, then I'll consider it a bug in websockets.) I'm sorry, I can't offer more help: I never used asyncio with signals. Perhaps you could ask on the [python-tulip mailing-list](https://groups.google.com/forum/#!forum/python-tulip)?
