### ISSUE TITLE
How to Establish SSL connection with .jks

### ISSUE THREAD

**Issue by gityou123** [aaugustin/websockets#654]
I have a server that uses .jks for SSL connections.  I have tried your basic example but cannot figure out how to convert the .jks to a .PEMS.  I've tried converting (using Pyjks) the .jks to OpenSSL Context, but that is different than SSLContext in your example.  Any guidance would be appreciated.

**Comment by lgrahl** [comment]
Completely untested but DuckDuckGo-ing for *convert jks to pem* brought up this: https://stackoverflow.com/questions/652916/converting-a-java-keystore-into-pem-format

Hope it helps. Other than that: Sorry but the question is really not related to this library. :woman_shrugging:
