### ISSUE TITLE
websocket compile error on IOS 8

### ISSUE THREAD

**Issue by nianxuejie** [aaugustin/websockets#656]
static __thread char buf[INET6_ADDRSTRLEN];

error：
websocket/Socket.cpp:15:12: error: thread-local storage is not supported for the current target
    static thread_local char buf[INET6_ADDRSTRLEN];
           ^

Who can give an alternative on ios？

**Comment by aaugustin** [comment]
I think you're reporting this to the wrong project. There's no Socket.cpp file in this project.
