### ISSUE TITLE
Interactive client appears to miss `__main__` file

### ISSUE THREAD

**Issue by Tmpod** [aaugustin/websockets#657]
Was scrolling through the documentation today and found out about the interactive client, however, when doing the exact command shown in the docs it failed due to package not havig the `__main__` file. 

I ran: `python3.7 -m websockets wss://echo.websocket.org/`
And got: `/usr/local/bin/python3.7: No module named websockets.__main__; 'websockets' is a package and cannot be directly executed`

I just checked the repo, and indeed you have the file, so I'm not sure what's going on here.

**Comment by aaugustin** [comment]
Are you using a sufficiently recent version of websockets?

I just checked the packages of the latest version (8.0.1) and the file is there.

**Comment by aaugustin** [comment]
Please reopen if you can reproduce on the latest version, thanks!
