### ISSUE TITLE
Unable to pass custom socket into websockets.serve()

### ISSUE THREAD

**Issue by michelneumann** [aaugustin/websockets#659]
When trying to pass a custom socket using the `sock` parameter of the `websockets.server.serve()` function, the assertion check at https://github.com/aaugustin/websockets/blob/master/src/websockets/server.py#L933 raises an exception because of the missing `port` parameter. However when setting the `port` parameter in the `serve()` function explicitly, an exception is raised saying it is not possible to specify a custom socket and and port. I was upgrading from version 7.0.0 to 8.0.1 where the error occurs. Thanks for looking into it.

**Comment by aaugustin** [comment]
Oops, that's a regression in 8.0.

**Comment by aaugustin** [comment]
Thanks for the report. I'll push a 8.0.2 with this fix to PyPi soon. (I'd just like to take a look at a couple other issues.)

**Comment by aaugustin** [comment]
8.0.2 is available on PyPI with this fix.
