### ISSUE TITLE
Get client addr (host and port) on server?

### ISSUE THREAD

**Issue by andreymal** [aaugustin/websockets#66]
I can't found this in documentation and source code. `client.host` and `client.port` [returns host and port of server](https://github.com/aaugustin/websockets/blob/master/websockets/server.py#L290). I'm inattentive or it is still not implemented?

If this is not implemented, then simplest solution — `self.transport = transport` in [connection_made](https://github.com/aaugustin/websockets/blob/master/websockets/server.py#L44). Then i can get host and port by [`client.transport.get_extra_info('peername')`](https://docs.python.org/3/library/asyncio-protocol.html#tcp-echo-server-protocol).

**Comment by aaugustin** [comment]
You're right: this feature isn't implemented at this time.

In terms of API, I'd rather avoid to expose the transport directly. WebSockets only exists over TCP or TCP + SSL, which restricts the variety of things of interest in `get_extra_info`.

**Comment by aaugustin** [comment]
I just added a public API to obtain this information.

(With the current version, you can call `client.writer.get_extra_info()`. However I wouldn't recommend that in the long run because `client.writer` isn't a public API.)

**Comment by aaugustin** [comment]
FYI I just released version 2.6 which includes this feature.
