### ISSUE TITLE
subprotocols malformed 

### ISSUE THREAD

**Issue by rsska** [aaugustin/websockets#666]
Very new to many things so I apologies if this is not a bug.  ( -but would greatly appreciate being pointed to some examples  using protocols, custom extension and custom headers on client and sever implementation).

On the client side when I try 
```
websockets.connect(uri,subprotocols=
websockets.headers.build_subprotocol(['One','Two']) 
)
```

The header received by the server look like:

> Sec-WebSocket-Version: 13
> Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
> Sec-WebSocket-Protocol: O, n, e, ,,  , T, w, o
> User-Agent: Python/3.7 websockets/8.0.2

**Comment by aaugustin** [comment]
Use `websockets.connect(uri,subprotocols=['One','Two'])`. `subprotocols` is documented to be a list of subprotocols.

This relates to a problem of the API docs: the low-level APIs should be more hidden.

**Comment by rsska** [comment]
- slightly off topic but how do I get the return custom headers?
websockets.connect(...,extra_headers=Client_Headers_Requests
    (Client_Header_Request is an  iterable of (name, value) pairs)
websockets.serve(....,extra_headers=SetUpHeaders)
    (SetUpHeader is a function retuning reading the Client headers and returning an iterable of (name, value) pairs set by the server for the client.)

... the question is what next - how to I retrieve the server response headers. Is it (async) possible in the websocket.connect  or (i assume should be) accessible from the websocket that is returned from the websockets.connect.  Any advice or examples would be greatly appreciated.
Thanks

**Comment by aaugustin** [comment]
> As soon as the HTTP request and response in the opening handshake are processed:
> - the request path is available in the `path` attribute;
> - the request and response HTTP headers are available in the `request_headers` and `response_headers` attributes, which are `Headers` instances.

Sorry, this is no super easy to find in the docs.

So:

```python
ws = await connect(...)
print(ws.response_headers)
```

If you need the subprotocol that was negociated:

```python
ws = await connect(...)
print(ws.subprotocol)
```
