### ISSUE TITLE
websockets.exceptions.PayloadTooBig: payload length exceeds size limit

### ISSUE THREAD

**Issue by CoderMudy** [aaugustin/websockets#668]
how can  i make max_zise bigger.or else way solve this
when the file size < 1M it's ok,but when it > 1 M it's wrong
i write server by go and client with python

**Comment by aaugustin** [comment]
Search for `max_size` in the API documentation.

**Comment by aaugustin** [comment]
in short: `connect(..., max_size=1_000_000_000)`

**Comment by 99991** [comment]
And for server, set `max_size` in bytes in `serve(..., max_size=2**28):`

```python
import asyncio
from websockets.server import serve

async def main():
    async with serve(echo, "localhost", 8765, max_size=2**28):
        await asyncio.get_running_loop().create_future()

async def echo(websocket):
    async for message in websocket:
        await websocket.send(message)

asyncio.run(main())
```

In JavaScript, you can also directly send `Uint8Array` with `ws.send(array)`, which is smaller than base64 encoding. If you do not need low latency, you can also consider compressing your data.
