### ISSUE TITLE
asyncio.CancelledError replaced with InvalidMessage

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [aaugustin/websockets#672]
In the snippet below, there is a try except block that catches all exceptions, including a `asyncio.CancelledError` if the task is cancelled. This exception should be reraised so that parent tasks also know about the cancellation.

https://github.com/aaugustin/websockets/blob/46ddc64b3ab02f38579880a812b9c04da6d89ae1/src/websockets/client.py#L101-L104

At least I suggest adding the following snippet:
```python
except asyncio.CancelledError:
    raise
```

**Comment by aaugustin** [comment]
Yes, the exception catching and re-raising is too broad there.

What issue does this cause in practice?

I suspect there are several other instances of the same issue in websockets.

**Comment by LasseBlaauwbroek** [comment]
In practice, if I have a task using websockets that gets cancelled within while this code snippet is running, the task continues. This is because in my code I will only terminate a task when I get a CancelledError, not any other error. In that case my task just tries again or does something else.

**Comment by aaugustin** [comment]
The patch should be:

```diff
diff --git a/src/websockets/client.py b/src/websockets/client.py
index eb58f9f..7f8d31d 100644
--- a/src/websockets/client.py
+++ b/src/websockets/client.py
@@ -99,6 +99,8 @@ class WebSocketClientProtocol(WebSocketCommonProtocol):
         """
         try:
             status_code, reason, headers = await read_response(self.reader)
+        except asyncio.CancelledError:
+            raise
         except Exception as exc:
             raise InvalidMessage("did not receive a valid HTTP response") from exc

diff --git a/src/websockets/server.py b/src/websockets/server.py
index 4f5e9e0..24306d2 100644
--- a/src/websockets/server.py
+++ b/src/websockets/server.py
@@ -133,6 +133,8 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
                     available_subprotocols=self.available_subprotocols,
                     extra_headers=self.extra_headers,
                 )
+            except asyncio.CancelledError:
+                raise
             except ConnectionError:
                 logger.debug("Connection error in opening handshake", exc_info=True)
                 raise
@@ -231,6 +233,8 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
         """
         try:
             path, headers = await read_request(self.reader)
+        except asyncio.CancelledError:
+            raise
         except Exception as exc:
             raise InvalidMessage("did not receive a valid HTTP request") from exc

```

It's quite annoying to write a test for this in the current test suite :-(

**Comment by LasseBlaauwbroek** [comment]
Looks good to me!
