### ISSUE TITLE
pong responses are TCP fragmented; is this a bug?

### ISSUE THREAD

**Issue by NelsonMinar** [aaugustin/websockets#68]
I'm having trouble staying connected to a websocket using websockets 2.5 in python 3.4 on an Ubuntu 14.04 system. Bottom line, it looks like the automatic pongs sent by the Python client get TCP fragmented, sent in two packets. I'm guessing the server isn't handling that and dropping my client because it thinks it's dead. Does this sound plausible? If so, is it something the client library could change?

The websocket in question can be found [on this page](http://watch.na.lolesports.com/en_US#/popout). Unfortunately the websocket URL requires a JWT that expires, so I can't link the socket endpoint directly, but FWIW the host is livestats.proxy.lolesports.com. If I connect to the websocket with the Python library it works fine for 90 seconds until my connection is dropped by the server. But a Javascript page in Chrome stays connected fine for an hour+ at a time.

I looked with Wireshark and discovered the server is sending a ping to the client every 45 seconds. Chrome sends a single packet back as a masked pong response and the server seems happy. The python library also sends a masked pong response back whose contents look correct. But I noticed in Wireshark that these pongs always are fragmented into two TCP packets; one for the mask data and one for the pong response itself (the string `hello`). I'm guessing the server doesn't understand that and decides to hang up on the client.

Does that analysis sound plausible? Am I right that the way websockets is coded, it sends pong packets as two fragments? Even if it's a bug in the server that it doesn't understand the fragmented pong, it might still be nice to have the python code avoid sending fragments both for efficiency and in case other servers have similar problems.

PS: thanks for your library, it's great!

**Comment by NelsonMinar** [comment]
I've put a sample pcap at http://somebits.com/~nelson/tmp/websockets-issue-68.pcap

The pong response fragments are packets 118 and 120. There's only one ping from the server (packet 116); I'm guessing the server decides to hang up rather than try a second ping.

**Comment by aaugustin** [comment]
The implementation of sending a frame currently looks like this:

    # Write the header
    # ... prepare header here ...
    writer(header.getvalue())

    # Write the data
    # ... prepare data here ...
    writer(data)

In hindsight it's obvious why frames are sent in multiple TCP frames but it didn't occur to me until you reported this issue.

I agree that the server you're connecting to is buggy :-) but that the problem is worth fixing for performance reasons.

**Comment by NelsonMinar** [comment]
Thanks for the response! I see [in the code](https://github.com/aaugustin/websockets/blob/master/websockets/framing.py#L125-L147) that it looks like the header is alway written separately from the data. That does seem a little inefficient. I'd prepare a pull request for you but I'm not confident enough in this level of programming to get it right. Glad to test a patch with Wireshark and/or this particular server if it helps you!

**Comment by aaugustin** [comment]
The change I just pushed should fix your problem. Let me know how it goes. Thanks!

**Comment by aaugustin** [comment]
FYI I just released version 2.6 which includes this bugfix.

**Comment by NelsonMinar** [comment]
Just tested with 2.6 and I can stay connected to that problem server now. Also tshark shows that pong packets aren't fragmented. Thanks for the fast fix!
