### ISSUE TITLE
Make a release with Python 3.8 compatibility

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#681]

**Comment by aaugustin** [comment]
Done - version 8.1 is on PyPI.

**Comment by aaugustin** [comment]
No wheels, though, because https://github.com/joerick/cibuildwheel/issues/170.

**Comment by michael-k** [comment]
FYI: cibuildwheel 1.0.0 is on PyPI and has support for Python 3.8.

Can you add cp38 wheels to PyPI?

- https://github.com/joerick/cibuildwheel#100 (Changelog)
- https://pypi.org/project/cibuildwheel/

**Comment by aaugustin** [comment]
I re-triggered the builds. Wheels are now available for all platforms.

Bonus: we got manylinux2010 wheels in the process.

For reasons unclear, the macOS wheel is `websockets-8.1-cp38-cp38-macosx_10_9_x86_64.whl` rather than `websockets-8.1-cp38-cp38m-macosx_10_6_intel.whl`, which I expected, assuming it followed the format of other macOS wheels. Probable not a problem.

**Comment by aaugustin** [comment]
Thanks for the heads up :-)
