### ISSUE TITLE
cibuildwheel is not running the test suite

### ISSUE THREAD

**Issue by jlaine** [aaugustin/websockets#683]
I noticed that the cibuildwheel run for Linux + Windows is not exercising the test suite:

Linux:

```
+ sh -c 'python3 -W default -m unittest'

~ /project

----------------------------------------------------------------------

Ran 0 tests in 0.000s
```

Windows:
```
+ python -W default -m unittest
Using default MSVC build environment for 64 bit architecture
Executing: python -W default -m unittest
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
```

**Comment by jlaine** [comment]
After some poking around I believe the `.appveyor.yml` needs to be amended with:

```
 CIBW_TEST_COMMAND: python -W default -m unittest discover -s {project}/tests
```

**Comment by aaugustin** [comment]
This might be an accident dating back to when I split src/ and tests/.

Or it might be something I decided in the past, because I don't care much about running tests with every built wheel.

No strong opinions there, happy to merge a PR if someone has an opinion :-)

**Comment by jlaine** [comment]
I'm now almost certain it is a result of splitting `src/` and `tests/`, I encountered the exact same thing for another package. I'll put together a PR.

**Comment by aaugustin** [comment]
I've been reconsidering this today as I moved the CI to GitHub actions. I don't think it's really necessary to run tests for each wheel, so I'm not going to try.
