### ISSUE TITLE
When would websocket.remote_address be None?

### ISSUE THREAD

**Issue by CaledoniaProject** [aaugustin/websockets#688]
I have a simple chat server, in onSocket method I cache the websocket object for later use. At sometimes later, `websocket.remote_address` become None (The websocket object is still present, e.g `<websockets.server.WebSocketServerProtocol object at 0x7efcdcaefeb8`)

So when would this attribute be None?

**Comment by aaugustin** [comment]
Not 100% sure, but I think `remote_address` becomes `None` once the connection is closed. Is that what you're seeing?

If so, it's a documentation bug.

**Comment by CaledoniaProject** [comment]
Looks like that way. It became None when self.transport is None

**Comment by aaugustin** [comment]
I'd like to update the docstring to reflect this.
