### ISSUE TITLE
Handler for closed connections not allowed to finish

### ISSUE THREAD

**Issue by anderslundstedt** [aaugustin/websockets#69]
During shutdown I wait for clients to close connections. When this is done, the handler is not allowed to finish.

To trigger the error, run the following script, interrupt it (Ctrl+C) with a connection open, then close the connection.

    #!/usr/bin/env python
    
    import asyncio
    import logging
    import signal
    
    import websockets
    
    logging.getLogger().setLevel(logging.DEBUG)
    
    connectionClosedEvents = []
    
    @asyncio.coroutine
    def echo(websocket, path):
        print("Connection opened.")
        connectionClosedEvent = asyncio.Event()
        connectionClosedEvents.append(connectionClosedEvent)
        s = yield from websocket.recv()
        if s is not None:
            yield from websocket.send(s)
        print("Connection closed.")
        connectionClosedEvent.set()
    
    @asyncio.coroutine
    def shutdown():
        print("Shutdown initialized.")
        print("Waiting for open connections to close ...")
        for e in connectionClosedEvents:
            yield from e.wait()
        print("All connections closed.")
        echoServer.close()
        print("Waiting for server to close ...")
        yield from echoServer.wait_closed()
        print("Server closed.")
        print("Stopping event loop ...")
        eventLoop.stop()
        print("Event loop stopped.")
        print("Shutdown complete.")
    
    eventLoop = asyncio.get_event_loop()
    eventLoop.add_signal_handler(signal.SIGINT, asyncio.async, shutdown())
    echoServer =\
        eventLoop.run_until_complete(websockets.serve(echo, "0.0.0.0", 8765))
    eventLoop.run_forever()

Typical output:

    Connection opened.
    ^CShutdown initialized.
    Waiting for open connections to close ...
    Connection closed.
    All connections closed.
    Waiting for server to close ...
    Server closed.
    Stopping event loop ...
    Event loop stopped.
    Shutdown complete.
    Task was destroyed but it is pending!
    task: <Task pending coro=<handler() running at /tmp/tmp.OhmZJ4uKUJ/venv/lib/python3.4/site-packages/websockets/server.py:77> wait_for=<Future finished result=None>>

The reason for the error is that `websockets.server.connection_lost` removes the connection from `self.websockets`. Thus in `websockets.server.wait_closed` the connection is not waited for:

                yield from asyncio.wait(
                    [ws.handler_task for ws in self.websockets], loop=self.loop)

I will submit a proposed fix for this shortly.

**Comment by aaugustin** [comment]
Indeed.

The correct fix is most likely to remove the connection from `self.websockets` as the last step of the `handler_task`.

**Comment by aaugustin** [comment]
Can you test if the following patch resolves your problem?

```diff
diff --git a/websockets/server.py b/websockets/server.py
index 94135d1..5adf4ae 100644
--- a/websockets/server.py
+++ b/websockets/server.py
@@ -48,6 +48,8 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
     def handler(self):
         # Since this method doesn't have a caller able to handle exceptions,
         # it attemps to log relevant ones and close the connection properly.
+
+        self.ws_server.register(self)
         try:
 
             try:
@@ -86,6 +88,9 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
             except Exception:                               # pragma: no cover
                 pass
 
+        finally:
+            self.ws_server.unregister(self)
+
     @asyncio.coroutine
     def handshake(self, origins=None, subprotocols=None, extra_headers=None):
         """
@@ -170,14 +175,6 @@ class WebSocketServerProtocol(WebSocketCommonProtocol):
         priority = lambda p: client_protos.index(p) + server_protos.index(p)
         return sorted(common_protos, key=priority)[0]
 
-    def client_connected(self, reader, writer):
-        super().client_connected(reader, writer)
-        self.ws_server.register(self)
-
-    def connection_lost(self, exc):
-        self.ws_server.unregister(self)
-        super().connection_lost(exc)
-
 
 class WebSocketServer(asyncio.AbstractServer):
     """
```

**Comment by anderslundstedt** [comment]
It does.

**Comment by aaugustin** [comment]
Great. Thank you!

I'm pretty sure that the patch above is correct as far as connection termination is concerned.

I suspect it still has a race condition in connection establishement. Perhaps `self.ws_server.register(self)` must be moved before the creation of the handler task. I'll investigate that before resolving this issue.
