### ISSUE TITLE
Is there schema requirement for redirection URL ?

### ISSUE THREAD

**Issue by anthrax-0** [aaugustin/websockets#691]
We are using websockets to connect to some third-party server and sometimes we get redirects from it.
 It seems there is an ambiguity in the RFC about redirects. If the server redirects using 3xx response with HTTP(S) schema in URL returned - what is the best behaviour?
 Given that https://tools.ietf.org/html/rfc6455#section-4.2.1 also says that opening handshake can have "Request-URI" that can be an absolute HTTP/HTTPS URI, I'm not sure if current behaviour of raising InvalidURI exception without configurable handling on it is the best choice?
 Is there some best practice on it?

**Comment by aaugustin** [comment]
If I understand correctly, you're suggesting to accept both ws/wss and http/https URLs at least in redirect URIs (and perhaps in initial URIs for consistency). Is that correct? Perhaps we could do this with a warning.

AFAIK many WebSocket servers don't even handle redirects. We're far from having developed best practices in the WebSocket ecosystem. If you'd like to benchmark what other software does, that would be interesting.

**Comment by aaugustin** [comment]
I looked at the RFC again today and I really don't understand what the sentence mentioning "absolute HTTP/HTTPS URI" refers to.

On one hand, rewriting http/https to ws/wss is unlikely to create a lot of harm. At worst the connection will end up on a HTTP endpoint and fail to establish.

On the other hand, changing the protocol is a really uncomfortable thing to do. I'm willing to call this a server bug, unless someone can demonstrate that this is widespread and legitimate behavior. Until then, I'd rather not make changes.
