### ISSUE TITLE
OSError: [Errno 10048] error while attempting to bind on address (address, port)

### ISSUE THREAD

**Issue by sangensong** [aaugustin/websockets#693]
I attemp to open two server with a (address, port) pair, the one for send message, the other one for recv message. Can you provide a solutions. Thanks

**Comment by aaugustin** [comment]
(In general) you can't have two TCP/IP servers listening on the same ports.

You're facing this problem with websockets but it would be the same with any other server software.

You should either use the same server for sending and receiving messages (likely the best solution) or use different ports for the two servers (likely not the best solution).
