### ISSUE TITLE
Happy Eyeballs connection with websocket?

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#695]
Hi! Is there a way to use a Happy Eyeballs connection when doing the websocket connection?
i see one implementation in asyncio https://bugs.python.org/issue33530 but it seems is python 3.8 only (and i have to maintain 3.6 compatibility)
Also i see as a separate package https://pypi.org/project/async-stagger/
but the async.create_* should be replaced with the async_stagger.create_connection()
Is there a way and are developers interested to make websockets use async_stagger.create_connection() if the module is found?
Thank you!!

**Comment by aaugustin** [comment]
I don't want to maintain this. There's too much complexity in this area already and it gets in the way of my long-term goals.

My recommendation is to use a version of asyncio that implements happy eyeballs, or to connect the socket yourself then pass it to the `connect`.

**Comment by adriansev** [comment]
Thanks for info! i see in the client code [here](https://github.com/aaugustin/websockets/blob/master/src/websockets/client.py#L465) that i can pass a socket to connect, but from function signature is not clear to me how to do it ... is it something like   
```
mysocket = await async_stagger.create_connected_sock(myhost, myport)
connect(sock=mysocket, path=mypath, ssl=mycontext)
``` ?
Thank you!

**Comment by aaugustin** [comment]
Yes, that should work.

`websockets` is simply passing the argument to `create_connection` (https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection).p

**Comment by adriansev** [comment]
it would seem that `connect` with `sock=` and `path=` have some issues :   
if i do not give the first argument (uri) and just do `await websockets.connect(sock=socket, path=path, ssl=ctx,` i get `__init__() missing 1 required positional argument: 'uri'`   
if i use uri, i get `you have to pass server_hostname when using ssl` in create_unix_connection   
if i remove path, i get `you must set server_hostname when using ssl without a host`
It would seem that uri is not swappable with explicit host,port,path variables and sock cannot replace host,port .. did i miss anything? Thanks a lot!

**Comment by adriansev** [comment]
In the connect part, maybe instead of `if path is None` , should be `if uri is None` ?

**Comment by aaugustin** [comment]
`connect` doesn't accept a `path` argument (well, technically, it does, but that's just an implementation detail for `unix_connect`, not a [documented API](https://websockets.readthedocs.io/en/stable/api.html#websockets.client.connect)).

I expect `connect(uri, sock=...)` or maybe `connect(uri, sock=..., server_hostname=...)` to do the job. However, I never tested it. Let me know how it goes.

**Comment by adriansev** [comment]
yes, `connect(uri, sock=..., server_hostname=...)` is required (without server_hostname i have `You must set server_hostname when using ssl without a host`) .. also i did this :   
`websockets.connect(fHostWSUrl, sock=socket, server_hostname=socket.getpeername()[0],`
I was wondering if the websocket.connect can be made to take host,port from sock if present (and not require uri), know that is wss from existence of ssl and use path for remote endpoint, to have an alternative signature as `connect(sock=, path=, ssl=)`

**Comment by aaugustin** [comment]
There was a discussion about whether or not to infer `server_hostname` automatically from `uri` when passing a `sock` argument. I'll check what why we decided not to do it.

**Comment by twisteroidambassador** [comment]
> I was wondering if the websocket.connect can be made to take host,port from sock if present (and not require uri)

This is probably not a good idea, because with `async_stagger` each socket object only "knows" one IP address among all addresses resolved from the host name, and you want the initial host name for `server_hostname`. Just parse the `uri` with `urllib.parse.urlparse` and take the hostname, like here https://github.com/aaugustin/websockets/blob/910f417c9179150c5ab4b44c7361dbf1e51ec322/src/websockets/uri.py#L59

(I am the author of `async_stagger`.)

**Comment by adriansev** [comment]
@twisteroidambassador Thanks a lot for info and help! Also for your work!! (to both present authors :) ) :) but, i apologize, but i do not understand where is the issue and why i need the server_hostname to be the connection fqdn. In my case the uri is built by combination of fqdn, port and path and while i could just use the fqdn host that i have i am not sure that is correct as the fqdn is an alias to multiple ipv4 and ipv6 addresses on multiple machines (each with different host certificate). I would think that if the server_name is a ssl requirements then is linked to the actual connection endpoint. So far i do [this](https://github.com/adriansev/jalien_py/blob/master/xjalienfs/alien.py#L948) and my complaint/suggestions comes from pure laziness because i construct an uri just to pass it to websocket when the information seems already to be there by the socket. What do i miss? (i am beginner with python so i might miss a lot of obvious things). Thank you!

**Comment by twisteroidambassador** [comment]
`server_hostname` is in fact not linked to the *actual* connection endpoint, but the *intended* destination. The point of SSL/TLS hostname verification is to make sure you are connecting to where you *intend* to connect to. When you instruct your browser to visit `http://www.google.com`, your browser resolves that hostname using DNS, connect to one of the resolved addresses, and verifies that the endpoint it connects to can cryptographically prove itself to be `www.google.com`. It makes no sense to ask the endpoint to prove itself to be `66.220.147.47`.

> the fqdn is an alias to multiple ipv4 and ipv6 addresses on multiple machines (each with different host certificate).
In this configuration, the standard way to do TLS demands that each machine's certificate should:
* either use the FQDN as its Common Name, if it does not use the Subject Alternative Name field
* or include the FQDN in the Subject Alternative Name field
And you should use the FQDN, not the endpoint's IP address, for SSL/TLS hostname verification.

Your current way is not the standard way to do TLS. It makes your setup vulnerable to DNS hijacking, which standard TLS will protect against.

**Comment by adriansev** [comment]
ok, thanks a lot! then i will use the server name as fqdn and yes, the server use it's FQDN in SAN field.. 
now, the question towards @aaugustin remains (a little bit changed), if it would make sense/be useful to have a signature for websocket connect with (host, port, path) instead of uri (i see that internal this is what is used, so i would see this as native signature). Thank you!

**Comment by aaugustin** [comment]
> now, the question towards @aaugustin remains (a little bit changed), if it would make sense/be useful to have a signature for websocket connect with (host, port, path) instead of uri (i see that internal this is what is used, so i would see this as native signature). Thank you!

In this situation, just use `connect(f"wss://{host}:{port}{path}")`.

This serializes and re-parses the URL, which is a waste of computing power, but I don't think it matters much compared to opening a network connection.

I care a lot of keeping the API clean and simple, because that's how the documentation stays clear and accessible and also how I can provide good error messages for incorrect inputs.

**Comment by adriansev** [comment]
thanks a lot, i forgot about f-strings.. Happy New Year and thanks a lot for all your work!!
