### ISSUE TITLE
Persistent Connections

### ISSUE THREAD

**Issue by Trogious** [aaugustin/websockets#696]
Please add support for persistent connections on the server side, such that the server does not close the connection after client request is handled (see [here](https://github.com/aaugustin/websockets/blob/910f417c9179150c5ab4b44c7361dbf1e51ec322/src/websockets/server.py#L201)). This decreases the volume of necessary TCP traffic for long lived connections and allows push type communication to the client.

**Comment by aaugustin** [comment]
I'm afraid you're confused. There's no concept of "handling a client request" in websockets.

Maybe the first question in the FAQ will help: https://websockets.readthedocs.io/en/stable/faq.html
