### ISSUE TITLE
async with websockets.connect(uri) as ws:写在循环外部！30秒左右就断开连接，报1006错误！

### ISSUE THREAD

**Issue by yazhoushi** [aaugustin/websockets#697]
```
async def get_res():
    uri = "wss://ws.cs.ws/v3/"
    async with websockets.connect(uri) as ws:
        i = 0
        while 1:
            st = time.time()
            # async with websockets.connect(uri) as websocket:
            await asyncio.sleep(1)
            req = {"id": random.randint(0, 99999),}
            await ws.send(json.dumps(req))
            res = await ws.recv()
            print(json.loads(res))
            i = i+1
            print('time：',i,time.time()-st)
```

我就想这个ws一直是连接的状态！为什么30秒左右就断开了！async with websockets.connect(uri) as ws在循环内部,那么每一次循环都会建立一个ws

**Comment by aaugustin** [comment]
Google Translate:

> Written outside the loop! Disconnected in about 30 seconds, reported 1006 error
> I think this ws is always connected! Why did it disconnect in about 30 seconds!
----

This item in the FAQ may answer your question: https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean

Specifically:

> HTTP load balancers or proxies that aren’t configured for long-lived connections may terminate connections after a short amount of time, usually 30 seconds.

Google Translate:

> 未为长时间连接配置的HTTP负载平衡器或代理可能会在短时间（通常为30秒）后终止连接。

**Comment by yazhoushi** [comment]
要怎么解决？客户端的

**Comment by aaugustin** [comment]
> How to solve it? Client-side

If you're using a proxy (which is the most common cause for this problem), you need to ask the people managing the proxy if they can configure it to support long lived connections.

**Comment by yazhoushi** [comment]
不是使用代理服务器的！我用其它的库(websocket-client)测试，连接是一直保持连接的状态，只要ws.send()就可以了！但是使用websockets库的时候，30秒就断开！看之前问题是说:未为长时间连接配置的HTTP负载平衡器。这个”配置的HTTP负载平衡器“这么配置？就我上面的代码！加什么代码可以一直保持一直连接的状态？我只要一直send就行达到订阅！

**Comment by yazhoushi** [comment]
ws.ping()没有参数时间！只有data！而且我测试的时候,在循环里面加了await ws.ping()！不管用！不知道我是不是加错地方了，还是用法不对？请指教一下

**Comment by ZZ-110** [comment]
> ws.ping()没有参数时间！只有data！而且我测试的时候,在循环里面加了await ws.ping()！不管用！不知道我是不是加错地方了，还是用法不对？请指教一下

I have met sth like this. Have a try like this:
`websockets.connect(uri, ping_interval=None)`
