### ISSUE TITLE
How to send and receive messages at the same time on server

### ISSUE THREAD

**Issue by YayuanZhang** [aaugustin/websockets#698]
Hi, I want to implement a function which can  send and receive messages to a client in one connection at  the same time on server. However, in the the ' while True' loop of the recv logic, the 'websocket.recv()' in fact blocks the loop.

```
async def echo(websocket, path):
    while True:
        recv_text=await websocket.recv()
      #I don't know how to add the send logic here 
      #bcause I don't know how to how to make the websocket.recv() none-blocking

asyncio.get_event_loop().run_until_complete(
    websockets.serve(echo, 'localhost', 8765))
asyncio.get_event_loop().run_forever()

```

I tried some ways to solve the question, using multiple tasks, threadings but all failed.
Finally it comes out as follows

```
async def echo(websocket, path):
    while True:
        try:
            recv_text=await asyncio.wait_for(websocket.recv(), timeout=0)
        except (asyncio.TimeoutError, ConnectionRefusedError):
            print('timeout')
        websocket.send('some other messages')

asyncio.get_event_loop().run_until_complete(
    websockets.serve(echo, 'localhost', 8765))
asyncio.get_event_loop().run_forever()
```

It works. However,  I'm confused why it works.  Is there a more elegant way to realize the function? Hope I made myself clear.

**Comment by aaugustin** [comment]
The "getting started" documentation covers this use case: https://websockets.readthedocs.io/en/stable/intro.html#both

**Comment by Time0o** [comment]
@aaugustin That link is invalid now, does documentation for this still exist somewhere?

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/howto/patterns.html#consumer-and-producer
