### ISSUE TITLE
How to safely write async code that saves to a Django db?

### ISSUE THREAD

**Issue by kramer65** [aaugustin/websockets#701]
From a Django project I want to use this library to connect to an external websocket endpoint which will provide a constant data stream. Since the stream is rather high volume I would like to use an async way of doing this. In the Django Channels project [I read](https://channels.readthedocs.io/en/latest/tutorial/part_2.html) that

> any asynchronous consumer must be careful to avoid directly performing blocking operations, such as accessing a Django model.

On [this page](https://channels.readthedocs.io/en/latest/topics/databases.html) a way of saving models to the database in an async way is explained using the Django Channels `database_sync_to_async` method.

What is the way of doing this using this websockets lib?

Does anybody know of any example code showing how to save models async while keeping it thread safe?

**Comment by lgrahl** [comment]
I'm mildly confused by the description and thus don't know how your architecture looks like. However, this is more of an asyncio question and there are two things asyncio provides that should meet your requirements:

* Schedule a coroutine/task on the event loop from another thread: https://docs.python.org/3/library/asyncio-task.html#scheduling-from-other-threads https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading
* Run something that would block the event loop's thread in an executor (using a thread or process pool) within the event loop via https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

**Comment by aaugustin** [comment]
If I understand the title correctly, you want to connect with this library to a websocket endpoint, receive data, and write it with the Django ORM.

Use `await asyncio.get_running_loop().run_in_executor(...)` for interacting with the Django ORM and you're good to go.
