### ISSUE TITLE
Portforwarding not working

### ISSUE THREAD

**Issue by infyDavis** [aaugustin/websockets#702]
I have the simple echo server running remotely and trying to portforward the websocket port to my local machine. I try to run the client locally to send and receive a message but I keep getting this error.

``OSError: [Errno 10049] Connect call failed ('0.0.0.0', 8765)```

I'm basically using the simple server and client scripts found in the readme.

If i run the same server and client script on the remote server, it works. just not when I try to portforward the port.

Is there anything I have to change about the server?

Here is the server code:

```
#!/usr/bin/env python

# WS server example

import asyncio
import websockets

async def hello(websocket, path):
    name = await websocket.recv()
    print(f"< {name}")

    greeting = f"Hello {name}!"

    await websocket.send(greeting)
    print(f"> {greeting}")

header = {'Access-Control-Allow-Origin' : '*'}
start_server = websockets.serve(hello, "0.0.0.0", 8765, extra_headers=header)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

```

And here is the client I'm using:
```
#!/usr/bin/env python

# WS client example

import asyncio
import websockets

async def hello():
    uri = "ws://0.0.0.0:8765"
    async with websockets.connect(uri) as websocket:
        #name = input("What's your name? ")
        name = 'Davis'

        await websocket.send(name)
        print(f"> {name}")

        greeting = await websocket.recv()
        print(f"< {greeting}")

asyncio.get_event_loop().run_until_complete(hello())

```

**Comment by aaugustin** [comment]
You can listen to 0.0.0.0 (that means any interface) but you cannot connect to 0.0.0.0.
