### ISSUE TITLE
Why does the client in this test setup disconnect after exactly 40 seconds

### ISSUE THREAD

**Issue by kramer65** [aaugustin/websockets#703]
I want to start using websockets for receiving a (fairly high volume) data stream. So I  set up a simple test setup as follows:

`server.py`:

```
import asyncio
import websockets
from time import sleep

async def hello(websocket, path):
    for i in range(10000):
        await websocket.send("xxxxxxxxxxxxxxxxxxx")
        print(i)
        sleep(1)

start_server = websockets.serve(hello, "localhost", 8181)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

`client.py`:

```
import asyncio
import websockets


async def consumer_handler():
    uri = "ws://localhost:8181"
    async with websockets.connect(uri) as websocket:
        counter = 1
        async for message in websocket:
            print(counter, message)
            counter += 1

asyncio.get_event_loop().run_until_complete(consumer_handler())
```

The weird thing is that after 40 seconds (40 messages) the client stops printing received messages while the server continues to print sent messages. And after another 20 seconds (by now the server is at message 60) both the client and the server stop with the following error:

    websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

- I tested whether it was because of the message size, by increasing the message size tenfold. But it still stops after 40 messages
- I then tested whether it was because of the number of messages, by speeding up the sent messages tenfold `sleep(0.1)`. When I do this, the client stops after message 398 (and always after exactly message 398). When I set `sleep(0.01)` it stops around 3825 (or 3822 or 3826 etc.)

I'm running this on Ubuntu 19.10 and also verified the same behaviour on MacOS.

Does anybody know why this stops after 40 seconds? Am I missing a setting somewhere?

**Comment by lgrahl** [comment]
This is a common issue when using load balancers or proxies. From the [FAQ](https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean)

> it means that the TCP connection was lost. As a consequence, the WebSocket connection was closed without receiving a close frame, which is abnormal.
> 
> You can catch and handle ConnectionClosed to prevent it from being logged.
> 
> There are several reasons why long-lived connections may be lost:
> 
> * End-user devices tend to lose network connectivity often and unpredictably because they can move out of wireless network coverage, get unplugged from a wired network, enter airplane mode, be put to sleep, etc.
> * HTTP load balancers or proxies that aren’t configured for long-lived connections may terminate connections after a short amount of time, usually 30 seconds.
> 
> If you’re facing a reproducible issue, enable debug logs to see when and how connections are closed.

But it is quite unusual when run against localhost.

**Comment by aaugustin** [comment]
You should really use `asyncio.sleep` instead of `time.sleep`. The `time.sleep` calls may block websockets internals here.

**Comment by loongWB** [comment]
you can set ping_interval and ping_timeout as None in websockets.server, like "websockets.serve(self.recv, '0.0.0.0', 8766, ping_interval=None, ping_timeout=None)"

**Comment by kramer65** [comment]
`await asyncio.sleep(1)` solved it. Thanks @aaugustin !

**Comment by aaugustin** [comment]
OK. `time.sleep()` was blocking the event loop; most likely this was preventing the code that handles pings and pongs from running, which eventually led to a timeout and connection termination.

**Comment by JETSdev** [comment]
> you can set ping_interval and ping_timeout as None in websockets.server, like "websockets.serve(self.recv, '0.0.0.0', 8766, ping_interval=None, ping_timeout=None)"

This works for me.
