### ISSUE TITLE
Unexpected results from websockets + wait_for timeout

### ISSUE THREAD

**Issue by kroitor** [aaugustin/websockets#704]
HI!

I have this script, the intent is to measure the time it takes to raise a connection timeout. With `aiohttp`'s ws implementation, the timeout works as expected – stopping at the specified time (5 seconds), precisely. With `websockets` the timeout is always 2x or 3x longer, regardless of which particular timeout setting i specify. For the testing purposes I'm running it against a dummy ws server @ localhost that just hangs all connections forever in the upgrade state, forcing clients to timeout.

```Python
from asyncio import get_event_loop, wait_for
from datetime import datetime
from websockets.client import connect
import aiohttp

def iso():
    return datetime.now().replace(microsecond=0).isoformat()

async def test():

    timeout = 5.0  # seconds

    print('------------------------------------------------------------------')

    session = aiohttp.ClientSession()
    print(iso(), 'aiohttp started')
    try:
        await wait_for(session.ws_connect('ws://127.0.0.1:8080'), timeout=timeout)
    except Exception as e:
        print(iso(), 'aiohttp', str(e))
    print(iso(),'aiohttp done')
    await session.close()

    print('------------------------------------------------------------------')

    print(iso(), 'websockets started')
    try:
        await wait_for(connect('ws://127.0.0.1:8080'), timeout=timeout)
    except Exception as e:
        print(iso(), 'websockets', str(e))
    print(iso(),'websockets done')

    print('------------------------------------------------------------------')

get_event_loop().run_until_complete(test())
```

Here's my results with websockets 7.0:

```
mbp:ccxt.pro igorkroitor$ uname -a
Darwin mbp.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
mbp:ccxt.pro igorkroitor$ python3 --version
Python 3.7.2
mbp:ccxt.pro igorkroitor$ pip3 list | grep websockets
websockets        7.0
mbp:ccxt.pro igorkroitor$ pip3 list | grep aiohttp
aiohttp           3.6.2
mbp:ccxt.pro igorkroitor$ python3 websockets_vs_aiohttp.py
------------------------------------------------------------------
2019-12-12T23:02:41 aiohttp started
2019-12-12T23:02:46 aiohttp
2019-12-12T23:02:46 aiohttp done
------------------------------------------------------------------
2019-12-12T23:02:46 websockets started
2019-12-12T23:03:01 websockets
2019-12-12T23:03:01 websockets done
------------------------------------------------------------------
```

↑ With websockets 7.0 the time is always 2x or 3x longer than with aiohttp, all the rest being equal. And my main question is *why?*

Also, it's worth noting that something has been broken in between `websockets` 7.0 and `websockets` 8.1 in that regard, so in 8.1 the exception seems to break the code somewhere inside the `websockets` implementation:

```
mbp:ccxt.pro igorkroitor$ pip3 list | grep websockets
websockets        8.1
mbp:ccxt.pro igorkroitor$ python3 websockets_vs_aiohttp.py
------------------------------------------------------------------
2019-12-12T23:08:35 aiohttp started
2019-12-12T23:08:40 aiohttp
2019-12-12T23:08:40 aiohttp done
------------------------------------------------------------------
2019-12-12T23:08:40 websockets started
2019-12-12T23:08:55 websockets
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py:596> exception=InvalidMessage('did not receive a valid HTTP response')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/http.py", line 213, in read_line
    line = await stream.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
2019-12-12T23:08:55 websockets done
------------------------------------------------------------------
```

- Can anyone shed some light on the above? 
- Mainly, why is the timeout always longer than expected (always 2x or 3x specifically)?
- How to handle the task exception deep inside the `websockets`' code ?

**Comment by aaugustin** [comment]
> Can anyone shed some light on the above?

Indeed, there's a series of timeouts happening in sequence. Per the docs:

> The close_timeout parameter defines a maximum wait time in seconds for completing the closing handshake and terminating the TCP connection. close() completes in at most 4 * close_timeout on the server side and 5 * close_timeout on the client side.

----

> Mainly, why is the timeout always longer than expected (always 2x or 3x specifically)?

Shutdown can hang at several layers / steps. Unlike aiohttp, websockets doesn't return until the connection is actually closed.

I could divide the timeout value you provide by 4 or 5 respectively; then you'd ask why the connection times out in 50% or 60% of the value you provided respectively.

This isn't a big issue for most people because no one really cares about the exact shutdown delay, as long as nothing hangs or leaks.

----

> How to handle the task exception deep inside the websockets' code ?

Probably websockets should take take care of this for you. Let's look at this.

**Comment by kroitor** [comment]
Thx for your answer @aaugustin !

> I could divide the timeout value you provide by 4 or 5 respectively; then you'd ask why the connection times out in 50% or 60% of the value you provided respectively.

As far as I understand, dividing or multiplying the specified timestamp isn't the best approach for a _"timeout-while-connecting"_ case. Instead, it is expected to timeout at the exact specified time if the handshake is not done by that time. And if the handshake isn't over yet, then expecting a graceful shutdown sequence is most likely meaningless. At least, this is what the caller of `wait_for` would expect when a timeout is specified from any generic awaitable thing – because in the async-sense `wait_for` should raise an exception when the time is out, not too early, but also not too late (regardless of how many internals layers or steps are involved). In my mind, the connection timeout should limit the entire attempt, including the closing sequence. But I do understand the decisions behind the current design, though, thx for clarifying this!

> This isn't a big issue for most people because no one really cares about the exact shutdown delay, as long as nothing hangs or leaks.

On one hand yes – when everything works smoothly, the bug goes unnoticed. However, i'm trying to implement a robust logic that will not crash in real life when something does not go right. In my case the user can have a set up of 20-40 simultaneous connections that aren't always stable since they work "in the wild", if you know what I mean (bad connectivity, abrupt disconnects, etc). Say, I'm implementing a reconnect-on-timeout logic and I want a swift reconnection, if a previous connection could not be established within a limited time. But if the previous attempt does not raise at specified time – then the code has to wait and potentially lose (whatever it is). I can probably  work around this issue by wrapping it in a userland class that will `race([ timeout, connect ])` and will spawn a new connection while the previous one is still shutting down in the background if the timeout fires first. Having a wrapper class is much less convenient from the user's perspective, though. But anyways, thx again!

**Comment by aaugustin** [comment]
Perhaps one day websockets will have a trio implementation, then we can have nice timeouts.

It believe #574 covers any action that may result from this discussion so I'm going to close it!

PS - I reviewed the stack trace above and it makes sense: wait_for times out and cancels the coroutine, which results in `CancelledError`,  which websockets translates into `InvalidMessage` with a fairly clear error.
