### ISSUE TITLE
Port sharing: Bad Gateway: /health/

### ISSUE THREAD

**Issue by enp** [aaugustin/websockets#705]
Hi,
Tried to use example of port sharing  from  https://websockets.readthedocs.io/en/stable/deployment.html#port-sharing as is, but received:

```
$ curl http://127.0.0.1:8765/health/
Bad Gateway: /health/
```

Can you fix please or advice something?

**Comment by aaugustin** [comment]
Try `curl -v http://127.0.0.1:8765/health/` to get more info.

**Comment by enp** [comment]
Sorry, it was proxy issue and I found it with -v key, thank you :)
