### ISSUE TITLE
Object oriented Websocket Client and Server example

### ISSUE THREAD

**Issue by pravindamodaran** [aaugustin/websockets#708]
I'm trying to implement object oriented Websocket client and server. Since `websockets` is completely coroutine based, I'm finding it difficult to go ahead with implementation. Is it possible to wrap it around classes? Are there any examples of using it in this way?

**Comment by lgrahl** [comment]
websockets is actually quite object-oriented, so I'm not sure what you're asking for. Of course you can wrap it in a class.

**Comment by Francwa** [comment]
The man obviously want a more detailed example than what's provided in the documentation.
If you've never used asyncio and you want to do something a little bit more complex than a "Hello world", you won't get far.

**Comment by lgrahl** [comment]
Then, what's missing from my example?

**Comment by pravindamodaran** [comment]
> The man obviously want a more detailed example than what's provided in the documentation.
> If you've never used asyncio and you want to do something a little bit more complex than a "Hello world", you won't get far.

Yeah, you're right. I've just started with asyncio and wanted to leverage an object oriented approach to websockets using asyncio. Currently we are using zmq sockets (pyzmq library) and since its synchronous, its easy in this case. 

Basically I have a parent class `Endpoint` and 2 child classes - `Client` and `Server`. Endpoint will common methods, while the child classes will have specific ones.  

Wanted to try out similarly for websockets, but stuck due to my inexperience in using asyncio.

**Comment by aaugustin** [comment]
I'm going to flag this as a documentation issue for now, but it's unclear to me what a documentation would look like. If you'd like to work on a patch, let's talk before you put too much time into it.

**Comment by aaugustin** [comment]
I'm still unclear on the scope of this issue. I'd rather avoid including too much asyncio tutorial in the websockets docs. Closing for now but willing to consider a concrete proposal in this area.

**Comment by toby-j** [comment]
Found this myself. Would be great to have an OO example
