### ISSUE TITLE
version 8.1 wheel for arm

### ISSUE THREAD

**Issue by transfluxus** [aaugustin/websockets#711]
Hi,
I just tried to install the recent version on a raspberry pi but for version 8.1 there is no arm wheel. Will that be available at some point?

Merry Xmas! :)

**Comment by aaugustin** [comment]
I'm sorry, this is unlikely to happen unless cibuildwheel supports ARM, and I'm not seeing any effort in this directory.

Installing from source should work fine, though, and you have plenty enough power on a Raspberry Pi to compile the C extension if you need it.
