### ISSUE TITLE
Unable to fetch response headers when handshake is failed with InvalidStatusCode

### ISSUE THREAD

**Issue by droserasprout** [aaugustin/websockets#712]
Hi!

I'm trying to connect a server behind Cloudflare proxy. Proxy rejects connection with the following message:
```
client < Headers([('Date', 'Mon, 23 Dec 2019 14:01:18 GMT'), ('Content-Type', 'application/json'), ('Transfer-Encoding', 'chunked'), ('Connection', 'close'), ('Retry-After', '50'), [...]
```
I want to sleep 'Retry-After' seconds when processing HTTP 429 with the following code:
```
        connect = websockets.connect(self.host)
        while True:
            try:
                websocket = await connect
                ...
            except websockets.exceptions.InvalidStatusCode as e:
                if e.status_code != 429:
                    raise
                headers = connect.ws_client.response_headers
                retry_after = int(headers['Retry-After'])
```
But in case of failed handshake WebSocketClientProtocol object is getting destroyed in `Connect.__await_impl__`, so there's no way to get response headers. I've patched library to set `ws_client` attribute each time WebSocketClientProtocol is being created, but I suppose there's a better way. In case of someone is dealing with the same issue here's my monkeypatch:
```
def patch_websockets_connect():
    async def patched_create_connection(self):
        transport, protocol = await self._original_create_connection()
        self.ws_client = protocol
        return transport, protocol

    def getx(self):
        return partial(patched_create_connection, self)

    def setx(self, value):
        self._original_create_connection = value

    Connect._create_connection = property(getx, setx)
```

**Comment by aaugustin** [comment]
Indeed, I'm not seeing a very good way to handle this in websockets.

There's no client-side equivalent of `process_request` on the server side (which is where you'd handle this).

The best solution would be to add the response headers as an attribute of the `InvalidStatusCode` exception, wouldn't it?

**Comment by droserasprout** [comment]
I agree, attaching response headers to `InvalidStatusCode` seems to be the most appropriate. I'll try dig into this when I have some free time.
