### ISSUE TITLE
SSL package cannot be installed

### ISSUE THREAD

**Issue by warcayac** [aaugustin/websockets#714]
I'm using Python 3.8 on Ubuntu-WSL. I'm trying to install package SSL but it is not possible:

```
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('looking for', f)?
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```
This is 'cause SSL package is not updated to work with Python 3.* however in your tutorial, you are working with it, how is it possible?

Could you update your tutorial? or tell us, how did you get to install SSL package with Python 3.*? and what requirements  are needed (OS, etc.) for this packages can be installed?

Thanks in advance.

**Comment by RemiCardona** [comment]
What command gave you that output? Could you give more context?

As for the rest of your comment, `websockets` only works on python3 (3.6.1 and up), so I'm guessing you're confusing things.

**Comment by aaugustin** [comment]
The SSL package is part of Python's standard library. You don't need to install it. Just import it.
