### ISSUE TITLE
send() doesn't raise a exceptions.ConnectionClosed() like recv() does

### ISSUE THREAD

**Issue by MaartenUreel** [aaugustin/websockets#717]
We are building something that passes on events from an event system to a websocket.
Because events keep coming, we want to keep the websocket open for as long as possible, instead of opening/closing the connection for every event.

However, if we restart the server in between, it is not detected.

I tried something like this;
```python
# Send to websocket
try:
    await ws_connections[domain].send(raw_json_event)
except (websockets.exceptions.ConnectionClosed, KeyError) as ex:
logging.info(
    "Received ex of type %s, restart WebSocket connection", type(ex)
)

# (Re-)connect to websocket
uri = FS_ESL_WEBSOCKET_URI % ws_channel

ws_connections[domain] = await websockets.connect(uri)
logging.info("Created websocket connection to channel %s", uri)

# (Re-)send message
await ws_connections[domain].send(raw_json_event)
```

That doesn't do it. If I add recv() after every send():
```python
try:
    await ws_connections[domain].send(raw_json_event)
    await ws_connections[domain].recv()
except (websockets.exceptions.ConnectionClosed, KeyError) as ex:
``` 

Then the exception gets thrown. However that means that I'm receiving the event that I sent every time, while I don't need it. Wouldn't this cause needless overhead? Is there a more efficient way to handle this?

**Comment by aaugustin** [comment]
Your last paragraph suggests that the server sends messages to the client, perhaps to acknowledge every message it receives. Is that correct?

If you never read incoming messages, then incoming data piles up in your receive buffer, so websockets doesn't see the WebSocket close frame and/or the end of the TCP stream, so it doesn't close the connection.

If the server echoes every message and you can't disable that behavior, then you're going to receive messages and you have discard them. Calling `recv()` and ignoring the result is the only reasonable way to do that.

Either you alternate `send()` and `recv()` like you did, if you're confident that you're going to receive exactly one message for each message you send, or you can start another asyncio task that just does:

```python
async for _ in ws_connections[domain]:
    pass
```

**Comment by MaartenUreel** [comment]
Hello

the server sends the message to the clients, but not with the intent to acknowledge the receival.

The idea is that clients will connect to the WebSocket, and they receive all the events from our backend system. In order to do so, there is one client on the serverside (the above code) that sends events to the WS.

So something like:
```python
    async def websocket_receive(self, event):
        text = json.loads(event["text"])
        parsed_data = dict()
        parsed_data["Event-Name"] = text["Event-Name"]
        # more data parsing here

        await self.channel_layer.group_send(
            self.esl_ws_channel, {"type": "fs_message", "text": json.dumps(parsed_data)}
        )
```

So because of the above, the sending client also receives the message back.

Is this a good approach? Or would it be better to have the backend send to another channel, and that that consumer sends it to the right group?
