### ISSUE TITLE
Get socket or ssl_context from WebSocketClientProtocol?

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#721]
Hi! Is there a way to recover the socket or ssl_context from client WebSocketClientProtocol?
I would like to identify the client certificate used to make the connection but i have only the created websocket connection. I tried to look with inspect and list various object from within but no luck so far.
Thank you!

**Comment by RemiCardona** [comment]
It's a little convoluted but it's available. Something like this should help you:
```python
protocol = await websockets.connect(...)
ssl_obj = protocol.reader._transport.get_extra_info('ssl_object')
```
Hope that helps

**Comment by RemiCardona** [comment]
oh and
```python
socket = protocol.reader._transport.get_extra_info('socket')
```
to get the underlying `socket` object

**Comment by aaugustin** [comment]
Even easier:

```python
protocol.transport.get_extra_info('ssl_object')
protocol.transport.get_extra_info('socket')
```

That's a private API but in practice it gets the job done. The public API is writing a custom `WebSocketClientProtocol` subclass where you override the `connection_made(transport)` method to get access to the transport. This design is inherited from asyncio.
