### ISSUE TITLE
Can't get simultaneous messages

### ISSUE THREAD

**Issue by ehriq** [aaugustin/websockets#723]
Using the [interactive client](https://websockets.readthedocs.io/en/stable/intro.html#one-more-thing), I sent a message to a server, and then received two simultaneous messages, both messages are displayed correctly. 

But implementing my code, using:
```
async def get_data():
    async with websockets.connect(uri) as ws:        
        b = json.dumps({  
            "data": '1234'
        })        
        await ws.send(b)
        async for message in ws:
            print(message)

m = asyncio.get_event_loop().run_until_complete(get_data())
```
it only returns the last message. And I can't find a way to get the first message sent.

It's expected? How can I read the first message?

**Comment by aaugustin** [comment]
You can't really receive simultaneous messages on a WebSocket connection (or any TCP connection for that matter). One message will be read from the network before the other. So there's no reason why a message would be dropped.

You should [enable debug logs](https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging) to understand what's going on.

**Comment by ehriq** [comment]
The debug helped me to fix this. The issue was on the provider side. 
Thanks for the help.
