### ISSUE TITLE
Websocket server returns error 1011 but the version I'm using doesn't have docs for that error

### ISSUE THREAD

**Issue by CmdrNorthpaw** [aaugustin/websockets#725]
I'm using websockets to implement an asynchronous socket server for my program. Because the client end of this program doesn't run constantly (it connects to the server, uploads some data and then disconnects), I was getting the following error:

`websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1011 (unexpected error), no reason`

Now according to the docs error 1011 is caused when the server sends a ping to the client, doesn't receive a pong and errors out (which causes problems with my program as the client isn't constantly connected to the server). Although you can get around this by setting ping_timeout to None, when I did this more errors were thrown.

So I did some digging and I found that because I've been using discord.py in my program (which itself uses websockets), I was being restricted to v6.0 of the library instead of v8.2, which is the version the docs were written for. But when I looked in that version of the docs, there wasn't anything about error 1011 at all. And there's also seemingly no way to stop the ping from timing out (in this version of the library). So how can I stop the server from shutting itself down simply because nothing is connecting to it?

**Comment by aaugustin** [comment]
I don't understand "how can I stop the server from shutting itself down" — only the coroutine handling that connection should terminate, not the entire server.

If you don't care about `ConnectionClosed` exceptions, catch them, ignore them and move on.

**Comment by CmdrNorthpaw** [comment]
Oh, OK. My bad.

**Comment by aaugustin** [comment]
No problem :-)

Issues like this one are useful to determine which areas of the documentation need improving — when the same question comes up repeatedly.
