### ISSUE TITLE
How to listen to terminate signal on windows?

### ISSUE THREAD

**Issue by iLLiCiTiT** [aaugustin/websockets#726]
Question:
I would like to run websockets server or clinet on windows but there is not support to `add_signal_handler`. Is there way to terminate websockets loop on windows with handling `SIGTERM` or `SIGINT` when `run_forever()` is called? Didn't found that in documentation and none of my attempts worked, but I'm not experienced with async and coroutins much. Code snippet would be best (if it's possible).

**Comment by aaugustin** [comment]
This is really a question about `asyncio`, not about `websockets`. If you find a way to do it with plain `asyncio`, it'll work equally with `websockets`.

**Comment by aaugustin** [comment]
In the docs (https://websockets.readthedocs.io/en/stable/deployment.html#graceful-shutdown) I said:

> It’s more difficult to achieve the same effect on Windows. Some third-party projects try to help with this problem.

I saw at least one such project when I wrote this but I'm not finding it again.

See also https://bugs.python.org/issue23057

**Comment by iLLiCiTiT** [comment]
Ok, thanks for the quick response.
