### ISSUE TITLE
Send message to a single connected client from the server directly

### ISSUE THREAD

**Issue by JeremyVarghese** [aaugustin/websockets#727]
Is there any way of initiating a message to a connected client as opposed to replying to a message from a client? So far, from the examples, I have got a working program if the client starts the conversation. I need the exchange to start from the server side. How would one go about executing it?

**Comment by lgrahl** [comment]
https://github.com/aaugustin/websockets/blob/160dfbec7dd582c12817de5c85e6bf3fbbc34826/example/server.py#L9

Once this function is being called, the channel is open and you can start sending data (instead of receiving on that particular line).

**Comment by JeremyVarghese** [comment]
Thanks.
And how can one single out a client from multiple (for eg. 5) clients? and send a message to that one client?
Instead of sending it to all clients?

**Comment by lgrahl** [comment]
That is all application logic. You can for example store clients in a dict.
