### ISSUE TITLE
[Question] Websocket connection issue 

### ISSUE THREAD

**Issue by fbove** [aaugustin/websockets#728]
Connection is lost after getting this console error:
```
socket.send() raised exception.
```
And a disconnection on websocket server is being triggered, with code 1006.

#### Environment
Websocket server is a Django 2.2.5 with Django Channels 2.4.0 over Daphne.
Python websockets is being used only as a client. Other clients are connected using Javascript WebSocket w/o any issue.

#### Implementation
```python
from asyncio import get_event_loop
from asyncio.futures import TimeoutError as ConnectionTimeoutError
from json import dumps
from logging import getLogger

from websockets import connect as WSConnect

WS_URI = 'ws://application:8000/ws'

logger = getLogger(__name__)

class WS:
    def __init__(self, ws=None, key=None):
        self.ws = ws
        self.key = key

    @staticmethod
    def connect(key: str):
        async def _connect():
            ws = await WSConnect(f'{WS_URI}/notifications/?key={key}')
            await ws.send(dumps({
                'command': 'join',
                'room': key,
                'message': 'Engine Joining!'
            }))
            return WS(ws, key)
        try:
            return get_event_loop().run_until_complete(_connect())
        except ConnectionTimeoutError as ex:
            logger.error(
                f'Connection Timeout Error in WebSocket connect: {str(ex)}')
            return WS()
        except Exception as ex:
            logger.error(f'Error in WebSocket connect: {str(ex)}')
            return WS()

    def sendMsg(self, message=''):
        async def _sendMsg():
            return await self.ws.send(dumps({
                'command': 'send',
                'room': self.key,
                'type': 0,
                'message': message,
            }))
        try:
            if self.ws is None or self.ws.closed:
                logger.error('WebSocket client is not stablished.')
            return get_event_loop().run_until_complete(_sendMsg())
        except ConnectionTimeoutError as ex:
            logger.error(
                f'Connection Timeout Error in WebSocket sendMsg: {str(ex)}')
        except Exception as ex:
            logger.error(f'Error in WebSocket sendMsg: {str(ex)}')

ws = WS.connect(key=key)
ws.sendMsg('something')
```

Tried changing timeout and the connection prevails for a bit longer, but it eventually logs the console exception when trying to send something.
```python
WSConnect(
    f'{WS_URI}/notifications/?key={key}',
    ping_interval=5, ping_timeout=3
)
```

An issue that may be related is [socket.send() raised exception](https://github.com/aaugustin/websockets/issues/84), but I'm not really sure.

Also checked [What does ConnectionClosedError: code = 1006 mean?](https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean), but websocket server is not behind a proxy nor a load balancer. In my case it's a docker-compose stack on a local machine, so connection between containers is not an issue.

It may be related with keeping the connection alive when it is idle for more than 30-40 seconds?
How can this be solved? Isn't it handle internally by websockets library with ping pongs?

Thanks in advanced.

**Comment by lgrahl** [comment]
My guess is you're not running the event loop after you've sent the message (in the last line), so the connection just dies.

**Comment by fbove** [comment]
Hi @lgrahl, thanks for the quick response.

I'm using the [Object Oriented approach](https://github.com/aaugustin/websockets/issues/708) and trying to reuse a connection already created/instantiated.
`sendMsg` method is a wrapper for doing what you mentioned.

Do I have to re-connect every time I want to use the socket? What if as a client I want to keep connected for incoming messages?

**Comment by lgrahl** [comment]
The thing is your approach is kind of working around the event loop instead of leveraging it. What I would do is fire up an **async** task that creates the connection and then do everything in that task, most likely in a loop. You can still wrap it in a class if you like.

```python
async def main():
    ws = await websockets.connect(...)
    await ws.send(...)
    # wrap it in a class if you like
    while true:
        # do everything else here

asyncio.run(main)
```
