### ISSUE TITLE
is there a way to bind to a local ip upon client connect

### ISSUE THREAD

**Issue by iofo** [aaugustin/websockets#730]
I would like to be able to specify the local IP address of my client websocket connection.
This would involve a bind socket call prior to socket connect.
Is there a way to specify this when calling connect.
Thanks,
Tom

**Comment by aaugustin** [comment]
Yes.

Per the [documentation of connect()](https://websockets.readthedocs.io/en/stable/api.html#websockets.client.connect):

> connect() is a wrapper around the event loop’s create_connection() method. Unknown keyword arguments are passed to create_connection().

Looking at the [documentation of create_connection()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection):

> local_addr, if given, is a (local_host, local_port) tuple used to bind the socket to locally. The local_host and local_port are looked up using getaddrinfo(), similarly to host and port.
