### ISSUE TITLE
Websockets server throws TypeError

### ISSUE THREAD

**Issue by CmdrNorthpaw** [aaugustin/websockets#732]
Running a Websockets server throws the following error: 

```
ERROR:websockets.server:Error in connection handler
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
TypeError: reciever() takes 0 positional arguments but 2 were given`
```

I'm running Python 3.8 on a Raspberry Pi 4B with Manjaro ARM.

**Comment by aaugustin** [comment]
The first argument you're passing to `serve()` must be a coroutine accepting two arguments. You defined `reciever` without arguments.
