### ISSUE TITLE
Unclear error report: giving dictionary as argument to send() causes "IncompleteReadError: 0 bytes read on a total of 2 expected bytes"

### ISSUE THREAD

**Issue by TrulyBright** [aaugustin/websockets#734]
Hi. I had the same problem in #579 some hours ago and finally managed to find the cause.

The error occurs when the code below runs:
```
async def handler(ws, path):
  await ws.send({'foo': 'bar'})
```
But it doesn't if we wrap the dict with ```json.dumps()```:
```
async def handler(ws, path):
  await ws.send(json.dumps({'foo': 'bar'}))
```
It was not easy to find the cause since the error report was unclear. I think it is better to show clear error like ```TypeError: type 'dict' was given to send() which doesn't accept that type as argument```, not the unclear message in the title.

This solution is not applicable to #579. vgoklani had the error though all data to send are wrapped with ```json.dumps()```. It seems the IncompleteReadError has plural causes.

**Comment by aaugustin** [comment]
I believe `websockets` is treating this as:

```python
async def handler(ws, path):
  await ws.send(['foo'])
```

which sends a fragmented message with a single fragment containing the string `foo`.

The client doesn't expect this and summarily closes the connection, which produces the error you're seeing.
