### ISSUE TITLE
Howto client: is WebSocket connected?

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#736]
Hi! What is the proper way to check if my (client) side is still connected (in the case of keep-alive present)?   
Is it enough something like `if wb:` or just ping/pong before sending a message?
(or put the message sending in a try and if exception redo the connection and try again?)
Thank you!

**Comment by aaugustin** [comment]
```python
pong_waiter = await ws.ping()
await pong_waiter
```
is probably the best answer to your question.

Be aware that the connection could still drop between this ping/pong and whatever you're going to do next. So you still need to handle connections errors.
