### ISSUE TITLE
How to read response body when server rejects connection

### ISSUE THREAD

**Issue by nosalan** [aaugustin/websockets#739]
Some WebSocket servers return BadRequest with details in body when something is wrong with websocket request. The `connect` method throws `InvalidStatusCode` exception but only status code is included there. Is it possible to read the response body in such case? 
There is a low level [read-response](https://websockets.readthedocs.io/en/stable/_modules/websockets/http.html#read_response) function but I don't know from where to get the `asyncio.StreamReader` parameter it requires.

**Comment by aaugustin** [comment]
#795 was exactly the same question, and there a bit more info on that issue, so let's follow up over there.
