### ISSUE TITLE
HTML+JavaScript example?

### ISSUE THREAD

**Issue by yotam-medini** [aaugustin/websockets#74]
Since websocket is frequently used for updating web pages,
it would be nice to have a complete I/O example with HTML having linked javascript code
that communicates with a [Python] websocket server.
thanks -- yotam

**Comment by aaugustin** [comment]
That's out of scope for the documentation but FYI here's what it looks like:

    <script>
    var ws = new WebSocket("ws://localhost:8765/");
    ws.onmessage = function (event) { console.log(event.data); }
    </script>

Just put this in any HTML file.

**Comment by shyam143007** [comment]
Does this snippet work on IE too because its not working on my system.

**Comment by mschnitzer** [comment]
@shyam143007 Try this one: https://www.websocket.org/echo.html

**Comment by shyam143007** [comment]
i'm new to python and django so i don't have much knowledge regarding this, but i want to know how to integrate the django server with websockets
i tried by googling and found few solutions but not that helpful to solve the issue.

**Comment by mschnitzer** [comment]
I didn't work with Django yet, but the WebSocket Server is an isolated program. You don't have to implement a WebSocket Server into Django. You can just run the server as a single program. Then you have to implement the code (which I sent you) into your Django project and send the Java Script part to a user.

**Comment by shyam143007** [comment]
thanks @mschnitzer  i got the solution i was starting the loop inside a method which i removed now and its working fine.

**Comment by aaugustin** [comment]
Just to be clear — I'm making an explicit choice not to mention this in the documentation because I don't have time for teaching this stuff to everyone for free. If I documented it I would have support requests about it.

`websockets` expects basic Python and JS skills. There are enough tutorials around the web.

**Comment by Ivoz** [comment]
@aaugustin maybe it'd be helpful to write a paragraph on an "example" or two of how this package might be used as part of a larger picture of a web application. And/or, together with any short note on what "deploying" it would look like.

**Comment by aaugustin** [comment]
Agreed, deployment tips would be useful.
