### ISSUE TITLE
Apparently contradicting messages in debug logs

### ISSUE THREAD

**Issue by Gobot1234** [aaugustin/websockets#740]
Hi,

Currently I am trying to connect to a Steam CM server in a ``websockets.client.WebSocketClientProtocol`` subclass. When reading information from the debug log I receive this info:

```py
DEBUG:websockets.protocol:client - state = CONNECTING
DEBUG:websockets.protocol:client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x107478e90>)
DEBUG:websockets.client:client > GET /cmsocket/ HTTP/1.1
DEBUG:websockets.client:client > Headers([('Host', 'cm2-par1.cm.steampowered.com:27022'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', '/not too sure if you can do stuff with this'), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.7 websockets/8.1')])
DEBUG:websockets.protocol:client - event = data_received(<129 bytes>)
DEBUG:websockets.client:client < HTTP/1.1 101 Switching Protocols
DEBUG:websockets.client:client < Headers([('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Accept', 'again not too sure if you can do stuff with this')])
DEBUG:websockets.protocol:client - state = OPEN
```
This specifies that the connection is open, however when printing self.state in ``protocol.py`` it says it is ``State.CONNECTING`` in ``ensure_open`` I am aware it says 
> Control may only reach this point in buggy third-party subclasses.

But I am unaware what exactly is wrong with [this (my source code)](https://gist.github.com/81ba3d6dfe3354aa3cef5923536d9f36)?
[The full error](https://gist.github.com/87ea1835ca51dc5848a73fd4fc13637f)

System Info:
----------------
Python version: 3.7.5 (v3.7.5:5c02a39a0b)
Library version: 8.1
OS: macOS Catalina 10.15.2 (19C57)

Thank you :D

**Comment by aaugustin** [comment]
It looks like you're creating a connection here: `self.ws = await websockets.connect(server, loop=client.loop)`. However, this isn't connecting the current instance of your `SteamWebSocket` class. It's creating a new instance of `WebSocketClientProtocol` and returning it. As a consequence, your `SteamWebSocket` instance is still in the initial state, CONNECTING.

**Comment by Gobot1234** [comment]
Ah thank you 👍.
