### ISSUE TITLE
Consider accepting 4107 bytes for request maximum accepted line size

### ISSUE THREAD

**Issue by thomasleveil** [aaugustin/websockets#743]
The code responsible for parsing a line from the request [raises `SecurityError("line too long")`](https://github.com/aaugustin/websockets/blob/139085fe2624192a5a6c72b1e5db211dcec6ced1/src/websockets/http.py#L216) when the size is greater than [`MAX_LINE = 4096`](https://github.com/aaugustin/websockets/blob/139085fe2624192a5a6c72b1e5db211dcec6ced1/src/websockets/http.py#L37)

Please consider increasing `MAX_LINE` to `4107` bytes.

# Rationale 

While the HTTP protocol does not specify limits for [request-line size](https://tools.ietf.org/html/rfc7230#section-3.1.1), [header size](https://tools.ietf.org/html/rfc7230#section-3.2.5) or [cookie size](https://tools.ietf.org/html/rfc2965#section-5.3), server implementations do (for security reasons). User agents also implement limits for the maximum size of a request-line, header, cookie, ...

So how to choose a reasonable limit for the maximum size a server implementation could enforce when parsing a requests ? We must consider what maximum sizes are enforced by popular recent user agents (let say Firefox and Chrome). 

It is safe to assume that the most frequently oversized line in a HTTP request is the one for the cookie header, since website developers tend to abuse this storage facility. On the [browsercookielimits](http://browsercookielimits.squawky.net/) website, we can discover that cookie value limits for popular browsers are : 
- Chrome : 4096 bytes
- Firefox : 4097 bytes

If we want to accept any requests made from those browsers even when they include a cookie reaching the user agent limit, we on the server side must consider accepting a request line of **4107 bytes** : 

```
cookie: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n
\__ 8 _/\___________ 4097 ____________/\_2/    = 4107
```

**Comment by aaugustin** [comment]
This is interesting. A couple thoughts:

- I think we need a bit more space because we could receive `set-cookie: ...` in a response; that's 4 more bytes (`set-`).
- I'd rather jump to 5000 or 8192 than match an implementation detail that isn't even consistent across browsers.

**Comment by thomasleveil** [comment]
Sure, and why not allowing to customize this value with an environment variable ? When I was first hit by this limitation, I was a bit disappointed to not be able to increase that limit. I ended up removing the cookie header in Varnish en front of my app (since my websocket endpoint does not care about cookies) and this feels hacky. I use gunicorn+uvicorn and uvicorn depends on this project for websockets.

I also took a look at Hypercorn, and their websocket [implementation](https://github.com/pgjones/hypercorn/blob/6f243df889ff008bf8a8175010b660d92892669c/src/hypercorn/protocol/ws_stream.py) does not seem to apply limits at all on headers size when accepting connections. However they have a (configurable) limit for websocket frame size. See their [Denial Of Service mitigations](https://github.com/pgjones/hypercorn/blob/45b1d754256c986a45f590edcd193a938cccf4a1/docs/discussion/dos_mitigations.rst) document.

**Comment by aaugustin** [comment]
You can monkey-patch the constant if you really feel strongly about this.

I think the correct limit is:

- `Set-Cookie: ` = 12 bytes
- Max cookie size = 4096 bytes (that's what the RFC requires, and while Firefox supports one more byte, Chrome doesn't)
- `\r\n` = 2 bytes

Total = 4110 bytes
