### ISSUE TITLE
Stuck client connections

### ISSUE THREAD

**Issue by Berserker66** [aaugustin/websockets#750]
So, we've been having some problems regarding stuck player slots because the server never notices that a client dropped unexpectedly. Trying to debug the problem has proven difficult as well.

The full code is at https://github.com/Berserker66/MultiWorld-Utilities However MultiClient and MultiServer are relevant.

Basically, a client may drop unexpectedly and despite a finally clause to .disconnect(), the finally may never be reached. 

We also have this mystifying error sometimes:
https://media.discordapp.net/attachments/701172724084637867/702216352580239420/unknown.png
That I haven't managed to replicate on my end at all yet, but may be related.

Some help would be really appreciated. This particular project started off as a fork. The websockets related code is by someone who has abandoned the project. :(

**Comment by aaugustin** [comment]
I'm sorry, your first question is too wide for me to investigate. You linked to thousands of lines of code and I don't know where to start.

Your second question looks a lot like #810.

Sorry I can't help more!
