### ISSUE TITLE
 I can use it only as a client to connect to an API?

### ISSUE THREAD

**Issue by mvalino0201** [aaugustin/websockets#753]
I want to change the way I connect to a websocket, looking for efficiency. I'm not a developer, and I'm having a hard time understanding if websockets is the way to go.

I currently connect using websocket

        self.socket = websocket.WebSocketApp(self.session.wsUrl,
                                             on_message=self.on_message,
                                             on_error=self.on_error,
                                             on_close=self.on_close,
                                             on_open=self.on_open,
                                             header=self.session.authtoken)
        self.startSocket()

**Comment by aaugustin** [comment]
`websockets` relies on Python's `asyncio` framework, which is a non-trivial barrier to entry.

Considering that you describe yourself as "not a developer", I don't think you want to put "learn asyncio" between your current situation and your target.
