### ISSUE TITLE
access remote_address during handshake

### ISSUE THREAD

**Issue by eoghanmurray** [aaugustin/websockets#754]
Is there any way to access the remote IP Address during the handshake?

It seems only the `request_headers` are passed to the `process_request` callback, and not `websocket.remote_address`.

**Comment by aaugustin** [comment]
Sorry, I wish I had a better answer than what follows :-(

There are two ways to implement the `process_request` callback:

1. Pass a coroutine in the `process_request` argument of `serve`
2. Subclass `WebSocketServerProtocol`, override the `process_request` method, and pass this subclass in the `create_protocol` argument of `serve`

With 1, you don't have access to the current `WebSocketServerProtocol` instance. With 2, you do — it's the `self` argument of the method — so you have access to `self.remote_address`.

All this is a bit difficult to change without breaking backwards compatibility, so... here we are.

**Comment by aaugustin** [comment]
Marking as a possible enhancement, although for now, I have no idea what the enhancement would be.

**Comment by eoghanmurray** [comment]
Thanks, I think I'd seen an example of the subclassing option a while back but didn't connect it to my current requirement, so will look at that.

Re. backwards compatibility, would it be too much if the calling code inspected the passed coroutine and if it accepts 3 arguments then pass in the remote address (or the `WebSocketServerProtocol` instance)?

I don't think you'd even need the `inspect` module, as `len(passed_coroutine.__code__.co_varnames)` may do the trick.

**Comment by aaugustin** [comment]
I think I will leave things the way they are for now.
