### ISSUE TITLE
connectting to a specific path

### ISSUE THREAD

**Issue by LucaPaterlini** [aaugustin/websockets#755]
I am reading the tutorial on how to use it.
After reading it I have been left wondering 

https://websockets.readthedocs.io/en/stable/intro.html

how can I create a WebSocket on a specific path say /sub/hi

Thanks in advance for the response

**Comment by aaugustin** [comment]
Does this answer your question?

```python
async def hello(websocket, path):
    if path == '/sub/hi':
        do_stuff()
    else:
        do_other_stuff()
```

See also #311.

If not, can you clarify the question?

**Comment by LucaPaterlini** [comment]
thanks for your response, what you have mentioned is the code client side,
I am looking for the code server-side that expose the service

**Comment by aaugustin** [comment]
My answer is for the server side.

You receive the path in the second argument to the connection handler.
