### ISSUE TITLE
Handling disconnected clients and terminating the connection handler

### ISSUE THREAD

**Issue by rgov** [aaugustin/websockets#757]
I am a newcomer to asyncio and websockets. I am developing a server where clients connect and from time to time a message is broadcast to all of them.

I am using a connection handler that looks something like this:

```python
clients = set()
async def handle_client(websocket, path):
    clients.add(websocket)
    while True:
        await asyncio.sleep(60)
```

Meanwhile, occasionally I will enumerate over `clients` and call `client.send()`. At this point, `client.send()` may raise a `ConnectionClosed` exception if the corresponding client has disconnected.

First, how do I properly handle this exception to remove the client from the connection set? I was thinking it would be something like this, but it isn't quite right.

```python
done, _ = \
    await asyncio.wait([client.send(message) for client in clients])
for task in done:
    if isinstance(task.exception(), websockets.ConnectionClosed):
        # I don't see such an attribute that I can use to get the associated instance
        clients.remove(task.exception().websocket)
```

Secondly, I believe my connection handler routine will forever be in its wait loop even after the client is disconnected. I could change the loop to something like:

```python
while websocket in clients:
    await asyncio.sleep(60)
```

Is that the best option available to me? It seems like I could also send occasional pings from the connection handler but I would rather not generate excess traffic if it can be avoided.

The [counter.py example](https://github.com/aaugustin/websockets/blob/master/example/counter.py) is similar but because it calls `send()` in its connection handler, it receives the `ConnectionClosed` exception there.

**Comment by aaugustin** [comment]
Do this:

```python
async def handle_client(websocket, path):
    clients.add(websocket)
    try:
        await websocket.wait_closed()
    finally:
        clients.remove(websocket)
```

Ignore exceptions when iterating over `clients`. Eventually broken connections will close and go through the `finally` block in the connection handler.

Marking as a documentation issue to check if examples can be improved.
