### ISSUE TITLE
How to call recv() from two coroutines concurrently

### ISSUE THREAD

**Issue by ocurero** [aaugustin/websockets#758]
Hi,

Reading through the changelog I read that since version 7.0 recv() fails if two coroutines call recv() concurrently. I know the answer may be obvious, just asking for clarification.
Do we need to protect recv() with a asyncio.lock to prevent two coroutines to call it concurrently? 

Like this: 

```
recv_lock = asyncio.Lock()
# ws is defined somewhere

async def send_receive():
    await ws.send('hi')
    async with recv_lock:
        response = await ws.recv()
```

Thanks!!

**Comment by aaugustin** [comment]
Most applications are built in such a way than `recv()` is called only once, and if it's called twice, it's a bug. Then it's up to you:

- if you don't use a lock, the app will crash and you'll know you have a logic error somewhere;
- if you use a lock, the app won't crash but you may get unexpected results.

In general I'd go for the first option. But that's up to you really.
