### ISSUE TITLE
Is there a way to disable all logging or make it optional?

### ISSUE THREAD

**Issue by DobroAlex** [aaugustin/websockets#759]
Greetings. I have pretty extensive logging in my app and I don't want WebSockets to show any of its logging. Is there a proper way to disable it? 

I came up with the following solution:
There is logging setup method in the app context creation there I add the following code:
`
for logger_name in {'websockets.protocol', 'websockets.server', 'websockets.client'}:
    logging.getLogger(logger_name).disabled = True
`

But I don't think of the usage of string constants as something good and this feels totally barbarous way to disable the logging.

**Comment by RemiCardona** [comment]
python logging is hierarchical, try disabling the top-most logger:
```python
logging.getLogger('websockets').disabled = True
```
should do it. If not, you could add a NullHandler and disable propagation to the root logger.

**Comment by DobroAlex** [comment]
I Should have guessed myself, that's pretty good and simple, thank you
