### ISSUE TITLE
TypeError: 'Lock' object is not iterable on py3.9

### ISSUE THREAD

**Issue by DavidBord** [aaugustin/websockets#760]
As can be seen in the errors from Sanic build: https://travis-ci.org/github/huge-success/sanic/jobs/686952886
That's probably because of this py3.9 change: https://github.com/python/cpython/commit/90d9ba6ef10af32e8dfe0649789c3a8ccf419e95

**Comment by aaugustin** [comment]
OK, hopefully we can find syntax that works both on Python 3.6 and 3.9?

**Comment by ahopkins** [comment]
I think you can just use

    async with...

I believe that async context managers have been in since before 3.6.

**Comment by DavidBord** [comment]
Sanic tests use an old version of websockets (0.7.0).
The usage of asyncio.Lock is fixed on newer websockets version (0.8.1).
