### ISSUE TITLE
Log pings similar to how receiving pongs are logged

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#765]
I noticed an asymmetry in the debug logs, namely that "server - received solicited pong" is logged, but sending the ping isn't. I think it would be a little user-friendlier if the outgoing ping appeared similarly. That way people could match them more easily.

(The lower-level `write_frame()` log message does occur in the outgoing direction, but it's not obvious whether it corresponds to the ping. Also, in the incoming direction, you do have two messages: both the lower-level `read_frame()` message, as well as the pong message.)

**Comment by aaugustin** [comment]
When sending a ping, there's nothing else to say than "we're sending a ping", which is currently covered by the almost-network-level debug logs.

Where receiving a pong, there are two pieces of information: "we're receiving a pong" and "does this pong match a ping we sent earlier?"

My interpretation of your suggestion is the following: add more human-friendly versions of the debug logs, like "sending a text frame / ping / pong / etc." in addition to the low level codes which, indeed, don't make a ton of sense if you don't know the binary opcodes of the various types of frames.

An intermediary solution would be to display the name of the opcode i.e. OP_PING instead than 0x09 (which the current version does, I think).

**Comment by cjerdonek** [comment]
> My interpretation of your suggestion is the following: add more human-friendly versions of the debug logs, like "sending a text frame / ping / pong / etc."

Yes, that's what I was suggesting.

**Comment by aaugustin** [comment]
While I made this a goal of #960, it's somewhat independant, so I'll keep this issue open for now.
