### ISSUE TITLE
Provide hook for reporting exceptions

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#769]
I don't have a specific API suggestion on this yet, but I wanted to throw it out there.

There are various places where `WebSocketCommonProtocol` and its subclasses handle exceptions as a last resort (e.g. `handler()` and `transfer_data()`). Currently, these are logged using the `logger`. In an application setting though, you might want to do something like report the exception to a crash reporter (like Sentry). Since `logger` is hard-coded, there's not a clear way to do this. Thus, my thought is for there to be an API that would let one hook into exceptions of interest. It could e.g. default to using the logger.

**Comment by aaugustin** [comment]
I believe the Sentry client (and other similar tools) can declare a log handler which will get the logs from `logger` (as well as any other logger in the application).

**Comment by aaugustin** [comment]
An easy solution would be to add a method to `WebSocketCommonProtocol` to report errors:

```python
        def report_error(self, message):
            logger.error(message, exc_info=True)
```

The two cases you mentioned are the only two cases in the codebase.

This would also require moving the logger to an attribute of the class — something we should do anyway so messages don't get logged on the `"websockets.protocol"` logger.

**Comment by aaugustin** [comment]
It is now possible to inject a custom logger instance, which should provide enough flexibility.
