### ISSUE TITLE
Receiving messages only after a very long time

### ISSUE THREAD

**Issue by initzx** [aaugustin/websockets#771]
Hello, my problem has been that when I establish a connection to my websocket server and begin sending messages, the messages can all be sent, but at some point I stop receiving the messages I am supposed to receive, or rather more accurately, the messages only arrive after a very long time. 

I believe that it has something to do with my application code, as if something is blocking the receiving queue. I have tested this with other clients that were able to communicate with the server and they all seem to do just fine. 

Nonetheless, other websockets in my application function fine whilst this one isn't able to receive any messages:
```python
    async def _connect(self):
        backoff = ExponentialBackoff(2)
        while not (self.ws and self.ws.open):
            try:
                self.ws = await websockets.connect(self.uri, extra_headers=self.headers)
                task = asyncio.create_task(self.listen())
                # asyncio.create_task(hello())
                self.keep_alive = KeepAlive(self, 3)
                self.keep_alive.start()
                # await task
            except OSError:
                delay = backoff.delay()
                logger.error(f"Connection refused, trying again in {delay:.2f}s")
                await asyncio.sleep(delay)


    async def listen(self):
        try:
            while True:
                msg = await self.ws.recv()
                logger.debug(f"Received websocket message from `{self.name}`: {msg}")
                await self.on_message(json.loads(msg))
        except websockets.ConnectionClosed:
            pass  # ping() handles this for us, no need to hear it twice..


    async def send(self, msg):
        if not self.ws or not self.ws.open:
            self.available = False
            raise NodeException("Websocket is not ready, cannot send message")
        logger.debug(f"Sending websocket message: {msg}")
        await self.ws.send(json.dumps(msg))
```
What am I doing wrong here?

**Comment by aaugustin** [comment]
I'm not seeing anything obvious here. Enabling debug logs might help: https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging

Running your own keepalive task doesn't seem necessary. Instead you should adjust the parameters of websockets' built-in keepalive if they don't do what you want.

Based on the symptoms you're describing, you might be saturating the connection from the client to the server. In that case websockets will apply backpressure and stop processing input until the output gets better. Specifically, when it receives a ping, it will wait until it can send the corresponding pong, and it can't as long as the send buffers are full. Most libraries don't handle backpressure correctly, which could explain why websocket stands out of the pack.

This is fairly uncommon, though: it requires sending a lot of data faster than the server can process it. In fact, it's somewhat tricky to trigger on purpose. Usually things break down before backpressure comes into play.

**Comment by initzx** [comment]
Is there a way to monitor how much my websockets are sending on a lower level, or even verify that it is due to backpressure? I've tried to use the debug settings, but it doesn't seem manageable to look at a million messages being sent all at once.

**Comment by aaugustin** [comment]
If you're sending a million messages at once, perhaps you're facing the issue I suggested.

websockets doesn't do anything in this regards. Everything is handled by asyncio and then the operating system (and then the NIC, if you go all the way down...)

As far as I know asyncio doesn't provide a way to inspect the send buffer, but you should see something in the logs if you saturate it:
https://github.com/python/cpython/blob/033d10bd21d962a59c6c4fc503092046baa451a1/Lib/asyncio/streams.py#L158

You can try experimenting with https://docs.python.org/3/library/asyncio-protocol.html#asyncio.WriteTransport.set_write_buffer_limits. If you set it higher than the total amount of data your application may send "at once", is it better? e.g. if you're sending one million messages of 32 bytes each, add 8 bytes for the WebSocket header, and set the buffer to 40 megabytes.

(I don't know how well Python will handle a 40MB bytes object. This may grind the interpreter to a halt.)

Keep in mind that the OS may buffer several megabytes as well. Controlling the asyncio write buffer doesn't give you full control. However, it can give you a general idea  of what's happening.

**Comment by aaugustin** [comment]
Hrm, wait, scratch that — websockets no longer uses asyncio's StreamWriter. It writes straight to the transport. So all you have is the OS buffer.

In general, this should be more efficient, but it may degrade less gracefully under excessive write load (our theory here).

Furthermore, the OS buffers usually much larger than asyncio.StreamWriter's buffer: a few MB vs 64kB if memory serves, so I don't think missing the asyncio buffer makes a big difference in your situation.

----

You can try commenting out this block of code:
https://github.com/aaugustin/websockets/blob/69c94af5c0ad19402e0bedcc6b61a23fa070c946/src/websockets/protocol.py#L1069-L1081

If it helps, then it means you're indeed saturating the write buffers.

----

If you need to write a lot of data much faster than you can send it to the network, you can try increasing the buffer size with `setsockopt` on `SEND_BUF_SIZE`.

**Comment by aaugustin** [comment]
I cannot remember what I wanted to document so I am going to close this issue.
