### ISSUE TITLE
Broken link on Python Package Index

### ISSUE THREAD

**Issue by mincrmatt12** [aaugustin/websockets#78]
The link to the documentation is pointing to an old documentation, on a nonexistent github pages server. Please correct it to go to the readthedocs page for this package.

**Comment by SzieberthAdam** [comment]
Digital version of Ramalho 2015 - Fluent Python, p. 581 also links to the nonexisting

http://aaugustin.github.io/websockets/

page.

**Comment by aaugustin** [comment]
That's because I moved the docs to Read the Docs. Back when I started I had to use GitHub pages because Read the Docs didn't support Python 3.3 yet. I'll put a redirect on that page.

**Comment by SzieberthAdam** [comment]
It would be nice to have the latest version of the library on PyPI.

**Comment by aaugustin** [comment]
I wanted to tackle #77 before making a new release.

**Comment by aaugustin** [comment]
I just set up a redirect. It a HTML redirect, which isn't great, but I'm not sure I can do anything better with GitHub Pages.

**Comment by aaugustin** [comment]
@SzieberthAdam I just pushed a release to PyPI.

**Comment by SzieberthAdam** [comment]
Thanks.
