### ISSUE TITLE
Better support for automatic port

### ISSUE THREAD

**Issue by Berserker66** [aaugustin/websockets#780]
it's possible to serve on port 0, to have the OS automatically assign a port, which works.
However, it's hard to retrieve the port it ended up binding to:

```
    for socket in server.ws_server.sockets:
        socketname = socket.getsockname()
```
Additionally, you can end up with multiple different ports, for example one for IPV4 and one for IPV6.

So, this issue is about two things:
  * Make it easier to retrieve a used port (optional for me)
  * Make it possible to limit it to one port per server (the one that's important to me)

**Comment by aaugustin** [comment]
Sure. How would you do this with plain asyncio? Then we can see if it's applicable to websockets.

**Comment by aaugustin** [comment]
My recommendation would be to create the socket outside of `websockets`, so you have full control over it.

Then you can use the `sock` argument to pass it to `serve`, which passes it to `create_server`.

See https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server for documentation.
