### ISSUE TITLE
How can I generate my .pem file?

### ISSUE THREAD

**Issue by archerhu77** [aaugustin/websockets#790]
There are some article tell us how to generate private key, but generate centificate. Can you tell me the right way to generate my own private key and certificate? Thanks!

**Comment by lgrahl** [comment]
This is definitely out of scope. Please, search for `openssl generate self-signed certificate` or `let's encrypt` with your preferred web search engine.

**Comment by archerhu77** [comment]
# generate self-signed certificate

openssl genrsa -out server.key 2048
openssl rsa -in server.key -out server.key
openssl req -sha256 -new -key server.key -out server.csr -subj '/CN=localhost'
openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt

cat server.crt server.key > cert.pem

For anyone who need this.

**Comment by Directory** [comment]
Nobody needs this
