### ISSUE TITLE
Could you add an example of client can input multi times?

### ISSUE THREAD

**Issue by archerhu77** [aaugustin/websockets#791]
1.I make the client can input serval time, but couldn't detect disconnect from client. How can I handle client disconnect?

import asyncio
import pathlib
import ssl
import websockets

async def recv_msg(websocket):
    while True:
        recv_text = await websocket.recv()
        response_text = f"your submit context: {recv_text}"
        await websocket.send(response_text)

async def main_logic(websocket, path):
    # await check_permit(websocket)
    await recv_msg(websocket)

ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
localhost_pem = pathlib.Path(__file__).with_name("localhost.pem")
ssl_context.load_cert_chain(localhost_pem)
start_server = websockets.serve(main_logic, 'localhost', 8765, ssl=ssl_context)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

2.How can we make server.py can send message to some client when connected?(Sometimes server need to send system message to client without client send message to server.)

**Comment by lgrahl** [comment]
1. Just call `recv_msg` in a loop.
2. Call `await websocket.send(greeting_message)` before anything else in `main_logic`.
