### ISSUE TITLE
Best Practise for handeling different messages via one connection?

### ISSUE THREAD

**Issue by JonahKr** [aaugustin/websockets#792]
Hi there 👋,

At first, i like this library very much... it workes flawlessly.
I was wondering wether there is a best practise for handeling different Messages/events recieved by a client at random intervals with each one needing to invoke a different method.
I am working with the Home Assistant Websocket API and different Eventsubscriptions are handled via a ID in the message.
So there are "Rest-Like" Calls (Request -> Response) both sharing the same ID
And Events which you can subscribe to.

Maybe i need to switch to a callback based library? And if so, do you have any recommendations?

Thanks in advance

**Comment by lgrahl** [comment]
You can just switch on it and call the function. I'm not sure there's a best practice here.

```python
import asyncio
import websockets

async def hello():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket:
        message = decode(await websocket.recv())
        if message.id == something:
            do_something(message)
        elif ...

asyncio.get_event_loop().run_until_complete(hello())
```

**Comment by aaugustin** [comment]
Doing something about this is #311.
