### ISSUE TITLE
Receiving binary data fails for non-ASCII values

### ISSUE THREAD

**Issue by avitase** [aaugustin/websockets#794]
Hi,

I have this test client:
```
#!/usr/bin/env python3

import asyncio
import websockets

async def run(port):
    uri = f'ws://localhost:{port}'
    async with websockets.connect(uri) as websocket:
        msg = await websocket.recv()
        print(f"> {msg:b}")

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(run(8888))
```
that I want to receive raw bytes but `websocket.recv()` fails and throws:
```
Traceback (most recent call last):
  File "[...] python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "[...] python3.8/site-packages/websockets/protocol.py", line 910, in read_message
    return frame.data.decode("utf-8") if text else frame.data
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1: invalid start byte
```
Is there a way to change the decoder? I already had a look at the [documentation of `recv`](https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol.recv) and 
found that it apparently can return bytes, so obviously I am missing a configuration step (?)

**Comment by aaugustin** [comment]
The problem is on the other end. You're receiving a message of type "Text" that contains non UTF-8 data. The sender should use the type "Binary" instead. See https://tools.ietf.org/html/rfc6455#section-5.6 for details.

**Comment by aaugustin** [comment]
Since your example runs on localhost, I assume you control the server code, so you can change it. `websockets` wouldn't let you send invalid data ;-)

**Comment by avitase** [comment]
Thanks for your help!
