### ISSUE TITLE
Support for multiple ssl contexts on same port

### ISSUE THREAD

**Issue by villekr** [aaugustin/websockets#796]
(This is a question)

I need to support both server side ssl certificates as well as mutual client and server side certificates for connection attempts. Currently I'm serving those on different ports as shown below. Is it possible to configure websockets server so that it can accept both types of connections on same port?

# WebSocket server with server side certificates
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
(ssl_context creation omiitted for clarity)
server = await websockets.serve(on_connect, listen_addr, 9998, ssl=ssl_context)

# WebSocket server with mutual (client and server) certificates
ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ssl_context.verify_mode = ssl.CERT_REQUIRED
(ssl_context creation omiitted for clarity)
server = await websockets.serve(on_connect, listen_addr, 9999, ssl=ssl_context)

**Comment by aaugustin** [comment]
If you show me how you do this with plain `asyncio`, I can probably extrapolate how to do this with `websockets`.

**Comment by villekr** [comment]
I'm not sure if I fully understand what I should show with asyncio. Do you mean full example how it's done atm? Or identical case using asyncio but with http instead of websockets? If I try to open both websocket servers on same port I get (naturally) address already in use error.

**Comment by aaugustin** [comment]
Let me clarify :-)

If you can do something with asyncio, there's a good chance you can also do it with websockets. If not, I will likely treat this as a valid bug report or feature request.

If you can't do it with asyncio, then I won't feel any pressure to support it in websockets, as websockets is layered on top of asyncio.

I don't have time (or expertise, in fact) to provide general support on asyncio :-( I'm only interested in the value added by websockets on top of asyncio.

So, if you can demonstrate a TLS/TCP server in asyncio that does what you want (support the two kinds of connections on a single port), and you can't achieve the same with websockets, I'll try to help. The server doesn't need to do anything besides accepting connections and negotiating TLS like you want.

If you can't demonstrate such a server, I'll assume that it isn't possible with asyncio, and therefore with websockets, and as a consequence I'll close the issue.

**Comment by villekr** [comment]
Thanks for clarification, now I got it :)

**Comment by aaugustin** [comment]
I'm going to close this issue because I don't think there's anything actionable for me here. If you have news, please comment and I'll consider reopening the issue.

**Comment by villekr** [comment]
"Fallback to basic auth when ssl.CERT_OPTIONAL and client certificat is not provided" might be more appropriate title for this.

I've managed to sort of hack around this so that if client doesn't provide certificate then client is authenticated using basic auth. However, as the basic auth is done on "on_connect" it's propably not possible to send correct http 401 response to client.

The following code should provide enough context for the issue:

```
import ssl
import websockets
from websockets import WebSocketServerProtocol, basic_auth_protocol_factory
from websockets.headers import parse_authorization_basic
from websockets.exceptions import InvalidHeader


async def check_credentials(self, username: str, password: str) -> bool:
    ...


async def authenticate(ws: WebSocketServerProtocol):
    """Try to authenticate with basic auth if no client certificate is present

    Modified from websockets/auth.py process_request
    """
    if ws.transport.get_extra_info("peercert") is None:
        try:
            authorization = ws.request_headers["Authorization"]
        except KeyError:
            raise exceptions.MissingCredentials()

        try:
            username, password = parse_authorization_basic(authorization)
        except InvalidHeader:
            raise exceptions.UnsupportedCredentials()

        if not await check_credentials(username, password):
            raise exceptions.InvalidCredentials()


async def on_connect(ws: WebSocketServerProtocol, path: str):
    # Authenticate with basic auth if no client certificate is provided
    #
    try:
        await authenticate(ws)
    except exceptions.InvalidCredentials:
        # Connection is already setup so it's late to send here http 401 "Invalid credentials"
    ...

...
create_protocol = basic_auth_protocol_factory(
    realm="foo",
    check_credentials=check_credentials,
)
ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
ssl_context.verify_mode = ssl.CERT_OPTIONAL

server = await websockets.serve(
    on_connect,
    "0.0.0.0",
    443,
    ssl=ssl_context,
    # create_protocol=create_protocol,
)
```

Possible solution could be to add peercert (or argument to basic_auth_protocol_factory's check_credentials coroutine. However, that might be a confusing argument is only basic auth is needed.
```
async def check_credentials(self, username: str, password: str, peercert: str) -> bool:
    if peercert is None:
        # perform credential check
        ...
```

**Comment by villekr** [comment]
@aaugustin Can you provide any assintance on the issue or maybe consider this as change request?

**Comment by aaugustin** [comment]
This is yet another instance of "the `process_request` hook needs access to the protocol instance" and "websockets tries to stay away from subclassing as an API but sometimes that's what you want" :-/

I would recommend that you subclass [BasicAuthWebSocketServerProtocol](https://websockets.readthedocs.io/en/stable/api/server.html#websockets.auth.BasicAuthWebSocketServerProtocol) and to override `process_request` there. If you have authentication with a peer certificate, `return None`. Else, `super().process_request(...)` to perform basic auth.

**Comment by villekr** [comment]
Thanks for the help!

So now I feel kind of embarrassed when reading websockets.server.serve documentation, which has the relevant pointers:
- create_protocol defaults to WebSocketServerProtocol. It may be replaced by a wrapper or a subclass to customize the protocol that manages the connection.
- process_request allows intercepting the HTTP request; it must be a coroutine taking the request path and headers in argument; see process_request() for details.

I also needed to pass extra argument for subclass, which adds a little bit extra complexity. Here's updated code if it may be helpful for others.

```
import ssl
import functools
import asyncio

import websockets
from websockets import WebSocketServerProtocol, BasicAuthWebSocketServerProtocol
from websockets.legacy.server import HTTPResponse


def ssl_context():
    ...


async def echo(ws: WebSocketServerProtocol, path: str):
    message = await ws.recv()
    await ws.send(message)


class AuthorizationService:
    def authenticate_with_password(self, username: str, password: str) -> bool:
        return True  # easy-going authentication just for a reference


class DualAuthWebSocketServerProtocol(BasicAuthWebSocketServerProtocol):
    def __init__(self, *args, authorization_service: AuthorizationService, **kwargs):
        self.authorization_service = authorization_service
        super().__init__(
            *args, check_credentials=self.check_credentials, **kwargs
        )

    async def process_request(self, path, request_headers) -> Optional[HTTPResponse]:
        client_cert = self.transport.get_extra_info("peercert")
        if client_cert is None:
            return await super().process_request(path, request_headers)

    async def check_credentials(self, username: str, password: str) -> bool:
        return self.authorization_service.authenticate_with_password(
            username=username, password=password
        )


async def start():
    # Pass additional arguments to DualAuthWebSocketServerProtocol
    create_protocol = functools.partial(
        DualAuthWebSocketServerProtocol,
        realm="foo",
        authorization_service=AuthorizationService(),
    )
    server = await websockets.serve(
        echo, "0.0.0.0", 443, ssl=ssl_context(), create_protocol=create_protocol
    )
    await server.wait_closed()


if __name__ == "__main__":
    asyncio.run(start())

```

**Comment by aaugustin** [comment]
Don't be embarrassed -- it's hard to see how the pieces fit together and the documentation isn't stellar!
