### ISSUE TITLE
Improve documentation for working with HTTP headers

### ISSUE THREAD

**Issue by Aran-Fey** [aaugustin/websockets#798]
As per the discussion in #420, the documentation regarding HTTP headers should be improved.

For reference, here's a summary of my personal experience with this:

1. Because I've never worked with websockets before, I initially assumed headers could be sent along with every message - but since the `send` method clearly doesn't accept any arguments besides the message, this was a dead end.
2. Not knowing where to look, I typed "header" into the search bar and got no useful results.
3. Realizing that it searched for whole words, I tried again with "headers". This yielded slightly more useful results (or at least they look more useful at first glance), which led me down the 3 rabbit holes `websockets.http`, `websockets.headers` and `websockets.handshake`.
4. After giving up on the docs and googling for a while, I discovered #420, where `extra_headers` is mentioned, but typing "extra_headers" into the search bar once again returned nothing useful.

**Comment by aaugustin** [comment]
Thanks, that's very useful.

Currently the documentation assumes that users are familiar with the WebSocket protocol. There was some discussion to point to general documentation about the protocol, however we haven't found a good resource. The best we found was in the SocketIO documentation, however it could be confusing due to websockets not implementing the entire SocketIO protocol.

**Comment by Aran-Fey** [comment]
Honestly, I don't think it's necessary for your docs to teach readers about websockets in general. I've made a (singular) wrong assumption about websockets, and realized my mistake when I found that your library doesn't support that feature. That wasted maybe 2 minutes of my time. It wasn't a big deal.

The real problem is the search - it's laughable how useless that search bar is. I don't know if you have any control over that (I assume you don't), but maybe you could do some SEO by incorporating important words/phrases in the documentation (since the search doesn't seem to search function signatures and the like). Even if someone doesn't know how websockets work, they usually have at least a rough idea of what they want to accomplish - and the search bar should help them find the relevant parts of the doc.

**Comment by aaugustin** [comment]
You aren't the first one to get confused about this aspect of the WebSocket protocol (although others have usually not been able to realize and explain it as clearly as you did).

No, I don't have control about the search. I see that FAQ about headers on the server side shows up in the search results (in last position). If I add a FAQ about headers on the client side, that should help.

Also, it would be better to have more prose docs and less API docs... That takes time to write...

**Comment by aaugustin** [comment]
Would be good to include this advice: https://github.com/aaugustin/websockets/issues/331#issuecomment-358787179
