### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by wh1tebeard** [aaugustin/websockets#80]
I got the following while installing websockets via pip:

    xxxxx@lamp:~$ pip install websockets
    Downloading/unpacking websockets
      Downloading websockets-2.7.tar.gz
      Running setup.py (path:/tmp/pip_build_xxxxx/websockets/setup.py) egg_info for package websockets
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/tmp/pip_build_xxxxx/websockets/setup.py", line 19, in <module>
            with open(os.path.join(root, 'README'), encoding='utf-8') as f:
        TypeError: 'encoding' is an invalid keyword argument for this function
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
    
      File "<string>", line 17, in <module>
    
      File "/tmp/pip_build_xxxxx/websockets/setup.py", line 19, in <module>
    
        with open(os.path.join(root, 'README'), encoding='utf-8') as f:

    TypeError: 'encoding' is an invalid keyword argument for this function

----------------------------

I haven't tried anything else yet, just thought I'd let you know.

**Comment by aaugustin** [comment]
Are you using a Python version websockets is compatible with?

**Comment by wh1tebeard** [comment]
Yes, but my system is set up for development of both Python2 and Python3 programs.
Looks like setup.py needs a shebang specifying python3, e.g.:
`#!/usr/bin/env python3`
and setuputils3 installed for python3 packages.

**Comment by wh1tebeard** [comment]
I only ended up adding the shebang, and it worked just fine!

However, if pip is invoking the default python interpreter and that interpreter is python2, downloading and invoking setup.py via
`sudo python3 setup.py install` 
is the easiest option and would not need the shebang at all.

**Comment by aaugustin** [comment]
It looks like you're installing packages at the system level. I suggest looking into virtualenv. It will better insulate you from all the ways distros break python and pip when they package them.
