### ISSUE TITLE
Error: The Future belongs to a different loop

### ISSUE THREAD

**Issue by JonahKr** [aaugustin/websockets#800]
Hey there 👋 
Let me describe my setup really quick.
There is a mqtt listener running at all times subscribed to certain topics.
In the Event of an message a function gets executed. (Async or "normal" doesn't matter)

Before the start of the mqtt client, i can create my websocket client and everything works perfectly fine.
The second i start it though, all websocket calls become impossible meaning that the tasks never end.

I assume this has something to do with the recv function and a loop behind it to detect new incoming messages...

```py
async def intent_handle(intent):
    logger.debug(await hass.ws.fetch_services())
    return EndSession("")
```
At the point where the message is called the first time, it freezes... If i exit the script, following error gets thrown:
```
[ERROR:2020-07-20 23:16:18,508] asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<WebSocketCommonProtocol.close_connection() done, defined at C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websockets\protocol.py:1153> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x03E20280>()]> cb=[gather.<locals>._done_callback() at C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py:751]>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0388D2B0>
Traceback (most recent call last):
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 508, in _check_closed       
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[ERROR:2020-07-20 23:16:18,513] asyncio: Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<WebSocketCommonProtocol.close_connection() running at C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websockets\protocol.py:1179> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x03BC00A0>()]> cb=[gather.<locals>._done_callback() at C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py:751]>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x03E50628>
Traceback (most recent call last):
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websockets\protocol.py", line 1206, in close_connection
    if await self.wait_for_connection_lost():
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\site-packages\websockets\protocol.py", line 1226, in wait_for_connection_lost
    await asyncio.wait_for(
  File "C:\Users\jonah\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 448, in wait_for
    loop = events.get_running_loop()
RuntimeError: no running event loop
```

That means somehow, it isn't able to fetch the future as far as i understand it.

Thanks in advance

**Comment by aaugustin** [comment]
I need a bit more info to give you the best answer:

- does your app use thread in any fashion? (created by your code or by a library you're using)
- can you confirm the same event loop you use to start the websocket connection is used throughout its lifetime?
- can you try ensuring that connections are completely closed (i.e. `await ws.wait_closed()`) before they're garbage collected?

Please note that the first stack trace is entirely in asyncio. websockets isn't involved at any point there. I'd like to tackle this one first: as long as we don't have the asyncio layer under control, there's little chance we can make sensible decisions in the websockets layer.

**Comment by aaugustin** [comment]
Closing, since there's no follow up. I have two theories here:

- Starting the mqtt client starts a new event loop, or otherwise messes up with event loops. In that case, calling `connect` after starting the mqtt client will make websockets use the right event loop.
- The websocket connection is created in a thread and used in another thread. Similar answer - make sure you call `connect` in the thread where you'll use it, after creating an event loop for that thread.

As a last resort, the `loop` argument to `connect` may help, but I wouldn't recommend it unless you understand extremely  well what's happening.
