### ISSUE TITLE
Cannot add brackets to IPv6 address

### ISSUE THREAD

**Issue by TomisderMeister** [aaugustin/websockets#802]
Hello Everyone,
I tried to set brackets after a full ipv6 address, because otherwise the server not accept my connection.
**Is there anyway how this is possible with the given arguments?**
As i understand the source code message get lost after parsing the uri.
I fixed the problem temporaly by editing **client.py** in line **253** and adding the brackets manually.
from:
`request_headers["Host"] = f"{wsuri.host}:{wsuri.port}"`
to:
`request_headers["Host"] = f"[{wsuri.host}]:{wsuri.port}"`
After this everything works fine.
If you could provide me with a more accurate solution, I would be really glad.

**Comment by aaugustin** [comment]
The question is whether this is a bug in websockets or a bug in the server you're connecting to. What server is this?

**Comment by TomisderMeister** [comment]
Its a implemented Server, i don`t know the implementation of it only the protocol.
I only checked with a quick googlesearch, but on [wikipedia]( https://en.wikipedia.org/wiki/IPv6_address) there is a part claiming that urls should have brackets (or could I´m not quite sure).
I need to double check it with the IPv6 spezification to ensure if its a bug of the websocket lib or a bug on the server site.

**Comment by aaugustin** [comment]
So it seems that websockets has the same bug Firefox had... 20 years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=45891

**Comment by TomisderMeister** [comment]
Oh okay. I will try to trace down deeper, where the brackets get lost. I think by parsing to URI and back. Quick solution would be check for IPv6 and add then the brackets, but it sounds for me like a quickhack.

**Comment by aaugustin** [comment]
This is the proper solution. Excerpt from the bug I linked to:

> Note in particular the "Host" header.  RFC 2617 (HTTP) defines the syntax of the
> "Host" header as:
>
> `      Host = "Host" ":" host [ ":" port ] ; Section 3.2.2`
>
> Section 3.2.2 gives the grammar of the http URL.  Therefore, for IPv6 literal
> addresses the Host header needs to follow the RFC 2732 grammar for "host", just
> as with URLs:
>
> `      host          = hostname | IPv4address | IPv6reference`
> `      IPv6reference = "[" IPv6address "]"`

So we have three cases for the `host` variable in websockets: hostname, IPv4 address, IPv6 address, and in the third case we have to turn it into an IPv6 reference by adding brackets.

**Comment by aaugustin** [comment]
Thanks for the bug report! That was a good catch.

**Comment by TomisderMeister** [comment]
Thank you very much for this great libary and the quick response. I was really impressed by the quick reply.
