### ISSUE TITLE
How to force close?

### ISSUE THREAD

**Issue by yunyuyuan** [aaugustin/websockets#805]
How to force close a websocket that locked by `await`

**Comment by aaugustin** [comment]
I'm sorry, there isn't enough detail in your question for me to understand it.

I believe you're asking how you can run `await websocket.close()` while you're already running `await websocket.recv()`.

If so, your question is really "how can a run two things in parallel with asyncio" and the anwser is probably "run a task". Getting familiar with asyncio should help.
