### ISSUE TITLE
The websocket send sometimes report "connection closed" when using reuse_port

### ISSUE THREAD

**Issue by jiangjianping** [aaugustin/websockets#811]
Running websocket servers in CentOS 7, kernal version is  3.10.0. I hope to support large connections in one server.
  
There is no problem to use one instance for ssl port 443. When use two more instances in the same port with reuse_port=True. After running about two minutes, the websocket may report "connection closed" (code=1000, no reason) when send the message to client. At that time, from client side, the websocket connection is still alive with normal ping/pong exchange.

**Comment by etkaar** [comment]
I may be absolutely wrong since you say this only happens when you use two instances, but could the reason be that at least one client remains silent and does not send/receive packages? You can periodically ping clients to prevent a timeout:

```
try:
	# Ping the client and wait a few seconds
	await asyncio.wait_for((await websocket.ping()), timeout=10)
# We didn't receive a pong, so connection seems to be broken
except asyncio.TimeoutError:
	print('Client has lost the connection.')
```

**Comment by jiangjianping** [comment]
@etkaar 
thanks, I will try. I should make my testing environment clearly: There are two server instances listening on the same ssl port 443 with reuse_port enabled. I test with one client. This client sent the ping every 20s and always got the pong response. At the same time, the server got  the message from other palce and forward the message to client with websocket.send.  When server instance is one (That's to say, no server instance sharing the listening port), no any problem occurred; When running two or more server instances sharing the listening port,   the  websocket.send worked well about two minutes, then throws the exception with "connection closed, code 1000, no reason" (ensure_open throw it).

**Comment by jiangjianping** [comment]
@aaugustin,

I wonder whether reuse_port is still support now?

**Comment by aaugustin** [comment]
I don't really understand the question; here's the help I can offer:

- The TCP/TLS layer is entirely managed by asyncio. If asyncio supports reuse_port, then websocket should also support it.
- The keepalive ping is designed to keep the connection alive in the presence of intermediaries (typically proxies) with short timeouts.

**Comment by etkaar** [comment]
@aaugustin Isn't the keepalive ping also for web applications where a user may be absent for hours, but the WebSocket needs to be still able to push notifications to the client?

**Comment by aaugustin** [comment]
Yes, that's exactly what I'm saying. What causes a TCP connection to drop?

- Either an endpoint closes the connection, which isn't the scenario we're talking about here;
- Or some equipment in the middle decides the connection is no longer useful, often based on a timeout, and terminates it. The keepalive ping helps avoiding this.

**Comment by etkaar** [comment]
I see – so I understood it correctly, thanks! :)
