### ISSUE TITLE
Coroutine execution is skipped after message reception

### ISSUE THREAD

**Issue by t0xic0der** [aaugustin/websockets#812]
I am trying to build a message service where the message is in the form of a JSON document with `username` and other relevant details. In order to check stuff and print selectively, I need to be able to parse a string back to a dictionary. But it seems to be skipped completely and execution terminates.

Here is the coroutine.

```python
async def consumer_handler(websocket, username, chatroom):
    async for recvdata in websocket:
        data = json.loads(recvdata)
        print(data)
```

Any help is appreciated.

**Comment by aaugustin** [comment]
Welcome to debugging asyncio programs ;-)

This isn't a complete example that I can run, so it's much harder for me than for you to debug it. I don't see anything obviously wrong in this piece of code.

Turning on debug logs may help: https://websockets.readthedocs.io/en/stable/cheatsheet.html#debugging

**Comment by aaugustin** [comment]
Tasks exiting with an exception are a common issue. https://docs.python.org/3/library/asyncio-dev.html may help.
