### ISSUE TITLE
How can i manually check the handshake for the server?

### ISSUE THREAD

**Issue by Directory** [aaugustin/websockets#814]
For my application the client is public and i want to obfuscate the handshake further and increase security. This is how I'm serving my application.
```py
async def connection_handler(connection: websockets.server.WebSocketServerProtocol, path: str):
    pass

start_server = websockets.serve(connection_handler, '0.0.0.0', 1234)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
The problem is `websockets.serve()` is too good. It automates everything. Any client can connect and will finish the handshake and establish the connection before it can be manually checked. I want to be able to check the http request and have the library verify that its a proper handshake request, but have custom code to check stuff like headers, url paths, etc and then decide if it should finish the handshake and continue on or send back a 403 response (or just ungracefully close the low level tcp socket underneath without response, idrc at that point since if this would ever happen then its not my real client and it can go fuck itself).

**Comment by aaugustin** [comment]
Look at the `process_request` hook, which is designed for this purpose.

https://websockets.readthedocs.io/en/stable/api.html#websockets.server.WebSocketServerProtocol.process_request

**Comment by Directory** [comment]
can you provide a server example of this from the code i sent? idk where im supposed to do this since `connection_handler()` is ran after the connection is established.
