### ISSUE TITLE
RE: Running Two Linux SBC Boards w/ WebSockets and Python

### ISSUE THREAD

**Issue by silver2row** [aaugustin/websockets#819]
Hello,

This is sounding odd but here it goes. How can I reach the outside of the board, my Linux SBC, w/ WebSockets online? Is it possible?

I am finding myself looking through articles online and finding ideas only. No stern facts so far...

So, I run this from your scripts online on readthedocs.io:

    #!/usr/bin/env python3

    # WS server that sends messages at random intervals

    import asyncio
    import datetime
    import random
    import websockets

    async def time(websocket, path):
        while True:
            now = datetime.datetime.utcnow().isoformat() + "Z"
            await websocket.send(now)
            await asyncio.sleep(random.random() * 3)

    start_server = websockets.serve(time, "0.0.0.0", 5678)

    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()

...

Then, I run the .html page found on the readthedocs.io page which can be found below:

    <!DOCTYPE html>
    <html>
        <head>
            <title>WebSocket demo</title>
        </head>
        <body>
            <script>
                var ws = new WebSocket("ws://0.0.0.0:5678/"),
                    messages = document.createElement('ul');
                ws.onmessage = function (event) {
                    var messages = document.getElementsByTagName('ul')[0],
                        message = document.createElement('li'),
                        content = document.createTextNode(event.data);
                    message.appendChild(content);
                    messages.appendChild(message);
                };
                document.body.appendChild(messages);
            </script>
        </body>
    </html>

I think my first issue is this idea: 

    I am running the first set of source onboard the Linux SBC while running the second HTML page online via my dev. desktop.

I will keep learning more while I try to consume as much of WebSockets as one man can handle.

Please type back any type of guidance you have on this concern.

Seth

**Comment by silver2row** [comment]
Hello Again,

About running (opening) the HTML page only via the dev. desktop, I have opened the HTML page w/ the other Linux SBC while having the first .py file running. I know there is something I am missing.

...

When you have time, please do reply. I sure could use some education on this project.

Seth

**Comment by lgrahl** [comment]
You cannot connect to `0.0.0.0`. It's likely `localhost` you're looking for.
