### ISSUE TITLE
Retrieve cookies ?

### ISSUE THREAD

**Issue by LordKBX** [aaugustin/websockets#82]
would it be possible to retrieve the cookies sent by the browser at the beginning of the connection?

**Comment by aaugustin** [comment]
Yes, although the docs don't surface this information as clearly as they could.

From http://websockets.readthedocs.org/en/stable/api.html?highlight=request_headers#websockets.protocol.WebSocketCommonProtocol:

> Once the handshake is complete, request and response HTTP headers are available:
> * as a MIME Message in the request_headers and response_headers attributes
> * as an iterable of (name, value) pairs in the raw_request_headers and raw_response_headers attributes

All you need to do is to feed `websocket.request_headers.get('Cookies')` to th]e cookie parser provided in the standard library.

**Comment by LordKBX** [comment]
Cookies without s works ^^

**Comment by aaugustin** [comment]
Great. If you have a suggestion to improve the documentation, let me know and I'll reopen this ticket.
