### ISSUE TITLE
Managing Stale Websocket Connections

### ISSUE THREAD

**Issue by kmiklas** [aaugustin/websockets#821]
_Note: Also documented on SO here:_
https://stackoverflow.com/questions/63639414/how-to-manage-stale-websocket-connections]

Using Python Websockets [1] to manage a set of server-side websocket connections from browser. They must be registered and maintained.

Problem: when User disconnects a stale connection remains present in the registry. Also, if user refreshes browser (1, 2, 17... or n times), or a reconnect script is present, more invalid connections are registered. This creates a big registry of stale connections.

The docs address this issue as follows:

> As shown in the synchronization example above, if you need to maintain
> a list of currently connected clients, you must register them when
> they connect and unregister them when they disconnect.

How are stale connections properly identified and removed? Is some sort of ping/pong scheme required?

I did find the code in [2], but it goes back to 2018. Is this obsolete, or has this issue since been addressed?

Ref:

1. https://websockets.readthedocs.io/en/stable/intro.html
2. https://github.com/aaugustin/websockets/issues/414

**Comment by aaugustin** [comment]
The example here (https://websockets.readthedocs.io/en/stable/intro.html#registration) removes stale connections:

```python
    finally:
        # Unregister.
        connected.remove(websocket)    
```
