### ISSUE TITLE
Linux error: socket.accept() out of system resource

### ISSUE THREAD

**Issue by steveseguin** [aaugustin/websockets#822]
Not sure where else to ask for help on this, but I'm using "websockets" as part of a simple WSS server.  During the peak hours of connections though, the python websocket script starts to Thrash like crazy, throwing this error like crazy:
```
17:30:14 app python3[1775]:   File "/usr/lib/python3.6/socket.py", line 205, in accept
17:30:14 app python3[1775]: OSError: [Errno 24] Too many open files
17:30:14 app python3[1775]: socket.accept() out of system resource
17:30:14 app python3[1775]: socket: <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 443)>
17:30:14 app python3[1775]: Traceback (most recent call last):
17:30:14 app python3[1775]:   File "/usr/lib/python3.6/asyncio/selector_events.py", line 168, in _accept_connection
17:30:14 app python3[1775]:     conn, addr = sock.accept()
```

Restarting the script clears the error, but a few days later it kicks up again, and quickly just starts to slow to a crawl, before not responding at all.

**ulimit -n** is set to around 65000; up from 4096, but the issue still occurs.

Can websockets handle a lot of connections?  Core CPU usage is about 5% before it just jumps to 25% when the trashing starts.

Any ideas would be welcomed.

**Comment by aaugustin** [comment]
Yes, I have successfully managed > 10k connections with a single process.

You would probably get exactly the same problem with TCP connections managed by asyncio, so I'd say this is a lower-level problem than what websockets is concerned with. I don't know the solution.

**Comment by steveseguin** [comment]
Thank you.  That does help.    Great project by the way -- it does work really well.

**Comment by aaugustin** [comment]
If you figure it out, it would be worth adding the solution to the documentation.

**Comment by aaugustin** [comment]
Since there hasn't been any activity here in three months, I'm going to close this issue.

**Comment by ahmad88me** [comment]
I am facing a similar issue. I post the source code as a reference in case someone wants to investigate this. 
```
import asyncio
import websockets
import sys
from multiprocessing import Lock

lock = Lock()

ws_watcher_port = 8764
ws_redirect_addr = "ws://localhost:8763"
redirect_connection = None

async def consumer_handler(websocket, path):
    global redirect_connection
    global lock
    redirect_connection = await websockets.connect(ws_redirect_addr)
    try:
        async for message in websocket:
            await consumer(websocket, message)
    except Exception as e:
        print("consumer_handler> Disconnect <%s>" % str(e))


async def consumer(websocket, message):
    global redirect_connection
    global lock
    print("consumer> %s" % message)
    reply = message
    try:
        await redirect_connection.send(reply)
    except Exception as e:
        print("consumer> Except: %s" % str(e))
        redirect_connection = await websockets.connect(ws_redirect_addr)
        await redirect_connection.send(reply)


if __name__ == "__main__":
    if len(sys.argv) >= 2:
        ws_watcher_port = int(sys.argv[1])
    if len(sys.argv) >= 3:
        ws_redirect_addr = sys.argv[2]

    start_server = websockets.serve(consumer_handler, "0.0.0.0", ws_watcher_port)

    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()
```

**Comment by aaugustin** [comment]
The source code won't help here. You must configure your OS to allow a single process to open enough file descriptors.

You would have the same issue with any other library if you opened the same number of connections on the same system.
