### ISSUE TITLE
Is there any way to quickly switch monitoring when switching WiFi

### ISSUE THREAD

**Issue by Wy2926** [aaugustin/websockets#827]
The current idea is to shut down the current process and restart it

**Comment by Wy2926** [comment]
Is there a convenient and quick way without shutting down the current process

**Comment by aaugustin** [comment]
I'm having a hard time making the connection to websockets. Either there a lot of missing information to convert this into an actionable feature request. Or you posted this to the wrong repo altogether.

If you'd like help, please provide sample code and a sequence of steps to reproduce what you're doing, explain what websockets currently does (or doesn't do), and what you would expect instead.
