### ISSUE TITLE
websocket.send() to specific uri

### ISSUE THREAD

**Issue by Kvg87** [aaugustin/websockets#828]
I have a websockets client running which is connected to multiple uri's. However I want to send a message to a specific uri, and not have to wait for an incoming message from that uri. How can I do this.

**Comment by Kvg87** [comment]
`import asyncio
import websockets

connections = set()
connections.add('wss://api.foo.com:8765')
connections.add('wss://api.bar.com:8765'))
connections.add('wss://api.foobar.com:8765'))

async def handle_socket(uri, ):
    async with websockets.connect(uri) as websocket:
        async for message in websocket:
            print(message)

async def handler():
    await asyncio.wait([handle_socket(uri) for uri in connections])

asyncio.get_event_loop().run_until_complete(handler())`

**Comment by Kvg87** [comment]
My code looks like the above..

**Comment by lgrahl** [comment]
```python
async def handle_socket(uri):
    async with websockets.connect(uri) as websocket:
        await websocket.send(foo)
        ...
```

**Comment by Kvg87** [comment]
I dont think this is what I need, I probably explained myself incorrectly. 

I want to respond to the message from a certain URI by sending messages to the other URI's. However I can only get it to work by waiting for messages from the other URIs like so:

`if uri ==  'wss://api.bar.com:8765'
`websocket.send(foo)

**Comment by lgrahl** [comment]
Alright, I see. I'd suggest posting that question on stackoverflow. The issue tracker here is rather for issues with the lib than general questions on how to do X.

**Comment by Kvg87** [comment]
Ah ok, cool. Thks!
