### ISSUE TITLE
websocket.send() doesn't flush on Windows

### ISSUE THREAD

**Issue by Weihnachtshase** [aaugustin/websockets#830]
Hi!

I have written a simple example which appears to not flush the websocket.send() method on Windows (2004). 
Instead all messages are sent as soon as the websocket.close() is called (except for the very first message which is sent immediately). Using WSL 2 and Ubuntu the messages are sent and received immediately.

Furthermore if I wait more than 20 seconds before exiting (Ctrl+C) a client, I get "Future exception was never retrieved" which is a ConnectionClosedOK Exception. I assume this has something to do with the ping-timeout, but this is set to None in the serve method, so I don't understand how this error is actually coming up.
Besides that I actually try to catch the ConnectionClosedOK Exception but somehow it is not caught, the second thing I don't understand.

I don't know if this is actually a bug in websockets or in my code/setup or maybe even in asyncio. Just wanted to share with somebody who can have a look at it.

My python version is 3.8.5 on Windows and 3.8.2 on Ubuntu(WSL)

Thank you very much in advance.

[example.zip](https://github.com/aaugustin/websockets/files/5196154/example.zip)

**Comment by aaugustin** [comment]
There's a slight difficulty here — I don't have (easy) access to a Windows machine to reproduce this :-(

**Comment by Weihnachtshase** [comment]
Only the flushing part appears on Windows.
The problem(s) concerning the ConnectionClosedOk Exception also appear on Ubuntu. At least on my machine.

**Comment by Joos-OST** [comment]
I'm currently experiencing the same behaviour on Windows. @Weihnachtshase, have you found a solution?

**Comment by Weihnachtshase** [comment]
Since my client was only for testing, I switched to WSL and the Ubuntu console where it is working for me

**Comment by aaugustin** [comment]
I took a look at this. I didn't find any explicit flushing in websockets so I suspect this is a Windows / asyncio bug.

If you could put together a minimal reproduction with just a TCP server in asyncio, that would prove it's an asyncio bug.

I don't know what I can do here, so I'm going to close the ticket, but I'll reopen if there's new information!

Thanks for taking the time to report the issue and put together a reproducible example.
