### ISSUE TITLE
How to keep a long live connection with websockets?

### ISSUE THREAD

**Issue by silent790** [aaugustin/websockets#833]
I am a newcomer to websocket and I built a client to receive from a websocket,

the code works well and report error like this after 30 seconds:
`websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason`

what can I do to keep the connection with python code?

**Comment by VacantHusky** [comment]
add ping_timeout=None
```python
async with websockets.connect("ws://127.0.0.1:53392/", ping_timeout=None) as websocket:
    # do something
```

**Comment by silent790** [comment]
Well, I add ping_timeout=None but it still report error after 30 seconds:
'websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason'

Can websockets add something like heartbeat report?
If so, would you please show me how can I comply it？

**Comment by lgrahl** [comment]
Then you're probably connected through a proxy: https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean

Feel free to reopen if that's not the case.

**Comment by silent790** [comment]
ReopenIssueInput!

**Comment by silent790** [comment]
Would you please help me to fix the problem below, I am completely clueless about this : 

HTTP load balancers or proxies that aren’t configured for long-lived connections may terminate connections after a short amount of time, usually 30 seconds.

**Comment by lgrahl** [comment]
Well, the question is: Are you using a proxy? If so, it's unlikely we will be able to help you (and, frankly, it's not an issue with this library). If not, you will need to find out who triggers the disconnect.
