### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by lgrahl** [aaugustin/websockets#835]
@aaugustin Can you set up templates for the issue tracker, so we have a general guideline on what to do (e.g. read the FAQ, ensure minimal knowledge of asyncio before going ahead, ...) before opening an issue?

https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by aaugustin** [comment]
Yes, we can do this, but let's make sure we keep bureaucracy to a minimum. I'm in favor of helping people find the information they need without having to wait for us to answer. I'm not in favor of a situation where every issue ends up containing 20 lines of template and 1 line of actual content somewhere in the middle of this template. Atom has an interesting hack to avoid this problem: they put instructions in HTML comments: https://github.com/atom/atom/issues/new?template=feature_request.md

**Comment by aaugustin** [comment]
I don't feel super inspired to do this myself. I'll happily configure a template suggested by someone else.
