### ISSUE TITLE
Run the sync example, got an error 'connection closed abnormally' every time a client closes the browser tab

### ISSUE THREAD

**Issue by Areso** [aaugustin/websockets#837]
Running this https://websockets.readthedocs.io/en/stable/intro.html#synchronization-example
Python3 --version 
3.7.6
Got
```
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
every time when a client closes a browser tab with the example

**Comment by aaugustin** [comment]
See https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean
