### ISSUE TITLE
How to use Porocess in websockets?

### ISSUE THREAD

**Issue by simeon49** [aaugustin/websockets#843]
In my application scenario, each client needs to connect to the server to execute python code in a relatively pure and independent process.
 
E.g: client A connects to the server, and a process (pid=1234) will be started and exec every code client A send to it, after execution, returns the execution result to A.

Fake code blow:
```Python
import asyncio
import websockets
from multiprocessing import Process

def handler(websocket, process_self):
    try:
         for code in websocket:
            exec(code)
            /* some other code here */
            websockets.send('exec result')
    finally:
        process_self.kill()

def ws_connect_handler(websocket, path):
    p = Process(target=handler, args=(websocket, process_self))
    p.start()

start_server = websockets.serve(ws_connect_handler, BIND_IP, BIND_PORT)
```
But "Porcess" can not use like this, What should I do?

**Comment by lgrahl** [comment]
This is more of an asyncio question. See the example for https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor
