### ISSUE TITLE
Replace watch badge with stargazer badge in documentation sidebar

### ISSUE THREAD

**Issue by septatrix** [aaugustin/websockets#844]
Most projects show the amount of stars the project has instead of the amount of watchers. While neither is a reliable metric for a projects quality I often find myself using the package which has more stars when they are otherwise similar.

Therefore I was almost not going to use this library as it seemed to only have a very small community when I opened the documentation and saw the low number there. Replacing the watcher badge with a stargazer one may make people more confident to use this and is more in line with other packages which do the same.

**Comment by aaugustin** [comment]
Thanks for the suggestion! Indeed the Stars button is shown first on https://ghbtns.com/ and therefore I assume it's the most popular.

**Comment by aaugustin** [comment]
Unfortunately, docs don't build, due to https://github.com/pypa/pip/issues/9155.
