### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by jondequinor** [aaugustin/websockets#847]
Latest release, `8.1`, is not semver. `8.0.2` is.

> A normal version number MUST take the form X.Y.Z ([SemVer](https://semver.org/))

If you don't follow semantic versioning, that's okay, just close the issue. It obviously does not affect tools like `pip`, only self-made build tools that relies on YML which parses `8.1` as a float instead of a string.

**Comment by aaugustin** [comment]
SemVer is overkill for websockets. I apply a simplified version of SemVer with only major and minor versions; no patch versions.

If a tool cannot parse `8.1`, it cannot parse `3.9`, which is a version of Python, or`3.2` which is a version of Django. I feel like I'm in good company.

**Comment by aaugustin** [comment]
Another way to look at this is -- I don't feel the urge to add a .0 after every version of websockets. Keep things simple!

**Comment by aaugustin** [comment]
Finally -- YAML 😱
