### ISSUE TITLE
UTF-8 validate

### ISSUE THREAD

**Issue by Ksengine** [aaugustin/websockets#848]
**question :** what is the utf-8 validate method of this library?

**Comment by aaugustin** [comment]
https://github.com/aaugustin/websockets/blob/c39268c4867e41d11c20f7859583761d52a04012/src/websockets/protocol.py#L936-L937

**Comment by Ksengine** [comment]
some packages like ws4py and gvent-websocket uses different utf-8 validators 
what are the differences. It looks like your method is good.

**Comment by aaugustin** [comment]
Of course my method is good ;-) I haven't look at what these other projects do.

**Comment by Ksengine** [comment]
Look at https://github.com/Lawouach/WebSocket-for-Python/blob/master/ws4py/utf8validator.py
