### ISSUE TITLE
How to get multiple message send by ws server one after another.

### ISSUE THREAD

**Issue by Bryan-u-2** [aaugustin/websockets#850]
Currently by using websockets i only receive the first message i dont receive other message which are send by the ws server after sometime. How do i get that?

**Comment by aaugustin** [comment]
With the limited amount of info you provided, this looks like the first question of the FAQ: https://websockets.readthedocs.io/en/stable/faq.html

**Comment by Bryan-u-2** [comment]
Am sorry but am new to websocket.
The browser sends a json file to ws server,then the browser receives 3 json which send one by one by ws server.
I want to make a client that can work like the browser.

**Comment by aaugustin** [comment]
You're also new to asyncio and that's the bigger concern here.

The answer to your question is also in the FAQ; look at "How do I do two things in parallel?"

Please do a little bit of homework before asking for support.
