### ISSUE TITLE
How to pass argument to the subclass of WebSocketServerProtocol

### ISSUE THREAD

**Issue by bwcc60** [aaugustin/websockets#851]
The document says, "The create_protocol parameter allows customizing the Protocol that manages the connection. It should be a callable or class accepting the same arguments as WebSocketServerProtocol and returning an instance of WebSocketServerProtocol or a subclass. It defaults to WebSocketServerProtocol."

Would you please supply some example on this?

I created the subclass of WebSocketServerPrototocol, and supplied my version of async def handler(self), it works. But when I plan to add extra argument to the subclass, I meet the issue to create the protocol

class MyWSSProtocol(websockets.WebSocketServerProtocol):

     def __init__(self, mgr: ClassA):
         self.m_mgr: ClassA = mgr
    
     def __call__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)

    async def handler(self):
         ......

later on 
   mycallalbe: MyWSSProtocol = MyWSSProtocol(mgr)
   start_server = websockets.serve(hello, '127.0.0.1', 28766, create_protocol=mycallalbe)  

Then I found at proactor_evetns.py

        def loop(f=None):
            try:
                if f is not None:
                    conn, addr = f.result()
                    if self._debug:
                        logger.debug("%r got a new connection from %r: %r",
                                     server, addr, conn)
                    **protocol = protocol_factory()   **# this can not create the protocol****
                    if sslcontext is not None:
                        self._make_ssl_transport(
                            conn, protocol, sslcontext, server_side=True,
                            extra={'peername': addr}, server=server,
                            ssl_handshake_timeout=ssl_handshake_timeout)

Would you please supply some example to show how to pass extra argument to subclass of WebSocketServerProtocol?

thanks,
Wei

**Comment by aaugustin** [comment]
This should be in the FAQ but it isn't yet!

Using `create_protocol=functools.partial(MyWSSProtocol, mgr)` would be the simplest solution here.

You don't need to define `__call__` in `MyWSSProtocol`.

**Comment by bwcc60** [comment]
Thanks a lot.  

the __init__() has to change a little bit. Now everything works.

```
   
class MyWSSProtocol(websockets.WebSocketServerProtocol):
 def __init__(self, mgr: ClassA, *args, **kwargs):
        self.m_mgr: ClassA = mgr
        super().__init__(*args, **kwargs)


create_protocol_my = functools.partial(MyWSSProtocol, mgr)
start_server = websockets.serve(hello, '127.0.0.1', 28766, create_protocol=create_protocol_my)
```
