### ISSUE TITLE
Register a callback for when a connection is openend

### ISSUE THREAD

**Issue by FFY00** [aaugustin/websockets#852]
Hey, is it possible to register a callback for when a websocket connection is opened. I have a websocket server and want to do some initial set up when a new connection is opened. Having had a look at the documentation, this does not seem possible right now, is that the case? If so, would you perhaps consider adding this?

**Comment by aaugustin** [comment]
What about this?

```python
def handler(ws, path):
    call_your_callback_here()
   do_everything_else_here()
```
