### ISSUE TITLE
What is the best practice to send data from a producer to clients?

### ISSUE THREAD

**Issue by mrdc** [aaugustin/websockets#853]
Hello,

Sorry for a newbie question - I've spent 1,5 days reading websockets docs, FAQ, googling and thinking how to do it - finally there is some code and I'm sure there is a better way to do it: to pass data from a function to websockets to send to clients.
The problem with the code that I can't remove `return('Producer')` from `async def producer()` - websocket clients constantly receive the same return message from the producer - producer function should return something otherwise `await `complains:
```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\websockets\server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "n:/Python/WebSockets/ws.py", line 30, in producer_handler
    await websocket.send(message)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\websockets\protocol.py", line 651, in send
    raise TypeError("data must be bytes, str, or iterable")
TypeError: data must be bytes, str, or iterable 
```

My code:
```python
# !/usr/bin/env python

import asyncio
import websockets

send_data = False
msg = ''

async def producer():
    global send_data
    if send_data:
        print("Sending new data...")
        send_data = False
        return(msg)
    await asyncio.sleep(1)
    return('Producer')

async def producer_handler(websocket, path):
    while True:
        message = await producer()
        await websocket.send(message)

# This function is called via a callback
def my_function():
    global send_data
    global msg
    # ...
    # here we have code to write data in DBs, etc
    # ...
    # We also need to send some data to WebSocket Clients:
    msg = processed_data
    send_data = True
    # There is no return in this function

ws_server = websockets.serve(producer_handler, "127.0.0.1", 8765)
asyncio.get_event_loop().run_until_complete(ws_server)
asyncio.get_event_loop().run_forever()
```

**Comment by aaugustin** [comment]
You have two problems here:

1. Your code doesn't work when more than one client is connected. Look at https://websockets.readthedocs.io/en/stable/intro.html#registration for broadcasting a message to all connected clients.

2. You need a way to schedule a coroutine from a regular function. Take a look at `call_soon` or more likely `call_soon_threadsafe` — you didn't mention it but I suspect `my_function()` runs in another thread (or else you're in trouble because you're blocking the event loop).

```python

connected = set()

async def handler(websocket, path):
    # Register.
    connected.add(websocket)
    try:
        async for msg in websocket:
            pass
    finally:
        # Unregister.
        connected.remove(websocket)

async def broadcast_msg(msg):
    await asyncio.wait([ws.send(msg) for ws in connected])

def my_function():
    asyncio.get_event_loop().call_soon_threadsafe(broadcast_msg, msg)
```

**Comment by aaugustin** [comment]
(didn't try that code, but shouldn't be too far from a working solution)

**Comment by mrdc** [comment]
@aaugustin 
Thanks! Works fine. I've just added a check for connected clients and everything works.
