### ISSUE TITLE
clever way to turn connect/disconnect the websockets during specific times

### ISSUE THREAD

**Issue by vgoklani** [aaugustin/websockets#856]
Hey there,

Is it possible to connect the websockets from (say) M-F 9am-5pm, and then disconnect when outside of that time range?

It sounds like you would need to jump through hoops with callbacks? 

Thanks!

**Comment by aaugustin** [comment]
Hello, as far as websockets is concerned, assuming you're talking about a client, run `client = await websockets.connect(...)` at 9 am and `await client.close()` at 5pm. Probably you need to handle reconnecting in case the connection drops during the business day.

**Comment by aaugustin** [comment]
Another way to look at this -- try to do this with a TCP connection managed by asyncio, and then you should be able to do something similar with websockets. If you can't do it with asyncio, well, I'm going to consider it a Python / asyncio issue rather than a websockets issue.
