### ISSUE TITLE
Connection cleanup blocks websockets server

### ISSUE THREAD

**Issue by neon-ninja** [aaugustin/websockets#857]
Hi,

I've been doing some stress testing using https://github.com/aaugustin/websockets/blob/master/example/counter.py and wsstat (https://github.com/Fitblip/wsstat/) - a tool which uses this library, by the way. When I run wsstat against this server, the first run works fine. Once I quit wsstat, a stream of errors about disconnected connections (`websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason`) is generated by the server. This exception handling seems to block, so that subsequent runs of wsstat hang until those exceptions are cleared.

Is there some way of preventing these exceptions generated from old connections from interfering with new connections?

Here is the exact `wsstat` command I'm running - ` wsstat -n 1000 ws://localhost:6789`

**Comment by aaugustin** [comment]
What operating system are you running these tests on?

**Comment by neon-ninja** [comment]
Ubuntu 18.04.5 LTS, Linux 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

websockets==8.1
wsstat==1.4.0

**Comment by aaugustin** [comment]
Thanks.

One more question - when you say "until these exceptions are cleared", do you mean "until output stops scrolling in your terminal, and there's quite a bit of output"?

If so, could you try adding:

```python
import logging
logging.basicConfig(level=logging.CRITICAL)
```

Then you shouldn't get any such output anymore; does the issue still happen?

I'm asking for this experiment in order to tell apart "Python cannot do anything else while writing to stdout" (I can't do anything about this) from "websockets is stuck somewhere".

**Comment by neon-ninja** [comment]
Yes. Adding this line reduces the connection wait time from 2m50.425s to 0m14.826s, which seems a lot more reasonable. Thanks for your help!

**Comment by aaugustin** [comment]
OK - I think this is the right order of magnitude given what `counter.py` does.

When a client disconnect, this is broadcasted to all other clients. With 1000 clients, this involves `sum(range(1000)) = 499500` messages`. Sending half-a-million messages in 15 seconds means over 30k messages per second, which isn't too shabby in Python.

Furthermore, `counter.py` is a simple example, not a robust one. It has no error handling: it broadcasts messages with `asyncio.wait([user.send(message) for user in USERS])`.

Broadcast a message to a thousand of users who all suddenly disconnected at the same time — your test script doesn't close connections — doesn't work too well.

I don't think websockets is at fault here, so I'm going to close the issue.

**Comment by aaugustin** [comment]
Modifying `counter.py` as follows:


And your test script as follows:

```python
#!/usr/bin/env python3

import asyncio
import websockets
from tqdm import tqdm
import sys

n = int(sys.argv[1])

URI = "ws://localhost:6789"

async def main():
    print("Connecting...")
    connections = [
        await websockets.connect(URI)
        for i in tqdm(range(n))
    ]
    print("Disonnecting...")
    [
        await connection.close()
        for connection in tqdm(connections)
    ]

asyncio.get_event_loop().run_until_complete(main())
```
