### ISSUE TITLE
TypeError: 'Lock' object is not iterable

### ISSUE THREAD

**Issue by calvinrobson** [aaugustin/websockets#858]
Hi David, 

Do you have a workout for the aforementioned issue?

I am trying to run some code for an asyncio ssh:

async def task(param):
    pdb.set_trace()
    async with netdev.create(**param) as ios:
        # Testing sending simple command
        out = await ios.send_command("show ip int br")
        print(out)

Thanks,
Calvin

**Comment by aaugustin** [comment]
I don't know what `netdev` is and I'm not seeing any reference to `websockets`. Did you file this issue against the wrong repository?
