### ISSUE TITLE
Is websocket.send() async? With a client who stops receiving / flushing the buffer (How to detect / control)

### ISSUE THREAD

**Issue by mortoray** [aaugustin/websockets#859]
I'm writing a simple loop that dispatches events to a logical "room" of several client connections. My code looks roughly like this now:

```
async def listen_queue():
	while True:
		room, qevent = await event_queue.get()
		for ws in rooms[room].values():
			await ws.send(encode_msg(qevent))
```

My question is how async `send`  is? Will the above loop block waiting to flush to a client?  And if not, how can I detect that a client has fallen behind?

**Comment by mortoray** [comment]
I experimented a bit with a slow client. It appears that eventually the server will disconnect it. This raises a ConnectionClosed event in the above `send` call. I didn't notice any significant slow-down of other connected clients.

**Comment by aaugustin** [comment]
`asyncio` has a send buffer, and the OS also has send buffers, which could be "async enough" for you use case — if you don't saturate the send buffers until the slow client gets disconnected.

If you want to be "more async":

```python
tasks = [
    asyncio.create_task(ws.send(encode_msg(qevent)))
    for ws in rooms[room].values()
]
# timeout ensures that a client who falls behind doesn't make everyone else stuck
done, pending = asyncio.wait(tasks, timeout=...)
# if pending isn't empty, perhaps you want to disconnect these clients,
# but it's slightly hard to get a reference to the underlying connection here :-/
```

**Comment by aaugustin** [comment]
You can control this with a shorter `ping_interval` & `ping_timeout` (default 20 seconds). This will disconnect unresponsive clients faster, reducing the likelihood of saturating send buffers and getting stuck waiting for them to flush.

**Comment by mortoray** [comment]
Does the 20s ping/timeout then mean it'll be up to 40s before a client is detected as not responding?

I do notice a slight reduction in throughput with a bad client, but I suspect this is due to allocating memory for the buffers somewhere.  I'm doing stress testing, so I suspect it'll never be this bad in production -- the ping will probably kick in long-before I saturate the buffers.

Perhaps related, or I can spawn a new question. If I do several `emit` calls without an intervening `async.wait / await` will the ordering of the messages be the order I called `emit`, or is it nondeterministic with all pending emit calls?

**Comment by aaugustin** [comment]
Yes, there could be up to 20 seconds delay until the next ping and then 20 seconds until the timeout, total 40 seconds.
