### ISSUE TITLE
Consider making websocket protocols context managers

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#86]
From https://github.com/aaugustin/websockets/issues/77#issuecomment-152921813

it would also be nice to use pythons context manager syntax to guarantee client code can be robust without any need for checking on their end.

something like this:

``` python
def echo_handler(websocket):
    with websocket as ws:
        # as long as the socket is open do your thing
        while True:
            message = yield from ws.recv()
            yield from ws.send(message)
```

it's not necessarily pretty (it took 3 indents to write anything useful), but it'll take some responsibility off a client.

---

I'm not sold on this approach yet but I think it's interesting and deserves its own ticket.

**Comment by aaugustin** [comment]
Upon further though, I think it's a rather obscure pattern as it does the opposite of what context managers usually do: hide errors on close instead of close on errors.

**Comment by SzieberthAdam** [comment]
Agree, the purpose of contextmanagers is to assure teardown/close.

Consider the example code of the documentation:
```
#!/usr/bin/env python

import asyncio
import websockets

@asyncio.coroutine
def hello():
    websocket = yield from websockets.connect('ws://localhost:8765/')

    name = input("What's your name? ")
    yield from websocket.send(name)
    print("> {}".format(name))

    greeting = yield from websocket.recv()
    print("< {}".format(greeting))

    yield from websocket.close()

asyncio.get_event_loop().run_until_complete(hello())
```

In Python 3.5+, with an [asyncronous context manager](https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with), it would look like this:

```
#!/usr/bin/env python

import asyncio
import websockets

async def hello():
    async with websockets.connect('ws://localhost:8765/') as websocket:

        name = input("What's your name? ")
        await websocket.send(name)
        print("> {}".format(name))
    
        greeting = await websocket.recv()
        print("< {}".format(greeting))

asyncio.get_event_loop().run_until_complete(hello())
```

This one seems nice and pythonic to me. It won't hide any errors but assures the drive of the `close()` coroutine with this trivial code addition:

```
class WebSocketClientProtocol(WebSocketCommonProtocol):

    ...

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        await self.close()

    ...
```

Unfortunately, the awesome 3.5+ syntax is invalid in previous versions. So maybe this is something to add in the future, perhaps in a separate new style async branch first.

**Comment by aaugustin** [comment]
Yes, this is the right semantic for a context manager.

We may be able to provide this right now by:

- defining a mixin with these methods in a separate module
- conditionnally importing it i.e.

    try:
        from .python35 import WebSocketProtocolContextManagerMixin
    except SyntaxError:  # or is it ImportError? to be confirmed
        WebSocketProtocolContextManagerMixin = object

**Comment by aaugustin** [comment]
A related question is: how to deal with Python 3.5 only syntax in docs? See also #88.

**Comment by SzieberthAdam** [comment]
I opened a branch for this. I missed in the first place that we are unable to put `proto.connect()` into a context manager instantly since it is not a regular function which returns the protocol, but a coro. So the example code had to be modified like this:

```
async def hello():
    websocket = await websockets.connect('ws://localhost:8765/')
    async with websocket:

        name = input("What's your name? ")
        await websocket.send(name)
        print("> {}".format(name))

        greeting = await websocket.recv()
        print("< {}".format(greeting))
```

**Comment by aaugustin** [comment]
Hmm. That's annoying.

I suppose you could do `async with (await websockets.connect(...))` but that's rather obscure.

I'll think about it.

**Comment by gsw945** [comment]
I want to watch the log of my program from server at web browser, but i dont't konw how to implement it.
I want to use _`websockets`_ as the  _`logger.addHandler`_'s parameter for _`logging`_ module.
such as following example code:
```
import asyncio
import websockets
import logging

@asyncio.coroutine
def func(websocket, path):
    recv_data = yield from websocket.recv()
    yield from websocket.send("some data")

start_server = websockets.serve(func, '127.0.0.1', 12345)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()

logger = logging.getLogger('mylogger')  
logger.setLevel(logging.DEBUG)
# logger.addHandler(logging.StreamHandler())
logger.addHandler(?) #how to set ?
logger.warning('test data ^_^')
```
Who can help me? thank you very much.

**Comment by aaugustin** [comment]
@gsw945 Not only is this unrelated to this issue, but it's unclear to me that it's related to websockets at all. It looks a generic question about Python logging. In any case, please don't spam unrelated issues. Thanks.

**Comment by SzieberthAdam** [comment]
@gsw945 Althoug your question is offtopic, here are some hints:
1. You should configure logging before run_forever().
2. What you want is a logging handler similar to `logging.handlers.SocketHandler`. Check its source code. You may be able to wrtite a similar handler for websocket based on that. You may need to get familiar how this library (and logging, asyncio) works. 

Next time please at least start a new issue!
Good luck!

**Comment by gsw945** [comment]
@aaugustin , @SzieberthAdam  Thank you for your guidance, this is the first time I'm here to ask questions, I will pay attention to the future,

**Comment by SzieberthAdam** [comment]
Back to the topic: I made a pull request for the case (#90).

About the concernes regarding the two step approach: The `aiohttp` library does the same:

1. Make a request: http://aiohttp.readthedocs.org/en/stable/client.html#make-a-request
2. Use it and release it either with a context manager or explicitly: http://aiohttp.readthedocs.org/en/stable/client.html#releasing-response

Note that `client.get(url)` is a regular method which returns a request object. Here, `client` is a `ClientSession` instance, thus in `aiohttp`, request could be made directly from a function or by a session instance.

**Comment by aaugustin** [comment]
I still don't like this pattern:

    websocket = await websockets.connect('ws://localhost:8765/')
    async with websocket:
        # ...

I can't see a fundamental reason why it couldn't be written:

    async with websockets.connect('ws://localhost:8765') as websocket:
        # ...

This should be possible on Python 3.5 by having connect returning an object that implements both the awaitable protocol (`__await__`) and the context manager protocol (`__aenter__`, `__aexit__`).

I could change my mind if a fundamental reason why this cannot work came up.

One of the philosophical differences between the websocket support in `aiohttp` and `websockets` is that I make no compromises when it comes to the simplicity of the API. I'm unlikely to follow the API choices in `aiohttp` when I suspect there's a better way :-)

**Comment by aaugustin** [comment]
I'm thinking of something like this (untested):

    import asyncio
    import websockets
    
    
    class Connect:
    
        def __init__(self, *args, **kwargs):
            self.args = args
            self.kwargs = kwargs
    
        async def __aenter__(self):
            return await self    
    
        async def __await__(self):
            self.websocket = await websockets.connect(*args, **kwargs)
            return self.websocket
    
        async def __aexit__(self, exc_type, exc_value, traceback):
            await return self.websocket.close()

If that's a valid replacement for websockets.connect() on Python 3.5 -- backwards-compatible with the current API and functional as a context manager -- then it would just be a matter of renaming the current `connect` to `_connect` and doing:

    try:
        from .python35 import Connect as connect
    except ImportError:
        connect = _connect

**Comment by aaugustin** [comment]
If someone feels like testing the above and reporting whether in works, that would be super useful. I'll leave it there for today as it's getting late.

**Comment by aaugustin** [comment]
Tentatively assigning Ádám, since he sent a PR already :-)

**Comment by ryanhiebert** [comment]
I haven't tested it, but it looks nice, and seems like it should be a reasonable approach. ;-)

**Comment by SzieberthAdam** [comment]
I updated the pull request with tested code which lacks comments and docstrings yet. 

Some interesting details which were also new to me:
* `__await__` should be a regular method returning an iterator (https://www.python.org/dev/peps/pep-0492/#id50).
* The `__iter__()` magic method was added to also support `yield from` syntax. 
* Failed import turned to raise `SyntaxError`.

Finally the patching was kept to remain in the `client` module. This seems cleaner are less error prone.

**Comment by aaugustin** [comment]
I had two more ideas this morning:

1) I think this would work and keep all the code in one place (instead of creating a python35.py module):

    # client.py

    try:
        class Connect:
            # ...

    except SyntaxError:
        pass

    else:
       # patch connect....

2) This is a less well-formed idea — is there a use case for applying a similar concept to the server? I don't have a syntax example in mind. I'm mostly thinking about the symmetry (which, obviously, isn't perfect, as we have different patterns for running a client that will make a single connection and a server that will handle multiple connections.)

**Comment by SzieberthAdam** [comment]
1) Interesting idea which seems working nicely. I refreshed the pull request.
2) I was thinking about the same. As I see, since exceptions in handlers should not make the server fail, the main use case of a server context manager would be to assure all client connections were properly closed when its process gets killed either by Ctrl+C or by the OS.

**Comment by aaugustin** [comment]
Yes, the idea of (2) is to call `server.close(); await server.wait_closed()` in `__aexit__`.

The use case could be:

    exit_now = asyncio.Future()
    with serve(...):
        yield from exit_now

and you'd `exit_now.set_result(None)` to exit.

**Comment by aaugustin** [comment]
(If you want to restrict this issue to the client side to avoid scope creep and do the server side later, that's fine.)

**Comment by SzieberthAdam** [comment]
That is fine, we should aim symmetry. I will deal with the server side soon.

**Comment by SzieberthAdam** [comment]
I ended up at a pattern and started a thread in python-dev about the subject:
http://thread.gmane.org/gmane.comp.python.devel/155699

**Comment by aaugustin** [comment]
I read the discussion over there. It looks like we'll have to do with what asyncio currently provides.

I'm tempted to punt on the whole topic of signals and exceptions and let users do what they wish.

I tried to come up with a syntax that's as simple as the current server example and shuts down cleanly, which the current example doesn't do.

Here's one possibility:

    stop = asyncio.Future()  # give this a result to exit the server
    asyncio.get_event_loop().run_until_complete(
        websockets.run_server(handler, host, port, stop=stop))

This proposal introduces a new, higher level API: `run_server`, which starts the server, waits until a Future passed by the user completes, and then closes it. The user would wire whatever shutdown signal they want to `stop.set_result(None)`. I'm not happy with that because there's no way people will remember what `run_server` and `serve` do.

It's unclear to me that a context manager is helpful as a end-user oriented API here, although it could be useful for the internal implementation.

**Comment by aaugustin** [comment]
We could also take advantage of the major version bump to throw backwards-compatibility to the wind and totally change how serve works by default (with a way to restore the previous behavior for current users).

**Comment by SzieberthAdam** [comment]
"I'm tempted to punt on the whole topic of signals and exceptions and let users do what they wish."

Agree. It is not this library's concern how a user design her main loop.

Agree with the concept of `stop`. Any awaitable as `stop` is adequate. Given none, it could default to a plain `Future`. 

```
async def run_server(ws_handler, host=None, port=None, stop=None, *,
          loop=None, **kwds):
    if stop is None:  # wait forever by default
        stop = asyncio.Future(loop=loop) 
    async with websockets.serve(ws_handler, host, port, loop=loop,
                                **kwds) as server:
        return await stop
```

However, I am curious whether we could provide handler code as the body of the context manager which would provide a nice symmetry with the client code:
```
async def run_server():
    async with websockets.serve('localhost', 8765, stop=None) as websocket:

        name = await websocket.recv()
        print("< {}".format(name))
        greeting = "Hello {}!".format(name)
    
        await websocket.send(greeting)
        print("> {}".format(greeting))
```

I'm not decided whether it is possible and what to think of this yet though. Surely it has some twists which may make it obscure for the first glance. The body of the context has to get scratched out as it is the handler code. It is not clear how the reference of the server object could be passed to the user if she needs it. Anyway, I thought it is better to share it. It's advantage besides being symmetric with client pattern would be that `run_server()` would be written by the user and it does not require a new API.

**Comment by aaugustin** [comment]
There's a dissymetry, though: you can't do anything with the server object. The closest analog to the `websocket` object that `connect` returns is the `websocket` object passed to the `ws_handler` coroutine. That's why I suggested that exposing a context manager to the end user may not serve a purpose.

**Comment by aaugustin** [comment]
1) Current pattern which doesn't close connections properly on exit:


```python
start_server = websockets.serve(hello, 'localhost', 8765)

server_task = asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()


2) Proposed pattern to close connections properly on exit:

```python
# `server_task` in the original proposal.
async def server_coroutine(*args, **kwargs):
    # `server` is unused here.
    with websockets.serve(*args, **kwargs) as server:
        await asyncio.Future()

server_task = asyncio.get_event_loop().create_task(
    server_coroutine(hello, 'localhost', 8765))
# at this point you can cancel `server_task` to stop the server.
asyncio.get_event_loop().run_forever()
```

This is essentially Ádám's proposal on python-dev. It only requires adding
context manager semantics to serve() like connect().

It has the drawback that we introduce a new kind of server task, which might be
confusing.


3) Other pattern to close connections properly on exit:

In the example above, `server_coroutine` and `serve` have exactly the same API.

Could it be refactored like this?

```python
server_task = asyncio.get_event_loop().create_task(
    serve(hello, 'localhost', 8765))
# at this point you can cancel `server_task` to stop the server.
asyncio.get_event_loop().run_forever()
```

Unfortunately, at this point, we're back where we started, because the pattern
for stopping the server becomes:

```python
server_task.cancel()
await server_task
```

while in section 1 it was:

```python
server_task.close()
await server_task.wait_closed()
```


I'm starting to think that `asyncio` provides a pretty good API for this use
case and that we aren't going to be able to do much better.

**Comment by aaugustin** [comment]
@SzieberthAdam I'm about to give up on the idea of improving the `serve` API. What do you think?

**Comment by SzieberthAdam** [comment]
Yep, it is fine as it is, until for now.

I think that ideally the user should create a server task, and run it until it completes, without forced to explicitly run the event loop three times, first to create the server, second to serve forever, and third to close it when an exception (`KeyboardInterrupt` ) occurs. This way is too complicated as I see.

However, currently we can not do much. My pattern merged the first two steps, and I believe it is superior to the current convention but perhaps not good enough to create a new one. This is because it can't resolve the third step. I am not 100% confident about the reasons yet but the following is getting outlined:

1. The exceptions have a one direction flow in the chain of coroutines. One exception is when a Future/Task gets cancelled which raises the `CancelledError` exception at the `await` point. 

2. Due to (1), once Ctrl+C pressed, the event loop stops (without waiting for pending tasks to complete) and raises the error immediately since it came from outside. It would be nice from the event loop to cache and propagate such exceptions as well as `CancelledError` and raising them only when any of the clients is unable to handle it. It would let the clients have `await` in their `finally:` or `__aexit__()` blocks. So far I was only able able to drive anything asyncronously in those blocks when cancelled the task and made an extra
```
try:
    loop.run_until_complete(t)
except asyncio.CancelledError:
    pass
```
in the main loop. Without `await` in the `__aexit__()`, there is no such problem and everything closes nicely. Unfortunately we want to await `server.wait_closed()` there.

Many may miss that without an extra run call, the garbage collector begins its job by closing the event loop which makes any subsequent tear down to fail with `RuntimeError`.

**Comment by aaugustin** [comment]
OK. Let's reopen if/when we want to pursue this further.

**Comment by bcb** [comment]
Seems ideal to add cleanup to `WebSocketServer`:

```python
    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.close()
        self.wait_closed()
```
The usage is then:

```python
start_server = websockets.serve(hello, 'localhost', 8765)
with asyncio.get_event_loop().run_until_complete(start_server):
    asyncio.get_event_loop().run_forever()
```
With interrupt signal:

```python
loop = asyncio.get_event_loop()
start_server = websockets.serve(hello, 'localhost', 8765)
with loop.run_until_complete(start_server):
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
    loop.run_forever()
```

**Comment by aaugustin** [comment]
I may have nailed this one in #181.

I also think we're handling cancellation much better now than when @SzieberthAdam was investigating this in 2015.

Feedback on the API and whether it works for you — whoever you are ;-) — much appreciated!
