### ISSUE TITLE
Firefox often can’t establish a connection to the websocket

### ISSUE THREAD

**Issue by belamenso** [aaugustin/websockets#860]
Here's the server (slightly modified example from `REAMDE.md`)
```python3
import asyncio
import websockets

async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)

s = asyncio.get_event_loop().run_until_complete(websockets.serve(echo, '', 0, compression=None))
print(s.server.sockets[0].getsockname()[1])
asyncio.get_event_loop().run_forever()
```
and the client:
```html
<!DOCTYPE html>
<html>
  <meta charset="utf-8" />
  <script>
    let socket = new WebSocket(`ws://localhost:${prompt("Port: ")}`)
    socket.onerror = (e) => { console.log('error', e) }
    socket.onclose = (e) => { console.log('close', e) }
  </script>
</html>
```
When I start the server by `python3 server.py` and open the `client.html` in the browser, on Chrome the connection seems to always succeed, however on Firefox, for some ports it always fails, that is now matter how many Firefox windows I open and how many times I retry (with that specific port) Firefox prints out this error
```
Firefox can’t establish a connection to the server at ws://localhost:41821/.
```
and then the websocket receives `error` and `close` events (`close` with code 1006).

On Chrome/Chromium it works always, on Firefox about 60% of the time, and before I added `compression=None` it worked maybe 30% of the time.

It is worth mentioning that for some ports that didn't work previously, they started working after hardcoding them into the server, and some ports that worked before stopped working after hardcoding them into the server, and for some ports nothing changed. Also, every port that Firefox could not connect to worked fine on Chrome.

`websockets` version `8.1` (pip3-installed), Firefox version: `78.0.2 (64-bit)`, Chromium version: `87.0.4280.88 (Official Build) snap (64-bit)`, system:
```
Operating System: Kubuntu 19.10
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4
Kernel Version: 5.3.0-64-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4700HQ CPU @ 2.40GHz
Memory: 15,6 GiB of RAM
```

**Comment by aaugustin** [comment]
Does this also happen if you use `127.0.0.1` or `[::1]` instead of `localhost`?

**Comment by belamenso** [comment]
I just checked and yes, the problem persists in both version.

**Comment by mortoray** [comment]
Running this locally, the issue is that the server is opening an ipv6 address (check `netstat -tunlp`):

```
tcp6       0      0 :::44657                :::*                    LISTEN      32473/python   
```

`localhost` does not connect there, but `::1` does. For example:

```
let socket = new WebSocket(`ws://[::1]:${prompt("Port: ")}`)
```

**Comment by belamenso** [comment]
I now agree that this is the issue. By using `netstat -tunlp` I determined that `s.server.sockets[0]` sometimes is an ipv6 address and sometimes it's ipv4 one. Whenever the JS code uses the wrong address (`localhost` for ipv6 or `[::1]` for ipv4) the problem arises.

`s.server.sockets` seems to always have exactly two sockets, one on ipv6 and one on ipv4, however their ordering is nondeterministic, and my code caused the problem by always reading from `s.server.sockets[0]`.

Thank you, this closes the issue.
