### ISSUE TITLE
Lag when receiving data

### ISSUE THREAD

**Issue by Jacks349** [aaugustin/websockets#863]
I'm trying to stream some sensor data for an experiment and i created a very simple script that lets me connect and receive sensor data using this library. 

The number of messages is around 100 per second, each message is very small, it's something like `{"date": "xx", "rate": "xx", "direction": "xx"}`, At first everything went flawlessly, but then i started noticing some discrepancies in the data i was receiving, in particular there seems to be some "lag" where some messages are received after some seconds while other messages are lost.

Now i checked everything and i'm sure the problem is in the part where i receive the data through my websocket connection, so i was wondering if maybe the big amount of messages per second can create problems and if so, how to avoid them. My code is pretty simple, for now i'm just receiving the data and printing it:

```
async def connect():
	while True:
		try:
		     async with websockets.client.connect('MYURL') as ws:
		             while True:
				    message = ''

				    try:
					msg = await asyncio.wait_for(ws.recv(), 5)
					message = json.loads(msg)
					print(message)

				    except asyncio.TimeoutError:
					break		
		except Exception as e:
			logging.exception(e)

```

This code should make sure to keep the connection alive when it breaks and to restart it when i have not received data for five second. Am i doing something wrong? Is there any way to fix this?

**Comment by aaugustin** [comment]
Somewhat related to #414.

In very old versions of websockets, there used to be a bug where canceling recv() could cause a message to be dropped, but I'd be surprised if you didn't use a recent enough version.

100 messages / second on a single connection shouldn't be a problem. I have experimental evidence that `websockets` can handle tens of thousands of messages on thousands of connections.

I don't have enough info to reproduce or diagnose the issue. Given that WebSocket runs over TCP it's extremely unlikely that messages would be lost, except if you're disconnecting and reconnecting, in which case it's expected.

When you say:
> Now i checked everything and i'm sure the problem is in the part where i receive the data through my websocket connection
can you clarify how you know that the TCP connection never breaks?

What exception is getting logged?

Finally, can you make sure the device you're connecting to responds to pings correctly, or alternatively set `ping_timeout=None` to disable disconnection detection?

**Comment by Jacks349** [comment]
Thank you a lot for your clarifications! I've been making some further checks and i found that the problems were due to drops in the connection of the server where the data was being generated, which lead me to believe (wrongly) that the problem happened when i started to stream from the websocket. Using `ping_timeout=None` is very helpful too. Thank you a lot!

**Comment by aaugustin** [comment]
You shouldn't need `ping_timeout=None` unless the server is quite shitty, but hey, maybe it is :-)

**Comment by Jacks349** [comment]
I thought it wasn't too much - but maybe it is :)

**Comment by Jacks349** [comment]
I'm sorry for reopening the issue here, but i just wanted to to understand something, so forgive me if i'm saying something stupid here. Now that i know that my problem is resource here, i investigated a bit into how does all of this work, and from what i understood, my problem might be the buffer getting filled by the flood of messages. Is it possible? And is there any possible fix to this other than getting better hardware?

**Comment by aaugustin** [comment]
If a buffer getting filled is a problem, the solution is usually to make it _smaller_, so that backpressure kicks in earlier.

There are some details here: https://websockets.readthedocs.io/en/stable/deployment.html?highlight=bufferbloat#buffers

**Comment by Jacks349** [comment]
Looking into this, thank you!
