### ISSUE TITLE
Non blocking websockets

### ISSUE THREAD

**Issue by rlewkowicz** [aaugustin/websockets#864]
I'm sure this is going to be semi ignorant. I'm trying to wrap my head around async in python and of course I feel like theres a bunch of old info and libraries that do similar things etc. 

tldr: How do I keep handling a stream of data without blocking?

I'm consuming ranchers event stream:
```
async def rancher_consumer(wsuri, ruri, ssl_context, bearer_token, persistent_object):
    async with websockets.connect(uri=wsuri, ssl=ssl_context, 
    extra_headers={"Authorization": "Bearer " + bearer_token}) as websocket:
         await rancher_handler(websocket, persistent_object, ruri, bearer_token)
```

I feel like no matter what I did, it would block while processing an event. 

I can put the code in if needed, but inside of rancher_handler, I tried things like:

asyncio.ensure_future()

I tried these concepts:

https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

But no matter what, it wanted to wait for all this stuff to finish. 

What worked is that inside of the handler, I called blocking code from a decorated method using threading. Yea, it worked, but I'm sure thats not a good way to do it.

```
import threading

def dont_block(f):
    def wrap(*args):
        threading.Thread(target=f, args=args).start()
    return wrap

@dont_block
def check_active_state(persistent_object, cluster_id, url, token):
    client = rancher.Client(url=url, token=token, verify=False)
    cluster = client.by_id_cluster(cluster_id)
    while cluster.state != 'active':
        cluster = client.by_id_cluster(cluster_id)
        
    persistent_object.cluster_ids[cluster_id] = "ready" 
```

Do you have recommendation on how to handle a stream of packets without blocking?

**Comment by aaugustin** [comment]
Probably you want `asyncio.create_task` to start an async execution flow. This is the equivalent of `Thread().start()` in asyncio.

Also, don't use threads — unless you want to run code that does synchronous I/O.
