### ISSUE TITLE
PayloadTooBig, frame size, and maximum payload question?

### ISSUE THREAD

**Issue by mortoray** [aaugustin/websockets#866]
The Python client has a maximum payload size. I know I can increase this, but I had a question in general. Is this only the payload size? If  understand correctly though the server has no limit. It will fragment messages into frames. What is that size (I want to make sure I'm under the AWS size).  

Is there a real limit to the maximum message size in WebSocket itself, or is it only the Python client that does this? I'm only trying to understand to avoid designing something that won't work everywhere.

**Comment by aaugustin** [comment]
This library doesn't automatically fragment messages. However, it allows you to fragment them as you wish by passing an iterator of fragments to `send()` instead of a single message.

The limit on the size of a message is only for incoming messages It exists for security reasons. Without the limit, you could trivially crash the server by sending a message of an impractically large size (likely in the form of a zip bomb, given that compression is enabled by default). 

There's a protocol-level limit on the size of a frame in the WebSocket protocol, which (if memory serves) is 2**63 - 1 bytes — compressed ;-)

This doesn't answer exactly your question but hopefull will point you in the right direction.

**Comment by aaugustin** [comment]
BTW - thanks for taking the time to write https://mortoray.com/2020/12/06/high-throughput-game-message-server-with-python-websockets/ - it's always interesting to see how this library is used!

I share your opinion on acceptable throughput. Python is slow, sure, but 10k msg/sec in a single thread is table-stakes :-) I believe it's possible to do even better but I'm not sure it's _generically_ possible to do better, without knowing what OS you'll be running on.

**Comment by mortoray** [comment]
Thank you. I'll need to do my own message fragmentation then. I'll test that, and if it works I'll close this issue.

The incoming limit makes sense.

Your welcome, about the article. I'll likely write a followup with the higher-level pieces.  10k/s supports a 0.1ms ping-time... which would be a response-time dream on the internet!  :D

**Comment by mortoray** [comment]
I've tried fragmented, by passing a list of bytes to the `send` method. The Python client accepts this fine, but a browser WebSocket connection rejects it -- the connection is closed.

My chunking code is this:

```
def encode_msg(msg: Dict) -> List[bytes]:
	all_bytes = json.dumps(msg, ensure_ascii=False).encode('utf-8')
	chunks = (len(all_bytes)-1) // fragment_size + 1
	if chunks > 1:
		print("Chunking",chunks)
	return [all_bytes[x*fragment_size:(x+1)*fragment_size] for x in range(0,chunks)]
```

Where previously I'd just return the `json.dumps(msg, ensure_ascii=False)` bit.

Am I doing something wrong?  

Note that it fails even if I send only one-chunk this way. So I'm guessing it's some kind of encoding/charset issue more than a chunking issue.

**Comment by mortoray** [comment]
There appears to be two issues:

- "send" will assume the bytes are a ByteFrame, though I want a TextFrame.  In order to calculate my chunks I need to encode as UTF-8 first, so can I override `send` to specify a TextFrame on bytes?  (For now I can divide my chunk-size by 4, the maximum length of a UTF-8 sequence, and return strings)
- Nonetheless, and array of a single string doesn't work:

This works: 
```
all = json.dumps(msg, ensure_ascii=False)
ws.send(all)
```

This does not:

```
all = json.dumps(msg, ensure_ascii=False)
ws.send([all])
```

**Comment by aaugustin** [comment]
Regarding your first point, the reason for fragmentation is to support sending input of unknown size without buffering it all. Since you have the entire input in memory, don't bother fragmenting it — just send it in one frame.

If you still want to fragment it, indeed, don't put effort into creating chunks of an exact size in `bytes` after UTF-8 encoding but before GZip compression. I'd just split the `str` in chunks of roughly the right size. Anyway the browser will reassemble fragments before passing the message to the `onmessage` handler.

Regarding your second point, the client example works fine with this change:

```diff
diff --git a/example/client.py b/example/client.py
index 4f969c4..160d139 100755
--- a/example/client.py
+++ b/example/client.py
@@ -10,7 +10,7 @@ async def hello():
     async with websockets.connect(uri) as websocket:
         name = input("What's your name? ")

-        await websocket.send(name)
+        await websocket.send([name])
         print(f"> {name}")

         greeting = await websocket.recv()
```

So there must be something else going on with your test.

In the code you showed, you don't await ws.send, maybe that's the reason?

**Comment by mortoray** [comment]
I want to fragment because the AWS ELB says they have a maximum fragment size of 32K.  I'm unsure if that's just in the docs, or enforced. Seems like an odd limit to have, but alas, it's there.

For the second, yes, I'm having no problem with the Python client receiving a fragmented message. I'm having difficulty with a basic WebSocket in the browser, getting an error, and disconnecting. I'm not sure how I can go about debugging this, as I don't see where more information would  be printed.

(Not having `await` was just a copying error when I reduced the code to the essential bits.)

**Comment by mortoray** [comment]
I've created a minimal example that shows the problem from the browser.

If the send line is changed to not be an array:
`await websocket.send(encode_msg(message))`
Then it works. As an array it fails with `The connection to ws://localhost:8765/ was interrupted while the page was loading.` in the browser and `The connection to ws://localhost:8765/ was interrupted while the page was loading.` on the server.

## Server

```py
from typing import *
import asyncio, websockets, json

def encode_msg(msg: Dict) -> str:
    return json.dumps(msg, ensure_ascii=False)

def decode_msg(text: str) -> Dict:
    return json.loads(text)


async def listen_socket(websocket, path):
    global rooms, client_id_count
    print("connect", path)
    
    try:
        async for message_raw in websocket:
            message = decode_msg(message_raw)
            print(message)
            await websocket.send([encode_msg(message)])
    except Exception as e:
        print(e)


def main() -> None:
    start_server = websockets.serve(listen_socket, "localhost", 8765, ping_interval=5, ping_timeout=5)
    asyncio.get_event_loop().run_until_complete(start_server)
    asyncio.get_event_loop().run_forever()


main()
```

## Web Client:

```
<html>
<script>
function loaded() {

    console.log("Loaded")
    const socket = new WebSocket('ws://localhost:8765');

    socket.addEventListener('open', function (event) {
        socket.send(encode_msg({
            type: 'join',
            room: 'js-room',
        }));
        console.log("Opened")
    });

    socket.addEventListener('message', function (event) {
        console.log('Message from server ', event.data);
    });

    window.addEventListener('beforeunload', () => {
        console.log("UNLOAD")
        socket.close()
    })
    console.log("LOADED")

    let count = 0
    setInterval(() => {
        count = count+1
        socket.send(encode_msg({
            type: 'ping',
            seq: count,
        }))
    }, 500)
}

function encode_msg(msg) { 
    return JSON.stringify(msg)
}

function decode_msg(text) {
    return JSON.parse(text)
}

</script>
<body onload="loaded()">
    <p>Text</p>
</body>
</html>

```

**Comment by aaugustin** [comment]
OK, I'll look into this.

This is really unexpected — I had a high level of confidence because websocket never had trouble passing protocol compliance tests, including fragmentation.

**Comment by aaugustin** [comment]
Disabling compression with `compression=None` makes the issue go away.

It seems that compression + fragmentation doesn't work.

You must be the first person to ever attempt to use fragmentation for real :-)

**Comment by aaugustin** [comment]
This seems to fix the problem:

```diff
diff --git a/src/websockets/extensions/permessage_deflate.py b/src/websockets/extensions/permessage_deflate.py
index 9a3fc4b..445c866 100644
--- a/src/websockets/extensions/permessage_deflate.py
+++ b/src/websockets/extensions/permessage_deflate.py
@@ -166,7 +166,7 @@ class PerMessageDeflate(Extension):
         if frame.fin and self.local_no_context_takeover:
             del self.encoder

-        return frame._replace(data=data, rsv1=True)
+        return frame._replace(data=data, rsv1=frame.opcode != OP_CONT)


 def _build_parameters(
```

Indeed, when a message is fragmented and compressed, only the first frame should carry the RSV1 flag saying that the message is compressed.

RFC 7692 is clear:

>   An endpoint MUST NOT set the "Per-Message Compressed" bit of control
>   frames and non-first fragments of a data message.  An endpoint
>   receiving such a frame MUST _Fail the WebSocket Connection_.

**Comment by mortoray** [comment]
Great that you found it!

In the meantime I found the ELB doesn't apply the 32K threshold, it's some other part of the AWS ecosystem that has it.  (I sent a ~1MB uncompressed packet across).  

It'll still be good to have the fix. Perhaps it'd be a good chance to add a way to specify the frame type as part of the fragmentation. So one could encode the UTF-8 and still send Text frames.  It'd let me store my messages pre-encoded in the DB, saving some processing time. Nothing critical though.

**Comment by kirti1910** [comment]
@mortoray : Hello, I am struggling for sending large data to aws websocket. In this article, you mentioned that you snet a 1 MB uncompressed data successfully. Could you please help me out here? Is it some configuration at aws side? Thanks in advance!!
