### ISSUE TITLE
How can I limit the maximum concurrent number？

### ISSUE THREAD

**Issue by szm2git** [aaugustin/websockets#871]
How can I limit the maximum concurrent number？

**Comment by aaugustin** [comment]
Track how many connections you have (there are examples in the docs of keeping track of connected clients) and reject connections in `process_request` if are at the maximum.

It could be interesting to give an example in the docs.

**Comment by szm2git** [comment]
I use this “asyncio.Semaphore”,  it works.

**Comment by aaugustin** [comment]
Oh yes a Semaphore sounds ideal 👍
