### ISSUE TITLE
Is python websockets client recv() blocked? How to set it to receive only when there is a message?

### ISSUE THREAD

**Issue by szm2git** [aaugustin/websockets#874]
Is python websockets client recv() blocked? How to set it to receive only when there is a message?

```
async with websockets.connect(url) as websocket:
  wfile = wave.open(sys.argv[1], "rb")
  await websocket.send(''something'')
  while True:
    data = wfile.readframes(2048)
    if len(data) == 0:
      break
    await websocket.send(data)
    res = await websocket.recv()
```

when server did not send something，the line "res = await websocket.recv()" is blocking.

**Comment by lgrahl** [comment]
No, it is not blocking but async. Please [read up on that topic in the Python docs](https://docs.python.org/3/library/asyncio.html).

**Comment by szm2git** [comment]
Thank you, I solved my problem, and I really don’t understand asyncio well.
