### ISSUE TITLE
How to wait for connection lost but not closed by the client?

### ISSUE THREAD

**Issue by HMaker** [aaugustin/websockets#875]
`WebSocketCommonProtocol.connection_lost_waiter` is fired when the websocket state becomes `CLOSED`, so this will be fired even when I call `WebSocketCommonProtocol.close()`. Is there a way to listen for the event of the connection being closed by some other reason, like closed by server or due network issues?

**Comment by aaugustin** [comment]
I suggest you rely on the public API documentation instead of implementation details.

`connection_lost_waiter` is an implementation detail. You must have found it by reading the source code.

There's a public API documented for this purpose. You should be able to find it in 20 seconds in the docs.

**Comment by HMaker** [comment]
> I suggest you rely on the public API documentation instead of implementation details.
> 
> `connection_lost_waiter` is an implementation detail. You must have found it by reading the source code.
> 
> There's a public API documented for this purpose. You should be able to find it in 20 seconds in the docs.

Sorry, I can't find it.

**Comment by HMaker** [comment]
I think you mean I should use `wait_for_connection_lost()` or `wait_closed()`, but from what I understood it internally waits for `connection_lost_waiter` future, so they are fired even when the connection is closed by the client application.

**Comment by aaugustin** [comment]
Yes, `wait_closed` is the public API.

The documentation doesn't mention `wait_for_connection_lost`. It's a private API.

You can set a boolean flag before you close a connection:

```python
i_closed_the_connection = True
```

 Then, when `wait_closed` complete, if the flag isn't set, it means the other end closed the connection.
 
 You may also be interested in `close_code`.
