### ISSUE TITLE
Start server using existing (unix) socket

### ISSUE THREAD

**Issue by satchamo** [aaugustin/websockets#878]
The API for setting up a websocket requires passing in a `host/port` or `path`. It would be ideal if you could pass in an existing socket object instead (consistent with Python's `create_unix_server`/`create_server`). 

This would be useful in cases where you've maxed out what a single process can do, and you need to spread the load to other processes. You can share a listening socket with multiple processes by forking _before_ using the event loop.

Right now, this is already possible (I think) if you're using a TCP socket, but there's no (easy) way to use a unix socket. I came up with this ugly workaround:
```
server = websockets.unix_serve(bound_safe_socket_handler, path="thisisnotused", sock=sock)
fn = server._create_server
server._create_server = functools.partial(
  fn.func,
  *fn.args[:-1],  # remove the `path` argument
  **fn.keywords)
```

**Comment by aaugustin** [comment]
The current API is a wrapper around `create_unix_server` or `create_server`.

Here's the entirety of the code that deal with `host`, `port`, `path`, or `sock` parameters (`sock` would be in `**kwargs`):

```python
        if path is None:
            create_server = functools.partial(
                loop.create_server, factory, host, port, **kwargs
            )
        else:
            # unix_serve(path) must not specify host and port parameters.
            assert host is None and port is None
            create_server = functools.partial(
                loop.create_unix_server, factory, path, **kwargs
            )
```

Could you demonstrate an example of what you're trying to do that works with  `asyncio.create_unix_server` or `asyncio.create_server`, then show how it fails with `websockets.serve` or `websockets.unix_serve`?

**Comment by satchamo** [comment]
Sorry, I didn't explain that very well. The key observation is that to branch to `loop.create_unix_server` in the websockets library, you _must_ specify the `path` argument. But Python doesn't let you pass both a `path` and a `sock`: https://github.com/python/cpython/blob/66d3b589c44fcbcf9afe1e442d9beac3bd8bcd34/Lib/asyncio/unix_events.py#L245 They are mutually exclusive arguments. 

Here's a full forking example that doesn't work with websockets (unless I perform that hack):
https://gist.github.com/satchamo/56886677e70febc841f7c93061e37b09

**Comment by aaugustin** [comment]
Does #879 fix it?

**Comment by satchamo** [comment]
Just tried it. Yup, it works. Thank you!

**Comment by aaugustin** [comment]
Thanks for the bug report!
