### ISSUE TITLE
Should examples be switched to Python 3.5 async syntax?

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#88]
At some point, we should change the examples from:

    @asyncio.coroutine
    def hello():
        websocket = yield from websockets.connect('ws://localhost:8765/')
        # ...

to:

    async def hello():
        websocket = await websockets.connect('ws://localhost:8765/')
        # ...

Pro:

- slightly more concise and readable
- maximizes Python hipster factor

Con:

- doesn't work on Python 3.3 and 3.4 which might generate support questions

Of course, we could point users of Python 3.4 to older versions of the docs.

An alternative would be to show both versions, but I'm afraid that might create confusion.

I'm only raising this question for the docs. I don't think there's any value in considering this change for the library's source until we drop support for Python 3.4. Per the current rules, its end of life should be in March 2019, and we aren't planning that far ahead.

**Comment by ryanhiebert** [comment]
When we write documentation, we want to put it in it's best light. I think that using `async` and `await` is that best light.

Perhaps we can minimize the support issue by having a short section on how an async function can be written with `@asyncio.coroutine` and `yield from` in older Pythons would alleviate some of the pressure from potential support questions.

I think that `async` and `await` are great carrots for Python 3.5, and I think it'd be good to encourage people to use it by making it the obvious way to use this library.

**Comment by SzieberthAdam** [comment]
Note that `aiohttp` documentation is already switched:

http://aiohttp.readthedocs.org/en/stable/client.html

**Comment by aaugustin** [comment]
That's interesting. It's also a textbook example of what I'd like to avoid.

http://aiohttp.readthedocs.org/en/stable/ starts with a Python 3.5+ only example. The only mention of the Python version in that page is "Dependencies: Python Python 3.4.1+".

Most people (myself included) struggle to figure `asyncio`. Tutorial code samples failing with a `SyntaxError` for no obvious reason won't help.

**Comment by SzieberthAdam** [comment]
True, I opened a new issue for them.

**Comment by aaugustin** [comment]
I'm modestly leaning towards making the change, with a note at the top of every page that includes code samples stating:

> This documentation uses syntax that only works on Python ≥ 3.5.
> If you're using Python 3.4 or 3.3, refer to <link to section explaining the changes>

That section would just say:

>  Replace:
>
>     async def ...
>
> with:
>
>     @asyncio.coroutine
>     def ...
>
> and replace:
>
>      await ...
>
> with:
>
>     yield from ...

Reasons for doing that:

- The hipster factor appears to be quite important for the asyncio community at this time ;-)
- I want the note to be before the code. People who jump to the middle of the page will still miss it but that's the best we can do.
- I don't want the note to take more than two lines, since it's at the top of the documentation. Since the explanation takes a large amount of vertical space, it must go to the bottom of the page.

**Comment by SzieberthAdam** [comment]
As I see, only the intro page is involved yet, so that seems a good way.

I would opt for a common separate explanation page if there would be multiple page with asyncio code in them.

**Comment by aaugustin** [comment]
A drawback of this change is that we're going to lose syntax highlighting of Python code — because Read the Docs runs on Python 3.4.

**Comment by aaugustin** [comment]
I asked about the ability to build docs with Python 3.5 in https://github.com/rtfd/readthedocs.org/issues/1865.

**Comment by aaugustin** [comment]
Let's put this on hold until Pygments has a new release.
