### ISSUE TITLE
How does a productions setup with websockets look like? 

### ISSUE THREAD

**Issue by BlkPingu** [aaugustin/websockets#882]
Hello, I'm new to websockets.

 I was wondering how I would serve a websockets server in a production setting, like in an nginx server for example. I can't find anything useful in the docs on deployment [in the docs ](https://websockets.readthedocs.io/en/stable/deployment.html). I would be thankful for a few pointers.

**Comment by aaugustin** [comment]
You'll find some information in #445.

**Comment by aaugustin** [comment]
There's also docs for deploying to Heroku now.
