### ISSUE TITLE
Support both secure and non-secure connection

### ISSUE THREAD

**Issue by NN---** [aaugustin/websockets#883]
Is it possible to make WebSocker server with both supporting secure and non secure connections ?
If this TLS use secure and if it is regular HTTP, then resort to non secure.

**Comment by lgrahl** [comment]
Potentially, yes, even though I would recommend against it for obvious reasons. It's generally advisable to put a reverse proxy ahead (e.g. Nginx) anyways, so it's not something I see a real need for. @aaugustin might have a different opinion.

**Comment by NN---** [comment]
I need it just for tests ,not for production.

**Comment by lgrahl** [comment]
Why not simply spin up an insecure server then or one with a self-signed certificate?

**Comment by NN---** [comment]
I do it but I wanted to use the same port.

**Comment by aaugustin** [comment]
Could you show how you would achieve this for a simple TCP echo server, written with asyncio?

Then we can evaluate adapting your proposal to websockets.

**Comment by NN---** [comment]
I don't have an idea.
Something like pseudo code

```
on_request:
  if HTTP: use non encrypted
  else: use encrypted
```

**Comment by aaugustin** [comment]
If you look at the APIs provided by asyncio, you'll realize that it cannot work that way.

Here's the starting point: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_server

**Comment by NN---** [comment]
I see. Closing then.
