### ISSUE TITLE
need hooks on client side like on_websocket_connect, on_websocket_error, on_websocket_close

### ISSUE THREAD

**Issue by Torchcc** [aaugustin/websockets#888]
Hello, is there a way to implement hooks like on_websocket_connect, on_websocket_error, on_websocket_close  just as Java Jetty websocket client provides? also,  how to do if I need to customize my one ping(), and do sth every time when a ping msg are sent.  looking forward to your reply, thank you

**Comment by aaugustin** [comment]
https://websockets.readthedocs.io/en/stable/faq.html#are-there-onopen-onmessage-onerror-and-onclose-callbacks
