### ISSUE TITLE
how can i get http querystring 

### ISSUE THREAD

**Issue by ench2** [aaugustin/websockets#889]
in health_check_server.py example 

async def health_check(path, request_headers):
    if path == "/health/":
        return http.HTTPStatus.OK, [], b"OK\n"

if i pass a get param,how can i got it

**Comment by ench2** [comment]
i use regex to get it ,have a better way?

**Comment by aaugustin** [comment]
I'd use https://docs.python.org/3/library/urllib.parse.html
