### ISSUE TITLE
When I use ssl, the browser prompts me that the certificate is invalid

### ISSUE THREAD

**Issue by C966890tkz** [aaugustin/websockets#892]
Dear author, my website used to be a ws service using python websockets, but it was recently upgraded to HTTPS. The browser prompted me to use the wss protocol. When I used the configuration in the example, the browser control panel showed
 `net:: ERR_CERT_COMMON_NAME_INVALID,`
 saying that my certificate is not recognized, because it is the first time to use ssl and I don’t know much about this knowledge, how do I need to configure my certificate or .py file?
：）

**Comment by lgrahl** [comment]
You need a valid certificate issued from a CA (e.g. Let's Encrypt). I suggest reading up on that topic.
