### ISSUE TITLE
How to close a secure websocket correctly

### ISSUE THREAD

**Issue by wenwenchenbosch** [aaugustin/websockets#893]
I implemented a websocket client using this library. But after I closing the secure connection by the client side, I always get the error from server side:
```
ERROR: read: stream truncated
```
which means that the client closed the connection abruptly. The question is, how to close a websocket correctly. I called [`close()`](https://github.com/eclipse/kuksa.val/blob/7b55bbfaa30117a5fc3e157011ab5c3704100928/clients/common/clientComm.py#L116) function. But I still got the error.

**Comment by aaugustin** [comment]
Hard to answer tell without seeing the content of `testclient.py`. Could you provide it?

**Comment by wenwenchenbosch** [comment]
> Hard to answer tell without seeing the content of `testclient.py`. Could you provide it?

thanks for quick reply. Sorry for providing a non-public repository. You can now find the code unter https://github.com/eclipse/kuksa.val/blob/7b55bbfaa30117a5fc3e157011ab5c3704100928/clients/common/clientComm.py#L116, which should be public.

**Comment by mdavis-xyz** [comment]
So you're calling `.close()` on the object returned by `.connect()`?

I'm doing the same thing, and getting a different error:

> code = 1006 (connection closed abnormally [internal]), no reason

**Comment by mdavis-xyz** [comment]
There is documentation [here](https://websockets.readthedocs.io/en/stable/faq.html#how-do-i-close-a-connection-properly)

> How do I close a connection properly?
> websockets takes care of closing the connection when the handler exits.

What is a "handler"? Does that mean the asyncio coroutine?

My use case is that I want to connect a client for a fixed amount of time, then have the client close the connection cleanly.

**Comment by aaugustin** [comment]
```python
client = await websockets.connect()

# when you want to close

await client.close()
```

Perhaps you forgot to await the close coroutine?

**Comment by wenwenchenbosch** [comment]
I used `await`
https://github.com/eclipse/kuksa.val/blob/061fe1dd4be5092c605af410162e420d49cbd049/kuksa_viss_client/__init__.py#L165

**Comment by aaugustin** [comment]
The `example/secure_server.py` and `example/secure_client.py` files the repository don't have this problem.

If you can give me an easy way to reproduce — which is likely to require access to a test server :-/ — maybe I can investigate. Otherwise there's nothing more I can do with the error message.
