### ISSUE TITLE
in sub thread want call websocket send,how do

### ISSUE THREAD

**Issue by ench2** [aaugustin/websockets#894]
in client ,main process  await recv ,keep  heart ,
sub thread  redis  listen for subscribe channel,and has data,use websocket send it 
but it notice  sys:1: RuntimeWarning: coroutine 'rds' was never awaited ,how 
code like follow

`in main 
 _thread.start_new_thread ( rds,(websocket,) )    
        while(logined):
            await websocket.recv()

rds fun
async def rds(websocket):
    logging.info("go redis")
    rd = redis.Redis(host=CONFIG.get("redis","server_addr"),port=CONFIG.getint("redis","server_port"),socket_keepalive=20,socket_connect_timeout=20)
        

    ps = rd.pubsub()
    ps.subscribe(["TCDT"])   

    for item in ps.listen(): 
        await websocket.send(makeJson(msg_type="TCDT",data = recv_data['data']) )`

**Comment by steveseguin** [comment]
What was your solution to this by chance? I'm having a similar issue. :)

```
pubsub.subscribe(**{UUID: handle_peer_pubsub})
```
```
def handle_peer_pubsub(message):
        clients[message['client']].send(message['data'])
```
Not sure how to handle this.  I can't await the websocket's send if its being called from the redis subscribe function.

**Comment by ench2** [comment]
i'm update pub/sub ps.listen to  while and asyncio.sleep
  while logined:
        item = ps.get_message()
    
        if item:
           
                   
                    await g_websocket.send(makeJson(msg_type="TCDT",data=recv_data['data']))  
        else: 
          
            await asyncio.sleep(2)
