### ISSUE TITLE
ConnectionClosed isn't thrown when using `async for` syntax

### ISSUE THREAD

**Issue by MaxBarraclough** [aaugustin/websockets#895]
I'm writing client-side WebSocket code. I'm finding that the `ConnectionClosed` exception is thrown as expected when I use `recv()` but not when I use the `async for` syntax, as shown below (adapted from my real code).

```python3
    while(True):
        msg = await ws.recv() ## throws ConnectionClosed if the connection is closed
        call_with_string_after_receipt(msg)

## This will fail to throw ConnectionClosed
#   async for msg in ws:
#       call_with_string_after_receipt(msg)

    except ConnectionClosed as cce:
      print("ConnectionClosed exception was thrown")
```

**Comment by cjerdonek** [comment]
This behavior [is documented](https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol):

> The iterator yields incoming messages. It exits normally when the connection is closed with the close code 1000 (OK) or 1001 (going away). It raises a ConnectionClosedError exception when the connection is closed with any other code.

(Normal usage is to stop processing messages when the connection ends.)

**Comment by MaxBarraclough** [comment]
I'd missed that, thanks for the reply.
