### ISSUE TITLE
closing server

### ISSUE THREAD

**Issue by charles-salvia** [aaugustin/websockets#898]
https://github.com/aaugustin/websockets/blob/aa93c4ceca90a1798f86b2fc2b110a42f308d721/src/websockets/legacy/server.py#L691

Just wondering why `WebSocketServer.close` does not return a coroutine (it just returns None).  It seems you need to call and await the private method `_close` to manually close the server

**Comment by aaugustin** [comment]
I would recommend to use the [public API](https://websockets.readthedocs.io/en/stable/api.html#websockets.server.WebSocketServer.wait_closed) instead of relying on implementation details.

**Comment by aaugustin** [comment]
The reason for the `close` vs. `wait_closed` split is the same as in [asyncio.Server](https://docs.python.org/3/library/asyncio-eventloop.html#server-objects).

It isn't the part of the API I'm the most satisfied with, but the cost / benefit ratio of changing it isn't compelling.
