### ISSUE TITLE
Problems with parallel sending and receiving

### ISSUE THREAD

**Issue by repa1030** [aaugustin/websockets#901]
Hello,

I have a websocket server running in python and one client running in C#.
The communication was working fine (but not asynchron what is necessary, as `await ws.recv()` was blocking ) 
so I tried to use the "Common Patterns" -> "Both" code snippet to get an asynchronous communication.
But now it does not work anymore. I only get one message in C# and I dont receive any message in the python socket.
I am pretty new to asyncio and websockets so I tried to follow the documents and got this:

```
import websockets
import asyncio
from threading import Thread
import time

def test_thread():
    while True:
        time.sleep(1)

async def server_main(websocket, path):
    recv_task = asyncio.ensure_future(
        recv_ws(websocket, path))
    send_task = asyncio.ensure_future(
        send_ws(websocket, path))
    done, pending = await asyncio.wait(
        [recv_task, send_task],
        return_when=asyncio.FIRST_COMPLETED,
    )
    for task in pending:
        task.cancel()

async def recv_ws(websocket, path):
    async for message in websocket:
        print(message)

async def send_ws(websocket, path):
    while True:
        await websocket.send("Test outgoing")
        time.sleep(0.005)

if __name__ == "__main__":

    # Start test thread
    testThread = Thread(target=test_thread)
    testThread.start()

    socket_server = websockets.serve(server_main, "localhost", 4042)
    asyncio.get_event_loop().run_until_complete(socket_server)
    asyncio.get_event_loop().run_forever()
    print("Disconnected")
```

Thank you for your help!

**Comment by aaugustin** [comment]
```python
    while True:
        await websocket.send("Test outgoing")
        time.sleep(0.005)
```

never yields control.

Never use `time.sleep` in asyncio code.

Use `await asyncio.sleep` instead.

**Comment by repa1030** [comment]
Without time.sleep() I still have the same problem that there is only one "Test outgoing" message received in C#
and no message received in python from C# (but C# is definitly sending some messages).

**Comment by repa1030** [comment]
Thank you! It works fine now
