### ISSUE TITLE
Keep the client connected to receive data, even if the connection drops

### ISSUE THREAD

**Issue by MrUke** [aaugustin/websockets#902]
I have a problem with my websocket client. I would like it to always listen for new data, even if there's a short connection loss.
This is the function I use to receive data:

```
async def __ws_recv(self):
    while self.ws.open:

        try:
            data = await asyncio.wait_for(self.ws.recv(), timeout=2)

        except asyncio.TimeoutError:
            continue
            log.critical('Websocket read timeout, restarting connection...')
            return

        except websockets.exceptions.ConnectionClosed:
            log.critical('Websocket connection is closed, restarting connection...')
            return

        except Exception as err_msg:
            log.critical(f'Unknown error __ws_recv: {err_msg}')
            os._exit(1)

        self.__process_ws_data(data)
```

The client works fine, the only problem is that if there is a short loss of connection, the function stops on ws.recv() until the ConnectionClosed exception is raised.

For example if I turn off/on wifi (which causes 1-2 seconds of connection loss), websocket stops and needs to be restarted.

How can I keep the websocket listen for new data, without having to reconnect to the server?

**Comment by lgrahl** [comment]
WebSocket is TCP-based and if your TCP connection has been lost, then there's nothing you can do other than to reconnect.

**Comment by MrUke** [comment]
> WebSocket is TCP-based and if your TCP connection has been lost, then there's nothing you can do other than to reconnect.

I don't think that's my case. The websocket client stays connected, it just doesn't receive data (nor pongs).

I want to elaborate the problem with a comparison. In my project I am also using  [asyncio Streams](https://docs.python.org/3/library/asyncio-stream.html) which does just what I would like websocket to do: if for a moment the connection is lost (for few seconds), once connected again it receives all the "pending" data. Websocket, on the other hand, hangs on recv() and disconnects.

**Comment by lgrahl** [comment]
Then we follow different terminology regarding "connection".

IIRC the `recv` method should ignore cancellation, so generally, I don't see a reason why your code shouldn't work but @aaugustin might have an idea. That being said, I don't understand why you do the `wait_for` dance in the first place if all you do is continue the loop once the 2s have been elapsed, which is essentially identical to `await ws.recv()`. :thinking:

**Comment by MrUke** [comment]
> Then we follow different terminology regarding "connection".
> 
> IIRC the `recv` method should ignore cancellation, so generally, I don't see a reason why your code shouldn't work but @aaugustin might have an idea. That being said, I don't understand why you do the `wait_for` dance in the first place if all you do is continue the loop once the 2s have been elapsed, which is essentially identical to `await ws.recv()`. 🤔

1. I mean "connection loss" in the sense of a couple of seconds of lack of wifi/internet connection, so this shouldn't cause the socket connection to drop.
2. My application needs to be sure of continuously receiving data. My client sends a ping every 1 second (in another task), so `recv` should receive the pong response every second (and so it works for most of the runtime). Thus, the only way to detect connection loss is to use the `wait_for` dance (with a 2 secs timeout tolerance, as written in the script above). If I remove it, the script takes a few tens of seconds before raising ConnectionClosed. It is too long. I'd really like to remove it, but unfortunately as I said a slight loss of connection causes the script to block on `recv`.

**Comment by aaugustin** [comment]
Instead of the custom ping/pong implementation you mention in (2) you could use the built-in functionality by configuring a suitable `ping_interval` and `ping_timeout`. Then `recv()` would raise `ConnectionClosed` after at most `ping_interval + ping_timeout + 4 * close_timeout` seconds when the connection lags. Unfortunately, it waits for the closing handshake to complete, hence the `4 * close_timeout` factor which is less than ideal when the connection is timing out :-/ There's no real problem in setting a small `close_timeout`, so perhaps this could solve your issue.

I'm confused about why websockets would hang in circumstances where asyncio doesn't, because websockets runs on top of asyncio.

**Comment by aaugustin** [comment]
websockets interacts with the network only via asyncio; if there's a problem when the network disconnects and reconnects, that's an asyncio (or lower) issue, not a websockets issue.

Now the question is -- does websocket handle cancellation of `recv` incorrectly, when `wait_for` timeouts?

I ran the following experiment:

1. Start the server defined in `example/show_time.py`, which broadcasts messages at random intervals of up to 3 seconds
2. Start this client script, which is expected to timeout on 1 message out of 6:
