### ISSUE TITLE
Causes of the error "RuntimeError: cannot call recv while another coroutine is already waiting for the next message"?

### ISSUE THREAD

**Issue by AlexAndHisScripts** [aaugustin/websockets#903]
I know, it's in the message. Another coroutine is currently waiting for a message on the same websocket.

The thing is, I never do that. To init I recieve data, send data, then receive again. Then I go into a loop: Receive data, do stuff with it, maybe send data back. Other coroutines do send data down the wire, but they definitely don't do any receiving because there's only 3 instances of websocket.recv() in the entire program. What else could be causing this error? Is there a way to see what coroutine that is?

Edit:
So if I add a asyncio.sleep() to that main loop it stops with 2 clients (it always worked with 1), but going higher breaks it again.

Edit 2: This only seems to happen if I send a message after a receive.

**Comment by aaugustin** [comment]
No worries - concurrent programming is hard. Guess how I know ;-)
