### ISSUE TITLE
not catching all unsent messages when using Nginx as reverse proxy

### ISSUE THREAD

**Issue by steveseguin** [aaugustin/websockets#904]
I'm using a try/catch on the websocket.send call to detect disconnected users, but this only works flawlessly when not adding in a reverse proxy.

For reference:
```
try:
    await clients[dst].send(json.dumps(data))
catch:
    cleanupClient(dst)
```

I'm a bit confused as to what is going on exactly, so I'm speculating a bit, but this websockets package was unable to scale past 4000-connections with SSL enabled. It just started to thrash the CPU heavily at that point, so I added an NGINX reverse proxy to handle the SSL aspect and connect without SSL to the server code. This change has drastically reduced the CPU load and got rid of the thrashing issues, but I'm finding messages are getting lost now.

As in, if a user reconnects to the server, messages that were sent to that user while they were disconnected for a few moments are not always caught by the try/catch. I have no way to know really if the client got the request, at least not without building in some sort of acknowledgement system with timeout, which adds to the overhead and complexity.

For transparency, here is the core of NGINX reverse proxy logic

```
map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
}
upstream websocket {
      server 127.0.0.1:8443;
}
limit_conn_zone $binary_remote_addr zone=addr:50m;
limit_req_zone $binary_remote_addr zone=req_limit_per_ip:50m rate=300r/s;

server {
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl; 
    ssl_certificate XXXXXXXXXXXXXX
    ssl_certificate_key XXXXXXXXXXXXXX
    
      location / {
         proxy_pass http://websocket;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
         proxy_read_timeout 43200000;
         proxy_connect_timeout 43200000;
      }
}
```

Would anyone know if there was a solution to this or whether I'm even chasing the right problem? I get the sense that Nginx is saying everything was sent, but it really wasn't

[update]
I notice it says here the client doesn't support proxies? https://websockets.readthedocs.io/en/stable/limitations.html
Perhaps I'm in trouble then.

]update 2]
I notice that NGINX has an option to disable buffering; it can be set via the header even.
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering
```headers['X-Accel-Buffering'] = 'no'```
Perhaps if I add this header to the requests that matter to me I'll be able to catch disconnects correctly?  Going to see if I can figure out how to do that...

**Comment by aaugustin** [comment]
Perhaps you can resolve this by adding:

```python
pong_waiter = await clients[dst].ping()
await pong_waiter
```

in your try/catch block, to ensure the message is sent and received by the other party, or you get an exception.

**Comment by steveseguin** [comment]
Thank you very kindly, I'll give that a try.

**Comment by steveseguin** [comment]
As an update, I haven't been able to reproduce problems since and have not had any user complaints so far.  I have not really seen any measurable CPU load to the server. 

Thank you kindly.  I'll close the issue as I think the solutions presented are reasonable.

**Comment by aaugustin** [comment]
Good to hear!

To answer you other questions:

> I notice it says here the client doesn't support proxies? https://websockets.readthedocs.io/en/stable/limitations.html

This is only when using websockets as a client behind a proxy, and you're using it as a server behind a reverse proxy.

> I notice that NGINX has an option to disable buffering; it can be set via the header even. http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

Worth a shot, but I'm skeptical, because buffering makes no sense on a WebSocket connection.
