### ISSUE TITLE
How to gracefully shut down using the close() method

### ISSUE THREAD

**Issue by CodeJP97** [aaugustin/websockets#905]
Hi together,

I would like to know, how to shut down the websocket server gracefully using the close() method. The example provided is only as a contextual manager not using close, but SIGTERM.
I tried to call close on the created object, but I get the following error:
` File "manager.py", line 21, in main
    server.close()
AttributeError: 'Serve' object has no attribute 'close'`
My server looks like this if printed: `<websockets.server.Serve object at 0x7f0d3c6949d0>`
According to the docs, shouldn't this be a websockets.server.WebSocketServer instead of Serve?
Or am I getting something wrong?
Thanks in advance for your help!
Kind regards JP

**Comment by lgrahl** [comment]
I'm unaware of an object named `Serve` in the code. Maybe ensure you're using the most recent version. But with the little information you provided, it's very hard to tell.

**Comment by CodeJP97** [comment]
Sorry for providing this little information and thanks for the fast reply. Here is my code I'm currently using (made from one of the examples):

    from multiprocessing import Process
    import asyncio
    import websockets
    async def echo(websocket, path):
        async for message in websocket:
            await websocket.send(message)
    def run(server):
        asyncio.get_event_loop().run_until_complete(start_server)
        asyncio.get_event_loop().run_forever()
    def main():
        start_server = websockets.serve(echo, 'localhost', 8765)
        p = Process(target=run, args=(start_server,))
        print(start_server)
        print(type(start_server))
        start_server.close()
        p.join()
    if __name__ == '__main__':
        main()

The error I get is the following:

    <websockets.server.Serve object at 0x0000020471C64970>
    <class 'websockets.server.Serve'>
    Traceback (most recent call last):
      File "C:\Users\Home\Documents\webs.py", line 22, in <module>
        main()
      File "C:\Users\Home\Documents\webs.py", line 18, in main
        start_server.close()
    AttributeError: 'Serve' object has no attribute 'close'

I'm using Python 3.9.1 with the latest websocket version (I think 8.1)
My idea was to run the event loop in a seperate process to be able to shutdown the server gracefully. But I don't know where this error is comming from, or how to avoid it.

**Comment by lgrahl** [comment]
Ah, there is the class in question: https://github.com/aaugustin/websockets/blob/aa93c4ceca90a1798f86b2fc2b110a42f308d721/src/websockets/legacy/server.py#L761

The error is because you're not using it in an async context manager. `async with websockets.serve(...)`, so you don't have the correct class instance.

**Comment by CodeJP97** [comment]
Thanks for clarification, I'll try it out :D
