### ISSUE TITLE
Two-way SSL - Access presented client certificate

### ISSUE THREAD

**Issue by Disc-rete** [aaugustin/websockets#906]
I've got two way ssl working great. Only trouble is that I would like to identify the user based off the presented certificate. Because this happens during the TLS setup, I don't see a way to know what certificate was presented during the websocket functions. 
I was able to find SSLSocket.getpeercert() but not seeing a way to get the socket after the handshake to grab that certificate.

**Comment by Disc-rete** [comment]
I also found a way to get the same result through asyncio (https://docs.python.org/3/library/asyncio-protocol.html?highlight=peercert#asyncio.BaseTransport.get_extra_info) if that would be possible. Perhaps I'm just overlooking this, though.

**Comment by aaugustin** [comment]
If you want to do this only through private APIs, you have to subclass `WebSocketServerProtocol` and override `connection_made`, which is the only place where `asyncio` gives you a reference to the transport, and there you can call `get_extra_info`.

Or you can just hack you way through the internals and use `websocket.transport.get_extra_info(...)`.

**Comment by Disc-rete** [comment]
I've tried both and both work perfectly. Thank you! I like the sub-classing because then I can embed user information into the sub-classed websocket and have it on hand wherever the instance is.

**Comment by aaugustin** [comment]
👍
