### ISSUE TITLE
How to ignore certs or trust custom cert for interactive client?

### ISSUE THREAD

**Issue by mdavis-xyz** [aaugustin/websockets#907]
I want to use the interactive client described on [this page](https://websockets.readthedocs.io/en/stable/intro.html?highlight=interactive#one-more-thing)

```
python -m websockets wss://echo.websocket.org/
```

The particular server I'm using provides a self-signed certificate.
I want to make websockets trust this certificate, or just ignore the certificate.
I want the equivalent of `-k` or `-capath` in `curl`.

Is there anything like that? I can't see any arguments in `__main__.py` for this. But do any of the underlying network libraries read from environment variables to get configuration?

I don't want to install this certificate as a root CA for my whole laptop.

I'm considering building a docker image and installing this particular self-signed cert as the root CA inside the docker image, then running from there. But that will be fiddly because docker on mac just can't handle proxies properly. Is there an easier way?

If there's not currently a way to do this easily, would you be open to a PR to add more arguments [here](https://github.com/aaugustin/websockets/blob/aa93c4ceca90a1798f86b2fc2b110a42f308d721/src/websockets/__main__.py#L173)? I'm not yet comfortable writing with asyncio, but fortunately this part of the code seems synchronous.

**Comment by mdavis-xyz** [comment]
If I add `-k` and `--capath` as command line arguments, there would be more of a need to have a `--help` argument.

I thought `argparse` [does this out of the box](https://docs.python.org/3/howto/argparse.html). But `python3 -m websockets --help` doesn't work. Any idea why? Is it because we're using `-m module_name` instead of just `python3 myscript.py`?

I assumed that would be fixed with [this line](https://github.com/aaugustin/websockets/blob/aa93c4ceca90a1798f86b2fc2b110a42f308d721/src/websockets/__main__.py#L169).

```
    parser = argparse.ArgumentParser(
        prog="python -m websockets",
```

**Comment by aaugustin** [comment]
Setting `SSL_CERT_FILE` may do the job.

If it doesn't, you're out of luck :-( because I don't have time & motivation to make `python -m websockets` as powerful as `curl`, sorry. You'll have to copy-paste the __main__.py script and modify it to suit your needs.
