### ISSUE TITLE
Connection closed error under load

### ISSUE THREAD

**Issue by nick-thompson** [aaugustin/websockets#912]
Hi, I'm hitting the following issue repeatedly on my websocket server whenever I apply non-trivial load from a websocket client. It seems that the issue stems from my `await ws.send(message)` call

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "/usr/lib/python3.7/site-packages/myapp/server.py", line 32, in handle_connect
    await ws.send(message)
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

My websocket server code is only this:
```
async def handle_connect(ws, path):
    logging.info('Accepting new socket connection')

    async for message in ws:
        payload = json.loads(message)

        try:
            await handle_payload(payload) # This actual hander is trivial but takes some time
        except Exception as e:
            logging.info(f'wat {e}')

        await ws.send(message)

async def run(host="0.0.0.0", port=8080):
    logging.info(f'WebsocketServer listening on {host}:{port}')

    return await websockets.serve(
        handle_connect,
        host=host,
        port=port,
        max_queue=1024,
    )
```

I've tried tweaking that `max_queue` setting. It seems that the larger that number the longer my server will run before this crash. My test client will send 10k messages at 16ms interval to stress performance under load.

Any idea what's happening here? How can I avoid this crash? Thanks.

**Comment by aaugustin** [comment]
Would you mind checking what happens if you add `ping_timeout=None` in the invocation of `websockets.serve`?

And likewise in your client if it's written with websockets?

**Comment by aaugustin** [comment]
My suspicion is that you're creating so much load on the server that it cannot respond to pings within the timeout of 20 seconds and the connection gets closed. Generally speaking an asyncio-based server (like most systems based on cooperative scheduling) is unlikely to behave well under 100% CPU load.

Alternatively, it might be that the queuing mechanism is broken.

**Comment by nick-thompson** [comment]
Interesting, thanks @aaugustin! Setting `ping_timeout=None` indeed resolves the issue; my socket remains alive even during the intense load here in my testing.

> My suspicion is that you're creating so much load on the server that it cannot respond to pings within the timeout of 20 seconds and the connection gets closed. Generally speaking an asyncio-based server (like most systems based on cooperative scheduling) is unlikely to behave well under 100% CPU load.

Of course, that makes plenty of sense. The simulated load I'm testing with is expected to be more intense than my actual application, but it's helpful for testing.

Out of curiousity, is it a very bad idea to use a longer (or `None`) `ping_timeout` in production? While I expect this type of load to never occur, I do want my socket server to be resilient to periods of rapid incoming messages

**Comment by aaugustin** [comment]
You can set `ping_timeout` to `None` without adverse effects. It exists only because users like their WebSocket connections to drop quickly when connectivity is poor and TCP connections tends to have very (very) long timeouts.

Alternatively, you can:

- set `max_queue` to a large enough value to absorb any spike of messages that you would expect (websockets will see the pings coming back even if messages are in queue);
- set `ping_timeout` to a large enough value to give the service the time to process a spike, rather than disabling it outright.

**Comment by nick-thompson** [comment]
Ok perfect, thank you!
