### ISSUE TITLE
support for basic auth RFC 2617

### ISSUE THREAD

**Issue by FilMar** [aaugustin/websockets#915]
hi everyone, 
i'm working with ocpp protocol 2.0.1.
For the autorization to start the comunication i need the RFC 2617 standard to check client's credential.
I saw some page of documentation of the ws API (for example: https://websockets.readthedocs.io/en/stable/_modules/websockets/auth.html)
but it is avaliable with RFC 7235 and 7617.

someone can help me please?

thanks in advance.

**Comment by aaugustin** [comment]
I believe the basic protocol remained the same between all these RFCs, but if there's a difference, I can look at making websockets more compatible.

**Comment by aaugustin** [comment]
Please provide some details and ideally a minimal reproduction if you think websockets doesn't implement basic auth correctly.
