### ISSUE TITLE
Running server after error code 1006

### ISSUE THREAD

**Issue by VidarHUN** [aaugustin/websockets#921]
I want to setup a simple server which can run after ConnectionClosedError. I tried to catch this exception and ignore it, but somehow the exception don't go away. 
I have this code:
``` python
import asyncio
import websockets

async def ws_server(websocket, path):
    while True:
        try:
            print("New server")
            name = await asyncio.wait_for(websocket.recv(), timeout=10)
            print(f"< {name}")

            greeting = f"Hello {name}!"

            await websocket.send(greeting)
            print(f"> {greeting}")
        except asyncio.TimeoutError:
            print("Timeout")
            continue
        except websockets.exceptions.ConnectionClosedError:
            print("Connection closed")
            continue

start_server = websockets.serve(ws_server, "127.0.0.1", 2000)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```
My client is a `websocat` process. So everything works fine until I close the connection with ctrl+c. After I closed the connection from client side the server generate this output: 
```
Connection closed
New server
Connection closed
New server
Connection closed
New server
Connection closed
New server
Connection closed
New server
Connection closed
```
How should I handle this exception?

**Comment by aaugustin** [comment]
Once a WebSocket connection is closed, well, it's closed. The client must open a new connection to your server.

**Comment by VidarHUN** [comment]
I know, but I cannot make a new connection after this exception.

**Comment by VidarHUN** [comment]
I was able to resolve this issue. Sorry if I asked a silly question. Thanks for your help!
