### ISSUE TITLE
How could I handle an HTTP post request?

### ISSUE THREAD

**Issue by KTibow** [aaugustin/websockets#926]
I'm working on building a proxy for Home Assistant using Python (yes I know nginx is probably better; it's complicated though). Everything works except the websocket connection, so I found this library.
After looking at the `process_request` function, it looks like it can't receive the body of a POST request. Is there any way that I could do this? If not, could a fix be implemented?

**Comment by KTibow** [comment]
I got a fair bit working, but still can't work out how to get the body. It seems like there's nothing in the POST request. Here's my code so far:
```

**Comment by aaugustin** [comment]
This comment may help: https://github.com/aaugustin/websockets/blob/aa93c4ceca90a1798f86b2fc2b110a42f308d721/src/websockets/legacy/http.py#L96-L98

In `process_request`, you should be able to read the body from `self.reader` — but that's a private API, so no backwards compatibility guarantees.

**Comment by KTibow** [comment]
It just gets infinitely stuck when I try to call `self.reader.readline()`.

**Comment by KTibow** [comment]
Okay, I changed it to `self.reader.read(4096)` and it works!
