### ISSUE TITLE
Lots of opened TCP connections

### ISSUE THREAD

**Issue by prav2019** [aaugustin/websockets#927]
When client closes connection, calling .close() on server is not closing the TCP connections. The close_wait (connections) piles up and creating lot of problem (OOM and disrupting the applications).

**Comment by aaugustin** [comment]
Yes, this behavior is mandated by the spec, see https://tools.ietf.org/html/rfc6455#section-7.1.1

> when a client is instructed to do the same, it SHOULD wait for a TCP Close from the server.
