### ISSUE TITLE
Any way to host on a serverless platform like Heroku?

### ISSUE THREAD

**Issue by cyfinfaza** [aaugustin/websockets#929]
I have a WebSocket server written with this library. I was just going to get a VPS and host my server on that, but it seems there are serverless platforms that support WebSockets, and those tend to be much cheaper (or even free), and they tend to be more reliable. However, most of these platforms seem to want a WSGI server, and as far as I know this library is not WSGI. I am a beginner/intermediate at this, so I am not sure whether I am misunderstanding something, or whether it is just not possible to use this library on serverless hosting platforms.

**Comment by aaugustin** [comment]
This is correct -- WSGI doesn't support long running connection (barring horrible hacks) so you cannot run a WebSocket server on top of WSGI.

If the platform supports ASGI, then the platform takes care of converting between WebSocket and ASGI, and you plug into the ASGI interface. In that case you don't need websockets either. (The platform may use something similar to websockets to implement the WebSocket <=> bridge.)

That said, I'm pretty sure you can run websockets on Heroku. Keeping this ticket open in case I'm interested in trying it.

**Comment by aaugustin** [comment]
There you go — a complete tutorial for deploying to Heroku.

It should translate to other similar platforms.

**Comment by cyfinfaza** [comment]
Thanks so much! I can confirm that method worked for me.
