### ISSUE TITLE
Add support for extensions and implement RFC 7692

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#93]
Until August 2015, I could get away with saying that no extensions were registered. Now there's one.

**Comment by aaugustin** [comment]
If you're interested in this feature, upvote this issue. I won't implement it until someone needs it.

**Comment by RouquinBlanc** [comment]
Hi Aaugustin,

Trying to move away from our nodejs websocket server, we will run into an issue using your implementation: the lack of support for websocket compression (permessage-deflate), which is now quite deployed on browsers and in nodejs, and saves a lot of bandwidth for our mobile clients. Do you have any plan concerning this one?

Thanks
Jonathan

**Comment by aaugustin** [comment]
Hello, while I'd like websockets to gain this feature, I'm unlikely to work on it in my free time for the next two months.

If you'd like to discuss sponsoring this feature, please email me: aymeric.augustin@fractalideas.com. Thanks!

**Comment by aaugustin** [comment]
I started a branch here: https://github.com/aaugustin/websockets/tree/extensions

**Comment by aaugustin** [comment]
Pull request for that branch: https://github.com/aaugustin/websockets/pull/178
