### ISSUE TITLE
Accept-Encoding:gzip,deflate,br

### ISSUE THREAD

**Issue by ablewolf** [aaugustin/websockets#930]
How does the client decompress these formats, I have tried many times to get garbled information

**Comment by aaugustin** [comment]
`Accept-Encoding` is a HTTP header; the WebSocket protocol doesn't interpret it (AFAIK).

If I'm missing something, could you point me to the relevant part of the spec?

**Comment by AmirHmZz** [comment]
@ablewolf It is not implemented yet in websocket protocol. According to [IETF ](https://tools.ietf.org/html/rfc7692) websocket servers can enable permessage-deflate extension in order to compress messages using deflate algorithm.

**Comment by aaugustin** [comment]
And websockets enables permessage-deflate by default.
