### ISSUE TITLE
send in thread - messages sent all at once?

### ISSUE THREAD

**Issue by zbouslikhin** [aaugustin/websockets#944]
Hello, 

I have a Websocket server running in python and one client running in JS.
I'm running an `asyncio.queue` in a thread to flush the queue and send the data through Websocket.

- Problem:

The first message is sent by the server and received from the client as expected. However, the incoming messages are received only when the job that puts data into the queue is done. 

- Expected behavior:

Receive messages one after another in the client side

- Code:

Server code structure:
```
    async def send_to_all(self, message: str) -> None:
        if self.clients:
            [await client.send(message) for client in self.clients]
        logger.debug("INFO: msg sent to ALL clients")

    async def flush_queue(self):
        logger.debug("INFO: queue worker has started.")
        logger.debug("INFO: looking for queue data to process.")
        while True:
            for _ in range(self.msg_q.qsize()):
                data = self.msg_q.get_nowait()
                await self.send_to_all(data)

async def ws_handler(self, ws: WebSocketServerProtocol, uri: str) -> None:
        await self.register(ws) 
        try:
            asyncio.ensure_future(self.trigger_pipeline())
        finally:
            pass
            # await self.unregister(ws)
            # await self.close()

    def start(self):
        _queue_worker = threading.Thread(target=asyncio.run, args=(self.flush_queue(),))
        _queue_worker.start()

        self.loop = asyncio.get_event_loop()

        self._server = websockets.serve(
            self.ws_handler, 
            self.listen, 
            self.port, 
            loop=self.loop
            )

        self.loop.run_until_complete(self._server)
        self.loop.run_forever()
```

Client:
![image](https://user-images.githubusercontent.com/47977073/117337044-3065ab80-ae9d-11eb-9d32-87711a77e4fd.png)

I'm sorry in advance if I'm missing a trivial thing. I'm very fresh to this world.
Thank you for your help!

**Comment by aaugustin** [comment]
You shouldn't mix asyncio and threads. Use asyncio tasks instead of threads.

If you need to perform synchronous operations (waiting on a queue, synchronous I/O) in a separate thread, use `asyncio.to_thread` - https://docs.python.org/3.9/library/asyncio-task.html#running-in-threads.

**Comment by zbouslikhin** [comment]
Thank you for the help!
I tried it using `asyncio.to_thread`, but the problem persists. 
This time, messages are received all at once to the client server at the very end of the job.

- Code:
Server code structure:

```
    async def send_to_all(self, message: str) -> None:
        print(message)
        if self.clients:
            [await client.send(message) for client in self.clients]

    async def flush_queue(self):
        while True:
            for _ in range(self.msg_q.qsize()):
                data = self.msg_q.get_nowait()
                await self.send_to_all(data)

    def start_server(self):
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        self._server = websockets.serve(
            self.ws_handler, 
            self.listen, 
            self.port, 
            loop=loop
            )
        loop.run_until_complete(self._server)
        loop.run_forever()

    async def _start(self):
        loop = asyncio.get_event_loop()
        await asyncio.gather(
            asyncio.to_thread(self.start_server),
            await loop.run_in_executor(None,
                self.flush_queue
                )
        )

    def start(self):
        asyncio.run(self._start())
```
Client:
![image](https://user-images.githubusercontent.com/47977073/117386081-8a3e9380-aee6-11eb-92b2-1d15ba6b2126.png)

**Comment by aaugustin** [comment]
You're still running two threads in an incorrect way. This is not a problem in websockets. This is a problem in the way you use asyncio.

You're running two event loops in two separate threads and calling from one to the other without thread safety.

Keep things simple, use only one event loop, and delegate only blocking operations to the thread pool managed by asyncio, with `asyncio.to_thread(self.msg_q.get_nowait)`.

**Comment by zbouslikhin** [comment]
@aaugustin Thank you so much for putting me back on track. 
Sorry for the inconvenience and non-related websockets library question!
