### ISSUE TITLE
Compressing with different negotiated LZ77 windows size

### ISSUE THREAD

**Issue by AmirHmZz** [aaugustin/websockets#945]
I set my websocket server to offer `windowBits = 9` for both client and server sides.
The negotiation offer header (sent by browser) looks like this :
`server < Headers([('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits')])`
And negotiation response looks like this :
`server > Headers([('Sec-WebSocket-Extensions', 'permessage-deflate; server_no_context_takeover; client_no_context_takeover; server_max_window_bits=9; client_max_window_bits=9')])`

But I'm trying to compress message with windowsBit = 15 and all is done without error! 
```python
def frame_message(message: Union[bytes, str]):
    if isinstance(message, str):
        frame = Frame(True, Opcode.TEXT, message.encode("utf-8"))
    elif isinstance(message, bytes):
        frame = Frame(True, Opcode.BINARY, message)
    else:
        raise Exception("Invalid message type")
    return frame.serialize(mask=False, extensions=[
        permessage_deflate.PerMessageDeflate(
            remote_no_context_takeover=True,
            remote_max_window_bits=15,
            local_no_context_takeover=True,
            local_max_window_bits=15,
            compress_settings={'memLevel': 4},
        )])
```
And browser receives messages well. how is that possible ?

**Comment by AmirHmZz** [comment]
Also I've written a websocket client which will try all possible combinations of `server_no_context_takeover` , `client_no_context_takeover` , `server_max_window_bits` , `client_max_window_bits`. 
Client received all of messages correctly.

**Comment by aaugustin** [comment]
The issue you're reporting is that you expect the browser to reject the message, and that it accepts it. That's a question for the browser vendor, not in websockets.

I don't believe the spec require the browser to reject messages compressed with a larger window. Merely it says the browser can use a small window:

> If the peer server uses a small LZ77 sliding window to compress messages, the client can reduce the memory needed for the LZ77 sliding window.
