### ISSUE TITLE
Client closes connection too quickly.

### ISSUE THREAD

**Issue by vaibhav-46** [aaugustin/websockets#947]
I am trying to create a websocket proxy, that allows clients to use my server locally as a websocket proxy to connect to some other websocket. To do so, I wrote the following code borrowed from a github post  and refactored. (https://gist.github.com/bsergean/bad452fa543ec7df6b7fd496696b2cd8)

```
#!/usr/bin/env python3

# websocket proxy

import asyncio
import websockets


class ProxyServer:
    '''
        Proxy server can be used to
    '''

    def __init__(self, host, port):
        self.host = host
        self.port = port

    def start_server(self):
        ''' Start listening on given host and port for any incoming traffic '''
        print("Starting server on port " + self.port)
        server = websockets.serve(self._proxy_server, self.host, self.port)
        return server

    def get_destination_url(self, url):
        return "ws://echo.websocket.org/"

    async def _client_to_server(self, ws, websocket):
        async for message in ws:
            await websocket.send(message)

    async def _server_to_client(self, ws, websocket):
        async for message in websocket:
            await ws.send(message)

    async def _proxy_server(self, websocket, url):
        '''Called whenever a new connection is made to the server'''

        destination_url = self.get_destination_url(url)
        async with websockets.connect(destination_url, ping_interval=None) as ws:
            loop = asyncio.get_event_loop()
            taskA = loop.create_task(self._client_to_server(ws, websocket))
            taskB = loop.create_task(self._server_to_client(ws, websocket))

        await taskA
        await taskB
```

The code to start the server is simple : 
```
import asyncio
import websocket_proxy


def run_server():
    server = websocket_proxy.ProxyServer("localhost", 8447)
    server.start_server()
    asyncio.get_event_loop().run_until_complete(server)
    asyncio.get_event_loop().run_forever()


if __name__ == "__main__":
    run_server()
```

But when running this server, the connection from this server to the echo server keeps getting closed immediately leading to the client not receiving anything/getting partial messages. The output of debug logging is below. The main line is the one that is closing the client-state connection almost immediately after going back to OPEN. 

(20:52:27) asyncio DEBUG     Using selector: EpollSelector
(20:52:30) websockets.protocol DEBUG     server - state = CONNECTING
(20:52:30) websockets.protocol DEBUG     server - event = connection_made(<_SelectorSocketTransport fd=8 read=idle write=<idle, bufsize=0>>)
(20:52:30) websockets.protocol DEBUG     server - state = OPEN
(20:52:30) websockets.protocol DEBUG     client - state = CONNECTING
(20:52:30) websockets.protocol DEBUG     client - event = connection_made(<_SelectorSocketTransport fd=9 read=idle write=<idle, bufsize=0>>)
(20:52:30) websockets.protocol DEBUG     client - state = OPEN
**(20:52:30) websockets.protocol DEBUG     client - state = CLOSING**
(20:52:30) websockets.protocol DEBUG     client > Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
(20:52:30) websockets.protocol DEBUG     client < Frame(fin=True, opcode=8, data=b'\x03\xe8', rsv1=False, rsv2=False, rsv3=False)
(20:52:30) websockets.protocol DEBUG     client - event = eof_received()
(20:52:30) websockets.protocol DEBUG     client - event = connection_lost(None)
(20:52:30) websockets.protocol DEBUG     client - state = CLOSED
(20:52:30) websockets.protocol DEBUG     client x code = 1000, reason = [no reason]
(20:52:31) websockets.protocol DEBUG     server < Frame(fin=True, opcode=1, data=b'Hello 0', rsv1=False, rsv2=False, rsv3=False)
(20:52:31) websockets.server ERROR     Error in connection handler

If I run the same code, without any modifications as taken from the github gist, it works perfectly fine.

**Comment by RonaldColyar** [comment]
I am having a similar issue : I posted the code here -> https://stackoverflow.com/questions/67443383/why-is-python-websocket-connection-closing-while-still-being-referenced

**Comment by aaugustin** [comment]
As soon as you create the "client to server" and "server to client" tasks, you exit the `async with websockets.connect(...)` context. The point of using a context manager is to close the connection when you exit the context, and that's what's happening.

```python
        async with websockets.connect(destination_url, ping_interval=None) as ws:
            await asyncio.gather(
                self._client_to_server(ws, websocket),
                self._server_to_client(ws, websocket),
           )
```
