### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by paskozdilar** [aaugustin/websockets#953]
On the following page:

https://websockets.readthedocs.io/en/stable/design.html

The `Public APIs` hyperlink in the `Warning` section on top of the page points to an invalid url:

https://websockets.readthedocs.io/en/stable/api/index

I suppose the URL should instead be:

https://websockets.readthedocs.io/en/stable/api/index.html

**Comment by aaugustin** [comment]
Good catch, thanks!
