### ISSUE TITLE
PyInstaller + Lazy importing

### ISSUE THREAD

**Issue by kevinpthorne** [aaugustin/websockets#956]
This is not petitioning for change since the library runs fine outside of EXE bundling. This is an informational post for all.

I ran into an issue bundling with PyInstaller. 
```
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "lib\ws_server.py", line 48, in run_ws_server_threaded      
                             # my app where it says: loop.run_until_complete(websockets.serve(on_connected, "127.0.0.1", 1234))
  File "websockets\imports.py", line 81, in __getattr__
  File "websockets\imports.py", line 26, in import_name
ModuleNotFoundError: No module named 'websockets.legacy'
```

I needed to add:
```
import websockets.legacy.server
```
explicitly in my (server) script for PyInstaller to include it properly. I imagine something similar (`websockets.legacy.client`) would need to be done for clients.

At the time of writing, I can't get the `hiddenimport` PyInstaller config option to perform the same thing; this is the best I could do.

**Comment by aaugustin** [comment]
I think it's a duplicate of #940.

**Comment by kevinpthorne** [comment]
At first glance, it does seem to be the same issue.

**Comment by aaugustin** [comment]
I'll release 9.0.2 hopefully over the weekend.
