### ISSUE TITLE
Frame length(?) included in received data

### ISSUE THREAD

**Issue by GeorgeTG** [aaugustin/websockets#96]
I am using the API, by supplying a custom class(derived from WebSocketClientProtocol) with the klass keyword in connect. My class' data_received method gets data in the form of "b'\x81\x10{"type":"hello"}'" ... Is this the intended behaviour, or am I doing something wrong  ?

**Comment by aaugustin** [comment]
`data_received` is the basic callback of the asyncio protocol. It gets bytes straight from the underlying transport (TCP for ws://, TLS for wss://).

If you're trying to intercept received messages, you could override `read_message`, `read_data_frame` or `read_frame` (depending on how low level you need to go), call the `super()` implementation, and do what you want before returning it.

**Comment by GeorgeTG** [comment]
Just like I've suspected, I was going the totally wrong way about this. Thanks for information!
