### ISSUE TITLE
Parsing anything but ASCII paths

### ISSUE THREAD

**Issue by Randelung** [aaugustin/websockets#963]
Hello

I use `websockets` as both a websocket and http(s) server backend. So far it works spendidly.
I've come across a small issue, though. Could it be that request paths aren't being url decoded, at least before being passed to the `process_request` callback?
I see you're reading the http request path [here](https://github.com/aaugustin/websockets/blob/08d8011132ba038b3f6c4d591189b57af4c9f147/src/websockets/legacy/http.py#L82), where it's being passed back to [here](https://github.com/aaugustin/websockets/blob/08d8011132ba038b3f6c4d591189b57af4c9f147/src/websockets/legacy/server.py#L335) and [here](https://github.com/aaugustin/websockets/blob/08d8011132ba038b3f6c4d591189b57af4c9f147/src/websockets/legacy/server.py#L630) and is subsequently immediately being passed to the `process_request` handler.
URL-encoded entities are not decoded at that point. I tried requesting a URL with a "ü" in the URL and the application receives a 404 for "%C3%BC".

For my application, decoding right at the beginning of `process_request` using `urllib.parse.unquote_plus` is sufficient.

I can't really estimate the extent of the impact url decoding would have on your framework (or if this is by design in the first place), but potentially a small improvement might be to url decode the request path just after [parsing the wire request](https://github.com/aaugustin/websockets/blob/08d8011132ba038b3f6c4d591189b57af4c9f147/src/websockets/legacy/http.py#L82), especially since you [include user form data](https://websockets.readthedocs.io/en/stable/api/server.html#websockets.server.WebSocketServerProtocol.process_request) ("request path, including optional query string") in the argument.

Cheers

**Comment by aaugustin** [comment]
I didn't consider this point specifically; it isn't a design decision.

Many websockets servers expose a single endpoint so URL routing isn't a huge concern.

That said, if websockets URL-decodes path, then there's a risk that you can't parse the query string properly anymore (e.g. if path contains a URL-encoded question mark).

I think the answer may come from #311 -- if there's a URL dispatcher, then it will parse and decode the path correctly. Until then, I'm afraid we have to keep the current behavior.

**Comment by Randelung** [comment]
Oh yeah, you're right, you'd have to parse the form data in its entirety first. Leaving that up to the callback is the best option considering the project scope.
Thanks!
