### ISSUE TITLE
Browsed-based websocket

### ISSUE THREAD

**Issue by yabsol** [aaugustin/websockets#966]
The normal Browsed-based example in your documentation is not secured(ws://) I was wondering how to make the connection secured(wss://)

**Comment by aaugustin** [comment]
Server side: get inspiration from https://websockets.readthedocs.io/en/stable/intro.html#secure-example
Client side: convince your browser to trust the certificate of your server (navigating to https://localhost:8765/ and overriding warnings could do the trick) then change ws:// to wss://

**Comment by yabsol** [comment]
Thanks for the response.
but how do I convince the browser to trust the certificate(
https://localhost:8765/ )?
if u can, better if u share me example code
