### ISSUE TITLE
Tips to scale and optimize websocket servers

### ISSUE THREAD

**Issue by AmirHmZz** [aaugustin/websockets#968]
Hello !
First of all thanks to @aaugustin for creating this fantastic library. I'm working on a large scalable high-frequency server which is going to handle lots of websocket connections using [websockets](https://github.com/aaugustin/websockets). There are many tips which helped me to keep things working. I wanna share my experience here and I hope it helps someone.

### ● Merge messages
Like any other method, `WebSocketServerProtocol.send()` has its own overhead. Each call to this method will construct frame(s), write them into the socket buffer and awaits for buffer to drain. By merging messages and sending them together you can reduce calls to this method. Also sending packets together is a technique which is used in socket based servers.

### ● The way of calling `send()`
`asyncio.create_task()` [is a little expensive](https://stackoverflow.com/questions/55761652/what-is-the-overhead-of-an-asyncio-task) because of creating `asyncio.Task` objects. If a server with 20K connected clients calls `asyncio.create_task()` for _each send message operation_ to _each client_ ( in order to achieve concurrency ), with a message rate of _3 msg/s_ per client, server is calling `create_task()` _60K times/s_. So you should use `await` instead of creating new tasks as much as possible. One suitable solution is creating an `asyncio.Queue` for each client and create a task which runs a loop as follows  : 
```Python
while not client.connection.closed:
    message = await client.out_queue.get()
    try:
        await client.connection.send(message=message)
    except ... :
        ...
```
Now it's enough to push messages to client's queues. Also there are other benefits of using this design :  
  - Merging messages to send them together will be much easier
  - In case of increasing message rates, overall performance & delay won't be affected a lot, unlike _create_task per message_ design.
  - When there are lots of connections with high message rates, `create_task` might keep number of event loop's coroutines increasing and this will lead to unwanted memory usage ( lots of tasks ). but with a queue you can set max items limit that also covers slow connections problems.

### ● Broadcasting same messages
If you are broadcasting same message to many clients, It's better to compress that message once to save **tons of ram**. First of all you should disable permessage-deflate feature. You can use `zlib` built-in module to compress your messages with `deflate` / `gzip` algorithms and send compressed messages to clients in binary frames. In the client side ( browser )  you can use [**pako**](https://github.com/nodeca/pako) (which is an high speed zlib port to javascript) to decompress messages efficiently. This will also let you design your own communication protocol easily.

### ● Use uvloop
[uvloop ](https://github.com/MagicStack/uvloop)( based on [libuv ](https://github.com/libuv/libuv)) is an alternative event loop which only works on unix based systems. According to benchmarks It's protocol acts **2x** faster than CPython's default event loops. In my case uvloop boosted performance of server and caused to handle **+25%** more connections on the same config.

I will be happy to read your suggestions about tuning websocket servers up.
Thanks again.

**Comment by aaugustin** [comment]
Quick feedback on your points.

**Use Binary frames** I believe the accepted answer to the SO question you linked to is complete bullshit. It namedrops HTTP/2 and SMTP for no valid reason. It confuses Base64 and UTF-8. Proxies don't do what this answer says they do.

Sure, binary frames don't require an UTF-8 encoding/decoding step, which makes them faster than text frames. My take on this: the cost lies in Python's unicode model; if Python's unicode is too slow for you, maybe don't go with Python in the first place? :-) So this isn't a recommendation I will make in websockets' docs.

**Merge messages** Your suggestion implies that "write [messages] into the socket buffer and awaits for buffer to drain" is a slow operation. In fact nothing happens in if the buffer isn't over the high water mark, not even yielding control to the event loop. I believe these two operations should have pretty much the same cost:

- Concatenating two strings together in your Python code then adding the result to the send buffer in asyncio Python code
- Adding two strings to the send buffer in asyncio Python code

In fact, the latter may be faster because it relies on a bytearray which has better amortized cost for appends. Happy to be proven wrong by a benchmark :-)

**Using a send queue** This is an interesting pattern. Indeed, most calls to `send()` don't yield to the event loop, so wrapping a task around fire'n'forget calls to `send()` (which you inevitably end up doing when you broadcast messages) could have a measurable overhead. However, it isn't clear to me whether throwing a queue in the mix improves the situation all that much. That would require benchmarking.

**Broadcasting same messages** I spent a bit of time thinking about this today and commented in #870, which tracks this feature request. I understand that you implement at at the application level to get 100% control and sidestep the issues I just pointed out in that issue. It works, but it isn't a recommendation I'd like to make in the docs, else folks will cargo cult it ("compression doesn't work in websockets, you must implement it in your app!") even though the default, protocol-level implementation does the job for many use cases.

**Use uvloop** Searching for "uvloop" in this tracker turns up multiple people who use it successfully, so this is definitely something I can document.

**Comment by AmirHmZz** [comment]
### Merge messages
**Section A - Benchmark**
The benchmark source code is available on [Gist](https://gist.github.com/AmirHmZz/02d078e52ce46dac84cec7102ba33668). You can use `run_benchmark()` function to run a benchmark, but let me explain the arguments :

- _messages_ : total count of messages to be sent from each `update_generator`
- _update_generator_count_ : count of `update_generator` loops to run concurrently
- _sleep_ : sleep time in seconds between sending messages from each `update_generator`
- _client_count_ : clients count to be participated in benchmark
- _merged_ : If set to `True` benchmark will run in merged mode

Messages are simple Unix Time `floats` which are interpreted to a _8 bytes_ double using `struct` module, clients will convert messages from `bytes` to `float` to calculate latency. Both `normal` and `merged` modes use an `asyncio.Queue` for each client. 
Here is some of benchmark results on my netbook :
```
messages count = 10 * 3 | sleep = 0.1 | client count = 2000 | merged = False | total_latency = 2.6162438921928404
messages count = 10 * 3 | sleep = 0.1 | client count = 2000 | merged = True | total_latency = 1.7331272947192193
```
```
messages count = 5 * 3 | sleep = 1 | client count = 2000 | merged = False | total_latency = 1.9605204912662508
messages count = 5 * 3 | sleep = 1 | client count = 2000 | merged = True | total_latency = 1.465327833724022
```
There is an important point about the `merged` mode : It's more **scalable** than `normal` mode. I wanna explain this with an example : Assume that our server is able to `send()` _2000 messages/seconds_ based on its capabilities (CPU , Network , ...). If message generation rate gets higher than _2000 messages/seconds_ , queue lengths start to grow and If you set a limit to the queue size you will probably get lots of `QueueFull` exceptions. That's exactly why increasing client counts affects `normal` mode more than `merged` mode :
```
messages count = 5 * 3 | sleep = 1 | client count = 5000 | merged = False | total_latency = 9.29358078933716
messages count = 5 * 3 | sleep = 1 | client count = 5000 | merged = True | total_latency = 4.856307481575012 
```

**Section B - Theory-based perspective**
- As I said, calling `WebSocketServerProtocol.send()` has a small overhead. I can divide this overhead into two important parts : **System (OS) socket.write() call** , **awaiting buffer to drain**. Reducing calls to `WebSocketServerProtocol.send()` can directly reduce system calls which can be effective anyway.
- If [Nagle algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) gets enabled ( which is enabled by default in system level ) sending multiple smaller messages over a given `tcp` connection will generally be slower than sending fewer larger messages over that same connection. Nagle buffers outbound data internally and has to wait for enough data to be buffered and/or timed out so it can send efficient messages.
- In a realistic environment, for a specific connected client, server won't call `socket.write()` continuously. There's always interval between `socket.write()` calls. There's something called **TCP flow control** which determines the throughput over time for each connection. Filling buffer in a chopy manner will causes that os lowers the throughput even if the connection is capable for more. Giving the whole merged messages will cause the tcp to send data more freely.
- There are also some experience based evidences that I've found and I suggest you to read more : https://stackoverflow.com/a/666032/11879944

I'm going to do more benchmarks about other mentioned tips soon. Thanks for reading!

**Comment by AmirHmZz** [comment]
@aaugustin Thank you for being motivated in this discussion :) Why you posted same comment twice ( please delete one of them if it's possible )
You were right about the message sizes, benchmark could be more realistic. I updated [benchmark](https://gist.github.com/AmirHmZz/02d078e52ce46dac84cec7102ba33668) and added _message_len_ argument to the arguments. Now messages are unix timestamp as a **8 byte float + random bytes**. Here's the result with _message_len_ equal to _1000_ bytes :

```
transmitted_messages = 75000 | sleep = 0.5 | client_count = 5000 | update_generators = 3 | merged = False | latency_avg = 8.042499717950822
transmitted_messages = 75000 | sleep = 0.5 | client_count = 5000 | update_generators = 3 | merged = True | latency_avg = 2.9124846661949158
```

And yes, I totally agree with you, The cost of syscall is more significant here.

**Comment by aaugustin** [comment]
Hello Amirreza -- I tried the technique you proposed under "the way of calling send()" here: https://github.com/aaugustin/websockets/issues/653#issuecomment-855436929

In my testing, using a queue underperforms creating a task for each message. So I'm not reaching the same conclusion as you did. What do you think?

**Comment by aaugustin** [comment]
Just to be sure I'm clear:

- yes, `create_task` has a cost, which is why the task-based method has worse performance than the naive method
- but the queue-based method seems even worse, so I'm wondering if you benchmarked a queue-based vs. a task-based implementation, and if so, if you got different results from mine.

**Comment by aaugustin** [comment]
I was about to start a "Performance" document recommending uvloop, then I saw it has received no maintenance since 4 months: no commit or response to issues. This is slightly worrying.

**Comment by AmirHmZz** [comment]
I've replied in that issue and I also provided a benchmark. You are right about uvloop. Some of amazing python open source projects are inactive these day. I've searched a lot for other event loops bindings but I found uvloop was the best one.
I'm going to add some tips to previous tips soon. These days I'm thinking about creating a faster design for managing high number of clients. Have you ever heard about [japronto](https://github.com/squeaky-pl/japronto) ? There are some [points](https://www.freecodecamp.org/news/million-requests-per-second-with-python-95c137af319/) about its optimizations. But have you ever think about writing more parts of `websockets` in C ?

**Comment by aaugustin** [comment]
I think you should switch to Go. I have zero desire to maintain more C code.

**Comment by aaugustin** [comment]
Japronto bases its claims based on sending a bazillion GET requests for a Hello World from the same client to the same server _in the same TCP connection_ which doesn't bear any relationship with any realistic workload. This says nothing about how it will perform in practice.

**Comment by AmirHmZz** [comment]
I never rely on projects' owners benchmarks. What I said was based on [TechEmpower](https://www.techempower.com/) benchmarks. As they say , japronto is really faster than Go in [PlainText test](https://www.techempower.com/benchmarks/#section=data-r0&hw=ph&test=plaintext&a=2) and [Json Serialization](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=json&a=2). Any way I'm just asking you a general question. Do you think maintaining websockets in C can cause any performance improvements?

**Comment by aaugustin** [comment]
I have a hard time answering this question:

- certainly you can get performance improvements in any Python project by rewriting it in Cython or C
- but the question remains theoretical until someone decides to fork websockets and rewrite it

I've been looking for performance critical parts that would be interesting to port in C and didn't come up with anything.

**Comment by aaugustin** [comment]
I covered "Merge messages", "The way of calling send()", and "Broadcasting same messages" in #986. The only action left here is to mention uvloop.

**Comment by AmirHmZz** [comment]
Thanks again. I was going to mention another point to increase performance of a websockets server :

### ● Try [SSL offloading](https://avinetworks.com/glossary/ssl-offload/#:~:text=SSL%20offloading%20is%20the%20process,HTTP%20requests%20on%20the%20internet.)
If your server uses `TLS` to provide secure websocket connections, you can rely on `reverse proxies` / `load balancers` to do the cpu-intensive task of encrypting and decrypting messages. Many of reverse proxies and load balancers are written in `C` / `C++` which can make handling the `TLS` layer tasks much faster than `Python`. In my own tests I could handle 25% more clients on the same server with ssl offloading.
