### ISSUE TITLE
Serve behind HAProxy with Unix Sockets

### ISSUE THREAD

**Issue by AmirHmZz** [aaugustin/websockets#971]
Hello.
I'm trying to serve my `websockets` server on a unix domain socket behind `HAProxy` load balancer, but I'm getting **503** status code in websocket handshake. The `HAProxy` logs says it couldn't connect to backend ( `websockets` server ). I've tried serving on TCP socket ( using `websockets.serve()` ) and it worked without any problems.
I'm running on ubuntu 20.04. I've also tried running `HAProxy` as `root` user and group and changed chmod of the unix socket file to 666 but it didn't make any sense.

HAProxy config :
```
global
  log /dev/log	local0
  log /dev/log	local1 notice
  chroot /var/lib/haproxy
  user root
  group root
  daemon

defaults
  mode http
  log global
  default-server inter 3s rise 2 fall 3

frontend ft_web
  bind X.X.X.X:Y name http ssl crt /etc/letsencrypt/live/***/full.pem
  maxconn 60000
  default_backend bk_ws

backend bk_ws                                                    
  server websrv1 unix@/tmp/lds-1.sock
```

And my websockets server :
```Python
import asyncio
import websockets

async def test(websocket, path):
    await websocket.send(await websocket.recv())

start_server = websockets.unix_serve(test, path="/tmp/lds-1.sock")
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

I've tried Lightspeed as a websocket reverse proxy before , and I faced the exact same problem : **Reverse proxies cannot connect to websockets server via an unix domain socket.**
Did I make any mistakes? Did anyone deploy websockets server behind Nginx / Lightspeed / HAproxy using a Unix domain socket?

**Comment by aaugustin** [comment]
Issues 539 and 849 mention setups with unix sockets behind a reverse proxy; that part seems to work well for their authors.

I never did it myself so I don't know what it takes.

**Comment by aaugustin** [comment]
There's also a complete example with nginx here: https://github.com/aaugustin/websockets/issues/445#issuecomment-739420455

**Comment by AmirHmZz** [comment]
@aaugustin Thanks a lot, I've found my mistake and sorry for wasting your time, of course.
HAProxy has a global configuration parameter called `chroot` which jails its process to a directory in order to increase security. So it cannot access outside of this directory at all. I've created my unix socket in `/var/lib/haproxy` and it worked perfectly.
I'm going to publish a HAProxy configuration working with `websockets` server file soon, so let this issue be open, please.

**Comment by aaugustin** [comment]
The docs now contain working examples for nginx + unix sockets and for haproxy. I think we're covered on that front.

The guides are kept simple on purpose because optimizations always depend a lot on the context of each project.

**Comment by aaugustin** [comment]
The docs contain the level of detail I'm comfortable maintaining so I'm going to close this issue.

Feel free to post your configuration in a comment in case someone reads this in the future!
