### ISSUE TITLE
why max_size and max_queue is invalid when we test?

### ISSUE THREAD

**Issue by cotyyang** [aaugustin/websockets#976]
Hello, when we are testing locally, why the max_size and max_queue in the connect function are set to be greater than the default value or None is invalid. But is it effective if it is set smaller than the default value? Thanks

**Comment by aaugustin** [comment]
Could you clarify what you mean by "is invalid"? Are you getting an exception? If so, could you please provide the full stack trace?

**Comment by cotyyang** [comment]
ok，the code and exception are like this
![image](https://user-images.githubusercontent.com/34573329/120442827-9f5cf400-c3b8-11eb-9e38-c8aa8bbb6fbc.png)
![image](https://user-images.githubusercontent.com/34573329/120443017-d29f8300-c3b8-11eb-97c8-d42e51715cfa.png)

**Comment by aaugustin** [comment]
Did you set `max_size =None` both in the client and the server? I suspect you only did it in the client.

**Comment by cotyyang** [comment]
> Did you set `max_size =None` both in the client and the server? I suspect you only did it in the client.

thank you very much,we solved it!!
