### ISSUE TITLE
Error in data transfer due to 1006

### ISSUE THREAD

**Issue by apljungquist** [aaugustin/websockets#977]
I'm writing some stress tests for a web app and I expect that no matter what clients do the server should never experience an error. However, the test occasionally fails because the below shows in the log:

```text
ERROR    websockets.protocol:protocol.py:805 Error in data transfer
Traceback (most recent call last):
  File "venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 919, in read_data_frame
    await self.pong(frame.data)
  File "venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 689, in pong
    await self.ensure_open()
  File "venv/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

As far as I can tell the exception never passes through the application thus providing the application no opportunity to catch it.

From a cursory reading it seems it should be safe to catch this since `self.state is State.CLOSED` and any later attempts to send or receive should raise the same exception to the application. However, I am not familiar enough with the library to know if it could be a symptom of a problem elsewhere.

What do you think?

It seems to be caused by connecting a client that does not receive any of the messages sent by the server eventually triggering a ping timeout. Not sure if it happens on client side or server side since in my testing so far both run in the same process.

**Comment by aaugustin** [comment]
Yup, almost certainly a ping timeout. Try setting `ping_timeout=None` to disable keepalive.

**Comment by apljungquist** [comment]
Thank you for taking time to read and reply.

You are correct, setting `ping_timeout=None` on the server does make the error disappear.

However, I think I failed to communicate my larger question which is this; what do you think about the idea that in general a lib (websockets) should communicate errors to the app and let the app decide about logging?

I like some guidelines laid out in the [python logging tutorial](https://docs.python.org/3/howto/logging.html#when-to-use-logging). In particular, it makes the following suggestions:
1. To _report an error regarding a particular runtime event_ the best tool is _raise an exception_.
2. To _report suppression of an error without raising an exception_ the best tool is _logging.error(), logging.exception() or logging.critical() as appropriate_.
3. The `ERROR` level should be used when _due to a more serious problem, the software has not been able to perform some function_.

As I noted I think, in effect, the exception is raised to the app and should not be considered suppressed thus negating 2. Additionally, the app may still be able to recover and perform its functions thus negating also 3.

W.r.t. this particular case I did some more digging and as far as I can tell this particular error occurs iff the ping that has not been acknowledged is waiting in the stream reader when it is closed.
```text
08:18:27.593 DEBUG server ! timed out waiting for pong                                                                                                                                                                             
08:18:27.593 DEBUG server ! failing OPEN WebSocket connection with code 1011                                                                                                                                                       
08:18:27.593 DEBUG server - state = CLOSING                                                                                                                                                                                        
08:18:27.593 DEBUG server > Frame(fin=True, opcode=<Opcode.CLOSE: 8>, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)                                                                                                        
08:18:27.593 DEBUG server x half-closing TCP connection                                                                                                                                                                            
08:18:27.593 DEBUG client - event = data_received(<4 bytes>)                                                                                                                                                                       
08:18:27.594 DEBUG client - event = eof_received()                                                                                                                                                                                 
08:18:27.594 DEBUG client - event = connection_lost(None)                                                                                                                                                                          
08:18:27.594 DEBUG client - state = CLOSED                                                                                                                                                                                         
08:18:27.594 DEBUG client x code = 1006, reason = [no reason]                                                                                                                                                                      
# At this point the client switches from sleeping to receiving in order to confirm the close code 
08:18:27.594 DEBUG server - event = eof_received()
08:18:27.595 DEBUG server - event = connection_lost(None)                                                                                                                                                                          
08:18:27.595 DEBUG client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{...}', rsv1=False, rsv2=False, rsv3=False)               
08:18:27.595 DEBUG server - state = CLOSED                                                                                                                                                                                         
08:18:27.595 DEBUG client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{...}', rsv1=False, rsv2=False, rsv3=False)                                                                                                                                                                                                                                                      
08:18:27.595 DEBUG server x code = 1006, reason = [no reason]                                                                                                                                                                      
08:18:27.596 DEBUG client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{...}', rsv1=False, rsv2=False, rsv3=False)                
08:18:27.596 DEBUG server - aborted pending ping: 741aa44a                                                                                                                                                                         
08:18:27.596 DEBUG client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{...}', rsv1=False, rsv2=False, rsv3=False)    
# Multiple data frames omitted for brevity                                                                                                                                                                                                                                                  
08:18:27.599 DEBUG client < Frame(fin=True, opcode=<Opcode.TEXT: 1>, data=b'{...}', rsv1=False, rsv2=False, rsv3=False)
08:18:27.599 DEBUG client < Frame(fin=True, opcode=<Opcode.PING: 9>, data=b't\x1a\xa4J', rsv1=False, rsv2=False, rsv3=False)
08:18:27.599 DEBUG client - received ping, sending pong: 741aa44a
08:18:27.599 ERROR Error in data transfer
```

Digression: The `{side} {classification} {other}` pattern of the log messages is neat. I assume `<` and `>` are used for frames received and sent respectively. What are the remaining classifications?

**Comment by apljungquist** [comment]
Also w.r.t. this particular case I suspect either of these chunks could help

```diff
diff --git a/src/websockets/legacy/protocol.py b/src/websockets/legacy/protocol.py
index 4e8958b..92b16e2 100644
--- a/src/websockets/legacy/protocol.py
+++ b/src/websockets/legacy/protocol.py
@@ -692,7 +692,13 @@ class WebSocketCommonProtocol(asyncio.Protocol):
             connection is closed
 
         """
-        await self.ensure_open()
+        try:
+            await self.ensure_open()
+        except ConnectionClosedError:
+            # would allow/force app read all data frames waiting in buffers before raising.
+            # previously only the data frames preceding the ping frame would be read.
+            logger.debug("%s ! connection closed, skipping pong", self.side)
+            return 
 
         data = prepare_ctrl(data)
 
@@ -804,6 +810,10 @@ class WebSocketCommonProtocol(asyncio.Protocol):
             self.transfer_data_exc = exc
             self.fail_connection(1009)
 
+        except ConnectionClosedError as exc:
+            self.transfer_data_exc = exc
+            self.fail_connection(exc.code) # not sure if this makes sense
+
         except Exception as exc:
             # This shouldn't happen often because exceptions expected under
             # regular circumstances are handled above. If it does, consider

```

**Comment by aaugustin** [comment]
> what do you think about the idea that in general a lib (websockets) should communicate errors to the app and let the app decide about logging?

I think you missed inversion of control.

https://websockets.readthedocs.io/en/latest/howto/logging.html could bring some clarity. It's written for the master branch where I just reworked logging, but mostly applies to 9.x.

In fact this error falls under the "bug in websockets" category.

> Also w.r.t. this particular case I suspect either of these chunks could help

It doesn't seem right to skip a pong silently if the user of the library wants to send one, so I don't think that patch is acceptable.

However, I have a better idea. I will submit a PR.

**Comment by aaugustin** [comment]
Would you be able to see if #981 works for you? Make sure you remove `ping_timeout=None` before trying it. Thank you!

**Comment by aaugustin** [comment]
I'm pretty sure this came up before but I couldn't nail the root cause.

**Comment by apljungquist** [comment]
You are of course right, I did not factor in inversion of control. In any case, thank you for being patient and accommodating.

I expect the PR should resolve my problem and I agree it is better for the reason you point out. Will confirm on Monday.

**Comment by aaugustin** [comment]
Well thank you for taking the time to report this and narrowing down the problem.

I think the PR was an improvement anyway so I merged it.

If it doesn't fix your situation, let's reopen this issue and try again. Let me know how it goes :-)

**Comment by apljungquist** [comment]
Can confirm the PR solved my problem.

Unfortunately at 0779eb973d2779c33b560488212ea8b652601596 other problems exist, so I had to cherry pick. This may however be the fault of other libraries involved, such as uvicorn. Will try to make time to look closer at it and attribute to the correct package. In any case this issue can remain closed and I thank you for your help.

**Comment by aaugustin** [comment]
If you have a stack trace, I'm happy to take a look and tell you if websockets appears to be at fault.
