### ISSUE TITLE
Type hint contradicts code

### ISSUE THREAD

**Issue by apljungquist** [aaugustin/websockets#988]
The main branch of websockets and uvicorn interact poorly causing an AssertionError. Below is the relevant part of the stacktrace.

```text
Traceback (most recent call last):
  File "/***/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/***/uvicorn/uvicorn/protocols/http/httptools_impl.py", line 137, in data_received
    self.handle_upgrade()
  File "/***/uvicorn/uvicorn/protocols/http/httptools_impl.py", line 177, in handle_upgrade
    protocol = self.ws_protocol_class(
  File "/***/uvicorn/uvicorn/protocols/websockets/websockets_impl.py", line 62, in __init__
    super().__init__(
  File "/***/websockets/src/websockets/legacy/server.py", line 190, in __init__
    super().__init__(logger=logger, **kwargs)
  File "/***/websockets/src/websockets/legacy/protocol.py", line 148, in __init__
    assert loop is not None
AssertionError
```

I'm not sure if this would be best solved here or in uvicorn. Below are a few quick fixes that solves the problem but may or may not be good ideas.

If the loop retrieval is not changed in websockets then I think at least the type signature should be since the loop argument is currently marked as optional but shortly thereafter it is asserted that it `is not None`.

Related to this first suggestion I'm curious why `get_event_loop` was not replaced with `get_running_loop` straight away in [`WebsocketCommonProtocol`](https://github.com/aaugustin/websockets/commit/08d8011132ba038b3f6c4d591189b57af4c9f147#diff-3851a087134dc94d4edce57e405054b17b85aed1639b8f62f1a79ba582345c3fL136) as it was in `Connect`?
```diff
diff --git a/src/websockets/legacy/protocol.py b/src/websockets/legacy/protocol.py
index 353317a..9acb9b4 100644
--- a/src/websockets/legacy/protocol.py
+++ b/src/websockets/legacy/protocol.py
@@ -145,6 +145,13 @@ class WebSocketCommonProtocol(asyncio.Protocol):
         # Track if DEBUG is enabled. Shortcut logging calls if it isn't.
         self.debug = logger.isEnabledFor(logging.DEBUG)

+        if loop is None:
+            loop = asyncio.get_running_loop()
+
+        # Also works, but bakes in knowledge of dependant which does not feel right.
+        # if loop is None and hasattr(self, "loop"):
+        #     loop = self.loop
+
         assert loop is not None
         # Remove when dropping Python < 3.10 - use get_running_loop instead.
         self.loop = loop
```

```diff
diff --git a/uvicorn/protocols/websockets/websockets_impl.py b/uvicorn/protocols/websockets/websockets_impl.py
index f166f71..cc0d153 100644
--- a/uvicorn/protocols/websockets/websockets_impl.py
+++ b/uvicorn/protocols/websockets/websockets_impl.py
@@ -64,6 +64,7 @@ class WebSocketProtocol(websockets.WebSocketServerProtocol):
             ws_server=self.ws_server,
             extensions=[ServerPerMessageDeflateFactory()],
             max_size=self.config.ws_max_size,
+            loop=self.loop,
         )

     def connection_made(self, transport):
```

**Comment by aaugustin** [comment]
Nice catch -- probably we should make the same change here as I did in the client and the server, see https://github.com/aaugustin/websockets/commit/08d8011132ba038b3f6c4d591189b57af4c9f147#diff-4cdef9c9e58dd4489278768e7e5e71a928bc04f0b97817419c5904bcc9e58817 for example.

Background -- the following sequence of events happened in asyncio:

- originally it assumed there was only one event loop
- then it gained optional `loop` parameters in all APIs
- then these parameters were deprecated and, starting from Python 3.10, aren't supported anymore

websockets is following along but suffers from this API churn, and so do projects depending on websockets like univcorn.

#987 suggests that this may not suffice, but I wouldn't want to make such large changes just to allow uvicorn to deviate from the standard set by asyncio.

**Comment by apljungquist** [comment]
987 sounds a bit disconcerting but I honestly don't understand what the problem is (though admittedly I have not spend a lot of time trying to understand it). In any case, on python 3.9 and already released versions of uvicorn it seems this issue can be solved. In fact I gave it a try. I thought it would be easy to fix but in my attempt I ended up using lots of version branches which makes me a bit uneasy. If you feel like taking a look and it turns out to be a good direction I'd be happy to fix any outstanding issues.

**Comment by graingert** [comment]
uvicorn tests also instantiate this WebSocketCommonProtocol before an event loop is available. I think it should bind the loop as late as possible like the stdlib objects Lock and Event etc

**Comment by graingert** [comment]
>  but I wouldn't want to make such large changes just to allow uvicorn to deviate from the standard set by asyncio.

In https://github.com/aaugustin/websockets/pull/987 I was loosely following the design in the stdlib for late binding the loop to objects:

https://github.com/python/cpython/blob/2af690fdb26d0312de056b54ddb113d3c44dee8c/Lib/asyncio/mixins.py#L22-L31

**Comment by aaugustin** [comment]
It's annoying of the stdlib to adopt a pattern everywhere but hide its implementation in a private API :-/

**Comment by graingert** [comment]
@aaugustin the `            with _global_lock:` seems gratuitous

**Comment by aaugustin** [comment]
@apljungquist I made two changes:

- restructured the code to support initializing `WebSocketCommonProtocol` without a loop argument
- went back from `get_running_loop` to `get_event_loop` in constructors, because they aren't coroutines, so they may be invoked while no event loop is running

At this point:

- passing a `loop` argument triggers a `DeprecationWarning`
- passing a `loop` argument and not having a running loop triggers a `DeprecationWarning` — this one doesn't come from me, it comes from Python 3.10

**Comment by graingert** [comment]
> passing a loop argument and not having a running loop triggers a DeprecationWarning — this one doesn't come from me, it comes from Python 3.10

I want to be able to construct a WebSocketCommonProtocol without a loop - like `asyncio.Lock()`

**Comment by aaugustin** [comment]
You can do this. Just ignore the deprecation warning.

**Comment by aaugustin** [comment]
Since you won't do anything with `WebSocketCommonProtocol` without an event loop, I assume you have one nearby and you just want to be able to initialize a `WebSocketCommonProtocol` instance while the event loop isn't running because that would require a large refactoring.

You could also do this:

```python
async def init_WebSocketCommonProtocol(*args, **kwargs):
    return WebSocketCommonProtocol(*args, **kwargs)

protocol = loop.run_until_complete(init_WebSocketCommonProtocol(...))
```

**Comment by aaugustin** [comment]
In my own test suite, I chose to ignore the deprecation warning :-)

**Comment by graingert** [comment]
the deprecation warning is not so bad, the problem is the RuntimeError:

```
import asyncio
import websockets

async def foo():
    pass


asyncio.run(foo())


ws_client = websockets.WebSocketClientProtocol()
```

```python
Traceback (most recent call last):
  File "/home/graingert/projects/websockets/foo.py", line 11, in <module>
    ws_client = websockets.WebSocketClientProtocol()
  File "/home/graingert/projects/websockets/.tox/py310/lib/python3.10/site-packages/websockets/legacy/client.py", line 157, in __init__
    super().__init__(logger=logger, **kwargs)
  File "/home/graingert/projects/websockets/.tox/py310/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 129, in __init__
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by aaugustin** [comment]
If it weren't for `asyncio.run(foo())`, `ws_client = websockets.WebSocketClientProtocol()` would succeed. I assume you're aware of this behavior of `asyncio.run()` and that's the reason why you included it in your example.

So, another library, namely `asyncio`, changes the state of the Python process. Code that worked perfectly before `asyncio.run()` no longer works afterwards. This is 100% reproducible without involving websockets:

```python
>>> import asyncio
>>> asyncio.get_event_loop()  # succeeds
<stdin>:1: DeprecationWarning: There is no current event loop
<_UnixSelectorEventLoop running=False closed=False debug=False>
>>> async def foo(): pass
...
>>> asyncio.run(foo())
>>> asyncio.get_event_loop()  # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myk/.pyenv/versions/3.10-dev/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

----

The docs for `asyncio.run()` say:

> This function always creates a new event loop and closes it at the end. It should be used as a main entry point for asyncio programs, and should ideally only be called once.

which is a very mild way to say "create a new event loop and also stomp the default event loop and leave the interpreter in an unusable state until the user resets it".

----


You could report this bug against `asyncio`, and while waiting for a fix, I would suggest this workaround:

```python
asyncio.set_event_loop(asyncio.new_event_loop())
```

My testing suggests that this resets the Python process to a usable state. At least `ws_client = websockets.WebSocketClientProtocol()` succeeds again which should fix your immediate concern without requiring a large refactoring of websockets.

**Comment by apljungquist** [comment]
> @apljungquist I made two changes:
> ...

You know the best what is good for the package. I can confirm that my problem is resolved and I thank you for it.

The digression about binding to the loop seems orthogonal to this issue but it is nonetheless interesting to read. My experience is that creating asyncio primitives off the loop is a nice footgun to the point where I wonder if creating them outside an async function should be considered a code smell. As such I am not opposed to eager binding since it puts symptom and cause in the same place and it prevents fun race problems like locks and queues crashing only when there is contention :fearful:. Then again I expect there is/was a rationale behind the standard lib using the loop lazily.

**Comment by graingert** [comment]
> The digression about binding to the loop seems orthogonal to this issue but it is nonetheless interesting to read.

@aaugustin can you enable GitHub discussions or gitter.im for this project?

> As such I am not opposed to eager binding since it puts symptom and cause in the same place and it prevents fun race problems like locks and queues crashing only when there is contention 😨. Then again I expect there is/was a rationale behind the standard lib using the loop lazily.

I tend to use anyio where the anyio.Event and anyio.Lock etc cannot be constructed outside the loop because they otherwise don't know which type to make, so I'm used to this approach.

I'm not sure what the rational of the stdlib is here or why asyncio.Lock doesn't accept a loop but for StreamReader it's mandatory
