### ISSUE TITLE
websockets 9.1 crash on multiple simultaneous connections (with the server example code)

### ISSUE THREAD

**Issue by mailamauro888** [aaugustin/websockets#992]
I wish I could have about 3k connections at once, but when running the server I'm having a bad crash (on about 500 connections in Win 10 x64 and on about 1019 connections on Ubuntu).

Here is the **stresstestscript.py** wich cause the issue (even if I run this one in different machines over the lan):
`import websocket,time
serveraddr="ws://localhost:12345"
ws = websocket.WebSocket()
ws.connect(serveraddr)
list = []
for b in range(3000):
    list.append(websocket.WebSocket())
count=1
for x in  list:
    count+=1
    x.connect(serveraddr)
    time.sleep(0.01)
time.sleep(5000)
`

Here is the **server.py** (the exact sample on websockets official documentation):
`import asyncio
import json
import logging
import websockets

logging.basicConfig()

STATE = {"value": 0}

USERS = set()

def state_event():
    return json.dumps({"type": "state", **STATE})

def users_event():
    return json.dumps({"type": "users", "count": len(USERS)})

async def notify_state():
    if USERS:  # asyncio.wait doesn't accept an empty list
        message = state_event()
        await asyncio.wait([user.send(message) for user in USERS])

async def notify_users():
    if USERS:  # asyncio.wait doesn't accept an empty list
        message = users_event()
        await asyncio.wait([user.send(message) for user in USERS])

async def register(websocket):
    USERS.add(websocket)
    print("add")
    await notify_users()

async def unregister(websocket):
    USERS.remove(websocket)
    await notify_users()

async def counter(websocket, path):
    # register(websocket) sends user_event() to websocket
    await register(websocket)
    try:
        await websocket.send(state_event())
        async for message in websocket:
            data = json.loads(message)
            if data["action"] == "minus":
                STATE["value"] -= 1
                await notify_state()
            elif data["action"] == "plus":
                STATE["value"] += 1
                await notify_state()
            else:
                logging.error("unsupported event: %s", data)
    finally:
        await unregister(websocket)

start_server = websockets.serve(counter, "localhost", 12345)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()`

**Here is the crash** (on windows, when exceed the 500 connetions opened at once):
`Traceback (most recent call last):
  File "websockettestserver.py", line 70, in <module>
    asyncio.get_event_loop().run_forever()
  File "C:\Python37-32\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Python37-32\lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python37-32\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Python37-32\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()`

Like i said, I wish i could have more simultaneous connections, increasing the about 1000 connections on linux to 3000-4000 (!?). How to fix this? Thanks.

**Comment by lgrahl** [comment]
Sorry but that's not a websockets issue but a deployment/event loop issue (although it could be added to the docs, /cc @aaugustin). You can use the [`ProactorEventLoop`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) on Windows.

**Comment by mailamauro888** [comment]
> 
> 
> You can use the [`ProactorEventLoop`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) on Windows.
Thanks, but which solution on Unix systems?

**Comment by lgrahl** [comment]
You need to [raise the number of file descriptors](https://duckduckgo.com/?q=raise+number+of+file+descriptors&t=ffab&ia=web).

**Comment by aaugustin** [comment]
Sometimes I document these in the FAQ when it isn't obvious, but in this case putting the error message in Google goes straight to StackOverflow with the correct answer, so I think we're good.

**Comment by mailamauro888** [comment]
> 
> 
> You need to [raise the number of file descriptors](https://duckduckgo.com/?q=raise+number+of+file+descriptors&t=ffab&ia=web).
> 
> No disrespect intended but this is something you could have easily resolved yourself by just throwing in the error into a search engine.

I appreciate your hint, but I've already changed by ulimit the "Max open files" from 1024 to 4096 with the same result "ValueError: filedescriptor out of range in select()" with the same amount of open connections (about 1019). 
That's pretty strange to me, that's why I was here :)
Am I missing something?

cat /proc/$PID/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7755                 7755                 processes 
Max open files            4096                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7755                 7755                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

**Comment by lgrahl** [comment]
Sounds like asyncio is selecting the most basic selector loop on your machine based on the `select` syscall which does not support fds beyond 1023. See https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.SelectorEventLoop on how to change that.
