### ISSUE TITLE
What is the right way to get the full path of the request.

### ISSUE THREAD

**Issue by vaibhav-falconx** [aaugustin/websockets#994]
I am using websockets to run a server which caters to clients. The way it is setup, I run multiple instances of the code behind a load-balancer to allow for more HA. When a message is received from the client, I would like to get the entire path of the HTTP request that was used to create the connection. For example, if the client was connecting to the websocket using the URL : "wss://stream-vaibhav.com/ws", then I would like to get the full URL "stream-vaibhav.com/ws" in some way. 

How do I get this information? Is there a field in WebSocketServerProtocol that can help me get the entire path? 

Would be good to add this to the documentation as well.

**Comment by AmirHmZz** [comment]
Hello,
Have you tried the `host` header of handshake? You can access to `GET` handshake request's headers in your handler : 
```python
async def handler(proto, path):
    print(proto.request_headers.get("host", None)
    ...
```

**Comment by aaugustin** [comment]
Either it works like @AmirHmZz said, or you can configure your load balancer to add the original `Host` in the non-standard-but-widely-used `X-Forwarded-Host` header.
